import 'dart:convert';

import 'package:drift/drift.dart';

import '../local/app_database.dart';
import '../models/enums.dart';

/// Queue of outbound changes awaiting upload. Idempotent, retryable,
/// ordered by creation time.
class SyncRepository {
  SyncRepository(this._db);

  final AppDatabase _db;

  /// Enqueues a change. Coalesces identical pending operations for the same
  /// entity (create→update becomes a single latest update).
  Future<SyncQueueItem> enqueue({
    required String entityType,
    required String entityId,
    required SyncOperation operation,
    required Map<String, Object?> payload,
    String? idempotencyKey,
  }) async {
    final now = DateTime.now();
    final key =
        idempotencyKey ??
        '${entityType}.$entityId.${now.microsecondsSinceEpoch}';
    final id = '$entityType.$entityId.${now.microsecondsSinceEpoch}';

    final pending =
        await (_db.select(_db.syncQueueItems)..where(
              (tbl) =>
                  tbl.entityType.equals(entityType) &
                  tbl.entityId.equals(entityId) &
                  tbl.status.isIn([
                    SyncStatus.pending.name,
                    SyncStatus.failed.name,
                  ]),
            ))
            .get();

    if (pending.isNotEmpty) {
      final latest = pending.reduce(
        (a, b) => a.createdAt.isAfter(b.createdAt) ? a : b,
      );
      await (_db.update(
        _db.syncQueueItems,
      )..where((tbl) => tbl.id.equals(latest.id))).write(
        SyncQueueItemsCompanion(
          operation: Value(operation.name),
          payloadJson: Value(_encode(payload)),
          retryCount: const Value(0),
          idempotencyKey: Value(key),
          syncedAt: const Value(null),
          lastError: const Value(null),
        ),
      );
      return latest;
    }

    final row = SyncQueueItemsCompanion.insert(
      id: id,
      entityType: entityType,
      entityId: entityId,
      operation: operation.name,
      payloadJson: _encode(payload),
      status: SyncStatus.pending,
      idempotencyKey: key,
      createdAt: now,
    );
    await _db.into(_db.syncQueueItems).insert(row);
    return (_db.select(
      _db.syncQueueItems,
    )..where((tbl) => tbl.id.equals(id))).getSingle();
  }

  Future<List<SyncQueueItem>> pending() =>
      (_db.select(_db.syncQueueItems)
            ..where(
              (tbl) =>
                  tbl.status.isIn([
                    SyncStatus.pending.name,
                    SyncStatus.failed.name,
                  ]) &
                  tbl.retryCount.isSmallerThanValue(5),
            )
            ..orderBy([(tbl) => OrderingTerm.asc(tbl.createdAt)]))
          .get();

  Future<int> pendingCount() async => (await pending()).length;

  Future<void> markSyncing(List<String> ids) async {
    if (ids.isEmpty) return;
    await (_db.update(_db.syncQueueItems)..where((tbl) => tbl.id.isIn(ids)))
        .write(SyncQueueItemsCompanion(status: Value(SyncStatus.syncing)));
  }

  Future<void> markSynced(List<String> ids, {DateTime? at}) async {
    if (ids.isEmpty) return;
    await (_db.update(
      _db.syncQueueItems,
    )..where((tbl) => tbl.id.isIn(ids))).write(
      SyncQueueItemsCompanion(
        status: const Value(SyncStatus.synced),
        syncedAt: Value(at ?? DateTime.now()),
        lastError: const Value(null),
      ),
    );
  }

  /// Updates the payload of a queued item in place (med by [id]).
  Future<void> updatePayload(String id, Map<String, Object?> payload) async {
    await (_db.update(
      _db.syncQueueItems,
    )..where((tbl) => tbl.id.equals(id))).write(
      SyncQueueItemsCompanion(payloadJson: Value(_encode(payload))),
    );
  }

  /// Restores items that were being pushed back to `pending` after a transport
  /// failure so the next sync tick retries them.
  Future<void> markPending(List<String> ids) async {
    if (ids.isEmpty) return;
    await (_db.update(
      _db.syncQueueItems,
    )..where((tbl) => tbl.id.isIn(ids))).write(
      SyncQueueItemsCompanion(status: const Value(SyncStatus.pending)),
    );
  }

  Future<void> markFailed(SyncQueueItem item, String error) async {
    await (_db.update(
      _db.syncQueueItems,
    )..where((tbl) => tbl.id.equals(item.id))).write(
      SyncQueueItemsCompanion(
        status: const Value(SyncStatus.failed),
        retryCount: Value(item.retryCount + 1),
        lastError: Value(error),
      ),
    );
  }

  /// True when [idempotencyKey] has already been delivered by the server.
  /// Used to drop incoming duplicates before applying.
  Future<bool> isDelivered(String idempotencyKey) async {
    final count = await (_db.select(
      _db.syncQueueItems,
    )..where((tbl) => tbl.idempotencyKey.equals(idempotencyKey))).get();
    return count.any((e) => e.status == SyncStatus.synced);
  }

  /// Confirms a record generated by THIS device is already uploaded —
  /// used by `pull` so we do not re-apply our own writes.
  Future<bool> alreadyApplied(
    String entityType,
    String entityId, {
    String? operation,
  }) async {
    final query = _db.select(_db.syncQueueItems)
      ..where(
        (tbl) =>
            tbl.entityType.equals(entityType) & tbl.entityId.equals(entityId),
      );
    final rows = await query.get();
    if (operation != null) {
      return rows.any(
        (e) => e.operation == operation && e.status == SyncStatus.synced,
      );
    }
    return rows.isNotEmpty;
  }

  Future<void> removeDelivered() async {
    await (_db.delete(
      _db.syncQueueItems,
    )..where((tbl) => tbl.status.equals(SyncStatus.synced.name))).go();
  }

  static String _encode(Map<String, Object?> payload) =>
      const JsonCodec().encode(payload.map((k, v) => MapEntry(k, v)));
}
