import '../l10n_keys.dart';

/// Khasi dictionary (best-effort machine-assisted translation; native review required).
/// Core food-market terms corroborated against xobdo.org, Glosbe and Khasi blog lessons.
/// Untranslated keys automatically fall back to English.
const Map<String, String> stringsKha = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'U para jong phi ha ka jingkynmaw',
  L10nKeys.back: 'Shol',
  L10nKeys.next: 'Hadien',
  L10nKeys.continueText: 'Iaid hadien',
  L10nKeys.skip: 'Khla',
  L10nKeys.done: 'Lah',
  L10nKeys.cancel: 'Pynkut',
  L10nKeys.yes: 'Hooid',
  L10nKeys.no: 'Ym',
  L10nKeys.save: 'Sakhi',
  L10nKeys.close: 'Kyah',
  L10nKeys.retry: 'Pyrshang shisien',
  L10nKeys.add: 'Pynpaw',
  L10nKeys.edit: 'Kylla',
  L10nKeys.remove: 'Shim noh',
  L10nKeys.search: 'Wod',
  L10nKeys.today: 'Mynta sngi',
  L10nKeys.offline: 'Ym don internet',
  L10nKeys.online: 'Ha internet',

  L10nKeys.goodMorning: 'Khublei step',
  L10nKeys.goodAfternoon: 'Khublei',
  L10nKeys.goodEvening: 'Khublei miet',
  L10nKeys.goodNight: 'Miet bha',

  L10nKeys.navHome: 'Iing',
  L10nKeys.navGarden: 'Iing tyngka',
  L10nKeys.navActivities: 'Ki jingpyrshang',
  L10nKeys.navMemories: 'Ki jingkynmaw',
  L10nKeys.navProfile: 'Profile',
  L10nKeys.navMystery: 'Ka jingkynmaw mynta sngi',

  L10nKeys.onboardingWelcomeTitle: 'U para kaba sain ha ka jingkynmaw',
  L10nKeys.onboardingWelcomeBody: 'Companio iarap phi ban kynmaw, lem da ki jingpyrshang rit bad shem ia ki para — khlem internet.',
  L10nKeys.onboardingNameTitle: 'Kumno ngin khot ia phi?',
  L10nKeys.onboardingNameHint: 'Ka kyrteng jong phi',
  L10nKeys.onboardingRegionTitle: 'Ha shano ka iing jong phi?',
  L10nKeys.onboardingRegionHint: 'Ka shnong ne ka wah',
  L10nKeys.onboardingRegionList: 'Shillong, Guwahati, Jowai, Nongpoh, Cherrapunjee, Tura, Agartala, Imphal, Aizawl, Itanagar, Kohima, Dimapur, Gangtok, Dibrugarh, Jorhat',
  L10nKeys.onboardingLanguageTitle: 'Aiu ka kotlen jong phi halor?',
  L10nKeys.onboardingLanguageBody: 'Phi lah ban kylla noh haba phi mon.',
  L10nKeys.onboardingFamilyTitle: 'Uei ki para sha?',
  L10nKeys.onboardingFamilyBody: 'Pynpaw ia kito kiba phi ieit. Ngi shim ia ki jingjngai bad ki synteng jong ki kum ki jingkynmaw kiba sain.',
  L10nKeys.onboardingAddFamily: 'Pynpaw ia u briew iing',
  L10nKeys.onboardingEmergencyTitle: 'Haba don kam, uei ngin khot?',
  L10nKeys.onboardingEmergencyBody: 'Lada phi them ia ka button SOS, Companio kin khot ia ki para iing jong phi — ym ka jingsukai kaba bias boh.',
  L10nKeys.onboardingEmergencyName: 'Ka kyrteng',
  L10nKeys.onboardingEmergencyPhone: 'Ka number',
  L10nKeys.onboardingEmergencyRelation: 'Ka jingiadei (ka kynthei, u khun…)',
  L10nKeys.onboardingDoneTitle: 'Ka iing tyngka jong phi la pynkhreh!',
  L10nKeys.onboardingDoneBody: 'Pynjubab ia ki jingpyrshang rit bad peit ia ka iing tyngka kaba dang phu. Ngi don ryngkat ia phi.',
  L10nKeys.onboardingStart: 'Pynbit ia ka iing tyngka jong nga',

  L10nKeys.homeWhatsGrowing: 'Kaei kaba dang phu mynta?',
  L10nKeys.homeTodayActivity: 'Ka jingpyrshang rit mynta sngi',
  L10nKeys.homeActivityDuration: 'Habun 3 minit',
  L10nKeys.homeMinutes: 'minit',
  L10nKeys.homeMemoryOfDay: 'Ka jingkynmaw mynta sngi',
  L10nKeys.homeMemoryLocked: 'Kawei ka jingkynmaw kaba kyrpang ka dang ap…',
  L10nKeys.homeMemoryUnlocked: 'Ka jingkynmaw la plie!',
  L10nKeys.homeContinueActivity: 'Iaid hadien ia ka jingpyrshang',
  L10nKeys.homeFamilyMemory: 'Na ka iing jong phi',
  L10nKeys.homeFamilyMemoryEmpty: 'Ki jingkynmaw na ka iing kin paw hangne.',
  L10nKeys.homeSos: 'Nga donkam jingiarap',
  L10nKeys.homeSosSubtitle: 'Khot ia ki para iing haba don kam',
  L10nKeys.homeGardenPreview: 'Ka iing tyngka jong phi',
  L10nKeys.homeEngine: 'U para Companio',
  L10nKeys.homeEngineReady: 'U jingiarap jong phi la pynkhreh.',
  L10nKeys.homeWelcomeBack:
      'Leit phai! Ngin iad ia ka iing tyngka jong phi. 🌸',
  L10nKeys.homeNoActivity: 'Ym don jingpyrshang mynta sngi',
  L10nKeys.homeNoActivityBody:
      'Shong khoti — ne yot ia ka jingpyrshang kaba phi ieit. 🌻',

  L10nKeys.gardenTitle: 'Ka iing tyngka jingkynmaw jong nga',
  L10nKeys.gardenSectionAll: 'Baroh',
  L10nKeys.gardenSectionFamily: 'Iing',
  L10nKeys.gardenSectionChildhood: 'Ka jingphaneng',
  L10nKeys.gardenSectionPlaces: 'Ki jaka',
  L10nKeys.gardenSectionFestivals: 'Ki iawsnem',
  L10nKeys.gardenEmpty: 'Ka iing tyngka jong phi ka dang sdang',
  L10nKeys.gardenEmptyBody: 'Pynjubab ia ka jingpyrshang kaba nyngkong, hangne yn thung ia ka byrniah.',
  L10nKeys.gardenPoints: 'Ki point',
  L10nKeys.gardenLevel: 'Ka jrong',
  L10nKeys.gardenSeed: 'Ka byrniah',
  L10nKeys.gardenPlant: 'U diengrit',
  L10nKeys.gardenFlower: 'Ka phlur',
  L10nKeys.gardenTree: 'U dieng',
  L10nKeys.gardenMilestone: 'Ka dak',
  L10nKeys.gardenGrowth: 'Dang phu',
  L10nKeys.gardenDidYouKnow: 'Man la kawei ka jingpyrshang kaba pynjubab, ka iing tyngka jong phi ka phu.',
  L10nKeys.gardenPlantSeed: 'Thung ia ka byrniah',

  L10nKeys.activitiesTitle: 'Ki jingpyrshang',
  L10nKeys.activitiesToday: 'Mynta sngi',
  L10nKeys.activitiesLibrary: 'Ki jingpyrshang bathymmai',
  L10nKeys.mainGamesTitle: 'Ki shad bakynta',
  L10nKeys.activitiesStart: 'Sdang',
  L10nKeys.activitiesCompleted: 'La leh',
  L10nKeys.activitiesInProgress: 'Dang iaid',
  L10nKeys.activitiesNotStarted: 'La pynkhreh',
  L10nKeys.activityYoureDone: 'Bha tam!',
  L10nKeys.activityPraise: 'Phi la ai jingim rit ha ka iing tyngka. 🌱',
  L10nKeys.activityHint: 'Donkam bunoh?',
  L10nKeys.activityTryAgain: 'To ngi peit biang ia kane jingkynmaw',
  L10nKeys.activityOptionsHint: 'Yot ia ka jubab',
  L10nKeys.activityTapToMatch: 'To ngin sarud na ka bynta ka jingiasaid',
  L10nKeys.activityNext: 'Hadien',
  L10nKeys.activityFinish: 'Lah',
  L10nKeys.activityGroupLetsAgain: 'To ngi peit biang',
  L10nKeys.activityGroupTogether: 'To ngi leh kane lang',
  L10nKeys.activityGreatJob: 'Kam bha!',
  L10nKeys.activityKitchen: 'Ka iing sah jong nga',
  L10nKeys.activityShopping: 'Ka bazar jong nga',
  L10nKeys.activityMatching: 'Sarud',
  L10nKeys.activitySequence: 'Ban jriah kan kram',
  L10nKeys.activityRecognition: 'Kaei kane?',
  L10nKeys.activityAssociation: 'Kaei ba iasoh lang?',
  L10nKeys.activityRecall: 'Phi kynmaw?',
  L10nKeys.activityAttention: 'Wod',
  L10nKeys.activityDurationSuffix: 'minit',
  L10nKeys.activityTodayDone: 'Ka jingpyrshang mynta sngi la pynjubab',
  L10nKeys.activityTodayDoneBody:
      'Ka iing tyngka jong phi la phu. Lashisien dyng kawej ka jingkynmaw.',
  L10nKeys.activityGardenGrew: 'Ka iing tyngka jong phi la phu!',
  L10nKeys.activityMemoryUnlocked: 'Ka jingkynmaw la plie',
  L10nKeys.activityReadAloud: 'Pule da ka ktien kaba jrong',

  L10nKeys.kitchenTitle: 'To ngin shna sha',
  L10nKeys.kitchenMakeChai: 'Shna ja',
  L10nKeys.kitchenMakeChaiPrompt: 'Yot ia ki kam ha ka kram kaba biang.',
  L10nKeys.kitchenSteps: 'Ki kam',
  L10nKeys.kitchenTapInOrder: 'Yot ia ki kam ha ka kram kaba biang',
  L10nKeys.kitchenCorrectOrder: 'Bha tam! Ka sha la thep!',
  L10nKeys.kitchenBreakfast: 'Shna ia ka sngi shisong seingkap',
  L10nKeys.kitchenBreakfastHint: 'Ka jingsdang kaba bha ia ka sngi',
  L10nKeys.kitchenBreakfastPrompt:
      'Jriah ia ki kam shna ka sngi shisong. ha ka kram.',

  L10nKeys.shopTitle: 'Ka bazar jong nga',
  L10nKeys.shopGetMilkBread: 'U ruti bad ka dud',
  L10nKeys.shopGetMilkBreadPrompt: 'Shon u ruti bad ka dud ha ₹100.',
  L10nKeys.shopBudget: 'Ka jingbatshi',
  L10nKeys.shopBasket: 'Ka kubli jong phi',
  L10nKeys.shopTotal: 'Baroh',
  L10nKeys.shopWithinBudget: 'Ha ka jingbatshi!',
  L10nKeys.shopOverBudget: 'Lait ban ia ka jingbatshi — peit biang',
  L10nKeys.shopCheckout: 'Shadien noh',
  L10nKeys.shopBuy: 'Buhte lem ha ka kubli',
  L10nKeys.shopSell: 'Buhte noh',
  L10nKeys.shopVeggies: 'Thymmai ia ka miet sngewbha',
  L10nKeys.shopVeggiesPrompt: 'Shon ia ki sohsaw bad ki piat ha ₹60.',
  L10nKeys.recKitchenItem: 'Kaei kane?',
  L10nKeys.recKitchenItemPrompt:
      'Kaei kaba phi pyndonkam haba wan shon na ka bazar?',
  L10nKeys.recCurrency: 'Sarud ia ka pisa',
  L10nKeys.recCurrencyPrompt: 'Kaei ka note ₹20?',
  L10nKeys.matchFestival: 'Sarud ia ki iawsnem',
  L10nKeys.matchFestivalPrompt:
      'Sarud ia uwei uwei iawsnem bad ka jingjinggan kaba kyrpang.',
  L10nKeys.matchObjectUse: 'Sarud',
  L10nKeys.matchObjectUsePrompt:
      'Sarud ia kawei kawei ka buh bad ka jingpyndonkam.',
  L10nKeys.seqMorning: 'Ka jingiaid step',
  L10nKeys.seqMorningPrompt: 'Jriah ia ka jingiaid step jong phi ha ka kram.',
  L10nKeys.seqRoute: 'Ka jingiaid step',
  L10nKeys.seqRoutePrompt: 'Jriah ia ka jingiaid sha ka bazar ha ka kram.',
  L10nKeys.assoRegion: 'Kaei hangne?',
  L10nKeys.assoRegionPrompt: 'Kaei kaba bha tam ha ka Assam?',
  L10nKeys.assoHarvest: 'Ka compound bah',
  L10nKeys.assoHarvestPrompt: 'Kaei ka compound kaba ia khot ia u Soh?',
  L10nKeys.attnVeg: 'Wod ia ka kajor',
  L10nKeys.attnVegPrompt: 'Phi lah ban shem ia ka kajor?',
  L10nKeys.recallSong: 'Ka jingrwai kaba phi tip',
  L10nKeys.recallSongPrompt: 'Ka jingrwai aiu kaba ia kem ha ka Bihu?',
  L10nKeys.activityPairs: 'Wad ia ka para',
  L10nKeys.activitySequenceRecall: 'Kynmaw pat ia ka rukom',
  L10nKeys.activityFindChanged: 'Aiu ba la kylla?',
  L10nKeys.pairsFruits: 'Ki soh ka Iew',
  L10nKeys.pairsKitchen: 'Ki jaiñjuh ka kut',
  L10nKeys.pairsRemember:
      'Peit bha ia ki karta, te wad ia ka para kaba ia shim.',
  L10nKeys.pairsStart: 'Thied noh ia ki karta bad sdang',
  L10nKeys.pairsFound: 'La shim ia ka para!',
  L10nKeys.seqRecallItems: 'Ki jaiñjuh man ba pynban',
  L10nKeys.seqRecallNumbers: 'Ki jingbun ha ka rukom',
  L10nKeys.seqRecallWatch: 'Peit bha ia ki karta – uwei uwei u sa pynshein.',
  L10nKeys.seqRecallRepeat:
      'Mynhynnip tap ia ki karta kat kum ka rukom ba la iohi.',
  L10nKeys.changeMarket: 'Ka shayong ki soh',
  L10nKeys.changeFestival: 'Ki kyntah ka jingïapngi',
  L10nKeys.changeRemember: 'Kynmaw bha ia kine ki phixa.',
  L10nKeys.changeFind: 'Uwei u phixa u la kylla. Wad ia uba pher.',
  L10nKeys.changeCorrect: 'Manshah! Uta u la kylla.',

  L10nKeys.mysteryTitle: 'Ka jingkynmaw kyrpang mynta sngi',
  L10nKeys.mysteryLocked: 'Kawei ka jingkynmaw kyrpang ka dang ap ia phi…',
  L10nKeys.mysteryLockedBody: 'Leh 2–3 jingpyrshang rit mynta sngi; hynrei sngewtynnyng, ka lah ban plie. Kaei ea?',
  L10nKeys.mysteryUnlocked: 'Ka jingkynmaw kyrpang jong phi hangne!',
  L10nKeys.mysteryUnlockedBody:
      'Kane ka jingkynmaw ka dei ka jong phi hi. Shim ka por. 🌸',
  L10nKeys.mysteryCuriosity: 'Kaei ban plie mynta sngi?',
  L10nKeys.mysteryOpen: 'Plie ia ka jingkynmaw',

  L10nKeys.memoriesTitle: 'Ki jingkynmaw jong nga',
  L10nKeys.memoriesEmpty: 'Hyndai kim pat don jingkynmaw',
  L10nKeys.memoriesEmptyBody: 'Ki para iing jong phi lah ban thêm ia ki jingjngai bad ki synteng. Kan paw hangne katba la thaw.',
  L10nKeys.memoriesFamily: 'Iing',
  L10nKeys.memoriesPlaces: 'Ki jaka',
  L10nKeys.memoriesFestivals: 'Ki iawsnem',
  L10nKeys.memoriesChildhood: 'Ka jingphaneng',
  L10nKeys.memoriesKindPhoto: 'Jingjngai',
  L10nKeys.memoriesKindVoice: 'Synteng loudspeaker',
  L10nKeys.memoriesKindText: 'Jingkham',
  L10nKeys.memoriesKindSound: 'Ka jingpyrta',
  L10nKeys.memoriesKindPlace: 'Jaka',
  L10nKeys.memoriesAddedBy: 'Thêm na',
  L10nKeys.memoriesWhoIsThis: 'Uei uta?',
  L10nKeys.memoriesPlayVoice: 'Pyntud',
  L10nKeys.memoriesThisIsMe: 'Ma nga',
  L10nKeys.memoriesNotMe: 'Ym ma nga',

  L10nKeys.profileTitle: 'Profile',
  L10nKeys.profileLanguage: 'Ka kotlen app',
  L10nKeys.profileRegion: 'Ka wah jong nga',
  L10nKeys.profileVoiceLanguage: 'Ka kotlen jingpwaiñ',
  L10nKeys.profileVoicePrompts:
      'Ki jingkynmaw kiba la pyniatrei ha ka jingpwaiñ',
  L10nKeys.profileTextSize: 'Ka jrong jong ka kot',
  L10nKeys.profileReducedMotion: 'Ka jingiaid kaba sain',
  L10nKeys.profileSoundEffects: 'Ki jingpyrta',
  L10nKeys.profileFamily: 'Iing',
  L10nKeys.profileContacts: 'Ki number huhai',
  L10nKeys.profileDemoMode: 'Mode demo',
  L10nKeys.profileReminders: 'Ki jingkynmaw sngi',
  L10nKeys.profileNeedHelp: 'Donkam jingiarap?',

  L10nKeys.remindersTitle: 'Ki jingkynmaw sngi',
  L10nKeys.remindersEmpty: 'Hyndai kim pat don jingkynmaw sngi',
  L10nKeys.remindersNew: 'Jingkynmaw sngi bathymmai',
  L10nKeys.remindersTitleLabel: 'Ka kyrteng',
  L10nKeys.remindersDetailLabel: 'Ka jingkham (jm lah)',
  L10nKeys.remindersTime: 'Ka por',
  L10nKeys.remindersDays: 'Ki sngi',
  L10nKeys.remindersEveryday: 'Man la ka sngi',
  L10nKeys.remindersEnabled: 'La sain',
  L10nKeys.remindersMedicine: 'Dawai',
  L10nKeys.remindersAppointment: 'Jingiasoh bad u doktor',
  L10nKeys.remindersRoutine: 'Jingiaid step',

  L10nKeys.dayMon: 'Hima',
  L10nKeys.dayTue: 'Syngkai',
  L10nKeys.dayWed: 'Thyrbai',
  L10nKeys.dayThu: 'Mluh',
  L10nKeys.dayFri: 'Smphluh',
  L10nKeys.daySat: 'Snympai',
  L10nKeys.daySun: 'Jingkwai',

  L10nKeys.sosTitle: 'Jingiarap huhai',
  L10nKeys.sosExplain: 'Ban buhte. Companio kin khot ia ki number huhai jong phi, uwei uwei. Ym ka service huhai (kum 112).',
  L10nKeys.sosHold: 'Buhte sha ka jingiarap',
  L10nKeys.sosHoldBody: 'Buhte ia ka button…',
  L10nKeys.sosActiveTitle: 'Khot ia ka jingiarap',
  L10nKeys.sosActiveBody: 'La khot ia ki para iing jong phi. Lada ym ju jubab, ngin khot hadien ia uwei uwei.',
  L10nKeys.sosContacting: 'Dang khot',
  L10nKeys.sosContactFamily: 'Khot ia ki para iing',
  L10nKeys.sosContacted: 'La khot',
  L10nKeys.sosWaitingResponse: 'Dang ap ka jubab…',
  L10nKeys.sosEscalating: 'Khot ia uwei uwei…',
  L10nKeys.sosCancelled: 'La pynkut ia ka jingiarap',
  L10nKeys.sosCancelAction: 'Pynkut ia ka jingiarap',
  L10nKeys.sosDone: 'Lah',
  L10nKeys.sosHelpOnWay: 'Uei uei la wan ha ka jaka jong phi. 🧡',
  L10nKeys.sosNoContacts: 'Hyndai kim pat don number huhai',
  L10nKeys.sosNoContactsBody:
      'Woichah, ong sha ki para iing ba kin thêm ia ka number huhai.',
  L10nKeys.sosAddContact: 'Thêm ia ka number',
  L10nKeys.sosDisclaimer: 'Companio kin khot ia ki number kiba phi la xka. Ym ka service huhai kaba bias.',
  L10nKeys.sosContactedPerson: 'La khot ia u briew iing',
  L10nKeys.sosEscalatedTo: 'La khot ia uwei uwei lum iing',
  L10nKeys.sosAcknowledged: 'U briew iing la jubab. Jingiarap ka la wan.',
  L10nKeys.sosNotSilent: 'Ngim ju ai jingtrei shuh lada ngim lah ban phah.',
  L10nKeys.sosAlertNotDelivered: 'Ka khubor jong phi khyndiat; ngim lah ban phah khyndilot. Ngin pyrshang biang.',

  L10nKeys.careTitle: 'U nonghiarap',
  L10nKeys.careDashboard: 'Ka jingjriah',
  L10nKeys.carePatients: 'Ki briew iing jong nga',
  L10nKeys.careMemories: 'Ki jingkynmaw',
  L10nKeys.careContacts: 'Ki number huhai',
  L10nKeys.careSettings: 'Ki jingpynbeit',
  L10nKeys.careAddMemory: 'Thêm ia ka jingkynmaw',
  L10nKeys.careAddContact: 'Thêm ia ka number',
  L10nKeys.careEngagement: 'Jingpynsah',
  L10nKeys.careActivitiesWeek: 'Ki jingpyrshang palta',
  L10nKeys.careGardenProgress: 'Ka jingphu ka iing tyngka',
  L10nKeys.careRecentActivity: 'Ki jingpyrshang bakan',
  L10nKeys.careNoPatients: 'Hyndai kim pat don briew iing',
  L10nKeys.careNoPatientsBody: 'Khot ia u briew iing ba un lah pynieng, ne thêm ia ka profile briew. Ngin iarap.',
  L10nKeys.careAddPatient: 'Thêm ia u briew',
  L10nKeys.carePerformanceNote: 'kane briew ka jingpyndonkam khyndiat; ka jingiaid kaba dang mynnor ha kane ka sngi.',
  L10nKeys.careUploadPhoto: 'Chat ia ka jingjngai',
  L10nKeys.careRecordVoice: 'Rekhot ia ka synteng',
  L10nKeys.careWriteMemory: 'Thow ia ka jingkynmaw',
  L10nKeys.careMemoryTitle: 'Ka kyrteng',
  L10nKeys.careMemoryCaption: 'Ka caption',
  L10nKeys.careMemoryRelation: 'Uei uhap? (ka jingiadei)',
  L10nKeys.careMemoryCategory: 'Ka baw',
  L10nKeys.careContactName: 'Ka kyrteng',
  L10nKeys.careContactPhone: 'Ka number',
  L10nKeys.careContactPriority: 'Ka jingjriah ka khot',
  L10nKeys.careContactRelation: 'Ka jingiadei',
  L10nKeys.careEscalationTimeout: 'Kiba ki minit shwa uwei uwei',
  L10nKeys.careIncidentStatus: 'Ka jaka',
  L10nKeys.careAckSos: 'Nga dang jubab',
  L10nKeys.careResponding: 'Dang jubab',
  L10nKeys.careActiveAlerts: 'Ki khubor huhai kiba dang don',

  L10nKeys.syncSavingOffline: 'Kha-long',
  L10nKeys.syncSavingOfflineBody:
      'Ki jingpyrshang jong phi la sakhi hangne ha kane ka device.',
  L10nKeys.syncSynced: 'La jubab',
  L10nKeys.syncInfo: 'Ka jingkynmaw jong phi la jubab.',
  L10nKeys.syncPending: 'Dang ap ia ka jubab',

  L10nKeys.errorGeneric: 'Kaei kaei ka la mih ia ka jong ka jinghikai',
  L10nKeys.errorGenericBody:
      'Ka jingpyllait jong phi ka sain. Pyrshang biang, jej.',
  L10nKeys.errorAudio: 'Ym lah ban pyntud ia ka synteng ha kane device.',
  L10nKeys.errorPermission: 'Kane ka donkam ia ka jingpynshah jong ka device.',
  L10nKeys.errorNoInternetAction:
      'Ym donkam internet — kane ka thap ha NER ka jaka sain.',

  L10nKeys.demoWelcome: 'Peit ia ka demo',
  L10nKeys.demoExplain: 'Ngin thêm ia kawei ka iing bad ki jingkynmaw kum ki nongrêd, ba phi lah ban peit.',
  L10nKeys.demoLoad: 'Chat ia ka iing tyngka demo',

  L10nKeys.unitsPoints: 'Ki point',
  L10nKeys.teaserChai: 'To ngin shna sha.',
  L10nKeys.familiarityName: 'Ka Iba',
  L10nKeys.regionMap: 'Ka wah jong nga',
  L10nKeys.regionChoose: 'Xka ia ka wah jong phi',
  L10nKeys.regionIndia: 'India',
  L10nKeys.importantMemory: 'Ka jingkynmaw kaba kyrpang',
  L10nKeys.growing: 'Dang phu',
  L10nKeys.blooming: 'Dang pyllait',
  L10nKeys.mature: 'La kloi',
  L10nKeys.noVoice: 'Ym don jingpwaiñ ha kane device.',
  L10nKeys.optional: 'Ym donkam shisha',

  L10nKeys.langChoose: 'Xka ia ka kotlen',
  L10nKeys.langPrimary: 'Kaba bias',
  L10nKeys.langNorthEast: 'NE India',
  L10nKeys.langMajor: 'Ki kotlen kiba don ha India',

  L10nKeys.authSignUpTitle: 'Thaw ia ka account jong phi',
  L10nKeys.authSignUpBody: 'Kane ka profile Companio ka sakhi ha ka device jong phi hi. Ai ia ka kyrteng bad ka password ba phi hi ban kop ia ka.',
  L10nKeys.authLoginTitle: 'Leit phai kaba sain',
  L10nKeys.authLoginBody: 'Sign in ryngkat ia ka kyrteng bad ka password sha ka iing tyngka jong phi.',
  L10nKeys.authUsername: 'Ka kyrteng account',
  L10nKeys.authUsernameHint: 'Kum: ranu123',
  L10nKeys.authDisplayName: 'Ka kyrteng jong phi',
  L10nKeys.authPassword: 'Ka password',
  L10nKeys.authPasswordHint: 'Khyndai 6 kut',
  L10nKeys.authConfirmPassword: 'Paw shisien ia ka password',
  L10nKeys.authRoleQuestion: 'Kaei kane profile ka byrniah kiei…',
  L10nKeys.authRolePatient: 'Jong nga hi',
  L10nKeys.authRoleCaregiver: 'Jong u briew iing',
  L10nKeys.authCreate: 'Thaw ia ka account',
  L10nKeys.authSignIn: 'Sign in',
  L10nKeys.authSignOut: 'Sign out',
  L10nKeys.authAccount: 'Ka account',
  L10nKeys.caregiverTitle: 'Caregiver',
  L10nKeys.caregiverNotLinked: 'No caregiver linked yet',
  L10nKeys.authBadCredentials: 'Ka kyrteng ne ka password ka bym biang.',
  L10nKeys.authUsernameTaken: 'Kane ka kyrteng la pyndonkam ha kane device.',
  L10nKeys.authPasswordMismatch: 'Ki password kim iasoh.',
  L10nKeys.authUsernameShort: 'Ka kyrteng dey khamtam 3 kut.',
  L10nKeys.authUsernameInvalid:
      'Pyndonkam tang ia ki letter, number, dot, dash ne underscore.',
  L10nKeys.authPasswordShort: 'Ka password dey khamtam 6 kut.',
  L10nKeys.authNameRequired: 'Lah-indicate ia ka kyrteng.',
  L10nKeys.authSignOutConfirm: 'Phi mon ban sign out na kane profile?',
  L10nKeys.screenTitle: 'Shim khut ka jingbishar jong ka jingkynmaw',
  L10nKeys.screenIntro: 'Ngin kylli katto katne ki jingkylli shaphang uta u nongpang. Pyrkhat kumno u long ha kine katto katne ki bnai ba la leit.',
  L10nKeys.screenNotSure: 'Ngam thuh',
  L10nKeys.screenFinish: 'Peit ia ka jingbishar jong nga',
  L10nKeys.screenSkip: 'Shahrieh kaba ym pat long',
  L10nKeys.screenResultBack: 'Lypa',
  L10nKeys.screenCheckAgain: 'Bishar biang',
  L10nKeys.screenStartCheckup: 'Shim khut ia ka jingbishar',
  L10nKeys.screenSkipped: 'La shahrieh ka jingbishar',
  L10nKeys.screenStatusGood: 'Baroh ka long kaba bha',
  L10nKeys.screenStatusGoodBody: 'Ym don ei ei kaba khuslai. Bha katba phin iai leh ia ki kam man ka sngi — lada don eiei kaba pynkylla, phin lah ban bishar biang ha ka por aiu ruh.',
  L10nKeys.screenStatusWatch: 'Ia khyndiat ka jingpynkylla la iohi',
  L10nKeys.screenStatusWatchBody: 'Ia khyndiat ka por ba la klet la iohi. Kane ka long kaba kham bha haba phin san, hynrei peit bha bad batai sha u doctor ha ka por ba phin leit biang.',
  L10nKeys.screenStatusDoctor: 'Wat leit sha ka jingbishar',
  L10nKeys.screenStatusDoctorBody: 'Ia bun jingpynpynkylla la iohi kiba lah ban donkam jingaiar. Batai sha u doctor ne ka hospital khnang ba kin iarap ia phi.',
  L10nKeys.screenRarely: 'Khyndiat',
  L10nKeys.screenSometimes: 'La khyndiat ka por',
  L10nKeys.screenFrequently: 'Shibun',
  L10nKeys.screenVeryFrequently: 'Shibun shibun',
  L10nKeys.screenQ01:
      'Hato u don jingeh ban kynmaw ia ki jingjia kiba dang mynta?',
  L10nKeys.screenQ02: 'Hato u pynphai biang ia ki jingkylli ne ki ktien?',
  L10nKeys.screenQ03: 'Hato u klet ia ki kyrteng ki briew kiba ithuh?',
  L10nKeys.screenQ04: 'Hato u don jingeh ban ithuh ia ki khmat kiba ithuh?',
  L10nKeys.screenQ05:
      'Hato u klet ia ki por kiba ngeit ne ki jingjia kibam donkam?',
  L10nKeys.screenQ06: 'Hato u don jingeh ban shem ia ki ktien kiba biang?',
  L10nKeys.screenQ07: 'Hato u da shah juk ia ka jaka ba u long?',
  L10nKeys.screenQ08: 'Hato u donkam ia kiba jur bad ki kam man ka sngi?',
  L10nKeys.screenQ09: 'Hato u don jingeh ban pynbeit ia ki dawai?',
  L10nKeys.screenQ10: 'Hato u da sngewsi ne sngewbha haba u shah juk?',
  L10nKeys.screenQ11: 'Hato u don jingeh ban sngewthuh ia ki jingiathuhkhana?',
  L10nKeys.screenQ12: 'Hato u don jingeh ban pyndep ia ki kam kiba ithuh?',
  L10nKeys.screenQ13:
      'Hato u klet ha kaba la pynsa ia ki jingkyndon man ka sngi?',
  L10nKeys.screenQ14: 'Hato u don jingeh ban kynmaw ia ki jingkynshew?',
  L10nKeys.screenQ15:
      'Hato u don jingeh ban leh ia ki kam kiba kham bun jingbuid?',

  L10nKeys.careDashboardSubtitle: 'Family care',
  L10nKeys.careSosLive: 'Live alert',
  L10nKeys.careSosRespondedBy: 'Responded by {name}',
  L10nKeys.careLinkTitle: 'Connect to a family member',
  L10nKeys.careLinkBody: 'Ask your loved one for the 6-letter family code shown on their phone, then connect.',
  L10nKeys.careLinkCode: 'Family code',
  L10nKeys.careLinkCodeHint: 'e.g. A1B2C3',
  L10nKeys.careLinkConnect: 'Connect',
  L10nKeys.careLinkDone: 'Connected',
  L10nKeys.careLinkSuccess:
      'Linked to {name}! Memories and alerts will now sync.',
  L10nKeys.careLinkFailed:
      'Could not connect. Please check the code and try again.',
  L10nKeys.careTrendsTitle: 'AI trends',
  L10nKeys.careTrendsBody: 'Daily accuracy by activity type',
  L10nKeys.careTrendsNoData:
      'No activity yet — complete an exercise to see trends.',
  L10nKeys.careAiDifficulty: 'Auto-tuned difficulty',
  L10nKeys.careAiAccuracy: 'Model accuracy',
  L10nKeys.careAiRealSessions: 'Real sessions',
  L10nKeys.careAiDemoSessions: 'Demo sessions',
  L10nKeys.careNavGames: 'Ki Kham',
  L10nKeys.careNavRoutine: 'Ka Rutin',
  L10nKeys.careGreetSubtitle: 'Kane ka pyni mynta kumno u {name} u dang im.',
  L10nKeys.careNotifEmpty: 'Ym don jingbthah thymmai',
  L10nKeys.careWellnessScore: 'Ka Suba jong ka Jingtip',
  L10nKeys.careStatusStable: 'Sbat',
  L10nKeys.careStatusAttention: 'Ka donkam jingaiar',
  L10nKeys.careLastSynced: 'La synk ia ka sien {time}',
  L10nKeys.careMinAgo: '{n} min ba la leit noh',
  L10nKeys.careGamesWeek: 'Ki kham ha kane ka taiew',
  L10nKeys.careRoutineCompletion: 'La pyndep ka rutin',
  L10nKeys.careCurrentStreak: 'Ka jrong kaba mynta',
  L10nKeys.careMoodCheckins: 'Ka jinget jingkhein ka mynsiem',
  L10nKeys.careDayUnit: 'sngi',
  L10nKeys.careDaysUnit: 'ki sngi',
  L10nKeys.careActivityTitle: 'Ka jingtrei ha kane ka taiew',
  L10nKeys.careWeekly: 'Ha ka taiew',
  L10nKeys.careMonthly: 'Ha ka bnai',
  L10nKeys.careNoActivityWeek:
      'Shuh shuh ka jingtrei ym don mynta ha kane ka taiew.',
  L10nKeys.careMoodTitle: 'Ka Mynsiem',
  L10nKeys.careMoodHappy: 'Kmen',
  L10nKeys.careMoodCalm: 'Tlot',
  L10nKeys.careMoodNeutral: 'Shohmynta',
  L10nKeys.careMoodLow: 'Thut',
  L10nKeys.careMood7Days: 'Ki 7 sngi ba la leit',
  L10nKeys.careMoodInsight: 'U {name} u dang shong tlot ha kane ka taiew, hynrei da khyndiat ba jar ha ki ar sngi kiba khatduh.',
  L10nKeys.careMoodNoData:
      'Ym don ka jinget jingkhein ka mynsiem ha kane ka taiew.',
  L10nKeys.careSkillsTitle: 'Ki Jingtip',
  L10nKeys.careSkillMemory: 'Ka Kynmaw',
  L10nKeys.careSkillAttention: 'Ka Jingaiar',
  L10nKeys.careSkillLanguage: 'Ka Jongktien',
  L10nKeys.careSkillReasoning: 'Ka Jingpyrkhat',
  L10nKeys.careSkillProcessing: 'Ka Jakmoid jong ka jingleh',
  L10nKeys.careInsightToday: 'Ka jingtip mynta',
  L10nKeys.careInsightBody: 'U Robert u la ioh jah ka jingleh ha ka jingkynmaw hadien ka rutin jong u ha step. Ka mynsiem jong u ka dang thut khyndiat ha ki ar sngi ba la leit noh.',
  L10nKeys.careInsightBodyReal: 'Ha kane ka taiew u {name} u la pyndep {count} ki kam jong ka jingtip ({goal} ka jingpyrkhat) bad u la bat ka jrong {streak} sngi.',
  L10nKeys.careViewDetails: 'Peit ia ka kot',
  L10nKeys.careInsightDisclaimer: 'Kane ka long ka jingpyntip slem na ka data — ym da ka jingpynjot ba iaidibit.',
  L10nKeys.careAttentionTitle: 'Ka donkam ka jingaiar jong me',
  L10nKeys.careAttentionEmpty:
      'Ym don kaei kaei kaba donkam ka jingaiar mynta.',
  L10nKeys.careAlertSos: 'U {name} u la joh ia ka button SOS',
  L10nKeys.careAlertRoutineMissed: 'La jah noh ka rutin ha ka step',
  L10nKeys.careAlertMoodDown:
      'Ka mynsiem ka la thut ha ki ar sngi ba la leit noh',
  L10nKeys.careAlertSessionPending:
      'Ym shong noh ka session jong ka jingtip mynta',
  L10nKeys.careAlertSeverityHigh: 'Khraw',
  L10nKeys.careAlertSeverityMedium: 'Khamtam',
  L10nKeys.careAlertSeverityLow: 'Rit',
  L10nKeys.careWeeklySummary: 'Ka jingbatai ha kane ka taiew',
  L10nKeys.careSessionsCompleted: 'Ki session ba la pyndep',
  L10nKeys.careAvgSessionDuration: 'Ka jingring ka sredsien ka session',
  L10nKeys.careRoutineAdherence: 'Ka jingbud ka rutin',
  L10nKeys.careMoodTrend: 'Ka jingpang bad ka jingthut ka mynsiem',
  L10nKeys.careMoodTrendSlightlyDown: 'Thut khyndiat',
  L10nKeys.careMoodTrendStable: 'Sbat',
  L10nKeys.careMoodTrendUp: 'Kiew thiah',
  L10nKeys.careVsLastWeek: 'Ia ka taiew ba leit noh',
  L10nKeys.careSyncedJustNow: 'La sync mynta lyngba',
  L10nKeys.careOfflineWaiting:
      'Ia khlieh shemphang · {count} ki jingleh ki ap ban sync',
  L10nKeys.careComingSoon: 'Ka jingwan mynta',
  L10nKeys.careHomeSoon:
      'Ka jingpeit slem jong ka sngi u {name} kan paw hangne.',
  L10nKeys.careGamesSoon:
      'Ki kham bad ka histori jong ki session kin paw hangne.',
  L10nKeys.careRoutineSoon: 'Ka rutin jong u jingsaid kan paw hangne.',
  L10nKeys.careProfileSoon:
      'Ka profile bad ki setting jong u nongtuh kan paw hangne.',
  L10nKeys.serverPairingTitle: 'Family code',
  L10nKeys.serverPairingBody:
      'Share this code with a caregiver so they can connect to you.',
  L10nKeys.serverUnlinked: 'Not connected to server',
  L10nKeys.serverLinked: 'Connected to server',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
