import '../l10n_keys.dart';

/// Manipuri (Meitei, Bengali script) dictionary (best-effort machine-assisted translation; native review required).
/// Core food-market terms corroborated against xobdo.org, Glosbe and
/// A Dictionary of Manipuri Verbs.
/// Untranslated keys automatically fall back to English.
const Map<String, String> stringsMni = {
  L10nKeys.appName: 'Companio',
  // How to play (tutorials)
  L10nKeys.tutListen: 'Listen',
  L10nKeys.tutPairs1: 'Watch the pictures carefully. Soon they will be hidden.',
  L10nKeys.tutPairs2: 'Tap a card to turn it around.',
  L10nKeys.tutPairs3: 'Find two of the very same picture.',
  L10nKeys.tutSeq1: 'Watch the cards light up one by one.',
  L10nKeys.tutSeq2: 'Remember the order.',
  L10nKeys.tutSeq3: 'Tap the cards in the same order.',
  L10nKeys.tutRecall1: 'Read or listen to the question.',
  L10nKeys.tutRecall2: 'Tap the answer you remember.',
  L10nKeys.tutRecall3: 'Choose one answer to finish.',
  L10nKeys.tutMatch1: 'Look at the pictures on the left.',
  L10nKeys.tutMatch2: 'Tap the matching picture on the right.',
  L10nKeys.tutMatch3: 'Match every pair to finish.',
  L10nKeys.tutNoFail: 'Take your time. There is no failing.',
  L10nKeys.tagline: 'নঙগি নিংথিবগি অচুম্বা মরূপ',
  L10nKeys.back: 'হল্লকপ',
  L10nKeys.next: 'মথক্ত',
  L10nKeys.continueText: 'মথক্ত চৎথরকপ',
  L10nKeys.skip: 'য়েংরোয়ব',
  L10nKeys.done: 'লোইরেম্মিনাক',
  L10nKeys.cancel: 'য়াথাং তৌগনি',
  L10nKeys.yes: 'হোয়',
  L10nKeys.no: 'নাত্তে',
  L10nKeys.save: 'থামজিননবা',
  L10nKeys.close: 'খুমজিন্নবা',
  L10nKeys.retry: 'অমুক হন্না হেন্না',
  L10nKeys.add: 'থেম্নবা',
  L10nKeys.edit: 'সেম্গৎপ',
  L10nKeys.remove: 'লোকৎপ',
  L10nKeys.search: 'থংগনবা',
  L10nKeys.today: 'নঙসি',
  L10nKeys.offline: 'ইন্টারনেট লৈঙাইদা',
  L10nKeys.online: 'ইন্টারনেটদা',

  L10nKeys.goodMorning: 'ফোরবগি ইরোইবম',
  L10nKeys.goodAfternoon: 'নুঙাইরকপ অফবা',
  L10nKeys.goodEvening: 'সারকগি ইরোইবম',
  L10nKeys.goodNight: 'ফোরৎ জেনা লৈবু',

  L10nKeys.navHome: 'যুম',
  L10nKeys.navGarden: 'লৈঙাক',
  L10nKeys.navActivities: 'খুদোল্লম',
  L10nKeys.navMemories: 'নিংশিংগি সৌজিন',
  L10nKeys.navProfile: 'প্রোফাইল',
  L10nKeys.navMystery: 'নঙসিগি নিংথিবা',

  L10nKeys.onboardingWelcomeTitle: 'নঙগি নিংথিবগি নুংগাইজম্নবা মরূপ',
  L10nKeys.onboardingWelcomeBody: 'মাইন্ডকেয়ার এনইআর নঙকপু ইন্টারনেট থাংলুপদা নিংথিবনবা, খুদোল্লকনবা অমসুং যুমগি মীশাক্কা লোনৌনবা মঙংগনি।',
  L10nKeys.onboardingNameTitle: 'Eকনি নঙকপু করি কোকপৈ?',
  L10nKeys.onboardingNameHint: 'নঙগি মীং',
  L10nKeys.onboardingRegionTitle: 'নঙগি যুম কৈদগি অমগোয়?',
  L10nKeys.onboardingRegionHint: 'মচাং অমসুং যুম',
  L10nKeys.onboardingRegionList: 'ইম্ফল, বিষ্ণুপুর, থৌবাল, উখরুল, চূড়াচাঁদপুর, সেনাপতি, গুয়াহাটি, শিলং, আগরতলা, আইজল, কোহিমা',
  L10nKeys.onboardingLanguageTitle: 'করি লোন্ নঙগি য়াথবা লৈবনি?',
  L10nKeys.onboardingLanguageBody: 'নঙকপু মখুখনু হন্না সেম্গৎপা য়াই বে।',
  L10nKeys.onboardingFamilyTitle: 'ঙাকপদা করা লৈরি?',
  L10nKeys.onboardingFamilyBody: 'নঙগি পাঞিনরবা মীশকপু হাইগনি। মখোয়গি মফম অমসুং খোনরেল নিংথিবগি নুংগাইবগে থমগনি।',
  L10nKeys.onboardingAddFamily: 'ইমুংগি মীয়াম থেম্নবা',
  L10nKeys.onboardingEmergencyTitle: 'স্বসংগদবগি মাতেঙা না করকপু কৌকনি?',
  L10nKeys.onboardingEmergencyBody: 'SOS বটন থেকপদা মাইন্ডকেয়ার নঙগি ইমুংগি মীয়মদা খোংগনি — অসুংব হীংগৎপা খোংচৎকপা অমসুং অদু ইন্টারনেট ওইনি।',
  L10nKeys.onboardingEmergencyName: 'মীং',
  L10nKeys.onboardingEmergencyPhone: 'ফোন নম্বর',
  L10nKeys.onboardingEmergencyRelation: 'মরী লৈনবা (মনু, মচন…)',
  L10nKeys.onboardingDoneTitle: 'নঙগি লৈঙাক থম্বা লোইরে!',
  L10nKeys.onboardingDoneBody: 'ঙই খুদোল্লম লোইব তমদুনা লৈঙাক সন্মখিবনে য়েংবু। Eiখোয় নঙগা লোইন্না লৈরি।',
  L10nKeys.onboardingStart: 'Eiগি লৈঙাক হৌরকপ',

  L10nKeys.homeWhatsGrowing: 'নঙসি করি সন্মি?',
  L10nKeys.homeTodayActivity: 'নঙসিগি ঙই খুদোল্লম',
  L10nKeys.homeActivityDuration: '৩ মিনিট ঈদাদা',
  L10nKeys.homeMinutes: 'মিনিট',
  L10nKeys.homeMemoryOfDay: 'নঙসিগি নিংথিবা',
  L10nKeys.homeMemoryLocked: 'অমা অচুম্বা নিংথিবা Ei নঙকোয় টমমিনি…',
  L10nKeys.homeMemoryUnlocked: 'অমা নিংথিবা হংখরে!',
  L10nKeys.homeContinueActivity: 'খুদোল্লম মথক্ত তমদুনা চৎথরকপ',
  L10nKeys.homeFamilyMemory: 'নঙগি ইমুংদগি',
  L10nKeys.homeFamilyMemoryEmpty: 'ইমুংগি নিংথিবা সি মসিদা উৎপা য়াই।',
  L10nKeys.homeSos: 'Ei মাতেঙ য়ানবা তাবনি',
  L10nKeys.homeSosSubtitle: 'স্বসংগদবগি ইমুংগি মীয়ামদা মাতেঙ কৌপ',
  L10nKeys.homeGardenPreview: 'নঙগি লৈঙাক',
  L10nKeys.homeEngine: 'মাইন্ডকেয়ার মরূপ',
  L10nKeys.homeEngineReady: 'নঙগি শক্তিমনবগি থম্বা সেম্বি য়াই।',
  L10nKeys.homeWelcomeBack:
      'অমুক হৌগৎকপা য়াই! লৈঙাক মথক্ত তম্দুনা চৎথরকপা য়াই। 🌸',
  L10nKeys.homeNoActivity: 'নঙসি খুদোল্লম লৈরে',
  L10nKeys.homeNoActivityBody:
      'Eiরৌ চল্লমা হুড়ৎপা য়াই — নঙগি পাঞিনরবা খুদোল্লম খঙহল্লো। 🌻',

  L10nKeys.gardenTitle: 'Eiগি নিংথিবা লৈঙাক',
  L10nKeys.gardenSectionAll: 'পোয়নমক',
  L10nKeys.gardenSectionFamily: 'ইমুং',
  L10nKeys.gardenSectionChildhood: 'মাৎতম',
  L10nKeys.gardenSectionPlaces: 'অপুন্বা লৈকাই',
  L10nKeys.gardenSectionFestivals: 'ইরোইবম',
  L10nKeys.gardenEmpty: 'নঙগি লৈঙাক খোই̆য়দা য়াই',
  L10nKeys.gardenEmptyBody:
      'অহঙবা খুদোল্লম লোইরকপদা, মসিদা অমা হৌজাকনবা থমকনি।',
  L10nKeys.gardenPoints: 'পয়েন্ট',
  L10nKeys.gardenLevel: 'থরম',
  L10nKeys.gardenSeed: 'হৌজাক',
  L10nKeys.gardenPlant: 'উল্লতা',
  L10nKeys.gardenFlower: 'মরুপ',
  L10nKeys.gardenTree: 'ঊ',
  L10nKeys.gardenMilestone: 'খুদেল',
  L10nKeys.gardenGrowth: 'চৎচৎলি',
  L10nKeys.gardenDidYouKnow: 'খুদোল্লম খুদিম্মক লোইবদা নঙগি লৈঙাক চৎচৎলি।',
  L10nKeys.gardenPlantSeed: 'হৌজাক থেম্নবা',

  L10nKeys.activitiesTitle: 'খুদোল্লম',
  L10nKeys.activitiesToday: 'নঙসি',
  L10nKeys.activitiesLibrary: 'অপরায় খুদোল্লম',
  L10nKeys.mainGamesTitle: 'মুখ্য থৌরং',
  L10nKeys.activitiesStart: 'হৌরকপ',
  L10nKeys.activitiesCompleted: 'লোইরেছেনি',
  L10nKeys.activitiesInProgress: 'চৎলি',
  L10nKeys.activitiesNotStarted: 'সেম্ব্রেবি',
  L10nKeys.activityYoureDone: 'ইনগৎ লাই!',
  L10nKeys.activityPraise: 'নঙ লৈঙাকতা অমা শক অপ্বা পুয়েনি। 🌱',
  L10nKeys.activityHint: 'মাতেঙ য়াব্র?',
  L10nKeys.activityTryAgain: 'সি নিংথিবা অমুক হন্না য়েং',
  L10nKeys.activityOptionsHint: 'নঙগি অক্তুবা থঙসীল্লো',
  L10nKeys.activityTapToMatch: 'মশক মৎয়চ্চনবা থঙসীল্লো',
  L10nKeys.activityNext: 'মথক্ত',
  L10nKeys.activityFinish: 'লোইব',
  L10nKeys.activityGroupLetsAgain: 'সি অমুক হন্না য়েংগনি',
  L10nKeys.activityGroupTogether: 'সি খোইননা তৌগনি',
  L10nKeys.activityGreatJob: 'ফাই আফবা!',
  L10nKeys.activityKitchen: 'Eiগি লেকাই',
  L10nKeys.activityShopping: 'Eiগি ময়কাই',
  L10nKeys.activityMatching: 'মৎয়চ্চন',
  L10nKeys.activitySequence: 'মফুং ওয়াংমগি মাশক',
  L10nKeys.activityRecognition: 'মসি করি অদুনি?',
  L10nKeys.activityAssociation: 'করি লোইনবা লৈরি?',
  L10nKeys.activityRecall: 'নঙ নিংশিংদব্র?',
  L10nKeys.activityAttention: 'থংগনবা',
  L10nKeys.activityDurationSuffix: 'মিনিট',
  L10nKeys.activityTodayDone: 'নঙসিগি খুদোল্লম লোইরে',
  L10nKeys.activityTodayDoneBody:
      'নঙগি লৈঙাক সন্মখি। নপকু অমা নিংথিবা Ei তমলনি।',
  L10nKeys.activityGardenGrew: 'নঙগি লৈঙাক সন্মখি!',
  L10nKeys.activityMemoryUnlocked: 'অমা নিংথিবা হংখি',
  L10nKeys.activityReadAloud: 'খোংদা য়েংরকপা য়াই',

  L10nKeys.kitchenTitle: 'চা সেম্গৎপা য়াই',
  L10nKeys.kitchenMakeChai: 'চা সেম্গৎপ',
  L10nKeys.kitchenMakeChaiPrompt: 'খুদোল্লমশিং ম্রোইমা ম্রোই অদা মশক থেংলো।',
  L10nKeys.kitchenSteps: 'খুদোল্লম',
  L10nKeys.kitchenTapInOrder: 'খুদোল্লমশিং মশক থেংলো',
  L10nKeys.kitchenCorrectOrder: 'ইনগৎ! চা থেম্বি য়াই!',
  L10nKeys.kitchenBreakfast: 'আইয়াবগি চদ্রবা',
  L10nKeys.kitchenBreakfastHint: 'নঙসিগি নুথুংবা চৌহৌ',
  L10nKeys.kitchenBreakfastPrompt: 'আইয়াবগি চদ্রবগি খুদোল্লমশিং মশক থেংলো।',

  L10nKeys.shopTitle: 'Eiগি ময়কাই',
  L10nKeys.shopGetMilkBread: 'সংগোম অমসুং রুটি',
  L10nKeys.shopGetMilkBreadPrompt: '₹১০০দা সংগোম অমসুং রুটি লীর্বি।',
  L10nKeys.shopBudget: 'হৌজাক মরোইমা',
  L10nKeys.shopBasket: 'নঙগি ময়াকথোই',
  L10nKeys.shopTotal: 'পোয়নমক',
  L10nKeys.shopWithinBudget: 'হৌজাক মরোইমাদা!',
  L10nKeys.shopOverBudget: 'হৌজাক মরোইমদগি হেনা — অমুক য়েং',
  L10nKeys.shopCheckout: 'লোইবনম্মিন্না',
  L10nKeys.shopBuy: 'ময়াকথোইদা থম্মু',
  L10nKeys.shopSell: 'লোকৎপড়ু',
  L10nKeys.shopVeggies: 'নুপি চদ্রবগি হাতাক',
  L10nKeys.shopVeggiesPrompt: '₹৬০দা আলু অমসুং পিয়াজ লীর্বি।',
  L10nKeys.recKitchenItem: 'মসি করি অদুনি?',
  L10nKeys.recKitchenItemPrompt: 'ময়কাইদগি পোল্লনবগি থিন্দে করি সেম্গৎকনি?',
  L10nKeys.recCurrency: 'থুম কুথি',
  L10nKeys.recCurrencyPrompt: 'করি নোট ₹২০ অদুনি?',
  L10nKeys.matchFestival: 'ইরোইবম মৎয়চ্চন',
  L10nKeys.matchFestivalPrompt: 'ইরোইবম খুদিং মমসবগা মশক থেংলো।',
  L10nKeys.matchObjectUse: 'মৎয়চ্চন',
  L10nKeys.matchObjectUsePrompt: 'মসবগা মসবগা অদু য়েং।',
  L10nKeys.seqMorning: 'আইয়াবগি অখোয়ায়',
  L10nKeys.seqMorningPrompt: 'সি মশক থেংলো।',
  L10nKeys.seqRoute: 'আইয়াবগি লমলেম',
  L10nKeys.seqRoutePrompt: 'ময়কাইদা চৎপগি লমলেম মশক থেংলো।',
  L10nKeys.assoRegion: 'মসিদা করি লৈরি?',
  L10nKeys.assoRegionPrompt: 'অসাম করি মীংখরোয়দবনি?',
  L10nKeys.assoHarvest: 'থরুম আচুম্বা',
  L10nKeys.assoHarvestPrompt: 'করি থরুম থাকা য়াই?',
  L10nKeys.attnVeg: 'গাজর থংগনবা',
  L10nKeys.attnVegPrompt: 'নঙ গাজর থেংখিবে?',
  L10nKeys.recallSong: 'খংনবা সেল',
  L10nKeys.recallSongPrompt: 'বাইহুদা করি সেল য়াওনোয়?',
  L10nKeys.activityPairs: 'জেরা থোকপা',
  L10nKeys.activitySequenceRecall: 'দায়েন মাইয়েকপা',
  L10nKeys.activityFindChanged: 'করি হংশিল্লে?',
  L10nKeys.pairsFruits: 'মার্কেটকি থল্লৈ',
  L10nKeys.pairsKitchen: 'ফুংগিমকি খোজৈ',
  L10nKeys.pairsRemember: 'পোয়ানশিং তুংনানা য়েংশি, অদুদগি জেরা থোক।',
  L10nKeys.pairsStart: 'পোয়ানশিং থুনাঙা হৌরক',
  L10nKeys.pairsFound: 'জেরা ফংলে!',
  L10nKeys.seqRecallItems: 'নুমিৎ খুদিঙগি খোযশিং',
  L10nKeys.seqRecallNumbers: 'দায়েনগী নুংশিং',
  L10nKeys.seqRecallWatch: 'পোয়ানশিং য়েংশি – খুদক্তক মীরেং ফংগনি।',
  L10nKeys.seqRecallRepeat: 'দৌরক্তি য়েঙখিবা দায়েন অসি মথংগদো তাল্লো।',
  L10nKeys.changeMarket: 'থল্লৈ খুম্লুম',
  L10nKeys.changeFestival: 'চাক চানুঙালগী মীরেং',
  L10nKeys.changeRemember: 'থশু পোয়ানশিং অসি মাইয়েক।',
  L10nKeys.changeFind: 'অমা পোয়ানশিং হংশিল্লে – খেমদবা অসি থোক।',
  L10nKeys.changeCorrect: 'য়েংদব! অসিমা হংশিল্লে।',

  L10nKeys.mysteryTitle: 'নঙসিগি অচুম্বা নিংথিবা',
  L10nKeys.mysteryLocked: 'অমা অচুম্বা নিংথিবা নঙথকি তমলি…',
  L10nKeys.mysteryLockedBody: 'নঙসি খুদোল্লম ২–৩ তৌরক; অদুমা মসি হংলকপা য়াই।',
  L10nKeys.mysteryUnlocked: 'নঙগি অচুম্বা নিংথিবা হংখলে!',
  L10nKeys.mysteryUnlockedBody: 'মসি নঙকপু মখকনগা। মতম লৌরক!',
  L10nKeys.mysteryCuriosity: 'নঙসি করি হংকদগনি?',
  L10nKeys.mysteryOpen: 'নিংথিবা হংলো',

  L10nKeys.memoriesTitle: 'Eiগি নিংথিবা',
  L10nKeys.memoriesEmpty: 'হুয়াই নিংথিবা লৈদি',
  L10nKeys.memoriesEmptyBody: 'নঙগি ইমুংদা মফম অমসুং খোনরল থমবগি শিংগিনা লৈরি। মখোয় লাকরকপদা মসিদা উৎপা য়াই।',
  L10nKeys.memoriesFamily: 'ইমুং',
  L10nKeys.memoriesPlaces: 'লৈকাই',
  L10nKeys.memoriesFestivals: 'ইরোইবম',
  L10nKeys.memoriesChildhood: 'মাৎতম',
  L10nKeys.memoriesKindPhoto: 'মফম',
  L10nKeys.memoriesKindVoice: 'খোনরল',
  L10nKeys.memoriesKindText: 'মহৈ',
  L10nKeys.memoriesKindSound: 'অজল',
  L10nKeys.memoriesKindPlace: 'লৈকাই',
  L10nKeys.memoriesAddedBy: 'থমল্বা মী',
  L10nKeys.memoriesWhoIsThis: 'মসি করা অদুনি?',
  L10nKeys.memoriesPlayVoice: 'সানা',
  L10nKeys.memoriesThisIsMe: 'Ei',
  L10nKeys.memoriesNotMe: 'Ei নীবিদে',

  L10nKeys.profileTitle: 'প্রোফাইল',
  L10nKeys.profileLanguage: 'এপ লোন',
  L10nKeys.profileRegion: 'Eiগি লৈকাই',
  L10nKeys.profileVoiceLanguage: 'খোঙগি লোন',
  L10nKeys.profileVoicePrompts: 'খোংদা থাজবগি থাবাক',
  L10nKeys.profileTextSize: 'মায়েকগি চৌবাস্তা',
  L10nKeys.profileReducedMotion: 'নুংগাইগা চৎপা',
  L10nKeys.profileSoundEffects: 'অজলগি মৎয়াম',
  L10nKeys.profileFamily: 'ইমুং',
  L10nKeys.profileContacts: 'স্বসংগদবগি খোংসেল',
  L10nKeys.profileDemoMode: 'ডেমো মোড',
  L10nKeys.profileReminders: 'নিংশিংহনবা',
  L10nKeys.profileNeedHelp: 'মাতেঙ য়ানবা তাব্র?',

  L10nKeys.remindersTitle: 'নিংশিংহনবা',
  L10nKeys.remindersEmpty: 'নিংশিংহনবা খুদিং লৈরে',
  L10nKeys.remindersNew: 'অহৎপা নিংশিংহনবা',
  L10nKeys.remindersTitleLabel: 'মীমাং',
  L10nKeys.remindersDetailLabel: 'অহাকল (যথাকাঙদা)',
  L10nKeys.remindersTime: 'মতম',
  L10nKeys.remindersDays: 'নুমিত',
  L10nKeys.remindersEveryday: 'নুমিত খুদিং',
  L10nKeys.remindersEnabled: 'হৌগৎখি',
  L10nKeys.remindersMedicine: 'লৌনবা',
  L10nKeys.remindersAppointment: 'ডক্টরদা উৎকপ',
  L10nKeys.remindersRoutine: 'খুদিং নুমিত্তগি নিগ্নি',

  L10nKeys.dayMon: 'নোংজাবা',
  L10nKeys.dayTue: 'নোংয়াইবা',
  L10nKeys.dayWed: 'য়ুমশাকে',
  L10nKeys.dayThu: 'য়ুমশাকে অখাংানীদ',
  L10nKeys.dayFri: 'অয়ুক্ত কবা',
  L10nKeys.daySat: 'য়ুমশাক কাবা',
  L10nKeys.daySun: 'খোমচিকা',

  L10nKeys.sosTitle: 'স্বসংগদবগি মাতেঙ',
  L10nKeys.sosExplain: 'মথেঙ থেকপদা মাইন্ডকেয়ার নঙগি স্বসংগদগি মীশক খুৎথক মীশকদা খোংগনি, অমা অমদা। মসি অসুংব খোংচৎকপা (কুম ১১২) ওইদা।',
  L10nKeys.sosHold: 'মাতেঙনবগি থেকপদা য়ুমু',
  L10nKeys.sosHoldBody: 'থেকপদা য়ুমু…',
  L10nKeys.sosActiveTitle: 'মাতেঙ কৌরি',
  L10nKeys.sosActiveBody:
      'নঙগি ইমুংগি মীশকদা খোংখি। মখোয় অক্তুবা য়াংখহলে লৈত্রকপদা অমুক খোংগনী।',
  L10nKeys.sosContacting: 'কৌরি',
  L10nKeys.sosContactFamily: 'ইমুংগি মীশক কৌরুবি',
  L10nKeys.sosContacted: 'খোংখি',
  L10nKeys.sosWaitingResponse: 'অক্তুবা য়াংহানবগি তমরি…',
  L10nKeys.sosEscalating: 'অতোপা মীশক কৌরি…',
  L10nKeys.sosCancelled: 'মাতেঙ খোংচৎপা তোংখি',
  L10nKeys.sosCancelAction: 'মাতেঙ খোংচৎপা তোংলো',
  L10nKeys.sosDone: 'লোইরে',
  L10nKeys.sosHelpOnWay: 'খবা মী নঙগি ঙাকপদা য়াই। 🧡',
  L10nKeys.sosNoContacts: 'স্বসংগদবগি খোংসেল লৈরে',
  L10nKeys.sosNoContactsBody: 'অচৌবা, ইমুংদা স্বসংগদবগি খোংসেল থম্নবা হাইয়ু।',
  L10nKeys.sosAddContact: 'খোংসেল থেম্নবা',
  L10nKeys.sosDisclaimer: 'মাইন্ডকেয়ার নঙগি থানম্লমবা মীশকদা খোংগনি মখত। মসি লৈকাইগি অসুংব খোংচৎকপা ওইদা।',
  L10nKeys.sosContactedPerson: 'ইমুংগি মীশকদা খোংখি',
  L10nKeys.sosEscalatedTo: 'অতোপা ইমুংগি মীশকদা খোংখি',
  L10nKeys.sosAcknowledged: 'ইমুংগি মীশক অক্তুবা য়াংখি। মাতেঙ লাকরি।',
  L10nKeys.sosNotSilent: 'থঙখি ওইদবগি মৎয়ামদা নৈচঙম্নবা ওইদি।',
  L10nKeys.sosAlertNotDelivered: 'নঙগি মাতেঙ অসংদা থঙখদে; Ei হেনগৎতুরি।',

  L10nKeys.careTitle: 'ঙাকপমীবগি ইমুং',
  L10nKeys.careDashboard: 'মচিম',
  L10nKeys.carePatients: 'Eiগি ঙাকপমীবা',
  L10nKeys.careMemories: 'নিংথিবা',
  L10nKeys.careContacts: 'স্বসংগদবগি খোংসেল',
  L10nKeys.careSettings: 'সেম্গৎসল',
  L10nKeys.careAddMemory: 'নিংথিবা থেম্নবা',
  L10nKeys.careAddContact: 'খোংসেল থেম্নবা',
  L10nKeys.careEngagement: 'লোইন্না লৈপ',
  L10nKeys.careActivitiesWeek: 'সি সি পাতকিদা খুদোল্লম',
  L10nKeys.careGardenProgress: 'লৈঙাকগি চৎচৎপা',
  L10nKeys.careRecentActivity: 'চৎলিবা খুদোল্লম',
  L10nKeys.careNoPatients: 'ঙাকপমীবা লৈরে',
  L10nKeys.careNoPatientsBody:
      'ইমুংগি মীশক থেম্নবা হাইয়ু, নঙগি ঙাকপমীবা প্রোফাইল হৌগৎলো।',
  L10nKeys.careAddPatient: 'অদংগবা ঙাকপমীবা থেম্নবা',
  L10nKeys.carePerformanceNote:
      'হৌজিক্ খুদোল্লমগি মরুওইবা মফাম অদু মখংন লাগত্মবদা ওইত্তনদা।',
  L10nKeys.careUploadPhoto: 'মফম থেল্লো',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'খোনরল রেকর্ড তৌরু',
  L10nKeys.careWriteMemory: 'নিংথিবা ইরুবী',
  L10nKeys.careMemoryTitle: 'মীমাং',
  L10nKeys.careMemoryCaption: 'নোংগি',
  L10nKeys.careMemoryRelation: 'মসিদা করা লৈরি? (মরীসম্বা)',
  L10nKeys.careMemoryCategory: 'মফাম',
  L10nKeys.careContactName: 'মীং',
  L10nKeys.careContactPhone: 'ফোন নম্বর',
  L10nKeys.careContactPriority: 'কৌকপদা মশক',
  L10nKeys.careContactRelation: 'মরীসম্বা',
  L10nKeys.careEscalationTimeout: 'অতোপা মীশকদা চৎপদগি মিনিটশিং',
  L10nKeys.careIncidentStatus: 'হৌজিক্ মেছুয়া',
  L10nKeys.careAckSos: 'Ei অক্তুবা য়াংরি',
  L10nKeys.careResponding: 'অক্তুবা য়াংরি',
  L10nKeys.careActiveAlerts: 'থাবায়া হন্দা লৈবা অছিঙুশিং',

  L10nKeys.syncSavingOffline: 'ইন্টারনেট থাংলুপ',
  L10nKeys.syncSavingOfflineBody: 'নঙগি খুদোল্লমশিং মসি ডিভাইসদা থমখি।',
  L10nKeys.syncSynced: 'অমা অমা থেমখি',
  L10nKeys.syncInfo: 'নঙগি নিংথিবা থেমখি।',
  L10nKeys.syncPending: 'থেমখনবগি তমরি',

  L10nKeys.errorGeneric: 'করি অমৌতাকনা থেঙখি',
  L10nKeys.errorGenericBody:
      'নঙগি নিংশিংহৌ এনঙপা লৈরে। অমুক হন্না য়েংবিও, এজি।',
  L10nKeys.errorAudio: 'মসি ডিভাইসদা অজল সানা য়াদে।',
  L10nKeys.errorPermission: 'মসি ডিভাইসগি য়াথবা য়া য়ানবা তাবনি।',
  L10nKeys.errorNoInternetAction: 'ইন্টারনেট লৈতবনি — মসি এনআরদা থমখি।',

  L10nKeys.demoWelcome: 'ডেমো য়েংলো',
  L10nKeys.demoExplain: 'নঙগি য়েংনবগি অমা ইমুং অমসুং নিংথিবা থেমকনি।',
  L10nKeys.demoLoad: 'ডেমো লৈঙাক হৌগৎলো',

  L10nKeys.unitsPoints: 'পয়েন্ট',
  L10nKeys.teaserChai: 'Ei চা সেম্গৎলো।',
  L10nKeys.familiarityName: 'মমা থোইবি',
  L10nKeys.regionMap: 'Eiগি লৈকাই',
  L10nKeys.regionChoose: 'নঙগি লৈকাই থেম্নরু',
  L10nKeys.regionIndia: 'ভারত',
  L10nKeys.importantMemory: 'কন্নবগি নিংথিবা',
  L10nKeys.growing: 'চৎচৎলি',
  L10nKeys.blooming: 'মুহাং উৎলি',
  L10nKeys.mature: 'হেনগৎখি',
  L10nKeys.noVoice: 'মসি ডিভাইসদা খোং য়াদে।',
  L10nKeys.optional: 'যথাকাঙদা',

  L10nKeys.langChoose: 'লোন থন্নরু',
  L10nKeys.langPrimary: 'মখরুপা',
  L10nKeys.langNorthEast: 'NE India',
  L10nKeys.langMajor: 'ভারতগি অথেনগি লোনশিং',

  L10nKeys.authSignUpTitle: 'নঙগি অকাউন্ট সেম্গৎরু',
  L10nKeys.authSignUpBody: 'মসি মাইন্ডকেয়ার প্রোফাইল নঙগি ডিভাইসদা থমখি। নঙ মখকনগা শריכה য়াবগি মীং অমসুং পাসওয়ার্ড থেমরু।',
  L10nKeys.authLoginTitle: 'অমুক হৌরকপ',
  L10nKeys.authLoginBody:
      'নঙগি লৈঙাকদা চৎপগি অকাউন্ট মীং অমসুং পাসওয়ার্ডদা সাইন ইন তৌরু।',
  L10nKeys.authUsername: 'মীং',
  L10nKeys.authUsernameHint: 'মদিগি: ranu123',
  L10nKeys.authDisplayName: 'নঙগি মীং',
  L10nKeys.authPassword: 'পাসওয়ার্ড',
  L10nKeys.authPasswordHint: 'লৈক তাহে ৬ অথম',
  L10nKeys.authConfirmPassword: 'পাসওয়ার্ড অমুক হন্না থমরু',
  L10nKeys.authRoleQuestion: 'মসি প্রোফাইল করগি…',
  L10nKeys.authRolePatient: 'Eiগি',
  L10nKeys.authRoleCaregiver: 'ইমুংগি মীয়ামগি',
  L10nKeys.authCreate: 'অকাউন্ট সেম্গৎরু',
  L10nKeys.authSignIn: 'সাইন ইন',
  L10nKeys.authSignOut: 'সাইন আউট',
  L10nKeys.authAccount: 'অকাউন্ট',
  L10nKeys.caregiverTitle: 'Caregiver',
  L10nKeys.caregiverNotLinked: 'No caregiver linked yet',
  L10nKeys.authBadCredentials: 'মীং অমসুং পাসওয়ার্ড অরুগ।',
  L10nKeys.authUsernameTaken: 'মসি মীং মসি ডিভাইসদা সক্তি।',
  L10nKeys.authPasswordMismatch: 'পাসওয়ার্ড অমা অমা ওইদা।',
  L10nKeys.authUsernameShort: 'মীং লৈকতৈ ৩ অথম লাইবা তাবনি।',
  L10nKeys.authUsernameInvalid:
      'অথেম্বা, নম্বর, ডট, ড্যাশ নৎত্রে আন্দারস্কোর খুগদা য়াই।',
  L10nKeys.authPasswordShort: 'পাসওয়ার্ড লৈকতৈ ৬ অথম লাইবা তাবনি।',
  L10nKeys.authNameRequired: 'মীং থেমরু।',
  L10nKeys.authSignOutConfirm:
      'নঙ মসি প্রোফাইলদগি সাইন আউট ওইনবা য়াঁবনেষকদ্রা?',
  L10nKeys.screenTitle: 'হল্লক নিংশিং চেৎশিৎ',
  L10nKeys.screenIntro:
      'ঐখোই রোগীগী মরমদা সেল্লে চেৎশিৎ কয়া হঙগনি। অসুবা ভাগী মচুংদা খঙদুনা।',
  L10nKeys.screenNotSure: 'খংদে',
  L10nKeys.screenFinish: 'ঐগী ফবম উয়ু',
  L10nKeys.screenSkip: 'অকলঙে তাই',
  L10nKeys.screenResultBack: 'লোইরে',
  L10nKeys.screenCheckAgain: 'অমুক্ চেৎশিৎ তৌ',
  L10nKeys.screenStartCheckup: 'চেৎশিৎ হৌ',
  L10nKeys.screenSkipped: 'চেৎশিৎ লোইদনা তা',
  L10nKeys.screenStatusGood: 'পুন্না লৈরম্মী',
  L10nKeys.screenStatusGoodBody: 'খুদৈমমা য়াউনবগী তায়দে। নুমিত্তংগী নাইবা তারকদুনা — করিগুম্বা হংলকলে, মতামগী মতাংদা অমুক্ চেৎশিৎ তৌ।',
  L10nKeys.screenStatusWatch: 'কনাগুম্বা হংলকপগা উখি',
  L10nKeys.screenStatusWatchBody:
      'খদক্ পোংগলকলে উখি। মসি সোমদগা য়াই, অদুদা নেংশিৎলনা ডক্টরগী অউনা হায়।',
  L10nKeys.screenStatusDoctor: 'ডক্টরদা চেৎশিৎ তৌহল্লু',
  L10nKeys.screenStatusDoctorBody: 'ঐখোই সেংনবা য়ানবা কয়াখুদা থমজেল্লে। সেংনবা লোঙথোকপগীদমক মসিংগু ডক্টর নত্যদে ক্লিনিকদা হায়লু।',
  L10nKeys.screenRarely: 'য়াদিদনা',
  L10nKeys.screenSometimes: 'খনগুম্বা মতামোদা',
  L10nKeys.screenFrequently: 'থোরক থোরক',
  L10nKeys.screenVeryFrequently: 'থোরক্না থোরক',
  L10nKeys.screenQ01: 'মহাকগী সয়োয়ুং থৌরমদা নিংশিংবগী খুদোংদা অপব নেইব্রে?',
  L10nKeys.screenQ02: 'মহাক্ সেম্গনা খোঙলবা থৌরম অমসুং ওয়ারী সাঙ্লি নে?',
  L10nKeys.screenQ03: 'মহাক্ খংলমপা মীদু হুয়েংদে নে?',
  L10nKeys.screenQ04: 'মহাক্ খংলমপা মীগী মৈথোং আঙাংলদোং খংদনে?',
  L10nKeys.screenQ05: 'মহাক্ থোঙজিনবা অমসুং য়ানবা থৌরম নিংশিংদে নে?',
  L10nKeys.screenQ06: 'মহাক্ অর্নথবগী ওয়াম ওদোদা অপব নেইব্রে?',
  L10nKeys.screenQ07: 'মহাক্ করমদা লৈবগী মরমদা নুনসিমদে নে?',
  L10nKeys.screenQ08: 'মহাক্পু নুমিত্তংগী থৌরম্গীদমক নিংশিনহনবগী য়াংলে নে?',
  L10nKeys.screenQ09: 'মহাক্ লক্চেৎ তৌবগী খুদোংদা অপব নেইব্রে?',
  L10nKeys.screenQ10: 'মহাক্ নুনসিমম্নে মাইকায়া অমসুং শাধৈ চাউ নে?',
  L10nKeys.screenQ11: 'মহাক্ খোঙলবা ওয়ারী খঙনদে নে?',
  L10nKeys.screenQ12: 'মহাক্ খংখবে থৌরম কছবা খুদোংদা অপব নেইব্রে?',
  L10nKeys.screenQ13:
      'মহাক্ নুমিত্তং চিংখগী পোথো করমদা থমখিব্রে হেরবগী নিংশিংদে নে?',
  L10nKeys.screenQ14: 'মহাক্ য়াত্নবগী নিংশিংদে নে?',
  L10nKeys.screenQ15: 'মহাক্ তুম উৎপদা চেৎশিৎ তৌবগী খুদোংদা অপব নেইব্রে?',

  L10nKeys.careDashboardSubtitle: 'Family care',
  L10nKeys.careSosLive: 'Live alert',
  L10nKeys.careSosRespondedBy: 'Responded by {name}',
  L10nKeys.careLinkTitle: 'Connect to a family member',
  L10nKeys.careLinkBody: 'Ask your loved one for the 6-letter family code shown on their phone, then connect.',
  L10nKeys.careLinkCode: 'Family code',
  L10nKeys.careLinkCodeHint: 'e.g. A1B2C3',
  L10nKeys.careLinkConnect: 'Connect',
  L10nKeys.careLinkDone: 'Connected',
  L10nKeys.careLinkSuccess:
      'Linked to {name}! Memories and alerts will now sync.',
  L10nKeys.careLinkFailed:
      'Could not connect. Please check the code and try again.',
  L10nKeys.careTrendsTitle: 'AI trends',
  L10nKeys.careTrendsBody: 'Daily accuracy by activity type',
  L10nKeys.careTrendsNoData:
      'No activity yet — complete an exercise to see trends.',
  L10nKeys.careAiDifficulty: 'Auto-tuned difficulty',
  L10nKeys.careAiAccuracy: 'Model accuracy',
  L10nKeys.careAiRealSessions: 'Real sessions',
  L10nKeys.careAiDemoSessions: 'Demo sessions',
  L10nKeys.careNavGames: 'থৌরং',
  L10nKeys.careNavRoutine: 'রুটিন',
  L10nKeys.careGreetSubtitle: 'নঙসি {name} করমদা লৈরি, মসিনি উল্লো।',
  L10nKeys.careNotifEmpty: 'অনৌবা খুমাইংবা লৈরে',
  L10nKeys.careWellnessScore: 'নিংথিবাগি চাংথেংনবা স্কোর',
  L10nKeys.careStatusStable: 'স্থির',
  L10nKeys.careStatusAttention: 'ঐখোং নাংগদবনি',
  L10nKeys.careLastSynced: '{time} দা সিঙ্ক তৌখ্রে',
  L10nKeys.careMinAgo: '{n} মিনিট উৎলংখ্রে',
  L10nKeys.careGamesWeek: 'পাতকিগি থৌরং',
  L10nKeys.careRoutineCompletion: 'রুটিন খুদোল্লম হৈখে',
  L10nKeys.careCurrentStreak: 'হৌগদব হুম',
  L10nKeys.careMoodCheckins: 'পুন্সিগি চেক-ইন',
  L10nKeys.careDayUnit: 'নুমিৎ',
  L10nKeys.careDaysUnit: 'নুমিৎসিং',
  L10nKeys.careActivityTitle: 'পাতকিগি খুদোল্লম',
  L10nKeys.careWeekly: 'পাতকিগি',
  L10nKeys.careMonthly: 'থাগি',
  L10nKeys.careNoActivityWeek: 'সেম্গৎখি পাতকিদা খুদোল্লম খংদে।',
  L10nKeys.careMoodTitle: 'পুন্সি',
  L10nKeys.careMoodHappy: 'ঙফাইবা',
  L10nKeys.careMoodCalm: 'আরম',
  L10nKeys.careMoodNeutral: 'সাধারণ',
  L10nKeys.careMoodLow: 'অনৈ',
  L10nKeys.careMood7Days: 'খুদিঙমদগি ৭ নুমিৎ',
  L10nKeys.careMoodInsight: '{name} সেম্গৎখি পাতকিদা হৌজিক্ তুম্খগা লৈরি, অদুবা কনাচবা অনীশু নুমিৎনিগি মরক্তা ইয়েংলিক্ অনৈথোকলে।',
  L10nKeys.careMoodNoData: 'সেম্গৎখি পাতকিদা পুন্সিগি চেক-ইন লৈরে।',
  L10nKeys.careSkillsTitle: 'নিংথিবাগি খুদোল্লম',
  L10nKeys.careSkillMemory: 'নিংথিবা',
  L10nKeys.careSkillAttention: 'থংগনবা',
  L10nKeys.careSkillLanguage: 'লোন',
  L10nKeys.careSkillReasoning: 'খল্লবা',
  L10nKeys.careSkillProcessing: 'থবক চপ্পৎতা',
  L10nKeys.careInsightToday: 'নঙসি অদুনা',
  L10nKeys.careInsightBody: 'রবার্তনা সায়োর্গি রুটিনগি মংগিবা নিংথিবা খুদোল্লমসিংদা থম্বানা সেমজৎলি। মখোম্গি পুন্সি খুদিঙমদগি অনীশু নুমিৎত্রগি চপ্পৎ তুম্খগা লৈরি।',
  L10nKeys.careInsightBodyReal: 'সেম্গৎখি পাতকিদা {name} {count} নিংথিবাগি খুদোল্লম ({goal} থম্বা) সেমজৎখ্রে, অদুগা {streak} নুমিৎ হুম চতলে।',
  L10nKeys.careViewDetails: 'খুম্নরো',
  L10nKeys.careInsightDisclaimer:
      'মসি দাতানিগি সরুক চৎখিবা নুংশিংবা — মেকেলগি হেন্নবা নৈ।',
  L10nKeys.careAttentionTitle: 'ঐখোং নাংগদবনি',
  L10nKeys.careAttentionEmpty: 'হৌনোদা ঐখোং নাংগদবা খুদিংমচা লৈদে।',
  L10nKeys.careAlertSos: '{name} SOS বাটন তমিখে',
  L10nKeys.careAlertRoutineMissed: 'খইদিসানা রুটিন খুদোল্লম তৌদা খ্রে',
  L10nKeys.careAlertMoodDown: 'খুদিঙমদগি অনীশু নুমিৎদা পুন্সি ইয়েংগদলে',
  L10nKeys.careAlertSessionPending: 'নঙসি নিংথিবাগি খুদোল্লম হৈদে',
  L10nKeys.careAlertSeverityHigh: 'অয়াম্বা',
  L10nKeys.careAlertSeverityMedium: 'অংগৎপা',
  L10nKeys.careAlertSeverityLow: 'অনৈ',
  L10nKeys.careWeeklySummary: 'পাতকিগি চরুক',
  L10nKeys.careSessionsCompleted: 'হৈখব খুদোল্লমসিং',
  L10nKeys.careAvgSessionDuration: 'খুদোল্লমগি চপ্পৎ মনুং মমিৎ',
  L10nKeys.careRoutineAdherence: 'রুটিন উৎনবা',
  L10nKeys.careMoodTrend: 'পুন্সিগি হেনখবা হৈনখবা',
  L10nKeys.careMoodTrendSlightlyDown: 'কয়াদনা ইয়েংলিক্',
  L10nKeys.careMoodTrendStable: 'স্থির',
  L10nKeys.careMoodTrendUp: 'থতুনা হেনখরে',
  L10nKeys.careVsLastWeek: 'খুদিঙমদগি পাতকি সুম্ডবা',
  L10nKeys.careSyncedJustNow: 'হৌজিক্ সিঙ্ক তৌখ্রে',
  L10nKeys.careOfflineWaiting:
      'ইন্টারনেট লৈদে · {count} খুদোল্লম সিঙ্ক তৌনে থামখিবা',
  L10nKeys.careComingSoon: 'খুদিঙমদগি পুথোক্কনি',
  L10nKeys.careHomeSoon:
      '{name} নুমিৎ খুদিঙমগি চহিনবা মসিগি সেংখু য়াইদা পুথোক্কনি।',
  L10nKeys.careGamesSoon:
      'থৌরং অমসুং খুদোল্লমগি খুদিঙগি মরম মসিগি সেংখু য়াইদা পুথোক্কনি।',
  L10nKeys.careRoutineSoon:
      'মীরেং নুমিৎদা রুটিন খুদোল্লম মসিগি সেংখু য়াইদা পুথোক্কনি।',
  L10nKeys.careProfileSoon:
      'ঐখোং নাংগীবগি প্রোফাইল অমসুং সেটিংসিং মসিগি সেংখু য়াইদা পুথোক্কনি।',
  L10nKeys.serverPairingTitle: 'Family code',
  L10nKeys.serverPairingBody:
      'Share this code with a caregiver so they can connect to you.',
  L10nKeys.serverUnlinked: 'Not connected to server',
  L10nKeys.serverLinked: 'Connected to server',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
  // Patient-home, memories, voice and calendar fallbacks (English source).
  L10nKeys.addFirstRoutine: 'নঙগি অহঙবা রুটিন থেম্নবা',
  L10nKeys.addMemoryTooltip: 'Add a memory',
  L10nKeys.addRoutine: 'রুটিন থেম্নবা',
  L10nKeys.addToMemory: 'Add to this memory',
  L10nKeys.attachmentsAddedMany: '{count} attachments added',
  L10nKeys.attachmentsAddedOne: '1 attachment added',
  L10nKeys.careAchieveEngagement: '10 Hours of Play',
  L10nKeys.careAchieveEngagementBody: '10 total hours spent playing together',
  L10nKeys.careAchieveFirstSteps: 'First Steps',
  L10nKeys.careAchieveFirstStepsBody: 'Patient completed their first session',
  L10nKeys.careAchieveGarden: 'Garden in Bloom',
  L10nKeys.careAchieveGardenBody: 'Grow 5 plants in the Memory Garden',
  L10nKeys.careAchievePerfect: 'Perfect Round',
  L10nKeys.careAchievePerfectBody: 'A game finished with a perfect score',
  L10nKeys.careAchieveSevenDay: 'One Week Together',
  L10nKeys.careAchieveSevenDayBody: 'A session on 7 different days',
  L10nKeys.categoryLabel: 'Category',
  L10nKeys.createMemory: 'Create a Memory',
  L10nKeys.deleteAction: 'লোকৎপ',
  L10nKeys.deleteRoutineBody: 'Remove "{title}" from your routine?',
  L10nKeys.deleteRoutineTitle: 'Delete routine?',
  L10nKeys.deleteRoutineTooltip: 'Delete routine',
  L10nKeys.homeRoutineSubtitle: 'নঙগি নুমিৎকিদমক অজাউবা লমসেম অমা।',
  L10nKeys.medicineKind: 'লৌনবা',
  L10nKeys.memoriesKindVideo: 'Video',
  L10nKeys.memoriesSubtitle: 'Keep your favourite moments close.',
  L10nKeys.memoryCaptionHint: 'What happened? Who was there? How did it feel?',
  L10nKeys.memoryCaptionLabel: 'Write something about this memory',
  L10nKeys.memoryComposeHint: 'Add a title, some text, and as many photos, videos or voice notes as you want.',
  L10nKeys.memorySaved: 'Memory saved 💙',
  L10nKeys.memoryTitleHint: 'e.g. My daughter\'s wedding',
  L10nKeys.memoryTitleLabel: 'Memory title',
  L10nKeys.memoryTitleRequired: 'Please give this memory a title.',
  L10nKeys.micVoicePermission: 'Microphone permission is needed for a voice memory.',
  L10nKeys.monthApr: 'Apr',
  L10nKeys.monthAug: 'Aug',
  L10nKeys.monthDec: 'Dec',
  L10nKeys.monthFeb: 'Feb',
  L10nKeys.monthJan: 'Jan',
  L10nKeys.monthJul: 'Jul',
  L10nKeys.monthJun: 'Jun',
  L10nKeys.monthMar: 'Mar',
  L10nKeys.monthMay: 'May',
  L10nKeys.monthNov: 'Nov',
  L10nKeys.monthOct: 'Oct',
  L10nKeys.monthSep: 'Sep',
  L10nKeys.photoAddFailed: 'Could not add this photo. Please try again.',
  L10nKeys.profileMissing: 'No patient profile found. Please sign in again.',
  L10nKeys.recordingStartFailed: 'Could not start recording. Please try again.',
  L10nKeys.routineAddBody: 'নঙগি নুমিৎকিদমক অজাউবা নিংশিংহনবা অমা সেম্গৎলো।',
  L10nKeys.routineAddTitle: 'রুটিন অমা থেম্নবা',
  L10nKeys.routineCheckBody: 'অফবা নুমিৎকিদমক অজাউবা থৌদোকশিং',
  L10nKeys.routineCheckTitle: 'রুটিন য়েংবা',
  L10nKeys.routineKind: 'রুটিন',
  L10nKeys.routineNameHint: 'মদিগি: ইশিং থাক',
  L10nKeys.routineNameLabel: 'রুটিনগি মীং',
  L10nKeys.savedMemoriesTitle: 'Saved Memories',
  L10nKeys.saveMemory: 'Save Memory',
  L10nKeys.settings: 'সেম্গৎসল',
  L10nKeys.sosShort: 'SOS',
  L10nKeys.stop: 'মথোকহল্লো',
  L10nKeys.stopVoiceFirst: 'Stop the voice recording first.',
  L10nKeys.textShort: 'Text',
  L10nKeys.timeLabel: 'মতম',
  L10nKeys.videoAddFailed: 'Could not add this video. Please try again.',
  L10nKeys.voiceSaveFailed: 'Could not save the voice recording.',
  L10nKeys.voiceShort: 'Voice',
  L10nKeys.waterKind: 'ইশিং',
};
