import '../l10n_keys.dart';

/// Marathi dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsMr = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'आपला स्मृती साथी',
  L10nKeys.back: 'मागे',
  L10nKeys.next: 'पुढे',
  L10nKeys.continueText: 'पुढे जा',
  L10nKeys.skip: 'वगळा',
  L10nKeys.done: 'झाले',
  L10nKeys.cancel: 'रद्द करा',
  L10nKeys.yes: 'होय',
  L10nKeys.no: 'नाही',
  L10nKeys.save: 'जतन करा',
  L10nKeys.close: 'बंद करा',
  L10nKeys.retry: 'पुन्हा प्रयत्न करा',
  L10nKeys.add: 'जोडा',
  L10nKeys.edit: 'बदला',
  L10nKeys.remove: 'काढा',
  L10nKeys.search: 'शोधा',
  L10nKeys.today: 'आज',
  L10nKeys.offline: 'ऑफलाइन',
  L10nKeys.online: 'ऑनलाइन',

  L10nKeys.goodMorning: 'सुप्रभात',
  L10nKeys.goodAfternoon: 'नमस्कार',
  L10nKeys.goodEvening: 'शुभ संध्याकाळ',
  L10nKeys.goodNight: 'शुभ रात्री',

  L10nKeys.navHome: 'घर',
  L10nKeys.navGarden: 'बाग',
  L10nKeys.navActivities: 'क्रिया',
  L10nKeys.navMemories: 'आठवणी',
  L10nKeys.navProfile: 'प्रोफाइल',
  L10nKeys.navMystery: 'आजची आठवण',

  L10nKeys.onboardingWelcomeTitle: 'तुमच्या आठवणींचा एक हळुवार साथी',
  L10nKeys.onboardingWelcomeBody: 'माइंडकेअर एनईआर इंटरनेटशिवायही लक्षात ठेवण्यास, खेळण्यास आणि कुटुंबाशी जोडलेले राहण्यास मदत करते.',
  L10nKeys.onboardingNameTitle: 'आम्ही तुम्हाला काय म्हणून हाक मारू?',
  L10nKeys.onboardingNameHint: 'तुमचे नाव',
  L10nKeys.onboardingRegionTitle: 'तुमचे घर कुठे आहे?',
  L10nKeys.onboardingRegionHint: 'शहर किंवा गाव',
  L10nKeys.onboardingRegionList: 'गुवाहाटी, शिलचर, शिलाँग, आगरतला, इंफाळ, आयझॉल, इटानगर, कोहिमा, गंगटोक, डिब्रुगड, जोरहट, तुमचे शहर',
  L10nKeys.onboardingLanguageTitle: 'तुम्हाला कोणती भाषा आवडेल?',
  L10nKeys.onboardingLanguageBody: 'तुम्ही हे कधीही बदलू शकता.',
  L10nKeys.onboardingFamilyTitle: 'कुटुंब कोण?',
  L10nKeys.onboardingFamilyBody: 'तुमच्या आवडत्या लोकांना जोडा. आम्ही त्यांचे फोटो आणि आवाज हळुवार आठवणी म्हणून दाखवू.',
  L10nKeys.onboardingAddFamily: 'कुटुंबातील सदस्य जोडा',
  L10nKeys.onboardingEmergencyTitle: 'आपत्कालावेळी आम्ही कोणाला बोलवू?',
  L10nKeys.onboardingEmergencyBody: 'SOS बटण दाबल्यास माइंडकेअर तुमच्या कुटुंबाला कळवते, आणीबाणी सेवांना नाही.',
  L10nKeys.onboardingEmergencyName: 'नाव',
  L10nKeys.onboardingEmergencyPhone: 'फोन नंबर',
  L10nKeys.onboardingEmergencyRelation: 'नाते (मुलगी, मुलगा…)',
  L10nKeys.onboardingDoneTitle: 'तुमची बाग तयार आहे!',
  L10nKeys.onboardingDoneBody: 'छोट्या क्रिया पूर्ण करा आणि तुमची बाग वाढताना पहा. आम्ही तुमच्या साथीने आहोत.',
  L10nKeys.onboardingStart: 'माझी बाग सुरू करा',

  L10nKeys.homeWhatsGrowing: 'आज काय वाढत आहे?',
  L10nKeys.homeTodayActivity: 'आजची छोटी क्रिया',
  L10nKeys.homeActivityDuration: 'साधारण ३ मिनिटे',
  L10nKeys.homeMinutes: 'मिनिट',
  L10nKeys.homeMemoryOfDay: 'आजची आठवण',
  L10nKeys.homeMemoryLocked: 'एक खास आठवण वाट पाहत आहे…',
  L10nKeys.homeMemoryUnlocked: 'एक आठवण उघडली!',
  L10nKeys.homeContinueActivity: 'क्रिया सुरू ठेवा',
  L10nKeys.homeFamilyMemory: 'तुमच्या कुटुंबाकडून',
  L10nKeys.homeFamilyMemoryEmpty: 'कुटुंबाच्या आठवणी इथे दिसू शकतात.',
  L10nKeys.homeSos: 'मदत हवी आहे',
  L10nKeys.homeSosSubtitle: 'आपत्कालावेळी कुटुंबाशी संपर्क',
  L10nKeys.homeGardenPreview: 'तुमची बाग',
  L10nKeys.homeEngine: 'माइंडकेअर साथी',
  L10nKeys.homeEngineReady: 'तुमचा मदतनीस तयार आहे.',
  L10nKeys.homeWelcomeBack: 'परत स्वागत! बाग पुढे नेऊया. 🌸',
  L10nKeys.homeNoActivity: 'आज क्रिया नाही',
  L10nKeys.homeNoActivityBody:
      'थोडी विश्रांती घ्या — किंवा हवी ती क्रिया निवडा. 🌻',

  L10nKeys.gardenTitle: 'माझी स्मृती बाग',
  L10nKeys.gardenSectionAll: 'सर्व',
  L10nKeys.gardenSectionFamily: 'कुटुंब',
  L10nKeys.gardenSectionChildhood: 'बालपण',
  L10nKeys.gardenSectionPlaces: 'ठिकाणे',
  L10nKeys.gardenSectionFestivals: 'सण',
  L10nKeys.gardenEmpty: 'तुमची बाग नुकतीच सुरू झाली',
  L10nKeys.gardenEmptyBody: 'पहिली क्रिया पूर्ण करा, इथे एक बी पेरले जाईल.',
  L10nKeys.gardenPoints: 'गुण',
  L10nKeys.gardenLevel: 'स्तर',
  L10nKeys.gardenSeed: 'बी',
  L10nKeys.gardenPlant: 'रोप',
  L10nKeys.gardenFlower: 'फूल',
  L10nKeys.gardenTree: 'झाड',
  L10nKeys.gardenMilestone: 'टप्पा',
  L10nKeys.gardenGrowth: 'वाढत आहे',
  L10nKeys.gardenDidYouKnow: 'प्रत्येक क्रिया पूर्ण केल्यावर तुमची बाग वाढते.',
  L10nKeys.gardenPlantSeed: 'बी पेरा',

  L10nKeys.activitiesTitle: 'क्रिया',
  L10nKeys.activitiesToday: 'आज',
  L10nKeys.activitiesLibrary: 'अधिक क्रिया',
  L10nKeys.mainGamesTitle: 'मुख्य खेळ',
  L10nKeys.activitiesStart: 'सुरू करा',
  L10nKeys.activitiesCompleted: 'पूर्ण झाली',
  L10nKeys.activitiesInProgress: 'सुरू',
  L10nKeys.activitiesNotStarted: 'तयार',
  L10nKeys.activityYoureDone: 'छान होतं!',
  L10nKeys.activityPraise: 'तुम्ही बागेला थोडे जीवन दिले. 🌱',
  L10nKeys.activityHint: 'संकेत हवाय का?',
  L10nKeys.activityTryAgain: 'ही आठवण पुन्हा पाहूया',
  L10nKeys.activityOptionsHint: 'तुमचे उत्तर निवडा',
  L10nKeys.activityTapToMatch: 'एकत्र जुळणारी जोडी निवडा',
  L10nKeys.activityNext: 'पुढे',
  L10nKeys.activityFinish: 'पूर्ण',
  L10nKeys.activityGroupLetsAgain: 'हे पुन्हा पाहूया',
  L10nKeys.activityGroupTogether: 'हे मिळून करूया',
  L10nKeys.activityGreatJob: 'छान केलं!',
  L10nKeys.activityKitchen: 'माझे स्वयंपाकघर',
  L10nKeys.activityShopping: 'माझे दुकान',
  L10nKeys.activityMatching: 'जोडी जुळवा',
  L10nKeys.activitySequence: 'क्रमाने लावा',
  L10nKeys.activityRecognition: 'हे काय?',
  L10nKeys.activityAssociation: 'काय एकत्र येतं?',
  L10nKeys.activityRecall: 'आठवतंय का?',
  L10nKeys.activityAttention: 'शोधा',
  L10nKeys.activityDurationSuffix: 'मिनिट',
  L10nKeys.activityTodayDone: 'आजची क्रिया पूर्ण',
  L10nKeys.activityTodayDoneBody:
      'तुमची बाग वाढली. उद्या एक आठवण वाट पाहत असेल.',
  L10nKeys.activityGardenGrew: 'तुमची बाग वाढली!',
  L10nKeys.activityMemoryUnlocked: 'एक आठवण उघडली',
  L10nKeys.activityReadAloud: 'मोठ्याने वाचा',

  L10nKeys.kitchenTitle: 'चहा करूया',
  L10nKeys.kitchenMakeChai: 'चहा करणे',
  L10nKeys.kitchenMakeChaiPrompt: 'पायऱ्या योग्य क्रमाने निवडा.',
  L10nKeys.kitchenSteps: 'पायऱ्या',
  L10nKeys.kitchenTapInOrder: 'पायऱ्या योग्य क्रमाने निवडा',
  L10nKeys.kitchenCorrectOrder: 'छान! चहा तयार!',
  L10nKeys.kitchenBreakfast: 'नाश्ता करणे',
  L10nKeys.kitchenBreakfastHint: 'दिवसाची ताजी सुरुवात',
  L10nKeys.kitchenBreakfastPrompt: 'नाश्त्याच्या पायऱ्या क्रमाने लावा.',

  L10nKeys.shopTitle: 'माझे दुकान',
  L10nKeys.shopGetMilkBread: 'ब्रेड आणि दूध',
  L10nKeys.shopGetMilkBreadPrompt: '₹१०० मध्ये दूध आणि ब्रेड घ्या.',
  L10nKeys.shopBudget: 'बजेट',
  L10nKeys.shopBasket: 'तुमची टोपली',
  L10nKeys.shopTotal: 'एकूण',
  L10nKeys.shopWithinBudget: 'बजेटमध्ये!',
  L10nKeys.shopOverBudget: 'बजेटच्या पलीकडे — पुन्हा पहा',
  L10nKeys.shopCheckout: 'पूर्ण करा आणि पैसे द्या',
  L10nKeys.shopBuy: 'टोपलीत टाका',
  L10nKeys.shopSell: 'काढा',
  L10nKeys.shopVeggies: 'रात्रीच्या जेवणासाठी भाज्या',
  L10nKeys.shopVeggiesPrompt: '₹६० मध्ये बटाटे आणि कांदे घ्या.',
  L10nKeys.recKitchenItem: 'हे कोणते?',
  L10nKeys.recKitchenItemPrompt:
      'बाजारातून सामान आणण्यासाठी यांपैकी कोणता वापरतो?',
  L10nKeys.recCurrency: 'थोडे पैसे',
  L10nKeys.recCurrencyPrompt: 'कोणती नोट ₹२० आहे?',
  L10nKeys.matchFestival: 'सण जुळवा',
  L10nKeys.matchFestivalPrompt: 'प्रत्येक सण त्याच्या खास पदार्थाशी जुळवा.',
  L10nKeys.matchObjectUse: 'जोडी जुळवा',
  L10nKeys.matchObjectUsePrompt:
      'प्रत्येक वस्तू तिच्या वापराच्या वेळेशी जुळवा.',
  L10nKeys.seqMorning: 'सकाळचा नित्यक्रम',
  L10nKeys.seqMorningPrompt: 'तुमचा सकाळचा नित्यक्रम क्रमाने लावा.',
  L10nKeys.seqRoute: 'सकाळचा प्रवास',
  L10nKeys.seqRoutePrompt: 'बाजारापर्यंतचा प्रवास क्रमाने लावा.',
  L10nKeys.assoRegion: 'इथे काय आहे?',
  L10nKeys.assoRegionPrompt: 'आसाम कशासाठी प्रसिद्ध आहे?',
  L10nKeys.assoHarvest: 'गोड फळ',
  L10nKeys.assoHarvestPrompt: 'कोणत्या फळाला उन्हाळ्याचा राजा म्हणतात?',
  L10nKeys.attnVeg: 'गाजर शोधा',
  L10nKeys.attnVegPrompt: 'गाजर सापडेल का?',
  L10nKeys.recallSong: 'एक ओळखीचे गाणे',
  L10nKeys.recallSongPrompt: 'बिहूमध्ये नर्तक कोणत्या गाण्यावर नाचतात?',
  L10nKeys.activityPairs: 'जोडी शोधा',
  L10nKeys.activitySequenceRecall: 'क्रम लक्षात ठेवा',
  L10nKeys.activityFindChanged: 'काय बदलले?',
  L10nKeys.pairsFruits: 'बाजारातील फळे',
  L10nKeys.pairsKitchen: 'स्वयंपाकघरातील वस्तू',
  L10nKeys.pairsRemember: 'सर्व कार्ड काळजीपूर्वक पहा, मग एकसारखी जोडी शोधा.',
  L10nKeys.pairsStart: 'कार्ड लपवून सुरू करा',
  L10nKeys.pairsFound: 'जोडी सापडली!',
  L10nKeys.seqRecallItems: 'रोजच्या वस्तू',
  L10nKeys.seqRecallNumbers: 'क्रमाने आकडे',
  L10nKeys.seqRecallWatch: 'कार्ड काळजीपूर्वक पहा – प्रत्येक क्रमाने उजळेल.',
  L10nKeys.seqRecallRepeat: 'आता तोच क्रम पुन्हा करा जो तुम्ही पाहिला.',
  L10nKeys.changeMarket: 'फळांची टोपली',
  L10nKeys.changeFestival: 'सणाचे दिवे',
  L10nKeys.changeRemember: 'ही चित्रे काळजीपूर्वक लक्षात ठेवा.',
  L10nKeys.changeFind: 'एक चित्र बदलले आहे. वेगळे चित्र शोधा.',
  L10nKeys.changeCorrect: 'छान! तेच बदलले होते.',

  L10nKeys.mysteryTitle: 'आजची खास आठवण',
  L10nKeys.mysteryLocked: 'एक खास आठवण तुमची वाट पाहत आहे…',
  L10nKeys.mysteryLockedBody:
      'आज २-३ छोट्या क्रिया करा, कदाचित ती उघडेल. ती काय असेल?',
  L10nKeys.mysteryUnlocked: 'तुमची खास आठवण इथे आहे!',
  L10nKeys.mysteryUnlockedBody: 'ही आठवण फक्त तुमच्यासाठी आहे. वेळ घ्या. 🌸',
  L10nKeys.mysteryCuriosity: 'आज काय उघडेल?',
  L10nKeys.mysteryOpen: 'आठवण उघडा',

  L10nKeys.memoriesTitle: 'माझ्या आठवणी',
  L10nKeys.memoriesEmpty: 'अजून आठवणी नाहीत',
  L10nKeys.memoriesEmptyBody: 'तुमचे कुटुंब फोटो आणि ध्वनी संदेश जोडू शकते. उपलब्ध झाल्यावर ते इथे दिसतील.',
  L10nKeys.memoriesFamily: 'कुटुंब',
  L10nKeys.memoriesPlaces: 'ठिकाणे',
  L10nKeys.memoriesFestivals: 'सण',
  L10nKeys.memoriesChildhood: 'बालपण',
  L10nKeys.memoriesKindPhoto: 'फोटो',
  L10nKeys.memoriesKindVoice: 'ध्वनी संदेश',
  L10nKeys.memoriesKindText: 'गोष्ट',
  L10nKeys.memoriesKindSound: 'आवाज',
  L10nKeys.memoriesKindPlace: 'ठिकाण',
  L10nKeys.memoriesAddedBy: 'जोडले',
  L10nKeys.memoriesWhoIsThis: 'हे कोण आहेत?',
  L10nKeys.memoriesPlayVoice: 'ऐका',
  L10nKeys.memoriesThisIsMe: 'हा मी आहे',
  L10nKeys.memoriesNotMe: 'मी नाही',

  L10nKeys.profileTitle: 'प्रोफाइल',
  L10nKeys.profileLanguage: 'अ‍ॅपची भाषा',
  L10nKeys.profileRegion: 'माझा प्रदेश',
  L10nKeys.profileVoiceLanguage: 'आवाजाची भाषा',
  L10nKeys.profileVoicePrompts: 'आवाजाचे संकेत',
  L10nKeys.profileTextSize: 'अक्षरांचा आकार',
  L10nKeys.profileReducedMotion: 'शांत गती',
  L10nKeys.profileSoundEffects: 'ध्वनी प्रभाव',
  L10nKeys.profileFamily: 'कुटुंब',
  L10nKeys.profileContacts: 'आपत्कालीन संपर्क',
  L10nKeys.profileDemoMode: 'डेमो मोड',
  L10nKeys.profileReminders: 'स्मरणपत्रे',
  L10nKeys.profileNeedHelp: 'मदत हवी आहे का?',

  L10nKeys.remindersTitle: 'स्मरणपत्रे',
  L10nKeys.remindersEmpty: 'अजून स्मरणपत्रे नाहीत',
  L10nKeys.remindersNew: 'नवीन स्मरणपत्र',
  L10nKeys.remindersTitleLabel: 'शीर्षक',
  L10nKeys.remindersDetailLabel: 'तपशील (ऐच्छिक)',
  L10nKeys.remindersTime: 'वेळ',
  L10nKeys.remindersDays: 'दिवस',
  L10nKeys.remindersEveryday: 'रोज',
  L10nKeys.remindersEnabled: 'चालू',
  L10nKeys.remindersMedicine: 'औषध',
  L10nKeys.remindersAppointment: 'भेट',
  L10nKeys.remindersRoutine: 'दैनंदिन नित्यक्रम',

  L10nKeys.dayMon: 'सोम',
  L10nKeys.dayTue: 'मंगळ',
  L10nKeys.dayWed: 'बुध',
  L10nKeys.dayThu: 'गुरु',
  L10nKeys.dayFri: 'शुक्र',
  L10nKeys.daySat: 'शनी',
  L10nKeys.daySun: 'रवि',

  L10nKeys.sosTitle: 'आपत्कालीन मदत',
  L10nKeys.sosExplain: 'दाबून धरा. माइंडकेअर तुमच्या आपत्कालीन संपर्कांना एकेक करून कळवेल. ही आणीबाणी सेवा (जसे ११२) नाही.',
  L10nKeys.sosHold: 'मदतीसाठी दाबून धरा',
  L10nKeys.sosHoldBody: 'दाबून धरा…',
  L10nKeys.sosActiveTitle: 'मदतीशी संपर्क साधला जात आहे',
  L10nKeys.sosActiveBody: 'तुमच्या कुटुंबाला कळवले आहे. त्यांनी प्रतिसाद न दिल्यास पुढील संपर्काला बोलावले जाईल.',
  L10nKeys.sosContacting: 'संपर्क साधत आहे',
  L10nKeys.sosContactFamily: 'कुटुंबाशी संपर्क',
  L10nKeys.sosContacted: 'संपर्क झाला',
  L10nKeys.sosWaitingResponse: 'प्रतिसादाची वाट पाहत आहे…',
  L10nKeys.sosEscalating: 'पुढील व्यक्तीशी संपर्क…',
  L10nKeys.sosCancelled: 'मदतीची विनंती रद्द',
  L10nKeys.sosCancelAction: 'मदतीची विनंती रद्द करा',
  L10nKeys.sosDone: 'झाले',
  L10nKeys.sosHelpOnWay: 'लवकरच कोणीतरी तुमच्यासोबत असेल. 🧡',
  L10nKeys.sosNoContacts: 'अजून आपत्कालीन संपर्क नाहीत',
  L10nKeys.sosNoContactsBody:
      'कृपया कुटुंबाला आपत्कालीन संपर्क जोडण्यास सांगा.',
  L10nKeys.sosAddContact: 'संपर्क जोडा',
  L10nKeys.sosDisclaimer: 'माइंडकेअर तुमच्या निवडलेल्या संपर्कांना कळवते. ती अधिकृत आपत्कालीन सेवांचा पर्याय नाही.',
  L10nKeys.sosContactedPerson: 'कुटुंबातील सदस्याशी संपर्क झाला',
  L10nKeys.sosEscalatedTo: 'पुढील कुटुंबातील सदस्याशी संपर्क झाला',
  L10nKeys.sosAcknowledged:
      'कुटुंबातील सदस्याने प्रतिसाद दिला आहे. मदत येत आहे.',
  L10nKeys.sosNotSilent:
      'मदत पाठवता न आली तर आम्ही कधीही पाठवली असल्याचे भासवणार नाही.',
  L10nKeys.sosAlertNotDelivered:
      'तुमचा संदेश अजून पाठवता आलेला नाही. आम्ही प्रयत्न करत राहू.',

  L10nKeys.careTitle: 'काळजीवाहक',
  L10nKeys.careDashboard: 'आढावा',
  L10nKeys.carePatients: 'माझे रुग्ण',
  L10nKeys.careMemories: 'आठवणी',
  L10nKeys.careContacts: 'आपत्कालीन संपर्क',
  L10nKeys.careSettings: 'सेटिंग्ज',
  L10nKeys.careAddMemory: 'आठवण जोडा',
  L10nKeys.careAddContact: 'संपर्क जोडा',
  L10nKeys.careEngagement: 'सहभाग',
  L10nKeys.careActivitiesWeek: 'या आठवड्यातील क्रिया',
  L10nKeys.careGardenProgress: 'बागेची प्रगती',
  L10nKeys.careRecentActivity: 'अलीकडील क्रिया',
  L10nKeys.careNoPatients: 'जोडलेले रुग्ण नाहीत',
  L10nKeys.careNoPatientsBody:
      'कुटुंबातील सदस्याला जोडण्यास सांगा, किंवा रुग्ण प्रोफाइल जोडा.',
  L10nKeys.careAddPatient: 'रुग्ण जोडा',
  L10nKeys.carePerformanceNote: 'अलीकडे या व्यक्तीची क्रिया कामगिरी त्यांच्या नेहमीच्या पातळीपेक्षा किंचित कमी आहे.',
  L10nKeys.careUploadPhoto: 'फोटो अपलोड करा',
  L10nKeys.careRecordVoice: 'आवाज रेकॉर्ड करा',
  L10nKeys.careWriteMemory: 'आठवण लिहा',
  L10nKeys.careMemoryTitle: 'शीर्षक',
  L10nKeys.careMemoryCaption: 'कॅप्शन',
  L10nKeys.careMemoryRelation: 'यात कोण आहे? (नाते)',
  L10nKeys.careMemoryCategory: 'श्रेणी',
  L10nKeys.careContactName: 'नाव',
  L10nKeys.careContactPhone: 'फोन नंबर',
  L10nKeys.careContactPriority: 'कॉल क्रम',
  L10nKeys.careContactRelation: 'नाते',
  L10nKeys.careEscalationTimeout: 'पुढील संपर्कापूर्वीचे मिनिटे',
  L10nKeys.careIncidentStatus: 'स्थिती',
  L10nKeys.careAckSos: 'मी प्रतिसाद देत आहे',
  L10nKeys.careResponding: 'प्रतिसाद देत आहे',
  L10nKeys.careActiveAlerts: 'सक्रिय सूचना',

  L10nKeys.syncSavingOffline: 'ऑफलाइन',
  L10nKeys.syncSavingOfflineBody: 'तुमच्या क्रिया या डिव्हाइसवर सुरक्षित आहेत.',
  L10nKeys.syncSynced: 'सिंक झाले',
  L10nKeys.syncInfo: 'तुमची माहिती सिंक झाली आहे.',
  L10nKeys.syncPending: 'सिंकची वाट पाहत आहे',

  L10nKeys.errorGeneric: 'काहीतरी चूक झाली',
  L10nKeys.errorGenericBody:
      'तुमची प्रगती सुरक्षित आहे. कृपया पुन्हा प्रयत्न करा.',
  L10nKeys.errorAudio: 'या डिव्हाइसवर आवाज चालवता आला नाही.',
  L10nKeys.errorPermission: 'यासाठी डिव्हाइसची परवानगी आवश्यक आहे.',
  L10nKeys.errorNoInternetAction:
      'इंटरनेटची गरज नाही — ते प्रथम येथेच जतन होते.',

  L10nKeys.demoWelcome: 'डेमो पहा',
  L10nKeys.demoExplain:
      'तुम्ही पाहू शकता म्हणून नमुना कुटुंब आणि आठवणी जोडल्या जातील.',
  L10nKeys.demoLoad: 'डेमो बाग लोड करा',

  L10nKeys.unitsPoints: 'गुण',
  L10nKeys.teaserChai: 'चहा करूया.',
  L10nKeys.familiarityName: 'आशा',
  L10nKeys.regionMap: 'माझा प्रदेश',
  L10nKeys.regionChoose: 'तुमचा प्रदेश निवडा',
  L10nKeys.regionIndia: 'भारत',
  L10nKeys.importantMemory: 'महत्वाची आठवण',
  L10nKeys.growing: 'वाढत आहे',
  L10nKeys.blooming: 'फुलत आहे',
  L10nKeys.mature: 'प्रौढ',
  L10nKeys.noVoice: 'या डिव्हाइसवर आवाज उपलब्ध नाही.',
  L10nKeys.optional: 'ऐच्छिक',

  L10nKeys.langChoose: 'भाषा निवडा',
  L10nKeys.langPrimary: 'मुख्य',
  L10nKeys.langNorthEast: 'उत्तर-पूर्व भारत',
  L10nKeys.langMajor: 'भारतातील प्रमुख भाषा',

  L10nKeys.authSignUpTitle: 'तुमचे खाते तयार करा',
  L10nKeys.authSignUpBody: 'हे माइंडकेअर प्रोफाइल तुमच्या डिव्हाइसवर सुरक्षित राहील. फक्त तुम्हीच उघडू शकता म्हणून यूजरनेम आणि पासवर्ड वापरा.',
  L10nKeys.authLoginTitle: 'परत स्वागत',
  L10nKeys.authLoginBody:
      'तुमची बाग उघडण्यासाठी यूजरनेम आणि पासवर्डने साइन इन करा.',
  L10nKeys.authUsername: 'यूजरनेम',
  L10nKeys.authUsernameHint: 'जसे: ranu123',
  L10nKeys.authDisplayName: 'तुमचे नाव',
  L10nKeys.authPassword: 'पासवर्ड',
  L10nKeys.authPasswordHint: 'किमान ६ अक्षरे',
  L10nKeys.authConfirmPassword: 'पासवर्डची पुष्टी करा',
  L10nKeys.authRoleQuestion: 'हे प्रोफाइल कशासाठी आहे…',
  L10nKeys.authRolePatient: 'माझ्यासाठी',
  L10nKeys.authRoleCaregiver: 'कुटुंबातील सदस्यासाठी',
  L10nKeys.authCreate: 'खाते तयार करा',
  L10nKeys.authSignIn: 'साइन इन',
  L10nKeys.authSignOut: 'साइन आउट',
  L10nKeys.authAccount: 'खाते',
  L10nKeys.caregiverTitle: 'काळजी घेणारे',
  L10nKeys.caregiverNotLinked: 'अजून कुणी काळजी घेणारे जोडलेले नाही',
  L10nKeys.authBadCredentials: 'यूजरनेम किंवा पासवर्ड चुकीचा आहे.',
  L10nKeys.authUsernameTaken: 'हे यूजरनेम या डिव्हाइसवर आधीच वापरात आहे.',
  L10nKeys.authPasswordMismatch: 'पासवर्ड जुळत नाहीत.',
  L10nKeys.authUsernameShort: 'यूजरनेम किमान ३ अक्षरांचे असावे.',
  L10nKeys.authUsernameInvalid:
      'फक्त अक्षरे, संख्या, बिंदू, डॅश किंवा अंडरस्कोर वापरा.',
  L10nKeys.authPasswordShort: 'पासवर्ड किमान ६ अक्षरांचा असावा.',
  L10nKeys.authNameRequired: 'कृपया नाव प्रविष्ट करा.',
  L10nKeys.authSignOutConfirm: 'या प्रोफाइलमधून साइन आउट करू का?',
  L10nKeys.screenTitle: 'त्वरित स्मृती तपासणी',
  L10nKeys.screenIntro: 'आम्ही रुग्णाबद्दल काही छोटे प्रश्न विचारू. गेल्या काही महिन्यांत ते कसे होते ते विचार करा.',
  L10nKeys.screenNotSure: 'नक्की माहीत नाही',
  L10nKeys.screenFinish: 'माझा निकाल पहा',
  L10nKeys.screenSkip: 'आत्ता सोडा',
  L10nKeys.screenResultBack: 'झाले',
  L10nKeys.screenCheckAgain: 'पुन्हा तपासा',
  L10nKeys.screenStartCheckup: 'तपासणी सुरू करा',
  L10nKeys.screenSkipped: 'तपासणी सोडली',
  L10nKeys.screenStatusGood: 'सर्व काही व्यवस्थित दिसते',
  L10nKeys.screenStatusGoodBody: 'कोणतीही मोठी चिंता दिसली नाही. दैनंदिन गोष्टी करत राहा, आणि काही बदलल्यास कधीही पुन्हा तपासू शकता.',
  L10nKeys.screenStatusWatch: 'काही बदल दिसले',
  L10nKeys.screenStatusWatchBody: 'विसरण्याचे काही क्षण दिसले. हे वयानुसार सामान्य आहे, पण लक्ष ठेवा आणि पुढच्या डॉक्टर भेटीत सांगा.',
  L10nKeys.screenStatusDoctor: 'कृपया तपासणी करून घ्या',
  L10nKeys.screenStatusDoctorBody: 'काही चिन्हे दिसली ज्यांकडे लक्ष देण्याची गरज असू शकते. कृपया ही डॉक्टर किंवा क्लिनिकला सांगा जेणेकरून ते मदत करू शकतील.',
  L10nKeys.screenRarely: 'क्वचित',
  L10nKeys.screenSometimes: 'कधी कधी',
  L10nKeys.screenFrequently: 'अनेकदा',
  L10nKeys.screenVeryFrequently: 'खूप वेळा',
  L10nKeys.screenQ01: 'त्यांना अलीकडच्या घटना लक्षात ठेवण्यात अडचण येते का?',
  L10nKeys.screenQ02: 'ते तेच प्रश्न किंवा गोष्टी पुन्हा विचारतात का?',
  L10nKeys.screenQ03: 'ते परिचित लोकांची नावे विसरतात का?',
  L10nKeys.screenQ04: 'त्यांना परिचित चेहरे ओळखण्यात अडचण येते का?',
  L10nKeys.screenQ05: 'ते भेटी किंवा महत्त्वाच्या घटना विसरतात का?',
  L10nKeys.screenQ06: 'त्यांना योग्य शब्द सापडण्यात अडचण येते का?',
  L10nKeys.screenQ07: 'ते कुठे आहेत याबद्दल गोंधळतात का?',
  L10nKeys.screenQ08: 'त्यांना दैनंदिन कामांसाठी आठवण करून द्यावी लागते का?',
  L10nKeys.screenQ09: 'त्यांना औषधे सांभाळण्यात अडचण येते का?',
  L10nKeys.screenQ10: 'ते गोंधळल्यावर चिंताग्रस्त किंवा चिडतात का?',
  L10nKeys.screenQ11: 'त्यांना संभाषण समजण्यात अडचण येते का?',
  L10nKeys.screenQ12: 'त्यांना परिचित कामे पूर्ण करण्यात अडचण येते का?',
  L10nKeys.screenQ13: 'ते विसरतात का रोजच्या वस्तू कुठे ठेवलेल्या आहेत?',
  L10nKeys.screenQ14: 'त्यांना सूचना लक्षात ठेवण्यात अडचण येते का?',
  L10nKeys.screenQ15: 'त्यांना बहु-चरणीय कामे करण्यात अडचण येते का?',

  L10nKeys.careDashboardSubtitle: 'कुटुंबाची काळजी',
  L10nKeys.careSosLive: 'थेट सूचना',
  L10nKeys.careSosRespondedBy: '{name} यांनी उत्तर दिले',
  L10nKeys.careLinkTitle: 'कुटुंबातील सदस्याशी संपर्क करा',
  L10nKeys.careLinkBody: 'आपल्या प्रिय व्यक्तीला त्यांच्या फोनवर दिसणारा 6-अक्षरी कौटुंबिक कोड विचारा, नंतर संपर्क करा.',
  L10nKeys.careLinkCode: 'कौटुंबिक कोड',
  L10nKeys.careLinkCodeHint: 'उदा. A1B2C3',
  L10nKeys.careLinkConnect: 'संपर्क',
  L10nKeys.careLinkDone: 'जोडले',
  L10nKeys.careLinkSuccess: '{name} शी जोडले! आठवणी आणि सूचना आता सिंक होतील.',
  L10nKeys.careLinkFailed:
      'संपर्क होऊ शकला नाही. कृपया कोड तपासून पुन्हा प्रयत्न करा.',
  L10nKeys.careTrendsTitle: 'AI कल',
  L10nKeys.careTrendsBody: 'क्रियाकलाप प्रकारानुसार दैनिक अचूकता',
  L10nKeys.careTrendsNoData:
      'अजून क्रियाकलाप नाही — कल पाहण्यासाठी एक व्यायाम पूर्ण करा.',
  L10nKeys.careAiDifficulty: 'स्वयं-समायोजित अडचण',
  L10nKeys.careAiAccuracy: 'मॉडेल अचूकता',
  L10nKeys.careAiRealSessions: 'वास्तविक सत्रे',
  L10nKeys.careAiDemoSessions: 'डेमो सत्रे',
  L10nKeys.careNavGames: 'खेळ',
  L10nKeys.careNavRoutine: 'रुटीन',
  L10nKeys.careGreetSubtitle: 'आज {name} कसे आहेत, हे येथे पहा.',
  L10nKeys.careNotifEmpty: 'कोणत्याही नवीन सूचना नाहीत',
  L10nKeys.careWellnessScore: 'संज्ञानात्मक कल्याण स्कोअर',
  L10nKeys.careStatusStable: 'स्थिर',
  L10nKeys.careStatusAttention: 'लक्ष आवश्यक',
  L10nKeys.careLastSynced: 'शेवटचे सिंक {time}',
  L10nKeys.careMinAgo: '{n} मिनिटांपूर्वी',
  L10nKeys.careGamesWeek: 'या आठवड्यातील खेळ',
  L10nKeys.careRoutineCompletion: 'रुटीन पूर्तता',
  L10nKeys.careCurrentStreak: 'सध्याचा स्ट्रीक',
  L10nKeys.careMoodCheckins: 'मूड चेक-इन',
  L10nKeys.careDayUnit: 'दिवस',
  L10nKeys.careDaysUnit: 'दिवस',
  L10nKeys.careActivityTitle: 'साप्ताहिक क्रियाकलाप',
  L10nKeys.careWeekly: 'साप्ताहिक',
  L10nKeys.careMonthly: 'मासिक',
  L10nKeys.careNoActivityWeek:
      'या आठवड्यात अद्याप कोणताही क्रियाकलाप नोंदवलेला नाही.',
  L10nKeys.careMoodTitle: 'मूड',
  L10nKeys.careMoodHappy: 'आनंदी',
  L10nKeys.careMoodCalm: 'शांत',
  L10nKeys.careMoodNeutral: 'तटस्थ',
  L10nKeys.careMoodLow: 'कमी',
  L10nKeys.careMood7Days: 'शेवटचे ७ दिवस',
  L10nKeys.careMoodInsight: '{name} या आठवड्यात बहुतेक शांत होते, शेवटच्या दोन दिवसांत सौम्य घट झाली आहे.',
  L10nKeys.careMoodNoData: 'या आठवड्यात अद्याप कोणतेही मूड चेक-इन नाही.',
  L10nKeys.careSkillsTitle: 'संज्ञानात्मक कौशल्ये',
  L10nKeys.careSkillMemory: 'स्मृती',
  L10nKeys.careSkillAttention: 'लक्ष',
  L10nKeys.careSkillLanguage: 'भाषा',
  L10nKeys.careSkillReasoning: 'तर्कशक्ती',
  L10nKeys.careSkillProcessing: 'प्रक्रिया गती',
  L10nKeys.careInsightToday: 'आजची अंतर्दृष्टी',
  L10nKeys.careInsightBody: 'रॉबर्ट सकाळच्या रुटीननंतर स्मृती क्रियाकलापांमध्ये सातत्याने सक्रिय आहेत. गेल्या दोन दिवसांत त्यांचा मूड किंचित कमी राहिला आहे.',
  L10nKeys.careInsightBodyReal: 'या आठवड्यात {name} ने {count} संज्ञानात्मक सत्रे पूर्ण केली (लक्ष्य {goal}) आणि {streak} दिवसांचा स्ट्रीक कायम ठेवला आहे.',
  L10nKeys.careViewDetails: 'तपशील पहा',
  L10nKeys.careInsightDisclaimer:
      'हे डेटावरील सौम्य निरीक्षण आहे — वैद्यकीय निदान नाही.',
  L10nKeys.careAttentionTitle: 'तुमचे लक्ष आवश्यक',
  L10nKeys.careAttentionEmpty:
      'सध्या तुमच्या लक्षाची आवश्यकता असणारी काहीही नाही.',
  L10nKeys.careAlertSos: '{name} ने SOS बटण दाबले',
  L10nKeys.careAlertRoutineMissed: 'काल रुटीन चुकली',
  L10nKeys.careAlertMoodDown: 'गेल्या दोन दिवसांत मूड घटला आहे',
  L10nKeys.careAlertSessionPending: 'आज संज्ञानात्मक सत्र पूर्ण झाले नाही',
  L10nKeys.careAlertSeverityHigh: 'उच्च',
  L10nKeys.careAlertSeverityMedium: 'मध्यम',
  L10nKeys.careAlertSeverityLow: 'कमी',
  L10nKeys.careWeeklySummary: 'साप्ताहिक सारांश',
  L10nKeys.careSessionsCompleted: 'पूर्ण केलेली सत्रे',
  L10nKeys.careAvgSessionDuration: 'सरासरी सत्र कालावधी',
  L10nKeys.careRoutineAdherence: 'रुटीन पाळणे',
  L10nKeys.careMoodTrend: 'मूड कल',
  L10nKeys.careMoodTrendSlightlyDown: 'किंचित कमी',
  L10nKeys.careMoodTrendStable: 'स्थिर',
  L10nKeys.careMoodTrendUp: 'सुधारत आहे',
  L10nKeys.careVsLastWeek: 'मागील आठवड्याच्या तुलनेत',
  L10nKeys.careSyncedJustNow: 'नुकतेच सिंक झाले',
  L10nKeys.careOfflineWaiting:
      'ऑफलाइन · {count} क्रियाकलाप सिंकच्या प्रतीक्षेत',
  L10nKeys.careComingSoon: 'लवकरच येत आहे',
  L10nKeys.careHomeSoon:
      '{name} च्या दिवसाचे संक्षिप्त विहंगावलोकन येथे दिसेल.',
  L10nKeys.careGamesSoon: 'खेळ आणि सत्र इतिहास येथे दिसेल.',
  L10nKeys.careRoutineSoon: 'रुग्णाची दैनंदिन रुटीन येथे दिसेल.',
  L10nKeys.careProfileSoon: 'काळजीवाहक प्रोफाइल आणि सेटिंग्ज येथे दिसतील.',
  L10nKeys.serverPairingTitle: 'कौटुंबिक कोड',
  L10nKeys.serverPairingBody: 'हा कोड कोणत्याही काळजीवाहकाशी सामायिक करा जेणेकरून ते आपल्याशी संपर्क साधू शकतील.',
  L10nKeys.serverUnlinked: 'सर्व्हरशी कनेक्ट नाही',
  L10nKeys.serverLinked: 'सर्व्हरशी कनेक्ट',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
