import '../l10n_keys.dart';

/// Mizo dictionary (best-effort machine-assisted translation; native review required).
/// Core food-market terms corroborated against xobdo.org, Glosbe.
/// (Dictionary of the Lushai language) and PolyTranslator.
/// Untranslated keys automatically fall back to English.
const Map<String, String> stringsLus = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'I hriatna ruahman paa',
  L10nKeys.back: 'Kir leh',
  L10nKeys.next: 'Hmasawn',
  L10nKeys.continueText: 'Hmasa zawh',
  L10nKeys.skip: 'Bojuhtir',
  L10nKeys.done: 'Zawh',
  L10nKeys.cancel: 'Tihbawrh',
  L10nKeys.yes: 'Aw',
  L10nKeys.no: 'Aih',
  L10nKeys.save: 'Khawi',
  L10nKeys.close: 'Khar',
  L10nKeys.retry: 'Beisei leh',
  L10nKeys.add: 'Dah belh',
  L10nKeys.edit: 'Ziam thar',
  L10nKeys.remove: 'Lak bo',
  L10nKeys.search: 'Zawng',
  L10nKeys.today: 'Vawiin',
  L10nKeys.offline: 'Internet nei lo',
  L10nKeys.online: 'Internet hman',

  L10nKeys.goodMorning: 'Chibai',
  L10nKeys.goodAfternoon: 'Chibai nuam',
  L10nKeys.goodEvening: 'Chibai tlak le',
  L10nKeys.goodNight: 'Zan tha',

  L10nKeys.navHome: 'In',
  L10nKeys.navGarden: 'Huan',
  L10nKeys.navActivities: 'Sorkip',
  L10nKeys.navMemories: 'Hriatna',
  L10nKeys.navProfile: 'Profile',
  L10nKeys.navMystery: 'Vawiin hriatna',

  L10nKeys.onboardingWelcomeTitle: 'I hriatna ngaithlak ruahman',
  L10nKeys.onboardingWelcomeBody: 'Companio chuan internet tel lo pawhin i hriat theihna, sorkip leh chhungkua nen inzawm sak thei a.',
  L10nKeys.onboardingNameTitle: 'Hei hian eng angin nge kan ko?',
  L10nKeys.onboardingNameHint: 'I hming',
  L10nKeys.onboardingRegionTitle: 'I in khi khawiah nge?',
  L10nKeys.onboardingRegionHint: 'Khua leh ram',
  L10nKeys.onboardingRegionList: 'Aizawl, Lunglei, Champhai, Kolasib, Serchhip, Lawngtlai, Saiha, Guwahati, Shillong, Agartala, Imphal',
  L10nKeys.onboardingLanguageTitle: 'Eng tarak nge i hmang duh?',
  L10nKeys.onboardingLanguageBody: 'Hei hi a hunah i thlak thei ang.',
  L10nKeys.onboardingFamilyTitle: 'Chhungkua chu tu nge?',
  L10nKeys.onboardingFamilyBody: 'I hmangaihte chu phuah ve rawh. An hnamphu leh an aw awktir chu hriatna nuamah i hmuh ang.',
  L10nKeys.onboardingAddFamily: 'Chhungkua pakhat belh',
  L10nKeys.onboardingEmergencyTitle: 'Harsatna ah tu nge i ko duh?',
  L10nKeys.onboardingEmergencyBody: 'SOS button i beih chuan Companio chuan i chhungkua te chu a ko dawn — emergency service kha a ni lo.',
  L10nKeys.onboardingEmergencyName: 'Hming',
  L10nKeys.onboardingEmergencyPhone: 'Phone number',
  L10nKeys.onboardingEmergencyRelation: 'Inpawhna (fanu, fapa…)',
  L10nKeys.onboardingDoneTitle: 'I huan chu a inpeih e!',
  L10nKeys.onboardingDoneBody: 'Sorkip te leh i huan a lo hlawitu te, anmahni en san chhin. Kan hnenah kan awm e.',
  L10nKeys.onboardingStart: 'Ka huan ngei lo phawt ang',

  L10nKeys.homeWhatsGrowing: 'Vawiin eng nge a lo hlawi?',
  L10nKeys.homeTodayActivity: 'Vawiin sorkip te',
  L10nKeys.homeActivityDuration: 'Minit 3 vel',
  L10nKeys.homeMinutes: 'minit',
  L10nKeys.homeMemoryOfDay: 'Vawiin hriatna',
  L10nKeys.homeMemoryLocked: 'Hriatna a hnathawh tak chuan a lo ngaitu tih…',
  L10nKeys.homeMemoryUnlocked: 'Hriatna a lo hawng e!',
  L10nKeys.homeContinueActivity: 'Sorkip chhunzawm',
  L10nKeys.homeFamilyMemory: 'I chhungkua ata',
  L10nKeys.homeFamilyMemoryEmpty:
      'Chhungkua hriatna chu hetah hian a lang ang.',
  L10nKeys.homeSos: 'Tanpuina ka mamawh',
  L10nKeys.homeSosSubtitle: 'Harsatna a chhungkua ko',
  L10nKeys.homeGardenPreview: 'I huan',
  L10nKeys.homeEngine: 'Companio partner',
  L10nKeys.homeEngineReady: 'I tanpui tu a inpeih e.',
  L10nKeys.homeWelcomeBack: 'Lo kir leh e! I huan chhunzawm ang. 🌸',
  L10nKeys.homeNoActivity: 'Vawiin sorkip a awm lo',
  L10nKeys.homeNoActivityBody:
      'Chawl ve e — nge i hlim tak sorkip ah rawn thlang. 🌻',

  L10nKeys.gardenTitle: 'Ka hriatna huan',
  L10nKeys.gardenSectionAll: 'Apo',
  L10nKeys.gardenSectionFamily: 'Chhungkua',
  L10nKeys.gardenSectionChildhood: 'Naupang hun',
  L10nKeys.gardenSectionPlaces: 'Hmun',
  L10nKeys.gardenSectionFestivals: 'Kut',
  L10nKeys.gardenEmpty: 'I huan a lo inpeih thung',
  L10nKeys.gardenEmptyBody:
      'A hmasa ber sorkip zawh la, hetah chihte a lo to ang.',
  L10nKeys.gardenPoints: 'Beng',
  L10nKeys.gardenLevel: 'Ram',
  L10nKeys.gardenSeed: 'Chihte',
  L10nKeys.gardenPlant: 'Thing',
  L10nKeys.gardenFlower: 'Par',
  L10nKeys.gardenTree: 'Kung',
  L10nKeys.gardenMilestone: 'Thlan thang',
  L10nKeys.gardenGrowth: 'Lo hlawi',
  L10nKeys.gardenDidYouKnow: 'Sorkip zawh apiangin i huan a lo hlawi zel.',
  L10nKeys.gardenPlantSeed: 'Chihte tuh',

  L10nKeys.activitiesTitle: 'Sorkip',
  L10nKeys.activitiesToday: 'Vawiin',
  L10nKeys.activitiesLibrary: 'Sorkip dang',
  L10nKeys.mainGamesTitle: 'Game pawimawhte',
  L10nKeys.activitiesStart: 'Phawt',
  L10nKeys.activitiesCompleted: 'A zawh',
  L10nKeys.activitiesInProgress: 'Meuhchhuak',
  L10nKeys.activitiesNotStarted: 'Inpeih',
  L10nKeys.activityYoureDone: 'Tha tak!',
  L10nKeys.activityPraise: 'I huanah hringnun te i phuh e. 🌱',
  L10nKeys.activityHint: 'Beisei mamawh?',
  L10nKeys.activityTryAgain: 'He hriatna hi i ngaihven leh ang',
  L10nKeys.activityOptionsHint: 'I chhanna thlang',
  L10nKeys.activityTapToMatch: 'Inmil tur thlang',
  L10nKeys.activityNext: 'Hmasawn',
  L10nKeys.activityFinish: 'Zawh',
  L10nKeys.activityGroupLetsAgain: 'Hei hi ngaihven leh ang',
  L10nKeys.activityGroupTogether: 'Hei hi remchang ang tur',
  L10nKeys.activityGreatJob: 'Hna tha tak!',
  L10nKeys.activityKitchen: 'Ka chhuan',
  L10nKeys.activityShopping: 'Ka bawhmun',
  L10nKeys.activityMatching: 'Inmil',
  L10nKeys.activitySequence: 'Hnathawh dinhmun',
  L10nKeys.activityRecognition: 'Hei hi eng nge?',
  L10nKeys.activityAssociation: 'Eng nge a inkaihho?',
  L10nKeys.activityRecall: 'I hre ang em?',
  L10nKeys.activityAttention: 'Thlang',
  L10nKeys.activityDurationSuffix: 'minit',
  L10nKeys.activityTodayDone: 'Vawiin sorkip a zawh',
  L10nKeys.activityTodayDoneBody:
      'I huan a lo hlawi e. Naktuk hriatna pakhat a lo ngaitu ang.',
  L10nKeys.activityGardenGrew: 'I huan a lo hlawi e!',
  L10nKeys.activityMemoryUnlocked: 'Hriatna a lo hawng',
  L10nKeys.activityReadAloud: 'Inring takin chhiar rawh',

  L10nKeys.kitchenTitle: 'Chhah siam ang',
  L10nKeys.kitchenMakeChai: 'Chhah siam',
  L10nKeys.kitchenMakeChaiPrompt: 'Hnathawh te dinhmun tlawlah',
  L10nKeys.kitchenSteps: 'Hnathawh',
  L10nKeys.kitchenTapInOrder: 'Hnathawh dinhmun tlawla hmang rawh',
  L10nKeys.kitchenCorrectOrder: 'Tha tak! Chhah a inpeih e!',
  L10nKeys.kitchenBreakfast: 'Zing chaw',
  L10nKeys.kitchenBreakfastHint: 'Ni thra tan',
  L10nKeys.kitchenBreakfastPrompt: 'Zing chaw siam ding hun hi tlawlah rawh.',

  L10nKeys.shopTitle: 'Ka bawhmun',
  L10nKeys.shopGetMilkBread: 'Changei leh hnute',
  L10nKeys.shopGetMilkBreadPrompt: '₹100 in hnute leh changei lei rawh.',
  L10nKeys.shopBudget: 'Zuk throp',
  L10nKeys.shopBasket: 'I hnaak',
  L10nKeys.shopTotal: 'A zawng zawng',
  L10nKeys.shopWithinBudget: 'Zuk thropah!',
  L10nKeys.shopOverBudget: 'Zuk throp aiin tam — ngaihven leh',
  L10nKeys.shopCheckout: 'Zuar zawh',
  L10nKeys.shopBuy: 'Hnaakah dah',
  L10nKeys.shopSell: 'Lak chhuak',
  L10nKeys.shopVeggies: 'Zan chaw atan sawh',
  L10nKeys.shopVeggiesPrompt: '₹60 in alo leh purun lei rawh.',
  L10nKeys.recKitchenItem: 'Hei hi eng nge?',
  L10nKeys.recKitchenItemPrompt: 'Bawhmun ata pawn turin eng nge hmang?',
  L10nKeys.recCurrency: 'Sum te',
  L10nKeys.recCurrencyPrompt: 'Eng note nge ₹20 a ni?',
  L10nKeys.matchFestival: 'Kut inmil',
  L10nKeys.matchFestivalPrompt: 'Kut tin hi a thlan chaw nen inmil rawh.',
  L10nKeys.matchObjectUse: 'Inmil',
  L10nKeys.matchObjectUsePrompt: 'Hmang I hriat te nen inmil rawh.',
  L10nKeys.seqMorning: 'Zing hna',
  L10nKeys.seqMorningPrompt: 'I zing hna te dinhmun tlawlah rawh.',
  L10nKeys.seqRoute: 'Zing chawr',
  L10nKeys.seqRoutePrompt: 'Bawhmun pan dan dinhmun tlawlah rawh.',
  L10nKeys.assoRegion: 'Hei hi eng nge?',
  L10nKeys.assoRegionPrompt: 'Assam eng nge chhinchhiah?',
  L10nKeys.assoHarvest: 'Hlum duh tur',
  L10nKeys.assoHarvestPrompt: 'Eng hmul nge thingkhi nen inkai?',
  L10nKeys.attnVeg: 'Alo thlang',
  L10nKeys.attnVegPrompt: 'Alo i hmuh thei ang em?',
  L10nKeys.recallSong: 'Zai hre theih',
  L10nKeys.recallSongPrompt: 'Bihu a zaiin eng zai nge thleng?',
  L10nKeys.activityPairs: 'Pair zawng rawh',
  L10nKeys.activitySequenceRecall: 'Ruahmanna hriatreng rawh',
  L10nKeys.activityFindChanged: 'Eng nge thleng?',
  L10nKeys.pairsFruits: 'Bazar-ah thei',
  L10nKeys.pairsKitchen: 'Chhura nèihtè',
  L10nKeys.pairsRemember:
      'Karding zawng zawng en rawh, tichuan kha thuhmun pair zawng rawh.',
  L10nKeys.pairsStart: 'Karding thup la, tan la',
  L10nKeys.pairsFound: 'Pair i hmu tal e!',
  L10nKeys.seqRecallItems: 'Ni tin hmanrua',
  L10nKeys.seqRecallNumbers: 'Zat leh zat in zuk',
  L10nKeys.seqRecallWatch: 'Karding en hle rawh – pakhat zêl a lo khuai ang.',
  L10nKeys.seqRecallRepeat:
      'Tunah i hmuh ang khan ruahmanna-ah karding tap rawh.',
  L10nKeys.changeMarket: 'Thei puk',
  L10nKeys.changeFestival: 'Kut-ah mei',
  L10nKeys.changeRemember: 'Heng lemte hi hriatreng rawh.',
  L10nKeys.changeFind: 'Lem pakhat a thleng – dang zawng rawh.',
  L10nKeys.changeCorrect: 'Aw hai! Chu chu a thleng.',

  L10nKeys.mysteryTitle: 'Vawiin hriatna a hnathawh',
  L10nKeys.mysteryLocked: 'Hriatna a hnathawh tak chuan i lo ngaitu…',
  L10nKeys.mysteryLockedBody:
      'Vawiin sorkip 2–3 zawh la; a hawng nge a duh ang. Eng nge?',
  L10nKeys.mysteryUnlocked: 'I hriatna a hnathawh hi hetah hian a awm!',
  L10nKeys.mysteryUnlockedBody:
      'Hei hi i hriatna a chan a ni. Hun hmang rawh. 🌸',
  L10nKeys.mysteryCuriosity: 'Vawiin eng nge a awng?',
  L10nKeys.mysteryOpen: 'Hriatna hawng',

  L10nKeys.memoriesTitle: 'Ka hriatna',
  L10nKeys.memoriesEmpty: 'Hriatna reng reng a awm chho lo',
  L10nKeys.memoriesEmptyBody: 'I chhungkua chuan hnamphu leh aw awktir a thun thei ang. A rawn thlen hunah hemah a lang ang.',
  L10nKeys.memoriesFamily: 'Chhungkua',
  L10nKeys.memoriesPlaces: 'Hmun',
  L10nKeys.memoriesFestivals: 'Kut',
  L10nKeys.memoriesChildhood: 'Naupang hun',
  L10nKeys.memoriesKindPhoto: 'Hnamphu',
  L10nKeys.memoriesKindVoice: 'Aw awktir',
  L10nKeys.memoriesKindText: 'Thu',
  L10nKeys.memoriesKindSound: 'Aw',
  L10nKeys.memoriesKindPlace: 'Hmun',
  L10nKeys.memoriesAddedBy: 'Thun chhuak',
  L10nKeys.memoriesWhoIsThis: 'Tu nge hei?',
  L10nKeys.memoriesPlayVoice: 'Theh',
  L10nKeys.memoriesThisIsMe: 'Keimah',
  L10nKeys.memoriesNotMe: 'Keimah ni lo',

  L10nKeys.profileTitle: 'Profile',
  L10nKeys.profileLanguage: 'App tarak',
  L10nKeys.profileRegion: 'Ka ram',
  L10nKeys.profileVoiceLanguage: 'Aw tarak',
  L10nKeys.profileVoicePrompts: 'Awawm chhuah',
  L10nKeys.profileTextSize: 'Letter size',
  L10nKeys.profileReducedMotion: 'Thla thun dik lo',
  L10nKeys.profileSoundEffects: 'Aw hman',
  L10nKeys.profileFamily: 'Chhungkua',
  L10nKeys.profileContacts: 'Hmasawn hmun',
  L10nKeys.profileDemoMode: 'Demo mode',
  L10nKeys.profileReminders: 'Hriatnawlngawh',
  L10nKeys.profileNeedHelp: 'Tanpuina mamawh?',

  L10nKeys.remindersTitle: 'Hriatnawlngawh',
  L10nKeys.remindersEmpty: 'Reminders reng reng a awm chho lo',
  L10nKeys.remindersNew: 'Reminder thar',
  L10nKeys.remindersTitleLabel: 'Thu hring',
  L10nKeys.remindersDetailLabel: 'Chhinchhiah (thlang duh)',
  L10nKeys.remindersTime: 'Hun',
  L10nKeys.remindersDays: 'Ni',
  L10nKeys.remindersEveryday: 'Nitin',
  L10nKeys.remindersEnabled: 'Ti tih',
  L10nKeys.remindersMedicine: 'Damdawi',
  L10nKeys.remindersAppointment: 'Doctor hmun',
  L10nKeys.remindersRoutine: 'Ni tin hna',

  L10nKeys.dayMon: 'Thawhtan',
  L10nKeys.dayTue: 'Thawhlehni',
  L10nKeys.dayWed: 'Nilaini',
  L10nKeys.dayThu: 'Nirukni',
  L10nKeys.dayFri: 'Zirtawpni',
  L10nKeys.daySat: 'Zanlam',
  L10nKeys.daySun: 'Pathianni',

  L10nKeys.sosTitle: 'Tanpuina riang',
  L10nKeys.sosExplain: 'Beh takin ngei duah. Companio chuan i tanpuina lo thlen turte chu ko dawn. Emergency service (kum 112) a ni lo.',
  L10nKeys.sosHold: 'Tanpuinan beih rawh',
  L10nKeys.sosHoldBody: 'Beh rei takin…',
  L10nKeys.sosActiveTitle: 'Tanpuina ko mek',
  L10nKeys.sosActiveBody: 'I chhungkua te chu i tih hriat e. An sawi loh chuan a dangte chu ko leh ang.',
  L10nKeys.sosContacting: 'Ko mek',
  L10nKeys.sosContactFamily: 'Chhungkua ko',
  L10nKeys.sosContacted: 'A ko e',
  L10nKeys.sosWaitingResponse: 'Chhan ngaitu…',
  L10nKeys.sosEscalating: 'Mi dang ko mek…',
  L10nKeys.sosCancelled: 'Tanpuina a lo chu thladun e',
  L10nKeys.sosCancelAction: 'Tanpuina thu chu thladun rawh',
  L10nKeys.sosDone: 'Zawh',
  L10nKeys.sosHelpOnWay: 'Mi pakhat na i hmunah a thlen dawn. 🧡',
  L10nKeys.sosNoContacts: 'Tanpuina hmun a awm lo',
  L10nKeys.sosNoContactsBody:
      'Chhungkua tanpuina hmun dah turin in hriattir rawh.',
  L10nKeys.sosAddContact: 'Hmun dah thar',
  L10nKeys.sosDisclaimer: 'Companio chuan i thlan te chu ko ngei ang. Hei hi ram hmun emergency service a ni lo.',
  L10nKeys.sosContactedPerson: 'Chhungkua mi ko a ni',
  L10nKeys.sosEscalatedTo: 'Chhungkua mi dang ko a ni',
  L10nKeys.sosAcknowledged:
      'Chhungkua chuan a lo awt e. Help a rawn thlen dawn.',
  L10nKeys.sosNotSilent: 'Thlen theih loh chuan cheibawl thei lo.',
  L10nKeys.sosAlertNotDelivered:
      'I thu chu thlen theih loh a ni; kan beisei zel ang.',

  L10nKeys.careTitle: 'Enkawltu',
  L10nKeys.careDashboard: 'Enchhin',
  L10nKeys.carePatients: 'Ka enkawl mi',
  L10nKeys.careMemories: 'Hriatna',
  L10nKeys.careContacts: 'Tanpuina hmun',
  L10nKeys.careSettings: 'Thlanna',
  L10nKeys.careAddMemory: 'Hriatna dah thar',
  L10nKeys.careAddContact: 'Hmun dah thar',
  L10nKeys.careEngagement: 'Rawn thlai',
  L10nKeys.careActivitiesWeek: 'He thlaia sorkip',
  L10nKeys.careGardenProgress: 'Huan hlawih',
  L10nKeys.careRecentActivity: 'Sorkip hnu',
  L10nKeys.careNoPatients: 'Enkawl mi a awm chho lo',
  L10nKeys.careNoPatientsBody: 'Chhungkua chu hriatna neih turin hrilh la, nge enkawl mi profile dah thar rawh.',
  L10nKeys.careAddPatient: 'Enkawl mi dah thar',
  L10nKeys.carePerformanceNote: 'He mi a hna thleng hi hun rei atanga sawt tak a ni lo; a tlawm deuh a; hun hlui nen inmil lo.',
  L10nKeys.careUploadPhoto: 'Hnamphu chhui',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'Aw record',
  L10nKeys.careWriteMemory: 'Hriatna ziak',
  L10nKeys.careMemoryTitle: 'Thu hring',
  L10nKeys.careMemoryCaption: 'Caption',
  L10nKeys.careMemoryRelation: 'Tu nge hei a awm? (inpawhna)',
  L10nKeys.careMemoryCategory: 'Mun',
  L10nKeys.careContactName: 'Hming',
  L10nKeys.careContactPhone: 'Phone number',
  L10nKeys.careContactPriority: 'Ko tur dinhmun',
  L10nKeys.careContactRelation: 'Inpawhna',
  L10nKeys.careEscalationTimeout: 'Mi dang ko mahna minit',
  L10nKeys.careIncidentStatus: 'Thilthleng',
  L10nKeys.careAckSos: 'Ka chhan duh',
  L10nKeys.careResponding: 'Chhan mek',
  L10nKeys.careActiveAlerts: 'Hmangaihna tarlante',

  L10nKeys.syncSavingOffline: 'Internet nei lo',
  L10nKeys.syncSavingOfflineBody: 'I sorkip te chu he device ah khawi a ni.',
  L10nKeys.syncSynced: 'A lo infui',
  L10nKeys.syncInfo: 'I hriatna te chu an lo infui.',
  L10nKeys.syncPending: 'Infui ngaitu',

  L10nKeys.errorGeneric: 'Engemaw a dik lo chhuak',
  L10nKeys.errorGenericBody: 'I hna chu him a ni. Chik mapo, jeh.',
  L10nKeys.errorAudio: 'He device ah aw awktir lo theih.',
  L10nKeys.errorPermission: 'Hei hian device chanvo a mamawh.',
  L10nKeys.errorNoInternetAction:
      'Internet a tul lo — hei hi NER-ah khawi a ni.',

  L10nKeys.demoWelcome: 'Demo en rawh',
  L10nKeys.demoExplain:
      'I en theihna atan chhungkua leh hriatna te lo dah ang.',
  L10nKeys.demoLoad: 'Demo huan lo phuh',

  L10nKeys.unitsPoints: 'Beng',
  L10nKeys.teaserChai: 'Chhah siam ang.',
  L10nKeys.familiarityName: 'Rualnu Li',
  L10nKeys.regionMap: 'Ka ram',
  L10nKeys.regionChoose: 'I ram thlang',
  L10nKeys.regionIndia: 'India',
  L10nKeys.importantMemory: 'Hriatna thupui',
  L10nKeys.growing: 'Lo hlawi',
  L10nKeys.blooming: 'Par eng e',
  L10nKeys.mature: 'A seiin a hlawi',
  L10nKeys.noVoice: 'He device ah aw a awm lo.',
  L10nKeys.optional: 'Thlang duh',

  L10nKeys.langChoose: 'Tarak thlang rawh',
  L10nKeys.langPrimary: 'Hmasa ber',
  L10nKeys.langNorthEast: 'NE India',
  L10nKeys.langMajor: 'India tarak te',

  L10nKeys.authSignUpTitle: 'I account siam rawh',
  L10nKeys.authSignUpBody: 'He Companio profile hi i device ah khawi a ni. Imah chauh hriat theih turin hming leh password siam rawh.',
  L10nKeys.authLoginTitle: 'Lo kir leh e',
  L10nKeys.authLoginBody:
      'I huan lut turin hming leh password-in sign in rawh.',
  L10nKeys.authUsername: 'Hming',
  L10nKeys.authUsernameHint: 'Entirnan: ranu123',
  L10nKeys.authDisplayName: 'I hming',
  L10nKeys.authPassword: 'Password',
  L10nKeys.authPasswordHint: 'A tlem 6 letter',
  L10nKeys.authConfirmPassword: 'Password en lehna',
  L10nKeys.authRoleQuestion: 'He profile hi tui tan nge…',
  L10nKeys.authRolePatient: 'Keimah tan',
  L10nKeys.authRoleCaregiver: 'Chhungkua mi tan',
  L10nKeys.authCreate: 'Account siam',
  L10nKeys.authSignIn: 'Sign in',
  L10nKeys.authSignOut: 'Sign out',
  L10nKeys.authAccount: 'Account',
  L10nKeys.caregiverTitle: 'Caregiver',
  L10nKeys.caregiverNotLinked: 'No caregiver linked yet',
  L10nKeys.authBadCredentials: 'Hming leh password a dik lo.',
  L10nKeys.authUsernameTaken: 'He device ah hming hi a hmang tawh.',
  L10nKeys.authPasswordMismatch: 'Password a inmil lo.',
  L10nKeys.authUsernameShort: 'Hming hi a tlem 3 letter ah irt',
  L10nKeys.authUsernameInvalid:
      'Letter, number, dot, dash emaw underscore lawng hmang rawh.',
  L10nKeys.authPasswordShort: 'Password hi a tlem 6 letter ah irt.',
  L10nKeys.authNameRequired: 'Hming siam rawh.',
  L10nKeys.authSignOutConfirm: 'He profile-ata sign out i duh em?',
  L10nKeys.screenTitle: 'Hriatna kan enna',
  L10nKeys.screenIntro: 'Kan rawn zawt che a, natnaa tan chungchâng zawhna te. Kum khat leh a awm dân chu han ngun ngaihtuah ang che.',
  L10nKeys.screenNotSure: 'Hre lo',
  L10nKeys.screenFinish: 'Ka rah chu han en rawh',
  L10nKeys.screenSkip: 'Tunah phen rawh',
  L10nKeys.screenResultBack: 'Ti zo',
  L10nKeys.screenCheckAgain: 'Ngun lehin en na leh',
  L10nKeys.screenStartCheckup: 'Enna hi ṭan ang',
  L10nKeys.screenSkipped: 'Enna chu a tlân ta',
  L10nKeys.screenStatusGood: 'Engkim a ṭha',
  L10nKeys.screenStatusGoodBody: 'Harsatna lian tak a hmu lo a. Ni tin thil ṭha ti zel rawh — engemaw a danglam chuan lêt lehin en theih reng a ni.',
  L10nKeys.screenStatusWatch: 'Danglamna ṭhenkhat a hmu',
  L10nKeys.screenStatusWatchBody: 'Hriat loh chhinte a hmuh a. Kum upa zêlin a âwm ve thung, mahse lo vei ang che a, doctor puan rawh.',
  L10nKeys.screenStatusDoctor: 'Doctor rawn pan rawh',
  L10nKeys.screenStatusDoctorBody: 'Thil ṭhenkhat a hmuh a, enkawl lehzual a mamawh thei. Hei hi doctor emaw clinic-ah hrilh rawh, an ṭanpui theih nan.',
  L10nKeys.screenRarely: 'Hman lêm lo',
  L10nKeys.screenSometimes: 'Ṭhenkhawm',
  L10nKeys.screenFrequently: 'Ṭum tam',
  L10nKeys.screenVeryFrequently: 'Ṭum tam hle',
  L10nKeys.screenQ01: 'Thil thar chhinchhiah chu an har em?',
  L10nKeys.screenQ02: 'Zawhna emaw thawnthu thaw khat an ti lêt leh zel em?',
  L10nKeys.screenQ03: 'Mipui ṭhenkhat hming an beng baih em?',
  L10nKeys.screenQ04: 'Mai hmuh hriat reng an harsa em?',
  L10nKeys.screenQ05: 'Huna intawh emaw pawi hun an beng baih em?',
  L10nKeys.screenQ06: 'Thu ṭha tak hmu chhuak an harsa em?',
  L10nKeys.screenQ07: 'Khawi hmunah an awm tih an hre lo va inrual reng em?',
  L10nKeys.screenQ08: 'Ni tin thiltih tân hriattir an mamawh em?',
  L10nKeys.screenQ09: 'Damdawi enkawl tûr an harsa em?',
  L10nKeys.screenQ10: 'An inrual chuan an buai emaw thinrim em?',
  L10nKeys.screenQ11: 'Thu hrilh awih an harsa em?',
  L10nKeys.screenQ12: 'Thil hre tawh ti zawh an harsa em?',
  L10nKeys.screenQ13: 'Ni tin thil awmna hmun an beng baih thin em?',
  L10nKeys.screenQ14: 'Thupêk hriat reng an harsa em?',
  L10nKeys.screenQ15: 'Thiltih ṭhenkhat sawm zawh an harsa em?',

  L10nKeys.careDashboardSubtitle: 'Family care',
  L10nKeys.careSosLive: 'Live alert',
  L10nKeys.careSosRespondedBy: 'Responded by {name}',
  L10nKeys.careLinkTitle: 'Connect to a family member',
  L10nKeys.careLinkBody: 'Ask your loved one for the 6-letter family code shown on their phone, then connect.',
  L10nKeys.careLinkCode: 'Family code',
  L10nKeys.careLinkCodeHint: 'e.g. A1B2C3',
  L10nKeys.careLinkConnect: 'Connect',
  L10nKeys.careLinkDone: 'Connected',
  L10nKeys.careLinkSuccess:
      'Linked to {name}! Memories and alerts will now sync.',
  L10nKeys.careLinkFailed:
      'Could not connect. Please check the code and try again.',
  L10nKeys.careTrendsTitle: 'AI trends',
  L10nKeys.careTrendsBody: 'Daily accuracy by activity type',
  L10nKeys.careTrendsNoData:
      'No activity yet — complete an exercise to see trends.',
  L10nKeys.careAiDifficulty: 'Auto-tuned difficulty',
  L10nKeys.careAiAccuracy: 'Model accuracy',
  L10nKeys.careAiRealSessions: 'Real sessions',
  L10nKeys.careAiDemoSessions: 'Demo sessions',
  L10nKeys.careNavGames: 'Pawl',
  L10nKeys.careNavRoutine: 'Rutin',
  L10nKeys.careGreetSubtitle: 'Hei hian vawiin {name} a nih dân a tarlang.',
  L10nKeys.careNotifEmpty: 'Thil thar vanchhinah nei lo',
  L10nKeys.careWellnessScore: 'Cognitive thiamna score',
  L10nKeys.careStatusStable: 'Nghet',
  L10nKeys.careStatusAttention: 'A ngaihtuah a ngai',
  L10nKeys.careLastSynced: '{time} ah synchronised a ni',
  L10nKeys.careMinAgo: '{n} min liam tawh',
  L10nKeys.careGamesWeek: 'He haptah pawl',
  L10nKeys.careRoutineCompletion: 'Rutin tih zawh',
  L10nKeys.careCurrentStreak: 'Dahral leh zoma chhâwng',
  L10nKeys.careMoodCheckins: 'Thinlung check-ins',
  L10nKeys.careDayUnit: 'ni',
  L10nKeys.careDaysUnit: 'nihte',
  L10nKeys.careActivityTitle: 'Hapta lama thawhna',
  L10nKeys.careWeekly: 'Hapta tin',
  L10nKeys.careMonthly: 'Thla tin',
  L10nKeys.careNoActivityWeek: 'He haptah hna la thleng lo.',
  L10nKeys.careMoodTitle: 'Thinlung lam',
  L10nKeys.careMoodHappy: 'Hlim',
  L10nKeys.careMoodCalm: 'Thlamuang',
  L10nKeys.careMoodNeutral: 'Thawkhat',
  L10nKeys.careMoodLow: 'Sawtah',
  L10nKeys.careMood7Days: 'Nipui 7',
  L10nKeys.careMoodInsight: '{name} he hapta hi a thlamuang tawp mai, mahse ni hnih aṭang khân a thinlung a tnuam dalh thung a ni.',
  L10nKeys.careMoodNoData: 'He haptah thinlung check-in la nei lo.',
  L10nKeys.careSkillsTitle: 'Cognitive thiamna',
  L10nKeys.careSkillMemory: 'Hriatna',
  L10nKeys.careSkillAttention: 'Ngaihtuahna',
  L10nKeys.careSkillLanguage: 'Ṭawng',
  L10nKeys.careSkillReasoning: 'Hriatchhuahna',
  L10nKeys.careSkillProcessing: 'Thawh chakna speed',
  L10nKeys.careInsightToday: 'Vawiin thiamna chhuah',
  L10nKeys.careInsightBody: 'Robert chuan a zing lam rutin hnuah hriatna thil tihah a tan tha hle a. A thinlung chu ni hnih liam tâh khed liam leh zên liam a ni.',
  L10nKeys.careInsightBodyReal: 'He hapta hian {name} chuan cognitive session {count} (tum {goal}) a tih zawh a, {streak} ni dahral chhâwm a ni.',
  L10nKeys.careViewDetails: 'Chhiar chiang rawh',
  L10nKeys.careInsightDisclaimer: 'Hei hi data ata thlamuanna rawngbawlna zâwl mêk — damdawi thlîrna ni lo.',
  L10nKeys.careAttentionTitle: 'I ngaihtuah a ngai e',
  L10nKeys.careAttentionEmpty: 'Tumah thil a ngaihtuah tur reng a awm lo.',
  L10nKeys.careAlertSos: '{name} SOS button a hmet a ni',
  L10nKeys.careAlertRoutineMissed: 'Nisan khan rutin a be nun lo',
  L10nKeys.careAlertMoodDown: 'Ni hnih liam tâh a thinlung a lo tlem',
  L10nKeys.careAlertSessionPending: 'Vawiin cognitive session a zawh lo',
  L10nKeys.careAlertSeverityHigh: 'Sang',
  L10nKeys.careAlertSeverityMedium: 'Lai',
  L10nKeys.careAlertSeverityLow: 'Tlem',
  L10nKeys.careWeeklySummary: 'Hapta thurual',
  L10nKeys.careSessionsCompleted: 'Session tih zawh',
  L10nKeys.careAvgSessionDuration: 'Session hlawhtling rei dân',
  L10nKeys.careRoutineAdherence: 'Rutin zawm dân',
  L10nKeys.careMoodTrend: 'Thinlung lam thleng dân',
  L10nKeys.careMoodTrendSlightlyDown: 'Tlem tlem hnuai lam',
  L10nKeys.careMoodTrendStable: 'Nghet',
  L10nKeys.careMoodTrendUp: 'Lâwn chho',
  L10nKeys.careVsLastWeek: 'Hapta kal ta atanga',
  L10nKeys.careSyncedJustNow: 'Tâh takah synchronise a ni',
  L10nKeys.careOfflineWaiting:
      'Internet awm lo · {count} thil synchronise tura nghakhlei',
  L10nKeys.careComingSoon: 'Lo la lût chhe',
  L10nKeys.careHomeSoon:
      '{name} ni tin mil dân atâna mawl zêl heta hian lo lang ang.',
  L10nKeys.careGamesSoon: 'Pawl leh session history heta hian lo lang ang.',
  L10nKeys.careRoutineSoon: 'Nâu tân a ni tin rutin heta hian lo lang ang.',
  L10nKeys.careProfileSoon:
      'Enkawltu profile leh settings heta hian lo lang ang.',
  L10nKeys.serverPairingTitle: 'Family code',
  L10nKeys.serverPairingBody:
      'Share this code with a caregiver so they can connect to you.',
  L10nKeys.serverUnlinked: 'Not connected to server',
  L10nKeys.serverLinked: 'Connected to server',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
