import '../l10n_keys.dart';

/// Malayalam dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsMl = {
  L10nKeys.appName: 'Companio',
  // How to play (tutorials)
  L10nKeys.tutListen: 'Listen',
  L10nKeys.tutPairs1: 'Watch the pictures carefully. Soon they will be hidden.',
  L10nKeys.tutPairs2: 'Tap a card to turn it around.',
  L10nKeys.tutPairs3: 'Find two of the very same picture.',
  L10nKeys.tutSeq1: 'Watch the cards light up one by one.',
  L10nKeys.tutSeq2: 'Remember the order.',
  L10nKeys.tutSeq3: 'Tap the cards in the same order.',
  L10nKeys.tutRecall1: 'Read or listen to the question.',
  L10nKeys.tutRecall2: 'Tap the answer you remember.',
  L10nKeys.tutRecall3: 'Choose one answer to finish.',
  L10nKeys.tutMatch1: 'Look at the pictures on the left.',
  L10nKeys.tutMatch2: 'Tap the matching picture on the right.',
  L10nKeys.tutMatch3: 'Match every pair to finish.',
  L10nKeys.tutNoFail: 'Take your time. There is no failing.',
  L10nKeys.tagline: 'നിങ്ങളുടെ ഓർമ്മകളുടെ കൂട്ട്',
  L10nKeys.back: 'പിന്നോട്ട്',
  L10nKeys.next: 'അടുത്തത്',
  L10nKeys.continueText: 'തുടരുക',
  L10nKeys.skip: 'ഒഴിവാക്കുക',
  L10nKeys.done: 'കഴിഞ്ഞു',
  L10nKeys.cancel: 'റദ്ദാക്കുക',
  L10nKeys.yes: 'അതെ',
  L10nKeys.no: 'ഇല്ല',
  L10nKeys.save: 'സംരക്ഷിക്കുക',
  L10nKeys.close: 'അടയ്ക്കുക',
  L10nKeys.retry: 'വീണ്ടും ശ്രമിക്കുക',
  L10nKeys.add: 'ചേർക്കുക',
  L10nKeys.edit: 'മാറ്റുക',
  L10nKeys.remove: 'നീക്കുക',
  L10nKeys.search: 'തിരയുക',
  L10nKeys.today: 'ഇന്ന്',
  L10nKeys.offline: 'ഓഫ്‌ലൈൻ',
  L10nKeys.online: 'ഓൺലൈൻ',

  L10nKeys.goodMorning: 'സുപ്രഭാതം',
  L10nKeys.goodAfternoon: 'നമസ്കാരം',
  L10nKeys.goodEvening: 'ശുഭ സായാഹ്നം',
  L10nKeys.goodNight: 'ശുഭ രാത്രി',

  L10nKeys.navHome: 'ഹോം',
  L10nKeys.navGarden: 'പൂന്തോട്ടം',
  L10nKeys.navActivities: 'പ്രവർത്തനങ്ങൾ',
  L10nKeys.navMemories: 'ഓർമ്മകൾ',
  L10nKeys.navProfile: 'പ്രൊഫൈൽ',
  L10nKeys.navMystery: 'ഇന്നത്തെ ഓർമ്മ',

  L10nKeys.onboardingWelcomeTitle: 'നിങ്ങളുടെ ഓർമ്മകളുടെ മൃദുവായ കൂട്ട്',
  L10nKeys.onboardingWelcomeBody: 'മൈൻഡ്കെയർ എൻഇആർ ഇൻ്റർനെറ്റ് ഇല്ലാതെ തന്നെ ഓർക്കാനും കളിക്കാനും കുടുംബവുമായി ബന്ധപ്പെട്ടിരിക്കാനും സഹായിക്കുന്നു.',
  L10nKeys.onboardingNameTitle: 'നിങ്ങളെ എങ്ങനെ വിളിക്കാം?',
  L10nKeys.onboardingNameHint: 'നിങ്ങളുടെ പേര്',
  L10nKeys.onboardingRegionTitle: 'നിങ്ങളുടെ വീട് എവിടെ?',
  L10nKeys.onboardingRegionHint: 'നഗരം അല്ലെങ്കിൽ ഗ്രാമം',
  L10nKeys.onboardingRegionList: 'ഗുവാഹത്തി, സിൽച്ചാർ, ഷിലോംഗ്, അഗർത്തല, ഇംഫാൽ, ഐസ്വാൾ, ഇട്ടാനഗർ, കോഹിമ, ഗാങ്‌ടോക്ക്, ഡിബ്രുഗഢ്, ജോർഹാട്ട്, നിങ്ങളുടെ നഗരം',
  L10nKeys.onboardingLanguageTitle: 'നിങ്ങൾക്ക് ഏത് ഭാഷ ഇഷ്ടമാകും?',
  L10nKeys.onboardingLanguageBody: 'ഇത് എപ്പോൾ വേണമെങ്കിലും മാറ്റാം.',
  L10nKeys.onboardingFamilyTitle: 'ആരാണ് കുടുംബം?',
  L10nKeys.onboardingFamilyBody: 'നിങ്ങളുടെ പ്രിയപ്പെട്ടവരെ ചേർക്കുക. അവരുടെ ഫോട്ടോകളും ശബ്ദവും മൃദുവായ ഓർമ്മകളായി കാണിക്കും.',
  L10nKeys.onboardingAddFamily: 'കുടുംബാംഗത്തെ ചേർക്കുക',
  L10nKeys.onboardingEmergencyTitle: 'അടിയന്തര ഘട്ടത്തിൽ ആരെ വിളിക്കും?',
  L10nKeys.onboardingEmergencyBody: 'SOS ബട്ടൺ അമർത്തിയാൽ മൈൻഡ്കെയർ നിങ്ങളുടെ കുടുംബത്തെ അറിയിക്കും, അടിയന്തര സേവനങ്ങളെ അല്ല.',
  L10nKeys.onboardingEmergencyName: 'പേര്',
  L10nKeys.onboardingEmergencyPhone: 'ഫോൺ നമ്പർ',
  L10nKeys.onboardingEmergencyRelation: 'ബന്ധം (മകൾ, മകൻ…)',
  L10nKeys.onboardingDoneTitle: 'നിങ്ങളുടെ പൂന്തോട്ടം തയ്യാർ!',
  L10nKeys.onboardingDoneBody: 'ചെറിയ പ്രവർത്തനങ്ങൾ പൂർത്തിയാക്കി പൂന്തോട്ടം വളരുന്നത് കാണുക. ഞങ്ങൾ നിങ്ങൾക്കൊപ്പമുണ്ട്.',
  L10nKeys.onboardingStart: 'എൻ്റെ പൂന്തോട്ടം ആരംഭിക്കുക',

  L10nKeys.homeWhatsGrowing: 'ഇന്ന് എന്താണ് വളരുന്നത്?',
  L10nKeys.homeTodayActivity: 'ഇന്നത്തെ ചെറിയ പ്രവർത്തനം',
  L10nKeys.homeActivityDuration: 'ഏകദേശം 3 മിനിറ്റ്',
  L10nKeys.homeMinutes: 'മിനിറ്റ്',
  L10nKeys.homeMemoryOfDay: 'ഇന്നത്തെ ഓർമ്മ',
  L10nKeys.homeMemoryLocked: 'ഒരു പ്രത്യേക ഓർമ്മ കാത്തിരിക്കുന്നു…',
  L10nKeys.homeMemoryUnlocked: 'ഒരു ഓർമ്മ തുറന്നു!',
  L10nKeys.homeContinueActivity: 'പ്രവർത്തനം തുടരുക',
  L10nKeys.homeFamilyMemory: 'നിങ്ങളുടെ കുടുംബത്തിൽ നിന്ന്',
  L10nKeys.homeFamilyMemoryEmpty: 'കുടുംബത്തിൻ്റെ ഓർമ്മകൾ ഇവിടെ കാണാം.',
  L10nKeys.homeSos: 'സഹായം വേണം',
  L10nKeys.homeSosSubtitle: 'അടിയന്തര ഘട്ടത്തിൽ കുടുംബവുമായി ബന്ധപ്പെടുക',
  L10nKeys.homeGardenPreview: 'നിങ്ങളുടെ പൂന്തോട്ടം',
  L10nKeys.homeEngine: 'മൈൻഡ്കെയർ കൂട്ട്',
  L10nKeys.homeEngineReady: 'നിങ്ങളുടെ സഹായി തയ്യാർ.',
  L10nKeys.homeWelcomeBack: 'തിരിച്ചു വരവ് സ്വാഗതം! പൂന്തോട്ടം തുടരാം. 🌸',
  L10nKeys.homeNoActivity: 'ഇന്ന് പ്രവർത്തനമില്ല',
  L10nKeys.homeNoActivityBody: 'അൽപ്പം വിശ്രമിക്കുക — അല്ലെങ്കിൽ ഇഷ്ടമുള്ള പ്രവർത്തനം തിരഞ്ഞെടുക്കുക. 🌻',

  L10nKeys.gardenTitle: 'എൻ്റെ ഓർമ്മകളുടെ പൂന്തോട്ടം',
  L10nKeys.gardenSectionAll: 'എല്ലാം',
  L10nKeys.gardenSectionFamily: 'കുടുംബം',
  L10nKeys.gardenSectionChildhood: 'ബാല്യം',
  L10nKeys.gardenSectionPlaces: 'സ്ഥലങ്ങൾ',
  L10nKeys.gardenSectionFestivals: 'ഉത്സവങ്ങൾ',
  L10nKeys.gardenEmpty: 'നിങ്ങളുടെ പൂന്തോട്ടം ഇപ്പോൾ തുടങ്ങി',
  L10nKeys.gardenEmptyBody:
      'ആദ്യ പ്രവർത്തനം പൂർത്തിയാക്കുക, ഇവിടെ ഒരു വിത്ത് നടും.',
  L10nKeys.gardenPoints: 'പോയിൻ്റുകൾ',
  L10nKeys.gardenLevel: 'തലം',
  L10nKeys.gardenSeed: 'വിത്ത്',
  L10nKeys.gardenPlant: 'തൈ',
  L10nKeys.gardenFlower: 'പൂവ്',
  L10nKeys.gardenTree: 'മരം',
  L10nKeys.gardenMilestone: 'ഘട്ടം',
  L10nKeys.gardenGrowth: 'വളരുന്നു',
  L10nKeys.gardenDidYouKnow:
      'ഓരോ പൂർണമാകുന്ന പ്രവർത്തനവും പൂന്തോട്ടത്തെ വളർത്തുന്നു.',
  L10nKeys.gardenPlantSeed: 'വിത്ത് നടുക',

  L10nKeys.activitiesTitle: 'പ്രവർത്തനങ്ങൾ',
  L10nKeys.activitiesToday: 'ഇന്ന്',
  L10nKeys.activitiesLibrary: 'കൂടുതൽ പ്രവർത്തനങ്ങൾ',
  L10nKeys.mainGamesTitle: 'പ്രധാന കളികൾ',
  L10nKeys.activitiesStart: 'ആരംഭിക്കുക',
  L10nKeys.activitiesCompleted: 'പൂർത്തിയായവ',
  L10nKeys.activitiesInProgress: 'നടക്കുന്നു',
  L10nKeys.activitiesNotStarted: 'തയ്യാർ',
  L10nKeys.activityYoureDone: 'മികച്ചത്!',
  L10nKeys.activityPraise: 'പൂന്തോട്ടത്തിന് അൽപ്പം ജീവൻ നൽകി. 🌱',
  L10nKeys.activityHint: 'സൂചന വേണോ?',
  L10nKeys.activityTryAgain: 'ഈ ഓർമ്മ വീണ്ടും നോക്കാം',
  L10nKeys.activityOptionsHint: 'നിങ്ങളുടെ ഉത്തരം തിരഞ്ഞെടുക്കുക',
  L10nKeys.activityTapToMatch: 'ഒത്തുപോകുന്ന ജോടി തിരഞ്ഞെടുക്കുക',
  L10nKeys.activityNext: 'അടുത്തത്',
  L10nKeys.activityFinish: 'പൂർത്തിയാക്കുക',
  L10nKeys.activityGroupLetsAgain: 'ഇത് വീണ്ടും നോക്കാം',
  L10nKeys.activityGroupTogether: 'ഇത് ഒന്നിച്ച് ചെയ്യാം',
  L10nKeys.activityGreatJob: 'നന്നായി ചെയ്തു!',
  L10nKeys.activityKitchen: 'എൻ്റെ അടുക്കള',
  L10nKeys.activityShopping: 'എൻ്റെ കട',
  L10nKeys.activityMatching: 'ജോടി ചേർക്കുക',
  L10nKeys.activitySequence: 'ക്രമത്തിൽ വയ്ക്കുക',
  L10nKeys.activityRecognition: 'ഇത് എന്താണ്?',
  L10nKeys.activityAssociation: 'എന്തൊക്കെ ഒന്നിച്ച് പോകും?',
  L10nKeys.activityRecall: 'ഓർക്കുന്നുണ്ടോ?',
  L10nKeys.activityAttention: 'തിരയുക',
  L10nKeys.activityDurationSuffix: 'മിനിറ്റ്',
  L10nKeys.activityTodayDone: 'ഇന്നത്തെ പ്രവർത്തനം പൂർത്തിയായി',
  L10nKeys.activityTodayDoneBody:
      'നിങ്ങളുടെ പൂന്തോട്ടം വളർന്നു. നാളെ ഒരു ഓർമ്മ കാത്തിരിക്കും.',
  L10nKeys.activityGardenGrew: 'നിങ്ങളുടെ പൂന്തോട്ടം വളർന്നു!',
  L10nKeys.activityMemoryUnlocked: 'ഒരു ഓർമ്മ തുറന്നു',
  L10nKeys.activityReadAloud: 'ഉച്ചത്തിൽ വായിക്കുക',

  L10nKeys.kitchenTitle: 'ചായ ഉണ്ടാക്കാം',
  L10nKeys.kitchenMakeChai: 'ചായ ഉണ്ടാക്കൽ',
  L10nKeys.kitchenMakeChaiPrompt: 'ഘട്ടങ്ങൾ ശരിയായ ക്രമത്തിൽ തിരഞ്ഞെടുക്കുക.',
  L10nKeys.kitchenSteps: 'ഘട്ടങ്ങൾ',
  L10nKeys.kitchenTapInOrder: 'ഘട്ടങ്ങൾ ശരിയായ ക്രമത്തിൽ തിരഞ്ഞെടുക്കുക',
  L10nKeys.kitchenCorrectOrder: 'നന്നായി! ചായ തയ്യാർ!',
  L10nKeys.kitchenBreakfast: 'പ്രഭാതഭക്ഷണം ഉണ്ടാക്കൽ',
  L10nKeys.kitchenBreakfastHint: 'ദിവസത്തിൻ്റെ പുതിയ തുടക്കം',
  L10nKeys.kitchenBreakfastPrompt:
      'പ്രഭാതഭക്ഷണത്തിൻ്റെ ഘട്ടങ്ങൾ ക്രമത്തിൽ വയ്ക്കുക.',

  L10nKeys.shopTitle: 'എൻ്റെ കട',
  L10nKeys.shopGetMilkBread: 'ബ്രെഡും പാലും',
  L10nKeys.shopGetMilkBreadPrompt: '₹100-ൽ പാലും ബ്രെഡും വാങ്ങുക.',
  L10nKeys.shopBudget: 'ബജറ്റ്',
  L10nKeys.shopBasket: 'നിങ്ങളുടെ കൊട്ട',
  L10nKeys.shopTotal: 'ആകെ',
  L10nKeys.shopWithinBudget: 'ബജറ്റിനുള്ളിൽ!',
  L10nKeys.shopOverBudget: 'ബജറ്റ് കവിഞ്ഞു — വീണ്ടും നോക്കുക',
  L10nKeys.shopCheckout: 'പൂർത്തിയാക്കി പണം നൽകുക',
  L10nKeys.shopBuy: 'കൊട്ടയിൽ ഇടുക',
  L10nKeys.shopSell: 'നീക്കുക',
  L10nKeys.shopVeggies: 'അത്താഴത്തിനുള്ള പച്ചക്കറികൾ',
  L10nKeys.shopVeggiesPrompt: '₹60-ൽ ഉരുളക്കിഴങ്ങും സവാളയും വാങ്ങുക.',
  L10nKeys.recKitchenItem: 'ഇത് ഏതാണ്?',
  L10nKeys.recKitchenItemPrompt:
      'ചന്തയിൽ നിന്ന് സാധനം കൊണ്ടുവരാൻ ഏതാണ് ഉപയോഗിക്കുക?',
  L10nKeys.recCurrency: 'കുറച്ച് പണം',
  L10nKeys.recCurrencyPrompt: 'ഏത് നോട്ടാണ് ₹20?',
  L10nKeys.matchFestival: 'ഉത്സവം ചേർക്കുക',
  L10nKeys.matchFestivalPrompt:
      'ഓരോ ഉത്സവവും അതിൻ്റെ പ്രത്യേക വിഭവവുമായി ചേർക്കുക.',
  L10nKeys.matchObjectUse: 'ജോടി ചേർക്കുക',
  L10nKeys.matchObjectUsePrompt:
      'ഓരോ വസ്തുവും ഉപയോഗിക്കുന്ന സമയവുമായി ചേർക്കുക.',
  L10nKeys.seqMorning: 'രാവിലത്തെ ദിനചര്യ',
  L10nKeys.seqMorningPrompt: 'നിങ്ങളുടെ രാവിലത്തെ ദിനചര്യ ക്രമത്തിൽ വയ്ക്കുക.',
  L10nKeys.seqRoute: 'രാവിലത്തെ യാത്ര',
  L10nKeys.seqRoutePrompt: 'ചന്ത വരെയുള്ള യാത്ര ക്രമത്തിൽ വയ്ക്കുക.',
  L10nKeys.assoRegion: 'ഇവിടെ എന്തുണ്ട്?',
  L10nKeys.assoRegionPrompt: 'അസം എന്തിന് പ്രസിദ്ധമാണ്?',
  L10nKeys.assoHarvest: 'മധുരമുള്ള പഴം',
  L10nKeys.assoHarvestPrompt: 'ഏത് പഴത്തെ വേനലിൻ്റെ രാജാവ് എന്ന് വിളിക്കും?',
  L10nKeys.attnVeg: 'കാരറ്റ് തിരയുക',
  L10nKeys.attnVegPrompt: 'കാരറ്റ് കണ്ടെത്താമോ?',
  L10nKeys.recallSong: 'ഒരു പരിചിതമായ പാട്ട്',
  L10nKeys.recallSongPrompt:
      'ബിഹുവിൽ നൃത്തം ചെയ്യുമ്പോൾ ഏത് പാട്ടാണ് മുഴങ്ങുന്നത്?',
  L10nKeys.activityPairs: 'ജോടി കണ്ടെത്തുക',
  L10nKeys.activitySequenceRecall: 'ക്രമം ഓർത്തുവെക്കുക',
  L10nKeys.activityFindChanged: 'എന്താണ് മാറിയത്?',
  L10nKeys.pairsFruits: 'ചന്തയിലെ പഴങ്ങൾ',
  L10nKeys.pairsKitchen: 'അടുക്കളയിലെ സാധനങ്ങൾ',
  L10nKeys.pairsRemember:
      'എല്ലാ കാർഡുകളും ശ്രദ്ധിച്ചു നോക്കൂ, പിന്നെ ഒരേ ജോടി കണ്ടെത്തുക.',
  L10nKeys.pairsStart: 'കാർഡുകൾ മറച്ചു തുടങ്ങുക',
  L10nKeys.pairsFound: 'ജോടി കിട്ടി!',
  L10nKeys.seqRecallItems: 'ദിനചര്യയിലെ സാധനങ്ങൾ',
  L10nKeys.seqRecallNumbers: 'കൃത്യക്രമത്തിലെ അക്കങ്ങൾ',
  L10nKeys.seqRecallWatch:
      'കാർഡുകൾ ശ്രദ്ധിച്ചു നോക്കൂ – ഓരോന്നും ക്രമത്തിൽ പ്രകാശിക്കും.',
  L10nKeys.seqRecallRepeat: 'ഇപ്പോൾ കണ്ട അതേ ക്രമത്തിൽ കാർഡുകൾ അമർത്തുക.',
  L10nKeys.changeMarket: 'പഴങ്ങളുടെ കുട്ട',
  L10nKeys.changeFestival: 'ഉത്സവ വിളക്കുകൾ',
  L10nKeys.changeRemember: 'ഈ ചിത്രങ്ങൾ ശ്രദ്ധയോടെ ഓർത്തുവെക്കുക.',
  L10nKeys.changeFind: 'ഒരു ചിത്രം മാറി. വ്യത്യസ്തമായത് കണ്ടെത്തുക.',
  L10nKeys.changeCorrect: 'കൊള്ളാം! അതാണ് മാറിയത്.',

  L10nKeys.mysteryTitle: 'ഇന്നത്തെ പ്രത്യേക ഓർമ്മ',
  L10nKeys.mysteryLocked: 'ഒരു പ്രത്യേക ഓർമ്മ നിങ്ങളെ കാത്തിരിക്കുന്നു…',
  L10nKeys.mysteryLockedBody:
      'ഇന്ന് 2–3 ചെറിയ പ്രവർത്തനങ്ങൾ ചെയ്യുക; ഒരുപക്ഷേ അത് തുറക്കും. എന്താകും?',
  L10nKeys.mysteryUnlocked: 'നിങ്ങളുടെ പ്രത്യേക ഓർമ്മ ഇവിടെ!',
  L10nKeys.mysteryUnlockedBody: 'ഈ ഓർമ്മ നിങ്ങൾക്ക് മാത്രം. സമയമെടുക്കുക. 🌸',
  L10nKeys.mysteryCuriosity: 'ഇന്ന് എന്ത് തുറക്കും?',
  L10nKeys.mysteryOpen: 'ഓർമ്മ തുറക്കുക',

  L10nKeys.memoriesTitle: 'എൻ്റെ ഓർമ്മകൾ',
  L10nKeys.memoriesEmpty: 'ഇതുവരെ ഓർമ്മകളൊന്നുമില്ല',
  L10nKeys.memoriesEmptyBody: 'നിങ്ങളുടെ കുടുംബം ഫോട്ടോകളും ശബ്ദ സന്ദേശങ്ങളും ചേർക്കാം. ലഭിച്ച ഉടൻ ഇവിടെ കാണും.',
  L10nKeys.memoriesFamily: 'കുടുംബം',
  L10nKeys.memoriesPlaces: 'സ്ഥലങ്ങൾ',
  L10nKeys.memoriesFestivals: 'ഉത്സവങ്ങൾ',
  L10nKeys.memoriesChildhood: 'ബാല്യം',
  L10nKeys.memoriesKindPhoto: 'ഫോട്ടോ',
  L10nKeys.memoriesKindVoice: 'ശബ്ദ സന്ദേശം',
  L10nKeys.memoriesKindText: 'കഥ',
  L10nKeys.memoriesKindSound: 'ശബ്ദം',
  L10nKeys.memoriesKindPlace: 'സ്ഥലം',
  L10nKeys.memoriesAddedBy: 'ചേർത്തത്',
  L10nKeys.memoriesWhoIsThis: 'ഇവർ ആരാണ്?',
  L10nKeys.memoriesPlayVoice: 'കേൾക്കുക',
  L10nKeys.memoriesThisIsMe: 'ഇതാണ് ഞാൻ',
  L10nKeys.memoriesNotMe: 'ഞാനല്ല',

  L10nKeys.profileTitle: 'പ്രൊഫൈൽ',
  L10nKeys.profileLanguage: 'ആപ്പ് ഭാഷ',
  L10nKeys.profileRegion: 'എൻ്റെ പ്രദേശം',
  L10nKeys.profileVoiceLanguage: 'ശബ്ദ ഭാഷ',
  L10nKeys.profileVoicePrompts: 'സംസാരിക്കുന്ന സൂചനകൾ',
  L10nKeys.profileTextSize: 'അക്ഷര വലുപ്പം',
  L10nKeys.profileReducedMotion: 'ശാന്തമായ ചലനം',
  L10nKeys.profileSoundEffects: 'ശബ്ദ പ്രഭാവങ്ങൾ',
  L10nKeys.profileFamily: 'കുടുംബം',
  L10nKeys.profileContacts: 'അടിയന്തര കോൺടാക്റ്റുകൾ',
  L10nKeys.profileDemoMode: 'ഡെമോ മോഡ്',
  L10nKeys.profileReminders: 'ഓർമ്മപ്പെടുത്തലുകൾ',
  L10nKeys.profileNeedHelp: 'സഹായം വേണോ?',

  L10nKeys.remindersTitle: 'ഓർമ്മപ്പെടുത്തലുകൾ',
  L10nKeys.remindersEmpty: 'ഇതുവരെ ഓർമ്മപ്പെടുത്തലുകളില്ല',
  L10nKeys.remindersNew: 'പുതിയ ഓർമ്മപ്പെടുത്തൽ',
  L10nKeys.remindersTitleLabel: 'തലക്കെട്ട്',
  L10nKeys.remindersDetailLabel: 'വിവരം (ഐച്ഛികം)',
  L10nKeys.remindersTime: 'സമയം',
  L10nKeys.remindersDays: 'ദിവസങ്ങൾ',
  L10nKeys.remindersEveryday: 'ദിവസവും',
  L10nKeys.remindersEnabled: 'സജീവം',
  L10nKeys.remindersMedicine: 'മരുന്ന്',
  L10nKeys.remindersAppointment: 'കൂടിക്കാഴ്ച',
  L10nKeys.remindersRoutine: 'ദൈനംദിന ദിനചര്യ',

  L10nKeys.dayMon: 'തിങ്കൾ',
  L10nKeys.dayTue: 'ചൊവ്വ',
  L10nKeys.dayWed: 'ബുധൻ',
  L10nKeys.dayThu: 'വ്യാഴം',
  L10nKeys.dayFri: 'വെള്ളി',
  L10nKeys.daySat: 'ശനി',
  L10nKeys.daySun: 'ഞായർ',

  L10nKeys.sosTitle: 'അടിയന്തര സഹായം',
  L10nKeys.sosExplain: 'അമർത്തിപ്പിടിക്കുക. മൈൻഡ്കെയർ നിങ്ങളുടെ അടിയന്തര കോൺടാക്റ്റുകളെ ഓരോരുത്തരായി അറിയിക്കും. ഇത് അടിയന്തര സേവനം (112 പോലുള്ളത്) അല്ല.',
  L10nKeys.sosHold: 'സഹായത്തിനായി അമർത്തിപ്പിടിക്കുക',
  L10nKeys.sosHoldBody: 'അമർത്തിപ്പിടിക്കുക…',
  L10nKeys.sosActiveTitle: 'സഹായത്തെ ബന്ധപ്പെടുന്നു',
  L10nKeys.sosActiveBody: 'നിങ്ങളുടെ കുടുംബത്തെ അറിയിച്ചു. പ്രതികരണമില്ലെങ്കിൽ അടുത്ത കോൺടാക്റ്റിനെ വിളിക്കും.',
  L10nKeys.sosContacting: 'ബന്ധപ്പെടുന്നു',
  L10nKeys.sosContactFamily: 'കുടുംബവുമായി ബന്ധപ്പെടുക',
  L10nKeys.sosContacted: 'ബന്ധപ്പെട്ടു',
  L10nKeys.sosWaitingResponse: 'പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു…',
  L10nKeys.sosEscalating: 'അടുത്ത വ്യക്തിയെ ബന്ധപ്പെടുന്നു…',
  L10nKeys.sosCancelled: 'സഹായ അഭ്യർത്ഥന റദ്ദാക്കി',
  L10nKeys.sosCancelAction: 'സഹായ അഭ്യർത്ഥന റദ്ദാക്കുക',
  L10nKeys.sosDone: 'കഴിഞ്ഞു',
  L10nKeys.sosHelpOnWay: 'ഉടൻ ആരെങ്കിലും നിങ്ങൾക്കൊപ്പമുണ്ടാകും. 🧡',
  L10nKeys.sosNoContacts: 'ഇതുവരെ അടിയന്തര കോൺടാക്റ്റുകളില്ല',
  L10nKeys.sosNoContactsBody:
      'അടിയന്തര കോൺടാക്റ്റുകൾ ചേർക്കാൻ കുടുംബത്തോട് ആവശ്യപ്പെടുക.',
  L10nKeys.sosAddContact: 'കോൺടാക്റ്റ് ചേർക്കുക',
  L10nKeys.sosDisclaimer: 'മൈൻഡ്കെയർ നിങ്ങൾ തിരഞ്ഞെടുത്ത കോൺടാക്റ്റുകളെ അറിയിക്കുന്നു. ഇത് ഔദ്യോഗിക അടിയന്തര സേവനങ്ങൾക്ക് പകരമല്ല.',
  L10nKeys.sosContactedPerson: 'കുടുംബാംഗത്തെ ബന്ധപ്പെട്ടു',
  L10nKeys.sosEscalatedTo: 'അടുത്ത കുടുംബാംഗത്തെ ബന്ധപ്പെട്ടു',
  L10nKeys.sosAcknowledged: 'കുടുംബാംഗം പ്രതികരിച്ചു. സഹായം എത്തുന്നു.',
  L10nKeys.sosNotSilent:
      'സഹായം അയയ്ക്കാൻ കഴിഞ്ഞില്ലെങ്കിൽ ഞങ്ങൾ ഒരിക്കലും നടിക്കില്ല.',
  L10nKeys.sosAlertNotDelivered:
      'നിങ്ങളുടെ സന്ദേശം ഇതുവരെ അയച്ചിട്ടില്ല. ശ്രമിച്ചുകൊണ്ടിരിക്കും.',

  L10nKeys.careTitle: 'പരിചാരകൻ',
  L10nKeys.careDashboard: 'അവലോകനം',
  L10nKeys.carePatients: 'എൻ്റെ രോഗികൾ',
  L10nKeys.careMemories: 'ഓർമ്മകൾ',
  L10nKeys.careContacts: 'അടിയന്തര കോൺടാക്റ്റുകൾ',
  L10nKeys.careSettings: 'ക്രമീകരണങ്ങൾ',
  L10nKeys.careAddMemory: 'ഓർമ്മ ചേർക്കുക',
  L10nKeys.careAddContact: 'കോൺടാക്റ്റ് ചേർക്കുക',
  L10nKeys.careEngagement: 'ഇടപെടൽ',
  L10nKeys.careActivitiesWeek: 'ഈ ആഴ്ചയിലെ പ്രവർത്തനങ്ങൾ',
  L10nKeys.careGardenProgress: 'പൂന്തോട്ടത്തിൻ്റെ പുരോഗതി',
  L10nKeys.careRecentActivity: 'സമീപകാല പ്രവർത്തനം',
  L10nKeys.careNoPatients: 'രോഗികളെ ബന്ധിപ്പിച്ചിട്ടില്ല',
  L10nKeys.careNoPatientsBody: 'കുടുംബാംഗത്തെ ബന്ധിപ്പിക്കാൻ ആവശ്യപ്പെടുക, അല്ലെങ്കിൽ രോഗിയുടെ പ്രൊഫൈൽ ചേർക്കുക.',
  L10nKeys.careAddPatient: 'രോഗിയെ ചേർക്കുക',
  L10nKeys.carePerformanceNote:
      'ഈയിടെ ഈ വ്യക്തിയുടെ പ്രവർത്തന പ്രകടനം സാധാരണ നിലയേക്കാൾ അൽപ്പം കുറവാണ്.',
  L10nKeys.careUploadPhoto: 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'ശബ്ദം റെക്കോർഡ് ചെയ്യുക',
  L10nKeys.careWriteMemory: 'ഓർമ്മ എഴുതുക',
  L10nKeys.careMemoryTitle: 'തലക്കെട്ട്',
  L10nKeys.careMemoryCaption: 'അടിക്കുറിപ്പ്',
  L10nKeys.careMemoryRelation: 'ഇതിൽ ആരുണ്ട്? (ബന്ധം)',
  L10nKeys.careMemoryCategory: 'വിഭാഗം',
  L10nKeys.careContactName: 'പേര്',
  L10nKeys.careContactPhone: 'ഫോൺ നമ്പർ',
  L10nKeys.careContactPriority: 'കോൾ ക്രമം',
  L10nKeys.careContactRelation: 'ബന്ധം',
  L10nKeys.careEscalationTimeout: 'അടുത്ത കോൺടാക്റ്റിന് മുമ്പുള്ള മിനിറ്റുകൾ',
  L10nKeys.careIncidentStatus: 'നില',
  L10nKeys.careAckSos: 'ഞാൻ പ്രതികരിക്കുന്നു',
  L10nKeys.careResponding: 'പ്രതികരിക്കുന്നു',
  L10nKeys.careActiveAlerts: 'സജീവ അലേർട്ടുകൾ',

  L10nKeys.syncSavingOffline: 'ഓഫ്‌ലൈൻ',
  L10nKeys.syncSavingOfflineBody:
      'നിങ്ങളുടെ പ്രവർത്തനങ്ങൾ ഈ ഉപകരണത്തിൽ സുരക്ഷിതമാണ്.',
  L10nKeys.syncSynced: 'സമന്വയിപ്പിച്ചു',
  L10nKeys.syncInfo: 'നിങ്ങളുടെ വിവരങ്ങൾ സമന്വയിപ്പിച്ചു.',
  L10nKeys.syncPending: 'സമന്വയത്തിനായി കാത്തിരിക്കുന്നു',

  L10nKeys.errorGeneric: 'എന്തോ കുഴപ്പം സംഭവിച്ചു',
  L10nKeys.errorGenericBody:
      'നിങ്ങളുടെ പുരോഗതി സുരക്ഷിതമാണ്. വീണ്ടും ശ്രമിക്കുക.',
  L10nKeys.errorAudio: 'ഈ ഉപകരണത്തിൽ ശബ്ദം പ്ലേ ആയില്ല.',
  L10nKeys.errorPermission: 'ഇതിന് ഉപകരണ അനുമതി ആവശ്യമാണ്.',
  L10nKeys.errorNoInternetAction:
      'ഇൻ്റർനെറ്റ് ആവശ്യമില്ല — അത് ആദ്യം ഇവിടെ സൂക്ഷിക്കും.',

  L10nKeys.demoWelcome: 'ഡെമോ കാണുക',
  L10nKeys.demoExplain:
      'നിങ്ങൾക്ക് കാണാനായി മാതൃകാ കുടുംബവും ഓർമ്മകളും ചേർക്കും.',
  L10nKeys.demoLoad: 'ഡെമോ പൂന്തോട്ടം ലോഡ് ചെയ്യുക',

  L10nKeys.unitsPoints: 'പോയിൻ്റുകൾ',
  L10nKeys.teaserChai: 'ചായ ഉണ്ടാക്കാം.',
  L10nKeys.familiarityName: 'ആശ',
  L10nKeys.regionMap: 'എൻ്റെ പ്രദേശം',
  L10nKeys.regionChoose: 'നിങ്ങളുടെ പ്രദേശം തിരഞ്ഞെടുക്കുക',
  L10nKeys.regionIndia: 'ഇന്ത്യ',
  L10nKeys.importantMemory: 'പ്രധാനപ്പെട്ട ഓർമ്മ',
  L10nKeys.growing: 'വളരുന്നു',
  L10nKeys.blooming: 'വിരിയുന്നു',
  L10nKeys.mature: 'പക്വമായത്',
  L10nKeys.noVoice: 'ഈ ഉപകരണത്തിൽ ശബ്ദം ലഭ്യമല്ല.',
  L10nKeys.optional: 'ഐച്ഛികം',

  L10nKeys.langChoose: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
  L10nKeys.langPrimary: 'പ്രാഥമികം',
  L10nKeys.langNorthEast: 'വടക്കുകിഴക്കൻ ഇന്ത്യ',
  L10nKeys.langMajor: 'ഇന്ത്യയിലെ പ്രധാന ഭാഷകൾ',

  L10nKeys.authSignUpTitle: 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
  L10nKeys.authSignUpBody: 'ഈ മൈൻഡ്കെയർ പ്രൊഫൈൽ നിങ്ങളുടെ ഉപകരണത്തിൽ സുരക്ഷിതമാണ്. നിങ്ങൾക്ക് മാത്രം തുറക്കാനായി യൂസർനെയിമും പാസ്വേർഡും ഇടുക.',
  L10nKeys.authLoginTitle: 'തിരിച്ചുവരവ് സ്വാഗതം',
  L10nKeys.authLoginBody: 'നിങ്ങളുടെ പൂന്തോട്ടം തുറക്കാൻ യൂസർനെയിമും പാസ്വേർഡും ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക.',
  L10nKeys.authUsername: 'യൂസർനെയിം',
  L10nKeys.authUsernameHint: 'ഉദാ: ranu123',
  L10nKeys.authDisplayName: 'നിങ്ങളുടെ പേര്',
  L10nKeys.authPassword: 'പാസ്വേർഡ്',
  L10nKeys.authPasswordHint: 'കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ',
  L10nKeys.authConfirmPassword: 'പാസ്വേർഡ് സ്ഥിരീകരിക്കുക',
  L10nKeys.authRoleQuestion: 'ഈ പ്രൊഫൈൽ ആർക്കുവേണ്ടി…',
  L10nKeys.authRolePatient: 'എനിക്കുവേണ്ടി',
  L10nKeys.authRoleCaregiver: 'കുടുംബാംഗത്തിനുവേണ്ടി',
  L10nKeys.authCreate: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
  L10nKeys.authSignIn: 'സൈൻ ഇൻ',
  L10nKeys.authSignOut: 'സൈൻ ഔട്ട്',
  L10nKeys.authAccount: 'അക്കൗണ്ട്',
  L10nKeys.caregiverTitle: 'പരിചാരകൻ',
  L10nKeys.caregiverNotLinked: 'ഇതുവരെ പരിചാരകനെ ബന്ധിപ്പിച്ചിട്ടില്ല',
  L10nKeys.authBadCredentials: 'യൂസർനെയിം അല്ലെങ്കിൽ പാസ്വേർഡ് തെറ്റാണ്.',
  L10nKeys.authUsernameTaken:
      'ഈ യൂസർനെയിം ഈ ഉപകരണത്തിൽ ഇതിനകം ഉപയോഗത്തിലുണ്ട്.',
  L10nKeys.authPasswordMismatch: 'പാസ്വേർഡുകൾ പൊരുത്തപ്പെടുന്നില്ല.',
  L10nKeys.authUsernameShort: 'യൂസർനെയിം കുറഞ്ഞത് 3 അക്ഷരം വേണം.',
  L10nKeys.authUsernameInvalid: 'അക്ഷരങ്ങൾ, അക്കങ്ങൾ, ഡോട്ട്, ഡാഷ് അല്ലെങ്കിൽ അണ്ടർസ്കോർ മാത്രം ഉപയോഗിക്കുക.',
  L10nKeys.authPasswordShort: 'പാസ്വേർഡ് കുറഞ്ഞത് 6 അക്ഷരം വേണം.',
  L10nKeys.authNameRequired: 'ദയവായി പേര് നൽകുക.',
  L10nKeys.authSignOutConfirm: 'ഈ പ്രൊഫൈലിൽ നിന്ന് സൈൻ ഔട്ട് ചെയ്യണോ?',
  L10nKeys.screenTitle: 'ദ്രുത ഓർമശക്തി പരിശോധന',
  L10nKeys.screenIntro: 'രോഗിയെക്കുറിച്ച് കുറച്ച് ചെറിയ ചോദ്യങ്ങൾ ചോദിക്കും. കഴിഞ്ഞ ഏതാനും മാസങ്ങളായി അവർ എങ്ങനെയായിരുന്നുവെന്ന് ചിന്തിക്കുക.',
  L10nKeys.screenNotSure: 'ഉറപ്പില്ല',
  L10nKeys.screenFinish: 'എന്റെ ഫലം കാണുക',
  L10nKeys.screenSkip: 'ഇപ്പോൾ വേണ്ട',
  L10nKeys.screenResultBack: 'കഴിഞ്ഞു',
  L10nKeys.screenCheckAgain: 'വീണ്ടും പരിശോധിക്കുക',
  L10nKeys.screenStartCheckup: 'പരിശോധന ആരംഭിക്കുക',
  L10nKeys.screenSkipped: 'പരിശോധന ഒഴിവാക്കി',
  L10nKeys.screenStatusGood: 'എല്ലാം ശരിയാണ്',
  L10nKeys.screenStatusGoodBody: 'വലിയ ആശങ്കയൊന്നും കണ്ടില്ല. ദൈനംദിന പ്രവർത്തനങ്ങൾ തുടരുക, എന്തെങ്കിലും മാറിയാൽ എപ്പോൾ വേണമെങ്കിലും വീണ്ടും പരിശോധിക്കാം.',
  L10nKeys.screenStatusWatch: 'ചില മാറ്റങ്ങൾ കണ്ടു',
  L10nKeys.screenStatusWatchBody: 'മറക്കുന്ന ചില നിമിഷങ്ങൾ കണ്ടു. ഇത് പ്രായത്തിനനുസരിച്ച് സാധാരണമാണ്, പക്ഷേ ശ്രദ്ധിക്കുകയും അടുത്ത ഡോക്ടർ സന്ദർശനത്തിൽ പറയുകയും ചെയ്യുക.',
  L10nKeys.screenStatusDoctor: 'ദയവായി പരിശോധന നടത്തുക',
  L10nKeys.screenStatusDoctorBody: 'ശ്രദ്ധ ആവശ്യമുള്ള ചില ലക്ഷണങ്ങൾ കണ്ടു. അവർക്ക് സഹായിക്കാനാകാൻ ഇവ ഡോക്ടറോടോ ക്ലിനിക്കിനോടോ പങ്കിടുക.',
  L10nKeys.screenRarely: 'അപൂർവമായി',
  L10nKeys.screenSometimes: 'ചിലപ്പോൾ',
  L10nKeys.screenFrequently: 'ഇടയ്ക്കിടെ',
  L10nKeys.screenVeryFrequently: 'വളരെ ഇടയ്ക്കിടെ',
  L10nKeys.screenQ01: 'സമീപകാല സംഭവങ്ങൾ ഓർക്കാൻ അവർക്ക് ബുദ്ധിമുട്ടുണ്ടോ?',
  L10nKeys.screenQ02: 'അതേ ചോദ്യങ്ങളോ കഥകളോ അവർ ആവർത്തിക്കുന്നുണ്ടോ?',
  L10nKeys.screenQ03: 'പരിചയമുള്ളവരുടെ പേരുകൾ അവർ മറക്കുന്നുണ്ടോ?',
  L10nKeys.screenQ04: 'പരിചയമുള്ള മുഖങ്ങൾ തിരിച്ചറിയാൻ ബുദ്ധിമുട്ടുണ്ടോ?',
  L10nKeys.screenQ05: 'കൂടിക്കാഴ്ചകളോ പ്രധാന സംഭവങ്ങളോ അവർ മറക്കുന്നുണ്ടോ?',
  L10nKeys.screenQ06: 'ശരിയായ വാക്കുകൾ കണ്ടെത്താൻ ബുദ്ധിമുട്ടുണ്ടോ?',
  L10nKeys.screenQ07: 'തങ്ങൾ എവിടെയാണെന്ന് അവർ ആശയക്കുഴപ്പത്തിലാകുന്നുണ്ടോ?',
  L10nKeys.screenQ08: 'ദൈനംദിന പ്രവർത്തനങ്ങൾക്ക് അവർക്ക് ഓർമ്മപ്പെടുത്തൽ വേണോ?',
  L10nKeys.screenQ09: 'മരുന്നുകൾ കൈകാര്യം ചെയ്യാൻ ബുദ്ധിമുട്ടുണ്ടോ?',
  L10nKeys.screenQ10:
      'ആശയക്കുഴപ്പത്തിൽ അവർ ഉത്കണ്ഠാകുലരോ പ്രകോപിതരോ ആകുന്നുണ്ടോ?',
  L10nKeys.screenQ11: 'സംഭാഷണങ്ങൾ പിന്തുടരാൻ ബുദ്ധിമുട്ടുണ്ടോ?',
  L10nKeys.screenQ12: 'പരിചയമുള്ള ജോലികൾ പൂർത്തിയാക്കാൻ ബുദ്ധിമുട്ടുണ്ടോ?',
  L10nKeys.screenQ13: 'ദൈനംദിന വസ്തുക്കൾ എവിടെയാണെന്ന് അവർ മറക്കുന്നുണ്ടോ?',
  L10nKeys.screenQ14: 'നിർദ്ദേശങ്ങൾ ഓർക്കാൻ ബുദ്ധിമുട്ടുണ്ടോ?',
  L10nKeys.screenQ15: 'ബഹുതല ജോലികൾ ചെയ്യാൻ ബുദ്ധിമുട്ടുണ്ടോ?',

  L10nKeys.careDashboardSubtitle: 'കുടുംബ പരിചരണം',
  L10nKeys.careSosLive: 'തത്സമയ അലർട്ട്',
  L10nKeys.careSosRespondedBy: '{name} മറുപടി നൽകി',
  L10nKeys.careLinkTitle: 'കുടുംബാംഗവുമായി ബന്ധിപ്പിക്കുക',
  L10nKeys.careLinkBody: 'അവരുടെ ഫോണിൽ കാണിക്കുന്ന 6-അക്ഷര കുടുംബ കോഡ് നിങ്ങളുടെ പ്രിയപ്പെട്ടവരോട് ചോദിക്കുക, തുടർന്ന് ബന്ധിപ്പിക്കുക.',
  L10nKeys.careLinkCode: 'കുടുംബ കോഡ്',
  L10nKeys.careLinkCodeHint: 'ഉദാ. A1B2C3',
  L10nKeys.careLinkConnect: 'ബന്ധിപ്പിക്കുക',
  L10nKeys.careLinkDone: 'ബന്ധിപ്പിച്ചു',
  L10nKeys.careLinkSuccess:
      '{name}-നുമായി ബന്ധിപ്പിച്ചു! ഓർമ്മകളും അലർട്ടുകളും ഇനി സമന്വയിക്കും.',
  L10nKeys.careLinkFailed:
      'ബന്ധിപ്പിക്കാൻ കഴിഞ്ഞില്ല. കോഡ് പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
  L10nKeys.careTrendsTitle: 'AI പ്രവണതകൾ',
  L10nKeys.careTrendsBody: 'പ്രവർത്തന തരം അനുസരിച്ച് ദൈനംദിന കൃത്യത',
  L10nKeys.careTrendsNoData:
      'ഇതുവരെ പ്രവർത്തനമില്ല — പ്രവണതകൾ കാണാൻ ഒരു വ്യായാമം പൂർത്തിയാക്കുക.',
  L10nKeys.careAiDifficulty: 'സ്വയം ക്രമീകരിച്ച ബുദ്ധിമുട്ട്',
  L10nKeys.careAiAccuracy: 'മോഡലിന്റെ കൃത്യത',
  L10nKeys.careAiRealSessions: 'യഥാർത്ഥ സെഷനുകൾ',
  L10nKeys.careAiDemoSessions: 'ഡെമോ സെഷനുകൾ',
  L10nKeys.careNavGames: 'ഗെയിമുകൾ',
  L10nKeys.careNavRoutine: 'ദിനചര്യ',
  L10nKeys.careGreetSubtitle: 'ഇന്ന് {name} എങ്ങനെയുണ്ട് എന്നത് ഇതാ.',
  L10nKeys.careNotifEmpty: 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല',
  L10nKeys.careWellnessScore: 'വൈജ്ഞാനിക ക്ഷേമ സ്കോർ',
  L10nKeys.careStatusStable: 'സ്ഥിരം',
  L10nKeys.careStatusAttention: 'ശ്രദ്ധ ആവശ്യമാണ്',
  L10nKeys.careLastSynced: 'അവസാനം സമന്വയിപ്പിച്ചത് {time}',
  L10nKeys.careMinAgo: '{n} മിനിറ്റ് മുമ്പ്',
  L10nKeys.careGamesWeek: 'ഈ ആഴ്ചയിലെ ഗെയിമുകൾ',
  L10nKeys.careRoutineCompletion: 'ദിനചര്യ പൂർത്തീകരണം',
  L10nKeys.careCurrentStreak: 'നിലവിലെ തുടർച്ച',
  L10nKeys.careMoodCheckins: 'മാനസികാവസ്ഥ ചെക്ക്-ഇനുകൾ',
  L10nKeys.careDayUnit: 'ദിവസം',
  L10nKeys.careDaysUnit: 'ദിവസങ്ങൾ',
  L10nKeys.careActivityTitle: 'ആഴ്ചയിലെ പ്രവർത്തനം',
  L10nKeys.careWeekly: 'ആഴ്ചയിൽ',
  L10nKeys.careMonthly: 'മാസത്തിൽ',
  L10nKeys.careNoActivityWeek:
      'ഈ ആഴ്ച ഇതുവരെ പ്രവർത്തനങ്ങൾ രേഖപ്പെടുത്തിയിട്ടില്ല.',
  L10nKeys.careMoodTitle: 'മാനസികാവസ്ഥ',
  L10nKeys.careMoodHappy: 'സന്തോഷം',
  L10nKeys.careMoodCalm: 'ശാന്തം',
  L10nKeys.careMoodNeutral: 'നിഷ്പക്ഷം',
  L10nKeys.careMoodLow: 'താഴ്ന്നത്',
  L10nKeys.careMood7Days: 'കഴിഞ്ഞ 7 ദിവസം',
  L10nKeys.careMoodInsight: '{name} ഈ ആഴ്ച കൂടുതലും ശാന്തരായിരുന്നു, കഴിഞ്ഞ രണ്ട് ദിവസങ്ങളിൽ നേരിയ ഇടിവ് ഉണ്ടായി.',
  L10nKeys.careMoodNoData: 'ഈ ആഴ്ച ഇതുവരെ മാനസികാവസ്ഥ ചെക്ക്-ഇനുകളൊന്നുമില്ല.',
  L10nKeys.careSkillsTitle: 'വൈജ്ഞാനിക കഴിവുകൾ',
  L10nKeys.careSkillMemory: 'മെമ്മറി',
  L10nKeys.careSkillAttention: 'ശ്രദ്ധ',
  L10nKeys.careSkillLanguage: 'ഭാഷ',
  L10nKeys.careSkillReasoning: 'യുക്തി',
  L10nKeys.careSkillProcessing: 'പ്രോസസ്സിംഗ് വേഗത',
  L10nKeys.careInsightToday: 'ഇന്നത്തെ ഉൾക്കാഴ്ച',
  L10nKeys.careInsightBody: 'രാവിലത്തെ ദിനചര്യയ്ക്ക് ശേഷം റോബർട്ട് മെമ്മറി പ്രവർത്തനങ്ങളിൽ സ്ഥിരത പുലർത്തി. കഴിഞ്ഞ രണ്ട് ദിവസങ്ങളിൽ അദ്ദേഹത്തിന്റെ മാനസികാവസ്ഥ അൽപ്പം കുറവായിരുന്നു.',
  L10nKeys.careInsightBodyReal: 'ഈ ആഴ്ച {name} {count} വൈജ്ഞാനിക സെഷനുകൾ (ലക്ഷ്യം {goal}) പൂർത്തിയാക്കി, {streak}-ദിവസത്തെ തുടർച്ച നിലനിർത്തുന്നു.',
  L10nKeys.careViewDetails: 'വിശദാംശങ്ങൾ കാണുക',
  L10nKeys.careInsightDisclaimer:
      'ഇത് ഡാറ്റയിൽ നിന്നുള്ള ഒരു സൗമ്യ നിരീക്ഷണമാണ് — മെഡിക്കൽ രോഗനിർണയമല്ല.',
  L10nKeys.careAttentionTitle: 'നിങ്ങളുടെ ശ്രദ്ധ ആവശ്യമാണ്',
  L10nKeys.careAttentionEmpty: 'ഇപ്പോൾ നിങ്ങളുടെ ശ്രദ്ധ ആവശ്യമുള്ള ഒന്നുമില്ല.',
  L10nKeys.careAlertSos: '{name} SOS ബട്ടൺ അമർത്തി',
  L10nKeys.careAlertRoutineMissed: 'ഇന്നലെ ദിനചര്യ ഒഴിവാക്കി',
  L10nKeys.careAlertMoodDown: 'കഴിഞ്ഞ രണ്ട് ദിവസങ്ങളിൽ മാനസികാവസ്ഥ കുറഞ്ഞു',
  L10nKeys.careAlertSessionPending:
      'ഇന്ന് വൈജ്ഞാനിക സെഷൻ പൂർത്തിയാക്കിയിട്ടില്ല',
  L10nKeys.careAlertSeverityHigh: 'ഉയർന്നത്',
  L10nKeys.careAlertSeverityMedium: 'ഇടത്തരം',
  L10nKeys.careAlertSeverityLow: 'കുറഞ്ഞത്',
  L10nKeys.careWeeklySummary: 'ആഴ്ചയിലെ സംഗ്രഹം',
  L10nKeys.careSessionsCompleted: 'പൂർത്തിയാക്കിയ സെഷനുകൾ',
  L10nKeys.careAvgSessionDuration: 'ശരാശരി സെഷൻ ദൈർഘ്യം',
  L10nKeys.careRoutineAdherence: 'ദിനചര്യ പാലിക്കൽ',
  L10nKeys.careMoodTrend: 'മാനസികാവസ്ഥ പ്രവണത',
  L10nKeys.careMoodTrendSlightlyDown: 'അൽപ്പം കുറവ്',
  L10nKeys.careMoodTrendStable: 'സ്ഥിരം',
  L10nKeys.careMoodTrendUp: 'മെച്ചപ്പെട്ടുവരുന്നു',
  L10nKeys.careVsLastWeek: 'കഴിഞ്ഞ ആഴ്ചയുമായി താരതമ്യം',
  L10nKeys.careSyncedJustNow: 'ഇപ്പോൾ തന്നെ സമന്വയിപ്പിച്ചു',
  L10nKeys.careOfflineWaiting:
      'ഓഫ്ലൈൻ · സമന്വയിപ്പിക്കാൻ കാത്തിരിക്കുന്ന {count} പ്രവർത്തനങ്ങൾ',
  L10nKeys.careComingSoon: 'ഉടൻ വരുന്നു',
  L10nKeys.careHomeSoon:
      '{name}ന്റെ ദിവസത്തെ ഒരു വേഗത്തിലുള്ള അവലോകനം ഇവിടെ കാണിക്കും.',
  L10nKeys.careGamesSoon: 'ഗെയിമുകളും സെഷൻ ചരിത്രവും ഇവിടെ കാണിക്കും.',
  L10nKeys.careRoutineSoon: 'രോഗിയുടെ ദൈനംദിന ദിനചര്യ ഇവിടെ കാണിക്കും.',
  L10nKeys.careProfileSoon:
      'പരിചാരകന്റെ പ്രൊഫൈലും ക്രമീകരണങ്ങളും ഇവിടെ കാണിക്കും.',
  L10nKeys.serverPairingTitle: 'കുടുംബ കോഡ്',
  L10nKeys.serverPairingBody:
      'ഒരു പരിചാരകരുമായി ഈ കോഡ് പങ്കിടുക, അവർക്ക് നിങ്ങളുമായി ബന്ധപ്പെടാനാകും.',
  L10nKeys.serverUnlinked: 'സെർവറുമായി ബന്ധിപ്പിച്ചിട്ടില്ല',
  L10nKeys.serverLinked: 'സെർവറുമായി ബന്ധിപ്പിച്ചു',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
  // Patient-home, memories, voice and calendar fallbacks (English source).
  L10nKeys.addFirstRoutine: 'Add your first routine',
  L10nKeys.addMemoryTooltip: 'Add a memory',
  L10nKeys.addRoutine: 'Add routine',
  L10nKeys.addToMemory: 'Add to this memory',
  L10nKeys.attachmentsAddedMany: '{count} attachments added',
  L10nKeys.attachmentsAddedOne: '1 attachment added',
  L10nKeys.careAchieveEngagement: '10 Hours of Play',
  L10nKeys.careAchieveEngagementBody: '10 total hours spent playing together',
  L10nKeys.careAchieveFirstSteps: 'First Steps',
  L10nKeys.careAchieveFirstStepsBody: 'Patient completed their first session',
  L10nKeys.careAchieveGarden: 'Garden in Bloom',
  L10nKeys.careAchieveGardenBody: 'Grow 5 plants in the Memory Garden',
  L10nKeys.careAchievePerfect: 'Perfect Round',
  L10nKeys.careAchievePerfectBody: 'A game finished with a perfect score',
  L10nKeys.careAchieveSevenDay: 'One Week Together',
  L10nKeys.careAchieveSevenDayBody: 'A session on 7 different days',
  L10nKeys.categoryLabel: 'Category',
  L10nKeys.createMemory: 'Create a Memory',
  L10nKeys.deleteAction: 'Delete',
  L10nKeys.deleteRoutineBody: 'Remove "{title}" from your routine?',
  L10nKeys.deleteRoutineTitle: 'Delete routine?',
  L10nKeys.deleteRoutineTooltip: 'Delete routine',
  L10nKeys.homeRoutineSubtitle: 'A calm little plan for your day.',
  L10nKeys.medicineKind: 'Medicine',
  L10nKeys.memoriesKindVideo: 'Video',
  L10nKeys.memoriesSubtitle: 'Keep your favourite moments close.',
  L10nKeys.memoryCaptionHint: 'What happened? Who was there? How did it feel?',
  L10nKeys.memoryCaptionLabel: 'Write something about this memory',
  L10nKeys.memoryComposeHint: 'Add a title, some text, and as many photos, videos or voice notes as you want.',
  L10nKeys.memorySaved: 'Memory saved 💙',
  L10nKeys.memoryTitleHint: 'e.g. My daughter\'s wedding',
  L10nKeys.memoryTitleLabel: 'Memory title',
  L10nKeys.memoryTitleRequired: 'Please give this memory a title.',
  L10nKeys.micVoicePermission: 'Microphone permission is needed for a voice memory.',
  L10nKeys.monthApr: 'Apr',
  L10nKeys.monthAug: 'Aug',
  L10nKeys.monthDec: 'Dec',
  L10nKeys.monthFeb: 'Feb',
  L10nKeys.monthJan: 'Jan',
  L10nKeys.monthJul: 'Jul',
  L10nKeys.monthJun: 'Jun',
  L10nKeys.monthMar: 'Mar',
  L10nKeys.monthMay: 'May',
  L10nKeys.monthNov: 'Nov',
  L10nKeys.monthOct: 'Oct',
  L10nKeys.monthSep: 'Sep',
  L10nKeys.photoAddFailed: 'Could not add this photo. Please try again.',
  L10nKeys.profileMissing: 'No patient profile found. Please sign in again.',
  L10nKeys.recordingStartFailed: 'Could not start recording. Please try again.',
  L10nKeys.routineAddBody: 'Create a simple reminder for your day.',
  L10nKeys.routineAddTitle: 'Add a routine',
  L10nKeys.routineCheckBody: 'Small steps for a good day',
  L10nKeys.routineCheckTitle: 'Routine check',
  L10nKeys.routineKind: 'Routine',
  L10nKeys.routineNameHint: 'e.g. Drink water',
  L10nKeys.routineNameLabel: 'Routine name',
  L10nKeys.savedMemoriesTitle: 'Saved Memories',
  L10nKeys.saveMemory: 'Save Memory',
  L10nKeys.settings: 'Settings',
  L10nKeys.sosShort: 'SOS',
  L10nKeys.stop: 'Stop',
  L10nKeys.stopVoiceFirst: 'Stop the voice recording first.',
  L10nKeys.textShort: 'Text',
  L10nKeys.timeLabel: 'Time',
  L10nKeys.videoAddFailed: 'Could not add this video. Please try again.',
  L10nKeys.voiceSaveFailed: 'Could not save the voice recording.',
  L10nKeys.voiceShort: 'Voice',
  L10nKeys.waterKind: 'Water',
};
