import '../l10n_keys.dart';

/// Hindi dictionary.
const Map<String, String> stringsHi = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'आपका स्मृति साथी',
  L10nKeys.back: 'वापस',
  L10nKeys.next: 'आगे',
  L10nKeys.continueText: 'जारी रखें',
  L10nKeys.skip: 'छोड़ें',
  L10nKeys.done: 'हो गया',
  L10nKeys.cancel: 'रद्द करें',
  L10nKeys.yes: 'हाँ',
  L10nKeys.no: 'नहीं',
  L10nKeys.save: 'सहेजें',
  L10nKeys.close: 'बंद करें',
  L10nKeys.retry: 'फिर से कोशिश करें',
  L10nKeys.add: 'जोड़ें',
  L10nKeys.edit: 'बदलें',
  L10nKeys.remove: 'हटाएँ',
  L10nKeys.search: 'खोजें',
  L10nKeys.today: 'आज',
  L10nKeys.offline: 'ऑफ़लाइन',
  L10nKeys.online: 'ऑनलाइन',

  L10nKeys.goodMorning: 'सुप्रभात',
  L10nKeys.goodAfternoon: 'नमस्ते',
  L10nKeys.goodEvening: 'शुभ संध्या',
  L10nKeys.goodNight: 'शुभ रात्रि',

  L10nKeys.navHome: 'घर',
  L10nKeys.navGarden: 'बगीचा',
  L10nKeys.navActivities: 'गतिविधियाँ',
  L10nKeys.navMemories: 'यादें',
  L10nKeys.navProfile: 'प्रोफ़ाइल',
  L10nKeys.navMystery: 'आज की याद',

  L10nKeys.onboardingWelcomeTitle: 'आपकी यादों का एक कोमल साथी',
  L10nKeys.onboardingWelcomeBody: 'माइंडकेयर आपको याद रखने, खेलने और परिवार से जुड़ने में मदद करता है — इंटरनेट के बिना भी।',
  L10nKeys.onboardingNameTitle: 'हम आपको क्या कहकर बुलाएँ?',
  L10nKeys.onboardingNameHint: 'आपका नाम',
  L10nKeys.onboardingRegionTitle: 'आपका घर कहाँ है?',
  L10nKeys.onboardingRegionHint: 'शहर या कस्बा',
  L10nKeys.onboardingRegionList: 'गुवाहाटी, सिलचर, शिलांग, अगरतला, इंफाल, आइज़ोल, ईटानगर, कोहिमा, गंगटोक, डिब्रूगढ़, जोरहाट, आपका शहर',
  L10nKeys.onboardingLanguageTitle: 'आप कौन सी भाषा चाहेंगे?',
  L10nKeys.onboardingLanguageBody: 'आप इसे कभी भी बदल सकते हैं।',
  L10nKeys.onboardingFamilyTitle: 'आपका परिवार कौन है?',
  L10nKeys.onboardingFamilyBody: 'अपने प्यारे लोगों को जोड़ें। हम उनकी तस्वीरें और आवाज़ें कोमल यादों के रूप में दिखाएँगे।',
  L10nKeys.onboardingAddFamily: 'परिवार का सदस्य जोड़ें',
  L10nKeys.onboardingEmergencyTitle: 'आपातकाल में हम किसे बुलाएँ?',
  L10nKeys.onboardingEmergencyBody: 'SOS दबाने पर माइंडकेयर आपके परिवार को सूचित करता है, आपातकालीन सेवाओं को नहीं।',
  L10nKeys.onboardingEmergencyName: 'नाम',
  L10nKeys.onboardingEmergencyPhone: 'फ़ोन नंबर',
  L10nKeys.onboardingEmergencyRelation: 'रिश्ता (बेटी, बेटा…)',
  L10nKeys.onboardingDoneTitle: 'आपका बगीचा तैयार है!',
  L10nKeys.onboardingDoneBody: 'छोटी गतिविधियाँ पूरी करें और अपना बगीचा बढ़ता देखें। हम हमेशा आपके साथ हैं।',
  L10nKeys.onboardingStart: 'मेरा बगीचा शुरू करें',

  L10nKeys.homeWhatsGrowing: 'आज क्या बढ़ रहा है?',
  L10nKeys.homeTodayActivity: 'आज की छोटी गतिविधि',
  L10nKeys.homeActivityDuration: 'लगभग ३ मिनट',
  L10nKeys.homeMinutes: 'मिनट',
  L10nKeys.homeMemoryOfDay: 'आज की याद',
  L10nKeys.homeMemoryLocked: 'एक खास याद आपका इंतज़ार कर रही है…',
  L10nKeys.homeMemoryUnlocked: 'एक याद खुल गई है!',
  L10nKeys.homeContinueActivity: 'गतिविधि जारी रखें',
  L10nKeys.homeFamilyMemory: 'आपके परिवार की ओर से',
  L10nKeys.homeFamilyMemoryEmpty: 'परिवार की यादें यहाँ आ सकती हैं।',
  L10nKeys.homeSos: 'मदद चाहिए',
  L10nKeys.homeSosSubtitle: 'आपातकाल में परिवार से संपर्क करें',
  L10nKeys.homeGardenPreview: 'आपका बगीचा',
  L10nKeys.homeEngine: 'माइंडकेयर साथी',
  L10nKeys.homeEngineReady: 'आपका सहायक तैयार है।',
  L10nKeys.homeWelcomeBack: 'वापसी पर स्वागत! चलिए बगीचा आगे बढ़ाएँ। 🌸',
  L10nKeys.homeNoActivity: 'आज कोई गतिविधि नहीं',
  L10nKeys.homeNoActivityBody: 'आराम करें — या कोई भी गतिविधि चुनें। 🌻',

  L10nKeys.gardenTitle: 'मेरा स्मृति बगीचा',
  L10nKeys.gardenSectionAll: 'सभी',
  L10nKeys.gardenSectionFamily: 'परिवार',
  L10nKeys.gardenSectionChildhood: 'बचपन',
  L10nKeys.gardenSectionPlaces: 'स्थान',
  L10nKeys.gardenSectionFestivals: 'त्योहार',
  L10nKeys.gardenEmpty: 'आपका बगीचा अभी शुरू हुआ है',
  L10nKeys.gardenEmptyBody: 'पहली गतिविधि पूरी करें, एक बीज यहाँ बोया जाएगा।',
  L10nKeys.gardenPoints: 'अंक',
  L10nKeys.gardenLevel: 'स्तर',
  L10nKeys.gardenSeed: 'बीज',
  L10nKeys.gardenPlant: 'पौधा',
  L10nKeys.gardenFlower: 'फूल',
  L10nKeys.gardenTree: 'पेड़',
  L10nKeys.gardenMilestone: 'मील का पत्थर',
  L10nKeys.gardenGrowth: 'बढ़ रहा',
  L10nKeys.gardenDidYouKnow: 'हर गतिविधि पूरी होने पर आपका बगीचा बढ़ता है।',
  L10nKeys.gardenPlantSeed: 'बीज बोएँ',

  L10nKeys.activitiesTitle: 'गतिविधियाँ',
  L10nKeys.activitiesToday: 'आज',
  L10nKeys.activitiesLibrary: 'और गतिविधियाँ',
  L10nKeys.mainGamesTitle: 'मुख्य खेल',
  L10nKeys.activitiesStart: 'शुरू करें',
  L10nKeys.activitiesCompleted: 'पूरी हुई',
  L10nKeys.activitiesInProgress: 'जारी',
  L10nKeys.activitiesNotStarted: 'तैयार',
  L10nKeys.activityYoureDone: 'बहुत सुंदर!',
  L10nKeys.activityPraise: 'आपने अपने बगीचे में एक नई जान डाल दी। 🌱',
  L10nKeys.activityHint: 'संकेत चाहिए?',
  L10nKeys.activityTryAgain: 'इस याद को फिर से देखें',
  L10nKeys.activityOptionsHint: 'अपना उत्तर चुनें',
  L10nKeys.activityTapToMatch: 'जो एक साथ जुड़ते हैं उन्हें चुनें',
  L10nKeys.activityNext: 'आगे',
  L10nKeys.activityFinish: 'समाप्त',
  L10nKeys.activityGroupLetsAgain: 'इसे फिर से देखें',
  L10nKeys.activityGroupTogether: 'चलिए यह साथ मिलकर करें',
  L10nKeys.activityGreatJob: 'बहुत अच्छे!',
  L10nKeys.activityKitchen: 'मेरी रसोई',
  L10nKeys.activityShopping: 'मेरी दुकान',
  L10nKeys.activityMatching: 'जोड़ी मिलाएँ',
  L10nKeys.activitySequence: 'क्रम में लगाएँ',
  L10nKeys.activityRecognition: 'यह क्या है?',
  L10nKeys.activityAssociation: 'क्या एक साथ आता है?',
  L10nKeys.activityRecall: 'क्या आपको याद है?',
  L10nKeys.activityAttention: 'इसे खोजें',
  L10nKeys.activityDurationSuffix: 'मिनट',
  L10nKeys.activityTodayDone: 'आज की गतिविधि पूरी हुई',
  L10nKeys.activityTodayDoneBody:
      'आपका बगीचा बढ़ा। कल एक नई याद इंतज़ार कर सकती है।',
  L10nKeys.activityGardenGrew: 'आपका बगीचा बढ़ा!',
  L10nKeys.activityMemoryUnlocked: 'एक याद खुल गई है',
  L10nKeys.activityReadAloud: 'ज़ोर से पढ़ें',

  L10nKeys.kitchenTitle: 'चलिए चाय बनाएँ',
  L10nKeys.kitchenMakeChai: 'चाय बनाना',
  L10nKeys.kitchenMakeChaiPrompt: 'चरणों को सही क्रम में चुनें।',
  L10nKeys.kitchenSteps: 'चरण',
  L10nKeys.kitchenTapInOrder: 'चरणों को सही क्रम में चुनें',
  L10nKeys.kitchenCorrectOrder: 'बढ़िया! चाय तैयार!',
  L10nKeys.kitchenBreakfast: 'नाश्ता बनाना',
  L10nKeys.kitchenBreakfastHint: 'दिन की ताज़ा शुरुआत',
  L10nKeys.kitchenBreakfastPrompt: 'नाश्ते के चरणों को सही क्रम में लगाएँ।',

  L10nKeys.shopTitle: 'मेरी दुकान',
  L10nKeys.shopGetMilkBread: 'ब्रेड और दूध',
  L10nKeys.shopGetMilkBreadPrompt: '₹100 के अंदर दूध और ब्रेड लें।',
  L10nKeys.shopBudget: 'बजट',
  L10nKeys.shopBasket: 'आपकी टोकरी',
  L10nKeys.shopTotal: 'कुल',
  L10nKeys.shopWithinBudget: 'बजट के अंदर!',
  L10nKeys.shopOverBudget: 'बजट से ज़्यादा — फिर देखें',
  L10nKeys.shopCheckout: 'समाप्त और भुगतान',
  L10nKeys.shopBuy: 'टोकरी में डालें',
  L10nKeys.shopSell: 'हटाएँ',
  L10nKeys.shopVeggies: 'रात के खाने की सब्ज़ियाँ',
  L10nKeys.shopVeggiesPrompt: '₹60 के अंदर आलू और प्याज़ लें।',
  L10nKeys.recKitchenItem: 'यह कौन सी चीज़ है?',
  L10nKeys.recKitchenItemPrompt:
      'बाज़ार से सामान लाने के लिए इनमें से किसका उपयोग होता है?',
  L10nKeys.recCurrency: 'थोड़ा पैसा',
  L10nKeys.recCurrencyPrompt: 'कौन सा नोट ₹20 का है?',
  L10nKeys.matchFestival: 'त्योहार जोड़ें',
  L10nKeys.matchFestivalPrompt: 'हर त्योहार को उसकी खास मिठाई से जोड़ें।',
  L10nKeys.matchObjectUse: 'जोड़ी मिलाएँ',
  L10nKeys.matchObjectUsePrompt: 'हर चीज़ को उसके उपयोग के समय से जोड़ें।',
  L10nKeys.seqMorning: 'सुबह की दिनचर्या',
  L10nKeys.seqMorningPrompt: 'अपनी सुबह की दिनचर्या को क्रम में लगाएँ।',
  L10nKeys.seqRoute: 'सुबह की यात्रा',
  L10nKeys.seqRoutePrompt: 'बाज़ार की यात्रा को क्रम में लगाएँ।',
  L10nKeys.assoRegion: 'यहाँ क्या है?',
  L10nKeys.assoRegionPrompt: 'असम किसके लिए मशहूर है?',
  L10nKeys.assoHarvest: 'मीठा फल',
  L10nKeys.assoHarvestPrompt: 'किस फल को गर्मी का राजा कहा जाता है?',
  L10nKeys.attnVeg: 'गाजर खोजें',
  L10nKeys.attnVegPrompt: 'क्या आपको गाजर मिल सकती है?',
  L10nKeys.recallSong: 'एक जाना-पहचाना गाना',
  L10nKeys.recallSongPrompt: 'बिहू पर नर्तक किस गाने पर नाचते हैं?',
  L10nKeys.activityPairs: 'जोड़ियाँ खोजें',
  L10nKeys.activitySequenceRecall: 'क्रम याद रखें',
  L10nKeys.activityFindChanged: 'क्या बदला?',
  L10nKeys.pairsFruits: 'बाज़ार के फल',
  L10nKeys.pairsKitchen: 'रसोई की चीज़ें',
  L10nKeys.pairsRemember: 'सभी कार्ड ध्यान से देखें, फिर एक जैसी जोड़ी खोजें।',
  L10nKeys.pairsStart: 'कार्ड छिपाएँ और शुरू करें',
  L10nKeys.pairsFound: 'जोड़ी मिल गई!',
  L10nKeys.seqRecallItems: 'रोज़ की चीज़ें',
  L10nKeys.seqRecallNumbers: 'क्रम में अंक',
  L10nKeys.seqRecallWatch: 'कार्ड ध्यान से देखें – हर एक क्रम से रोशन होगा।',
  L10nKeys.seqRecallRepeat: 'अब वही क्रम दोहराएँ जो आपने देखा।',
  L10nKeys.changeMarket: 'फलों की टोकरी',
  L10nKeys.changeFestival: 'त्योहार की रोशनी',
  L10nKeys.changeRemember: 'इन चित्रों को ध्यान से याद रखें।',
  L10nKeys.changeFind: 'एक चित्र बदल गया। अलग चित्र खोजें।',
  L10nKeys.changeCorrect: 'शाबाश! वही बदला था।',

  L10nKeys.mysteryTitle: 'आज की खास याद',
  L10nKeys.mysteryLocked: 'एक खास याद आपका इंतज़ार कर रही है…',
  L10nKeys.mysteryLockedBody:
      'आज २-३ छोटी गतिविधियाँ करें, शायद यह खुल जाए। यह क्या होगा?',
  L10nKeys.mysteryUnlocked: 'आपकी खास याद यहाँ है!',
  L10nKeys.mysteryUnlockedBody: 'यह याद केवल आपके लिए है। अपना समय लें। 🌸',
  L10nKeys.mysteryCuriosity: 'आज क्या खुलेगा?',
  L10nKeys.mysteryOpen: 'याद खोलें',

  L10nKeys.memoriesTitle: 'मेरी यादें',
  L10nKeys.memoriesEmpty: 'अभी कोई याद नहीं',
  L10nKeys.memoriesEmptyBody:
      'आपका परिवार तस्वीरें और आवाज़ें जोड़ सकता है। तब वे यहाँ दिखेंगी।',
  L10nKeys.memoriesFamily: 'परिवार',
  L10nKeys.memoriesPlaces: 'स्थान',
  L10nKeys.memoriesFestivals: 'त्योहार',
  L10nKeys.memoriesChildhood: 'बचपन',
  L10nKeys.memoriesKindPhoto: 'तस्वीर',
  L10nKeys.memoriesKindVoice: 'आवाज़ संदेश',
  L10nKeys.memoriesKindText: 'कहानी',
  L10nKeys.memoriesKindSound: 'आवाज़',
  L10nKeys.memoriesKindPlace: 'स्थान',
  L10nKeys.memoriesAddedBy: 'जोड़ा',
  L10nKeys.memoriesWhoIsThis: 'यह कौन हैं?',
  L10nKeys.memoriesPlayVoice: 'सुनें',
  L10nKeys.memoriesThisIsMe: 'यह मैं हूँ',
  L10nKeys.memoriesNotMe: 'मैं नहीं',

  L10nKeys.profileTitle: 'प्रोफ़ाइल',
  L10nKeys.profileLanguage: 'ऐप की भाषा',
  L10nKeys.profileRegion: 'मेरा क्षेत्र',
  L10nKeys.profileVoiceLanguage: 'आवाज़ की भाषा',
  L10nKeys.profileVoicePrompts: 'आवाज़ संकेत',
  L10nKeys.profileTextSize: 'अक्षर का आकार',
  L10nKeys.profileReducedMotion: 'हल्की गति',
  L10nKeys.profileSoundEffects: 'ध्वनि प्रभाव',
  L10nKeys.profileFamily: 'परिवार',
  L10nKeys.profileContacts: 'आपातकालीन संपर्क',
  L10nKeys.profileDemoMode: 'डेमो मोड',
  L10nKeys.profileReminders: 'अनुस्मारक',
  L10nKeys.profileNeedHelp: 'मदद चाहिए?',

  L10nKeys.remindersTitle: 'अनुस्मारक',
  L10nKeys.remindersEmpty: 'अभी कोई अनुस्मारक नहीं',
  L10nKeys.remindersNew: 'नया अनुस्मारक',
  L10nKeys.remindersTitleLabel: 'शीर्षक',
  L10nKeys.remindersDetailLabel: 'विवरण (वैकल्पिक)',
  L10nKeys.remindersTime: 'समय',
  L10nKeys.remindersDays: 'दिन',
  L10nKeys.remindersEveryday: 'हर दिन',
  L10nKeys.remindersEnabled: 'चालू',
  L10nKeys.remindersMedicine: 'दवा',
  L10nKeys.remindersAppointment: 'अपॉइंटमेंट',
  L10nKeys.remindersRoutine: 'दैनिक दिनचर्या',

  L10nKeys.dayMon: 'सोम',
  L10nKeys.dayTue: 'मंगल',
  L10nKeys.dayWed: 'बुध',
  L10nKeys.dayThu: 'गुरु',
  L10nKeys.dayFri: 'शुक्र',
  L10nKeys.daySat: 'शनि',
  L10nKeys.daySun: 'रवि',

  L10nKeys.sosTitle: 'आपातकालीन मदद',
  L10nKeys.sosExplain: 'दबाकर रखें। माइंडकेयर आपके आपातकालीन संपर्कों को एक-एक कर सूचित करेगा। यह आपातकालीन सेवाओं (जैसे 112) की जगह नहीं है।',
  L10nKeys.sosHold: 'मदद के लिए दबाकर रखें',
  L10nKeys.sosHoldBody: 'दबाए रखें…',
  L10nKeys.sosActiveTitle: 'मदद से संपर्क हो रहा है',
  L10nKeys.sosActiveBody: 'आपके परिवार को बताया गया है। अगर वे जवाब नहीं देते, अगले संपर्क को सूचित किया जाएगा।',
  L10nKeys.sosContacting: 'संपर्क हो रहा है',
  L10nKeys.sosContactFamily: 'परिवार से संपर्क करें',
  L10nKeys.sosContacted: 'सूचित किया गया',
  L10nKeys.sosWaitingResponse: 'जवाब का इंतज़ार…',
  L10nKeys.sosEscalating: 'अगले व्यक्ति से संपर्क…',
  L10nKeys.sosCancelled: 'मदद का अनुरोध रद्द',
  L10nKeys.sosCancelAction: 'मदद अनुरोध रद्द करें',
  L10nKeys.sosDone: 'हो गया',
  L10nKeys.sosHelpOnWay: 'कोई मदद लेकर आ रहा है। 🧡',
  L10nKeys.sosNoContacts: 'अभी कोई आपातकालीन संपर्क नहीं',
  L10nKeys.sosNoContactsBody:
      'कृपया परिवार से आपातकालीन संपर्क जोड़ने को कहें।',
  L10nKeys.sosAddContact: 'संपर्क जोड़ें',
  L10nKeys.sosDisclaimer: 'माइंडकेयर आपके चुने हुए संपर्कों को सूचित करता है। यह आधिकारिक आपातकालीन सेवाओं का विकल्प नहीं है।',
  L10nKeys.sosContactedPerson: 'परिवार के सदस्य को सूचित किया गया',
  L10nKeys.sosEscalatedTo: 'अगले परिवार के सदस्य को सूचित किया गया',
  L10nKeys.sosAcknowledged: 'परिवार के सदस्य ने जवाब दिया है। मदद आ रही है।',
  L10nKeys.sosNotSilent:
      'हम कभी यह नहीं कहेंगे कि मदद भेजी गई जब वह नहीं भेजी जा सकी।',
  L10nKeys.sosAlertNotDelivered:
      'आपका संदेश अभी नहीं भेजा जा सका। हम प्रयास करते रहेंगे।',

  L10nKeys.careTitle: 'देखभालकर्ता',
  L10nKeys.careDashboard: 'सारांश',
  L10nKeys.carePatients: 'मेरे मरीज़',
  L10nKeys.careMemories: 'यादें',
  L10nKeys.careContacts: 'आपातकालीन संपर्क',
  L10nKeys.careSettings: 'सेटिंग्स',
  L10nKeys.careAddMemory: 'याद जोड़ें',
  L10nKeys.careAddContact: 'संपर्क जोड़ें',
  L10nKeys.careEngagement: 'भागीदारी',
  L10nKeys.careActivitiesWeek: 'इस सप्ताह की गतिविधियाँ',
  L10nKeys.careGardenProgress: 'बगीचे की प्रगति',
  L10nKeys.careRecentActivity: 'हाल की गतिविधि',
  L10nKeys.careNoPatients: 'कोई जुड़ा मरीज़ नहीं',
  L10nKeys.careNoPatientsBody:
      'परिवार के सदस्य से जुड़ने को कहें, या मरीज़ प्रोफ़ाइल जोड़ें।',
  L10nKeys.careAddPatient: 'मरीज़ जोड़ें',
  L10nKeys.carePerformanceNote:
      'हाल में गतिविधि प्रदर्शन इस व्यक्ति के सामान्य स्तर से थोड़ा कम है।',
  L10nKeys.careUploadPhoto: 'तस्वीर जोड़ें',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'आवाज़ रिकॉर्ड करें',
  L10nKeys.careWriteMemory: 'याद लिखें',
  L10nKeys.careMemoryTitle: 'शीर्षक',
  L10nKeys.careMemoryCaption: 'विवरण',
  L10nKeys.careMemoryRelation: 'इसमें कौन हैं? (रिश्ता)',
  L10nKeys.careMemoryCategory: 'श्रेणी',
  L10nKeys.careContactName: 'नाम',
  L10nKeys.careContactPhone: 'फ़ोन नंबर',
  L10nKeys.careContactPriority: 'कॉल क्रम',
  L10nKeys.careContactRelation: 'रिश्ता',
  L10nKeys.careEscalationTimeout: 'अगले संपर्क से पहले मिनट',
  L10nKeys.careIncidentStatus: 'स्थिति',
  L10nKeys.careAckSos: 'मैं जवाब दे रहा हूँ',
  L10nKeys.careResponding: 'जवाब दे रहे हैं',
  L10nKeys.careActiveAlerts: 'सक्रिय चेतावनी',

  L10nKeys.syncSavingOffline: 'ऑफ़लाइन',
  L10nKeys.syncSavingOfflineBody: 'आपकी गतिविधियाँ इसी डिवाइस पर सुरक्षित हैं।',
  L10nKeys.syncSynced: 'सिंक हुआ',
  L10nKeys.syncInfo: 'आपकी जानकारी सिंक हो गई है।',
  L10nKeys.syncPending: 'सिंक की प्रतीक्षा में',

  L10nKeys.errorGeneric: 'कुछ गड़बड़ हुई',
  L10nKeys.errorGenericBody:
      'आपकी प्रगति सुरक्षित है। कृपया फिर से कोशिश करें।',
  L10nKeys.errorAudio: 'इस डिवाइस पर आवाज़ नहीं चल पाई।',
  L10nKeys.errorPermission: 'इसके लिए डिवाइस की अनुमति चाहिए।',
  L10nKeys.errorNoInternetAction:
      'इंटरनेट की ज़रूरत नहीं — यह पहले यहीं सहेजा जाता है।',

  L10nKeys.demoWelcome: 'डेमो देखें',
  L10nKeys.demoExplain:
      'एक नमूना परिवार और यादें जोड़ी जाएँगी ताकि आप जान सकें।',
  L10nKeys.demoLoad: 'डेमो बगीचा शुरू करें',

  L10nKeys.unitsPoints: 'अंक',
  L10nKeys.teaserChai: 'चलिए चाय बनाते हैं।',
  L10nKeys.familiarityName: 'आशा',
  L10nKeys.regionMap: 'मेरा क्षेत्र',
  L10nKeys.regionChoose: 'अपना क्षेत्र चुनें',
  L10nKeys.regionIndia: 'भारत',
  L10nKeys.importantMemory: 'महत्वपूर्ण याद',
  L10nKeys.growing: 'बढ़ रहा',
  L10nKeys.blooming: 'खिल रहा',
  L10nKeys.mature: 'परिपक्व',
  L10nKeys.noVoice: 'इस डिवाइस पर आवाज़ उपलब्ध नहीं है।',
  L10nKeys.optional: 'वैकल्पिक',

  L10nKeys.authSignUpTitle: 'अपना खाता बनाएँ',
  L10nKeys.authSignUpBody: 'यह माइंडकेयर प्रोफ़ाइल आपके डिवाइस पर सुरक्षित रहेगी। उपयोगकर्ता नाम और पासवर्ड से केवल आप इसे खोल पाएँगे।',
  L10nKeys.authLoginTitle: 'वापसी पर स्वागत',
  L10nKeys.authLoginBody:
      'अपना बगीचा खोलने के लिए अपना उपयोगकर्ता नाम और पासवर्ड दर्ज करें।',
  L10nKeys.authUsername: 'उपयोगकर्ता नाम',
  L10nKeys.authUsernameHint: 'जैसे रानू123',
  L10nKeys.authDisplayName: 'आपका नाम',
  L10nKeys.authPassword: 'पासवर्ड',
  L10nKeys.authPasswordHint: 'कम से कम ६ अक्षर',
  L10nKeys.authConfirmPassword: 'पासवर्ड दोबारा',
  L10nKeys.authRoleQuestion: 'यह प्रोफ़ाइल किसके लिए है?',
  L10nKeys.authRolePatient: 'मेरे लिए',
  L10nKeys.authRoleCaregiver: 'परिवार के सदस्य के लिए',
  L10nKeys.authCreate: 'खाता बनाएँ',
  L10nKeys.authSignIn: 'साइन इन करें',
  L10nKeys.authSignOut: 'साइन आउट',
  L10nKeys.authAccount: 'खाता',
  L10nKeys.caregiverTitle: 'देखभालकर्ता',
  L10nKeys.caregiverNotLinked: 'अभी कोई देखभालकर्ता जुड़ा नहीं है',
  L10nKeys.authBadCredentials: 'उपयोगकर्ता नाम या पासवर्ड गलत है।',
  L10nKeys.authUsernameTaken:
      'यह उपयोगकर्ता नाम इस डिवाइस पर पहले से उपयोग में है।',
  L10nKeys.authPasswordMismatch: 'पासवर्ड मेल नहीं खाते।',
  L10nKeys.authUsernameShort: 'उपयोगकर्ता नाम कम से कम ३ अक्षर का होना चाहिए।',
  L10nKeys.authUsernameInvalid:
      'केवल अक्षर, संख्याएँ, बिंदु, डैश या अंडरस्कोर उपयोग करें।',
  L10nKeys.authPasswordShort: 'पासवर्ड कम से कम ६ अक्षर का होना चाहिए।',
  L10nKeys.authNameRequired: 'कृपया नाम दर्ज करें।',
  L10nKeys.authSignOutConfirm: 'क्या आप इस प्रोफ़ाइल से साइन आउट करेंगे?',

  L10nKeys.langChoose: 'भाषा चुनें',
  L10nKeys.langPrimary: 'मुख्य',
  L10nKeys.langNorthEast: 'पूर्वोत्तर भारत',
  L10nKeys.langMajor: 'भारत की प्रमुख भाषाएँ',
  L10nKeys.screenTitle: 'त्वरित स्मृति जाँच',
  L10nKeys.screenIntro: 'हम मरीज़ के बारे में कुछ छोटे सवाल पूछेंगे। सोचें कि पिछले कुछ महीनों में वे कैसे रहे हैं।',
  L10nKeys.screenNotSure: 'पता नहीं',
  L10nKeys.screenFinish: 'मेरा परिणाम देखें',
  L10nKeys.screenSkip: 'अभी छोड़ें',
  L10nKeys.screenResultBack: 'हो गया',
  L10nKeys.screenCheckAgain: 'फिर से जाँचें',
  L10nKeys.screenStartCheckup: 'जाँच शुरू करें',
  L10nKeys.screenSkipped: 'जाँच छोड़ दी गई',
  L10nKeys.screenStatusGood: 'सब कुछ ठीक लग रहा है',
  L10nKeys.screenStatusGoodBody: 'कोई बड़ी चिंता नहीं दिखी। रोज़ की गतिविधियाँ करते रहें, और कुछ बदले तो कभी भी फिर जाँच करें।',
  L10nKeys.screenStatusWatch: 'कुछ बदलाव नज़र आए',
  L10nKeys.screenStatusWatchBody: 'कुछ भूलने वाले पल दिखे। यह उम्र के साथ आम है, पर ध्यान रखें और अगली डॉक्टर यात्रा पर बताएँ।',
  L10nKeys.screenStatusDoctor: 'कृपया जाँच करवाएँ',
  L10nKeys.screenStatusDoctorBody: 'कुछ ऐसे संकेत दिखे जिन पर ध्यान देने की ज़रूरत हो सकती है। कृपया इन्हें डॉक्टर या क्लिनिक से साझा करें ताकि वे मदद कर सकें।',
  L10nKeys.screenRarely: 'कम ही',
  L10nKeys.screenSometimes: 'कभी-कभी',
  L10nKeys.screenFrequently: 'अक्सर',
  L10nKeys.screenVeryFrequently: 'बहुत बार',
  L10nKeys.screenQ01: 'क्या उन्हें हाल की घटनाएँ याद रखने में परेशानी होती है?',
  L10nKeys.screenQ02: 'क्या वे वही सवाल या कहानियाँ दोहराते हैं?',
  L10nKeys.screenQ03: 'क्या वे जाने-पहचाने लोगों के नाम भूल जाते हैं?',
  L10nKeys.screenQ04: 'क्या उन्हें परिचित चेहरे पहचानने में परेशानी होती है?',
  L10nKeys.screenQ05: 'क्या वे तारीखें या ज़रूरी काम भूल जाते हैं?',
  L10nKeys.screenQ06: 'क्या उन्हें सही शब्द मिलने में परेशानी होती है?',
  L10nKeys.screenQ07: 'क्या वे भ्रमित हो जाते हैं कि वे कहाँ हैं?',
  L10nKeys.screenQ08:
      'क्या उन्हें रोज़ की गतिविधियों के लिए याद दिलाने की ज़रूरत होती है?',
  L10nKeys.screenQ09: 'क्या उन्हें दवाइयाँ संभालने में परेशानी होती है?',
  L10nKeys.screenQ10: 'क्या वे भ्रमित होने पर घबराते या चिढ़ जाते हैं?',
  L10nKeys.screenQ11: 'क्या उन्हें बातचीत समझने में परेशानी होती है?',
  L10nKeys.screenQ12:
      'क्या उन्हें जाने-पहचाने काम पूरे करने में परेशानी होती है?',
  L10nKeys.screenQ13: 'क्या वे भूल जाते हैं कि रोज़ की चीज़ें कहाँ रखी हैं?',
  L10nKeys.screenQ14: 'क्या उन्हें निर्देश याद रखने में परेशानी होती है?',
  L10nKeys.screenQ15:
      'क्या उन्हें कई चरणों वाली गतिविधियाँ करने में परेशानी होती है?',

  L10nKeys.careDashboardSubtitle: 'परिवार की देखभाल',
  L10nKeys.careSosLive: 'लाइव सूचना',
  L10nKeys.careSosRespondedBy: '{name} ने उत्तर दिया',
  L10nKeys.careLinkTitle: 'परिवार के सदस्य से जोड़ें',
  L10nKeys.careLinkBody: 'अपने प्रियजन से उनके फ़ोन पर दिख रहे 6-अक्षर वाले पारिवारिक कोड के लिए पूछें, फिर जोड़ें।',
  L10nKeys.careLinkCode: 'पारिवारिक कोड',
  L10nKeys.careLinkCodeHint: 'जैसे A1B2C3',
  L10nKeys.careLinkConnect: 'जोड़ें',
  L10nKeys.careLinkDone: 'जुड़ गया',
  L10nKeys.careLinkSuccess:
      '{name} से जुड़ गए! यादें और सूचनाएं अब सिंक होंगी।',
  L10nKeys.careLinkFailed: 'जुड़ नहीं सके। कृपया कोड जांचें और फिर कोशिश करें।',
  L10nKeys.careTrendsTitle: 'AI रुझान',
  L10nKeys.careTrendsBody: 'गतिविधि प्रकार से दैनिक सटीकता',
  L10nKeys.careTrendsNoData:
      'अभी तक कोई गतिविधि नहीं — रुझान देखने के लिए एक अभ्यास पूरा करें।',
  L10nKeys.careAiDifficulty: 'स्वतः समायोजित कठिनाई',
  L10nKeys.careAiAccuracy: 'मॉडल की सटीकता',
  L10nKeys.careAiRealSessions: 'वास्तविक सत्र',
  L10nKeys.careAiDemoSessions: 'डेमो सत्र',
  L10nKeys.careNavGames: 'खेल',
  L10nKeys.careNavRoutine: 'दिनचर्या',
  L10nKeys.careGreetSubtitle: 'यहाँ देखें कि आज {name} कैसा कर रहा है।',
  L10nKeys.careNotifEmpty: 'कोई नई सूचना नहीं',
  L10nKeys.careWellnessScore: 'संज्ञानात्मक कल्याण स्कोर',
  L10nKeys.careStatusStable: 'स्थिर',
  L10nKeys.careStatusAttention: 'ध्यान आवश्यक',
  L10nKeys.careLastSynced: 'अंतिम बार सिंक {time}',
  L10nKeys.careMinAgo: '{n} मिनट पहले',
  L10nKeys.careGamesWeek: 'इस सप्ताह के खेल',
  L10nKeys.careRoutineCompletion: 'दिनचर्या पूर्णता',
  L10nKeys.careCurrentStreak: 'चालू स्ट्रीक',
  L10nKeys.careMoodCheckins: 'मूड चेक-इन',
  L10nKeys.careDayUnit: 'दिन',
  L10nKeys.careDaysUnit: 'दिन',
  L10nKeys.careActivityTitle: 'साप्ताहिक गतिविधि',
  L10nKeys.careWeekly: 'साप्ताहिक',
  L10nKeys.careMonthly: 'मासिक',
  L10nKeys.careNoActivityWeek: 'इस सप्ताह अभी तक कोई गतिविधि दर्ज नहीं हुई।',
  L10nKeys.careMoodTitle: 'मनोदशा',
  L10nKeys.careMoodHappy: 'खुश',
  L10nKeys.careMoodCalm: 'शांत',
  L10nKeys.careMoodNeutral: 'तटस्थ',
  L10nKeys.careMoodLow: 'कम',
  L10nKeys.careMood7Days: 'पिछले 7 दिन',
  L10nKeys.careMoodInsight: '{name} इस सप्ताह ज़्यादातर शांत रहे हैं, पिछले दो दिनों में हल्की गिरावट के साथ।',
  L10nKeys.careMoodNoData: 'इस सप्ताह अभी तक कोई मूड चेक-इन नहीं।',
  L10nKeys.careSkillsTitle: 'संज्ञानात्मक कौशल',
  L10nKeys.careSkillMemory: 'स्मृति',
  L10nKeys.careSkillAttention: 'ध्यान',
  L10nKeys.careSkillLanguage: 'भाषा',
  L10nKeys.careSkillReasoning: 'तर्क',
  L10nKeys.careSkillProcessing: 'प्रसंस्करण गति',
  L10nKeys.careInsightToday: 'आज की अंतर्दृष्टि',
  L10nKeys.careInsightBody: 'रॉबर्ट सुबह की दिनचर्या के बाद स्मृति गतिविधियों में लगातार सक्रिय रहे हैं। पिछले दो दिनों में उनकी मनोदशा थोड़ी कम रही है।',
  L10nKeys.careInsightBodyReal: 'इस सप्ताह {name} ने {count} संज्ञानात्मक सत्र पूरे किए (लक्ष्य {goal}) और {streak} दिन की स्ट्रीक जारी है।',
  L10nKeys.careViewDetails: 'विवरण देखें',
  L10nKeys.careInsightDisclaimer:
      'यह डेटा से एक सौम्य अवलोकन है — चिकित्सकीय निदान नहीं।',
  L10nKeys.careAttentionTitle: 'आपके ध्यान की आवश्यकता',
  L10nKeys.careAttentionEmpty: 'अभी आपके ध्यान के लिए कुछ भी नहीं है।',
  L10nKeys.careAlertSos: '{name} ने SOS बटन दबाया',
  L10nKeys.careAlertRoutineMissed: 'कल दिनचर्या छूट गई',
  L10nKeys.careAlertMoodDown: 'पिछले दो दिनों में मनोदशा कम हुई',
  L10nKeys.careAlertSessionPending: 'आज संज्ञानात्मक सत्र पूरा नहीं हुआ',
  L10nKeys.careAlertSeverityHigh: 'उच्च',
  L10nKeys.careAlertSeverityMedium: 'मध्यम',
  L10nKeys.careAlertSeverityLow: 'निम्न',
  L10nKeys.careWeeklySummary: 'साप्ताहिक सारांश',
  L10nKeys.careSessionsCompleted: 'पूर्ण किए गए सत्र',
  L10nKeys.careAvgSessionDuration: 'औसत सत्र अवधि',
  L10nKeys.careRoutineAdherence: 'दिनचर्या पालन',
  L10nKeys.careMoodTrend: 'मनोदशा प्रवृत्ति',
  L10nKeys.careMoodTrendSlightlyDown: 'थोड़ी कम',
  L10nKeys.careMoodTrendStable: 'स्थिर',
  L10nKeys.careMoodTrendUp: 'सुधार हो रहा है',
  L10nKeys.careVsLastWeek: 'पिछले सप्ताह की तुलना में',
  L10nKeys.careSyncedJustNow: 'अभी सिंक हुआ',
  L10nKeys.careOfflineWaiting:
      'ऑफ़लाइन · {count} गतिविधियाँ सिंक की प्रतीक्षा में',
  L10nKeys.careComingSoon: 'जल्द आ रहा है',
  L10nKeys.careHomeSoon: '{name} के दिन का संक्षिप्त अवलोकन यहाँ दिखाई देगा।',
  L10nKeys.careGamesSoon: 'खेल और सत्र इतिहास यहाँ दिखाई देंगे।',
  L10nKeys.careRoutineSoon: 'मरीज़ की दैनिक दिनचर्या यहाँ दिखाई देगी।',
  L10nKeys.careProfileSoon:
      'देखभालकर्ता प्रोफ़ाइल और सेटिंग्स यहाँ दिखाई देंगी।',
  L10nKeys.serverPairingTitle: 'पारिवारिक कोड',
  L10nKeys.serverPairingBody:
      'यह कोड किसी देखभालकर्ता के साथ साझा करें ताकि वे आपसे जुड़ सकें।',
  L10nKeys.serverUnlinked: 'सर्वर से जुड़ा नहीं',
  L10nKeys.serverLinked: 'सर्वर से जुड़ा',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
