import '../l10n_keys.dart';

/// Garo (A·chik) dictionary (best-effort machine-assisted translation; native review required).
/// Core food-market terms corroborated against xobdo.org, Glosbe and Wiktionary.
/// Untranslated keys automatically fall back to English.
const Map<String, String> stringsGrt = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'Nangni gopramni bewal',
  L10nKeys.back: 'Wangnika',
  L10nKeys.next: 'Ajana',
  L10nKeys.continueText: 'Ajakai re·ba',
  L10nKeys.skip: 'Re·angja',
  L10nKeys.done: 'Kusan',
  L10nKeys.cancel: 'Mulka',
  L10nKeys.yes: 'Ho',
  L10nKeys.no: 'Ja',
  L10nKeys.save: 'Rikita',
  L10nKeys.close: 'Kalja',
  L10nKeys.retry: 'Besoka susuba',
  L10nKeys.add: 'Danna',
  L10nKeys.edit: 'Pil·dapa',
  L10nKeys.remove: 'Dokata',
  L10nKeys.search: 'Napa',
  L10nKeys.today: 'Dinbi',
  L10nKeys.offline: 'Internet dongja',
  L10nKeys.online: 'Internet-on',

  L10nKeys.goodMorning: 'Salgipa karmik',
  L10nKeys.goodAfternoon: 'Salnam',
  L10nKeys.goodEvening: 'Namnikeng',
  L10nKeys.goodNight: 'Simsim nama',

  L10nKeys.navHome: 'Nok',
  L10nKeys.navGarden: 'Bagan',
  L10nKeys.navActivities: 'Sorkipsa',
  L10nKeys.navMemories: 'Gopramrang',
  L10nKeys.navProfile: 'Profile',
  L10nKeys.navMystery: 'Dinoni gopram',

  L10nKeys.onboardingWelcomeTitle: 'Nangni gopramni gualjapgipa watata',
  L10nKeys.onboardingWelcomeBody: 'Companio nangna dakchakaniko daka miksongani ni, sandigamako ra·china, sorkipchina aro matsamung sa·china — internet dongjakuja.',
  L10nKeys.onboardingNameTitle: 'Nangna mai ming ong·na nayu?',
  L10nKeys.onboardingNameHint: 'Nangni bimung',
  L10nKeys.onboardingRegionTitle: 'Nangni nok maia hawao donga?',
  L10nKeys.onboardingRegionHint: 'Nokdang ba nokgipa',
  L10nKeys.onboardingRegionList: 'Tura, Guwahati, Shillong, Williamnagar, Agartala, Imphal, Aizawl, Itanagar, Kohima, Gangtok, Dibrugarh, Jorhat',
  L10nKeys.onboardingLanguageTitle: 'Nangni ka·saanani ku?siko sea?',
  L10nKeys.onboardingLanguageBody: 'Na·a joton saron ong·pilangna man·a.',
  L10nKeys.onboardingFamilyTitle: 'Sawa nangni nokgipa?',
  L10nKeys.onboardingFamilyBody: 'Nangni ka·saani manderangko dapbo. Uamangni chibimungrangko aro kuriako nang·ni gopramna on·genchim.',
  L10nKeys.onboardingAddFamily: 'Nokgipa mande dapbo',
  L10nKeys.onboardingEmergencyTitle: 'On·pilessaa jolo sawa na·na dakchakgen?',
  L10nKeys.onboardingEmergencyBody: 'SOS button na·a don·oga, Companio nangni nokgipa manderangko aganpagen — bang·a jolani dakchakaniko agana.',
  L10nKeys.onboardingEmergencyName: 'Bimung',
  L10nKeys.onboardingEmergencyPhone: 'Phone number',
  L10nKeys.onboardingEmergencyRelation: 'Nangni mangmang (demsu, migipa…)',
  L10nKeys.onboardingDoneTitle: 'Nangni bagan sakkim!',
  L10nKeys.onboardingDoneBody: 'Bebia sorkiparangko kusanbo aro bagan neng·o chu·gimik an·chibonna nibo. An·ching nang·baksa donga.',
  L10nKeys.onboardingStart: 'Angni bagan pangchakbo',

  L10nKeys.homeWhatsGrowing: 'Mai dinon neng·a?',
  L10nKeys.homeTodayActivity: 'Dini sorkipsa',
  L10nKeys.homeActivityDuration: '3 minit',
  L10nKeys.homeMinutes: 'minit',
  L10nKeys.homeMemoryOfDay: 'Dini gopram',
  L10nKeys.homeMemoryLocked: 'Sa·gipa gopram jangkipa…',
  L10nKeys.homeMemoryUnlocked: 'Sa·gipa gopram oa!',
  L10nKeys.homeContinueActivity: 'Sorkipsako ajalbo',
  L10nKeys.homeFamilyMemory: 'Nangni nokoniko',
  L10nKeys.homeFamilyMemoryEmpty: 'Nokoniko gopramrang ian man·gen.',
  L10nKeys.homeSos: 'Dakchakaniko nangea',
  L10nKeys.homeSosSubtitle: 'On·pilessaa silgipa manderangko bi·do',
  L10nKeys.homeGardenPreview: 'Nangni bagan',
  L10nKeys.homeEngine: 'Companio watata',
  L10nKeys.homeEngineReady: 'Nangni dakchakgipa sakkim.',
  L10nKeys.homeWelcomeBack: 'Rajden bagan sorkipchina re·ba! 🌸',
  L10nKeys.homeNoActivity: 'Dino sorkipsa dongja',
  L10nKeys.homeNoActivityBody:
      'Kusanaba — ne nangni ka·saani sorkipsako basako. 🌻',

  L10nKeys.gardenTitle: 'Angni gopram bagan',
  L10nKeys.gardenSectionAll: 'Pilak',
  L10nKeys.gardenSectionFamily: 'Nok',
  L10nKeys.gardenSectionChildhood: 'Nikkokgipa somoi',
  L10nKeys.gardenSectionPlaces: 'Jagirang',
  L10nKeys.gardenSectionFestivals: 'Moraabasarang',
  L10nKeys.gardenEmpty: 'Nangni bagan pangchakjringjringenga',
  L10nKeys.gardenEmptyBody:
      'Skanggipa sorkipsako kusanbo, iaon bilirang sue nang·gen.',
  L10nKeys.gardenPoints: 'Bobilrang',
  L10nKeys.gardenLevel: 'Bilsigipa',
  L10nKeys.gardenSeed: 'Bilirang',
  L10nKeys.gardenPlant: 'Guserang',
  L10nKeys.gardenFlower: 'Olbirang',
  L10nKeys.gardenTree: 'Bol',
  L10nKeys.gardenMilestone: 'Rongkapa nok',
  L10nKeys.gardenGrowth: 'Neng·enga',
  L10nKeys.gardenDidYouKnow: 'Primal kusani sorkipsa, nangni bagan neng·ega.',
  L10nKeys.gardenPlantSeed: 'Bilirang sue',

  L10nKeys.activitiesTitle: 'Sorkipsarang',
  L10nKeys.activitiesToday: 'Dinbi',
  L10nKeys.activitiesLibrary: 'Gipin sorkipsarang',
  L10nKeys.mainGamesTitle: 'Ba·sani gam',
  L10nKeys.activitiesStart: 'Pangchakbo',
  L10nKeys.activitiesCompleted: 'Kusanaha',
  L10nKeys.activitiesInProgress: 'Nang·enga',
  L10nKeys.activitiesNotStarted: 'Sakkim',
  L10nKeys.activityYoureDone: 'Namtal!',
  L10nKeys.activityPraise: 'Na·a baganona janggi on·aha. 🌱',
  L10nKeys.activityHint: 'Dakchakaniko nangea?',
  L10nKeys.activityTryAgain: 'Gopramko skang jalsu',
  L10nKeys.activityOptionsHint: 'Nangni aganchakako basa',
  L10nKeys.activityTapToMatch: 'Wangso gita dake basa',
  L10nKeys.activityNext: 'Ajana',
  L10nKeys.activityFinish: 'Kusan',
  L10nKeys.activityGroupLetsAgain: 'Skang jalsu',
  L10nKeys.activityGroupTogether: 'Ian gimikna dakbo',
  L10nKeys.activityGreatJob: 'Nam gita dakaha!',
  L10nKeys.activityKitchen: 'Angni nokrang',
  L10nKeys.activityShopping: 'Angni bazar',
  L10nKeys.activityMatching: 'Wangso ona',
  L10nKeys.activitySequence: 'Jedosona dake sua',
  L10nKeys.activityRecognition: 'Ian maia?',
  L10nKeys.activityAssociation: 'Maia mangrake gnang?',
  L10nKeys.activityRecall: 'Na·a mikna ka.gipaia?',
  L10nKeys.activityAttention: 'Susa',
  L10nKeys.activityDurationSuffix: 'minit',
  L10nKeys.activityTodayDone: 'Dini sorkipsa kusanaha',
  L10nKeys.activityTodayDoneBody:
      'Nangni bagan neng·enga. Pitta gopram gimaaha. Rakgingenchi.',
  L10nKeys.activityGardenGrew: 'Nangni bagan neng·aha!',
  L10nKeys.activityMemoryUnlocked: 'Primal gopram oa',
  L10nKeys.activityReadAloud: 'Ugaio susapa',

  L10nKeys.kitchenTitle: 'Cha sakani kusanabo',
  L10nKeys.kitchenMakeChai: 'Cha sakani',
  L10nKeys.kitchenMakeChaiPrompt: 'Jedosona don.be.',
  L10nKeys.kitchenSteps: 'Sulkan',
  L10nKeys.kitchenTapInOrder: 'Sulkan jedosona basa',
  L10nKeys.kitchenCorrectOrder: 'Namtal! Cha sakimi!',
  L10nKeys.kitchenBreakfast: 'Biyon namgipa cha maha',
  L10nKeys.kitchenBreakfastHint: 'Dini namgipa biyong',
  L10nKeys.kitchenBreakfastPrompt: 'Biyonni sulkan jedosona sua.',

  L10nKeys.shopTitle: 'Angni bazar',
  L10nKeys.shopGetMilkBread: 'Dut aro roti',
  L10nKeys.shopGetMilkBreadPrompt: '₹100-on dut aro roti jekani.',
  L10nKeys.shopBudget: 'Bepari',
  L10nKeys.shopBasket: 'Nangni tokgipa',
  L10nKeys.shopTotal: 'Pilak',
  L10nKeys.shopWithinBudget: 'Bepari-o!',
  L10nKeys.shopOverBudget: 'Bepari sakna — pil·e nibo',
  L10nKeys.shopCheckout: 'Roboba kusanbo',
  L10nKeys.shopBuy: 'Tokgipo-o don',
  L10nKeys.shopSell: 'Jok',
  L10nKeys.shopVeggies: 'Wali cha·ani bi·sarang',
  L10nKeys.shopVeggiesPrompt: '₹60-on alu aro piyaz jekani.',
  L10nKeys.recKitchenItem: 'Ian maia?',
  L10nKeys.recKitchenItemPrompt: 'Bazardon jekani ja·dik?',
  L10nKeys.recCurrency: 'Paisa namgipa',
  L10nKeys.recCurrencyPrompt: 'Maia note ₹20?',
  L10nKeys.matchFestival: 'Moraabasar jekbo',
  L10nKeys.matchFestivalPrompt:
      'Primal moraabasarko uamangna ka·saani na·a cha·ani mangrake jekbo.',
  L10nKeys.matchObjectUse: 'Jekbo',
  L10nKeys.matchObjectUsePrompt: 'Primal jinmao uana sorok gita jekbo.',
  L10nKeys.seqMorning: 'Pitbokchongni janggi gimikan',
  L10nKeys.seqMorningPrompt:
      'Nangni pitbokchongni janggi gimikan jedosona sua.',
  L10nKeys.seqRoute: 'Pitbokchongni jilga',
  L10nKeys.seqRoutePrompt: 'Bazardon jilgaokon jedosona sua.',
  L10nKeys.assoRegion: 'Ian maia?',
  L10nKeys.assoRegionPrompt: 'Assam maia gisepo ia manga?',
  L10nKeys.assoHarvest: 'Maikha songgipa',
  L10nKeys.assoHarvestPrompt: 'Maia mikni songgipa raja?',
  L10nKeys.attnVeg: 'Garot susa',
  L10nKeys.attnVegPrompt: 'Na·a garot donga?',
  L10nKeys.recallSong: 'Mi:pangi ginggap',
  L10nKeys.recallSongPrompt: 'Bihu-o neng·en, maia ginggap?',
  L10nKeys.activityPairs: 'Do·para nika',
  L10nKeys.activitySequenceRecall: 'Rukgruako gipachee',
  L10nKeys.activityFindChanged: 'Maia kendenchim?',
  L10nKeys.pairsFruits: 'Bazar-ni bi·sap',
  L10nKeys.pairsKitchen: 'Nok-gitna-ni gisim',
  L10nKeys.pairsRemember: 'Kardrangko mol·mole nibo, a·pango bia gipako nika.',
  L10nKeys.pairsStart: 'Kardrangko apataha aro a·ba',
  L10nKeys.pairsFound: 'Para ma·aha!',
  L10nKeys.seqRecallItems: 'Sana-kena gisim',
  L10nKeys.seqRecallNumbers: 'Rukgruako anchi',
  L10nKeys.seqRecallWatch:
      'Kardrangko mol·mole nibo – sakgipini baksa apatriman dikdik rongtala.',
  L10nKeys.seqRecallRepeat: 'Da·o nikgimin rukgruako kardrangko na·ara.',
  L10nKeys.changeMarket: 'Bi·sapni kalga',
  L10nKeys.changeFestival: 'Kut-na tengaha dangrangkoba',
  L10nKeys.changeRemember: 'Iarangko mol·mole gipachee bo.',
  L10nKeys.changeFind:
      'Mingen gipakkasan ong·chengaha. Gipargipa ong·chenggipako nika.',
  L10nKeys.changeCorrect: 'Tengse! Ua gipakkasan ong·chengaha.',

  L10nKeys.mysteryTitle: 'Dini sa·gipa gopram',
  L10nKeys.mysteryLocked: 'Sa·gipa gopram na·a jangkipa…',
  L10nKeys.mysteryLockedBody:
      'Dino 2–3 sorkipsa kusanbo; ong·e nibo, ian oa kusi. Maia?',
  L10nKeys.mysteryUnlocked: 'Nangni sa·gipa gopram ian!',
  L10nKeys.mysteryUnlockedBody: 'Ian nangni gopram jangko. Somoi on·bo. 🌸',
  L10nKeys.mysteryCuriosity: 'Dino maia ogipa?',
  L10nKeys.mysteryOpen: 'Gopram okapbo',

  L10nKeys.memoriesTitle: 'Angni gopramrang',
  L10nKeys.memoriesEmpty: 'Ia somoi gopram dongja',
  L10nKeys.memoriesEmptyBody: 'Nangni nokgipa mande chibimung aro kuriako don.na man·engea. Iarang ian man·gen.',
  L10nKeys.memoriesFamily: 'Nok',
  L10nKeys.memoriesPlaces: 'Jagirang',
  L10nKeys.memoriesFestivals: 'Moraabasar',
  L10nKeys.memoriesChildhood: 'Nikkokgipa somoi',
  L10nKeys.memoriesKindPhoto: 'Chibimung',
  L10nKeys.memoriesKindVoice: 'Kuria',
  L10nKeys.memoriesKindText: 'Sukani',
  L10nKeys.memoriesKindSound: 'Awata',
  L10nKeys.memoriesKindPlace: 'Jagio',
  L10nKeys.memoriesAddedBy: 'Dapgipa',
  L10nKeys.memoriesWhoIsThis: 'Ia sawa?',
  L10nKeys.memoriesPlayVoice: 'Susa',
  L10nKeys.memoriesThisIsMe: 'Ian ang',
  L10nKeys.memoriesNotMe: 'Ian angja',

  L10nKeys.profileTitle: 'Profile',
  L10nKeys.profileLanguage: 'App ku?sik',
  L10nKeys.profileRegion: 'Angni hawa',
  L10nKeys.profileVoiceLanguage: 'Kuri ku?sik',
  L10nKeys.profileVoicePrompts: 'Kuri ni dakaha',
  L10nKeys.profileTextSize: 'Akser na·a',
  L10nKeys.profileReducedMotion: 'Rongo gita anning',
  L10nKeys.profileSoundEffects: 'Awatani',
  L10nKeys.profileFamily: 'Nok',
  L10nKeys.profileContacts: 'Jikmangan number',
  L10nKeys.profileDemoMode: 'Demo mode',
  L10nKeys.profileReminders: 'Jangkipa',
  L10nKeys.profileNeedHelp: 'Dakchakaniko nangea?',

  L10nKeys.remindersTitle: 'Jangkiparang',
  L10nKeys.remindersEmpty: 'Ia somoi jangkipa dongja',
  L10nKeys.remindersNew: 'Gital jangkipa',
  L10nKeys.remindersTitleLabel: 'Mikrok',
  L10nKeys.remindersDetailLabel: 'Gipin (namja)',
  L10nKeys.remindersTime: 'Somoi',
  L10nKeys.remindersDays: 'Salrang',
  L10nKeys.remindersEveryday: 'Primal salo',
  L10nKeys.remindersEnabled: 'Ona',
  L10nKeys.remindersMedicine: 'Dokoba',
  L10nKeys.remindersAppointment: 'Dokoror gram',
  L10nKeys.remindersRoutine: 'Janggi gimikan',

  L10nKeys.dayMon: 'Kettagon',
  L10nKeys.dayTue: 'Rongsinna',
  L10nKeys.dayWed: 'Rokal',
  L10nKeys.dayThu: 'Srichina',
  L10nKeys.dayFri: 'Doroka',
  L10nKeys.daySat: 'Samma',
  L10nKeys.daySun: 'Sandakoni',

  L10nKeys.sosTitle: 'Jikmangan dakchaka',
  L10nKeys.sosExplain: 'Doksangare ra·bo. Companio nangni jikmangan numberrangko aganpagen, arot arot. Ian jikmangan service (kum 112) ong·ja.',
  L10nKeys.sosHold: 'Dakchakanina doksangaro don',
  L10nKeys.sosHoldBody: 'Button-ko don…',
  L10nKeys.sosActiveTitle: 'Dakchakgipana aganenga',
  L10nKeys.sosActiveBody: 'Nangni nokgipa manderangna aganaha. Uamang jaju ong·jaode, gipin mande-na aganpagen.',
  L10nKeys.sosContacting: 'Aganenga',
  L10nKeys.sosContactFamily: 'Nokgipa manderang aganbo',
  L10nKeys.sosContacted: 'Aganaha',
  L10nKeys.sosWaitingResponse: 'Jaju jangkipa…',
  L10nKeys.sosEscalating: 'Gipin mande-na aganenga…',
  L10nKeys.sosCancelled: 'Dakchaka mulkaha',
  L10nKeys.sosCancelAction: 'Dakchakani mulkabo',
  L10nKeys.sosDone: 'Kusan',
  L10nKeys.sosHelpOnWay: 'Na·a gitse mande ba·jringre. 🧡',
  L10nKeys.sosNoContacts: 'Jikmangan number dongja',
  L10nKeys.sosNoContactsBody:
      'Nokgipa manderangna aganbo, jikmangan number don·ok.',
  L10nKeys.sosAddContact: 'Number dapbo',
  L10nKeys.sosDisclaimer: 'Companio nangni basegiparang na aganpagen. Ian biapni jikmangan service-ko gapja.',
  L10nKeys.sosContactedPerson: 'Nokgipa manderangna aganaha',
  L10nKeys.sosEscalatedTo: 'Gipin nokgipa mande-na aganaha',
  L10nKeys.sosAcknowledged: 'Nokgipa mandeni jaju ong·aha. Dakchaka ba·enga.',
  L10nKeys.sosNotSilent:
      'Uamangna jaju dyna man·janaode an·ching aganna ong·ja.',
  L10nKeys.sosAlertNotDelivered:
      'Nangni kuri din ka·japaha; an·ching susuana man·ja. An·ching besokgen.',

  L10nKeys.careTitle: 'Dakchakgipa',
  L10nKeys.careDashboard: 'Nibo',
  L10nKeys.carePatients: 'Angni gama manderang',
  L10nKeys.careMemories: 'Gopramrang',
  L10nKeys.careContacts: 'Jikmangan number',
  L10nKeys.careSettings: 'Rongtala',
  L10nKeys.careAddMemory: 'Gopram dapbo',
  L10nKeys.careAddContact: 'Number dapbo',
  L10nKeys.careEngagement: 'Kusani',
  L10nKeys.careActivitiesWeek: 'Ia anningni sorkipsarang',
  L10nKeys.careGardenProgress: 'Bagan bewal',
  L10nKeys.careRecentActivity: 'Gopram sorkipsarang',
  L10nKeys.careNoPatients: 'Gama mande dongja',
  L10nKeys.careNoPatientsBody:
      'Nokgipa mandena aganbo bianiko danna, ba gama mandeni profile dapbo.',
  L10nKeys.careAddPatient: 'Gama mande dapbo',
  L10nKeys.carePerformanceNote:
      'Isol mandeni bewal skang jimanio chu·gimik ong·ja; ua somoioni nenhaha.',
  L10nKeys.careUploadPhoto: 'Chibimungko tarina',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'Kuria record kuna',
  L10nKeys.careWriteMemory: 'Gopram sebo',
  L10nKeys.careMemoryTitle: 'Mikrok',
  L10nKeys.careMemoryCaption: 'Caption',
  L10nKeys.careMemoryRelation: 'Sawa ia-o donga? (mangmang)',
  L10nKeys.careMemoryCategory: 'Kanggol',
  L10nKeys.careContactName: 'Bimung',
  L10nKeys.careContactPhone: 'Phone number',
  L10nKeys.careContactPriority: 'Aganani jolo',
  L10nKeys.careContactRelation: 'Mangmang',
  L10nKeys.careEscalationTimeout: 'Gipin-na agananio jolo miniton',
  L10nKeys.careIncidentStatus: 'Pangchaksoa',
  L10nKeys.careAckSos: 'Ang jaju on·enga',
  L10nKeys.careResponding: 'Kusi on·enga',
  L10nKeys.careActiveAlerts: 'Uanenea jikmanganrang',

  L10nKeys.syncSavingOffline: 'Internet jakgija',
  L10nKeys.syncSavingOfflineBody:
      'Nangni sorkipsarang ian device-o rikita. Ha.',
  L10nKeys.syncSynced: 'Rikitaaha',
  L10nKeys.syncInfo: 'Nangni gopramrang rikitaaha.',
  L10nKeys.syncPending: 'Rikitanina jangkipenga',

  L10nKeys.errorGeneric: 'Gual aoni ong·aha',
  L10nKeys.errorGenericBody: 'Nangni bewalna darangma jegijako. Susubobo, jej.',
  L10nKeys.errorAudio: 'Ian device-o awata man·ja.',
  L10nKeys.errorPermission: 'Ia jakoba device-ni jakhara nanga.',
  L10nKeys.errorNoInternetAction: 'Internet nanga — ian NER-ni bewalko rikita.',

  L10nKeys.demoWelcome: 'Demo nibo',
  L10nKeys.demoExplain: 'Na·a nina gita sa·gipa nok aro gopramrangko dapgen.',
  L10nKeys.demoLoad: 'Demo bagan ra·bo',

  L10nKeys.unitsPoints: 'Bobilrang',
  L10nKeys.teaserChai: 'Cha sakani dakgen.',
  L10nKeys.familiarityName: 'Apo Mela',
  L10nKeys.regionMap: 'Angni hawa',
  L10nKeys.regionChoose: 'Nangni hawa basabo',
  L10nKeys.regionIndia: 'India',
  L10nKeys.importantMemory: 'Onrang gopram',
  L10nKeys.growing: 'Neng·enga',
  L10nKeys.blooming: 'Bi·oga',
  L10nKeys.mature: 'Chu·gimik bol',
  L10nKeys.noVoice: 'Ian device-o kuri dongja.',
  L10nKeys.optional: 'Namja inggipa',

  L10nKeys.langChoose: 'Ku?sik basabo',
  L10nKeys.langPrimary: 'Aro',
  L10nKeys.langNorthEast: 'NE India',
  L10nKeys.langMajor: 'India-ni nokdang ku?sikrang',

  L10nKeys.authSignUpTitle: 'Nangni account sakkimbo',
  L10nKeys.authSignUpBody: 'Ia Companio profile nangni device-o rikita ong·a. Na·a jan rongtale nina bimung aro password on·bo.',
  L10nKeys.authLoginTitle: 'Rajden wan·a',
  L10nKeys.authLoginBody:
      'Nangni baganona agana bimung aro password-on sign in ka·bo.',
  L10nKeys.authUsername: 'Bimung',
  L10nKeys.authUsernameHint: 'Kum: ranu123',
  L10nKeys.authDisplayName: 'Nangni bimung',
  L10nKeys.authPassword: 'Password',
  L10nKeys.authPasswordHint: '6 akser bako',
  L10nKeys.authConfirmPassword: 'Password-ko pil·e on·bo',
  L10nKeys.authRoleQuestion: 'Ia profile sawani dakna?…',
  L10nKeys.authRolePatient: 'Angni',
  L10nKeys.authRoleCaregiver: 'Nokgipa mandeni',
  L10nKeys.authCreate: 'Account sakkimbo',
  L10nKeys.authSignIn: 'Sign in',
  L10nKeys.authSignOut: 'Sign out',
  L10nKeys.authAccount: 'Account',
  L10nKeys.caregiverTitle: 'Caregiver',
  L10nKeys.caregiverNotLinked: 'No caregiver linked yet',
  L10nKeys.authBadCredentials: 'Bimung ba password jija.',
  L10nKeys.authUsernameTaken: 'Ia bimung ian device-o skango seng·aha.',
  L10nKeys.authPasswordMismatch: 'Passwordrang ja mangse.',
  L10nKeys.authUsernameShort: 'Bimung mi·sa 3 akser ong·joska.',
  L10nKeys.authUsernameInvalid:
      'Jena akser, number, dot, dash ba underscore ong·bo.',
  L10nKeys.authPasswordShort: 'Password mi·sa 6 akser ong·joska.',
  L10nKeys.authNameRequired: 'Bimungko on·bo.',
  L10nKeys.authSignOutConfirm: 'Na·a ia profile-niko sign out ka·nengeama?',
  L10nKeys.screenTitle: 'Mikangni nangrimani chanchia',
  L10nKeys.screenIntro: 'Anga bimarina katchiniko singgen. Skang palni rokomni janggi-tanganiko chanchia.',
  L10nKeys.screenNotSure: 'Uia',
  L10nKeys.screenFinish: 'Angni chanchianiko niko',
  L10nKeys.screenSkip: 'Dao bari',
  L10nKeys.screenResultBack: 'Skae',
  L10nKeys.screenCheckAgain: 'Ausin chanchia',
  L10nKeys.screenStartCheckup: 'Chanchia abacheng',
  L10nKeys.screenSkipped: 'Chanchia silgija ong aha',
  L10nKeys.screenStatusGood: 'Mai gnangchi ong aha',
  L10nKeys.screenStatusGoodBody: 'Dal a gisik-nanganiko nikja. Dami damiko kam ka rorogen, aro kanai nanggen ong aha baksa ausin chanchia.',
  L10nKeys.screenStatusWatch: 'Baning nikbaren nangaha',
  L10nKeys.screenStatusWatchBody: 'Wiruani baing nikbaren nangaha. Ia somayni gini ong aha, indake nikbo aro dr. jakalona aganbo.',
  L10nKeys.screenStatusDoctor: 'Bima saani gita chanchia',
  L10nKeys.screenStatusDoctorBody: 'Jensam chanchia nanggipa chanaiko nikaha. Ia chanchianiko dakko mande baksa janapbo, uamang nengniko dakna man aha.',
  L10nKeys.screenRarely: 'Babri',
  L10nKeys.screenSometimes: 'Baning baning',
  L10nKeys.screenFrequently: 'Sabega',
  L10nKeys.screenVeryFrequently: 'Sabega je jek-sa',
  L10nKeys.screenQ01: 'Ua nikmaniko gisiku ra ani dol nanga ma?',
  L10nKeys.screenQ02: 'Ua soji katchina minggipa damngango aganpraa ma?',
  L10nKeys.screenQ03: 'Ua manderangni nameko warijahama?',
  L10nKeys.screenQ04: 'Ua manderangni mikokko ma sina dol nanga ma?',
  L10nKeys.screenQ05: 'Ua daknapaniko warijahama?',
  L10nKeys.screenQ06: 'Ua katta nambatsranggipako ma si ong aha ma?',
  L10nKeys.screenQ07: 'Ua an tang ong aha pakko gipatako dakaha ma?',
  L10nKeys.screenQ08: 'Ua damiko kamkuni gimin geste nanggen ma?',
  L10nKeys.screenQ09: 'Ua intako ra ani dol nanga ma?',
  L10nKeys.screenQ10: 'Ua gipatako dakanio ka saani ong aha ma?',
  L10nKeys.screenQ11: 'Ua manderangni kattariko ma sina dol nanga ma?',
  L10nKeys.screenQ12: 'Ua masimana kamko sasona dol nanga ma?',
  L10nKeys.screenQ13: 'Ua rokom rokomo gimik ong aha pakko warijahama?',
  L10nKeys.screenQ14: 'Ua ge etaniko gisiku ra ani dol nanga ma?',
  L10nKeys.screenQ15: 'Ua bang pelko kamko dakani dol nanga ma?',

  L10nKeys.careDashboardSubtitle: 'Family care',
  L10nKeys.careSosLive: 'Live alert',
  L10nKeys.careSosRespondedBy: 'Responded by {name}',
  L10nKeys.careLinkTitle: 'Connect to a family member',
  L10nKeys.careLinkBody: 'Ask your loved one for the 6-letter family code shown on their phone, then connect.',
  L10nKeys.careLinkCode: 'Family code',
  L10nKeys.careLinkCodeHint: 'e.g. A1B2C3',
  L10nKeys.careLinkConnect: 'Connect',
  L10nKeys.careLinkDone: 'Connected',
  L10nKeys.careLinkSuccess:
      'Linked to {name}! Memories and alerts will now sync.',
  L10nKeys.careLinkFailed:
      'Could not connect. Please check the code and try again.',
  L10nKeys.careTrendsTitle: 'AI trends',
  L10nKeys.careTrendsBody: 'Daily accuracy by activity type',
  L10nKeys.careTrendsNoData:
      'No activity yet — complete an exercise to see trends.',
  L10nKeys.careAiDifficulty: 'Auto-tuned difficulty',
  L10nKeys.careAiAccuracy: 'Model accuracy',
  L10nKeys.careAiRealSessions: 'Real sessions',
  L10nKeys.careAiDemoSessions: 'Demo sessions',
  L10nKeys.careNavGames: 'Gamrang',
  L10nKeys.careNavRoutine: 'Rutin',
  L10nKeys.careGreetSubtitle: 'Ia bakko {name} da·alo maikai ong·enga mesoka.',
  L10nKeys.careNotifEmpty: 'Olakkigipa nokkol bang·baja.',
  L10nKeys.careWellnessScore: 'Nok·kani nangchongmotani score',
  L10nKeys.careStatusStable: 'Seng·gipa',
  L10nKeys.careStatusAttention: 'Nanga sagrika',
  L10nKeys.careLastSynced: '{time} o syncreaha',
  L10nKeys.careMinAgo: '{n} min a·siatang',
  L10nKeys.careGamesWeek: 'Ia haptako gamrang',
  L10nKeys.careRoutineCompletion: 'Rutin ku·sika',
  L10nKeys.careCurrentStreak: 'Nai ong·enggipa sal',
  L10nKeys.careMoodCheckins: 'Monni check-in',
  L10nKeys.careDayUnit: 'sal',
  L10nKeys.careDaysUnit: 'salrang',
  L10nKeys.careActivityTitle: 'Haptani kamrang',
  L10nKeys.careWeekly: 'Haptaniko',
  L10nKeys.careMonthly: 'Ma·iniko',
  L10nKeys.careNoActivityWeek: 'Ia haptaoni kam nang·jaha indide.',
  L10nKeys.careMoodTitle: 'Monni so·gijae',
  L10nKeys.careMoodHappy: 'Ka·srakgipa',
  L10nKeys.careMoodCalm: 'Se·gipa',
  L10nKeys.careMoodNeutral: 'Seng·srokaha',
  L10nKeys.careMoodLow: 'So·gipa',
  L10nKeys.careMood7Days: 'Reangbebea 7 sal',
  L10nKeys.careMoodInsight: '{name} ia haptao batanggimin somoio se·e dongachim, ning·achim bilsi salrango so·e ong·aha.',
  L10nKeys.careMoodNoData: 'Ia haptao monni check-in nang·jaha indide.',
  L10nKeys.careSkillsTitle: 'Nok·kani biria',
  L10nKeys.careSkillMemory: 'Gisikrongani',
  L10nKeys.careSkillAttention: 'Sagrika',
  L10nKeys.careSkillLanguage: 'Ku·sik',
  L10nKeys.careSkillReasoning: 'Pandarangani',
  L10nKeys.careSkillProcessing: 'Ka·donggipa somoi',
  L10nKeys.careInsightToday: 'Da·alni u·ianirang',
  L10nKeys.careInsightBody: 'Robert mamungba begani ja·mano gisikrongani kamko nang·gro joljol ka·engachim. Reangbebea salrango ua so·e ong·engnokachim.',
  L10nKeys.careInsightBodyReal: 'Ia haptaon {name} {count} nok·kani session ku·sikaha ({goal} miksonggipa) aro {streak} sal jolgimini sal dongengaha.',
  L10nKeys.careViewDetails: 'Nubatna',
  L10nKeys.careInsightDisclaimer:
      'Ia u·ianirang dataoni sokbaenga — darubai dakitani ong·ja.',
  L10nKeys.careAttentionTitle: 'Nanga sagrika',
  L10nKeys.careAttentionEmpty: 'Da·o mamungba nanga sagrika dongja.',
  L10nKeys.careAlertSos: '{name} SOS knaramko tangaha',
  L10nKeys.careAlertRoutineMissed: 'Wachio rutin gimaaha',
  L10nKeys.careAlertMoodDown: 'Reangbebea salrango monni so·gijagipa ong·aha',
  L10nKeys.careAlertSessionPending: 'Da·alo nok·kani session ku·sikja',
  L10nKeys.careAlertSeverityHigh: 'Dal·gipa',
  L10nKeys.careAlertSeverityMedium: 'Gisango',
  L10nKeys.careAlertSeverityLow: 'Gagani',
  L10nKeys.careWeeklySummary: 'Haptani kattarang',
  L10nKeys.careSessionsCompleted: 'Ku·sikgipa sessionrang',
  L10nKeys.careAvgSessionDuration: 'Sessionni gisik dakchakani somoi',
  L10nKeys.careRoutineAdherence: 'Rutin ja·rikataniko',
  L10nKeys.careMoodTrend: 'Monni gisikrang',
  L10nKeys.careMoodTrendSlightlyDown: 'A·sitang so·soa',
  L10nKeys.careMoodTrendStable: 'Seng·gipa',
  L10nKeys.careMoodTrendUp: 'Patenga',
  L10nKeys.careVsLastWeek: 'Wachi haptabaksa meligipa',
  L10nKeys.careSyncedJustNow: 'Kuntik uon syncreaha',
  L10nKeys.careOfflineWaiting:
      'Internet dongja · {count} karrang syncna neng·engmande',
  L10nKeys.careComingSoon: 'Re·baengani kattarang',
  L10nKeys.careHomeSoon: '{name}ni da·alo maikai ong·enga, iaoni nubagen.',
  L10nKeys.careGamesSoon: 'Gamrang aro sessionrangni itihas iaoni nubagen.',
  L10nKeys.careRoutineSoon: 'Bil·a manderangni salgni rutin iaoni nubagen.',
  L10nKeys.careProfileSoon:
      'Sagrika manderangni profile aro settings iaoni nubagen.',
  L10nKeys.serverPairingTitle: 'Family code',
  L10nKeys.serverPairingBody:
      'Share this code with a caregiver so they can connect to you.',
  L10nKeys.serverUnlinked: 'Not connected to server',
  L10nKeys.serverLinked: 'Connected to server',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
