import '../l10n_keys.dart';

/// Tamil dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsTa = {
  L10nKeys.appName: 'Companio',
  // How to play (tutorials)
  L10nKeys.tutListen: 'Listen',
  L10nKeys.tutPairs1: 'Watch the pictures carefully. Soon they will be hidden.',
  L10nKeys.tutPairs2: 'Tap a card to turn it around.',
  L10nKeys.tutPairs3: 'Find two of the very same picture.',
  L10nKeys.tutSeq1: 'Watch the cards light up one by one.',
  L10nKeys.tutSeq2: 'Remember the order.',
  L10nKeys.tutSeq3: 'Tap the cards in the same order.',
  L10nKeys.tutRecall1: 'Read or listen to the question.',
  L10nKeys.tutRecall2: 'Tap the answer you remember.',
  L10nKeys.tutRecall3: 'Choose one answer to finish.',
  L10nKeys.tutMatch1: 'Look at the pictures on the left.',
  L10nKeys.tutMatch2: 'Tap the matching picture on the right.',
  L10nKeys.tutMatch3: 'Match every pair to finish.',
  L10nKeys.tutNoFail: 'Take your time. There is no failing.',
  L10nKeys.tagline: 'உங்கள் நினைவுகளின் துணை',
  L10nKeys.back: 'பின்செல்',
  L10nKeys.next: 'அடுத்து',
  L10nKeys.continueText: 'தொடரவும்',
  L10nKeys.skip: 'தவிர்க்கவும்',
  L10nKeys.done: 'முடிந்தது',
  L10nKeys.cancel: 'ரத்துசெய்',
  L10nKeys.yes: 'ஆம்',
  L10nKeys.no: 'இல்லை',
  L10nKeys.save: 'சேமி',
  L10nKeys.close: 'மூடு',
  L10nKeys.retry: 'மீண்டும் முயற்சி',
  L10nKeys.add: 'சேர்',
  L10nKeys.edit: 'திருத்து',
  L10nKeys.remove: 'அகற்று',
  L10nKeys.search: 'தேடு',
  L10nKeys.today: 'இன்று',
  L10nKeys.offline: 'ஆஃப்லைன்',
  L10nKeys.online: 'ஆன்லைன்',

  L10nKeys.goodMorning: 'காலை வணக்கம்',
  L10nKeys.goodAfternoon: 'நண்பகல் வணக்கம்',
  L10nKeys.goodEvening: 'மாலை வணக்கம்',
  L10nKeys.goodNight: 'இனிய இரவு',

  L10nKeys.navHome: 'முகப்பு',
  L10nKeys.navGarden: 'தோட்டம்',
  L10nKeys.navActivities: 'செயல்பாடுகள்',
  L10nKeys.navMemories: 'நினைவுகள்',
  L10nKeys.navProfile: 'சுயவிவரம்',
  L10nKeys.navMystery: 'இன்றைய நினைவு',

  L10nKeys.onboardingWelcomeTitle: 'உங்கள் நினைவுகளின் மென்மையான துணை',
  L10nKeys.onboardingWelcomeBody: 'மைண்ட்கேர் என்இஆர் இணையம் இல்லாமலும் நினைவில் வைக்கவும், விளையாடவும், குடும்பத்துடன் இணைந்திருக்கவும் உதவுகிறது.',
  L10nKeys.onboardingNameTitle: 'உங்களை எப்படி அழைக்கலாம்?',
  L10nKeys.onboardingNameHint: 'உங்கள் பெயர்',
  L10nKeys.onboardingRegionTitle: 'உங்கள் வீடு எங்கே?',
  L10nKeys.onboardingRegionHint: 'நகரம் அல்லது கிராமம்',
  L10nKeys.onboardingRegionList: 'குவஹாத்தி, சில்சார், ஷில்லாங், அகர்தலா, இம்பால், ஐஸ்வால், இட்டாநகர், கோஹிமா, கேங்டாக், டிப்ருகார், ஜோர்ஹாட், உங்கள் நகரம்',
  L10nKeys.onboardingLanguageTitle: 'எந்த மொழி உங்களுக்கு பிடிக்கும்?',
  L10nKeys.onboardingLanguageBody: 'இதை எப்போது வேண்டுமானாலும் மாற்றலாம்.',
  L10nKeys.onboardingFamilyTitle: 'குடும்பம் யார்?',
  L10nKeys.onboardingFamilyBody: 'உங்கள் அன்பானவர்களை இணைக்கவும். அவர்களின் புகைப்படங்களையும் குரலையும் மென்மையான நினைவுகளாகக் காட்டுவோம்.',
  L10nKeys.onboardingAddFamily: 'குடும்ப உறுப்பினரைச் சேர்க்கவும்',
  L10nKeys.onboardingEmergencyTitle: 'அவசரத்தில் யாரை அழைப்போம்?',
  L10nKeys.onboardingEmergencyBody: 'SOS பட்டனை அழுத்தினால் மைண்ட்கேர் உங்கள் குடும்பத்திற்குத் தெரிவிக்கும், அவசரச் சேவைகளுக்கு அல்ல.',
  L10nKeys.onboardingEmergencyName: 'பெயர்',
  L10nKeys.onboardingEmergencyPhone: 'தொலைபேசி எண்',
  L10nKeys.onboardingEmergencyRelation: 'உறவு (மகள், மகன்…)',
  L10nKeys.onboardingDoneTitle: 'உங்கள் தோட்டம் தயார்!',
  L10nKeys.onboardingDoneBody: 'சிறிய செயல்பாடுகளை முடியுங்கள், உங்கள் தோட்டம் வளர்வதைப் பாருங்கள். நாங்கள் உங்களுடன் இருக்கிறோம்.',
  L10nKeys.onboardingStart: 'என் தோட்டத்தைத் தொடங்கு',

  L10nKeys.homeWhatsGrowing: 'இன்று என்ன வளர்கிறது?',
  L10nKeys.homeTodayActivity: 'இன்றைய சிறிய செயல்பாடு',
  L10nKeys.homeActivityDuration: 'சுமார் 3 நிமிடங்கள்',
  L10nKeys.homeMinutes: 'நிமிடம்',
  L10nKeys.homeMemoryOfDay: 'இன்றைய நினைவு',
  L10nKeys.homeMemoryLocked: 'ஒரு சிறப்பு நினைவு காத்திருக்கிறது…',
  L10nKeys.homeMemoryUnlocked: 'ஒரு நினைவு திறந்தது!',
  L10nKeys.homeContinueActivity: 'செயல்பாட்டை தொடரவும்',
  L10nKeys.homeFamilyMemory: 'உங்கள் குடும்பத்திடமிருந்து',
  L10nKeys.homeFamilyMemoryEmpty: 'குடும்ப நினைவுகள் இங்கே தோன்றலாம்.',
  L10nKeys.homeSos: 'உதவி தேவை',
  L10nKeys.homeSosSubtitle: 'அவசரத்தில் குடும்பத்தைத் தொடர்பு கொள்ளுங்கள்',
  L10nKeys.homeGardenPreview: 'உங்கள் தோட்டம்',
  L10nKeys.homeEngine: 'மைண்ட்கேர் துணை',
  L10nKeys.homeEngineReady: 'உங்கள் உதவியாளர் தயார்.',
  L10nKeys.homeWelcomeBack: 'மீண்டும் வரவேற்கிறோம்! தோட்டத்தை தொடரலாம். 🌸',
  L10nKeys.homeNoActivity: 'இன்று செயல்பாடு இல்லை',
  L10nKeys.homeNoActivityBody:
      'ஓய்வு எடுங்கள் — அல்லது பிடித்த செயல்பாட்டை தேர்வு செய்யுங்கள். 🌻',

  L10nKeys.gardenTitle: 'என் நினைவுத் தோட்டம்',
  L10nKeys.gardenSectionAll: 'அனைத்தும்',
  L10nKeys.gardenSectionFamily: 'குடும்பம்',
  L10nKeys.gardenSectionChildhood: 'குழந்தை பருவம்',
  L10nKeys.gardenSectionPlaces: 'இடங்கள்',
  L10nKeys.gardenSectionFestivals: 'திருவிழாக்கள்',
  L10nKeys.gardenEmpty: 'உங்கள் தோட்டம் இப்போதுதான் தொடங்கியது',
  L10nKeys.gardenEmptyBody:
      'முதல் செயல்பாட்டை முடியுங்கள், இங்கே ஒரு விதை நடப்படும்.',
  L10nKeys.gardenPoints: 'புள்ளிகள்',
  L10nKeys.gardenLevel: 'நிலை',
  L10nKeys.gardenSeed: 'விதை',
  L10nKeys.gardenPlant: 'செடி',
  L10nKeys.gardenFlower: 'பூ',
  L10nKeys.gardenTree: 'மரம்',
  L10nKeys.gardenMilestone: 'கட்டம்',
  L10nKeys.gardenGrowth: 'வளர்கிறது',
  L10nKeys.gardenDidYouKnow:
      'ஒவ்வொரு முடிவடையும் செயல்பாடும் தோட்டத்தை வளர்க்கிறது.',
  L10nKeys.gardenPlantSeed: 'விதை நடவும்',

  L10nKeys.activitiesTitle: 'செயல்பாடுகள்',
  L10nKeys.activitiesToday: 'இன்று',
  L10nKeys.activitiesLibrary: 'மேலும் செயல்பாடுகள்',
  L10nKeys.mainGamesTitle: 'முக்கிய விளையாட்டுகள்',
  L10nKeys.activitiesStart: 'தொடங்கு',
  L10nKeys.activitiesCompleted: 'முடிந்தது',
  L10nKeys.activitiesInProgress: 'நடந்து வருகிறது',
  L10nKeys.activitiesNotStarted: 'தயார்',
  L10nKeys.activityYoureDone: 'அருமை!',
  L10nKeys.activityPraise: 'தோட்டத்திற்கு சிறிது உயிர் கொடுத்தீர்கள். 🌱',
  L10nKeys.activityHint: 'குறிப்பு வேண்டுமா?',
  L10nKeys.activityTryAgain: 'இந்த நினைவை மீண்டும் பார்ப்போம்',
  L10nKeys.activityOptionsHint: 'உங்கள் பதிலைத் தேர்வு செய்யுங்கள்',
  L10nKeys.activityTapToMatch: 'ஒன்றாக பொருந்தும் இணையை தேர்வு செய்யுங்கள்',
  L10nKeys.activityNext: 'அடுத்து',
  L10nKeys.activityFinish: 'முடி',
  L10nKeys.activityGroupLetsAgain: 'இதை மீண்டும் பார்ப்போம்',
  L10nKeys.activityGroupTogether: 'இதை ஒன்றாக செய்வோம்',
  L10nKeys.activityGreatJob: 'நன்றாக செய்தீர்கள்!',
  L10nKeys.activityKitchen: 'என் சமையலறை',
  L10nKeys.activityShopping: 'என் கடை',
  L10nKeys.activityMatching: 'இணை பொருத்து',
  L10nKeys.activitySequence: 'வரிசையில் வைக்கவும்',
  L10nKeys.activityRecognition: 'இது என்ன?',
  L10nKeys.activityAssociation: 'எது ஒன்றாக போகும்?',
  L10nKeys.activityRecall: 'நினைவிருக்கிறதா?',
  L10nKeys.activityAttention: 'தேடு',
  L10nKeys.activityDurationSuffix: 'நிமிடம்',
  L10nKeys.activityTodayDone: 'இன்றைய செயல்பாடு முடிந்தது',
  L10nKeys.activityTodayDoneBody:
      'உங்கள் தோட்டம் வளர்ந்தது. நாளை ஒரு நினைவு காத்திருக்கும்.',
  L10nKeys.activityGardenGrew: 'உங்கள் தோட்டம் வளர்ந்தது!',
  L10nKeys.activityMemoryUnlocked: 'ஒரு நினைவு திறந்தது',
  L10nKeys.activityReadAloud: 'சத்தமாக வாசிக்கவும்',

  L10nKeys.kitchenTitle: 'சாய் செய்வோம்',
  L10nKeys.kitchenMakeChai: 'சாய் தயாரித்தல்',
  L10nKeys.kitchenMakeChaiPrompt: 'படிகளை சரியான வரிசையில் தேர்வு செய்யுங்கள்.',
  L10nKeys.kitchenSteps: 'படிகள்',
  L10nKeys.kitchenTapInOrder: 'படிகளை சரியான வரிசையில் தேர்வு செய்யுங்கள்',
  L10nKeys.kitchenCorrectOrder: 'அருமை! சாய் தயார்!',
  L10nKeys.kitchenBreakfast: 'காலை உணவு தயாரித்தல்',
  L10nKeys.kitchenBreakfastHint: 'நாளின் புத்துணர்ச்சியான தொடக்கம்',
  L10nKeys.kitchenBreakfastPrompt: 'காலை உணவின் படிகளை வரிசையில் வைக்கவும்.',

  L10nKeys.shopTitle: 'என் கடை',
  L10nKeys.shopGetMilkBread: 'பட்டும் பால்',
  L10nKeys.shopGetMilkBreadPrompt: '₹100-லில் பால் மற்றும் ரொட்டி வாங்குங்கள்.',
  L10nKeys.shopBudget: 'பட்ஜெட்',
  L10nKeys.shopBasket: 'உங்கள் கூடை',
  L10nKeys.shopTotal: 'மொத்தம்',
  L10nKeys.shopWithinBudget: 'பட்ஜெட்டுக்குள்!',
  L10nKeys.shopOverBudget: 'பட்ஜெட் அதிகமாகி விட்டது — மீண்டும் பாருங்கள்',
  L10nKeys.shopCheckout: 'முடித்து பணம் செலுத்துங்கள்',
  L10nKeys.shopBuy: 'கூடையில் போடுங்கள்',
  L10nKeys.shopSell: 'அகற்று',
  L10nKeys.shopVeggies: 'இரவு உணவிற்கான காய்கறிகள்',
  L10nKeys.shopVeggiesPrompt:
      '₹60-லில் உருளைக்கிழங்கும் வெங்காயமும் வாங்குங்கள்.',
  L10nKeys.recKitchenItem: 'இது எது?',
  L10nKeys.recKitchenItemPrompt:
      'சந்தையிலிருந்து பொருள் வாங்க எதைப் பயன்படுத்துவோம்?',
  L10nKeys.recCurrency: 'கொஞ்சம் பணம்',
  L10nKeys.recCurrencyPrompt: 'எந்த நோட்டு ₹20?',
  L10nKeys.matchFestival: 'திருவிழாவை பொருத்துங்கள்',
  L10nKeys.matchFestivalPrompt:
      'ஒவ்வொரு திருவிழாவையும் அதன் சிறப்பு உணவுடன் பொருத்துங்கள்.',
  L10nKeys.matchObjectUse: 'இணை பொருத்துங்கள்',
  L10nKeys.matchObjectUsePrompt:
      'ஒவ்வொரு பொருளையும் பயன்படுத்தும் நேரத்துடன் பொருத்துங்கள்.',
  L10nKeys.seqMorning: 'காலை வழக்கம்',
  L10nKeys.seqMorningPrompt: 'உங்கள் காலை வழக்கத்தை வரிசையில் வைக்கவும்.',
  L10nKeys.seqRoute: 'காலை பயணம்',
  L10nKeys.seqRoutePrompt: 'சந்தைக்கான பயணத்தை வரிசையில் வைக்கவும்.',
  L10nKeys.assoRegion: 'இங்கே என்ன?',
  L10nKeys.assoRegionPrompt: 'அசாம் எதற்கு பிரபலம்?',
  L10nKeys.assoHarvest: 'இனிப்பு பழம்',
  L10nKeys.assoHarvestPrompt: 'எந்த பழத்தை கோடையின் அரசன் என்பார்கள்?',
  L10nKeys.attnVeg: 'கேரட்டை தேடுங்கள்',
  L10nKeys.attnVegPrompt: 'கேரட் கண்டுபிடிக்க முடியுமா?',
  L10nKeys.recallSong: 'ஒரு பழக்கப்பட்ட பாடல்',
  L10nKeys.recallSongPrompt: 'பிஹுவில் நடனமாடும்போது எந்தப் பாடல் ஒலிக்கிறது?',
  L10nKeys.activityPairs: 'இணையைக் கண்டுபிடியுங்கள்',
  L10nKeys.activitySequenceRecall: 'வரிசையை நினைவில் கொள்ளுங்கள்',
  L10nKeys.activityFindChanged: 'எது மாறியது?',
  L10nKeys.pairsFruits: 'கடையின் பழங்கள்',
  L10nKeys.pairsKitchen: 'சமையலறைப் பொருட்கள்',
  L10nKeys.pairsRemember: 'எல்லா அட்டைகளையும் கவனமாகப் பாருங்கள், பிறகு ஒரே இணையைக் கண்டுபிடியுங்கள்.',
  L10nKeys.pairsStart: 'அட்டைகளை மறைத்துத் தொடங்குங்கள்',
  L10nKeys.pairsFound: 'இணை கிடைத்தது!',
  L10nKeys.seqRecallItems: 'அன்றாடப் பொருட்கள்',
  L10nKeys.seqRecallNumbers: 'வரிசையில் எண்கள்',
  L10nKeys.seqRecallWatch:
      'அட்டைகளைக் கவனமாகப் பாருங்கள் – ஒவ்வொன்றும் வரிசையாகப் பிரகாசிக்கும்.',
  L10nKeys.seqRecallRepeat:
      'இப்போது நீங்கள் பார்த்த அதே வரிசையில் அட்டைகளைத் தட்டுங்கள்.',
  L10nKeys.changeMarket: 'பழக் கூடை',
  L10nKeys.changeFestival: 'பண்டிகை விளக்குகள்',
  L10nKeys.changeRemember: 'இந்தப் படங்களைக் கவனமாக நினைவில் கொள்ளுங்கள்.',
  L10nKeys.changeFind: 'ஒரு படம் மாறியது. வேறான படத்தைக் கண்டுபிடியுங்கள்.',
  L10nKeys.changeCorrect: 'சரி! அதுதான் மாறியது.',

  L10nKeys.mysteryTitle: 'இன்றைய சிறப்பு நினைவு',
  L10nKeys.mysteryLocked: 'ஒரு சிறப்பு நினைவு உங்களைக் காத்திருக்கிறது…',
  L10nKeys.mysteryLockedBody: 'இன்று 2–3 சிறிய செயல்பாடுகள் செய்யுங்கள்; ஒருவேளை அது திறக்கும். என்னவாக இருக்கும்?',
  L10nKeys.mysteryUnlocked: 'உங்கள் சிறப்பு நினைவு இங்கே!',
  L10nKeys.mysteryUnlockedBody:
      'இந்த நினைவு உங்களுக்கு மட்டுமே. உங்கள் நேரத்தை எடுங்கள். 🌸',
  L10nKeys.mysteryCuriosity: 'இன்று என்ன திறக்கும்?',
  L10nKeys.mysteryOpen: 'நினைவைத் திற',

  L10nKeys.memoriesTitle: 'என் நினைவுகள்',
  L10nKeys.memoriesEmpty: 'இன்னும் நினைவுகள் இல்லை',
  L10nKeys.memoriesEmptyBody: 'உங்கள் குடும்பம் புகைப்படங்களும் குரல் செய்திகளும் சேர்க்கலாம். கிடைத்ததும் இங்கே தோன்றும்.',
  L10nKeys.memoriesFamily: 'குடும்பம்',
  L10nKeys.memoriesPlaces: 'இடங்கள்',
  L10nKeys.memoriesFestivals: 'திருவிழாக்கள்',
  L10nKeys.memoriesChildhood: 'குழந்தை பருவம்',
  L10nKeys.memoriesKindPhoto: 'புகைப்படம்',
  L10nKeys.memoriesKindVoice: 'குரல் செய்தி',
  L10nKeys.memoriesKindText: 'கதை',
  L10nKeys.memoriesKindSound: 'ஒலி',
  L10nKeys.memoriesKindPlace: 'இடம்',
  L10nKeys.memoriesAddedBy: 'சேர்த்தவர்',
  L10nKeys.memoriesWhoIsThis: 'இவர்கள் யார்?',
  L10nKeys.memoriesPlayVoice: 'கேள்',
  L10nKeys.memoriesThisIsMe: 'இதுதான் நான்',
  L10nKeys.memoriesNotMe: 'நான் இல்லை',

  L10nKeys.profileTitle: 'சுயவிவரம்',
  L10nKeys.profileLanguage: 'ஆப்ஸ் மொழி',
  L10nKeys.profileRegion: 'என் பகுதி',
  L10nKeys.profileVoiceLanguage: 'குரல் மொழி',
  L10nKeys.profileVoicePrompts: 'ஒலிக்கும் குறிப்புகள்',
  L10nKeys.profileTextSize: 'எழுத்து அளவு',
  L10nKeys.profileReducedMotion: 'அமைதியான இயக்கம்',
  L10nKeys.profileSoundEffects: 'ஒலி விளைவுகள்',
  L10nKeys.profileFamily: 'குடும்பம்',
  L10nKeys.profileContacts: 'அவசர தொடர்புகள்',
  L10nKeys.profileDemoMode: 'டெமோ முறை',
  L10nKeys.profileReminders: 'நினைவூட்டிகள்',
  L10nKeys.profileNeedHelp: 'உதவி வேண்டுமா?',

  L10nKeys.remindersTitle: 'நினைவூட்டிகள்',
  L10nKeys.remindersEmpty: 'இன்னும் நினைவூட்டிகள் இல்லை',
  L10nKeys.remindersNew: 'புதிய நினைவூட்டி',
  L10nKeys.remindersTitleLabel: 'தலைப்பு',
  L10nKeys.remindersDetailLabel: 'விவரம் (விருப்பமானது)',
  L10nKeys.remindersTime: 'நேரம்',
  L10nKeys.remindersDays: 'நாட்கள்',
  L10nKeys.remindersEveryday: 'தினமும்',
  L10nKeys.remindersEnabled: 'இயக்கு',
  L10nKeys.remindersMedicine: 'மருந்து',
  L10nKeys.remindersAppointment: 'சந்திப்பு',
  L10nKeys.remindersRoutine: 'தினசரி வழக்கம்',

  L10nKeys.dayMon: 'திங்',
  L10nKeys.dayTue: 'செவ்',
  L10nKeys.dayWed: 'புத',
  L10nKeys.dayThu: 'வியா',
  L10nKeys.dayFri: 'வெள்',
  L10nKeys.daySat: 'சனி',
  L10nKeys.daySun: 'ஞாயி',

  L10nKeys.sosTitle: 'அவசர உதவி',
  L10nKeys.sosExplain: 'அழுத்திப் பிடிக்கவும். மைண்ட்கேர் உங்கள் அவசர தொடர்புகளுக்கு ஒவ்வொருவராகத் தெரிவிக்கும். இது அவசரச் சேவை (112 போன்றவை) அல்ல.',
  L10nKeys.sosHold: 'உதவிக்காக அழுத்திப் பிடிக்கவும்',
  L10nKeys.sosHoldBody: 'அழுத்திப் பிடிக்கவும்…',
  L10nKeys.sosActiveTitle: 'உதவியை தொடர்பு கொள்கிறோம்',
  L10nKeys.sosActiveBody: 'உங்கள் குடும்பத்திற்கு தெரிவிக்கப்பட்டது. பதில் இல்லை என்றால் அடுத்த தொடர்பை அழைக்கும்.',
  L10nKeys.sosContacting: 'தொடர்பு கொள்ளுகிறோம்',
  L10nKeys.sosContactFamily: 'குடும்பத்தை தொடர்பு கொள்ளுங்கள்',
  L10nKeys.sosContacted: 'தொடர்பு கொள்ளப்பட்டது',
  L10nKeys.sosWaitingResponse: 'பதில் காத்திருக்கிறது…',
  L10nKeys.sosEscalating: 'அடுத்த நபரை தொடர்பு கொள்கிறோம்…',
  L10nKeys.sosCancelled: 'உதவி கோரிக்கை ரத்து',
  L10nKeys.sosCancelAction: 'உதவி கோரிக்கையை ரத்து செய்யுங்கள்',
  L10nKeys.sosDone: 'முடிந்தது',
  L10nKeys.sosHelpOnWay: 'விரைவில் யாராவது உங்களுடன் இருப்பார்கள். 🧡',
  L10nKeys.sosNoContacts: 'இன்னும் அவசர தொடர்புகள் இல்லை',
  L10nKeys.sosNoContactsBody:
      'குடும்பத்திடம் அவசர தொடர்புகளை சேர்க்கச் சொல்லுங்கள்.',
  L10nKeys.sosAddContact: 'தொடர்பை சேர்க்கவும்',
  L10nKeys.sosDisclaimer: 'மைண்ட்கேர் நீங்கள் தேர்ந்தெடுத்த தொடர்புகளுக்கு அறிவிக்கிறது. இது அதிகாரப்பூர்வ அவசரச் சேவைகளுக்கு மாற்றாகாது.',
  L10nKeys.sosContactedPerson: 'குடும்ப உறுப்பினரை தொடர்பு கொண்டோம்',
  L10nKeys.sosEscalatedTo: 'அடுத்த குடும்ப உறுப்பினரை தொடர்பு கொண்டோம்',
  L10nKeys.sosAcknowledged:
      'குடும்ப உறுப்பினர் பதிலளித்துள்ளார். உதவி வருகிறது.',
  L10nKeys.sosNotSilent: 'உதவி அனுப்ப முடியவில்லை என்றால் நாங்கள் ஒருபோதும் பாசாங்கு செய்ய மாட்டோம்.',
  L10nKeys.sosAlertNotDelivered:
      'உங்கள் செய்தி இன்னும் அனுப்பப்படவில்லை. தொடர்ந்து முயற்சிப்போம்.',

  L10nKeys.careTitle: 'பராமரிப்பாளர்',
  L10nKeys.careDashboard: 'கண்ணோட்டம்',
  L10nKeys.carePatients: 'என் நோயாளிகள்',
  L10nKeys.careMemories: 'நினைவுகள்',
  L10nKeys.careContacts: 'அவசர தொடர்புகள்',
  L10nKeys.careSettings: 'அமைப்புகள்',
  L10nKeys.careAddMemory: 'நினைவை சேர்க்கவும்',
  L10nKeys.careAddContact: 'தொடர்பை சேர்க்கவும்',
  L10nKeys.careEngagement: 'ஈடுபாடு',
  L10nKeys.careActivitiesWeek: 'இந்த வார செயல்பாடுகள்',
  L10nKeys.careGardenProgress: 'தோட்ட முன்னேற்றம்',
  L10nKeys.careRecentActivity: 'சமீபத்திய செயல்பாடு',
  L10nKeys.careNoPatients: 'நோயாளிகள் யாரும் இணைக்கப்படவில்லை',
  L10nKeys.careNoPatientsBody: 'குடும்ப உறுப்பினரை இணைக்கச் சொல்லுங்கள், அல்லது நோயாளி சுயவிவரத்தை சேர்க்கவும்.',
  L10nKeys.careAddPatient: 'நோயாளியை சேர்க்கவும்',
  L10nKeys.carePerformanceNote: 'சமீபத்தில் இந்த நபரின் செயல்பாடு செயல்திறன் அவர்களின் வழக்கமான நிலைக்கு சற்று குறைவாக உள்ளது.',
  L10nKeys.careUploadPhoto: 'புகைப்படத்தை பதிவேற்றவும்',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'குரலை பதிவு செய்யவும்',
  L10nKeys.careWriteMemory: 'நினைவு எழுதவும்',
  L10nKeys.careMemoryTitle: 'தலைப்பு',
  L10nKeys.careMemoryCaption: 'தலைப்பு வரி',
  L10nKeys.careMemoryRelation: 'இதில் யார் இருக்கிறார்கள்? (உறவு)',
  L10nKeys.careMemoryCategory: 'பிரிவு',
  L10nKeys.careContactName: 'பெயர்',
  L10nKeys.careContactPhone: 'தொலைபேசி எண்',
  L10nKeys.careContactPriority: 'அழைப்பு வரிசை',
  L10nKeys.careContactRelation: 'உறவு',
  L10nKeys.careEscalationTimeout: 'அடுத்த தொடர்புக்கு முந்தைய நிமிடங்கள்',
  L10nKeys.careIncidentStatus: 'நிலை',
  L10nKeys.careAckSos: 'நான் பதிலளிக்கிறேன்',
  L10nKeys.careResponding: 'பதிலளிக்கிறது',
  L10nKeys.careActiveAlerts: 'செயலில் உள்ள எச்சரிக்கைகள்',

  L10nKeys.syncSavingOffline: 'ஆஃப்லைன்',
  L10nKeys.syncSavingOfflineBody:
      'உங்கள் செயல்பாடுகள் இந்த சாதனத்தில் பாதுகாப்பாக உள்ளன.',
  L10nKeys.syncSynced: 'ஒத்திசைந்தது',
  L10nKeys.syncInfo: 'உங்கள் தகவல் ஒத்திசைந்து விட்டது.',
  L10nKeys.syncPending: 'ஒத்திசைவு காத்திருக்கிறது',

  L10nKeys.errorGeneric: 'ஏதோ தவறு ஏற்பட்டது',
  L10nKeys.errorGenericBody:
      'உங்கள் முன்னேற்றம் பாதுகாப்பானது. மீண்டும் முயற்சிக்கவும்.',
  L10nKeys.errorAudio: 'இந்த சாதனத்தில் ஒலி இயக்க முடியவில்லை.',
  L10nKeys.errorPermission: 'இதற்கு சாதன அனுமதி தேவை.',
  L10nKeys.errorNoInternetAction:
      'இணையம் தேவையில்லை — இது முதலில் இங்கேயே சேமிக்கப்படுகிறது.',

  L10nKeys.demoWelcome: 'டெமோ பார்க்கவும்',
  L10nKeys.demoExplain:
      'நீங்கள் பார்க்க மாதிரி குடும்பமும் நினைவுகளும் சேர்க்கப்படும்.',
  L10nKeys.demoLoad: 'டெமோ தோட்டத்தை ஏற்றவும்',

  L10nKeys.unitsPoints: 'புள்ளிகள்',
  L10nKeys.teaserChai: 'சாய் செய்வோம்.',
  L10nKeys.familiarityName: 'ஆஷா',
  L10nKeys.regionMap: 'என் பகுதி',
  L10nKeys.regionChoose: 'உங்கள் பகுதியை தேர்வு செய்யுங்கள்',
  L10nKeys.regionIndia: 'இந்தியா',
  L10nKeys.importantMemory: 'முக்கியமான நினைவு',
  L10nKeys.growing: 'வளர்கிறது',
  L10nKeys.blooming: 'பூக்கிறது',
  L10nKeys.mature: 'முதிர்ந்தது',
  L10nKeys.noVoice: 'இந்த சாதனத்தில் குரல் கிடைக்கவில்லை.',
  L10nKeys.optional: 'விருப்பமானது',

  L10nKeys.langChoose: 'மொழியை தேர்வு செய்யுங்கள்',
  L10nKeys.langPrimary: 'முதன்மை',
  L10nKeys.langNorthEast: 'வடகிழக்கு இந்தியா',
  L10nKeys.langMajor: 'இந்தியாவின் முதன்மை மொழிகள்',

  L10nKeys.authSignUpTitle: 'உங்கள் கணக்கை உருவாக்குங்கள்',
  L10nKeys.authSignUpBody: 'இந்த மைண்ட்கேர் சுயவிவரம் உங்கள் சாதனத்தில் பாதுகாப்பாக உள்ளது. உங்களால் மட்டுமே திறக்க முடியும் என்பதற்காக பயனர்பெயர் மற்றும் கடவுச்சொல்லை வைங்கள்.',
  L10nKeys.authLoginTitle: 'மீண்டும் வரவேற்கிறோம்',
  L10nKeys.authLoginBody: 'உங்கள் தோட்டத்தை திறக்க பயனர்பெயர் மற்றும் கடவுச்சொல்லுடன் உள்நுழையுங்கள்.',
  L10nKeys.authUsername: 'பயனர்பெயர்',
  L10nKeys.authUsernameHint: 'எ.கா: ranu123',
  L10nKeys.authDisplayName: 'உங்கள் பெயர்',
  L10nKeys.authPassword: 'கடவுச்சொல்',
  L10nKeys.authPasswordHint: 'குறைந்தது 6 எழுத்துகள்',
  L10nKeys.authConfirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
  L10nKeys.authRoleQuestion: 'இந்த சுயவிவரம் யாருக்கு…',
  L10nKeys.authRolePatient: 'எனக்காக',
  L10nKeys.authRoleCaregiver: 'குடும்ப உறுப்பினருக்காக',
  L10nKeys.authCreate: 'கணக்கை உருவாக்கு',
  L10nKeys.authSignIn: 'உள்நுழை',
  L10nKeys.authSignOut: 'வெளியேறு',
  L10nKeys.authAccount: 'கணக்கு',
  L10nKeys.caregiverTitle: 'பராமரிப்பாளர்',
  L10nKeys.caregiverNotLinked:
      'இன்னும் எந்தப் பராமரிப்பாளரும் இணைக்கப்படவில்லை',
  L10nKeys.authBadCredentials: 'பயனர்பெயர் அல்லது கடவுச்சொல் தவறு.',
  L10nKeys.authUsernameTaken: 'இந்த பயனர்பெயர் இந்த சாதனத்தில் ஏற்கனவே உள்ளது.',
  L10nKeys.authPasswordMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை.',
  L10nKeys.authUsernameShort:
      'பயனர்பெயர் குறைந்தது 3 எழுத்துகள் இருக்க வேண்டும்.',
  L10nKeys.authUsernameInvalid: 'எழுத்துகள், எண்கள், புள்ளி, டாஷ் அல்லது அண்டர்ஸ்கோர் மட்டுமே பயன்படுத்துங்கள்.',
  L10nKeys.authPasswordShort:
      'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.',
  L10nKeys.authNameRequired: 'பெயரை உள்ளிடவும்.',
  L10nKeys.authSignOutConfirm:
      'இந்த சுயவிவரத்திலிருந்து வெளியேற விரும்புகிறீர்களா?',
  L10nKeys.screenTitle: 'விரைவான நினைவக சோதனை',
  L10nKeys.screenIntro: 'நோயாளி பற்றி சில சிறிய கேள்விகள் கேட்போம். கடந்த சில மாதங்களில் அவர்கள் எப்படி இருந்தார்கள் என்று யோசியுங்கள்.',
  L10nKeys.screenNotSure: 'நிச்சயமில்லை',
  L10nKeys.screenFinish: 'என் முடிவை பார்க்கவும்',
  L10nKeys.screenSkip: 'இப்போது வேண்டாம்',
  L10nKeys.screenResultBack: 'முடிந்தது',
  L10nKeys.screenCheckAgain: 'மீண்டும் சரிபார்க்கவும்',
  L10nKeys.screenStartCheckup: 'சோதனையை தொடங்கவும்',
  L10nKeys.screenSkipped: 'சோதனை தவிர்க்கப்பட்டது',
  L10nKeys.screenStatusGood: 'எல்லாம் நன்றாக உள்ளது',
  L10nKeys.screenStatusGoodBody: 'பெரிய கவலை எதுவும் கவனிக்கப்படவில்லை. அன்றாட செயல்களை தொடருங்கள், மற்றும் ஏதேனும் மாறினால் எப்போது வேண்டுமானாலும் மீண்டும் சரிபார்க்கலாம்.',
  L10nKeys.screenStatusWatch: 'சில மாற்றங்கள் கவனிக்கப்பட்டன',
  L10nKeys.screenStatusWatchBody: 'மறக்கும் சில தருணங்கள் காணப்பட்டன. இது வயதுக்கு ஏற்ப பொதுவானது, ஆனால் கவனத்தில் வையுங்கள் மற்றும் அடுத்த மருத்துவர் சந்திப்பில் சொல்லுங்கள்.',
  L10nKeys.screenStatusDoctor: 'தயவுசெய்து சோதனை செய்யுங்கள்',
  L10nKeys.screenStatusDoctorBody: 'கவனம் தேவைப்படக்கூடிய சில அறிகுறிகள் காணப்பட்டன. அவர்கள் உதவ முடியும் என்பதற்காக இவற்றை மருத்துவர் அல்லது மருத்துவமனையிடம் பகிருங்கள்.',
  L10nKeys.screenRarely: 'அரிதாக',
  L10nKeys.screenSometimes: 'சில நேரங்களில்',
  L10nKeys.screenFrequently: 'அடிக்கடி',
  L10nKeys.screenVeryFrequently: 'மிக அடிக்கடி',
  L10nKeys.screenQ01:
      'சமீபத்திய நிகழ்வுகளை நினைவில் கொள்வதில் அவர்களுக்கு சிரமம் உள்ளதா?',
  L10nKeys.screenQ02: 'அதே கேள்விகள் அல்லது கதைகளை மீண்டும் சொல்கிறார்களா?',
  L10nKeys.screenQ03: 'தெரிந்த நபர்களின் பெயர்களை மறக்கிறார்களா?',
  L10nKeys.screenQ04: 'தெரிந்த முகங்களை அடையாளம் காண்பதில் சிரமம் உள்ளதா?',
  L10nKeys.screenQ05: 'சந்திப்புகள் அல்லது முக்கிய நிகழ்வுகளை மறக்கிறார்களா?',
  L10nKeys.screenQ06: 'சரியான வார்த்தைகளை கண்டுபிடிப்பதில் சிரமம் உள்ளதா?',
  L10nKeys.screenQ07: 'தங்கள் இருப்பிடம் குறித்து குழப்பமடைகிறார்களா?',
  L10nKeys.screenQ08: 'அன்றாட செயல்களுக்கு நினைவூட்டல் தேவையா?',
  L10nKeys.screenQ09: 'மருந்துகளை கையாள்வதில் சிரமம் உள்ளதா?',
  L10nKeys.screenQ10:
      'குழப்பமடையும்போது பதற்றமடைகிறார்களா அல்லது எரிச்சலடைகிறார்களா?',
  L10nKeys.screenQ11: 'உரையாடலைப் புரிந்துகொள்வதில் சிரமம் உள்ளதா?',
  L10nKeys.screenQ12: 'தெரிந்த பணிகளை முடிப்பதில் சிரமம் உள்ளதா?',
  L10nKeys.screenQ13:
      'அன்றாட பொருட்கள் எங்கே வைக்கப்படுகின்றன என்பதை மறக்கிறார்களா?',
  L10nKeys.screenQ14: 'வழிமுறைகளை நினைவில் கொள்வதில் சிரமம் உள்ளதா?',
  L10nKeys.screenQ15: 'பல-படி செயல்களை செய்வதில் சிரமம் உள்ளதா?',

  L10nKeys.careDashboardSubtitle: 'குடும்ப கவனிப்பு',
  L10nKeys.careSosLive: 'நேரடி எச்சரிக்கை',
  L10nKeys.careSosRespondedBy: '{name} பதிலளித்தார்',
  L10nKeys.careLinkTitle: 'குடும்ப உறுப்பினருடன் இணைக்கவும்',
  L10nKeys.careLinkBody: 'அவர்களின் தொலைபேசியில் காட்டப்படும் 6-எழுத்து குடும்பக் குறியீட்டை உங்கள் அன்பானவரிடம் கேளுங்கள், பிறகு இணைக்கவும்.',
  L10nKeys.careLinkCode: 'குடும்பக் குறியீடு',
  L10nKeys.careLinkCodeHint: 'எ.கா. A1B2C3',
  L10nKeys.careLinkConnect: 'இணைக்க',
  L10nKeys.careLinkDone: 'இணைக்கப்பட்டது',
  L10nKeys.careLinkSuccess: '{name} உடன் இணைக்கப்பட்டது! நினைவுகள் மற்றும் எச்சரிக்கைகள் இப்போது ஒத்திசைக்கப்படும்.',
  L10nKeys.careLinkFailed:
      'இணைக்க முடியவில்லை. குறியீட்டைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  L10nKeys.careTrendsTitle: 'AI போக்குகள்',
  L10nKeys.careTrendsBody: 'செயல்பாட்டு வகைக்கு ஏற்ப தினசரி துல்லியம்',
  L10nKeys.careTrendsNoData: 'இன்னும் செயல்பாடு இல்லை — போக்குகளைப் பார்க்க ஒரு பயிற்சியை முடிக்கவும்.',
  L10nKeys.careAiDifficulty: 'தானாகச் சரிசெய்யப்பட்ட சிரமம்',
  L10nKeys.careAiAccuracy: 'மாதிரித் துல்லியம்',
  L10nKeys.careAiRealSessions: 'உண்மையான அமர்வுகள்',
  L10nKeys.careAiDemoSessions: 'டெமோ அமர்வுகள்',
  L10nKeys.careNavGames: 'விளையாட்டுகள்',
  L10nKeys.careNavRoutine: 'தினசரி வழக்கம்',
  L10nKeys.careGreetSubtitle: 'இன்று {name} எப்படி இருக்கிறார் என்பது இங்கே.',
  L10nKeys.careNotifEmpty: 'புதிய அறிவிப்புகள் இல்லை',
  L10nKeys.careWellnessScore: 'அறிவாற்றல் நலன் மதிப்பெண்',
  L10nKeys.careStatusStable: 'நிலையானது',
  L10nKeys.careStatusAttention: 'கவனம் தேவை',
  L10nKeys.careLastSynced: 'கடைசியாக ஒத்திசைத்தது {time}',
  L10nKeys.careMinAgo: '{n} நிமிடங்களுக்கு முன்',
  L10nKeys.careGamesWeek: 'இந்த வார விளையாட்டுகள்',
  L10nKeys.careRoutineCompletion: 'தினசரி வழக்கம் முடிதல்',
  L10nKeys.careCurrentStreak: 'தற்போதைய தொடர்',
  L10nKeys.careMoodCheckins: 'மனநிலை சரிபார்ப்புகள்',
  L10nKeys.careDayUnit: 'நாள்',
  L10nKeys.careDaysUnit: 'நாட்கள்',
  L10nKeys.careActivityTitle: 'வாராந்திர செயல்பாடு',
  L10nKeys.careWeekly: 'வாராந்திரம்',
  L10nKeys.careMonthly: 'மாதாந்திரம்',
  L10nKeys.careNoActivityWeek:
      'இந்த வாரம் இன்னும் எந்த செயல்பாடும் பதிவு செய்யப்படவில்லை.',
  L10nKeys.careMoodTitle: 'மனநிலை',
  L10nKeys.careMoodHappy: 'மகிழ்ச்சி',
  L10nKeys.careMoodCalm: 'அமைதி',
  L10nKeys.careMoodNeutral: 'நடுநிலை',
  L10nKeys.careMoodLow: 'குறைவு',
  L10nKeys.careMood7Days: 'கடந்த 7 நாட்கள்',
  L10nKeys.careMoodInsight: '{name} இந்த வாரம் பெரும்பாலும் அமைதியாக இருந்தார், கடந்த இரண்டு நாட்களில் மென்மையான சரிவு காணப்பட்டது.',
  L10nKeys.careMoodNoData: 'இந்த வாரம் இன்னும் மனநிலை சரிபார்ப்புகள் இல்லை.',
  L10nKeys.careSkillsTitle: 'அறிவாற்றல் திறன்கள்',
  L10nKeys.careSkillMemory: 'நினைவாற்றல்',
  L10nKeys.careSkillAttention: 'கவனம்',
  L10nKeys.careSkillLanguage: 'மொழி',
  L10nKeys.careSkillReasoning: 'பகுத்தறிவு',
  L10nKeys.careSkillProcessing: 'செயலாக்க வேகம்',
  L10nKeys.careInsightToday: 'இன்றைய நுண்ணறிவு',
  L10nKeys.careInsightBody: 'ராபர்ட் தனது காலை வழக்கத்திற்குப் பிறகு நினைவாற்றல் செயல்பாடுகளில் நிலையாக இருந்தார். கடந்த இரண்டு நாட்களில் அவரது மனநிலை சற்று குறைவாக இருந்தது.',
  L10nKeys.careInsightBodyReal: 'இந்த வாரம் {name} {count} அறிவாற்றல் அமர்வுகளை (இலக்கு {goal}) முடித்தார், மேலும் {streak}-நாள் தொடரை தொடர்கிறார்.',
  L10nKeys.careViewDetails: 'விவரங்களைப் பார்க்க',
  L10nKeys.careInsightDisclaimer: 'இது தரவுகளிலிருந்து எடுக்கப்பட்ட ஒரு மென்மையான கவனிப்பு — இது மருத்துவ நோயறிதல் அல்ல.',
  L10nKeys.careAttentionTitle: 'உங்கள் கவனம் தேவை',
  L10nKeys.careAttentionEmpty:
      'இப்போது உங்கள் கவனம் தேவைப்படும் எதுவும் இல்லை.',
  L10nKeys.careAlertSos: '{name} SOS பொத்தானை அழுத்தினார்',
  L10nKeys.careAlertRoutineMissed: 'நேற்று தினசரி வழக்கம் தவறவிட்டது',
  L10nKeys.careAlertMoodDown: 'கடந்த இரண்டு நாட்களில் மனநிலை குறைந்தது',
  L10nKeys.careAlertSessionPending: 'இன்று அறிவாற்றல் அமர்வு முடிக்கப்படவில்லை',
  L10nKeys.careAlertSeverityHigh: 'அதிகம்',
  L10nKeys.careAlertSeverityMedium: 'நடுத்தரம்',
  L10nKeys.careAlertSeverityLow: 'குறைவு',
  L10nKeys.careWeeklySummary: 'வாராந்திர சுருக்கம்',
  L10nKeys.careSessionsCompleted: 'முடிக்கப்பட்ட அமர்வுகள்',
  L10nKeys.careAvgSessionDuration: 'சராசரி அமர்வு காலம்',
  L10nKeys.careRoutineAdherence: 'தினசரி வழக்கத்தை கடைப்பிடித்தல்',
  L10nKeys.careMoodTrend: 'மனநிலை போக்கு',
  L10nKeys.careMoodTrendSlightlyDown: 'சற்று குறைவாக',
  L10nKeys.careMoodTrendStable: 'நிலையானது',
  L10nKeys.careMoodTrendUp: 'மேம்படுகிறது',
  L10nKeys.careVsLastWeek: 'கடந்த வாரத்துடன் ஒப்பிடும்போது',
  L10nKeys.careSyncedJustNow: 'இப்போதுதான் ஒத்திசைக்கப்பட்டது',
  L10nKeys.careOfflineWaiting:
      'ஆஃப்லைன் · ஒத்திசைக்க காத்திருக்கும் {count} செயல்பாடுகள்',
  L10nKeys.careComingSoon: 'விரைவில் வருகிறது',
  L10nKeys.careHomeSoon:
      '{name}வின் நாள் பற்றிய விரைவான கண்ணோட்டம் இங்கே தோன்றும்.',
  L10nKeys.careGamesSoon: 'விளையாட்டுகள் மற்றும் அமர்வு வரலாறு இங்கே தோன்றும்.',
  L10nKeys.careRoutineSoon: 'நோயாளியின் தினசரி வழக்கம் இங்கே தோன்றும்.',
  L10nKeys.careProfileSoon:
      'பராமரிப்பாளர் சுயவிவரம் மற்றும் அமைப்புகள் இங்கே தோன்றும்.',
  L10nKeys.serverPairingTitle: 'குடும்பக் குறியீடு',
  L10nKeys.serverPairingBody: 'இந்தக் குறியீட்டை ஒரு பராமரிப்பாளருடன் பகிர்ந்து கொள்ளுங்கள், அவர்கள் உங்களுடன் இணைக்கலாம்.',
  L10nKeys.serverUnlinked: 'சேவையகத்துடன் இணைக்கப்படவில்லை',
  L10nKeys.serverLinked: 'சேவையகத்துடன் இணைக்கப்பட்டது',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
  // Patient-home, memories, voice and calendar fallbacks (English source).
  L10nKeys.addFirstRoutine: 'Add your first routine',
  L10nKeys.addMemoryTooltip: 'Add a memory',
  L10nKeys.addRoutine: 'Add routine',
  L10nKeys.addToMemory: 'Add to this memory',
  L10nKeys.attachmentsAddedMany: '{count} attachments added',
  L10nKeys.attachmentsAddedOne: '1 attachment added',
  L10nKeys.careAchieveEngagement: '10 Hours of Play',
  L10nKeys.careAchieveEngagementBody: '10 total hours spent playing together',
  L10nKeys.careAchieveFirstSteps: 'First Steps',
  L10nKeys.careAchieveFirstStepsBody: 'Patient completed their first session',
  L10nKeys.careAchieveGarden: 'Garden in Bloom',
  L10nKeys.careAchieveGardenBody: 'Grow 5 plants in the Memory Garden',
  L10nKeys.careAchievePerfect: 'Perfect Round',
  L10nKeys.careAchievePerfectBody: 'A game finished with a perfect score',
  L10nKeys.careAchieveSevenDay: 'One Week Together',
  L10nKeys.careAchieveSevenDayBody: 'A session on 7 different days',
  L10nKeys.categoryLabel: 'Category',
  L10nKeys.createMemory: 'Create a Memory',
  L10nKeys.deleteAction: 'Delete',
  L10nKeys.deleteRoutineBody: 'Remove "{title}" from your routine?',
  L10nKeys.deleteRoutineTitle: 'Delete routine?',
  L10nKeys.deleteRoutineTooltip: 'Delete routine',
  L10nKeys.homeRoutineSubtitle: 'A calm little plan for your day.',
  L10nKeys.medicineKind: 'Medicine',
  L10nKeys.memoriesKindVideo: 'Video',
  L10nKeys.memoriesSubtitle: 'Keep your favourite moments close.',
  L10nKeys.memoryCaptionHint: 'What happened? Who was there? How did it feel?',
  L10nKeys.memoryCaptionLabel: 'Write something about this memory',
  L10nKeys.memoryComposeHint: 'Add a title, some text, and as many photos, videos or voice notes as you want.',
  L10nKeys.memorySaved: 'Memory saved 💙',
  L10nKeys.memoryTitleHint: 'e.g. My daughter\'s wedding',
  L10nKeys.memoryTitleLabel: 'Memory title',
  L10nKeys.memoryTitleRequired: 'Please give this memory a title.',
  L10nKeys.micVoicePermission: 'Microphone permission is needed for a voice memory.',
  L10nKeys.monthApr: 'Apr',
  L10nKeys.monthAug: 'Aug',
  L10nKeys.monthDec: 'Dec',
  L10nKeys.monthFeb: 'Feb',
  L10nKeys.monthJan: 'Jan',
  L10nKeys.monthJul: 'Jul',
  L10nKeys.monthJun: 'Jun',
  L10nKeys.monthMar: 'Mar',
  L10nKeys.monthMay: 'May',
  L10nKeys.monthNov: 'Nov',
  L10nKeys.monthOct: 'Oct',
  L10nKeys.monthSep: 'Sep',
  L10nKeys.photoAddFailed: 'Could not add this photo. Please try again.',
  L10nKeys.profileMissing: 'No patient profile found. Please sign in again.',
  L10nKeys.recordingStartFailed: 'Could not start recording. Please try again.',
  L10nKeys.routineAddBody: 'Create a simple reminder for your day.',
  L10nKeys.routineAddTitle: 'Add a routine',
  L10nKeys.routineCheckBody: 'Small steps for a good day',
  L10nKeys.routineCheckTitle: 'Routine check',
  L10nKeys.routineKind: 'Routine',
  L10nKeys.routineNameHint: 'e.g. Drink water',
  L10nKeys.routineNameLabel: 'Routine name',
  L10nKeys.savedMemoriesTitle: 'Saved Memories',
  L10nKeys.saveMemory: 'Save Memory',
  L10nKeys.settings: 'Settings',
  L10nKeys.sosShort: 'SOS',
  L10nKeys.stop: 'Stop',
  L10nKeys.stopVoiceFirst: 'Stop the voice recording first.',
  L10nKeys.textShort: 'Text',
  L10nKeys.timeLabel: 'Time',
  L10nKeys.videoAddFailed: 'Could not add this video. Please try again.',
  L10nKeys.voiceSaveFailed: 'Could not save the voice recording.',
  L10nKeys.voiceShort: 'Voice',
  L10nKeys.waterKind: 'Water',
};
