import '../l10n_keys.dart';

/// Bengali dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsBn = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'আপনার স্মৃতির সঙ্গী',
  L10nKeys.back: 'পেছনে',
  L10nKeys.next: 'এগিয়ে',
  L10nKeys.continueText: 'চালিয়ে যান',
  L10nKeys.skip: 'এড়িয়ে যান',
  L10nKeys.done: 'সম্পন্ন',
  L10nKeys.cancel: 'বাতিল',
  L10nKeys.yes: 'হ্যাঁ',
  L10nKeys.no: 'না',
  L10nKeys.save: 'সেভ করুন',
  L10nKeys.close: 'বন্ধ',
  L10nKeys.retry: 'আবার চেষ্টা',
  L10nKeys.add: 'যোগ করুন',
  L10nKeys.edit: 'সম্পাদনা',
  L10nKeys.remove: 'মুছে ফেলুন',
  L10nKeys.search: 'খুঁজুন',
  L10nKeys.today: 'আজ',
  L10nKeys.offline: 'অফলাইন',
  L10nKeys.online: 'অনলাইন',

  L10nKeys.goodMorning: 'সুপ্রভাত',
  L10nKeys.goodAfternoon: 'নমস্কার',
  L10nKeys.goodEvening: 'শুভ সন্ধ্যা',
  L10nKeys.goodNight: 'শুভ রাত্রি',

  L10nKeys.navHome: 'হোম',
  L10nKeys.navGarden: 'বাগান',
  L10nKeys.navActivities: 'কার্যকলাপ',
  L10nKeys.navMemories: 'স্মৃতি',
  L10nKeys.navProfile: 'প্রোফাইল',
  L10nKeys.navMystery: 'আজকের স্মৃতি',

  L10nKeys.onboardingWelcomeTitle: 'আপনার স্মৃতির জন্য এক কোমল সঙ্গী',
  L10nKeys.onboardingWelcomeBody: 'মাইন্ডকেয়ার এনইআর ইন্টারনেট ছাড়াই মনে রাখতে, খেলতে ও পরিবারের সঙ্গে যুক্ত থাকতে সহায়তা করে।',
  L10nKeys.onboardingNameTitle: 'আমরা আপনাকে কী বলে ডাকব?',
  L10nKeys.onboardingNameHint: 'আপনার নাম',
  L10nKeys.onboardingRegionTitle: 'আপনার বাড়ি কোথায়?',
  L10nKeys.onboardingRegionHint: 'শহর বা গ্রাম',
  L10nKeys.onboardingRegionList: 'গুয়াহাটি, শিলচর, শিলং, আগরতলা, ইম্ফল, আইজল, ইটানগর, কোহিমা, গ্যাংটক, ডিব্রুগড়, যোরহাট, আপনার শহর',
  L10nKeys.onboardingLanguageTitle: 'আপনি কোন ভাষা পছন্দ করেন?',
  L10nKeys.onboardingLanguageBody: 'এটি যেকোনো সময় বদলাতে পারেন।',
  L10nKeys.onboardingFamilyTitle: 'পরিবার কারা?',
  L10nKeys.onboardingFamilyBody: 'আপনার প্রিয়জনদের যোগ করুন। আমরা তাদের ছবি ও কণ্ঠ কোমল স্মৃতি হিসেবে দেখাব।',
  L10nKeys.onboardingAddFamily: 'পরিবারের সদস্য যোগ করুন',
  L10nKeys.onboardingEmergencyTitle: 'জরুরি অবস্থায় আমরা কাকে ডাকব?',
  L10nKeys.onboardingEmergencyBody:
      'SOS বাটন চাপলে মাইন্ডকেয়ার আপনার পরিবারকে জানাবে, জরুরি পরিষেবাকে নয়।',
  L10nKeys.onboardingEmergencyName: 'নাম',
  L10nKeys.onboardingEmergencyPhone: 'ফোন নম্বর',
  L10nKeys.onboardingEmergencyRelation: 'সম্পর্ক (মেয়ে, ছেলে…)',
  L10nKeys.onboardingDoneTitle: 'আপনার বাগান প্রস্তুত!',
  L10nKeys.onboardingDoneBody: 'ছোট কাজগুলো সম্পন্ন করুন এবং বাগান বেড়ে ওঠা দেখুন। আমরা সবসময় আপনার পাশে আছি।',
  L10nKeys.onboardingStart: 'আমার বাগান শুরু করুন',

  L10nKeys.homeWhatsGrowing: 'আজ কী বাড়ছে?',
  L10nKeys.homeTodayActivity: 'আজকের ছোট কার্যকলাপ',
  L10nKeys.homeActivityDuration: 'প্রায় ৩ মিনিট',
  L10nKeys.homeMinutes: 'মিনিট',
  L10nKeys.homeMemoryOfDay: 'আজকের স্মৃতি',
  L10nKeys.homeMemoryLocked: 'একটি বিশেষ স্মৃতি অপেক্ষা করছে…',
  L10nKeys.homeMemoryUnlocked: 'একটি স্মৃতি খুলে গেছে!',
  L10nKeys.homeContinueActivity: 'কার্যকলাপ চালিয়ে যান',
  L10nKeys.homeFamilyMemory: 'আপনার পরিবারের পক্ষ থেকে',
  L10nKeys.homeFamilyMemoryEmpty: 'পরিবারের স্মৃতি এখানে আসতে পারে।',
  L10nKeys.homeSos: 'সাহায্য প্রয়োজন',
  L10nKeys.homeSosSubtitle: 'জরুরি অবস্থায় পরিবারের সঙ্গে যোগাযোগ',
  L10nKeys.homeGardenPreview: 'আপনার বাগান',
  L10nKeys.homeEngine: 'মাইন্ডকেয়ার সঙ্গী',
  L10nKeys.homeEngineReady: 'আপনার সহায়ক প্রস্তুত।',
  L10nKeys.homeWelcomeBack: 'ফিরে আসায় স্বাগতম! বাগান চালিয়ে যান। 🌸',
  L10nKeys.homeNoActivity: 'আজ কোনো কার্যকলাপ নেই',
  L10nKeys.homeNoActivityBody: 'বিশ্রাম নিন — বা যেকোনো কার্যকলাপ বেছে নিন। 🌻',

  L10nKeys.gardenTitle: 'আমার স্মৃতি বাগান',
  L10nKeys.gardenSectionAll: 'সব',
  L10nKeys.gardenSectionFamily: 'পরিবার',
  L10nKeys.gardenSectionChildhood: 'শৈশব',
  L10nKeys.gardenSectionPlaces: 'স্থান',
  L10nKeys.gardenSectionFestivals: 'উৎসব',
  L10nKeys.gardenEmpty: 'আপনার বাগান সবে শুরু',
  L10nKeys.gardenEmptyBody:
      'প্রথম কার্যকলাপ সম্পন্ন করুন, এখানে একটি বীজ রোপণ হবে।',
  L10nKeys.gardenPoints: 'পয়েন্ট',
  L10nKeys.gardenLevel: 'স্তর',
  L10nKeys.gardenSeed: 'বীজ',
  L10nKeys.gardenPlant: 'চারা',
  L10nKeys.gardenFlower: 'ফুল',
  L10nKeys.gardenTree: 'গাছ',
  L10nKeys.gardenMilestone: 'মাইলফলক',
  L10nKeys.gardenGrowth: 'বাড়ছে',
  L10nKeys.gardenDidYouKnow: 'প্রতিটি কার্যকলাপ সম্পন্ন হলে আপনার বাগান বাড়ে।',
  L10nKeys.gardenPlantSeed: 'বীজ রোপণ করুন',

  L10nKeys.activitiesTitle: 'কার্যকলাপ',
  L10nKeys.activitiesToday: 'আজ',
  L10nKeys.activitiesLibrary: 'আরও কার্যকলাপ',
  L10nKeys.mainGamesTitle: 'প্রধান খেলা',
  L10nKeys.activitiesStart: 'শুরু',
  L10nKeys.activitiesCompleted: 'সম্পন্ন',
  L10nKeys.activitiesInProgress: 'চলছে',
  L10nKeys.activitiesNotStarted: 'প্রস্তুত',
  L10nKeys.activityYoureDone: 'খুব সুন্দর!',
  L10nKeys.activityPraise: 'আপনি আপনার বাগানে নতুন প্রাণ এনেছেন। 🌱',
  L10nKeys.activityHint: 'ইঙ্গিত চাই?',
  L10nKeys.activityTryAgain: 'এই স্মৃতিটি আবার দেখি',
  L10nKeys.activityOptionsHint: 'আপনার উত্তরটি চাপুন',
  L10nKeys.activityTapToMatch: 'যা একসাথে জুড়ে যায় তা স্পর্শ করুন',
  L10nKeys.activityNext: 'পরবর্তী',
  L10nKeys.activityFinish: 'শেষ',
  L10nKeys.activityGroupLetsAgain: 'এটি আবার দেখি',
  L10nKeys.activityGroupTogether: 'এটি একসাথে করি',
  L10nKeys.activityGreatJob: 'সাবাশ!',
  L10nKeys.activityKitchen: 'আমার রান্নাঘর',
  L10nKeys.activityShopping: 'আমার দোকান',
  L10nKeys.activityMatching: 'জোড়া মেলান',
  L10nKeys.activitySequence: 'ক্রমে সাজান',
  L10nKeys.activityRecognition: 'এটি কী?',
  L10nKeys.activityAssociation: 'কী একসাথে যায়?',
  L10nKeys.activityRecall: 'মনে আছে কি?',
  L10nKeys.activityAttention: 'খুঁজে বের করুন',
  L10nKeys.activityDurationSuffix: 'মিনিট',
  L10nKeys.activityTodayDone: 'আজকের কার্যকলাপ শেষ',
  L10nKeys.activityTodayDoneBody:
      'আপনার বাগান বেড়েছে। কাল একটি স্মৃতি অপেক্ষা করতে পারে।',
  L10nKeys.activityGardenGrew: 'আপনার বাগান বেড়েছে!',
  L10nKeys.activityMemoryUnlocked: 'একটি স্মৃতি খুলে গেছে',
  L10nKeys.activityReadAloud: 'উচ্চস্বরে পড়ুন',

  L10nKeys.kitchenTitle: 'চা বানাই',
  L10nKeys.kitchenMakeChai: 'চা বানানো',
  L10nKeys.kitchenMakeChaiPrompt: 'সঠিক ক্রমে ধাপগুলো চাপুন।',
  L10nKeys.kitchenSteps: 'ধাপ',
  L10nKeys.kitchenTapInOrder: 'সঠিক ক্রমে ধাপগুলো চাপুন',
  L10nKeys.kitchenCorrectOrder: 'দারুণ! চা প্রস্তুত!',
  L10nKeys.kitchenBreakfast: 'সকালের নাশতা বানানো',
  L10nKeys.kitchenBreakfastHint: 'দিনের একটি তাজা শুরু',
  L10nKeys.kitchenBreakfastPrompt: 'নাশতার ধাপগুলো ক্রমে সাজান।',

  L10nKeys.shopTitle: 'আমার দোকান',
  L10nKeys.shopGetMilkBread: 'রুটি ও দুধ',
  L10nKeys.shopGetMilkBreadPrompt: '₹১০০-এর মধ্যে দুধ ও রুটি নিন।',
  L10nKeys.shopBudget: 'বাজেট',
  L10nKeys.shopBasket: 'আপনার ঝুড়ি',
  L10nKeys.shopTotal: 'মোট',
  L10nKeys.shopWithinBudget: 'বাজেটের মধ্যে!',
  L10nKeys.shopOverBudget: 'বাজেটের বেশি — আবার দেখুন',
  L10nKeys.shopCheckout: 'শেষ ও পরিশোধ',
  L10nKeys.shopBuy: 'ঝুড়িতে যোগ করুন',
  L10nKeys.shopSell: 'মুছে ফেলুন',
  L10nKeys.shopVeggies: 'রাতের খাবারের সবজি',
  L10nKeys.shopVeggiesPrompt: '₹৬০-এর মধ্যে আলু ও পেঁয়াজ নিন।',
  L10nKeys.recKitchenItem: 'এটি কোনটি?',
  L10nKeys.recKitchenItemPrompt:
      'বাজার থেকে মাল আনার জন্য এগুলো কোনটি ব্যবহার করি?',
  L10nKeys.recCurrency: 'একটু টাকা',
  L10nKeys.recCurrencyPrompt: 'কোন নোটটি ₹২০?',
  L10nKeys.matchFestival: 'উৎসব মেলান',
  L10nKeys.matchFestivalPrompt: 'প্রতিটি উৎসবকে তার বিশেষ খাবারের সঙ্গে মেলান।',
  L10nKeys.matchObjectUse: 'জোড়া মেলান',
  L10nKeys.matchObjectUsePrompt:
      'প্রতিটি জিনিসকে এর ব্যবহারের সময়ের সঙ্গে মেলান।',
  L10nKeys.seqMorning: 'সকালের রুটিন',
  L10nKeys.seqMorningPrompt: 'আপনার সকালের রুটিন ক্রমে সাজান।',
  L10nKeys.seqRoute: 'সকালের যাত্রা',
  L10nKeys.seqRoutePrompt: 'বাজারে যাওয়ার যাত্রা ক্রমে সাজান।',
  L10nKeys.assoRegion: 'এখানে কী আছে?',
  L10nKeys.assoRegionPrompt: 'আসাম কিসের জন্য বিখ্যাত?',
  L10nKeys.assoHarvest: 'মিষ্টি ফল',
  L10nKeys.assoHarvestPrompt: 'কোন ফলকে গ্রীষ্মের রাজা বলা হয়?',
  L10nKeys.attnVeg: 'গাজর খুঁজুন',
  L10nKeys.attnVegPrompt: 'গাজরটি কি খুঁজে পাবেন?',
  L10nKeys.recallSong: 'একটি চেনা গান',
  L10nKeys.recallSongPrompt: 'বিহুতে নাচের সময় নৃত্যশিল্পীরা কোন গানে নাচে?',
  L10nKeys.activityPairs: 'জোড়া খুঁজুন',
  L10nKeys.activitySequenceRecall: 'ক্রম মনে রাখুন',
  L10nKeys.activityFindChanged: 'কী বদলেছে?',
  L10nKeys.pairsFruits: 'বাজারের ফল',
  L10nKeys.pairsKitchen: 'রান্নাঘরের জিনিস',
  L10nKeys.pairsRemember: 'সব কার্ড মন দিয়ে দেখুন, তারপর একই জোড়া খুঁজুন।',
  L10nKeys.pairsStart: 'কার্ড লুকিয়ে শুরু করুন',
  L10nKeys.pairsFound: 'জোড়া পাওয়া গেছে!',
  L10nKeys.seqRecallItems: 'দৈনন্দিন জিনিস',
  L10nKeys.seqRecallNumbers: 'ক্রমে ক্রমে সংখ্যা',
  L10nKeys.seqRecallWatch: 'কার্ড মন দিয়ে দেখুন – প্রতিটা ক্রমে জ্বলবে।',
  L10nKeys.seqRecallRepeat: 'যে ক্রমে দেখেছেন সেই ক্রমেই কার্ডে ট্যাপ করুন।',
  L10nKeys.changeMarket: 'ফলের ঝুড়ি',
  L10nKeys.changeFestival: 'উৎসবের আলো',
  L10nKeys.changeRemember: 'এই ছবিগুলো মন দিয়ে মনে রাখুন।',
  L10nKeys.changeFind: 'একটা ছবি বদলেছে। আলাদাটা খুঁজুন।',
  L10nKeys.changeCorrect: 'সাবাশ! ওটাই বদলেছিল।',

  L10nKeys.mysteryTitle: 'আজকের বিশেষ স্মৃতি',
  L10nKeys.mysteryLocked: 'একটি বিশেষ স্মৃতি আপনার জন্য অপেক্ষা করছে…',
  L10nKeys.mysteryLockedBody:
      'আজ ২-৩টি ছোট কাজ করুন, এটি খুলে যেতে পারে। এটি কী হবে?',
  L10nKeys.mysteryUnlocked: 'আপনার বিশেষ স্মৃতি এখানে!',
  L10nKeys.mysteryUnlockedBody: 'এই স্মৃতিটি কেবল আপনার। সময় নিন। 🌸',
  L10nKeys.mysteryCuriosity: 'আজ কী খুলবে?',
  L10nKeys.mysteryOpen: 'স্মৃতি খুলুন',

  L10nKeys.memoriesTitle: 'আমার স্মৃতি',
  L10nKeys.memoriesEmpty: 'এখনও কোনো স্মৃতি নেই',
  L10nKeys.memoriesEmptyBody:
      'আপনার পরিবার ছবি ও ভয়েস বার্তা যোগ করতে পারে। পাওয়া গেলে এখানে আসবে।',
  L10nKeys.memoriesFamily: 'পরিবার',
  L10nKeys.memoriesPlaces: 'স্থান',
  L10nKeys.memoriesFestivals: 'উৎসব',
  L10nKeys.memoriesChildhood: 'শৈশব',
  L10nKeys.memoriesKindPhoto: 'ছবি',
  L10nKeys.memoriesKindVoice: 'ভয়েস বার্তা',
  L10nKeys.memoriesKindText: 'গল্প',
  L10nKeys.memoriesKindSound: 'শব্দ',
  L10nKeys.memoriesKindPlace: 'স্থান',
  L10nKeys.memoriesAddedBy: 'যোগ করেছেন',
  L10nKeys.memoriesWhoIsThis: 'এ কে?',
  L10nKeys.memoriesPlayVoice: 'শুনুন',
  L10nKeys.memoriesThisIsMe: 'এই আমি',
  L10nKeys.memoriesNotMe: 'আমি নই',

  L10nKeys.profileTitle: 'প্রোফাইল',
  L10nKeys.profileLanguage: 'অ্যাপের ভাষা',
  L10nKeys.profileRegion: 'আমার অঞ্চল',
  L10nKeys.profileVoiceLanguage: 'কণ্ঠের ভাষা',
  L10nKeys.profileVoicePrompts: 'কণ্ঠের নির্দেশ',
  L10nKeys.profileTextSize: 'অক্ষরের আকার',
  L10nKeys.profileReducedMotion: 'শান্ত গতি',
  L10nKeys.profileSoundEffects: 'শব্দ প্রভাব',
  L10nKeys.profileFamily: 'পরিবার',
  L10nKeys.profileContacts: 'জরুরি যোগাযোগ',
  L10nKeys.profileDemoMode: 'ডেমো মোড',
  L10nKeys.profileReminders: 'রিমাইন্ডার',
  L10nKeys.profileNeedHelp: 'সাহায্য চাই?',

  L10nKeys.remindersTitle: 'রিমাইন্ডার',
  L10nKeys.remindersEmpty: 'এখনও কোনো রিমাইন্ডার নেই',
  L10nKeys.remindersNew: 'নতুন রিমাইন্ডার',
  L10nKeys.remindersTitleLabel: 'শিরোনাম',
  L10nKeys.remindersDetailLabel: 'বিস্তারিত (ঐচ্ছিক)',
  L10nKeys.remindersTime: 'সময়',
  L10nKeys.remindersDays: 'দিন',
  L10nKeys.remindersEveryday: 'প্রতিদিন',
  L10nKeys.remindersEnabled: 'চালু',
  L10nKeys.remindersMedicine: 'ওষুধ',
  L10nKeys.remindersAppointment: 'অ্যাপয়েন্টমেন্ট',
  L10nKeys.remindersRoutine: 'দৈনন্দিন রুটিন',

  L10nKeys.dayMon: 'সোম',
  L10nKeys.dayTue: 'মঙ্গল',
  L10nKeys.dayWed: 'বুধ',
  L10nKeys.dayThu: 'বৃহস্পতি',
  L10nKeys.dayFri: 'শুক্র',
  L10nKeys.daySat: 'শনি',
  L10nKeys.daySun: 'রবি',

  L10nKeys.sosTitle: 'জরুরি সাহায্য',
  L10nKeys.sosExplain: 'চেপে ধরে রাখুন। মাইন্ডকেয়ার আপনার জরুরি যোগাযোগগুলিকে একে একে জানাবে। এটি জরুরি পরিষেবা (যেমন ১১২) নয়।',
  L10nKeys.sosHold: 'সাহায্যের জন্য ধরে রাখুন',
  L10nKeys.sosHoldBody: 'ধরে রাখুন…',
  L10nKeys.sosActiveTitle: 'সাহায্যে যোগাযোগ হচ্ছে',
  L10nKeys.sosActiveBody: 'আপনার পরিবারকে জানানো হয়েছে। তারা না সাড়া দিলে পরের যোগাযোগকে ডাকা হবে।',
  L10nKeys.sosContacting: 'যোগাযোগ করা হচ্ছে',
  L10nKeys.sosContactFamily: 'পরিবারের সঙ্গে যোগাযোগ',
  L10nKeys.sosContacted: 'যোগাযোগ হয়েছে',
  L10nKeys.sosWaitingResponse: 'সাড়ার অপেক্ষা…',
  L10nKeys.sosEscalating: 'পরের জনকে বলা হচ্ছে…',
  L10nKeys.sosCancelled: 'সাহায্য অনুরোধ বাতিল',
  L10nKeys.sosCancelAction: 'সাহায্য অনুরোধ বাতিল করুন',
  L10nKeys.sosDone: 'সম্পন্ন',
  L10nKeys.sosHelpOnWay: 'শীঘ্রই তো কেউ পাশে থাকবে। 🧡',
  L10nKeys.sosNoContacts: 'এখনও কোনো জরুরি যোগাযোগ নেই',
  L10nKeys.sosNoContactsBody:
      'অনুগ্রহ করে পরিবারকে একটি জরুরি যোগাযোগ যোগ করতে বলুন।',
  L10nKeys.sosAddContact: 'যোগাযোগ যোগ করুন',
  L10nKeys.sosDisclaimer: 'মাইন্ডকেয়ার আপনার নির্বাচিত যোগাযোগগুলিকে জানায়। এটি সরকারি জরুরি পরিষেবার বিকল্প নয়।',
  L10nKeys.sosContactedPerson: 'পরিবারের সদস্যকে জানানো হয়েছে',
  L10nKeys.sosEscalatedTo: 'পরের পরিবারের সদস্যকে জানানো হয়েছে',
  L10nKeys.sosAcknowledged: 'পরিবারের একজন সাড়া দিয়েছেন। সাহায্য আসছে।',
  L10nKeys.sosNotSilent:
      'সাহায্য পাঠানো সম্ভব না হলে আমরা কখনো পাঠিয়েছি ভান করব না।',
  L10nKeys.sosAlertNotDelivered:
      'আপনার বার্তা এখনও পাঠানো যায়নি। আমরা চেষ্টা চালিয়ে যাব।',

  L10nKeys.careTitle: 'যত্নকারী',
  L10nKeys.careDashboard: 'সারসংক্ষেপ',
  L10nKeys.carePatients: 'আমার রোগীরা',
  L10nKeys.careMemories: 'স্মৃতি',
  L10nKeys.careContacts: 'জরুরি যোগাযোগ',
  L10nKeys.careSettings: 'সেটিংস',
  L10nKeys.careAddMemory: 'স্মৃতি যোগ করুন',
  L10nKeys.careAddContact: 'যোগাযোগ যোগ করুন',
  L10nKeys.careEngagement: 'সম্পৃক্ততা',
  L10nKeys.careActivitiesWeek: 'এই সপ্তাহের কার্যকলাপ',
  L10nKeys.careGardenProgress: 'বাগানের অগ্রগতি',
  L10nKeys.careRecentActivity: 'সাম্প্রতিক কার্যকলাপ',
  L10nKeys.careNoPatients: 'কোনো যুক্ত রোগী নেই',
  L10nKeys.careNoPatientsBody:
      'আপনার পরিবারের সদস্যকে যুক্ত করতে বলুন, বা রোগীর প্রোফাইল যোগ করুন।',
  L10nKeys.careAddPatient: 'রোগী যোগ করুন',
  L10nKeys.carePerformanceNote: 'সাম্প্রতিক কার্যকলাপের পারদর্শিতা এই ব্যক্তির স্বাভাবিক স্তরের চেয়ে কিছুটা কম।',
  L10nKeys.careUploadPhoto: 'ছবি আপলোড',
  L10nKeys.careRecordVoice: 'কণ্ঠ রেকর্ড',
  L10nKeys.careWriteMemory: 'স্মৃতি লিখুন',
  L10nKeys.careMemoryTitle: 'শিরোনাম',
  L10nKeys.careMemoryCaption: 'ক্যাপশন',
  L10nKeys.careMemoryRelation: 'এর মধ্যে কে? (সম্পর্ক)',
  L10nKeys.careMemoryCategory: 'শ্রেণি',
  L10nKeys.careContactName: 'নাম',
  L10nKeys.careContactPhone: 'ফোন নম্বর',
  L10nKeys.careContactPriority: 'কলের ক্রম',
  L10nKeys.careContactRelation: 'সম্পর্ক',
  L10nKeys.careEscalationTimeout: 'পরের যোগাযোগের আগে মিনিট',
  L10nKeys.careIncidentStatus: 'অবস্থা',
  L10nKeys.careAckSos: 'আমি সাড়া দিচ্ছি',
  L10nKeys.careResponding: 'সাড়া দিচ্ছে',
  L10nKeys.careActiveAlerts: 'সক্রিয় সতর্কতা',

  L10nKeys.syncSavingOffline: 'অফলাইন',
  L10nKeys.syncSavingOfflineBody:
      'আপনার কার্যকলাপ এই ডিভাইসে নিরাপদে সংরক্ষিত।',
  L10nKeys.syncSynced: 'সিঙ্ক হয়েছে',
  L10nKeys.syncInfo: 'আপনার তথ্য সিঙ্ক হয়েছে।',
  L10nKeys.syncPending: 'সিঙ্কের অপেক্ষায়',

  L10nKeys.errorGeneric: 'কিছু ভুল হয়েছে',
  L10nKeys.errorGenericBody:
      'আপনার অগ্রগতি নিরাপদ। অনুগ্রহ করে আবার চেষ্টা করুন।',
  L10nKeys.errorAudio: 'এই ডিভাইসে শব্দ চালানো যায়নি।',
  L10nKeys.errorPermission: 'ডিভাইস থেকে অনুমতি প্রয়োজন।',
  L10nKeys.errorNoInternetAction:
      'ইন্টারনেটের দরকার নেই — প্রথমে এখানেই সংরক্ষিত হয়।',

  L10nKeys.demoWelcome: 'ডেমো দেখুন',
  L10nKeys.demoExplain:
      'আপনি যাতে ঘুরে দেখতে পারেন, একটি নমুনা পরিবার ও স্মৃতি যোগ হবে।',
  L10nKeys.demoLoad: 'ডেমো বাগান লোড করুন',

  L10nKeys.unitsPoints: 'পয়েন্ট',
  L10nKeys.teaserChai: 'একটু চা বানাই।',
  L10nKeys.familiarityName: 'আশা',
  L10nKeys.regionMap: 'আমার অঞ্চল',
  L10nKeys.regionChoose: 'আপনার অঞ্চল বেছে নিন',
  L10nKeys.regionIndia: 'ভারত',
  L10nKeys.importantMemory: 'গুরুত্বপূর্ণ স্মৃতি',
  L10nKeys.growing: 'বাড়ছে',
  L10nKeys.blooming: 'ফুটছে',
  L10nKeys.mature: 'পরিপক্ব',
  L10nKeys.noVoice: 'এই ডিভাইসে কণ্ঠ উপলব্ধ নেই।',
  L10nKeys.optional: 'ঐচ্ছিক',

  L10nKeys.langChoose: 'ভাষা বেছে নিন',
  L10nKeys.langPrimary: 'প্রধান',
  L10nKeys.langNorthEast: 'উত্তর-পূর্ব ভারত',
  L10nKeys.langMajor: 'ভারতের প্রধান ভাষা',

  L10nKeys.authSignUpTitle: 'আপনার অ্যাকাউন্ট তৈরি করুন',
  L10nKeys.authSignUpBody: 'এই মাইন্ডকেয়ার প্রোফাইল আপনার ডিভাইসে নিরাপদে থাকবে। শুধু আপনার জন্যই খোলার জন্য ইউজারনেম ও পাসওয়ার্ড ব্যবহার করুন।',
  L10nKeys.authLoginTitle: 'ফিরে আসায় স্বাগতম',
  L10nKeys.authLoginBody:
      'আপনার বাগান খুলতে ইউজারনেম ও পাসওয়ার্ড দিয়ে সাইন ইন করুন।',
  L10nKeys.authUsername: 'ইউজারনেম',
  L10nKeys.authUsernameHint: 'যেমন: ranu123',
  L10nKeys.authDisplayName: 'আপনার নাম',
  L10nKeys.authPassword: 'পাসওয়ার্ড',
  L10nKeys.authPasswordHint: 'কমপক্ষে ৬ অক্ষর',
  L10nKeys.authConfirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
  L10nKeys.authRoleQuestion: 'এই প্রোফাইলটি কার জন্য…',
  L10nKeys.authRolePatient: 'আমার জন্য',
  L10nKeys.authRoleCaregiver: 'পরিবারের সদস্যের জন্য',
  L10nKeys.authCreate: 'অ্যাকাউন্ট তৈরি করুন',
  L10nKeys.authSignIn: 'সাইন ইন',
  L10nKeys.authSignOut: 'সাইন আউট',
  L10nKeys.authAccount: 'অ্যাকাউন্ট',
  L10nKeys.caregiverTitle: 'যত্নকারী',
  L10nKeys.caregiverNotLinked: 'এখনও কোনো যত্নকারী যুক্ত নেই',
  L10nKeys.authBadCredentials: 'ইউজারনেম বা পাসওয়ার্ড ভুল।',
  L10nKeys.authUsernameTaken: 'এই ডিভাইসে ইউজারনেমটি ইতিমধ্যে ব্যবহৃত হচ্ছে।',
  L10nKeys.authPasswordMismatch: 'পাসওয়ার্ড মেলেনি।',
  L10nKeys.authUsernameShort: 'ইউজারনেম কমপক্ষে ৩ অক্ষরের হতে হবে।',
  L10nKeys.authUsernameInvalid:
      'কেবল অক্ষর, সংখ্যা, বিন্দু, ড্যাশ বা আন্ডারস্কোর ব্যবহার করুন।',
  L10nKeys.authPasswordShort: 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।',
  L10nKeys.authNameRequired: 'অনুগ্রহ করে একটি নাম দিন।',
  L10nKeys.authSignOutConfirm: 'এই প্রোফাইল থেকে সাইন আউট করবেন?',
  L10nKeys.screenTitle: 'দ্রুত স্মৃতি পরীক্ষা',
  L10nKeys.screenIntro: 'আমরা রোগী সম্পর্কে কিছু ছোট প্রশ্ন জিজ্ঞেস করব। গত কয়েক মাসে তারা কেমন ছিলেন, তা ভাবুন।',
  L10nKeys.screenNotSure: 'নিশ্চিত নই',
  L10nKeys.screenFinish: 'আমার ফলাফল দেখুন',
  L10nKeys.screenSkip: 'এখন না',
  L10nKeys.screenResultBack: 'সম্পন্ন',
  L10nKeys.screenCheckAgain: 'আবার পরীক্ষা করুন',
  L10nKeys.screenStartCheckup: 'পরীক্ষা শুরু করুন',
  L10nKeys.screenSkipped: 'পরীক্ষা বাদ দেওয়া হয়েছে',
  L10nKeys.screenStatusGood: 'সব ঠিক আছে',
  L10nKeys.screenStatusGoodBody: 'কোনো বড় উদ্বেগ দেখা যায়নি। দৈনন্দিন কাজগুলো করে যান, এবং কিছু পরিবর্তন হলে যেকোনো সময় আবার পরীক্ষা করুন।',
  L10nKeys.screenStatusWatch: 'কিছু পরিবর্তন দেখা গেছে',
  L10nKeys.screenStatusWatchBody: 'কিছু ভুলে যাওয়ার মুহূর্ত দেখা গেছে। বয়সের সাথে এটা সাধারণ, তবে খেয়াল রাখুন এবং পরের ডাক্তারের দেখা করার সময় জানান।',
  L10nKeys.screenStatusDoctor: 'দয়া করে পরীক্ষা করান',
  L10nKeys.screenStatusDoctorBody: 'কয়েকটি লক্ষণ দেখা গেছে যেগুলোতে মনোযোগ প্রয়োজন। অনুগ্রহ করে এগুলো ডাক্তার বা ক্লিনিককে জানান যাতে তারা সাহায্য করতে পারে।',
  L10nKeys.screenRarely: 'খুব কমই',
  L10nKeys.screenSometimes: 'কখনো কখনো',
  L10nKeys.screenFrequently: 'ঘন ঘন',
  L10nKeys.screenVeryFrequently: 'খুব ঘন ঘন',
  L10nKeys.screenQ01: 'তাদের কি সাম্প্রতিক ঘটনা মনে রাখতে সমস্যা হয়?',
  L10nKeys.screenQ02: 'তারা কি একই প্রশ্ন বা গল্প বারবার করেন?',
  L10nKeys.screenQ03: 'তারা কি পরিচিত মানুষের নাম ভুলে যান?',
  L10nKeys.screenQ04: 'তাদের কি পরিচিত মুখ চিনতে সমস্যা হয়?',
  L10nKeys.screenQ05: 'তারা কি নির্ধারিত সময় বা গুরুত্বপূর্ণ ঘটনা ভুলে যান?',
  L10nKeys.screenQ06: 'তাদের কি সঠিক শব্দ খুঁজতে সমস্যা হয়?',
  L10nKeys.screenQ07: 'তারা কি কোথায় আছেন তা নিয়ে বিভ্রান্ত হন?',
  L10nKeys.screenQ08: 'তাদের কি দৈনন্দিন কাজের জন্য মনে করিয়ে দেওয়া লাগে?',
  L10nKeys.screenQ09: 'তাদের কি ওষুধ সামলাতে সমস্যা হয়?',
  L10nKeys.screenQ10: 'তারা কি বিভ্রান্ত হলে উদ্বিগ্ন বা বিরক্ত হন?',
  L10nKeys.screenQ11: 'তাদের কি কথোপকথন ধরতে সমস্যা হয়?',
  L10nKeys.screenQ12: 'তাদের কি পরিচিত কাজ শেষ করতে সমস্যা হয়?',
  L10nKeys.screenQ13: 'তারা কি ভুলে যান দৈনন্দিন জিনিস কোথায় রাখা হয়?',
  L10nKeys.screenQ14: 'তাদের কি নির্দেশ মনে রাখতে সমস্যা হয়?',
  L10nKeys.screenQ15: 'তাদের কি বহু-ধাপের কাজ করতে সমস্যা হয়?',

  L10nKeys.careDashboardSubtitle: 'পরিবারের যত্ন',
  L10nKeys.careSosLive: 'লাইভ সতর্কতা',
  L10nKeys.careSosRespondedBy: '{name} উত্তর দিয়েছেন',
  L10nKeys.careLinkTitle: 'পরিবারের সদস্যের সাথে সংযোগ করুন',
  L10nKeys.careLinkBody: 'আপনার প্রিয়জনকে তাদের ফোনে দেখানো ৬-অক্ষরের পারিবারিক কোডটি জিজ্ঞাসা করুন, তারপর সংযোগ করুন।',
  L10nKeys.careLinkCode: 'পারিবারিক কোড',
  L10nKeys.careLinkCodeHint: 'যেমন A1B2C3',
  L10nKeys.careLinkConnect: 'সংযোগ',
  L10nKeys.careLinkDone: 'সংযুক্ত হয়েছে',
  L10nKeys.careLinkSuccess:
      '{name} এর সাথে সংযুক্ত! স্মৃতি এবং সতর্কতা এখন সিঙ্ক হবে।',
  L10nKeys.careLinkFailed:
      'সংযোগ করা যায়নি। দয়া করে কোডটি পরীক্ষা করে আবার চেষ্টা করুন।',
  L10nKeys.careTrendsTitle: 'AI প্রবণতা',
  L10nKeys.careTrendsBody: 'কাজের ধরন অনুযায়ী দৈনিক নির্ভুলতা',
  L10nKeys.careTrendsNoData:
      'এখনও কোনো কাজ নেই — প্রবণতা দেখতে একটি অনুশীলন সম্পূর্ণ করুন।',
  L10nKeys.careAiDifficulty: 'স্বয়ংক্রিয় সমন্বয়কৃত অসুবিধা',
  L10nKeys.careAiAccuracy: 'মডেলের নির্ভুলতা',
  L10nKeys.careAiRealSessions: 'প্রকৃত সেশন',
  L10nKeys.careAiDemoSessions: 'ডেমো সেশন',
  L10nKeys.careNavGames: 'গেম',
  L10nKeys.careNavRoutine: 'রুটিন',
  L10nKeys.careGreetSubtitle: 'এখানে দেখুন আজ {name} কেমন আছেন।',
  L10nKeys.careNotifEmpty: 'কোনো নতুন বিজ্ঞপ্তি নেই',
  L10nKeys.careWellnessScore: 'জ্ঞানগত সুস্থতা স্কোর',
  L10nKeys.careStatusStable: 'স্থিতিশীল',
  L10nKeys.careStatusAttention: 'মনোযোগ প্রয়োজন',
  L10nKeys.careLastSynced: 'সর্বশেষ সিঙ্ক {time}',
  L10nKeys.careMinAgo: '{n} মিনিট আগে',
  L10nKeys.careGamesWeek: 'এই সপ্তাহের গেম',
  L10nKeys.careRoutineCompletion: 'রুটিন সম্পন্ন',
  L10nKeys.careCurrentStreak: 'বর্তমান স্ট্রিক',
  L10nKeys.careMoodCheckins: 'মুড চেক-ইন',
  L10nKeys.careDayUnit: 'দিন',
  L10nKeys.careDaysUnit: 'দিন',
  L10nKeys.careActivityTitle: 'সাপ্তাহিক কার্যকলাপ',
  L10nKeys.careWeekly: 'সাপ্তাহিক',
  L10nKeys.careMonthly: 'মাসিক',
  L10nKeys.careNoActivityWeek:
      'এই সপ্তাহে এখনও কোনো কার্যকলাপ রেকর্ড করা হয়নি।',
  L10nKeys.careMoodTitle: 'মুড',
  L10nKeys.careMoodHappy: 'খুশি',
  L10nKeys.careMoodCalm: 'শান্ত',
  L10nKeys.careMoodNeutral: 'নিরপেক্ষ',
  L10nKeys.careMoodLow: 'নিম্ন',
  L10nKeys.careMood7Days: 'গত ৭ দিন',
  L10nKeys.careMoodInsight: '{name} এই সপ্তাহে বেশিরভাগ সময় শান্ত ছিলেন, গত দুই দিনে সামান্য হ্রাস পাওয়া গেছে।',
  L10nKeys.careMoodNoData: 'এই সপ্তাহে এখনও কোনো মুড চেক-ইন নেই।',
  L10nKeys.careSkillsTitle: 'জ্ঞানগত দক্ষতা',
  L10nKeys.careSkillMemory: 'স্মৃতিশক্তি',
  L10nKeys.careSkillAttention: 'মনোযোগ',
  L10nKeys.careSkillLanguage: 'ভাষা',
  L10nKeys.careSkillReasoning: 'যুক্তি',
  L10nKeys.careSkillProcessing: 'প্রক্রিয়াকরণ গতি',
  L10nKeys.careInsightToday: 'আজকের অন্তর্দৃষ্টি',
  L10nKeys.careInsightBody: 'রবার্ট সকালের রুটিনের পরে স্মৃতিশক্তি কার্যকলাপে ধারাবাহিক ছিলেন। গত দুই দিনে তার মুড কিছুটা নিম্নে ছিল।',
  L10nKeys.careInsightBodyReal: 'এই সপ্তাহে {name} {count}টি জ্ঞানগত সেশন সম্পন্ন করেছেন (লক্ষ্য {goal}) এবং {streak} দিনের স্ট্রিক বজায় রেখেছেন।',
  L10nKeys.careViewDetails: 'বিস্তারিত দেখুন',
  L10nKeys.careInsightDisclaimer:
      'এটি ডেটা থেকে একটি সৌম্য পর্যবেক্ষণ — চিকিৎসা নির্ণয় নয়।',
  L10nKeys.careAttentionTitle: 'আপনার মনোযোগ প্রয়োজন',
  L10nKeys.careAttentionEmpty: 'আপাতত আপনার মনোযোগের প্রয়োজন এমন কিছু নেই।',
  L10nKeys.careAlertSos: '{name} SOS বোতাম টিপেছেন',
  L10nKeys.careAlertRoutineMissed: 'গতকাল রুটিন মিস হয়েছে',
  L10nKeys.careAlertMoodDown: 'গত দুই দিনে মুড কমেছে',
  L10nKeys.careAlertSessionPending: 'আজ জ্ঞানগত সেশন সম্পন্ন হয়নি',
  L10nKeys.careAlertSeverityHigh: 'উচ্চ',
  L10nKeys.careAlertSeverityMedium: 'মাঝারি',
  L10nKeys.careAlertSeverityLow: 'নিম্ন',
  L10nKeys.careWeeklySummary: 'সাপ্তাহিক সারাংশ',
  L10nKeys.careSessionsCompleted: 'সম্পন্ন সেশন',
  L10nKeys.careAvgSessionDuration: 'গড় সেশন সময়কাল',
  L10nKeys.careRoutineAdherence: 'রুটিন অনুসরণ',
  L10nKeys.careMoodTrend: 'মুড প্রবণতা',
  L10nKeys.careMoodTrendSlightlyDown: 'সামান্য নিম্ন',
  L10nKeys.careMoodTrendStable: 'স্থিতিশীল',
  L10nKeys.careMoodTrendUp: 'উন্নতি হচ্ছে',
  L10nKeys.careVsLastWeek: 'গত সপ্তাহের তুলনায়',
  L10nKeys.careSyncedJustNow: 'এইমাত্র সিঙ্ক হয়েছে',
  L10nKeys.careOfflineWaiting: 'অফলাইন · {count}টি কার্যকলাপ সিঙ্কের অপেক্ষায়',
  L10nKeys.careComingSoon: 'শীঘ্রই আসছে',
  L10nKeys.careHomeSoon:
      '{name}-এর দিনের একটি দ্রুত সারসংক্ষেপ এখানে দেখা যাবে।',
  L10nKeys.careGamesSoon: 'গেম এবং সেশন ইতিহাস এখানে দেখা যাবে।',
  L10nKeys.careRoutineSoon: 'রোগীর দৈনিক রুটিন এখানে দেখা যাবে।',
  L10nKeys.careProfileSoon:
      'পরিচর্যাকারীর প্রোফাইল এবং সেটিংস এখানে দেখা যাবে।',
  L10nKeys.serverPairingTitle: 'পারিবারিক কোড',
  L10nKeys.serverPairingBody: 'এই কোডটি কোনো পরিচর্যাকারীর সাথে শেয়ার করুন যাতে তারা আপনার সাথে সংযোগ করতে পারে।',
  L10nKeys.serverUnlinked: 'সার্ভারের সাথে সংযুক্ত নয়',
  L10nKeys.serverLinked: 'সার্ভারের সাথে সংযুক্ত',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
