import '../l10n_keys.dart';

/// Nepali dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsNe = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'तपाईंको सम्झनाको साथी',
  L10nKeys.back: 'पछाडि',
  L10nKeys.next: 'अगाडि',
  L10nKeys.continueText: 'अगाडि जानुहोस्',
  L10nKeys.skip: 'छोड्नुहोस्',
  L10nKeys.done: 'सकियो',
  L10nKeys.cancel: 'रद्द गर्नुहोस्',
  L10nKeys.yes: 'हो',
  L10nKeys.no: 'होइन',
  L10nKeys.save: 'सुरक्षित गर्नुहोस्',
  L10nKeys.close: 'बन्द गर्नुहोस्',
  L10nKeys.retry: 'फेरि प्रयास गर्नुहोस्',
  L10nKeys.add: 'थप्नुहोस्',
  L10nKeys.edit: 'सम्पादन गर्नुहोस्',
  L10nKeys.remove: 'हटाउनुहोस्',
  L10nKeys.search: 'खोज्नुहोस्',
  L10nKeys.today: 'आज',
  L10nKeys.offline: 'अफलाइन',
  L10nKeys.online: 'अनलाइन',

  L10nKeys.goodMorning: 'शुभ प्रभात',
  L10nKeys.goodAfternoon: 'नमस्ते',
  L10nKeys.goodEvening: 'शुभ साँझ',
  L10nKeys.goodNight: 'शुभ रात्री',

  L10nKeys.navHome: 'गृह',
  L10nKeys.navGarden: 'बगैचा',
  L10nKeys.navActivities: 'क्रियाकलाप',
  L10nKeys.navMemories: 'सम्झनाहरू',
  L10nKeys.navProfile: 'प्रोफाइल',
  L10nKeys.navMystery: 'आजको सम्झना',

  L10nKeys.onboardingWelcomeTitle: 'तपाईंको सम्झनाको कोमल साथी',
  L10nKeys.onboardingWelcomeBody: 'माइन्डकेयर एनईआरले इन्टरनेट बिना नै सम्झन, खेल्न र परिवारसँग जोडिएर रहन मद्दत गर्छ।',
  L10nKeys.onboardingNameTitle: 'हामीले तपाईंलाई के भनेर बोलाऔं?',
  L10nKeys.onboardingNameHint: 'तपाईंको नाम',
  L10nKeys.onboardingRegionTitle: 'तपाईंको घर कहाँ छ?',
  L10nKeys.onboardingRegionHint: 'सहर वा गाउँ',
  L10nKeys.onboardingRegionList: 'गुवाहाटी, सिल्चर, शिलोङ, अगरतला, इम्फाल, आइजोल, इटानगर, कोहिमा, गान्तोक, डिब्रुगढ, जोरहाट, तपाईंको सहर',
  L10nKeys.onboardingLanguageTitle: 'तपाईंलाई कुन भाषा मन पर्ला?',
  L10nKeys.onboardingLanguageBody:
      'तपाईं यो जहिले पनि परिवर्तन गर्न सक्नुहुन्छ।',
  L10nKeys.onboardingFamilyTitle: 'परिवार को?',
  L10nKeys.onboardingFamilyBody: 'आफ्ना मनपर्ने मानिसहरूलाई जोड्नुहोस्। हामी उनीहरूका फोटो र आवाज कोमल सम्झनाका रूपमा देखाउनेछौं।',
  L10nKeys.onboardingAddFamily: 'परिवार सदस्य थप्नुहोस्',
  L10nKeys.onboardingEmergencyTitle: 'आपत्कालमा हामी कसलाई बोलाऔं?',
  L10nKeys.onboardingEmergencyBody: 'SOS बटन थिच्दा माइन्डकेयरले तपाईंको परिवारलाई खबर गर्छ, आपत्काल सेवालाई होइन।',
  L10nKeys.onboardingEmergencyName: 'नाम',
  L10nKeys.onboardingEmergencyPhone: 'फोन नम्बर',
  L10nKeys.onboardingEmergencyRelation: 'नाता (छोरी, छोरा…)',
  L10nKeys.onboardingDoneTitle: 'तपाईंको बगैचा तयार छ!',
  L10nKeys.onboardingDoneBody: 'साना क्रियाकलाप पूरा गर्नुहोस् र बगैचा बढेको हेर्नुहोस्। हामी तपाईंको साथमा छौं।',
  L10nKeys.onboardingStart: 'मेरो बगैचा सुरु गर्नुहोस्',

  L10nKeys.homeWhatsGrowing: 'आज के बढ्दै छ?',
  L10nKeys.homeTodayActivity: 'आजको सानो क्रियाकलाप',
  L10nKeys.homeActivityDuration: 'लगभग ३ मिनेट',
  L10nKeys.homeMinutes: 'मिनेट',
  L10nKeys.homeMemoryOfDay: 'आजको सम्झना',
  L10nKeys.homeMemoryLocked: 'एउटा विशेष सम्झना पर्खँदै छ…',
  L10nKeys.homeMemoryUnlocked: 'एउटा सम्झना खुल्यो!',
  L10nKeys.homeContinueActivity: 'क्रियाकलाप जारी राख्नुहोस्',
  L10nKeys.homeFamilyMemory: 'तपाईंको परिवारबाट',
  L10nKeys.homeFamilyMemoryEmpty: 'परिवारका सम्झनाहरू यहाँ देखिन सक्छन्।',
  L10nKeys.homeSos: 'मद्दत चाहिन्छ',
  L10nKeys.homeSosSubtitle: 'आपत्कालमा परिवारसँग सम्पर्क',
  L10nKeys.homeGardenPreview: 'तपाईंको बगैचा',
  L10nKeys.homeEngine: 'माइन्डकेयर साथी',
  L10nKeys.homeEngineReady: 'तपाईंको सहायक तयार छ।',
  L10nKeys.homeWelcomeBack: 'पुनः स्वागत! बगैचा अगाडि बढाऔं। 🌸',
  L10nKeys.homeNoActivity: 'आज कुनै क्रियाकलाप छैन',
  L10nKeys.homeNoActivityBody:
      'थोरै आराम गर्नुहोस् — वा मनपर्ने क्रियाकलाप छान्नुहोस्। 🌻',

  L10nKeys.gardenTitle: 'मेरो सम्झना बगैचा',
  L10nKeys.gardenSectionAll: 'सबै',
  L10nKeys.gardenSectionFamily: 'परिवार',
  L10nKeys.gardenSectionChildhood: 'बाल्यकाल',
  L10nKeys.gardenSectionPlaces: 'स्थानहरू',
  L10nKeys.gardenSectionFestivals: 'चाडपर्व',
  L10nKeys.gardenEmpty: 'तपाईंको बगैचा भर्खरै सुरु भयो',
  L10nKeys.gardenEmptyBody:
      'पहिलो क्रियाकलाप पूरा गर्नुहोस्, यहाँ एउटा बीउ रोपिनेछ।',
  L10nKeys.gardenPoints: 'अंक',
  L10nKeys.gardenLevel: 'तह',
  L10nKeys.gardenSeed: 'बीउ',
  L10nKeys.gardenPlant: 'बिरुवा',
  L10nKeys.gardenFlower: 'फूल',
  L10nKeys.gardenTree: 'रूख',
  L10nKeys.gardenMilestone: 'कोसेढुङ्गा',
  L10nKeys.gardenGrowth: 'बढ्दै छ',
  L10nKeys.gardenDidYouKnow:
      'हरेक पूरा हुने क्रियाकलापले तपाईंको बगैचा बढाउँछ।',
  L10nKeys.gardenPlantSeed: 'बीउ रोप्नुहोस्',

  L10nKeys.activitiesTitle: 'क्रियाकलाप',
  L10nKeys.activitiesToday: 'आज',
  L10nKeys.activitiesLibrary: 'थप क्रियाकलाप',
  L10nKeys.mainGamesTitle: 'मुख्य खेलहरू',
  L10nKeys.activitiesStart: 'सुरु गर्नुहोस्',
  L10nKeys.activitiesCompleted: 'पूरा भयो',
  L10nKeys.activitiesInProgress: 'चलिरहेको',
  L10nKeys.activitiesNotStarted: 'तयार',
  L10nKeys.activityYoureDone: 'गजब!',
  L10nKeys.activityPraise: 'तपाईंले बगैचामा थोरै जीवन दिनुभयो। 🌱',
  L10nKeys.activityHint: 'सङ्केत चाहिन्छ?',
  L10nKeys.activityTryAgain: 'यो सम्झना फेरि हेरौं',
  L10nKeys.activityOptionsHint: 'आफ्नो उत्तर चुन्नुहोस्',
  L10nKeys.activityTapToMatch: 'सँगै मिल्ने जोडी चुन्नुहोस्',
  L10nKeys.activityNext: 'अगाडि',
  L10nKeys.activityFinish: 'सक्नुहोस्',
  L10nKeys.activityGroupLetsAgain: 'यो फेरि हेरौं',
  L10nKeys.activityGroupTogether: 'यो सँगै गरौं',
  L10nKeys.activityGreatJob: 'राम्रो गर्नुभयो!',
  L10nKeys.activityKitchen: 'मेरो भान्सा',
  L10nKeys.activityShopping: 'मेरो पसल',
  L10nKeys.activityMatching: 'जोडा मिलाउनुहोस्',
  L10nKeys.activitySequence: 'क्रममा लगाउनुहोस्',
  L10nKeys.activityRecognition: 'यो के हो?',
  L10nKeys.activityAssociation: 'के सँगै जान्छ?',
  L10nKeys.activityRecall: 'याद छ?',
  L10nKeys.activityAttention: 'खोज्नुहोस्',
  L10nKeys.activityDurationSuffix: 'मिनेट',
  L10nKeys.activityTodayDone: 'आजको क्रियाकलाप पूरा भयो',
  L10nKeys.activityTodayDoneBody:
      'तपाईंको बगैचा बढ्यो। भोलि एउटा सम्झना पर्खिरहने छ।',
  L10nKeys.activityGardenGrew: 'तपाईंको बगैचा बढ्यो!',
  L10nKeys.activityMemoryUnlocked: 'एउटा सम्झना खुल्यो',
  L10nKeys.activityReadAloud: 'ठूलो स्वरमा पढ्नुहोस्',

  L10nKeys.kitchenTitle: 'चिया बनाऔं',
  L10nKeys.kitchenMakeChai: 'चिया बनाउने',
  L10nKeys.kitchenMakeChaiPrompt: 'चरणहरू सही क्रममा चुन्नुहोस्।',
  L10nKeys.kitchenSteps: 'चरणहरू',
  L10nKeys.kitchenTapInOrder: 'चरणहरू सही क्रममा चुन्नुहोस्',
  L10nKeys.kitchenCorrectOrder: 'उत्तम! चिया तयार!',
  L10nKeys.kitchenBreakfast: 'नास्ता बनाउने',
  L10nKeys.kitchenBreakfastHint: 'दिनको ताजा सुरुवात',
  L10nKeys.kitchenBreakfastPrompt: 'नास्ताका चरणहरू क्रममा लगाउनुहोस्।',

  L10nKeys.shopTitle: 'मेरो पसल',
  L10nKeys.shopGetMilkBread: 'ब्रेड र दूध',
  L10nKeys.shopGetMilkBreadPrompt: '₹१०० मा दूध र ब्रेड किन्नुहोस्।',
  L10nKeys.shopBudget: 'बजेट',
  L10nKeys.shopBasket: 'तपाईंको टोकरी',
  L10nKeys.shopTotal: 'जम्मा',
  L10nKeys.shopWithinBudget: 'बजेटभित्र!',
  L10nKeys.shopOverBudget: 'बजेटभन्दा बढी — फेरि हेर्नुहोस्',
  L10nKeys.shopCheckout: 'पूरा गरी भुक्तान गर्नुहोस्',
  L10nKeys.shopBuy: 'टोकरीमा राख्नुहोस्',
  L10nKeys.shopSell: 'निकाल्नुहोस्',
  L10nKeys.shopVeggies: 'रातको खानाका लागि तरकारी',
  L10nKeys.shopVeggiesPrompt: '₹६० मा आलु र प्याज किन्नुहोस्।',
  L10nKeys.recKitchenItem: 'यो कुन हो?',
  L10nKeys.recKitchenItemPrompt:
      'बजारबाट सामान ल्याउन यीमध्ये कुन प्रयोग हुन्छ?',
  L10nKeys.recCurrency: 'थोरै पैसा',
  L10nKeys.recCurrencyPrompt: 'कुन नोट ₹२० हो?',
  L10nKeys.matchFestival: 'चाड मिलाउनुहोस्',
  L10nKeys.matchFestivalPrompt: 'हरेक चाडलाई उसको विशेष परिकारसँग मिलाउनुहोस्।',
  L10nKeys.matchObjectUse: 'जोडा मिलाउनुहोस्',
  L10nKeys.matchObjectUsePrompt:
      'हरेक वस्तुलाई प्रयोग हुने समयसँग मिलाउनुहोस्।',
  L10nKeys.seqMorning: 'बिहानको दिनचर्या',
  L10nKeys.seqMorningPrompt: 'आफ्नो बिहानको दिनचर्या क्रममा लगाउनुहोस्।',
  L10nKeys.seqRoute: 'बिहानको यात्रा',
  L10nKeys.seqRoutePrompt: 'बजारसम्मको यात्रा क्रममा लगाउनुहोस्।',
  L10nKeys.assoRegion: 'यहाँ के छ?',
  L10nKeys.assoRegionPrompt: 'आसाम केको लागि प्रसिद्ध छ?',
  L10nKeys.assoHarvest: 'गुलियो फल',
  L10nKeys.assoHarvestPrompt: 'कुन फललाई गर्मीको राजा भनिन्छ?',
  L10nKeys.attnVeg: 'गाजर खोज्नुहोस्',
  L10nKeys.attnVegPrompt: 'के तपाईं गाजर भेट्टाउन सक्नुहुन्छ?',
  L10nKeys.recallSong: 'एउटा चिनजानको गीत',
  L10nKeys.recallSongPrompt: 'बिहूमा नाच्दा कुन गीत बज्छ?',
  L10nKeys.activityPairs: 'जोडी पत्ता लगाउनुहोस्',
  L10nKeys.activitySequenceRecall: 'क्रम सम्झनुहोस्',
  L10nKeys.activityFindChanged: 'के फेरियो?',
  L10nKeys.pairsFruits: 'बजारका फलफूल',
  L10nKeys.pairsKitchen: 'भान्साका सामान',
  L10nKeys.pairsRemember:
      'सबै कार्ड ध्यान दिएर हेर्नुहोस्, अनि उस्तै जोडी खोज्नुहोस्।',
  L10nKeys.pairsStart: 'कार्ड लुकाएर सुरु गर्नुहोस्',
  L10nKeys.pairsFound: 'जोडी भेटियो!',
  L10nKeys.seqRecallItems: 'दैनिक सामान',
  L10nKeys.seqRecallNumbers: 'क्रममा अंकहरू',
  L10nKeys.seqRecallWatch:
      'कार्डहरू ध्यान दिएर हेर्नुहोस् – हरेक क्रमैसँग बल्छ।',
  L10nKeys.seqRecallRepeat: 'अब देखेकै क्रममा कार्डहरू दबाउनुहोस्।',
  L10nKeys.changeMarket: 'फलफूलको टोकरी',
  L10nKeys.changeFestival: 'चाडपर्वका बत्ती',
  L10nKeys.changeRemember: 'यी चित्रहरू ध्यान दिएर सम्झनुहोस्।',
  L10nKeys.changeFind: 'एउटा चित्र फेरिएको छ। फरक चित्र खोज्नुहोस्।',
  L10nKeys.changeCorrect: 'राम्रो! त्यही नै फेरिएको थियो।',

  L10nKeys.mysteryTitle: 'आजको विशेष सम्झना',
  L10nKeys.mysteryLocked: 'एउटा विशेष सम्झना तपाईंलाई पर्खँदै छ…',
  L10nKeys.mysteryLockedBody:
      'आज २–३ साना क्रियाकलाप गर्नुहोस्; सायद त्यो खुल्नेछ। के होला?',
  L10nKeys.mysteryUnlocked: 'तपाईंको विशेष सम्झना यहाँ छ!',
  L10nKeys.mysteryUnlockedBody: 'यो सम्झना केवल तपाईंकै हो। समय लिनुहोस्। 🌸',
  L10nKeys.mysteryCuriosity: 'आज के खुल्नेछ?',
  L10nKeys.mysteryOpen: 'सम्झना खोल्नुहोस्',

  L10nKeys.memoriesTitle: 'मेरा सम्झनाहरू',
  L10nKeys.memoriesEmpty: 'अहिलेसम्म कुनै सम्झना छैन',
  L10nKeys.memoriesEmptyBody: 'तपाईंको परिवारले फोटो र आवाज सन्देश थप्न सक्छ। आउनेबित्तिकै यहाँ देखिनेछ।',
  L10nKeys.memoriesFamily: 'परिवार',
  L10nKeys.memoriesPlaces: 'स्थानहरू',
  L10nKeys.memoriesFestivals: 'चाडपर्व',
  L10nKeys.memoriesChildhood: 'बाल्यकाल',
  L10nKeys.memoriesKindPhoto: 'फोटो',
  L10nKeys.memoriesKindVoice: 'आवाज सन्देश',
  L10nKeys.memoriesKindText: 'कथा',
  L10nKeys.memoriesKindSound: 'ध्वनि',
  L10nKeys.memoriesKindPlace: 'स्थान',
  L10nKeys.memoriesAddedBy: 'थप्ने',
  L10nKeys.memoriesWhoIsThis: 'यी को हुन्?',
  L10nKeys.memoriesPlayVoice: 'सुन्नुहोस्',
  L10nKeys.memoriesThisIsMe: 'यही म हुँ',
  L10nKeys.memoriesNotMe: 'म होइन',

  L10nKeys.profileTitle: 'प्रोफाइल',
  L10nKeys.profileLanguage: 'एपको भाषा',
  L10nKeys.profileRegion: 'मेरो क्षेत्र',
  L10nKeys.profileVoiceLanguage: 'आवाजको भाषा',
  L10nKeys.profileVoicePrompts: 'बोलिने सङ्केत',
  L10nKeys.profileTextSize: 'अक्षरको आकार',
  L10nKeys.profileReducedMotion: 'शान्त गति',
  L10nKeys.profileSoundEffects: 'ध्वनि प्रभाव',
  L10nKeys.profileFamily: 'परिवार',
  L10nKeys.profileContacts: 'आपत्काल सम्पर्क',
  L10nKeys.profileDemoMode: 'डेमो मोड',
  L10nKeys.profileReminders: 'सम्झाउने सूचना',
  L10nKeys.profileNeedHelp: 'मद्दत चाहिन्छ?',

  L10nKeys.remindersTitle: 'सम्झाउने सूचना',
  L10nKeys.remindersEmpty: 'अहिलेसम्म कुनै सम्झाउने सूचना छैन',
  L10nKeys.remindersNew: 'नयाँ सम्झाउने सूचना',
  L10nKeys.remindersTitleLabel: 'शीर्षक',
  L10nKeys.remindersDetailLabel: 'विवरण (वैकल्पिक)',
  L10nKeys.remindersTime: 'समय',
  L10nKeys.remindersDays: 'दिनहरू',
  L10nKeys.remindersEveryday: 'दैनिक',
  L10nKeys.remindersEnabled: 'सक्रिय',
  L10nKeys.remindersMedicine: 'औषधि',
  L10nKeys.remindersAppointment: 'भेट',
  L10nKeys.remindersRoutine: 'दैनिक दिनचर्या',

  L10nKeys.dayMon: 'सोम',
  L10nKeys.dayTue: 'मङ्गल',
  L10nKeys.dayWed: 'बुध',
  L10nKeys.dayThu: 'बिही',
  L10nKeys.dayFri: 'शुक्र',
  L10nKeys.daySat: 'शनि',
  L10nKeys.daySun: 'आइत',

  L10nKeys.sosTitle: 'आपत्काल मद्दत',
  L10nKeys.sosExplain: 'थिचेर समात्नुहोस्। माइन्डकेयरले तपाईंका आपत्काल सम्पर्कहरूलाई एकपछि अर्को गरी खबर गर्नेछ। यो आपत्काल सेवा (जस्तै ११२) होइन।',
  L10nKeys.sosHold: 'मद्दतका लागि थिचेर समात्नुहोस्',
  L10nKeys.sosHoldBody: 'थिचेर समात्नुहोस्…',
  L10nKeys.sosActiveTitle: 'मद्दतसँग सम्पर्क गर्दै',
  L10nKeys.sosActiveBody: 'तपाईंको परिवारलाई खबर गरियो। उनीहरूले जवाफ नदिए अर्को सम्पर्कलाई बोलाइनेछ।',
  L10nKeys.sosContacting: 'सम्पर्क गर्दै छ',
  L10nKeys.sosContactFamily: 'परिवारसँग सम्पर्क',
  L10nKeys.sosContacted: 'सम्पर्क भयो',
  L10nKeys.sosWaitingResponse: 'जवाफको पर्खाइ…',
  L10nKeys.sosEscalating: 'अर्को व्यक्तिसँग सम्पर्क…',
  L10nKeys.sosCancelled: 'मद्दत अनुरोध रद्द भयो',
  L10nKeys.sosCancelAction: 'मद्दत अनुरोध रद्द गर्नुहोस्',
  L10nKeys.sosDone: 'सकियो',
  L10nKeys.sosHelpOnWay: 'चाँडै कोही तपाईंको साथमा हुनेछ। 🧡',
  L10nKeys.sosNoContacts: 'अहिलेसम्म कुनै आपत्काल सम्पर्क छैन',
  L10nKeys.sosNoContactsBody: 'कृपया परिवारलाई आपत्काल सम्पर्क थप्न भन्नुहोस्।',
  L10nKeys.sosAddContact: 'सम्पर्क थप्नुहोस्',
  L10nKeys.sosDisclaimer: 'माइन्डकेयरले तपाईंले छानेका सम्पर्कहरूलाई खबर गर्छ। यो आधिकारिक आपत्काल सेवाको विकल्प होइन।',
  L10nKeys.sosContactedPerson: 'परिवार सदस्यसँग सम्पर्क भयो',
  L10nKeys.sosEscalatedTo: 'अर्को परिवार सदस्यसँग सम्पर्क भयो',
  L10nKeys.sosAcknowledged: 'परिवार सदस्यले जवाफ दिनुभयो। मद्दत आउँदै छ।',
  L10nKeys.sosNotSilent: 'मद्दत पठाउन नसके हामी कहिल्यै दाबी गर्दैनौं।',
  L10nKeys.sosAlertNotDelivered:
      'तपाईंको सन्देश अहिलेसम्म पठाउन सकिएन। हामी प्रयास गरिरहने छौं।',

  L10nKeys.careTitle: 'हेरचाहकर्ता',
  L10nKeys.careDashboard: 'सारांश',
  L10nKeys.carePatients: 'मेरा बिरामीहरू',
  L10nKeys.careMemories: 'सम्झनाहरू',
  L10nKeys.careContacts: 'आपत्काल सम्पर्क',
  L10nKeys.careSettings: 'सेटिङहरू',
  L10nKeys.careAddMemory: 'सम्झना थप्नुहोस्',
  L10nKeys.careAddContact: 'सम्पर्क थप्नुहोस्',
  L10nKeys.careEngagement: 'सहभागिता',
  L10nKeys.careActivitiesWeek: 'यस हप्ताका क्रियाकलाप',
  L10nKeys.careGardenProgress: 'बगैचाको प्रगति',
  L10nKeys.careRecentActivity: 'हालको क्रियाकलाप',
  L10nKeys.careNoPatients: 'कुनै बिरामी जोडिएका छैनन्',
  L10nKeys.careNoPatientsBody:
      'परिवार सदस्य जोड्न भन्नुहोस्, वा बिरामी प्रोफाइल थप्नुहोस्।',
  L10nKeys.careAddPatient: 'बिरामी थप्नुहोस्',
  L10nKeys.carePerformanceNote:
      'हालै यस व्यक्तिको क्रियाकलाप क्षमता तिनको सामान्य स्तरभन्दा थोरै कम छ।',
  L10nKeys.careUploadPhoto: 'फोटो अपलोड गर्नुहोस्',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'आवाज रेकर्ड गर्नुहोस्',
  L10nKeys.careWriteMemory: 'सम्झना लेख्नुहोस्',
  L10nKeys.careMemoryTitle: 'शीर्षक',
  L10nKeys.careMemoryCaption: 'क्याप्सन',
  L10nKeys.careMemoryRelation: 'यसमा को छन्? (नाता)',
  L10nKeys.careMemoryCategory: 'वर्ग',
  L10nKeys.careContactName: 'नाम',
  L10nKeys.careContactPhone: 'फोन नम्बर',
  L10nKeys.careContactPriority: 'कल क्रम',
  L10nKeys.careContactRelation: 'नाता',
  L10nKeys.careEscalationTimeout: 'अर्को सम्पर्कभन्दा अघिका मिनेट',
  L10nKeys.careIncidentStatus: 'स्थिति',
  L10nKeys.careAckSos: 'म जवाफ दिँदै छु',
  L10nKeys.careResponding: 'जवाफ दिँदै',
  L10nKeys.careActiveAlerts: 'सक्रिय चेतावनी',

  L10nKeys.syncSavingOffline: 'अफलाइन',
  L10nKeys.syncSavingOfflineBody: 'तपाईंका क्रियाकलाप यस उपकरणमा सुरक्षित छन्।',
  L10nKeys.syncSynced: 'सिंक भयो',
  L10nKeys.syncInfo: 'तपाईंको जानकारी सिंक भयो।',
  L10nKeys.syncPending: 'सिंकको पर्खाइ',

  L10nKeys.errorGeneric: 'केही गलत भयो',
  L10nKeys.errorGenericBody:
      'तपाईंको प्रगति सुरक्षित छ। कृपया फेरि प्रयास गर्नुहोस्।',
  L10nKeys.errorAudio: 'यस उपकरणमा आवाज चलाउन सकिएन।',
  L10nKeys.errorPermission: 'यसका लागि उपकरणको अनुमति आवश्यक छ।',
  L10nKeys.errorNoInternetAction:
      'इन्टरनेट आवश्यक छैन — यो पहिले यहीँ सुरक्षित हुन्छ।',

  L10nKeys.demoWelcome: 'डेमो हेर्नुहोस्',
  L10nKeys.demoExplain:
      'तपाईंले देख्न सक भनि नमुना परिवार र सम्झनाहरू थपिनेछन्।',
  L10nKeys.demoLoad: 'डेमो बगैचा लोड गर्नुहोस्',

  L10nKeys.unitsPoints: 'अंक',
  L10nKeys.teaserChai: 'चिया बनाऔं।',
  L10nKeys.familiarityName: 'आशा',
  L10nKeys.regionMap: 'मेरो क्षेत्र',
  L10nKeys.regionChoose: 'आफ्नो क्षेत्र चुन्नुहोस्',
  L10nKeys.regionIndia: 'भारत',
  L10nKeys.importantMemory: 'महत्त्वपूर्ण सम्झना',
  L10nKeys.growing: 'बढ्दै छ',
  L10nKeys.blooming: 'फुल्दै छ',
  L10nKeys.mature: 'परिपक्व',
  L10nKeys.noVoice: 'यस उपकरणमा आवाज उपलब्ध छैन।',
  L10nKeys.optional: 'वैकल्पिक',

  L10nKeys.langChoose: 'भाषा चुन्नुहोस्',
  L10nKeys.langPrimary: 'मुख्य',
  L10nKeys.langNorthEast: 'उत्तर-पूर्व भारत',
  L10nKeys.langMajor: 'भारतका प्रमुख भाषाहरू',

  L10nKeys.authSignUpTitle: 'आफ्नो खाता सिर्जना गर्नुहोस्',
  L10nKeys.authSignUpBody: 'यो माइन्डकेयर प्रोफाइल तपाईंकै उपकरणमा सुरक्षित रहन्छ। तपाईं मात्र खोल्न सक्नुहुन्छ भनि प्रयोगकर्ता नाम र पासवर्ड राख्नुहोस्।',
  L10nKeys.authLoginTitle: 'पुनः स्वागत',
  L10nKeys.authLoginBody:
      'आफ्नो बगैचा खोल्न प्रयोगकर्ता नाम र पासवर्डले साइन इन गर्नुहोस्।',
  L10nKeys.authUsername: 'प्रयोगकर्ता नाम',
  L10nKeys.authUsernameHint: 'जस्तै: ranu123',
  L10nKeys.authDisplayName: 'तपाईंको नाम',
  L10nKeys.authPassword: 'पासवर्ड',
  L10nKeys.authPasswordHint: 'कम्तीमा ६ अक्षर',
  L10nKeys.authConfirmPassword: 'पासवर्ड पुष्टि गर्नुहोस्',
  L10nKeys.authRoleQuestion: 'यो प्रोफाइल कसको लागि…',
  L10nKeys.authRolePatient: 'मेरो लागि',
  L10nKeys.authRoleCaregiver: 'परिवार सदस्यको लागि',
  L10nKeys.authCreate: 'खाता सिर्जना गर्नुहोस्',
  L10nKeys.authSignIn: 'साइन इन',
  L10nKeys.authSignOut: 'साइन आउट',
  L10nKeys.authAccount: 'खाता',
  L10nKeys.caregiverTitle: 'हेरचाहकर्ता',
  L10nKeys.caregiverNotLinked: 'अहिलेसम्म कुनै हेरचाहकर्ता जोडिएको छैन',
  L10nKeys.authBadCredentials: 'प्रयोगकर्ता नाम वा पासवर्ड गलत छ।',
  L10nKeys.authUsernameTaken:
      'यो प्रयोगकर्ता नाम यस उपकरणमा पहिले नै प्रयोगमा छ।',
  L10nKeys.authPasswordMismatch: 'पासवर्ड मिलेन।',
  L10nKeys.authUsernameShort: 'प्रयोगकर्ता नाम कम्तीमा ३ अक्षरको हुनुपर्छ।',
  L10nKeys.authUsernameInvalid:
      'केवल अक्षर, अङ्क, डट, ड्यास वा अन्डरस्कोर प्रयोग गर्नुहोस्।',
  L10nKeys.authPasswordShort: 'पासवर्ड कम्तीमा ६ अक्षरको हुनुपर्छ।',
  L10nKeys.authNameRequired: 'कृपया नाम लेख्नुहोस्।',
  L10nKeys.authSignOutConfirm:
      'के तपाईं यस प्रोफाइलबाट साइन आउट गर्न चाहनुहुन्छ?',
  L10nKeys.screenTitle: 'द्रुत स्मृति जाँच',
  L10nKeys.screenIntro: 'हामी बिरामीको बारेमा केही छोटा प्रश्न सोध्नेछौं। विगत केही महिनामा उनीहरू कस्तो रहे भनेर सोच्नुहोस्।',
  L10nKeys.screenNotSure: 'थाहा छैन',
  L10nKeys.screenFinish: 'मेरो नतिजा हेर्नुहोस्',
  L10nKeys.screenSkip: 'अहिले छोड्नुहोस्',
  L10nKeys.screenResultBack: 'भयो',
  L10nKeys.screenCheckAgain: 'फेरि जाँच गर्नुहोस्',
  L10nKeys.screenStartCheckup: 'जाँच सुरु गर्नुहोस्',
  L10nKeys.screenSkipped: 'जाँच छोडियो',
  L10nKeys.screenStatusGood: 'सबै ठिक देखिन्छ',
  L10nKeys.screenStatusGoodBody: 'कुनै ठूलो चिन्ता देखिएन। दैनिक गतिविधिहरू गरिरहनुहोस्, र केही फेरिए भने कुनै पनि बेला फेरि जाँच गर्न सक्नुहुन्छ।',
  L10nKeys.screenStatusWatch: 'केही परिवर्तन देखियो',
  L10nKeys.screenStatusWatchBody: 'बिर्सने केही क्षण देखियो। यो उमेरसँग सामान्य हो, तर ध्यान राख्नुहोस् र अर्को डाक्टर भेटमा बताउनुहोस्।',
  L10nKeys.screenStatusDoctor: 'कृपया जाँच गराउनुहोस्',
  L10nKeys.screenStatusDoctorBody: 'केही संकेत देखिए जसमा ध्यान दिनुपर्ने हुन सक्छ। कृपया यी डाक्टर वा क्लिनिकलाई बताउनुहोस् ताकि उनीहरूले मद्दत गर्न सकुन्।',
  L10nKeys.screenRarely: 'विरलै',
  L10nKeys.screenSometimes: 'कहिलेकाहीँ',
  L10nKeys.screenFrequently: 'अक्सर',
  L10nKeys.screenVeryFrequently: 'धेरै पटक',
  L10nKeys.screenQ01: 'के उनीहरूलाई भर्खरका घटनाहरू सम्झन गाह्रो हुन्छ?',
  L10nKeys.screenQ02: 'के उनीहरू उही प्रश्न वा कथाहरू दोहोर्‍याउँछन्?',
  L10nKeys.screenQ03: 'के उनीहरू परिचित मानिसका नाम बिर्सन्छन्?',
  L10nKeys.screenQ04: 'के उनीहरूलाई परिचित अनुहार चिन्न गाह्रो हुन्छ?',
  L10nKeys.screenQ05: 'के उनीहरू भेटघाट वा महत्त्वपूर्ण घटनाहरू बिर्सन्छन्?',
  L10nKeys.screenQ06: 'के उनीहरूलाई सही शब्द भेट्टाउन गाह्रो हुन्छ?',
  L10nKeys.screenQ07: 'के उनीहरू आफू कहाँ छन् भनेर अलमलिन्छन्?',
  L10nKeys.screenQ08: 'के उनीहरूलाई दैनिक कामका लागि सम्झाउनुपर्छ?',
  L10nKeys.screenQ09: 'के उनीहरूलाई औषधि मिलाउन गाह्रो हुन्छ?',
  L10nKeys.screenQ10: 'के उनीहरू अलमलिएपछि चिन्तित वा रिसाउँछन्?',
  L10nKeys.screenQ11: 'के उनीहरूलाई कुराकानी बुझ्न गाह्रो हुन्छ?',
  L10nKeys.screenQ12: 'के उनीहरूलाई परिचित कामहरू सक्न गाह्रो हुन्छ?',
  L10nKeys.screenQ13: 'के उनीहरू दैनिक वस्तुहरू कहाँ राखिएको छ बिर्सन्छन्?',
  L10nKeys.screenQ14: 'के उनीहरूलाई निर्देशन सम्झन गाह्रो हुन्छ?',
  L10nKeys.screenQ15: 'के उनीहरूलाई धेरै चरणका कामहरू गर्न गाह्रो हुन्छ?',

  L10nKeys.careDashboardSubtitle: 'परिवारको हेरचाह',
  L10nKeys.careSosLive: 'लाइभ अलर्ट',
  L10nKeys.careSosRespondedBy: '{name} ले जवाफ दिए',
  L10nKeys.careLinkTitle: 'परिवारको सदस्यसँग जडान गर्नुहोस्',
  L10nKeys.careLinkBody: 'आफ्नो प्रियजनलाई उहाँको फोनमा देखिने 6-अक्षरको पारिवारिक कोड सोध्नुहोस्, अनि जडान गर्नुहोस्।',
  L10nKeys.careLinkCode: 'पारिवारिक कोड',
  L10nKeys.careLinkCodeHint: 'जस्तै A1B2C3',
  L10nKeys.careLinkConnect: 'जडान',
  L10nKeys.careLinkDone: 'जडान भयो',
  L10nKeys.careLinkSuccess:
      '{name} सँग जडान भयो! सम्झनाहरू र अलर्टहरू अब सिङ्क हुनेछन्।',
  L10nKeys.careLinkFailed:
      'जडान हुन सकेन। कृपया कोड जाँचेर फेरि प्रयास गर्नुहोस्।',
  L10nKeys.careTrendsTitle: 'AI प्रवृत्तिहरू',
  L10nKeys.careTrendsBody: 'गतिविधिको प्रकार अनुसार दैनिक शुद्धता',
  L10nKeys.careTrendsNoData:
      'अहिले कुनै गतिविधि छैन — प्रवृत्तिहरू हेर्न एउटा अभ्यास पूरा गर्नुहोस्।',
  L10nKeys.careAiDifficulty: 'स्वतः मिलाइएको कठिनाइ',
  L10nKeys.careAiAccuracy: 'मोडेल शुद्धता',
  L10nKeys.careAiRealSessions: 'वास्तविक सत्रहरू',
  L10nKeys.careAiDemoSessions: 'डेमो सत्रहरू',
  L10nKeys.careNavGames: 'खेलहरू',
  L10nKeys.careNavRoutine: 'दिनचर्या',
  L10nKeys.careGreetSubtitle: 'यहाँ हेर्नुहोस् कि आज {name} कस्तो गर्दैछन्।',
  L10nKeys.careNotifEmpty: 'कुनै नयाँ सूचना छैन',
  L10nKeys.careWellnessScore: 'संज्ञानात्मक कल्याण स्कोर',
  L10nKeys.careStatusStable: 'स्थिर',
  L10nKeys.careStatusAttention: 'ध्यान आवश्यक',
  L10nKeys.careLastSynced: 'पछिल्लो सिंक {time}',
  L10nKeys.careMinAgo: '{n} मिनेट अघि',
  L10nKeys.careGamesWeek: 'यस हप्ताका खेलहरू',
  L10nKeys.careRoutineCompletion: 'दिनचर्या पूर्ति',
  L10nKeys.careCurrentStreak: 'हालको स्ट्रिक',
  L10nKeys.careMoodCheckins: 'मुड चेक-इनहरू',
  L10nKeys.careDayUnit: 'दिन',
  L10nKeys.careDaysUnit: 'दिन',
  L10nKeys.careActivityTitle: 'साप्ताहिक गतिविधि',
  L10nKeys.careWeekly: 'साप्ताहिक',
  L10nKeys.careMonthly: 'मासिक',
  L10nKeys.careNoActivityWeek:
      'यस हप्ता अहिलेसम्म कुनै गतिविधि रेकर्ड भएको छैन।',
  L10nKeys.careMoodTitle: 'मुड',
  L10nKeys.careMoodHappy: 'खुसी',
  L10nKeys.careMoodCalm: 'शान्त',
  L10nKeys.careMoodNeutral: 'तटस्थ',
  L10nKeys.careMoodLow: 'कम',
  L10nKeys.careMood7Days: 'पछिल्ला ७ दिन',
  L10nKeys.careMoodInsight: '{name} यस हप्ता प्रायः शान्त हुनुहुन्थ्यो, पछिल्लो दुई दिनमा सामान्य गिरावटसहित।',
  L10nKeys.careMoodNoData: 'यस हप्ता अहिलेसम्म कुनै मुड चेक-इन छैन।',
  L10nKeys.careSkillsTitle: 'संज्ञानात्मक सीपहरू',
  L10nKeys.careSkillMemory: 'स्मृति',
  L10nKeys.careSkillAttention: 'ध्यान',
  L10nKeys.careSkillLanguage: 'भाषा',
  L10nKeys.careSkillReasoning: 'तर्क',
  L10nKeys.careSkillProcessing: 'प्रशोधन गति',
  L10nKeys.careInsightToday: 'आजको अन्तर्दृष्टि',
  L10nKeys.careInsightBody: 'रोबर्ट बिहानको दिनचर्या पछि स्मृति गतिविधिहरूमा निरन्तर सक्रिय रहेका छन्। पछिल्लो दुई दिनमा उनको मुड अलि कम रहेको छ।',
  L10nKeys.careInsightBodyReal: 'यस हप्ता {name} ले {count} वटा संज्ञानात्मक सत्रहरू पूरा गर्नुभयो (लक्ष्य {goal}) र {streak} दिनको स्ट्रिक कायम राख्नुभएको छ।',
  L10nKeys.careViewDetails: 'विवरण हेर्नुहोस्',
  L10nKeys.careInsightDisclaimer:
      'यो डेटाबाट एउटा सौम्य अवलोकन हो — चिकित्सकीय निदान होइन।',
  L10nKeys.careAttentionTitle: 'तपाईंको ध्यान आवश्यक',
  L10nKeys.careAttentionEmpty: 'अहिले तपाईंको ध्यान आवश्यक पर्ने केही छैन।',
  L10nKeys.careAlertSos: '{name} ले SOS बटन थिच्नुभयो',
  L10nKeys.careAlertRoutineMissed: 'हिजो दिनचर्या छुट्यो',
  L10nKeys.careAlertMoodDown: 'पछिल्लो दुई दिनमा मुड घटेको छ',
  L10nKeys.careAlertSessionPending: 'आज संज्ञानात्मक सत्र पूरा भएन',
  L10nKeys.careAlertSeverityHigh: 'उच्च',
  L10nKeys.careAlertSeverityMedium: 'मध्यम',
  L10nKeys.careAlertSeverityLow: 'निम्न',
  L10nKeys.careWeeklySummary: 'साप्ताहिक सारांश',
  L10nKeys.careSessionsCompleted: 'पूरा भएका सत्रहरू',
  L10nKeys.careAvgSessionDuration: 'औसत सत्र अवधि',
  L10nKeys.careRoutineAdherence: 'दिनचर्या पालना',
  L10nKeys.careMoodTrend: 'मुड प्रवृत्ति',
  L10nKeys.careMoodTrendSlightlyDown: 'अलि कम',
  L10nKeys.careMoodTrendStable: 'स्थिर',
  L10nKeys.careMoodTrendUp: 'सुधार हुँदै',
  L10nKeys.careVsLastWeek: 'गत हप्ताको तुलनामा',
  L10nKeys.careSyncedJustNow: 'भर्खर सिंक भयो',
  L10nKeys.careOfflineWaiting:
      'अफलाइन · {count} वटा गतिविधिहरू सिंकको पर्खाइमा',
  L10nKeys.careComingSoon: 'चाँडै आउँदै',
  L10nKeys.careHomeSoon: '{name} को दिनको एक छोटो सिंहावलोकन यहाँ देखिनेछ।',
  L10nKeys.careGamesSoon: 'खेलहरू र सत्र इतिहास यहाँ देखिनेछ।',
  L10nKeys.careRoutineSoon: 'बिरामीको दैनिक दिनचर्या यहाँ देखिनेछ।',
  L10nKeys.careProfileSoon: 'हेरचाहकर्ताको प्रोफाइल र सेटिङहरू यहाँ देखिनेछन्।',
  L10nKeys.serverPairingTitle: 'पारिवारिक कोड',
  L10nKeys.serverPairingBody: 'यो कोड कुनै हेरचाहकर्तासँग साझा गर्नुहोस् ताकि उनीहरू तपाईंसँग जडान हुन सकून्।',
  L10nKeys.serverUnlinked: 'सर्भरसँग जडान छैन',
  L10nKeys.serverLinked: 'सर्भरसँग जडान',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
