import '../l10n_keys.dart';

/// English dictionary (fallback language).
const Map<String, String> stringsEn = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'Your memory companion',
  L10nKeys.back: 'Back',
  L10nKeys.next: 'Next',
  L10nKeys.continueText: 'Continue',
  L10nKeys.skip: 'Skip',
  L10nKeys.done: 'Done',
  L10nKeys.cancel: 'Cancel',
  L10nKeys.yes: 'Yes',
  L10nKeys.no: 'No',
  L10nKeys.save: 'Save',
  L10nKeys.close: 'Close',
  L10nKeys.retry: 'Try again',
  L10nKeys.add: 'Add',
  L10nKeys.edit: 'Edit',
  L10nKeys.remove: 'Remove',
  L10nKeys.search: 'Search',
  L10nKeys.today: 'Today',
  L10nKeys.offline: 'Offline',
  L10nKeys.online: 'Online',

  L10nKeys.goodMorning: 'Good morning',
  L10nKeys.goodAfternoon: 'Good afternoon',
  L10nKeys.goodEvening: 'Good evening',
  L10nKeys.goodNight: 'Good night',

  L10nKeys.navHome: 'Home',
  L10nKeys.navGarden: 'Garden',
  L10nKeys.navActivities: 'Activities',
  L10nKeys.navMemories: 'Memories',
  L10nKeys.navProfile: 'Profile',
  L10nKeys.navMystery: 'Today\'s memory',

  L10nKeys.onboardingWelcomeTitle: 'A gentle companion for your memories',
  L10nKeys.onboardingWelcomeBody: 'Companio helps you remember, play and connect with your family — even without the internet.',
  L10nKeys.onboardingNameTitle: 'What should we call you?',
  L10nKeys.onboardingNameHint: 'Your name',
  L10nKeys.onboardingRegionTitle: 'Where is home for you?',
  L10nKeys.onboardingRegionHint: 'City or town',
  L10nKeys.onboardingRegionList: 'Guwahati, Silchar, Shillong, Agartala, Imphal, Aizawl, Itanagar, Kohima, Gangtok, Dibrugarh, Jorhat, Your city',
  L10nKeys.onboardingLanguageTitle: 'Which language do you prefer?',
  L10nKeys.onboardingLanguageBody: 'You can change this anytime.',
  L10nKeys.onboardingFamilyTitle: 'Who is family?',
  L10nKeys.onboardingFamilyBody: 'Add the people you love. We will show their photos and voices to you as gentle memories.',
  L10nKeys.onboardingAddFamily: 'Add family member',
  L10nKeys.onboardingEmergencyTitle: 'Who should we call in an emergency?',
  L10nKeys.onboardingEmergencyBody: 'Companio can contact your family, not emergency services, when you press the SOS button.',
  L10nKeys.onboardingEmergencyName: 'Name',
  L10nKeys.onboardingEmergencyPhone: 'Phone number',
  L10nKeys.onboardingEmergencyRelation: 'Relation (daughter, son…)',
  L10nKeys.onboardingDoneTitle: 'Your garden is ready!',
  L10nKeys.onboardingDoneBody: 'Complete small activities and watch your garden grow. We are always by your side.',
  L10nKeys.onboardingStart: 'Start my garden',

  L10nKeys.homeWhatsGrowing: 'What is growing today?',
  L10nKeys.homeTodayActivity: 'Today\'s little activity',
  L10nKeys.homeActivityDuration: 'About 3 minutes',
  L10nKeys.homeMinutes: 'min',
  L10nKeys.homeMemoryOfDay: 'Memory of the day',
  L10nKeys.homeMemoryLocked: 'A special memory is waiting…',
  L10nKeys.homeMemoryUnlocked: 'A memory has been unlocked!',
  L10nKeys.homeContinueActivity: 'Continue activity',
  L10nKeys.homeFamilyMemory: 'From your family',
  L10nKeys.homeFamilyMemoryEmpty: 'Family memories can appear here.',
  L10nKeys.homeSos: 'Help needed',
  L10nKeys.homeSosSubtitle: 'Contact family in an emergency',
  L10nKeys.homeGardenPreview: 'Your garden',
  L10nKeys.homeEngine: 'Companio companion',
  L10nKeys.homeEngineReady: 'Your helper is ready.',
  L10nKeys.homeWelcomeBack: 'Welcome back! Let\'s continue your garden. 🌸',
  L10nKeys.homeNoActivity: 'No activity today',
  L10nKeys.homeNoActivityBody:
      'Take a rest — or pick any activity you like. 🌻',

  L10nKeys.gardenTitle: 'My Memory Garden',
  L10nKeys.gardenSectionAll: 'All',
  L10nKeys.gardenSectionFamily: 'Family',
  L10nKeys.gardenSectionChildhood: 'Childhood',
  L10nKeys.gardenSectionPlaces: 'Places',
  L10nKeys.gardenSectionFestivals: 'Festivals',
  L10nKeys.gardenEmpty: 'Your garden is just beginning',
  L10nKeys.gardenEmptyBody:
      'Complete your first activity and a seed will be planted here.',
  L10nKeys.gardenPoints: 'points',
  L10nKeys.gardenLevel: 'Level',
  L10nKeys.gardenSeed: 'Seed',
  L10nKeys.gardenPlant: 'Plant',
  L10nKeys.gardenFlower: 'Flower',
  L10nKeys.gardenTree: 'Tree',
  L10nKeys.gardenMilestone: 'Milestone',
  L10nKeys.gardenGrowth: 'Growing',
  L10nKeys.gardenDidYouKnow:
      'Your garden grows every time you complete an activity.',
  L10nKeys.gardenPlantSeed: 'Plant a seed',

  L10nKeys.activitiesTitle: 'Activities',
  L10nKeys.activitiesToday: 'Today',
  L10nKeys.activitiesLibrary: 'More activities',
  L10nKeys.mainGamesTitle: 'Main games',
  L10nKeys.activitiesStart: 'Start',
  L10nKeys.activitiesCompleted: 'Completed',
  L10nKeys.activitiesInProgress: 'In progress',
  L10nKeys.activitiesNotStarted: 'Ready',
  L10nKeys.activityYoureDone: 'That was lovely!',
  L10nKeys.activityPraise: 'You added a little life to your garden. 🌱',
  L10nKeys.activityHint: 'Need a hint?',
  L10nKeys.activityTryAgain: 'Let\'s look at this memory again',
  L10nKeys.activityOptionsHint: 'Tap your answer',
  L10nKeys.activityTapToMatch: 'Tap the pair that belong together',
  L10nKeys.activityNext: 'Next',
  L10nKeys.activityFinish: 'Finish',
  L10nKeys.activityGroupLetsAgain: 'Let\'s look at this again',
  L10nKeys.activityGroupTogether: 'Let\'s do this together',
  L10nKeys.activityGreatJob: 'Well done!',
  L10nKeys.activityKitchen: 'My Kitchen',
  L10nKeys.activityShopping: 'My Shop',
  L10nKeys.activityMatching: 'Match the pair',
  L10nKeys.activitySequence: 'Put in order',
  L10nKeys.activityRecognition: 'What is this?',
  L10nKeys.activityAssociation: 'What goes together?',
  L10nKeys.activityRecall: 'Can you remember?',
  L10nKeys.activityAttention: 'Find it',
  L10nKeys.activityDurationSuffix: 'min',
  L10nKeys.activityTodayDone: 'Today\'s activity is done',
  L10nKeys.activityTodayDoneBody:
      'Your garden has grown. A memory might be waiting tomorrow.',
  L10nKeys.activityGardenGrew: 'Your garden grew!',
  L10nKeys.activityMemoryUnlocked: 'A memory has been unlocked',
  L10nKeys.activityReadAloud: 'Read aloud',

  L10nKeys.kitchenTitle: 'Let\'s make chai',
  L10nKeys.kitchenMakeChai: 'Making chai',
  L10nKeys.kitchenMakeChaiPrompt: 'Tap the steps in the right order.',
  L10nKeys.kitchenSteps: 'Steps',
  L10nKeys.kitchenTapInOrder: 'Tap the steps in the right order',
  L10nKeys.kitchenCorrectOrder: 'Perfect chai order!',
  L10nKeys.kitchenBreakfast: 'Making breakfast',
  L10nKeys.kitchenBreakfastHint: 'A fresh start to the day',
  L10nKeys.kitchenBreakfastPrompt: 'Put the breakfast steps in order.',

  L10nKeys.shopTitle: 'My Shop',
  L10nKeys.shopGetMilkBread: 'Bread and milk',
  L10nKeys.shopGetMilkBreadPrompt: 'Get milk and bread within ₹100.',
  L10nKeys.shopBudget: 'Budget',
  L10nKeys.shopBasket: 'Your basket',
  L10nKeys.shopTotal: 'Total',
  L10nKeys.shopWithinBudget: 'Within budget!',
  L10nKeys.shopOverBudget: 'Over the budget — try again',
  L10nKeys.shopCheckout: 'Finish and pay',
  L10nKeys.shopBuy: 'Add to basket',
  L10nKeys.shopSell: 'Remove',
  L10nKeys.shopVeggies: 'Vegetables for dinner',
  L10nKeys.shopVeggiesPrompt: 'Get potatoes and onions within ₹60.',
  L10nKeys.recKitchenItem: 'Which one is this?',
  L10nKeys.recKitchenItemPrompt:
      'Which of these do we use to carry things from the market?',
  L10nKeys.recCurrency: 'A little money',
  L10nKeys.recCurrencyPrompt: 'Which note is ₹20?',
  L10nKeys.matchFestival: 'Match the festival',
  L10nKeys.matchFestivalPrompt: 'Match each festival with its special food.',
  L10nKeys.matchObjectUse: 'Match the pair',
  L10nKeys.matchObjectUsePrompt: 'Match each thing with its time of use.',
  L10nKeys.seqMorning: 'Morning routine',
  L10nKeys.seqMorningPrompt: 'Put your morning routine in order.',
  L10nKeys.seqRoute: 'The morning trip',
  L10nKeys.seqRoutePrompt: 'Put the trip to the market in order.',
  L10nKeys.assoRegion: 'What belongs here?',
  L10nKeys.assoRegionPrompt: 'What is Assam famous for?',
  L10nKeys.assoHarvest: 'Sweet fruit',
  L10nKeys.assoHarvestPrompt: 'Which fruit is called the king of summer?',
  L10nKeys.attnVeg: 'Find the carrot',
  L10nKeys.attnVegPrompt: 'Can you find the carrot?',
  L10nKeys.recallSong: 'A familiar song',
  L10nKeys.recallSongPrompt: 'Which song do dancers move to during Bihu?',
  L10nKeys.activityPairs: 'Find the Pairs',
  L10nKeys.activitySequenceRecall: 'Remember the Sequence',
  L10nKeys.activityFindChanged: 'What Changed?',
  L10nKeys.pairsFruits: 'Fruits from the market',
  L10nKeys.pairsKitchen: 'Things in your kitchen',
  L10nKeys.pairsRemember:
      'Look at all the cards carefully, then find the matching pair.',
  L10nKeys.pairsStart: 'Hide the cards and start',
  L10nKeys.pairsFound: 'You found a pair!',
  L10nKeys.seqRecallItems: 'Everyday things',
  L10nKeys.seqRecallNumbers: 'Numbers in order',
  L10nKeys.seqRecallWatch:
      'Watch the cards carefully – each one lights up in order.',
  L10nKeys.seqRecallRepeat: 'Now tap the cards in the same order you saw them.',
  L10nKeys.changeMarket: 'A basket of fruits',
  L10nKeys.changeFestival: 'Festival lamps',
  L10nKeys.changeRemember: 'Remember these pictures carefully.',
  L10nKeys.changeFind: 'One picture has changed. Find the different one.',
  L10nKeys.changeCorrect: 'Well spotted! That one changed.',

  L10nKeys.mysteryTitle: 'Today\'s special memory',
  L10nKeys.mysteryLocked: 'A special memory is waiting for you…',
  L10nKeys.mysteryLockedBody:
      'Do 2–3 little activities today and it may unlock. What will it be?',
  L10nKeys.mysteryUnlocked: 'Your special memory is here!',
  L10nKeys.mysteryUnlockedBody:
      'This memory is only for you. Take your time. 🌸',
  L10nKeys.mysteryCuriosity: 'What will open today?',
  L10nKeys.mysteryOpen: 'Open memory',

  L10nKeys.memoriesTitle: 'My Memories',
  L10nKeys.memoriesEmpty: 'No memories yet',
  L10nKeys.memoriesEmptyBody: 'Your family can add photos and voice messages. When available they will appear here.',
  L10nKeys.memoriesFamily: 'Family',
  L10nKeys.memoriesPlaces: 'Places',
  L10nKeys.memoriesFestivals: 'Festivals',
  L10nKeys.memoriesChildhood: 'Childhood',
  L10nKeys.memoriesKindPhoto: 'Photo',
  L10nKeys.memoriesKindVoice: 'Voice message',
  L10nKeys.memoriesKindText: 'Story',
  L10nKeys.memoriesKindSound: 'Sound',
  L10nKeys.memoriesKindPlace: 'Place',
  L10nKeys.memoriesAddedBy: 'Added by',
  L10nKeys.memoriesWhoIsThis: 'Who is this?',
  L10nKeys.memoriesPlayVoice: 'Listen',
  L10nKeys.memoriesThisIsMe: 'This is me',
  L10nKeys.memoriesNotMe: 'Not me',

  L10nKeys.profileTitle: 'Profile',
  L10nKeys.profileLanguage: 'App language',
  L10nKeys.profileRegion: 'My region',
  L10nKeys.profileVoiceLanguage: 'Voice language',
  L10nKeys.profileVoicePrompts: 'Voice prompts',
  L10nKeys.profileTextSize: 'Text size',
  L10nKeys.profileReducedMotion: 'Calmer motion',
  L10nKeys.profileSoundEffects: 'Sound effects',
  L10nKeys.profileFamily: 'Family',
  L10nKeys.profileContacts: 'Emergency contacts',
  L10nKeys.profileDemoMode: 'Demo mode',
  L10nKeys.profileReminders: 'Reminders',
  L10nKeys.profileNeedHelp: 'Need help?',

  L10nKeys.remindersTitle: 'Reminders',
  L10nKeys.remindersEmpty: 'No reminders yet',
  L10nKeys.remindersNew: 'New reminder',
  L10nKeys.remindersTitleLabel: 'Title',
  L10nKeys.remindersDetailLabel: 'Details (optional)',
  L10nKeys.remindersTime: 'Time',
  L10nKeys.remindersDays: 'Days',
  L10nKeys.remindersEveryday: 'Every day',
  L10nKeys.remindersEnabled: 'On',
  L10nKeys.remindersMedicine: 'Medicine',
  L10nKeys.remindersAppointment: 'Appointment',
  L10nKeys.remindersRoutine: 'Daily routine',

  L10nKeys.dayMon: 'Mon',
  L10nKeys.dayTue: 'Tue',
  L10nKeys.dayWed: 'Wed',
  L10nKeys.dayThu: 'Thu',
  L10nKeys.dayFri: 'Fri',
  L10nKeys.daySat: 'Sat',
  L10nKeys.daySun: 'Sun',

  L10nKeys.sosTitle: 'Emergency help',
  L10nKeys.sosExplain: 'Press and hold. Companio will contact your emergency contacts one by one. Companio does not replace emergency services (like calling 112).',
  L10nKeys.sosHold: 'Hold to call for help',
  L10nKeys.sosHoldBody: 'Keep holding…',
  L10nKeys.sosActiveTitle: 'Help is being contacted',
  L10nKeys.sosActiveBody: 'Your family has been notified. If they do not respond, the next contact will be called.',
  L10nKeys.sosContacting: 'Contacting',
  L10nKeys.sosContactFamily: 'Contact family',
  L10nKeys.sosContacted: 'Contacted',
  L10nKeys.sosWaitingResponse: 'Waiting for a response…',
  L10nKeys.sosEscalating: 'Contacting next person…',
  L10nKeys.sosCancelled: 'Help request cancelled',
  L10nKeys.sosCancelAction: 'Cancel help request',
  L10nKeys.sosDone: 'Done',
  L10nKeys.sosHelpOnWay: 'Someone will be with you soon. 🧡',
  L10nKeys.sosNoContacts: 'No emergency contacts yet',
  L10nKeys.sosNoContactsBody:
      'Please ask your family to add an emergency contact.',
  L10nKeys.sosAddContact: 'Add contact',
  L10nKeys.sosDisclaimer: 'Companio informs your chosen contacts. It is not a substitute for official emergency services.',
  L10nKeys.sosContactedPerson: 'Family member contacted',
  L10nKeys.sosEscalatedTo: 'Next family member contacted',
  L10nKeys.sosAcknowledged:
      'A family member has responded. Help is on the way.',
  L10nKeys.sosNotSilent:
      'We will never pretend help was sent when it could not be delivered.',
  L10nKeys.sosAlertNotDelivered:
      'Your message could not be delivered yet. We will keep trying.',

  L10nKeys.careTitle: 'Caregiver',
  L10nKeys.careDashboard: 'Overview',
  L10nKeys.carePatients: 'My patients',
  L10nKeys.careMemories: 'Memories',
  L10nKeys.careContacts: 'Emergency contacts',
  L10nKeys.careSettings: 'Settings',
  L10nKeys.careAddMemory: 'Add a memory',
  L10nKeys.careAddContact: 'Add contact',
  L10nKeys.careEngagement: 'Engagement',
  L10nKeys.careActivitiesWeek: 'Activities this week',
  L10nKeys.careGardenProgress: 'Garden progress',
  L10nKeys.careRecentActivity: 'Recent activity',
  L10nKeys.careNoPatients: 'No linked patients',
  L10nKeys.careNoPatientsBody:
      'Ask your family member to link you, or add a patient profile.',
  L10nKeys.careAddPatient: 'Add patient',
  L10nKeys.carePerformanceNote:
      'Activity performance is lower than this person\'s recent baseline.',
  L10nKeys.careUploadPhoto: 'Upload photo',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'Record voice',
  L10nKeys.careWriteMemory: 'Write memory',
  L10nKeys.careMemoryTitle: 'Title',
  L10nKeys.careMemoryCaption: 'Caption',
  L10nKeys.careMemoryRelation: 'Who is in it? (relation)',
  L10nKeys.careMemoryCategory: 'Category',
  L10nKeys.careContactName: 'Name',
  L10nKeys.careContactPhone: 'Phone number',
  L10nKeys.careContactPriority: 'Call order',
  L10nKeys.careContactRelation: 'Relation',
  L10nKeys.careEscalationTimeout: 'Minutes before calling the next contact',
  L10nKeys.careIncidentStatus: 'Status',
  L10nKeys.careAckSos: 'I\'m responding',
  L10nKeys.careResponding: 'Responding',
  L10nKeys.careActiveAlerts: 'Active alerts',
  L10nKeys.careDashboardSubtitle: 'Family care',

  L10nKeys.careSosLive: 'Live alert',
  L10nKeys.careSosRespondedBy: 'Responded by {name}',
  L10nKeys.careLinkTitle: 'Connect to a family member',
  L10nKeys.careLinkBody: 'Ask your loved one for the 6-letter family code shown on their phone, then connect.',
  L10nKeys.careLinkCode: 'Family code',
  L10nKeys.careLinkCodeHint: 'e.g. A1B2C3',
  L10nKeys.careLinkConnect: 'Connect',
  L10nKeys.careLinkDone: 'Connected',
  L10nKeys.careLinkSuccess:
      'Linked to {name}! Memories and alerts will now sync.',
  L10nKeys.careLinkFailed:
      'Could not connect. Please check the code and try again.',
  L10nKeys.careTrendsTitle: 'AI trends',
  L10nKeys.careTrendsBody: 'Daily accuracy by activity type',
  L10nKeys.careTrendsNoData:
      'No activity yet — complete an exercise to see trends.',
  L10nKeys.careAiDifficulty: 'Auto-tuned difficulty',
  L10nKeys.careAiAccuracy: 'Model accuracy',
  L10nKeys.careAiRealSessions: 'Real sessions',
  L10nKeys.careAiDemoSessions: 'Demo sessions',

  L10nKeys.careNavGames: 'Games',
  L10nKeys.careNavRoutine: 'Routine',
  L10nKeys.careGreetSubtitle: "Here's how {name} is doing today.",
  L10nKeys.careNotifEmpty: 'No new notifications',
  L10nKeys.careWellnessScore: 'Cognitive Wellness Score',
  L10nKeys.careStatusStable: 'Stable',
  L10nKeys.careStatusAttention: 'Needs attention',
  L10nKeys.careLastSynced: 'Last synced {time}',
  L10nKeys.careMinAgo: '{n} min ago',
  L10nKeys.careGamesWeek: 'Games this week',
  L10nKeys.careRoutineCompletion: 'Routine completion',
  L10nKeys.careCurrentStreak: 'Current streak',
  L10nKeys.careMoodCheckins: 'Mood check-ins',
  L10nKeys.careDayUnit: 'day',
  L10nKeys.careDaysUnit: 'days',
  L10nKeys.careActivityTitle: 'Weekly activity',
  L10nKeys.careWeekly: 'Weekly',
  L10nKeys.careMonthly: 'Monthly',
  L10nKeys.careNoActivityWeek: 'No activity recorded this week yet.',
  L10nKeys.careMoodTitle: 'Mood',
  L10nKeys.careMoodHappy: 'Happy',
  L10nKeys.careMoodCalm: 'Calm',
  L10nKeys.careMoodNeutral: 'Neutral',
  L10nKeys.careMoodLow: 'Low',
  L10nKeys.careMood7Days: 'Last 7 days',
  L10nKeys.careMoodInsight: '{name} has been mostly calm this week, with a gentle dip in the last two days.',
  L10nKeys.careMoodNoData: 'No mood check-ins this week yet.',
  L10nKeys.careSkillsTitle: 'Cognitive skills',
  L10nKeys.careSkillMemory: 'Memory',
  L10nKeys.careSkillAttention: 'Attention',
  L10nKeys.careSkillLanguage: 'Language',
  L10nKeys.careSkillReasoning: 'Reasoning',
  L10nKeys.careSkillProcessing: 'Processing speed',
  L10nKeys.careInsightToday: "Today's insight",
  L10nKeys.careInsightBody: "Robert has been consistent in memory activities after his morning routine. His mood has been slightly lower over the last two days.",
  L10nKeys.careInsightBodyReal: "This week {name} completed {count} cognitive sessions (goal {goal}) and keeps a {streak}-day streak going.",
  L10nKeys.careViewDetails: 'View details',
  L10nKeys.careInsightDisclaimer:
      'This is a gentle observation from the data — not a medical diagnosis.',
  L10nKeys.careAttentionTitle: 'Needs your attention',
  L10nKeys.careAttentionEmpty: 'Nothing needs your attention right now.',
  L10nKeys.careAlertSos: '{name} pressed the SOS button',
  L10nKeys.careAlertRoutineMissed: 'Routine was missed yesterday',
  L10nKeys.careAlertMoodDown: 'Mood decreased over the last two days',
  L10nKeys.careAlertSessionPending: 'Cognitive session not completed today',
  L10nKeys.careAlertSeverityHigh: 'High',
  L10nKeys.careAlertSeverityMedium: 'Medium',
  L10nKeys.careAlertSeverityLow: 'Low',
  L10nKeys.careWeeklySummary: 'Weekly summary',
  L10nKeys.careSessionsCompleted: 'Sessions completed',
  L10nKeys.careAvgSessionDuration: 'Avg session duration',
  L10nKeys.careRoutineAdherence: 'Routine adherence',
  L10nKeys.careMoodTrend: 'Mood trend',
  L10nKeys.careMoodTrendSlightlyDown: 'Slightly lower',
  L10nKeys.careMoodTrendStable: 'Stable',
  L10nKeys.careMoodTrendUp: 'Lifting up',
  L10nKeys.careVsLastWeek: 'vs last week',
  L10nKeys.careSyncedJustNow: 'Synced just now',
  L10nKeys.careOfflineWaiting: 'Offline · {count} activities waiting to sync',
  L10nKeys.careComingSoon: 'Coming soon',
  L10nKeys.careHomeSoon: "A quick overview of {name}'s day will appear here.",
  L10nKeys.careGamesSoon: 'Games and session history will appear here.',
  L10nKeys.careRoutineSoon: "The patient's daily routine will appear here.",
  L10nKeys.careProfileSoon: 'Caregiver profile and settings will appear here.',

  L10nKeys.serverPairingTitle: 'Family code',
  L10nKeys.serverPairingBody:
      'Share this code with a caregiver so they can connect to you.',
  L10nKeys.serverUnlinked: 'Not connected to server',
  L10nKeys.serverLinked: 'Connected to server',

  L10nKeys.syncSavingOffline: 'Offline',
  L10nKeys.syncSavingOfflineBody:
      'Your activities are safely saved on this device.',
  L10nKeys.syncSynced: 'Synchronized',
  L10nKeys.syncInfo: 'Your information has been synchronized.',
  L10nKeys.syncPending: 'Waiting to synchronize',

  L10nKeys.errorGeneric: 'Something went wrong',
  L10nKeys.errorGenericBody: 'Your progress is still safe. Please try again.',
  L10nKeys.errorAudio: 'Audio could not be played on this device.',
  L10nKeys.errorPermission: 'Permission needed to access this on your device.',
  L10nKeys.errorNoInternetAction:
      'No internet needed — it is saved here first.',

  L10nKeys.demoWelcome: 'Try the demo',
  L10nKeys.demoExplain:
      'A sample family and memories will be added so you can explore.',
  L10nKeys.demoLoad: 'Load demo garden',

  L10nKeys.unitsPoints: 'points',
  L10nKeys.teaserChai: 'Let\'s make some chai.',
  L10nKeys.familiarityName: 'Asha',
  L10nKeys.regionMap: 'My Region',
  L10nKeys.regionChoose: 'Choose your region',
  L10nKeys.regionIndia: 'India',
  L10nKeys.importantMemory: 'Important memory',
  L10nKeys.growing: 'Growing',
  L10nKeys.blooming: 'Blooming',
  L10nKeys.mature: 'Mature',
  L10nKeys.noVoice: 'Voice is not available on this device.',
  L10nKeys.optional: 'optional',

  L10nKeys.langChoose: 'Choose language',
  L10nKeys.langPrimary: 'Primary',
  L10nKeys.langNorthEast: 'North-East India',
  L10nKeys.langMajor: 'Major Indian languages',

  L10nKeys.authSignUpTitle: 'Create your account',
  L10nKeys.authSignUpBody: 'This Companio profile will stay safely on this device. Use a username and password so only you can open it.',
  L10nKeys.authLoginTitle: 'Welcome back',
  L10nKeys.authLoginBody:
      'Sign in with your username and password to open your garden.',
  L10nKeys.authUsername: 'Username',
  L10nKeys.authUsernameHint: 'e.g. ranu123',
  L10nKeys.authDisplayName: 'Your name',
  L10nKeys.authPassword: 'Password',
  L10nKeys.authPasswordHint: 'At least 6 characters',
  L10nKeys.authConfirmPassword: 'Confirm password',
  L10nKeys.authRoleQuestion: 'This profile is for…',
  L10nKeys.authRolePatient: 'Myself',
  L10nKeys.authRoleCaregiver: 'A family member',
  L10nKeys.authCreate: 'Create account',
  L10nKeys.authSignIn: 'Sign in',
  L10nKeys.authSignOut: 'Sign out',
  L10nKeys.authAccount: 'Account',
  L10nKeys.caregiverTitle: 'Caregiver',
  L10nKeys.caregiverNotLinked: 'No caregiver linked yet',
  L10nKeys.authBadCredentials: 'Incorrect username or password.',
  L10nKeys.authUsernameTaken: 'That username is already in use on this device.',
  L10nKeys.authPasswordMismatch: 'Passwords do not match.',
  L10nKeys.authUsernameShort: 'Username needs at least 3 characters.',
  L10nKeys.authUsernameInvalid:
      'Use only letters, numbers, dots, dashes or underscores.',
  L10nKeys.authPasswordShort: 'Password needs at least 6 characters.',
  L10nKeys.authNameRequired: 'Please enter a name.',
  L10nKeys.authSignOutConfirm: 'Sign out of this profile?',
  L10nKeys.screenTitle: 'Quick memory check-up',
  L10nKeys.screenIntro: 'We will ask a few short questions about the patient. Think about how they have been over the past few months.',
  L10nKeys.screenNotSure: 'Not sure',
  L10nKeys.screenFinish: 'See my result',
  L10nKeys.screenSkip: 'Skip for now',
  L10nKeys.screenResultBack: 'Done',
  L10nKeys.screenCheckAgain: 'Check again',
  L10nKeys.screenStartCheckup: 'Start check-up',
  L10nKeys.screenSkipped: 'Check-up skipped',
  L10nKeys.screenStatusGood: 'Everything looks fine',
  L10nKeys.screenStatusGoodBody: 'No major concerns were noticed. Keep enjoying the daily activities, and if anything changes you can check again anytime.',
  L10nKeys.screenStatusWatch: 'Some changes noticed',
  L10nKeys.screenStatusWatchBody: 'A few forgetful moments were noticed. This is common with age, but it is good to keep an eye and mention it at the next doctor visit.',
  L10nKeys.screenStatusDoctor: 'Please get a check-up',
  L10nKeys.screenStatusDoctorBody: 'Several signs were noticed that could need attention. Please share these with a doctor or clinic so they can help.',
  L10nKeys.screenRarely: 'Rarely',
  L10nKeys.screenSometimes: 'Sometimes',
  L10nKeys.screenFrequently: 'Frequently',
  L10nKeys.screenVeryFrequently: 'Very frequently',
  L10nKeys.screenQ01: 'Do they have difficulty remembering recent events?',
  L10nKeys.screenQ02: 'Do they repeat the same questions or stories?',
  L10nKeys.screenQ03: 'Do they forget names of familiar people?',
  L10nKeys.screenQ04: 'Do they have difficulty recognising familiar faces?',
  L10nKeys.screenQ05: 'Do they forget appointments or important events?',
  L10nKeys.screenQ06: 'Do they have difficulty finding the right words?',
  L10nKeys.screenQ07: 'Do they become confused about where they are?',
  L10nKeys.screenQ08: 'Do they need reminders for daily activities?',
  L10nKeys.screenQ09: 'Do they have difficulty managing medicines?',
  L10nKeys.screenQ10: 'Do they get anxious or frustrated when confused?',
  L10nKeys.screenQ11: 'Do they have difficulty following conversations?',
  L10nKeys.screenQ12: 'Do they have difficulty completing familiar tasks?',
  L10nKeys.screenQ13: 'Do they forget where everyday objects are kept?',
  L10nKeys.screenQ14: 'Do they have difficulty remembering instructions?',
  L10nKeys.screenQ15: 'Do they have difficulty with multi-step activities?',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  // ── Caregiver ───────────────────────────────────────────────────────────
  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',

  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',

  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',

  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',

  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',

  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',

  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',

  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',

  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',

  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
