import '../l10n_keys.dart';

/// Gujarati dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsGu = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'તમારા સંસ્મરણોનો સાથી',
  L10nKeys.back: 'પાછળ',
  L10nKeys.next: 'આગળ',
  L10nKeys.continueText: 'આગળ જાઓ',
  L10nKeys.skip: 'છોડો',
  L10nKeys.done: 'થઈ ગયું',
  L10nKeys.cancel: 'રદ કરો',
  L10nKeys.yes: 'હા',
  L10nKeys.no: 'ના',
  L10nKeys.save: 'સાચવો',
  L10nKeys.close: 'બંધ કરો',
  L10nKeys.retry: 'ફરી પ્રયત્ન કરો',
  L10nKeys.add: 'ઉમેરો',
  L10nKeys.edit: 'બદલો',
  L10nKeys.remove: 'દૂર કરો',
  L10nKeys.search: 'શોધો',
  L10nKeys.today: 'આજ',
  L10nKeys.offline: 'ઓફલાઈન',
  L10nKeys.online: 'ઓનલાઈન',

  L10nKeys.goodMorning: 'સુપ્રભાત',
  L10nKeys.goodAfternoon: 'નમસ્કાર',
  L10nKeys.goodEvening: 'શુભ સાંજ',
  L10nKeys.goodNight: 'શુભ રાત્રિ',

  L10nKeys.navHome: 'ઘર',
  L10nKeys.navGarden: 'બગીચો',
  L10nKeys.navActivities: 'પ્રવૃત્તિઓ',
  L10nKeys.navMemories: 'સંસ્મરણો',
  L10nKeys.navProfile: 'પ્રોફાઈલ',
  L10nKeys.navMystery: 'આજનું સંસ્મરણ',

  L10nKeys.onboardingWelcomeTitle: 'તમારા યાદગાર પળોનો હૂંફાળો સાથી',
  L10nKeys.onboardingWelcomeBody: 'માઈન્ડકેર એનઈઆર તમને ઈન્ટરનેટ વિના પણ યાદ રાખવામાં, રમવામાં અને પરિવારની સાથે જોડાયેલા રહેવામાં મદદ કરે છે.',
  L10nKeys.onboardingNameTitle: 'અમે તમને શું કહીને બોલાવીએ?',
  L10nKeys.onboardingNameHint: 'તમારું નામ',
  L10nKeys.onboardingRegionTitle: 'તમારું ઘર ક્યાં છે?',
  L10nKeys.onboardingRegionHint: 'શહેર કે ગામ',
  L10nKeys.onboardingRegionList: 'ગુવાહાટી, શિલચર, શિલોંગ, અગરતલા, ઈમ્ફાલ, આઈઝોલ, ઈટાનગર, કોહિમા, ગંગટોક, ડિબ્રુગઢ, જોરહટ, તમારું શહેર',
  L10nKeys.onboardingLanguageTitle: 'તમને કઈ ભાષા ગમશે?',
  L10nKeys.onboardingLanguageBody: 'તમે આ કોઈ પણ સમયે બદલી શકો છો.',
  L10nKeys.onboardingFamilyTitle: 'પરિવાર કોણ?',
  L10nKeys.onboardingFamilyBody: 'તમારા વહાલા લોકોને જોડો. અમે તેમના ફોટા અને અવાજ નરમ સંસ્મરણ તરીકે બતાવીશું.',
  L10nKeys.onboardingAddFamily: 'પરિવારનો સભ્ય ઉમેરો',
  L10nKeys.onboardingEmergencyTitle: 'કટોકટીમાં અમે કોને બોલાવશું?',
  L10nKeys.onboardingEmergencyBody: 'SOS બટન દબાવો એટલે માઈન્ડકેર તમારા પરિવારને જાણ કરે છે, કટોકટી સેવાઓને નહીં.',
  L10nKeys.onboardingEmergencyName: 'નામ',
  L10nKeys.onboardingEmergencyPhone: 'ફોન નંબર',
  L10nKeys.onboardingEmergencyRelation: 'સંબંધ (દીકરી, દીકરો…)',
  L10nKeys.onboardingDoneTitle: 'તમારો બગીચો તૈયાર છે!',
  L10nKeys.onboardingDoneBody:
      'નાની પ્રવૃત્તિઓ પૂરી કરો અને તમારો બગીચો વધતો જુઓ. અમે તમારી સાથે છીએ.',
  L10nKeys.onboardingStart: 'મારો બગીચો શરૂ કરો',

  L10nKeys.homeWhatsGrowing: 'આજે શું વધી રહ્યું છે?',
  L10nKeys.homeTodayActivity: 'આજની નાની પ્રવૃત્તિ',
  L10nKeys.homeActivityDuration: 'લગભગ ૩ મિનિટ',
  L10nKeys.homeMinutes: 'મિનિટ',
  L10nKeys.homeMemoryOfDay: 'આજનું સંસ્મરણ',
  L10nKeys.homeMemoryLocked: 'એક ખાસ સંસ્મરણ રાહ જોઈ રહ્યું છે…',
  L10nKeys.homeMemoryUnlocked: 'એક સંસ્મરણ ખુલ્યું!',
  L10nKeys.homeContinueActivity: 'પ્રવૃત્તિ ચાલુ રાખો',
  L10nKeys.homeFamilyMemory: 'તમારા પરિવાર તરફથી',
  L10nKeys.homeFamilyMemoryEmpty: 'પરિવારના સંસ્મરણો અહીં દેખાઈ શકે છે.',
  L10nKeys.homeSos: 'મદદ જોઈએ છે',
  L10nKeys.homeSosSubtitle: 'કટોકટીમાં પરિવારનો સંપર્ક',
  L10nKeys.homeGardenPreview: 'તમારો બગીચો',
  L10nKeys.homeEngine: 'માઈન્ડકેર સાથી',
  L10nKeys.homeEngineReady: 'તમારો સહાયક તૈયાર છે.',
  L10nKeys.homeWelcomeBack: 'પાછા આવવા બદલ આભાર! ચાલો બગીચો આગળ વધારીએ. 🌸',
  L10nKeys.homeNoActivity: 'આજે પ્રવૃત્તિ નથી',
  L10nKeys.homeNoActivityBody:
      'થોડી રાહત લો — કે પછી તમને ગમે તે પ્રવૃત્તિ પસંદ કરો. 🌻',

  L10nKeys.gardenTitle: 'મારો સંસ્મરણ બગીચો',
  L10nKeys.gardenSectionAll: 'બધા',
  L10nKeys.gardenSectionFamily: 'પરિવાર',
  L10nKeys.gardenSectionChildhood: 'બાળપણ',
  L10nKeys.gardenSectionPlaces: 'સ્થળો',
  L10nKeys.gardenSectionFestivals: 'તહેવારો',
  L10nKeys.gardenEmpty: 'તમારો બગીચો હમણાં જ શરૂ થયો છે',
  L10nKeys.gardenEmptyBody: 'પહેલી પ્રવૃત્તિ પૂરી કરો, અહીં એક બીજ રોપાશે.',
  L10nKeys.gardenPoints: 'ગુણ',
  L10nKeys.gardenLevel: 'સ્તર',
  L10nKeys.gardenSeed: 'બીજ',
  L10nKeys.gardenPlant: 'રોપા',
  L10nKeys.gardenFlower: 'ફૂલ',
  L10nKeys.gardenTree: 'ઝાડ',
  L10nKeys.gardenMilestone: 'કાળ',
  L10nKeys.gardenGrowth: 'વધી રહ્યું છે',
  L10nKeys.gardenDidYouKnow: 'દરેક પૂરી થતી પ્રવૃત્તિ તમારો બગીચો વધારે છે.',
  L10nKeys.gardenPlantSeed: 'બીજ રોપો',

  L10nKeys.activitiesTitle: 'પ્રવૃત્તિઓ',
  L10nKeys.activitiesToday: 'આજ',
  L10nKeys.activitiesLibrary: 'વધુ પ્રવૃત્તિઓ',
  L10nKeys.mainGamesTitle: 'મુખ્ય રમતો',
  L10nKeys.activitiesStart: 'શરૂ કરો',
  L10nKeys.activitiesCompleted: 'પૂર્ણ',
  L10nKeys.activitiesInProgress: 'ચાલુ',
  L10nKeys.activitiesNotStarted: 'તૈયાર',
  L10nKeys.activityYoureDone: 'ખૂબ સરસ!',
  L10nKeys.activityPraise: 'તમે બગીચાને થોડું જીવન આપ્યું. 🌱',
  L10nKeys.activityHint: 'સંકેત જોઈએ છે?',
  L10nKeys.activityTryAgain: 'ચાલો આ સંસ્મરણ ફરી જોઈએ',
  L10nKeys.activityOptionsHint: 'તમારો જવાબ પસંદ કરો',
  L10nKeys.activityTapToMatch: 'સાથે મળતી જોડી પસંદ કરો',
  L10nKeys.activityNext: 'આગળ',
  L10nKeys.activityFinish: 'પૂરું',
  L10nKeys.activityGroupLetsAgain: 'ચાલો આ ફરી જોઈએ',
  L10nKeys.activityGroupTogether: 'ચાલો આ સાથે કરીએ',
  L10nKeys.activityGreatJob: 'સરસ કામ!',
  L10nKeys.activityKitchen: 'મારું રસોડું',
  L10nKeys.activityShopping: 'મારું દુકાન',
  L10nKeys.activityMatching: 'જોડી બનાવો',
  L10nKeys.activitySequence: 'ક્રમમાં ગોઠવો',
  L10nKeys.activityRecognition: 'આ શું છે?',
  L10nKeys.activityAssociation: 'શું સાથે મળે?',
  L10nKeys.activityRecall: 'યાદ આવે છે?',
  L10nKeys.activityAttention: 'શોધો',
  L10nKeys.activityDurationSuffix: 'મિનિટ',
  L10nKeys.activityTodayDone: 'આજની પ્રવૃત્તિ પૂર્ણ',
  L10nKeys.activityTodayDoneBody:
      'તમારો બગીચો વધ્યો. આવતી કાલે સંસ્મરણ રાહ જોશે.',
  L10nKeys.activityGardenGrew: 'તમારો બગીચો વધ્યો!',
  L10nKeys.activityMemoryUnlocked: 'એક સંસ્મરણ ખુલ્યું',
  L10nKeys.activityReadAloud: 'મોટેથી વાંચો',

  L10nKeys.kitchenTitle: 'ચા બનાવીએ',
  L10nKeys.kitchenMakeChai: 'ચા બનાવવી',
  L10nKeys.kitchenMakeChaiPrompt: 'પગલાં યોગ્ય ક્રમમાં પસંદ કરો.',
  L10nKeys.kitchenSteps: 'પગલાં',
  L10nKeys.kitchenTapInOrder: 'પગલાં યોગ્ય ક્રમમાં પસંદ કરો',
  L10nKeys.kitchenCorrectOrder: 'સરસ! ચા તૈયાર!',
  L10nKeys.kitchenBreakfast: 'નાસ્તો બનાવવો',
  L10nKeys.kitchenBreakfastHint: 'દિવસની તાજી શરૂઆત',
  L10nKeys.kitchenBreakfastPrompt: 'નાસ્તાના પગલાં ક્રમમાં ગોઠવો.',

  L10nKeys.shopTitle: 'મારું દુકાન',
  L10nKeys.shopGetMilkBread: 'બ્રેડ અને દૂધ',
  L10nKeys.shopGetMilkBreadPrompt: '₹૧૦૦માં દૂધ અને બ્રેડ ખરીદો.',
  L10nKeys.shopBudget: 'બજેટ',
  L10nKeys.shopBasket: 'તમારી ટોપલી',
  L10nKeys.shopTotal: 'કુલ',
  L10nKeys.shopWithinBudget: 'બજેટમાં!',
  L10nKeys.shopOverBudget: 'બજેટની બહાર — ફરી જુઓ',
  L10nKeys.shopCheckout: 'પૂરું કરો અને ચૂકવો',
  L10nKeys.shopBuy: 'ટોપલીમાં મૂકો',
  L10nKeys.shopSell: 'કાઢી નાખો',
  L10nKeys.shopVeggies: 'રાતના ભોજન માટે શાકભાજી',
  L10nKeys.shopVeggiesPrompt: '₹૬૦માં બટેટા અને ડુંગળી ખરીદો.',
  L10nKeys.recKitchenItem: 'આ કયું છે?',
  L10nKeys.recKitchenItemPrompt:
      'બજારમાંથી સામાન લાવવા માટે આમાંથી કયું વપરાય છે?',
  L10nKeys.recCurrency: 'થોડા પૈસા',
  L10nKeys.recCurrencyPrompt: 'કઈ નોટ ₹૨૦ છે?',
  L10nKeys.matchFestival: 'તહેવાર જોડો',
  L10nKeys.matchFestivalPrompt: 'દરેક તહેવારને તેની ખાસ વાનગી સાથે જોડો.',
  L10nKeys.matchObjectUse: 'જોડી બનાવો',
  L10nKeys.matchObjectUsePrompt: 'દરેક ચીજવસ્તુને તેના ઉપયોગના સમય સાથે જોડો.',
  L10nKeys.seqMorning: 'સવારની દિનચર્યા',
  L10nKeys.seqMorningPrompt: 'તમારી સવારની દિનચર્યા ક્રમમાં ગોઠવો.',
  L10nKeys.seqRoute: 'સવારની મુસાફરી',
  L10nKeys.seqRoutePrompt: 'બજાર સુધીની મુસાફરી ક્રમમાં ગોઠવો.',
  L10nKeys.assoRegion: 'અહીં શું છે?',
  L10nKeys.assoRegionPrompt: 'આસામ શું માટે પ્રખ્યાત છે?',
  L10nKeys.assoHarvest: 'મીઠું ફળ',
  L10nKeys.assoHarvestPrompt: 'કયા ફળને ઉનાળાનો રાજા કહેવાય છે?',
  L10nKeys.attnVeg: 'ગાજર શોધો',
  L10nKeys.attnVegPrompt: 'શું તમે ગાજર શોધી શકો છો?',
  L10nKeys.recallSong: 'એક ઓળખીતું ગીત',
  L10nKeys.recallSongPrompt: 'બિહુમાં નર્તકો કયા ગીત પર નાચે છે?',
  L10nKeys.activityPairs: 'જોડી શોધો',
  L10nKeys.activitySequenceRecall: 'ક્રમ યાદ રાખો',
  L10nKeys.activityFindChanged: 'શું બદલાયું?',
  L10nKeys.pairsFruits: 'બજારના ફળો',
  L10nKeys.pairsKitchen: 'રસોડાની વસ્તુઓ',
  L10nKeys.pairsRemember: 'બધા કાર્ડ ધ્યાનથી જુઓ, પછી સરખી જોડી શોધો.',
  L10nKeys.pairsStart: 'કાર્ડ સંતાડીને શરૂ કરો',
  L10nKeys.pairsFound: 'જોડી મળી!',
  L10nKeys.seqRecallItems: 'રોજની વસ્તુઓ',
  L10nKeys.seqRecallNumbers: 'ક્રમમાં આંકડા',
  L10nKeys.seqRecallWatch: 'કાર્ડ ધ્યાનથી જુઓ – દરેક ક્રમે પ્રગટ થશે.',
  L10nKeys.seqRecallRepeat: 'હવે તમે જે ક્રમમાં જોયું એ જ ક્રમમાં કાર્ડ દબાવો.',
  L10nKeys.changeMarket: 'ફળોની ટોપલી',
  L10nKeys.changeFestival: 'તહેવારના દીવા',
  L10nKeys.changeRemember: 'આ ચિત્રો ધ્યાનથી યાદ રાખો.',
  L10nKeys.changeFind: 'એક ચિત્ર બદલાયું છે. જુદું ચિત્ર શોધો.',
  L10nKeys.changeCorrect: 'શાબાશ! તે જ બદલાયું હતું.',

  L10nKeys.mysteryTitle: 'આજનું ખાસ સંસ્મરણ',
  L10nKeys.mysteryLocked: 'એક ખાસ સંસ્મરણ તમારી રાહ જોઈ રહ્યું છે…',
  L10nKeys.mysteryLockedBody:
      'આજે ૨–૩ નાની પ્રવૃત્તિ કરો; કદાચ તે ખુલશે. શું હશે?',
  L10nKeys.mysteryUnlocked: 'તમારું ખાસ સંસ્મરણ અહીં છે!',
  L10nKeys.mysteryUnlockedBody:
      'આ સંસ્મરણ ફક્ત તમારા માટે છે. તમારો સમય લો. 🌸',
  L10nKeys.mysteryCuriosity: 'આજે શું ખુલશે?',
  L10nKeys.mysteryOpen: 'સંસ્મરણ ખોલો',

  L10nKeys.memoriesTitle: 'મારા સંસ્મરણો',
  L10nKeys.memoriesEmpty: 'હજી સંસ્મરણો નથી',
  L10nKeys.memoriesEmptyBody: 'તમારો પરિવાર ફોટા અને અવાજ-સંદેશા ઉમેરી શકે છે. ઉપલબ્ધ થતાની સાથે તે અહીં દેખાશે.',
  L10nKeys.memoriesFamily: 'પરિવાર',
  L10nKeys.memoriesPlaces: 'સ્થળો',
  L10nKeys.memoriesFestivals: 'તહેવારો',
  L10nKeys.memoriesChildhood: 'બાળપણ',
  L10nKeys.memoriesKindPhoto: 'ફોટો',
  L10nKeys.memoriesKindVoice: 'અવાજ-સંદેશો',
  L10nKeys.memoriesKindText: 'વાર્તા',
  L10nKeys.memoriesKindSound: 'અવાજ',
  L10nKeys.memoriesKindPlace: 'સ્થળ',
  L10nKeys.memoriesAddedBy: 'ઉમેર્યું',
  L10nKeys.memoriesWhoIsThis: 'આ કોણ છે?',
  L10nKeys.memoriesPlayVoice: 'સાંભળો',
  L10nKeys.memoriesThisIsMe: 'આ હું છું',
  L10nKeys.memoriesNotMe: 'હું નથી',

  L10nKeys.profileTitle: 'પ્રોફાઈલ',
  L10nKeys.profileLanguage: 'એપની ભાષા',
  L10nKeys.profileRegion: 'મારો વિસ્તાર',
  L10nKeys.profileVoiceLanguage: 'અવાજની ભાષા',
  L10nKeys.profileVoicePrompts: 'બોલાયેલા સંકેતો',
  L10nKeys.profileTextSize: 'લખાણનું કદ',
  L10nKeys.profileReducedMotion: 'શાંત ગતિ',
  L10nKeys.profileSoundEffects: 'ધ્વનિ અસરો',
  L10nKeys.profileFamily: 'પરિવાર',
  L10nKeys.profileContacts: 'કટોકટી સંપર્કો',
  L10nKeys.profileDemoMode: 'ડેમો મોડ',
  L10nKeys.profileReminders: 'રિમાઈન્ડર્સ',
  L10nKeys.profileNeedHelp: 'મદદ જોઈએ છે?',

  L10nKeys.remindersTitle: 'રિમાઈન્ડર્સ',
  L10nKeys.remindersEmpty: 'હજી રિમાઈન્ડર્સ નથી',
  L10nKeys.remindersNew: 'નવું રિમાઈન્ડર',
  L10nKeys.remindersTitleLabel: 'શીર્ષક',
  L10nKeys.remindersDetailLabel: 'વિગત (વૈકલ્પિક)',
  L10nKeys.remindersTime: 'સમય',
  L10nKeys.remindersDays: 'દિવસો',
  L10nKeys.remindersEveryday: 'દરરોજ',
  L10nKeys.remindersEnabled: 'ચાલુ',
  L10nKeys.remindersMedicine: 'દવા',
  L10nKeys.remindersAppointment: 'મુલાકાત',
  L10nKeys.remindersRoutine: 'રોજિંદી દિનચર્યા',

  L10nKeys.dayMon: 'સોમ',
  L10nKeys.dayTue: 'મંગળ',
  L10nKeys.dayWed: 'બુધ',
  L10nKeys.dayThu: 'ગુરુ',
  L10nKeys.dayFri: 'શુક્ર',
  L10nKeys.daySat: 'શનિ',
  L10nKeys.daySun: 'રવિ',

  L10nKeys.sosTitle: 'કટોકટી મદદ',
  L10nKeys.sosExplain: 'દબાવીને પકડી રાખો. માઈન્ડકેર તમારા કટોકટી સંપર્કોમાં એક પછી એક જાણ કરશે. આ કટોકટી સેવા (જેમ કે ૧૧૨) નથી.',
  L10nKeys.sosHold: 'મદદ માટે દબાવીને પકડી રાખો',
  L10nKeys.sosHoldBody: 'દબાવીને પકડી રાખો…',
  L10nKeys.sosActiveTitle: 'મદદ સાથે સંપર્ક થઈ રહ્યો છે',
  L10nKeys.sosActiveBody: 'તમારા પરિવારને જાણ કરવામાં આવી છે. જો તેઓ જવાબ ન આપે તો આગલા સંપર્કને બોલાવવામાં આવશે.',
  L10nKeys.sosContacting: 'સંપર્ક થઈ રહ્યો છે',
  L10nKeys.sosContactFamily: 'પરિવારનો સંપર્ક',
  L10nKeys.sosContacted: 'સંપર્ક થયો',
  L10nKeys.sosWaitingResponse: 'જવાબની રાહ…',
  L10nKeys.sosEscalating: 'આગલી વ્યક્તિનો સંપર્ક…',
  L10nKeys.sosCancelled: 'મદદની વિનંતી રદ થઈ',
  L10nKeys.sosCancelAction: 'મદદની વિનંતી રદ કરો',
  L10nKeys.sosDone: 'થઈ ગયું',
  L10nKeys.sosHelpOnWay: 'કોઈ તમારી સાથે જલદી હાજર થશે. 🧡',
  L10nKeys.sosNoContacts: 'હજી કટોકટી સંપર્કો નથી',
  L10nKeys.sosNoContactsBody: 'કૃપા કરીને પરિવારને કટોકટી સંપર્કો ઉમેરવા કહો.',
  L10nKeys.sosAddContact: 'સંપર્ક ઉમેરો',
  L10nKeys.sosDisclaimer: 'માઈન્ડકેર તમે પસંદ કરેલા સંપર્કોને જાણ કરે છે. તે અધિકૃત કટોકટી સેવાઓનો વિકલ્પ નથી.',
  L10nKeys.sosContactedPerson: 'પરિવારના સભ્યનો સંપર્ક થયો',
  L10nKeys.sosEscalatedTo: 'આગલા પરિવારના સભ્યનો સંપર્ક થયો',
  L10nKeys.sosAcknowledged: 'પરિવારના સભ્યે જવાબ આપ્યો છે. મદદ આવી રહી છે.',
  L10nKeys.sosNotSilent:
      'જો અમે મદદ ન મોકલી શકીએ તો અમે ક્યારેય દેખાવ નહીં કરીએ.',
  L10nKeys.sosAlertNotDelivered:
      'તમારો સંદેશ હજી મોકલી શકાયો નથી. અમે પ્રયત્ન કરતા રહીશું.',

  L10nKeys.careTitle: 'સંભાળ રાખનાર',
  L10nKeys.careDashboard: 'ઝાંખી',
  L10nKeys.carePatients: 'મારા દર્દીઓ',
  L10nKeys.careMemories: 'સંસ્મરણો',
  L10nKeys.careContacts: 'કટોકટી સંપર્કો',
  L10nKeys.careSettings: 'સેટિંગ્સ',
  L10nKeys.careAddMemory: 'સંસ્મરણ ઉમેરો',
  L10nKeys.careAddContact: 'સંપર્ક ઉમેરો',
  L10nKeys.careEngagement: 'સંલગ્નતા',
  L10nKeys.careActivitiesWeek: 'આ અઠવાડિયાની પ્રવૃત્તિઓ',
  L10nKeys.careGardenProgress: 'બગીચાની પ્રગતિ',
  L10nKeys.careRecentActivity: 'તાજેતરની પ્રવૃત્તિ',
  L10nKeys.careNoPatients: 'કોઈ દર્દી જોડાયેલા નથી',
  L10nKeys.careNoPatientsBody:
      'પરિવારના સભ્યને જોડવા કહો, અથવા દર્દી પ્રોફાઈલ ઉમેરો.',
  L10nKeys.careAddPatient: 'દર્દી ઉમેરો',
  L10nKeys.carePerformanceNote: 'હાલમાં આ વ્યક્તિનું પ્રવૃત્તિ પ્રદર્શન તેમના સામાન્ય સ્તર કરતાં થોડું ઓછું છે.',
  L10nKeys.careUploadPhoto: 'ફોટો અપલોડ કરો',
  L10nKeys.careRecordVoice: 'અવાજ રેકોર્ડ કરો',
  L10nKeys.careWriteMemory: 'સંસ્મરણ લખો',
  L10nKeys.careMemoryTitle: 'શીર્ષક',
  L10nKeys.careMemoryCaption: 'કૅપ્શન',
  L10nKeys.careMemoryRelation: 'આમાં કોણ છે? (સંબંધ)',
  L10nKeys.careMemoryCategory: 'શ્રેણી',
  L10nKeys.careContactName: 'નામ',
  L10nKeys.careContactPhone: 'ફોન નંબર',
  L10nKeys.careContactPriority: 'કૉલ ક્રમ',
  L10nKeys.careContactRelation: 'સંબંધ',
  L10nKeys.careEscalationTimeout: 'આગલા સંપર્ક પહેલાંની મિનિટો',
  L10nKeys.careIncidentStatus: 'સ્થિતિ',
  L10nKeys.careAckSos: 'હું જવાબ આપી રહ્યો છું',
  L10nKeys.careResponding: 'જવાબ આપી રહ્યા છે',
  L10nKeys.careActiveAlerts: 'સક્રિય ચેતવણીઓ',

  L10nKeys.syncSavingOffline: 'ઓફલાઈન',
  L10nKeys.syncSavingOfflineBody: 'તમારી પ્રવૃત્તિઓ આ ઉપકરણ પર સુરક્ષિત છે.',
  L10nKeys.syncSynced: 'સિંક થયું',
  L10nKeys.syncInfo: 'તમારી માહિતી સિંક થઈ ગઈ છે.',
  L10nKeys.syncPending: 'સિંકની રાહ',

  L10nKeys.errorGeneric: 'કંઈક ખોટું થયું',
  L10nKeys.errorGenericBody:
      'તમારી પ્રગતિ સુરક્ષિત છે. કૃપા કરીને ફરી પ્રયત્ન કરો.',
  L10nKeys.errorAudio: 'આ ઉપકરણ પર અવાજ ચાલી શક્યો નથી.',
  L10nKeys.errorPermission: 'આ માટે ઉપકરણની પરવાનગી જરૂરી છે.',
  L10nKeys.errorNoInternetAction:
      'ઈન્ટરનેટની જરૂર નથી — તે પહેલા અહીં જ સાચવાય છે.',

  L10nKeys.demoWelcome: 'ડેમો જુઓ',
  L10nKeys.demoExplain:
      'તમે જોઈ શકો તે માટે નમૂના પરિવાર અને સંસ્મરણો ઉમેરાશે.',
  L10nKeys.demoLoad: 'ડેમો બગીચો લોડ કરો',

  L10nKeys.unitsPoints: 'ગુણ',
  L10nKeys.teaserChai: 'ચા બનાવીએ.',
  L10nKeys.familiarityName: 'આશા',
  L10nKeys.regionMap: 'મારો વિસ્તાર',
  L10nKeys.regionChoose: 'તમારો વિસ્તાર પસંદ કરો',
  L10nKeys.regionIndia: 'ભારત',
  L10nKeys.importantMemory: 'મહત્વનું સંસ્મરણ',
  L10nKeys.growing: 'વધી રહ્યું છે',
  L10nKeys.blooming: 'ખીલી રહ્યું છે',
  L10nKeys.mature: 'પરિપક્વ',
  L10nKeys.noVoice: 'આ ઉપકરણ પર અવાજ ઉપલબ્ધ નથી.',
  L10nKeys.optional: 'વૈકલ્પિક',

  L10nKeys.langChoose: 'ભાષા પસંદ કરો',
  L10nKeys.langPrimary: 'મુખ્ય',
  L10nKeys.langNorthEast: 'ઈશાન ભારત',
  L10nKeys.langMajor: 'ભારતની મુખ્ય ભાષાઓ',

  L10nKeys.authSignUpTitle: 'તમારું એકાઉન્ટ બનાવો',
  L10nKeys.authSignUpBody: 'આ માઈન્ડકેર પ્રોફાઈલ તમારા ઉપકરણ પર સુરક્ષિત રહે છે. ફક્ત તમે જ ખોલી શકો તે માટે યુઝરનામ અને પાસવર્ડ મૂકો.',
  L10nKeys.authLoginTitle: 'પાછા આવવા બદલ આભાર',
  L10nKeys.authLoginBody:
      'તમારો બગીચો ખોલવા માટે યુઝરનામ અને પાસવર્ડથી સાઈન ઇન કરો.',
  L10nKeys.authUsername: 'યુઝરનામ',
  L10nKeys.authUsernameHint: 'ઉદા: ranu123',
  L10nKeys.authDisplayName: 'તમારું નામ',
  L10nKeys.authPassword: 'પાસવર્ડ',
  L10nKeys.authPasswordHint: 'ઓછામાં ઓછા ૬ અક્ષરો',
  L10nKeys.authConfirmPassword: 'પાસવર્ડની પુષ્ટિ કરો',
  L10nKeys.authRoleQuestion: 'આ પ્રોફાઈલ કોના માટે છે…',
  L10nKeys.authRolePatient: 'મારા માટે',
  L10nKeys.authRoleCaregiver: 'પરિવારના સભ્ય માટે',
  L10nKeys.authCreate: 'એકાઉન્ટ બનાવો',
  L10nKeys.authSignIn: 'સાઈન ઇન',
  L10nKeys.authSignOut: 'સાઈન આઉટ',
  L10nKeys.authAccount: 'એકાઉન્ટ',
  L10nKeys.caregiverTitle: 'સંભાળ રાખનાર',
  L10nKeys.caregiverNotLinked: 'હજી કોઈ સંભાળ રાખનાર જોડાયેલ નથી',
  L10nKeys.authBadCredentials: 'યુઝરનામ કે પાસવર્ડ ખોટો છે.',
  L10nKeys.authUsernameTaken: 'આ યુઝરનામ આ ઉપકરણ પર પહેલેથી વપરાયેલું છે.',
  L10nKeys.authPasswordMismatch: 'પાસવર્ડ મેળ ખાતા નથી.',
  L10nKeys.authUsernameShort: 'યુઝરનામ ઓછામાં ઓછું ૩ અક્ષરોનું હોવું જોઈએ.',
  L10nKeys.authUsernameInvalid:
      'ફક્ત અક્ષરો, સંખ્યાઓ, ડોટ, ડેશ કે અંડરસ્કોર વાપરો.',
  L10nKeys.authPasswordShort: 'પાસવર્ડ ઓછામાં ઓછો ૬ અક્ષરોનો હોવો જોઈએ.',
  L10nKeys.authNameRequired: 'કૃપા કરીને નામ દાખલ કરો.',
  L10nKeys.authSignOutConfirm: 'આ પ્રોફાઈલમાંથી સાઈન આઉટ થવું છે?',
  L10nKeys.screenTitle: 'ઝડપી યાદશક્તિ તપાસ',
  L10nKeys.screenIntro: 'અમે દર્દી વિશે થોડા ટૂંકા પ્રશ્નો પૂછીશું. છેલ્લા થોડા મહિનામાં તેઓ કેવાં હતાં તે વિચારો.',
  L10nKeys.screenNotSure: 'ખાતરી નથી',
  L10nKeys.screenFinish: 'મારું પરિણામ જુઓ',
  L10nKeys.screenSkip: 'હમણાં નહીં',
  L10nKeys.screenResultBack: 'થઈ ગયું',
  L10nKeys.screenCheckAgain: 'ફરી તપાસો',
  L10nKeys.screenStartCheckup: 'તપાસ શરૂ કરો',
  L10nKeys.screenSkipped: 'તપાસ છોડી દેવામાં આવી',
  L10nKeys.screenStatusGood: 'બધું બરાબર લાગે છે',
  L10nKeys.screenStatusGoodBody: 'કોઈ મોટી ચિંતા જોવા મળી નથી. રોજની પ્રવૃત્તિઓ ચાલુ રાખો, અને કંઈ બદલાય તો કોઈ પણ વખતે ફરી તપાસ કરી શકાય.',
  L10nKeys.screenStatusWatch: 'કેટલાક ફેરફાર જોવા મળ્યા',
  L10nKeys.screenStatusWatchBody: 'ભૂલી જવાની થોડી ક્ષણો જોવા મળી. આ ઉંમર સાથે સામાન્ય છે, પણ નજર રાખો અને આગલી ડોક્ટર મુલાકાતે જણાવો.',
  L10nKeys.screenStatusDoctor: 'કૃપા કરીને તપાસ કરાવો',
  L10nKeys.screenStatusDoctorBody: 'કેટલાક ચિહ્નો જોવા મળ્યા જેમાં ધ્યાનની જરૂર પડી શકે. કૃપા કરીને આ ડોક્ટર અથવા ક્લિનિક સાથે શેર કરો જેથી તેઓ મદદ કરી શકે.',
  L10nKeys.screenRarely: 'ભાગ્યે જ',
  L10nKeys.screenSometimes: 'ક્યારેક ક્યારેક',
  L10nKeys.screenFrequently: 'વારંવાર',
  L10nKeys.screenVeryFrequently: 'ખૂબ વારંવાર',
  L10nKeys.screenQ01: 'શું તેમને તાજેતરની ઘટનાઓ યાદ રાખવામાં મુશ્કેલી પડે છે?',
  L10nKeys.screenQ02: 'શું તેઓ તે જ પ્રશ્નો કે વાર્તાઓ વારંવાર કરે છે?',
  L10nKeys.screenQ03: 'શું તેઓ પરિચિત લોકોના નામ ભૂલી જાય છે?',
  L10nKeys.screenQ04: 'શું તેમને પરિચિત ચહેરા ઓળખવામાં મુશ્કેલી પડે છે?',
  L10nKeys.screenQ05: 'શું તેઓ મુલાકાતો કે મહત્વની ઘટનાઓ ભૂલી જાય છે?',
  L10nKeys.screenQ06: 'શું તેમને યોગ્ય શબ્દો મળવામાં મુશ્કેલી પડે છે?',
  L10nKeys.screenQ07: 'શું તેઓ પોતે ક્યાં છે તે સમજવામાં ગૂંચવાય જાય છે?',
  L10nKeys.screenQ08:
      'શું તેમને રોજની પ્રવૃત્તિઓ માટે યાદ અપાવવાની જરૂર પડે છે?',
  L10nKeys.screenQ09: 'શું તેમને દવાઓ સંભાળવામાં મુશ્કેલી પડે છે?',
  L10nKeys.screenQ10: 'શું તેઓ ગૂંચવાય ત્યારે ચિંતિત કે હેરાન થાય છે?',
  L10nKeys.screenQ11: 'શું તેમને વાતચીત સમજવામાં મુશ્કેલી પડે છે?',
  L10nKeys.screenQ12: 'શું તેમને પરિચિત કાર્યો પૂરા કરવામાં મુશ્કેલી પડે છે?',
  L10nKeys.screenQ13:
      'શું તેઓ ભૂલી જાય છે કે રોજની ચીજો ક્યાં રાખવામાં આવે છે?',
  L10nKeys.screenQ14: 'શું તેમને સૂચનાઓ યાદ રાખવામાં મુશ્કેલી પડે છે?',
  L10nKeys.screenQ15:
      'શું તેમને બહુ-પગલાંવાળી પ્રવૃત્તિઓ કરવામાં મુશ્કેલી પડે છે?',

  L10nKeys.careDashboardSubtitle: 'કુટુંબની સંભાળ',
  L10nKeys.careSosLive: 'લાઇવ ચેતવણી',
  L10nKeys.careSosRespondedBy: '{name} એ જવાબ આપ્યો',
  L10nKeys.careLinkTitle: 'પરિવારના સભ્ય સાથે જોડાઓ',
  L10nKeys.careLinkBody: 'તમારા પ્રિયજનને તેમના ફોન પર બતાવવામાં આવેલ 6-અક્ષરનો પારિવારિક કોડ પૂછો, પછી જોડાઓ.',
  L10nKeys.careLinkCode: 'પારિવારિક કોડ',
  L10nKeys.careLinkCodeHint: 'દા.ત. A1B2C3',
  L10nKeys.careLinkConnect: 'જોડાઓ',
  L10nKeys.careLinkDone: 'જોડાયેલ',
  L10nKeys.careLinkSuccess:
      '{name} સાથે જોડાયેલ! યાદો અને ચેતવણીઓ હવે સમન્વયિત થશે.',
  L10nKeys.careLinkFailed:
      'જોડી શકાયું નથી. કૃપા કરીને કોડ તપાસીને ફરી પ્રયાસ કરો.',
  L10nKeys.careTrendsTitle: 'AI વલણો',
  L10nKeys.careTrendsBody: 'પ્રવૃત્તિ પ્રકાર મુજબ દૈનિક ચોકસાઈ',
  L10nKeys.careTrendsNoData:
      'હજુ કોઈ પ્રવૃત્તિ નથી — વલણો જોવા માટે એક કસરત પૂર્ણ કરો.',
  L10nKeys.careAiDifficulty: 'સ્વયંસંચાલિત સમાયોજિત મુશ્કેલી',
  L10nKeys.careAiAccuracy: 'મોડેલ ચોકસાઈ',
  L10nKeys.careAiRealSessions: 'વાસ્તવિક સત્રો',
  L10nKeys.careAiDemoSessions: 'ડેમો સત્રો',
  L10nKeys.careNavGames: 'રમતો',
  L10nKeys.careNavRoutine: 'દિનચર્યા',
  L10nKeys.careGreetSubtitle: 'આજે {name} કેવું કરી રહ્યા છે તે અહીં છે.',
  L10nKeys.careNotifEmpty: 'કોઈ નવી સૂચનાઓ નથી',
  L10nKeys.careWellnessScore: 'જ્ઞાનાત્મક સુખાકારી સ્કોર',
  L10nKeys.careStatusStable: 'સ્થિર',
  L10nKeys.careStatusAttention: 'ધ્યાનની જરૂર છે',
  L10nKeys.careLastSynced: 'છેલ્લે સમન્વયિત {time}',
  L10nKeys.careMinAgo: '{n} મિનિટ પહેલાં',
  L10nKeys.careGamesWeek: 'આ અઠવાડિયે રમતો',
  L10nKeys.careRoutineCompletion: 'દિનચર્યા પૂર્ણતા',
  L10nKeys.careCurrentStreak: 'હાલનો સિલસિલો',
  L10nKeys.careMoodCheckins: 'મૂડ ચેક-ઇન્સ',
  L10nKeys.careDayUnit: 'દિવસ',
  L10nKeys.careDaysUnit: 'દિવસો',
  L10nKeys.careActivityTitle: 'સાપ્તાહિક પ્રવૃત્તિ',
  L10nKeys.careWeekly: 'સાપ્તાહિક',
  L10nKeys.careMonthly: 'માસિક',
  L10nKeys.careNoActivityWeek: 'આ અઠવાડિયે હજી કોઈ પ્રવૃત્તિ નોંધાઈ નથી.',
  L10nKeys.careMoodTitle: 'મૂડ',
  L10nKeys.careMoodHappy: 'ખુશ',
  L10nKeys.careMoodCalm: 'શાંત',
  L10nKeys.careMoodNeutral: 'તટસ્થ',
  L10nKeys.careMoodLow: 'નીચા',
  L10nKeys.careMood7Days: 'છેલ્લા 7 દિવસ',
  L10nKeys.careMoodInsight: '{name} આ અઠવાડિયે મોટે ભાગે શાંત રહ્યા છે, છેલ્લા બે દિવસમાં થોડો ઘટાડો જોવા મળ્યો છે.',
  L10nKeys.careMoodNoData: 'આ અઠવાડિયે હજી કોઈ મૂડ ચેક-ઇન નથી.',
  L10nKeys.careSkillsTitle: 'જ્ઞાનાત્મક કુશળતા',
  L10nKeys.careSkillMemory: 'યાદશક્તિ',
  L10nKeys.careSkillAttention: 'ધ્યાન',
  L10nKeys.careSkillLanguage: 'ભાષા',
  L10nKeys.careSkillReasoning: 'તર્ક',
  L10nKeys.careSkillProcessing: 'પ્રક્રિયા ગતિ',
  L10nKeys.careInsightToday: 'આજની સમજ',
  L10nKeys.careInsightBody: 'રોબર્ટ તેમની સવારની દિનચર્યા પછી યાદશક્તિની પ્રવૃત્તિઓમાં સુસંગત રહ્યા છે. છેલ્લા બે દિવસમાં તેમનો મૂડ થોડો ઓછો રહ્યો છે.',
  L10nKeys.careInsightBodyReal: 'આ અઠવાડિયે {name}એ {count} જ્ઞાનાત્મક સત્રો પૂર્ણ કર્યા (લક્ષ્ય {goal}) અને {streak}-દિવસનો સિલસિલો જાળવી રહ્યા છે.',
  L10nKeys.careViewDetails: 'વિગતો જુઓ',
  L10nKeys.careInsightDisclaimer:
      'આ માહિતીમાંથી એક હળવું અવલોકન છે — તબીબી નિદાન નથી.',
  L10nKeys.careAttentionTitle: 'તમારા ધ્યાનની જરૂર છે',
  L10nKeys.careAttentionEmpty: 'હમણાં કંઈપણ તમારા ધ્યાનની જરૂર નથી.',
  L10nKeys.careAlertSos: '{name}એ SOS બટન દબાવ્યું',
  L10nKeys.careAlertRoutineMissed: 'ગઈકાલે દિનચર્યા ચૂકી ગઈ',
  L10nKeys.careAlertMoodDown: 'છેલ્લા બે દિવસમાં મૂડ ઘટ્યો',
  L10nKeys.careAlertSessionPending: 'આજે જ્ઞાનાત્મક સત્ર પૂર્ણ થયું નથી',
  L10nKeys.careAlertSeverityHigh: 'ઊંચી',
  L10nKeys.careAlertSeverityMedium: 'મધ્યમ',
  L10nKeys.careAlertSeverityLow: 'નીચી',
  L10nKeys.careWeeklySummary: 'સાપ્તાહિક સારાંશ',
  L10nKeys.careSessionsCompleted: 'પૂર્ણ થયેલા સત્રો',
  L10nKeys.careAvgSessionDuration: 'સરેરાશ સત્ર અવધિ',
  L10nKeys.careRoutineAdherence: 'દિનચર્યાનું પાલન',
  L10nKeys.careMoodTrend: 'મૂડ પ્રવાહ',
  L10nKeys.careMoodTrendSlightlyDown: 'થોડો નીચા',
  L10nKeys.careMoodTrendStable: 'સ્થિર',
  L10nKeys.careMoodTrendUp: 'સુધારો થઈ રહ્યો',
  L10nKeys.careVsLastWeek: 'ગયા અઠવાડિયાની સરખામણીમાં',
  L10nKeys.careSyncedJustNow: 'હમણાં જ સમન્વયિત થયું',
  L10nKeys.careOfflineWaiting:
      'ઓફલાઇન · સમન્વય માટે {count} પ્રવૃત્તિઓ રાહ જુએ છે',
  L10nKeys.careComingSoon: 'ટૂંક સમયમાં આવી રહ્યું છે',
  L10nKeys.careHomeSoon: '{name}ના દિવસની ઝડપી ઝલક અહીં દેખાશે.',
  L10nKeys.careGamesSoon: 'રમતો અને સત્ર ઇતિહાસ અહીં દેખાશે.',
  L10nKeys.careRoutineSoon: 'દર્દીની દૈનિક દિનચર્યા અહીં દેખાશે.',
  L10nKeys.careProfileSoon: 'સંભાળકર્તાની પ્રોફાઇલ અને સેટિંગ્સ અહીં દેખાશે.',
  L10nKeys.serverPairingTitle: 'પારિવારિક કોડ',
  L10nKeys.serverPairingBody:
      'આ કોડ કોઈ સંભાળકર્તા સાથે શેર કરો જેથી તેઓ તમારી સાથે જોડાઈ શકે.',
  L10nKeys.serverUnlinked: 'સર્વર સાથે જોડાયેલ નથી',
  L10nKeys.serverLinked: 'સર્વર સાથે જોડાયેલ',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
