import '../l10n_keys.dart';

/// Punjabi dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsPa = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'ਤੁਹਾਡੀਆਂ ਯਾਦਾਂ ਦਾ ਸਾਥੀ',
  L10nKeys.back: 'ਪਿੱਛੇ',
  L10nKeys.next: 'ਅੱਗੇ',
  L10nKeys.continueText: 'ਅੱਗੇ ਜਾਓ',
  L10nKeys.skip: 'ਛੱਡੋ',
  L10nKeys.done: 'ਹੋ ਗਿਆ',
  L10nKeys.cancel: 'ਰੱਦ ਕਰੋ',
  L10nKeys.yes: 'ਹਾਂ',
  L10nKeys.no: 'ਨਹੀਂ',
  L10nKeys.save: 'ਸੰਭਾਲੋ',
  L10nKeys.close: 'ਬੰਦ ਕਰੋ',
  L10nKeys.retry: 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  L10nKeys.add: 'ਜੋੜੋ',
  L10nKeys.edit: 'ਬਦਲੋ',
  L10nKeys.remove: 'ਹਟਾਓ',
  L10nKeys.search: 'ਖੋਜ',
  L10nKeys.today: 'ਅੱਜ',
  L10nKeys.offline: 'ਆਫਲਾਈਨ',
  L10nKeys.online: 'ਆਨਲਾਈਨ',

  L10nKeys.goodMorning: 'ਸ਼ੁਭ ਸਵੇਰ',
  L10nKeys.goodAfternoon: 'ਨਮਸਕਾਰ',
  L10nKeys.goodEvening: 'ਸ਼ੁਭ ਸ਼ਾਮ',
  L10nKeys.goodNight: 'ਸ਼ੁਭ ਰਾਤ',

  L10nKeys.navHome: 'ਘਰ',
  L10nKeys.navGarden: 'ਬਾਗ',
  L10nKeys.navActivities: 'ਸਰਗਰਮੀਆਂ',
  L10nKeys.navMemories: 'ਯਾਦਾਂ',
  L10nKeys.navProfile: 'ਪ੍ਰੋਫਾਈਲ',
  L10nKeys.navMystery: 'ਅੱਜ ਦੀ ਯਾਦ',

  L10nKeys.onboardingWelcomeTitle: 'ਤੁਹਾਡੀਆਂ ਯਾਦਾਂ ਦਾ ਨਰਮ ਸਾਥੀ',
  L10nKeys.onboardingWelcomeBody: 'ਮਾਈਂਡਕੇਅਰ ਏਐਨਈਆਰ ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਵੀ ਯਾਦ ਰੱਖਣ, ਖੇਡਣ ਅਤੇ ਪਰਿਵਾਰ ਨਾਲ ਜੁੜੇ ਰਹਿਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।',
  L10nKeys.onboardingNameTitle: 'ਅਸੀਂ ਤੁਹਾਨੂੰ ਕੀ ਕਹਿ ਕੇ ਬੁਲਾਈਏ?',
  L10nKeys.onboardingNameHint: 'ਤੁਹਾਡਾ ਨਾਮ',
  L10nKeys.onboardingRegionTitle: 'ਤੁਹਾਡਾ ਘਰ ਕਿੱਥੇ ਹੈ?',
  L10nKeys.onboardingRegionHint: 'ਸ਼ਹਿਰ ਜਾਂ ਪਿੰਡ',
  L10nKeys.onboardingRegionList: 'ਗੁਹਾਟੀ, ਸਿਲਚਰ, ਸ਼ਿਲਾਂਗ, ਅਗਰਤਲਾ, ਇੰਫਾਲ, ਆਈਜ਼ੌਲ, ਇਟਾਨਗਰ, ਕੋਹਿਮਾ, ਗੰਗਟੋਕ, ਡਿਬਰੂਗੜ੍ਹ, ਜੋਰਹਾਟ, ਤੁਹਾਡਾ ਸ਼ਹਿਰ',
  L10nKeys.onboardingLanguageTitle: 'ਤੁਹਾਨੂੰ ਕਿਹੜੀ ਭਾਸ਼ਾ ਪਸੰਦ ਆਵੇਗੀ?',
  L10nKeys.onboardingLanguageBody: 'ਤੁਸੀਂ ਇਹ ਕਦੇ ਵੀ ਬਦਲ ਸਕਦੇ ਹੋ।',
  L10nKeys.onboardingFamilyTitle: 'ਪਰਿਵਾਰ ਕੌਣ?',
  L10nKeys.onboardingFamilyBody: 'ਆਪਣੇ ਪਿਆਰੇ ਲੋਕਾਂ ਨੂੰ ਜੋੜੋ। ਅਸੀਂ ਉਨ੍ਹਾਂ ਦੇ ਫੋਟੋ ਅਤੇ ਆਵਾਜ਼ ਨਰਮ ਯਾਦਾਂ ਵਜੋਂ ਦਿਖਾਵਾਂਗੇ।',
  L10nKeys.onboardingAddFamily: 'ਪਰਿਵਾਰ ਦਾ ਮੈਂਬਰ ਜੋੜੋ',
  L10nKeys.onboardingEmergencyTitle: 'ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਅਸੀਂ ਕਿਸ ਨੂੰ ਬੁਲਾਈਏ?',
  L10nKeys.onboardingEmergencyBody: 'SOS ਬਟਨ ਦਬਾਉਣ ਨਾਲ ਮਾਈਂਡਕੇਅਰ ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਨੂੰ ਸੂਚਿਤ ਕਰਦਾ ਹੈ, ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ ਨੂੰ ਨਹੀਂ।',
  L10nKeys.onboardingEmergencyName: 'ਨਾਮ',
  L10nKeys.onboardingEmergencyPhone: 'ਫੋਨ ਨੰਬਰ',
  L10nKeys.onboardingEmergencyRelation: 'ਰਿਸ਼ਤਾ (ਧੀ, ਪੁੱਤਰ…)',
  L10nKeys.onboardingDoneTitle: 'ਤੁਹਾਡਾ ਬਾਗ ਤਿਆਰ ਹੈ!',
  L10nKeys.onboardingDoneBody:
      'ਛੋਟੀਆਂ ਸਰਗਰਮੀਆਂ ਪੂਰੀਆਂ ਕਰੋ ਅਤੇ ਆਪਣਾ ਬਾਗ ਵਧਦਾ ਦੇਖੋ। ਅਸੀਂ ਤੁਹਾਡੇ ਨਾਲ ਹਾਂ।',
  L10nKeys.onboardingStart: 'ਮੇਰਾ ਬਾਗ ਸ਼ੁਰੂ ਕਰੋ',

  L10nKeys.homeWhatsGrowing: 'ਅੱਜ ਕੀ ਵਧ ਰਿਹਾ ਹੈ?',
  L10nKeys.homeTodayActivity: 'ਅੱਜ ਦੀ ਛੋਟੀ ਸਰਗਰਮੀ',
  L10nKeys.homeActivityDuration: 'ਲਗਭਗ ੩ ਮਿੰਟ',
  L10nKeys.homeMinutes: 'ਮਿੰਟ',
  L10nKeys.homeMemoryOfDay: 'ਅੱਜ ਦੀ ਯਾਦ',
  L10nKeys.homeMemoryLocked: 'ਇੱਕ ਖਾਸ ਯਾਦ ਤੁਹਾਡੀ ਉਡੀਕ ਕਰ ਰਹੀ ਹੈ…',
  L10nKeys.homeMemoryUnlocked: 'ਇੱਕ ਯਾਦ ਖੁੱਲ੍ਹੀ!',
  L10nKeys.homeContinueActivity: 'ਸਰਗਰਮੀ ਜਾਰੀ ਰੱਖੋ',
  L10nKeys.homeFamilyMemory: 'ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਵੱਲੋਂ',
  L10nKeys.homeFamilyMemoryEmpty: 'ਪਰਿਵਾਰ ਦੀਆਂ ਯਾਦਾਂ ਇੱਥੇ ਦਿਖ ਸਕਦੀਆਂ ਹਨ।',
  L10nKeys.homeSos: 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ',
  L10nKeys.homeSosSubtitle: 'ਐਮਰਜੈਂਸੀ ਵਿੱਚ ਪਰਿਵਾਰ ਨਾਲ ਸੰਪਰਕ',
  L10nKeys.homeGardenPreview: 'ਤੁਹਾਡਾ ਬਾਗ',
  L10nKeys.homeEngine: 'ਮਾਈਂਡਕੇਅਰ ਸਾਥੀ',
  L10nKeys.homeEngineReady: 'ਤੁਹਾਡਾ ਸਹਾਇਕ ਤਿਆਰ ਹੈ।',
  L10nKeys.homeWelcomeBack: 'ਵਾਪਸੀ ਲਈ ਜੀ ਆਇਆਂ ਨੂੰ! ਚੱਲੋ ਬਾਗ ਅੱਗੇ ਵਧਾਈਏ। 🌸',
  L10nKeys.homeNoActivity: 'ਅੱਜ ਕੋਈ ਸਰਗਰਮੀ ਨਹੀਂ',
  L10nKeys.homeNoActivityBody: 'ਥੋੜਾ ਆਰਾਮ ਕਰੋ — ਜਾਂ ਕੋਈ ਮਨਪਸੰਦ ਸਰਗਰਮੀ ਚੁਣੋ। 🌻',

  L10nKeys.gardenTitle: 'ਮੇਰਾ ਯਾਦਾਂ ਦਾ ਬਾਗ',
  L10nKeys.gardenSectionAll: 'ਸਭ',
  L10nKeys.gardenSectionFamily: 'ਪਰਿਵਾਰ',
  L10nKeys.gardenSectionChildhood: 'ਬਚਪਨ',
  L10nKeys.gardenSectionPlaces: 'ਥਾਵਾਂ',
  L10nKeys.gardenSectionFestivals: 'ਤਿਉਹਾਰ',
  L10nKeys.gardenEmpty: 'ਤੁਹਾਡਾ ਬਾਗ ਹੁਣੇ ਸ਼ੁਰੂ ਹੋਇਆ ਹੈ',
  L10nKeys.gardenEmptyBody: 'ਪਹਿਲੀ ਸਰਗਰਮੀ ਪੂਰੀ ਕਰੋ, ਇੱਥੇ ਇੱਕ ਬੀਜ ਬੀਜਿਆ ਜਾਵੇਗਾ।',
  L10nKeys.gardenPoints: 'ਅੰਕ',
  L10nKeys.gardenLevel: 'ਪੱਧਰ',
  L10nKeys.gardenSeed: 'ਬੀਜ',
  L10nKeys.gardenPlant: 'ਪੌਦਾ',
  L10nKeys.gardenFlower: 'ਫੁੱਲ',
  L10nKeys.gardenTree: 'ਰੁੱਖ',
  L10nKeys.gardenMilestone: 'ਪੜਾਅ',
  L10nKeys.gardenGrowth: 'ਵਧ ਰਿਹਾ ਹੈ',
  L10nKeys.gardenDidYouKnow: 'ਹਰ ਪੂਰੀ ਹੋਈ ਸਰਗਰਮੀ ਨਾਲ ਤੁਹਾਡਾ ਬਾਗ ਵਧਦਾ ਹੈ।',
  L10nKeys.gardenPlantSeed: 'ਬੀਜ ਬੀਜੋ',

  L10nKeys.activitiesTitle: 'ਸਰਗਰਮੀਆਂ',
  L10nKeys.activitiesToday: 'ਅੱਜ',
  L10nKeys.activitiesLibrary: 'ਹੋਰ ਸਰਗਰਮੀਆਂ',
  L10nKeys.mainGamesTitle: 'ਮੁੱਖ ਖੇਡਾਂ',
  L10nKeys.activitiesStart: 'ਸ਼ੁਰੂ ਕਰੋ',
  L10nKeys.activitiesCompleted: 'ਪੂਰੀਆਂ',
  L10nKeys.activitiesInProgress: 'ਚੱਲ ਰਹੀਆਂ',
  L10nKeys.activitiesNotStarted: 'ਤਿਆਰ',
  L10nKeys.activityYoureDone: 'ਬਹੁਤ ਵਧੀਆ!',
  L10nKeys.activityPraise: 'ਤੁਸੀਂ ਬਾਗ ਨੂੰ ਥੋੜ੍ਹਾ ਜੀਵਨ ਦਿੱਤਾ। 🌱',
  L10nKeys.activityHint: 'ਸੁਰਾਗ ਚਾਹੀਦਾ ਹੈ?',
  L10nKeys.activityTryAgain: 'ਚੱਲੋ ਇਸ ਯਾਦ ਨੂੰ ਫਿਰ ਦੇਖੀਏ',
  L10nKeys.activityOptionsHint: 'ਆਪਣਾ ਜਵਾਬ ਚੁਣੋ',
  L10nKeys.activityTapToMatch: 'ਇਕੱਠੇ ਮਿਲਦੀ ਜੋੜੀ ਚੁਣੋ',
  L10nKeys.activityNext: 'ਅੱਗੇ',
  L10nKeys.activityFinish: 'ਖਤਮ',
  L10nKeys.activityGroupLetsAgain: 'ਚੱਲੋ ਇਹ ਫਿਰ ਦੇਖੀਏ',
  L10nKeys.activityGroupTogether: 'ਚੱਲੋ ਇਹ ਮਿਲ ਕੇ ਕਰੀਏ',
  L10nKeys.activityGreatJob: 'ਬਹੁਤ ਵਧੀਆ ਕੀਤਾ!',
  L10nKeys.activityKitchen: 'ਮੇਰੀ ਰਸੋਈ',
  L10nKeys.activityShopping: 'ਮੇਰੀ ਦੁਕਾਨ',
  L10nKeys.activityMatching: 'ਜੋੜੀ ਬਣਾਓ',
  L10nKeys.activitySequence: 'ਕ੍ਰਮ ਵਿੱਚ ਲਗਾਓ',
  L10nKeys.activityRecognition: 'ਇਹ ਕੀ ਹੈ?',
  L10nKeys.activityAssociation: 'ਕੀ ਇਕੱਠੇ ਚੱਲਦਾ ਹੈ?',
  L10nKeys.activityRecall: 'ਯਾਦ ਆਉਂਦਾ ਹੈ?',
  L10nKeys.activityAttention: 'ਲੱਭੋ',
  L10nKeys.activityDurationSuffix: 'ਮਿੰਟ',
  L10nKeys.activityTodayDone: 'ਅੱਜ ਦੀ ਸਰਗਰਮੀ ਪੂਰੀ',
  L10nKeys.activityTodayDoneBody:
      'ਤੁਹਾਡਾ ਬਾਗ ਵਧਿਆ। ਕੱਲ੍ਹ ਇੱਕ ਯਾਦ ਉਡੀਕ ਰਹੀ ਹੋਵੇਗੀ।',
  L10nKeys.activityGardenGrew: 'ਤੁਹਾਡਾ ਬਾਗ ਵਧਿਆ!',
  L10nKeys.activityMemoryUnlocked: 'ਇੱਕ ਯਾਦ ਖੁੱਲ੍ਹੀ',
  L10nKeys.activityReadAloud: 'ਉੱਚੀ ਪੜ੍ਹੋ',

  L10nKeys.kitchenTitle: 'ਚਾਹ ਬਣਾਈਏ',
  L10nKeys.kitchenMakeChai: 'ਚਾਹ ਬਣਾਉਣੀ',
  L10nKeys.kitchenMakeChaiPrompt: 'ਕਦਮ ਸਹੀ ਕ੍ਰਮ ਵਿੱਚ ਚੁਣੋ।',
  L10nKeys.kitchenSteps: 'ਕਦਮ',
  L10nKeys.kitchenTapInOrder: 'ਕਦਮ ਸਹੀ ਕ੍ਰਮ ਵਿੱਚ ਚੁਣੋ',
  L10nKeys.kitchenCorrectOrder: 'ਵਧੀਆ! ਚਾਹ ਤਿਆਰ!',
  L10nKeys.kitchenBreakfast: 'ਨਾਸ਼ਤਾ ਬਣਾਉਣਾ',
  L10nKeys.kitchenBreakfastHint: 'ਦਿਨ ਦੀ ਤਾਜ਼ਾ ਸ਼ੁਰੂਆਤ',
  L10nKeys.kitchenBreakfastPrompt: 'ਨਾਸ਼ਤੇ ਦੇ ਕਦਮ ਕ੍ਰਮ ਵਿੱਚ ਲਗਾਓ।',

  L10nKeys.shopTitle: 'ਮੇਰੀ ਦੁਕਾਨ',
  L10nKeys.shopGetMilkBread: 'ਬਰੈੱਡ ਅਤੇ ਦੁੱਧ',
  L10nKeys.shopGetMilkBreadPrompt: '₹੧੦੦ ਵਿੱਚ ਦੁੱਧ ਅਤੇ ਬਰੈੱਡ ਖਰੀਦੋ।',
  L10nKeys.shopBudget: 'ਬਜਟ',
  L10nKeys.shopBasket: 'ਤੁਹਾਡੀ ਟੋਕਰੀ',
  L10nKeys.shopTotal: 'ਕੁੱਲ',
  L10nKeys.shopWithinBudget: 'ਬਜਟ ਵਿੱਚ!',
  L10nKeys.shopOverBudget: 'ਬਜਟ ਤੋਂ ਬਾਹਰ — ਫਿਰ ਦੇਖੋ',
  L10nKeys.shopCheckout: 'ਪੂਰਾ ਕਰੋ ਅਤੇ ਭੁਗਤਾਨ ਕਰੋ',
  L10nKeys.shopBuy: 'ਟੋਕਰੀ ਵਿੱਚ ਪਾਓ',
  L10nKeys.shopSell: 'ਹਟਾਓ',
  L10nKeys.shopVeggies: 'ਰਾਤ ਦੇ ਖਾਣੇ ਲਈ ਸਬਜ਼ੀਆਂ',
  L10nKeys.shopVeggiesPrompt: '₹੬੦ ਵਿੱਚ ਆਲੂ ਅਤੇ ਪਿਆਜ਼ ਖਰੀਦੋ।',
  L10nKeys.recKitchenItem: 'ਇਹ ਕਿਹੜਾ ਹੈ?',
  L10nKeys.recKitchenItemPrompt:
      'ਬਾਜ਼ਾਰ ਤੋਂ ਸਮਾਨ ਲਿਆਉਣ ਲਈ ਇਨ੍ਹਾਂ ਵਿੱਚੋਂ ਕਿਹੜਾ ਵਰਤਦੇ ਹਾਂ?',
  L10nKeys.recCurrency: 'ਥੋੜ੍ਹੇ ਪੈਸੇ',
  L10nKeys.recCurrencyPrompt: 'ਕਿਹੜਾ ਨੋਟ ₹੨੦ ਹੈ?',
  L10nKeys.matchFestival: 'ਤਿਉਹਾਰ ਮਿਲਾਓ',
  L10nKeys.matchFestivalPrompt: 'ਹਰ ਤਿਉਹਾਰ ਨੂੰ ਉਸਦੇ ਖਾਸ ਪਕਵਾਨ ਨਾਲ ਮਿਲਾਓ।',
  L10nKeys.matchObjectUse: 'ਜੋੜੀ ਬਣਾਓ',
  L10nKeys.matchObjectUsePrompt: 'ਹਰ ਵਸਤੂ ਨੂੰ ਵਰਤੋਂ ਦੇ ਸਮੇਂ ਨਾਲ ਮਿਲਾਓ।',
  L10nKeys.seqMorning: 'ਸਵੇਰ ਦੀ ਰੁਟੀਨ',
  L10nKeys.seqMorningPrompt: 'ਆਪਣੀ ਸਵੇਰ ਦੀ ਰੁਟੀਨ ਕ੍ਰਮ ਵਿੱਚ ਲਗਾਓ।',
  L10nKeys.seqRoute: 'ਸਵੇਰ ਦਾ ਸਫ਼ਰ',
  L10nKeys.seqRoutePrompt: 'ਬਾਜ਼ਾਰ ਤੱਕ ਦਾ ਸਫ਼ਰ ਕ੍ਰਮ ਵਿੱਚ ਲਗਾਓ।',
  L10nKeys.assoRegion: 'ਇੱਥੇ ਕੀ ਹੈ?',
  L10nKeys.assoRegionPrompt: 'ਅਸਾਮ ਕਿਸ ਲਈ ਮਸ਼ਹੂਰ ਹੈ?',
  L10nKeys.assoHarvest: 'ਮਿੱਠਾ ਫਲ',
  L10nKeys.assoHarvestPrompt: 'ਕਿਸ ਫਲ ਨੂੰ ਗਰਮੀਆਂ ਦਾ ਰਾਜਾ ਕਹਿੰਦੇ ਹਨ?',
  L10nKeys.attnVeg: 'ਗਾਜਰ ਲੱਭੋ',
  L10nKeys.attnVegPrompt: 'ਕੀ ਤੁਸੀਂ ਗਾਜਰ ਲੱਭ ਸਕਦੇ ਹੋ?',
  L10nKeys.recallSong: 'ਇੱਕ ਜਾਣੂ ਗੀਤ',
  L10nKeys.recallSongPrompt: 'ਬਿਹੂ ਵਿੱਚ ਨੱਚਦਿਆਂ ਕਿਹੜਾ ਗੀਤ ਵਜਦਾ ਹੈ?',
  L10nKeys.activityPairs: 'ਜੋੜੀ ਲੱਭੋ',
  L10nKeys.activitySequenceRecall: 'ਕ੍ਰਮ ਯਾਦ ਰੱਖੋ',
  L10nKeys.activityFindChanged: 'ਕੀ ਬਦਲਿਆ?',
  L10nKeys.pairsFruits: 'ਬਾਜ਼ਾਰ ਦੇ ਫਲ',
  L10nKeys.pairsKitchen: 'ਰਸੋਈ ਦੀਆਂ ਚੀਜ਼ਾਂ',
  L10nKeys.pairsRemember: 'ਸਾਰੀਆਂ ਕਾਰਡ ਧਿਆਨ ਨਾਲ ਵੇਖੋ, ਫਿਰ ਮਿਲਦੀ ਜੋੜੀ ਲੱਭੋ।',
  L10nKeys.pairsStart: 'ਕਾਰਡ ਲੁਕੋ ਕੇ ਸ਼ੁਰੂ ਕਰੋ',
  L10nKeys.pairsFound: 'ਜੋੜੀ ਮਿਲ ਗਈ!',
  L10nKeys.seqRecallItems: 'ਰੋਜ਼ ਦੀਆਂ ਚੀਜ਼ਾਂ',
  L10nKeys.seqRecallNumbers: 'ਕ੍ਰਮ ਵਿੱਚ ਅੰਕ',
  L10nKeys.seqRecallWatch: 'ਕਾਰਡ ਧਿਆਨ ਨਾਲ ਵੇਖੋ – ਹਰ ਇੱਕ ਕ੍ਰਮ ਵਿੱਚ ਚਮਕੇਗਾ।',
  L10nKeys.seqRecallRepeat: 'ਹੁਣ ਉਸੇ ਕ੍ਰਮ ਵਿੱਚ ਕਾਰਡ ਦਬਾਓ ਜਿਵੇਂ ਤੁਸੀਂ ਵੇਖਿਆ।',
  L10nKeys.changeMarket: 'ਫਲਾਂ ਦੀ ਟੋਕਰੀ',
  L10nKeys.changeFestival: 'ਤਿਉਹਾਰ ਦੇ ਦੀਵੇ',
  L10nKeys.changeRemember: 'ਇਹ ਤਸਵੀਰਾਂ ਧਿਆਨ ਨਾਲ ਯਾਦ ਰੱਖੋ।',
  L10nKeys.changeFind: 'ਇੱਕ ਤਸਵੀਰ ਬਦਲੀ ਹੈ। ਵੱਖਰੀ ਤਸਵੀਰ ਲੱਭੋ।',
  L10nKeys.changeCorrect: 'ਸ਼ਾਬਾਸ਼! ਓਹੀ ਬਦਲੀ ਸੀ।',

  L10nKeys.mysteryTitle: 'ਅੱਜ ਦੀ ਖਾਸ ਯਾਦ',
  L10nKeys.mysteryLocked: 'ਇੱਕ ਖਾਸ ਯਾਦ ਤੁਹਾਡੀ ਉਡੀਕ ਕਰ ਰਹੀ ਹੈ…',
  L10nKeys.mysteryLockedBody:
      'ਅੱਜ ੨–੩ ਛੋਟੀਆਂ ਸਰਗਰਮੀਆਂ ਕਰੋ; ਸ਼ਾਇਦ ਇਹ ਖੁੱਲ੍ਹ ਜਾਵੇ। ਕੀ ਹੋਵੇਗਾ?',
  L10nKeys.mysteryUnlocked: 'ਤੁਹਾਡੀ ਖਾਸ ਯਾਦ ਇੱਥੇ ਹੈ!',
  L10nKeys.mysteryUnlockedBody: 'ਇਹ ਯਾਦ ਸਿਰਫ਼ ਤੁਹਾਡੇ ਲਈ ਹੈ। ਆਪਣਾ ਸਮਾਂ ਲਓ। 🌸',
  L10nKeys.mysteryCuriosity: 'ਅੱਜ ਕੀ ਖੁੱਲ੍ਹੇਗਾ?',
  L10nKeys.mysteryOpen: 'ਯਾਦ ਖੋਲ੍ਹੋ',

  L10nKeys.memoriesTitle: 'ਮੇਰੀਆਂ ਯਾਦਾਂ',
  L10nKeys.memoriesEmpty: 'ਹਾਲੇ ਕੋਈ ਯਾਦ ਨਹੀਂ',
  L10nKeys.memoriesEmptyBody:
      'ਤੁਹਾਡਾ ਪਰਿਵਾਰ ਫੋਟੋ ਅਤੇ ਆਵਾਜ਼ ਸੁਨੇਹੇ ਜੋੜ ਸਕਦਾ ਹੈ। ਮਿਲਦੇ ਹੀ ਇੱਥੇ ਦਿਖਣਗੇ।',
  L10nKeys.memoriesFamily: 'ਪਰਿਵਾਰ',
  L10nKeys.memoriesPlaces: 'ਥਾਵਾਂ',
  L10nKeys.memoriesFestivals: 'ਤਿਉਹਾਰ',
  L10nKeys.memoriesChildhood: 'ਬਚਪਨ',
  L10nKeys.memoriesKindPhoto: 'ਫੋਟੋ',
  L10nKeys.memoriesKindVoice: 'ਆਵਾਜ਼ ਸੁਨੇਹਾ',
  L10nKeys.memoriesKindText: 'ਕਹਾਣੀ',
  L10nKeys.memoriesKindSound: 'ਆਵਾਜ਼',
  L10nKeys.memoriesKindPlace: 'ਥਾਂ',
  L10nKeys.memoriesAddedBy: 'ਜੋੜਿਆ',
  L10nKeys.memoriesWhoIsThis: 'ਇਹ ਕੌਣ ਹਨ?',
  L10nKeys.memoriesPlayVoice: 'ਸੁਣੋ',
  L10nKeys.memoriesThisIsMe: 'ਇਹ ਮੈਂ ਹਾਂ',
  L10nKeys.memoriesNotMe: 'ਮੈਂ ਨਹੀਂ',

  L10nKeys.profileTitle: 'ਪ੍ਰੋਫਾਈਲ',
  L10nKeys.profileLanguage: 'ਐਪ ਦੀ ਭਾਸ਼ਾ',
  L10nKeys.profileRegion: 'ਮੇਰਾ ਖੇਤਰ',
  L10nKeys.profileVoiceLanguage: 'ਆਵਾਜ਼ ਦੀ ਭਾਸ਼ਾ',
  L10nKeys.profileVoicePrompts: 'ਬੋਲੇ ਜਾਂਦੇ ਸੰਕੇਤ',
  L10nKeys.profileTextSize: 'ਲਿਖਤ ਦਾ ਆਕਾਰ',
  L10nKeys.profileReducedMotion: 'ਸ਼ਾਂਤ ਗਤੀ',
  L10nKeys.profileSoundEffects: 'ਆਵਾਜ਼ ਪ੍ਰਭਾਵ',
  L10nKeys.profileFamily: 'ਪਰਿਵਾਰ',
  L10nKeys.profileContacts: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
  L10nKeys.profileDemoMode: 'ਡੈਮੋ ਮੋਡ',
  L10nKeys.profileReminders: 'ਰਿਮਾਈਂਡਰ',
  L10nKeys.profileNeedHelp: 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',

  L10nKeys.remindersTitle: 'ਰਿਮਾਈਂਡਰ',
  L10nKeys.remindersEmpty: 'ਹਾਲੇ ਕੋਈ ਰਿਮਾਈਂਡਰ ਨਹੀਂ',
  L10nKeys.remindersNew: 'ਨਵਾਂ ਰਿਮਾਈਂਡਰ',
  L10nKeys.remindersTitleLabel: 'ਸਿਰਲੇਖ',
  L10nKeys.remindersDetailLabel: 'ਵੇਰਵਾ (ਵਿਕਲਪਿਕ)',
  L10nKeys.remindersTime: 'ਸਮਾਂ',
  L10nKeys.remindersDays: 'ਦਿਨ',
  L10nKeys.remindersEveryday: 'ਰੋਜ਼ਾਨਾ',
  L10nKeys.remindersEnabled: 'ਚਾਲੂ',
  L10nKeys.remindersMedicine: 'ਦਵਾਈ',
  L10nKeys.remindersAppointment: 'ਮੁਲਾਕਾਤ',
  L10nKeys.remindersRoutine: 'ਰੋਜ਼ ਦੀ ਰੁਟੀਨ',

  L10nKeys.dayMon: 'ਸੋਮ',
  L10nKeys.dayTue: 'ਮੰਗਲ',
  L10nKeys.dayWed: 'ਬੁੱਧ',
  L10nKeys.dayThu: 'ਵੀਰ',
  L10nKeys.dayFri: 'ਸ਼ੁੱਕਰ',
  L10nKeys.daySat: 'ਸ਼ਨੀ',
  L10nKeys.daySun: 'ਐਤ',

  L10nKeys.sosTitle: 'ਐਮਰਜੈਂਸੀ ਮਦਦ',
  L10nKeys.sosExplain: 'ਦਬਾ ਕੇ ਫੜ ਕੇ ਰੱਖੋ। ਮਾਈਂਡਕੇਅਰ ਇੱਕ-ਇੱਕ ਕਰਕੇ ਤੁਹਾਡੇ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕਾਂ ਨੂੰ ਸੂਚਿਤ ਕਰੇਗਾ। ਇਹ ਐਮਰਜੈਂਸੀ ਸੇਵਾ (ਜਿਵੇਂ ੧੧੨) ਨਹੀਂ ਹੈ।',
  L10nKeys.sosHold: 'ਮਦਦ ਲਈ ਦਬਾ ਕੇ ਫੜੋ',
  L10nKeys.sosHoldBody: 'ਦਬਾ ਕੇ ਫੜੋ…',
  L10nKeys.sosActiveTitle: 'ਮਦਦ ਨਾਲ ਸੰਪਰਕ ਹੋ ਰਿਹਾ ਹੈ',
  L10nKeys.sosActiveBody: 'ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਗਿਆ ਹੈ। ਜੇ ਉਹ ਜਵਾਬ ਨਾ ਦੇਣ ਤਾਂ ਅਗਲੇ ਸੰਪਰਕ ਨੂੰ ਬੁਲਾਇਆ ਜਾਵੇਗਾ।',
  L10nKeys.sosContacting: 'ਸੰਪਰਕ ਹੋ ਰਿਹਾ ਹੈ',
  L10nKeys.sosContactFamily: 'ਪਰਿਵਾਰ ਨਾਲ ਸੰਪਰਕ',
  L10nKeys.sosContacted: 'ਸੰਪਰਕ ਹੋਇਆ',
  L10nKeys.sosWaitingResponse: 'ਜਵਾਬ ਦੀ ਉਡੀਕ…',
  L10nKeys.sosEscalating: 'ਅਗਲੇ ਵਿਅਕਤੀ ਨਾਲ ਸੰਪਰਕ…',
  L10nKeys.sosCancelled: 'ਮਦਦ ਦੀ ਬੇਨਤੀ ਰੱਦ',
  L10nKeys.sosCancelAction: 'ਮਦਦ ਦੀ ਬੇਨਤੀ ਰੱਦ ਕਰੋ',
  L10nKeys.sosDone: 'ਹੋ ਗਿਆ',
  L10nKeys.sosHelpOnWay: 'ਕੋਈ ਜਲਦੀ ਤੁਹਾਡੇ ਨਾਲ ਹੋਵੇਗਾ। 🧡',
  L10nKeys.sosNoContacts: 'ਹਾਲੇ ਕੋਈ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਨਹੀਂ',
  L10nKeys.sosNoContactsBody:
      'ਕਿਰਪਾ ਕਰਕੇ ਪਰਿਵਾਰ ਨੂੰ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਜੋੜਨ ਲਈ ਕਹੋ।',
  L10nKeys.sosAddContact: 'ਸੰਪਰਕ ਜੋੜੋ',
  L10nKeys.sosDisclaimer: 'ਮਾਈਂਡਕੇਅਰ ਤੁਹਾਡੇ ਚੁਣੇ ਹੋਏ ਸੰਪਰਕਾਂ ਨੂੰ ਸੂਚਿਤ ਕਰਦਾ ਹੈ। ਇਹ ਅਧਿਕਾਰਤ ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।',
  L10nKeys.sosContactedPerson: 'ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨਾਲ ਸੰਪਰਕ ਹੋਇਆ',
  L10nKeys.sosEscalatedTo: 'ਅਗਲੇ ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨਾਲ ਸੰਪਰਕ ਹੋਇਆ',
  L10nKeys.sosAcknowledged: 'ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨੇ ਜਵਾਬ ਦਿੱਤਾ ਹੈ। ਮਦਦ ਆ ਰਹੀ ਹੈ।',
  L10nKeys.sosNotSilent:
      'ਜੇ ਅਸੀਂ ਮਦਦ ਨਹੀਂ ਭੇਜ ਸਕਦੇ ਤਾਂ ਅਸੀਂ ਕਦੇ ਦਿਖਾਵਾ ਨਹੀਂ ਕਰਾਂਗੇ।',
  L10nKeys.sosAlertNotDelivered:
      'ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਹਾਲੇ ਨਹੀਂ ਭੇਜ ਸਕੇ। ਅਸੀਂ ਕੋਸ਼ਿਸ਼ ਕਰਦੇ ਰਹਾਂਗੇ।',

  L10nKeys.careTitle: 'ਦੇਖਭਾਲ ਕਰਨ ਵਾਲਾ',
  L10nKeys.careDashboard: 'ਝਲਕ',
  L10nKeys.carePatients: 'ਮੇਰੇ ਮਰੀਜ਼',
  L10nKeys.careMemories: 'ਯਾਦਾਂ',
  L10nKeys.careContacts: 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
  L10nKeys.careSettings: 'ਸੈਟਿੰਗਾਂ',
  L10nKeys.careAddMemory: 'ਯਾਦ ਜੋੜੋ',
  L10nKeys.careAddContact: 'ਸੰਪਰਕ ਜੋੜੋ',
  L10nKeys.careEngagement: 'ਸ਼ਮੂਲੀਅਤ',
  L10nKeys.careActivitiesWeek: 'ਇਸ ਹਫ਼ਤੇ ਦੀਆਂ ਸਰਗਰਮੀਆਂ',
  L10nKeys.careGardenProgress: 'ਬਾਗ ਦੀ ਤਰੱਕੀ',
  L10nKeys.careRecentActivity: 'ਤਾਜ਼ਾ ਸਰਗਰਮੀ',
  L10nKeys.careNoPatients: 'ਕੋਈ ਮਰੀਜ਼ ਜੁੜੇ ਨਹੀਂ',
  L10nKeys.careNoPatientsBody:
      'ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨੂੰ ਜੋੜਨ ਲਈ ਕਹੋ, ਜਾਂ ਮਰੀਜ਼ ਪ੍ਰੋਫਾਈਲ ਜੋੜੋ।',
  L10nKeys.careAddPatient: 'ਮਰੀਜ਼ ਜੋੜੋ',
  L10nKeys.carePerformanceNote: 'ਇਸ ਸਮੇਂ ਇਸ ਵਿਅਕਤੀ ਦਾ ਸਰਗਰਮੀ ਪ੍ਰਦਰਸ਼ਨ ਉਨ੍ਹਾਂ ਦੇ ਆਮ ਪੱਧਰ ਤੋਂ ਥੋੜ੍ਹਾ ਘੱਟ ਹੈ।',
  L10nKeys.careUploadPhoto: 'ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'ਆਵਾਜ਼ ਰਿਕਾਰਡ ਕਰੋ',
  L10nKeys.careWriteMemory: 'ਯਾਦ ਲਿਖੋ',
  L10nKeys.careMemoryTitle: 'ਸਿਰਲੇਖ',
  L10nKeys.careMemoryCaption: 'ਕੈਪਸ਼ਨ',
  L10nKeys.careMemoryRelation: 'ਇਸ ਵਿੱਚ ਕੌਣ ਹੈ? (ਰਿਸ਼ਤਾ)',
  L10nKeys.careMemoryCategory: 'ਸ਼੍ਰੇਣੀ',
  L10nKeys.careContactName: 'ਨਾਮ',
  L10nKeys.careContactPhone: 'ਫੋਨ ਨੰਬਰ',
  L10nKeys.careContactPriority: 'ਕਾਲ ਕ੍ਰਮ',
  L10nKeys.careContactRelation: 'ਰਿਸ਼ਤਾ',
  L10nKeys.careEscalationTimeout: 'ਅਗਲੇ ਸੰਪਰਕ ਤੋਂ ਪਹਿਲਾਂ ਦੇ ਮਿੰਟ',
  L10nKeys.careIncidentStatus: 'ਸਥਿਤੀ',
  L10nKeys.careAckSos: 'ਮੈਂ ਜਵਾਬ ਦੇ ਰਿਹਾ ਹਾਂ',
  L10nKeys.careResponding: 'ਜਵਾਬ ਦੇ ਰਹੇ ਹਨ',
  L10nKeys.careActiveAlerts: 'ਸਰਗਰਮ ਚੇਤਾਵਨੀਆਂ',

  L10nKeys.syncSavingOffline: 'ਆਫਲਾਈਨ',
  L10nKeys.syncSavingOfflineBody:
      'ਤੁਹਾਡੀਆਂ ਸਰਗਰਮੀਆਂ ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਸੁਰੱਖਿਅਤ ਹਨ।',
  L10nKeys.syncSynced: 'ਸਿੰਕ ਹੋਇਆ',
  L10nKeys.syncInfo: 'ਤੁਹਾਡੀ ਜਾਣਕਾਰੀ ਸਿੰਕ ਹੋ ਗਈ ਹੈ।',
  L10nKeys.syncPending: 'ਸਿੰਕ ਦੀ ਉਡੀਕ',

  L10nKeys.errorGeneric: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
  L10nKeys.errorGenericBody:
      'ਤੁਹਾਡੀ ਤਰੱਕੀ ਸੁਰੱਖਿਅਤ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  L10nKeys.errorAudio: 'ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਆਵਾਜ਼ ਨਹੀਂ ਚੱਲੀ।',
  L10nKeys.errorPermission: 'ਇਸ ਲਈ ਡਿਵਾਈਸ ਦੀ ਇਜਾਜ਼ਤ ਚਾਹੀਦੀ ਹੈ।',
  L10nKeys.errorNoInternetAction:
      'ਇੰਟਰਨੈੱਟ ਦੀ ਲੋੜ ਨਹੀਂ — ਇਹ ਪਹਿਲਾਂ ਇੱਥੇ ਹੀ ਸੰਭਲ ਜਾਂਦਾ ਹੈ।',

  L10nKeys.demoWelcome: 'ਡੈਮੋ ਦੇਖੋ',
  L10nKeys.demoExplain:
      'ਤੁਸੀਂ ਦੇਖ ਸਕੋ ਇਸ ਲਈ ਨਮੂਨਾ ਪਰਿਵਾਰ ਅਤੇ ਯਾਦਾਂ ਜੋੜੀਆਂ ਜਾਣਗੀਆਂ।',
  L10nKeys.demoLoad: 'ਡੈਮੋ ਬਾਗ ਲੋਡ ਕਰੋ',

  L10nKeys.unitsPoints: 'ਅੰਕ',
  L10nKeys.teaserChai: 'ਚਾਹ ਬਣਾਈਏ।',
  L10nKeys.familiarityName: 'ਆਸ਼ਾ',
  L10nKeys.regionMap: 'ਮੇਰਾ ਖੇਤਰ',
  L10nKeys.regionChoose: 'ਆਪਣਾ ਖੇਤਰ ਚੁਣੋ',
  L10nKeys.regionIndia: 'ਭਾਰਤ',
  L10nKeys.importantMemory: 'ਮਹੱਤਵਪੂਰਨ ਯਾਦ',
  L10nKeys.growing: 'ਵਧ ਰਿਹਾ ਹੈ',
  L10nKeys.blooming: 'ਖਿੜ ਰਿਹਾ ਹੈ',
  L10nKeys.mature: 'ਪਰਿਪੱਕ',
  L10nKeys.noVoice: 'ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਆਵਾਜ਼ ਉਪਲਬਧ ਨਹੀਂ।',
  L10nKeys.optional: 'ਵਿਕਲਪਿਕ',

  L10nKeys.langChoose: 'ਭਾਸ਼ਾ ਚੁਣੋ',
  L10nKeys.langPrimary: 'ਮੁੱਖ',
  L10nKeys.langNorthEast: 'ਉੱਤਰ-ਪੂਰਬੀ ਭਾਰਤ',
  L10nKeys.langMajor: 'ਭਾਰਤ ਦੀਆਂ ਮੁੱਖ ਭਾਸ਼ਾਵਾਂ',

  L10nKeys.authSignUpTitle: 'ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ',
  L10nKeys.authSignUpBody: 'ਇਹ ਮਾਈਂਡਕੇਅਰ ਪ੍ਰੋਫਾਈਲ ਤੁਹਾਡੀ ਡਿਵਾਈਸ ਉੱਤੇ ਸੁਰੱਖਿਅਤ ਰਹਿੰਦਾ ਹੈ। ਇਸ ਨੂੰ ਸਿਰਫ਼ ਤੁਸੀਂ ਖੋਲ੍ਹ ਸਕੋ ਇਸ ਲਈ ਯੂਜ਼ਰਨੇਮ ਅਤੇ ਪਾਸਵਰਡ ਪਾਓ।',
  L10nKeys.authLoginTitle: 'ਮੁੜ ਸਵਾਗਤ ਹੈ',
  L10nKeys.authLoginBody:
      'ਆਪਣਾ ਬਾਗ ਖੋਲ੍ਹਣ ਲਈ ਯੂਜ਼ਰਨੇਮ ਅਤੇ ਪਾਸਵਰਡ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ।',
  L10nKeys.authUsername: 'ਯੂਜ਼ਰਨੇਮ',
  L10nKeys.authUsernameHint: 'ਜਿਵੇਂ: ranu123',
  L10nKeys.authDisplayName: 'ਤੁਹਾਡਾ ਨਾਮ',
  L10nKeys.authPassword: 'ਪਾਸਵਰਡ',
  L10nKeys.authPasswordHint: 'ਘੱਟੋ-ਘੱਟ ੬ ਅੱਖਰ',
  L10nKeys.authConfirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
  L10nKeys.authRoleQuestion: 'ਇਹ ਪ੍ਰੋਫਾਈਲ ਕਿਸ ਲਈ ਹੈ…',
  L10nKeys.authRolePatient: 'ਮੇਰੇ ਲਈ',
  L10nKeys.authRoleCaregiver: 'ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਲਈ',
  L10nKeys.authCreate: 'ਖਾਤਾ ਬਣਾਓ',
  L10nKeys.authSignIn: 'ਸਾਈਨ ਇਨ',
  L10nKeys.authSignOut: 'ਸਾਈਨ ਆਊਟ',
  L10nKeys.authAccount: 'ਖਾਤਾ',
  L10nKeys.caregiverTitle: 'ਦੇਖਭਾਲ ਕਰਨ ਵਾਲਾ',
  L10nKeys.caregiverNotLinked: 'ਹਾਲੇ ਕੋਈ ਦੇਖਭਾਲ ਕਰਨ ਵਾਲਾ ਨਹੀਂ ਜੁੜਿਆ',
  L10nKeys.authBadCredentials: 'ਯੂਜ਼ਰਨੇਮ ਜਾਂ ਪਾਸਵਰਡ ਗਲਤ ਹੈ।',
  L10nKeys.authUsernameTaken:
      'ਇਹ ਯੂਜ਼ਰਨੇਮ ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਪਹਿਲਾਂ ਤੋਂ ਵਰਤਿਆ ਜਾ ਰਿਹਾ ਹੈ।',
  L10nKeys.authPasswordMismatch: 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ।',
  L10nKeys.authUsernameShort: 'ਯੂਜ਼ਰਨੇਮ ਘੱਟੋ-ਘੱਟ ੩ ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
  L10nKeys.authUsernameInvalid: 'ਸਿਰਫ਼ ਅੱਖਰ, ਅੰਕ, ਡਾਟ, ਡੈਸ਼ ਜਾਂ ਅੰਡਰਸਕੋਰ ਵਰਤੋ।',
  L10nKeys.authPasswordShort: 'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ ੬ ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।',
  L10nKeys.authNameRequired: 'ਕਿਰਪਾ ਕਰਕੇ ਨਾਮ ਦਾਖਲ ਕਰੋ।',
  L10nKeys.authSignOutConfirm:
      'ਕੀ ਤੁਸੀਂ ਇਸ ਪ੍ਰੋਫਾਈਲ ਤੋਂ ਸਾਈਨ ਆਊਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
  L10nKeys.screenTitle: 'ਤੁਰੰਤ ਯਾਦਦਾਸ਼ਤ ਜਾਂਚ',
  L10nKeys.screenIntro: 'ਅਸੀਂ ਮਰੀਜ਼ ਬਾਰੇ ਕੁਝ ਛੋਟੇ ਸਵਾਲ ਪੁੱਛਾਂਗੇ। ਸੋਚੋ ਕਿ ਪਿਛਲੇ ਕੁਝ ਮਹੀਨਿਆਂ ਵਿੱਚ ਉਹ ਕਿਵੇਂ ਰਹੇ ਹਨ।',
  L10nKeys.screenNotSure: 'ਪਤਾ ਨਹੀਂ',
  L10nKeys.screenFinish: 'ਮੇਰਾ ਨਤੀਜਾ ਵੇਖੋ',
  L10nKeys.screenSkip: 'ਹੁਣ ਲਈ ਛੱਡੋ',
  L10nKeys.screenResultBack: 'ਹੋ ਗਿਆ',
  L10nKeys.screenCheckAgain: 'ਦੁਬਾਰਾ ਜਾਂਚ ਕਰੋ',
  L10nKeys.screenStartCheckup: 'ਜਾਂਚ ਸ਼ੁਰੂ ਕਰੋ',
  L10nKeys.screenSkipped: 'ਜਾਂਚ ਛੱਡ ਦਿੱਤੀ ਗਈ',
  L10nKeys.screenStatusGood: 'ਸਭ ਕੁਝ ਠੀਕ ਲੱਗਦਾ ਹੈ',
  L10nKeys.screenStatusGoodBody: 'ਕੋਈ ਵੱਡੀ ਚਿੰਤਾ ਨਹੀਂ ਦਿਖੀ। ਰੋਜ਼ ਦੀਆਂ ਗਤੀਵਿਧੀਆਂ ਕਰਦੇ ਰਹੋ, ਅਤੇ ਕੁਝ ਬਦਲੇ ਤਾਂ ਕਦੇ ਵੀ ਦੁਬਾਰਾ ਜਾਂਚ ਕਰ ਸਕਦੇ ਹੋ।',
  L10nKeys.screenStatusWatch: 'ਕੁਝ ਤਬਦੀਲੀਆਂ ਦੇਖੀਆਂ ਗਈਆਂ',
  L10nKeys.screenStatusWatchBody: 'ਭੁੱਲਣ ਦੇ ਕੁਝ ਪਲ ਦਿਖੇ। ਇਹ ਉਮਰ ਨਾਲ ਆਮ ਹੈ, ਪਰ ਨਜ਼ਰ ਰੱਖੋ ਅਤੇ ਅਗਲੀ ਡਾਕਟਰ ਮੁਲਾਕਾਤ ਤੇ ਦੱਸੋ।',
  L10nKeys.screenStatusDoctor: 'ਕਿਰਪਾ ਕਰਕੇ ਜਾਂਚ ਕਰਵਾਓ',
  L10nKeys.screenStatusDoctorBody: 'ਕੁਝ ਸੰਕੇਤ ਦਿਖੇ ਜਿਨ੍ਹਾਂ ਵੱਲ ਧਿਆਨ ਦੇਣ ਦੀ ਲੋੜ ਹੋ ਸਕਦੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਇਹ ਡਾਕਟਰ ਜਾਂ ਕਲੀਨਿਕ ਨਾਲ ਸਾਂਝੇ ਕਰੋ ਤਾਂ ਜੋ ਉਹ ਮਦਦ ਕਰ ਸਕਣ।',
  L10nKeys.screenRarely: 'ਕਦੇ ਕਦਾਈਂ',
  L10nKeys.screenSometimes: 'ਕਦੇ ਕਦੇ',
  L10nKeys.screenFrequently: 'ਅਕਸਰ',
  L10nKeys.screenVeryFrequently: 'ਬਹੁਤ ਅਕਸਰ',
  L10nKeys.screenQ01:
      'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਹਾਲ ਦੀਆਂ ਘਟਨਾਵਾਂ ਯਾਦ ਰੱਖਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ02: 'ਕੀ ਉਹ ਉਹੀ ਸਵਾਲ ਜਾਂ ਕਹਾਣੀਆਂ ਦੁਹਰਾਉਂਦੇ ਹਨ?',
  L10nKeys.screenQ03: 'ਕੀ ਉਹ ਜਾਣੇ-ਪਛਾਣੇ ਲੋਕਾਂ ਦੇ ਨਾਂ ਭੁੱਲ ਜਾਂਦੇ ਹਨ?',
  L10nKeys.screenQ04:
      'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਜਾਣੇ-ਪਛਾਣੇ ਚਿਹਰੇ ਪਛਾਣਨ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ05: 'ਕੀ ਉਹ ਮੁਲਾਕਾਤਾਂ ਜਾਂ ਮਹੱਤਵਪੂਰਨ ਘਟਨਾਵਾਂ ਭੁੱਲ ਜਾਂਦੇ ਹਨ?',
  L10nKeys.screenQ06: 'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਸਹੀ ਸ਼ਬਦ ਲੱਭਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ07: 'ਕੀ ਉਹ ਗੁੰਝਲ ਜਾਂਦੇ ਹਨ ਕਿ ਉਹ ਕਿੱਥੇ ਹਨ?',
  L10nKeys.screenQ08:
      'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਰੋਜ਼ ਦੀਆਂ ਗਤੀਵਿਧੀਆਂ ਲਈ ਯਾਦ ਦਿਵਾਉਣ ਦੀ ਲੋੜ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ09: 'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਦਵਾਈਆਂ ਸੰਭਾਲਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ10: 'ਕੀ ਉਹ ਗੁੰਝਲਣ ਤੇ ਚਿੰਤਤ ਜਾਂ ਪਰੇਸ਼ਾਨ ਹੋ ਜਾਂਦੇ ਹਨ?',
  L10nKeys.screenQ11: 'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਗੱਲਬਾਤ ਸਮਝਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ12:
      'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਜਾਣੇ-ਪਛਾਣੇ ਕੰਮ ਪੂਰੇ ਕਰਨ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ13:
      'ਕੀ ਉਹ ਭੁੱਲ ਜਾਂਦੇ ਹਨ ਕਿ ਰੋਜ਼ ਦੀਆਂ ਚੀਜ਼ਾਂ ਕਿੱਥੇ ਰੱਖੀਆਂ ਹਨ?',
  L10nKeys.screenQ14: 'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਹਿਦਾਇਤਾਂ ਯਾਦ ਰੱਖਣ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',
  L10nKeys.screenQ15:
      'ਕੀ ਉਨ੍ਹਾਂ ਨੂੰ ਬਹੁ-ਪੜਾਵੀ ਗਤੀਵਿਧੀਆਂ ਕਰਨ ਵਿੱਚ ਮੁਸ਼ਕਲ ਹੁੰਦੀ ਹੈ?',

  L10nKeys.careDashboardSubtitle: 'ਪਰਿਵਾਰ ਦੀ ਦੇਖਭਾਲ',
  L10nKeys.careSosLive: 'ਲਾਈਵ ਚੇਤਾਵਨੀ',
  L10nKeys.careSosRespondedBy: '{name} ਨੇ ਜਵਾਬ ਦਿੱਤਾ',
  L10nKeys.careLinkTitle: 'ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨਾਲ ਜੁੜੋ',
  L10nKeys.careLinkBody: 'ਆਪਣੇ ਪਿਆਰੇ ਵਿਅਕਤੀ ਤੋਂ ਉਨ੍ਹਾਂ ਦੇ ਫੋਨ ’ਤੇ ਦਿਖਾਈ ਦੇਣ ਵਾਲਾ 6-ਅੱਖਰਾਂ ਵਾਲਾ ਪਰਿਵਾਰਕ ਕੋਡ ਪੁੱਛੋ, ਫਿਰ ਜੁੜੋ।',
  L10nKeys.careLinkCode: 'ਪਰਿਵਾਰਕ ਕੋਡ',
  L10nKeys.careLinkCodeHint: 'ਉਦਾ. A1B2C3',
  L10nKeys.careLinkConnect: 'ਜੁੜੋ',
  L10nKeys.careLinkDone: 'ਜੁੜ ਗਿਆ',
  L10nKeys.careLinkSuccess:
      '{name} ਨਾਲ ਜੁੜ ਗਿਆ! ਯਾਦਾਂ ਅਤੇ ਚੇਤਾਵਨੀਆਂ ਹੁਣ ਸਿੰਕ ਹੋਣਗੀਆਂ।',
  L10nKeys.careLinkFailed:
      'ਜੁੜ ਨਹੀਂ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਕੋਡ ਜਾਂਚ ਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  L10nKeys.careTrendsTitle: 'AI ਰੁਝਾਨ',
  L10nKeys.careTrendsBody: 'ਸਰਗਰਮੀ ਦੀ ਕਿਸਮ ਅਨੁਸਾਰ ਰੋਜ਼ਾਨਾ ਸ਼ੁੱਧਤਾ',
  L10nKeys.careTrendsNoData:
      'ਹਾਲੇ ਕੋਈ ਸਰਗਰਮੀ ਨਹੀਂ — ਰੁਝਾਨ ਦੇਖਣ ਲਈ ਇੱਕ ਕਸਰਤ ਪੂਰੀ ਕਰੋ।',
  L10nKeys.careAiDifficulty: 'ਆਪਣੇ ਆਪ ਸਮਾਯੋਜਿਤ ਮੁਸ਼ਕਲ',
  L10nKeys.careAiAccuracy: 'ਮਾਡਲ ਸ਼ੁੱਧਤਾ',
  L10nKeys.careAiRealSessions: 'ਅਸਲ ਸੈਸ਼ਨ',
  L10nKeys.careAiDemoSessions: 'ਡੈਮੋ ਸੈਸ਼ਨ',
  L10nKeys.careNavGames: 'ਖੇਡਾਂ',
  L10nKeys.careNavRoutine: 'ਦਿਨਚਰਯਾ',
  L10nKeys.careGreetSubtitle: 'ਦੇਖੋ ਅੱਜ {name} ਕਿਵੇਂ ਕਰ ਰਿਹਾ ਹੈ।',
  L10nKeys.careNotifEmpty: 'ਕੋਈ ਨਵੀਂ ਸੂਚਨਾ ਨਹੀਂ',
  L10nKeys.careWellnessScore: 'ਬੋਧਾਤਮਕ ਤੰਦਰੁਸਤੀ ਸਕੋਰ',
  L10nKeys.careStatusStable: 'ਸਥਿਰ',
  L10nKeys.careStatusAttention: 'ਧਿਆਨ ਦੀ ਲੋੜ',
  L10nKeys.careLastSynced: 'ਆਖਰੀ ਸਿੰਕ {time}',
  L10nKeys.careMinAgo: '{n} ਮਿੰਟ ਪਹਿਲਾਂ',
  L10nKeys.careGamesWeek: 'ਇਸ ਹਫ਼ਤੇ ਦੀਆਂ ਖੇਡਾਂ',
  L10nKeys.careRoutineCompletion: 'ਦਿਨਚਰਯਾ ਪੂਰੀ ਹੋਈ',
  L10nKeys.careCurrentStreak: 'ਮੌਜੂਦਾ ਸਟ੍ਰੀਕ',
  L10nKeys.careMoodCheckins: 'ਮੂਡ ਚੈੱਕ-ਇਨ',
  L10nKeys.careDayUnit: 'ਦਿਨ',
  L10nKeys.careDaysUnit: 'ਦਿਨ',
  L10nKeys.careActivityTitle: 'ਹਫ਼ਤਾਵਾਰੀ ਗਤੀਵਿਧੀ',
  L10nKeys.careWeekly: 'ਹਫ਼ਤਾਵਾਰੀ',
  L10nKeys.careMonthly: 'ਮਾਸਿਕ',
  L10nKeys.careNoActivityWeek: 'ਇਸ ਹਫ਼ਤੇ ਅਜੇ ਤੱਕ ਕੋਈ ਗਤੀਵਿਧੀ ਦਰਜ ਨਹੀਂ ਹੋਈ।',
  L10nKeys.careMoodTitle: 'ਮੂਡ',
  L10nKeys.careMoodHappy: 'ਖੁਸ਼',
  L10nKeys.careMoodCalm: 'ਸ਼ਾਂਤ',
  L10nKeys.careMoodNeutral: 'ਨਿਰਪੱਖ',
  L10nKeys.careMoodLow: 'ਘੱਟ',
  L10nKeys.careMood7Days: 'ਪਿਛਲੇ 7 ਦਿਨ',
  L10nKeys.careMoodInsight: '{name} ਇਸ ਹਫ਼ਤੇ ਜ਼ਿਆਦਾਤਰ ਸ਼ਾਂਤ ਰਿਹਾ ਹੈ, ਪਿਛਲੇ ਦੋ ਦਿਨਾਂ ਵਿੱਚ ਹਲਕੀ ਗਿਰਾਵਟ ਦੇ ਨਾਲ।',
  L10nKeys.careMoodNoData: 'ਇਸ ਹਫ਼ਤੇ ਅਜੇ ਤੱਕ ਕੋਈ ਮੂਡ ਚੈੱਕ-ਇਨ ਨਹੀਂ।',
  L10nKeys.careSkillsTitle: 'ਬੋਧਾਤਮਕ ਹੁਨਰ',
  L10nKeys.careSkillMemory: 'ਯਾਦਦਾਸ਼ਤ',
  L10nKeys.careSkillAttention: 'ਧਿਆਨ',
  L10nKeys.careSkillLanguage: 'ਭਾਸ਼ਾ',
  L10nKeys.careSkillReasoning: 'ਤਰਕ',
  L10nKeys.careSkillProcessing: 'ਪ੍ਰੋਸੈਸਿੰਗ ਗਤੀ',
  L10nKeys.careInsightToday: 'ਅੱਜ ਦੀ ਜਾਣਕਾਰੀ',
  L10nKeys.careInsightBody: 'ਰੌਬਰਟ ਆਪਣੀ ਸਵੇਰ ਦੀ ਦਿਨਚਰਯਾ ਤੋਂ ਬਾਅਦ ਯਾਦਦਾਸ਼ਤ ਦੀਆਂ ਗਤੀਵਿਧੀਆਂ ਵਿੱਚ ਲਗਾਤਾਰ ਸਰਗਰਮ ਰਿਹਾ ਹੈ। ਪਿਛਲੇ ਦੋ ਦਿਨਾਂ ਵਿੱਚ ਉਸਦਾ ਮੂਡ ਥੋੜ੍ਹਾ ਘੱਟ ਰਿਹਾ ਹੈ।',
  L10nKeys.careInsightBodyReal: 'ਇਸ ਹਫ਼ਤੇ {name} ਨੇ {count} ਬੋਧਾਤਮਕ ਸੈਸ਼ਨ ਪੂਰੇ ਕੀਤੇ (ਨਿਸ਼ਾਨਾ {goal}) ਅਤੇ {streak} ਦਿਨਾਂ ਦੀ ਸਟ੍ਰੀਕ ਜਾਰੀ ਹੈ।',
  L10nKeys.careViewDetails: 'ਵੇਰਵੇ ਦੇਖੋ',
  L10nKeys.careInsightDisclaimer:
      'ਇਹ ਡੇਟਾ ਤੋਂ ਇੱਕ ਨਰਮ ਨਿਰੀਖਣ ਹੈ — ਡਾਕਟਰੀ ਨਿਦਾਨ ਨਹੀਂ।',
  L10nKeys.careAttentionTitle: 'ਤੁਹਾਡੇ ਧਿਆਨ ਦੀ ਲੋੜ',
  L10nKeys.careAttentionEmpty: 'ਹੁਣ ਤੁਹਾਡੇ ਧਿਆਨ ਦੀ ਲੋੜ ਵਾਲੀ ਕੋਈ ਚੀਜ਼ ਨਹੀਂ ਹੈ।',
  L10nKeys.careAlertSos: '{name} ਨੇ SOS ਬਟਨ ਦਬਾਇਆ',
  L10nKeys.careAlertRoutineMissed: 'ਕੱਲ੍ਹ ਦਿਨਚਰਯਾ ਖੁੰਝ ਗਈ',
  L10nKeys.careAlertMoodDown: 'ਪਿਛਲੇ ਦੋ ਦਿਨਾਂ ਵਿੱਚ ਮੂਡ ਘਟਿਆ ਹੈ',
  L10nKeys.careAlertSessionPending: 'ਅੱਜ ਬੋਧਾਤਮਕ ਸੈਸ਼ਨ ਪੂਰਾ ਨਹੀਂ ਹੋਇਆ',
  L10nKeys.careAlertSeverityHigh: 'ਉੱਚ',
  L10nKeys.careAlertSeverityMedium: 'ਦਰਮਿਆਨੀ',
  L10nKeys.careAlertSeverityLow: 'ਘੱਟ',
  L10nKeys.careWeeklySummary: 'ਹਫ਼ਤਾਵਾਰੀ ਸਾਰ',
  L10nKeys.careSessionsCompleted: 'ਪੂਰੇ ਕੀਤੇ ਸੈਸ਼ਨ',
  L10nKeys.careAvgSessionDuration: 'ਔਸਤ ਸੈਸ਼ਨ ਮਿਆਦ',
  L10nKeys.careRoutineAdherence: 'ਦਿਨਚਰਯਾ ਦੀ ਪਾਲਣਾ',
  L10nKeys.careMoodTrend: 'ਮੂਡ ਰੁਝਾਨ',
  L10nKeys.careMoodTrendSlightlyDown: 'ਥੋੜ੍ਹਾ ਘੱਟ',
  L10nKeys.careMoodTrendStable: 'ਸਥਿਰ',
  L10nKeys.careMoodTrendUp: 'ਸੁਧਾਰ ਹੋ ਰਿਹਾ ਹੈ',
  L10nKeys.careVsLastWeek: 'ਪਿਛਲੇ ਹਫ਼ਤੇ ਦੇ ਮੁਕਾਬਲੇ',
  L10nKeys.careSyncedJustNow: 'ਹੁਣੇ ਸਿੰਕ ਹੋਇਆ',
  L10nKeys.careOfflineWaiting: 'ਆਫ਼ਲਾਈਨ · {count} ਗਤੀਵਿਧੀਆਂ ਸਿੰਕ ਦੀ ਉਡੀਕ ਵਿੱਚ',
  L10nKeys.careComingSoon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
  L10nKeys.careHomeSoon: '{name} ਦੇ ਦਿਨ ਦਾ ਇੱਕ ਝਟਪਟ ਜਾਇਜ਼ਾ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗਾ।',
  L10nKeys.careGamesSoon: 'ਖੇਡਾਂ ਅਤੇ ਸੈਸ਼ਨ ਇਤਿਹਾਸ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।',
  L10nKeys.careRoutineSoon: 'ਮਰੀਜ਼ ਦੀ ਰੋਜ਼ਾਨਾ ਦਿਨਚਰਯਾ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗੀ।',
  L10nKeys.careProfileSoon:
      'ਦੇਖਭਾਲ ਕਰਨ ਵਾਲੇ ਦਾ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਸੈਟਿੰਗਾਂ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੀਆਂ।',
  L10nKeys.serverPairingTitle: 'ਪਰਿਵਾਰਕ ਕੋਡ',
  L10nKeys.serverPairingBody:
      'ਇਹ ਕੋਡ ਕਿਸੇ ਦੇਖਭਾਲ ਕਰਨ ਵਾਲੇ ਨਾਲ ਸਾਂਝਾ ਕਰੋ ਤਾਂ ਜੋ ਉਹ ਤੁਹਾਡੇ ਨਾਲ ਜੁੜ ਸਕਣ।',
  L10nKeys.serverUnlinked: 'ਸਰਵਰ ਨਾਲ ਕਨੈਕਟ ਨਹੀਂ',
  L10nKeys.serverLinked: 'ਸਰਵਰ ਨਾਲ ਕਨੈਕਟ',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
