import '../l10n_keys.dart';

/// Assamese dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsAs = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'আপোনাৰ স্মৃতিৰ সংগী',
  L10nKeys.back: 'পিছলৈ',
  L10nKeys.next: 'আগলৈ',
  L10nKeys.continueText: 'আগবাঢ়ক',
  L10nKeys.skip: 'এৰি দিয়ক',
  L10nKeys.done: 'হৈ গ’ল',
  L10nKeys.cancel: 'বাতিল',
  L10nKeys.yes: 'হয়',
  L10nKeys.no: 'নহয়',
  L10nKeys.save: 'সাঁচি ৰাখক',
  L10nKeys.close: 'বন্ধ',
  L10nKeys.retry: 'আকৌ চেষ্টা',
  L10nKeys.add: 'যোগ',
  L10nKeys.edit: 'সংশোধন',
  L10nKeys.remove: 'আঁতৰাওক',
  L10nKeys.search: 'সন্ধান',
  L10nKeys.today: 'আজি',
  L10nKeys.offline: 'অফলাইন',
  L10nKeys.online: 'অনলাইন',

  L10nKeys.goodMorning: 'সুপ্ৰভাত',
  L10nKeys.goodAfternoon: 'নমস্কাৰ',
  L10nKeys.goodEvening: 'শুভ সন্ধ্যা',
  L10nKeys.goodNight: 'শুভ ৰাতি',

  L10nKeys.navHome: 'হোম',
  L10nKeys.navGarden: 'বাগিচা',
  L10nKeys.navActivities: 'কাৰ্যকলাপ',
  L10nKeys.navMemories: 'স্মৃতি',
  L10nKeys.navProfile: 'প্ৰফাইল',
  L10nKeys.navMystery: 'আজিৰ স্মৃতি',

  L10nKeys.onboardingWelcomeTitle: 'আপোনাৰ স্মৃতিৰ বাবে এজন কোমল সংগী',
  L10nKeys.onboardingWelcomeBody: 'মাইণ্ডকেয়াৰে ইন্টাৰনেট অবিহনেও মনত ৰখাত, খেলাত আৰু পৰিয়ালৰ সৈতে জুৰি থাকাত সহায় কৰে।',
  L10nKeys.onboardingNameTitle: 'আপোনাক কি বুলি মাতিম?',
  L10nKeys.onboardingNameHint: 'আপোনাৰ নাম',
  L10nKeys.onboardingRegionTitle: 'আপোনাৰ ঘৰ ক’ত?',
  L10nKeys.onboardingRegionHint: 'চহৰ বা নগৰ',
  L10nKeys.onboardingRegionList: 'গুৱাহাটী, শিলচৰ, শ্বিলং, আগৰতলা, ইম্ফল, আইজল, ইটানগৰ, কোহিমা, গেংটক, ডিব্ৰুগড়, যোৰহাট, আপোনাৰ চহৰ',
  L10nKeys.onboardingLanguageTitle: 'আপুনি কোন ভাষা ভাল পায়?',
  L10nKeys.onboardingLanguageBody: 'যিকোনো সময়তে সলনি কৰিব পাৰে।',
  L10nKeys.onboardingFamilyTitle: 'পৰিয়াল কোন?',
  L10nKeys.onboardingFamilyBody: 'আপোনাৰ প্ৰিয়জনসকলক যোগ কৰক। আমি তেওঁলোকৰ ফটো আৰু মাত কোমল স্মৃতি হিচাপে দেখুৱাম।',
  L10nKeys.onboardingAddFamily: 'পৰিয়ালৰ সদস্য যোগ',
  L10nKeys.onboardingEmergencyTitle: 'জৰুৰীকালত আমি কাক মাতিম?',
  L10nKeys.onboardingEmergencyBody:
      'SOS বুটাম দিলে মাইণ্ডকেয়াৰে আপোনাৰ পৰিয়ালক জনাব, জৰুৰী সেৱাক নহয়।',
  L10nKeys.onboardingEmergencyName: 'নাম',
  L10nKeys.onboardingEmergencyPhone: 'ফোন নম্বৰ',
  L10nKeys.onboardingEmergencyRelation: 'সম্পৰ্ক (জীয়েক, পুতেক…)',
  L10nKeys.onboardingDoneTitle: 'আপোনাৰ বাগিচা সাজু!',
  L10nKeys.onboardingDoneBody: 'সৰু কাৰ্যকলাপ সম্পন্ন কৰক আৰু বাগিচা বাঢ়ি অহা চাওক। আমি সদায় আপোনাৰ কাষত আছো।',
  L10nKeys.onboardingStart: 'মোৰ বাগিচা আৰম্ভ',

  L10nKeys.homeWhatsGrowing: 'আজি কি বাঢ়িছে?',
  L10nKeys.homeTodayActivity: 'আজিৰ সৰু কাৰ্যকলাপ',
  L10nKeys.homeActivityDuration: 'প্ৰায় ৩ মিনিট',
  L10nKeys.homeMinutes: 'মিনিট',
  L10nKeys.homeMemoryOfDay: 'আজিৰ স্মৃতি',
  L10nKeys.homeMemoryLocked: 'এটা বিশেষ স্মৃতি আপোনাৰ বাবে অপেক্ষাত…',
  L10nKeys.homeMemoryUnlocked: 'এটা স্মৃতি মুকলি হ’ল!',
  L10nKeys.homeContinueActivity: 'কাৰ্যকলাপ আগবঢ়াওক',
  L10nKeys.homeFamilyMemory: 'আপোনাৰ পৰিয়ালৰ পৰা',
  L10nKeys.homeFamilyMemoryEmpty: 'পৰিয়ালৰ স্মৃতি ইয়াত দেখা দিব পাৰে।',
  L10nKeys.homeSos: 'সহায় লাগে',
  L10nKeys.homeSosSubtitle: 'জৰুৰীকালত পৰিয়ালৰ সৈতে যোগাযোগ',
  L10nKeys.homeGardenPreview: 'আপোনাৰ বাগিচা',
  L10nKeys.homeEngine: 'মাইণ্ডকেয়াৰ সংগী',
  L10nKeys.homeEngineReady: 'আপোনাৰ সহায়ক সাজু।',
  L10nKeys.homeWelcomeBack: 'স্বাগতম! বাগিচা আগবঢ়াও আহক। 🌸',
  L10nKeys.homeNoActivity: 'আজি কোনো কাৰ্যকলাপ নাই',
  L10nKeys.homeNoActivityBody: 'বিৰাম লওক — বা যিকোনো কাৰ্যকলাপ বাছক। 🌻',

  L10nKeys.gardenTitle: 'মোৰ স্মৃতি বাগিচা',
  L10nKeys.gardenSectionAll: 'সকলো',
  L10nKeys.gardenSectionFamily: 'পৰিয়াল',
  L10nKeys.gardenSectionChildhood: 'শৈশৱ',
  L10nKeys.gardenSectionPlaces: 'স্থান',
  L10nKeys.gardenSectionFestivals: 'উৎসৱ',
  L10nKeys.gardenEmpty: 'আপোনাৰ বাগিচা আৰম্ভ হৈছে',
  L10nKeys.gardenEmptyBody:
      'প্ৰথম কাৰ্যকলাপ সম্পন্ন কৰক, ইয়াত এটা মাহ বিচি দিয়া হ’ব।',
  L10nKeys.gardenPoints: 'পইণ্ট',
  L10nKeys.gardenLevel: 'স্তৰ',
  L10nKeys.gardenSeed: 'মাহ',
  L10nKeys.gardenPlant: 'গছ',
  L10nKeys.gardenFlower: 'ফুল',
  L10nKeys.gardenTree: 'বৃক্ষ',
  L10nKeys.gardenMilestone: 'সফলতা',
  L10nKeys.gardenGrowth: 'বাঢ়ি আছে',
  L10nKeys.gardenDidYouKnow:
      'প্ৰতিটো কাৰ্যকলাপ সম্পন্ন হ’লে আপোনাৰ বাগিচা বাঢ়ে।',
  L10nKeys.gardenPlantSeed: 'মাহ বিচক',

  L10nKeys.activitiesTitle: 'কাৰ্যকলাপ',
  L10nKeys.activitiesToday: 'আজি',
  L10nKeys.activitiesLibrary: 'আৰু কাৰ্যকলাপ',
  L10nKeys.mainGamesTitle: 'মুখ্য খেল',
  L10nKeys.activitiesStart: 'আৰম্ভ',
  L10nKeys.activitiesCompleted: 'সম্পন্ন',
  L10nKeys.activitiesInProgress: 'জাৰি আছে',
  L10nKeys.activitiesNotStarted: 'সাজু',
  L10nKeys.activityYoureDone: 'বৰ ধুনীয়া!',
  L10nKeys.activityPraise: 'আপুনি বাগিচাত নতুন জীৱন যোগালে। 🌱',
  L10nKeys.activityHint: 'ইংগিত লাগে?',
  L10nKeys.activityTryAgain: 'এই স্মৃতিটো আকৌ চাওক',
  L10nKeys.activityOptionsHint: 'আপোনাৰ উত্তৰ দাওক',
  L10nKeys.activityTapToMatch: 'যিবোৰ একেলগে খাপ খায় সেইবোৰ দাওক',
  L10nKeys.activityNext: 'আগলৈ',
  L10nKeys.activityFinish: 'সমাপ্ত',
  L10nKeys.activityGroupLetsAgain: 'এইটো আকৌ চাওক',
  L10nKeys.activityGroupTogether: 'একেলগে এইটো কৰোঁ আহক',
  L10nKeys.activityGreatJob: 'বেৰা ভাল!',
  L10nKeys.activityKitchen: 'মোৰ ৰন্ধা ঘৰ',
  L10nKeys.activityShopping: 'মোৰ দোকান',
  L10nKeys.activityMatching: 'যোৰ মিলাওক',
  L10nKeys.activitySequence: 'ক্ৰমত সজাওক',
  L10nKeys.activityRecognition: 'এইটো কি?',
  L10nKeys.activityAssociation: 'কি একেলগে যায়?',
  L10nKeys.activityRecall: 'মনত আছে নেকি?',
  L10nKeys.activityAttention: 'বিচাৰি উলিয়াওক',
  L10nKeys.activityDurationSuffix: 'মিনিট',
  L10nKeys.activityTodayDone: 'আজিৰ কাৰ্যকলাপ সম্পন্ন',
  L10nKeys.activityTodayDoneBody:
      'আপোনাৰ বাগিচা বাঢ়িল। কাইলৈ নতুন স্মৃতি বাটি থাকিব পাৰে।',
  L10nKeys.activityGardenGrew: 'আপোনাৰ বাগিচা বাঢ়িল!',
  L10nKeys.activityMemoryUnlocked: 'এটা স্মৃতি মুকলি হ’ল',
  L10nKeys.activityReadAloud: 'উচ্চস্বৰে পঢ়ক',

  L10nKeys.kitchenTitle: 'চাহ বনাওঁ আহক',
  L10nKeys.kitchenMakeChai: 'চাহ বনোৱা',
  L10nKeys.kitchenMakeChaiPrompt: 'সঠিক ক্ৰমত খোজবোৰ দাওক।',
  L10nKeys.kitchenSteps: 'খোজ',
  L10nKeys.kitchenTapInOrder: 'সঠিক ক্ৰমত খোজবোৰ দাওক',
  L10nKeys.kitchenCorrectOrder: 'ডাঙৰীয়া! চাহ সাজু!',
  L10nKeys.kitchenBreakfast: 'পুৱাৰ আহাৰ বনোৱা',
  L10nKeys.kitchenBreakfastHint: 'দিনটোৰ সতেজ আৰম্ভণি',
  L10nKeys.kitchenBreakfastPrompt: 'পুৱাৰ আহাৰৰ খোজবোৰ ক্ৰমত সজাওক।',

  L10nKeys.shopTitle: 'মোৰ দোকান',
  L10nKeys.shopGetMilkBread: 'পাউৰুটি আৰু গাখীৰ',
  L10nKeys.shopGetMilkBreadPrompt: '₹১০০ৰ ভিতৰত গাখীৰ আৰু পাউৰুটি আনক।',
  L10nKeys.shopBudget: 'বাজেট',
  L10nKeys.shopBasket: 'আপোনাৰ টোপোলা',
  L10nKeys.shopTotal: 'মুঠ',
  L10nKeys.shopWithinBudget: 'বাজেটৰ ভিতৰত!',
  L10nKeys.shopOverBudget: 'বাজেটতকৈ বেছি — আকৌ চাওক',
  L10nKeys.shopCheckout: 'সম্পন্ন আৰু পৰিশোধ',
  L10nKeys.shopBuy: 'টোপোলাত দিয়ক',
  L10nKeys.shopSell: 'আঁতৰাওক',
  L10nKeys.shopVeggies: 'ৰাতিৰ আহাৰৰ পাচলি',
  L10nKeys.shopVeggiesPrompt: '₹৬০ৰ ভিতৰত আলু আৰু পিয়াঁজ আনক।',
  L10nKeys.recKitchenItem: 'এইটো কোনটো?',
  L10nKeys.recKitchenItemPrompt:
      'বজাৰৰ পৰা সামগ্ৰী আনিবলৈ এইবোৰৰ কোনটো ব্যৱহাৰ হয়?',
  L10nKeys.recCurrency: 'অলপ টকা',
  L10nKeys.recCurrencyPrompt: 'কোন নোটটো ₹২০ হয়?',
  L10nKeys.matchFestival: 'উৎসৱ মিলাওক',
  L10nKeys.matchFestivalPrompt: 'প্ৰতিটো উৎসৱক তাৰ বিশেষ আহাৰৰ সৈতে মিলাওক।',
  L10nKeys.matchObjectUse: 'যোৰ মিলাওক',
  L10nKeys.matchObjectUsePrompt:
      'প্ৰতিটো বস্তু তাৰ ব্যৱহাৰৰ সময়ৰ সৈতে মিলাওক।',
  L10nKeys.seqMorning: 'পুৱাৰ নিয়ম',
  L10nKeys.seqMorningPrompt: 'আপোনাৰ পুৱাৰ নিয়ম ক্ৰমত সজাওক।',
  L10nKeys.seqRoute: 'পুৱাৰ যাত্ৰা',
  L10nKeys.seqRoutePrompt: 'বজাৰলৈ যোৱা যাত্ৰা ক্ৰমত সজাওক।',
  L10nKeys.assoRegion: 'ইয়াত কি আছে?',
  L10nKeys.assoRegionPrompt: 'অসম কিয় বিখ্যাত?',
  L10nKeys.assoHarvest: 'মিঠা ফল',
  L10nKeys.assoHarvestPrompt: 'কোনটো ফলক গ্ৰীষ্মৰ ৰজা বোলা হয়?',
  L10nKeys.attnVeg: 'গাজৰ বিচাৰক',
  L10nKeys.attnVegPrompt: 'গাজৰটো বিচাৰি পাব নেকি?',
  L10nKeys.recallSong: 'এটা চিনাকি গীত',
  L10nKeys.recallSongPrompt: 'বিহুত নৃত্যশিল্পীসকলে কোন গীতত নাচে?',
  L10nKeys.activityPairs: 'যোৰা বিচাৰক',
  L10nKeys.activitySequenceRecall: 'ক্ৰম মনত ৰাখক',
  L10nKeys.activityFindChanged: 'কি সলনি হ’ল?',
  L10nKeys.pairsFruits: 'বজাৰৰ ফল',
  L10nKeys.pairsKitchen: 'ৰান্ধনীঘৰৰ বস্তু',
  L10nKeys.pairsRemember: 'বিলাক কাৰ্ড মন দি চাওক, তাৰ পিছত একে যোৰা বিচাৰক।',
  L10nKeys.pairsStart: 'কাৰ্ড লুকুৱাই আৰম্ভ কৰক',
  L10nKeys.pairsFound: 'যোৰা পালে!',
  L10nKeys.seqRecallItems: 'দৈনন্দিন বস্তু',
  L10nKeys.seqRecallNumbers: 'ক্ৰমে ক্ৰমে সংখ্যা',
  L10nKeys.seqRecallWatch: 'কাৰ্ডবোৰ মন দি চাওক – প্ৰতিটো ক্ৰমে জ্বলিব।',
  L10nKeys.seqRecallRepeat: 'এতিয়া দেখাৰ ক্ৰমৰে কাৰ্ডবোৰত টিপক।',
  L10nKeys.changeMarket: 'ফলৰ টুকুৰি',
  L10nKeys.changeFestival: 'উৎসৱৰ বন্তি',
  L10nKeys.changeRemember: 'এই ছবিবোৰ মন দি মনত ৰাখক।',
  L10nKeys.changeFind: 'এখন ছবি সলনি হৈছে। বেলেগ ছবি খুঁজক।',
  L10nKeys.changeCorrect: 'বাহ! সেইখনেই সলনি হৈছিল।',

  L10nKeys.mysteryTitle: 'আজিৰ বিশেষ স্মৃতি',
  L10nKeys.mysteryLocked: 'এটা বিশেষ স্মৃতি আপোনাৰ বাবে অপেক্ষাত…',
  L10nKeys.mysteryLockedBody:
      'আজি ২-৩টা সৰু কাৰ্যকলাপ কৰক, ই মুকলি হ’ব পাৰে। ই কি হ’ব?',
  L10nKeys.mysteryUnlocked: 'আপোনাৰ বিশেষ স্মৃতি ইয়াত!',
  L10nKeys.mysteryUnlockedBody: 'এই স্মৃতিটো কেৱল আপোনাৰ। আপোনাৰ সময় লওক। 🌸',
  L10nKeys.mysteryCuriosity: 'আজি কি মুকলি হ’ব?',
  L10nKeys.mysteryOpen: 'স্মৃতি মুকলি',

  L10nKeys.memoriesTitle: 'মোৰ স্মৃতি',
  L10nKeys.memoriesEmpty: 'এতিয়ালৈ কোনো স্মৃতি নাই',
  L10nKeys.memoriesEmptyBody:
      'আপোনাৰ পৰিয়ালে ফটো আৰু মাত যোগ দিব পাৰে। উপলব্ধ হ’লে ইয়াত দেখা দিব।',
  L10nKeys.memoriesFamily: 'পৰিয়াল',
  L10nKeys.memoriesPlaces: 'স্থান',
  L10nKeys.memoriesFestivals: 'উৎসৱ',
  L10nKeys.memoriesChildhood: 'শৈশৱ',
  L10nKeys.memoriesKindPhoto: 'ফটো',
  L10nKeys.memoriesKindVoice: 'মাতৰ বাৰ্তা',
  L10nKeys.memoriesKindText: 'কাহিনী',
  L10nKeys.memoriesKindSound: 'মাত',
  L10nKeys.memoriesKindPlace: 'স্থান',
  L10nKeys.memoriesAddedBy: 'যোগ কৰিছে',
  L10nKeys.memoriesWhoIsThis: 'এওঁ কোন?',
  L10nKeys.memoriesPlayVoice: 'শুনক',
  L10nKeys.memoriesThisIsMe: 'এই ময়েই',
  L10nKeys.memoriesNotMe: 'মই নহয়',

  L10nKeys.profileTitle: 'প্ৰফাইল',
  L10nKeys.profileLanguage: 'এপৰ ভাষা',
  L10nKeys.profileRegion: 'মোৰ অঞ্চল',
  L10nKeys.profileVoiceLanguage: 'মাতৰ ভাষা',
  L10nKeys.profileVoicePrompts: 'মাতৰ সংকেত',
  L10nKeys.profileTextSize: 'আখৰৰ আকাৰ',
  L10nKeys.profileReducedMotion: 'শান্ত গতি',
  L10nKeys.profileSoundEffects: 'শব্দ প্ৰভাৱ',
  L10nKeys.profileFamily: 'পৰিয়াল',
  L10nKeys.profileContacts: 'জৰুৰী যোগাযোগ',
  L10nKeys.profileDemoMode: 'ডেম’ ম’ড',
  L10nKeys.profileReminders: 'সোঁৱৰণী',
  L10nKeys.profileNeedHelp: 'সহায় লাগে?',

  L10nKeys.remindersTitle: 'সোঁৱৰণী',
  L10nKeys.remindersEmpty: 'এতিয়ালৈ কোনো সোঁৱৰণী নাই',
  L10nKeys.remindersNew: 'নতুন সোঁৱৰণী',
  L10nKeys.remindersTitleLabel: 'শিৰোনামা',
  L10nKeys.remindersDetailLabel: 'বিশদ (বিকল্প)',
  L10nKeys.remindersTime: 'সময়',
  L10nKeys.remindersDays: 'দিন',
  L10nKeys.remindersEveryday: 'প্ৰতিদিন',
  L10nKeys.remindersEnabled: 'চালু',
  L10nKeys.remindersMedicine: 'ঔষধ',
  L10nKeys.remindersAppointment: 'এপইণ্টমেণ্ট',
  L10nKeys.remindersRoutine: 'দৈনিক নিয়ম',

  L10nKeys.dayMon: 'সোম',
  L10nKeys.dayTue: 'মঙ্গল',
  L10nKeys.dayWed: 'বুধ',
  L10nKeys.dayThu: 'বৃহস্পতি',
  L10nKeys.dayFri: 'শুকুৰ',
  L10nKeys.daySat: 'শনি',
  L10nKeys.daySun: 'ৰবি',

  L10nKeys.sosTitle: 'জৰুৰী সহায়',
  L10nKeys.sosExplain: 'দবাই ধৰি ৰাখক। মাইণ্ডকেয়াৰে আপোনাৰ জৰুৰী যোগাযোগসকলক এটা এটাকৈ জনাব। ই জৰুৰী সেৱা (যেনে 112) নহয়।',
  L10nKeys.sosHold: 'সহায়ৰ বাবে দবাই ধৰি ৰাখক',
  L10nKeys.sosHoldBody: 'দবাই ধৰি ৰাখক…',
  L10nKeys.sosActiveTitle: 'সহায়ক যোগাযোগ কৰা হৈছে',
  L10nKeys.sosActiveBody: 'আপোনাৰ পৰিয়ালক জনোৱা হৈছে। তেওঁলোকে উত্তৰ নিদিলে পিছৰ যোগাযোগজনক মতা হ’ব।',
  L10nKeys.sosContacting: 'যোগাযোগ',
  L10nKeys.sosContactFamily: 'পৰিয়ালৰ সৈতে যোগাযোগ',
  L10nKeys.sosContacted: 'জনোৱা হৈছে',
  L10nKeys.sosWaitingResponse: 'উত্তৰৰ বাবে অপেক্ষা…',
  L10nKeys.sosEscalating: 'পিছৰজনলৈ যোগাযোগ…',
  L10nKeys.sosCancelled: 'সহায় অনুৰোধ বাতিল',
  L10nKeys.sosCancelAction: 'সহায় অনুৰোধ বাতিল কৰক',
  L10nKeys.sosDone: 'হৈ গ’ল',
  L10nKeys.sosHelpOnWay: 'সহায় লৈ কোনোবা আহিব। 🧡',
  L10nKeys.sosNoContacts: 'এতিয়ালৈ কোনো জৰুৰী যোগাযোগ নাই',
  L10nKeys.sosNoContactsBody:
      'অনুগ্ৰহ কৰি পৰিয়ালক জৰুৰী যোগাযোগ যোগ দিবলৈ কওক।',
  L10nKeys.sosAddContact: 'যোগাযোগ যোগ',
  L10nKeys.sosDisclaimer: 'মাইণ্ডকেয়াৰে আপোনাৰ মনোনীত যোগাযোগসকলক জনায়। ই চৰকাৰী জৰুৰী সেৱাৰ বিকল্প নহয়।',
  L10nKeys.sosContactedPerson: 'পৰিয়ালৰ সদস্যক জনোৱা হৈছে',
  L10nKeys.sosEscalatedTo: 'পিছৰ পৰিয়ালৰ সদস্যক জনোৱা হৈছে',
  L10nKeys.sosAcknowledged: 'পৰিয়ালৰ সদস্যই উত্তৰ দিছে। সহায় আহি আছে।',
  L10nKeys.sosNotSilent: 'সহায় পঠোৱা নহ’লে আমি কেতিয়াও পঠোৱা বুলি নকওঁ।',
  L10nKeys.sosAlertNotDelivered:
      'আপোনাৰ বাৰ্তা এতিয়াও পঠোৱা হোৱা নাই। আমি চেষ্টা কৰি থাকিম।',

  L10nKeys.careTitle: 'যত্নকৰ্তা',
  L10nKeys.careDashboard: 'আভাস',
  L10nKeys.carePatients: 'মোৰ ৰোগী',
  L10nKeys.careMemories: 'স্মৃতি',
  L10nKeys.careContacts: 'জৰুৰী যোগাযোগ',
  L10nKeys.careSettings: 'ছেটিংছ',
  L10nKeys.careAddMemory: 'স্মৃতি যোগ',
  L10nKeys.careAddContact: 'যোগাযোগ যোগ',
  L10nKeys.careEngagement: 'সহভাগিতা',
  L10nKeys.careActivitiesWeek: 'এই সপ্তাহৰ কাৰ্যকলাপ',
  L10nKeys.careGardenProgress: 'বাগিচাৰ অগ্ৰগতি',
  L10nKeys.careRecentActivity: 'শেহতীয়া কাৰ্যকলাপ',
  L10nKeys.careNoPatients: 'কোনো সংযুক্ত ৰোগী নাই',
  L10nKeys.careNoPatientsBody:
      'পৰিয়ালৰ সদস্যক সংযোগ হ’বলৈ কওক, বা ৰোগী প্ৰফাইল যোগ দিয়ক।',
  L10nKeys.careAddPatient: 'ৰোগী যোগ',
  L10nKeys.carePerformanceNote:
      'শেহতীয়া কাৰ্যকলাপৰ প্ৰদৰ্শন এই ব্যক্তিজনৰ সাধাৰণ স্তৰতকৈ অলপ কম।',
  L10nKeys.careUploadPhoto: 'ফটো আপলোড',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'মাত ৰেকৰ্ড',
  L10nKeys.careWriteMemory: 'স্মৃতি লিখক',
  L10nKeys.careMemoryTitle: 'শিৰোনামা',
  L10nKeys.careMemoryCaption: 'বেৰণ',
  L10nKeys.careMemoryRelation: 'ইয়াত কোন আছে? (সম্পৰ্ক)',
  L10nKeys.careMemoryCategory: 'শ্ৰেণী',
  L10nKeys.careContactName: 'নাম',
  L10nKeys.careContactPhone: 'ফোন নম্বৰ',
  L10nKeys.careContactPriority: 'কলৰ ক্ৰম',
  L10nKeys.careContactRelation: 'সম্পৰ্ক',
  L10nKeys.careEscalationTimeout: 'পিছৰ যোগাযোগলৈ সময় (মিনিট)',
  L10nKeys.careIncidentStatus: 'অৱস্থা',
  L10nKeys.careAckSos: 'মই উত্তৰ দিছো',
  L10nKeys.careResponding: 'উত্তৰ দিছে',
  L10nKeys.careActiveAlerts: 'সক্ৰিয় সকিয়নি',

  L10nKeys.syncSavingOffline: 'অফলাইন',
  L10nKeys.syncSavingOfflineBody: 'আপোনাৰ কাৰ্যকলাপ এই ডিভাইচত সাঁচি ৰখা হৈছে।',
  L10nKeys.syncSynced: 'সিংক হৈছে',
  L10nKeys.syncInfo: 'আপোনাৰ তথ্য সিংক হ’ল।',
  L10nKeys.syncPending: 'সিংকৰ অপেক্ষা',

  L10nKeys.errorGeneric: 'কিবা এটা সমস্যা হ’ল',
  L10nKeys.errorGenericBody:
      'আপোনাৰ অগ্ৰগতি সুৰক্ষিত। অনুগ্ৰহ কৰি আকৌ চেষ্টা কৰক।',
  L10nKeys.errorAudio: 'এই ডিভাইচত শব্দ নবজাল।',
  L10nKeys.errorPermission: 'এই বাবে ডিভাইচৰ অনুমতি লাগে।',
  L10nKeys.errorNoInternetAction:
      'ইন্টাৰনেটৰ আৱশ্যক নাই — প্ৰথমে ইয়াতে সাঁচি ৰখা হয়।',

  L10nKeys.demoWelcome: 'ডেম’ চাওক',
  L10nKeys.demoExplain:
      'অন্বেষণৰ বাবে এটা নমুনা পৰিয়াল আৰু স্মৃতি যোগ দিয়া হ’ব।',
  L10nKeys.demoLoad: 'ডেম’ বাগিচা আৰম্ভ',

  L10nKeys.unitsPoints: 'পইণ্ট',
  L10nKeys.teaserChai: 'চাহ বনাওঁ আহক।',
  L10nKeys.familiarityName: 'আশা',
  L10nKeys.regionMap: 'মোৰ অঞ্চল',
  L10nKeys.regionChoose: 'আপোনাৰ অঞ্চল বাছক',
  L10nKeys.regionIndia: 'ভাৰত',
  L10nKeys.importantMemory: 'গুৰুত্বপূৰ্ণ স্মৃতি',
  L10nKeys.growing: 'বাঢ়ি আছে',
  L10nKeys.blooming: 'ফুলি আছে',
  L10nKeys.mature: 'পূৰ্ণবয়স্ক',
  L10nKeys.noVoice: 'এই ডিভাইচত মাত উপলব্ধ নাই।',
  L10nKeys.optional: 'বিকল্প',

  L10nKeys.langChoose: 'ভাষা বাছক',
  L10nKeys.langPrimary: 'মুখ্য',
  L10nKeys.langNorthEast: 'উত্তৰ-পূব ভাৰত',
  L10nKeys.langMajor: 'ভাৰতৰ মুখ্য ভাষা',

  L10nKeys.authSignUpTitle: 'আপোনাৰ একাউণ্ট বনাওক',
  L10nKeys.authSignUpBody: 'এই মাইণ্ডকেয়াৰ প্ৰফাইল আপোনাৰ ডিভাইচত সুৰক্ষিত হৈ থাকিব। কেৱল আপুনি ইয়াক খুলিবলৈ ইউজাৰনেম আৰু পাছৱৰ্ড ব্যৱহাৰ কৰিব।',
  L10nKeys.authLoginTitle: 'স্বাগতম ঘূৰাই',
  L10nKeys.authLoginBody: 'আপোনাৰ বাগিচা খুলিবলৈ ইউজাৰনেম আৰু পাছৱৰ্ড দিয়ক।',
  L10nKeys.authUsername: 'ইউজাৰনেম',
  L10nKeys.authUsernameHint: 'যেনে ranu123',
  L10nKeys.authDisplayName: 'আপোনাৰ নাম',
  L10nKeys.authPassword: 'পাছৱৰ্ড',
  L10nKeys.authPasswordHint: 'অন্ততঃ ৬ টা আখৰ',
  L10nKeys.authConfirmPassword: 'পাছৱৰ্ড আকৌ',
  L10nKeys.authRoleQuestion: 'এই প্ৰফাইলজনৰ বাবে…',
  L10nKeys.authRolePatient: 'মোৰ বাবে',
  L10nKeys.authRoleCaregiver: 'পৰিয়ালৰ সদস্যৰ বাবে',
  L10nKeys.authCreate: 'একাউণ্ট বনাওক',
  L10nKeys.authSignIn: 'ছাইন ইন',
  L10nKeys.authSignOut: 'ছাইন আউট',
  L10nKeys.authAccount: 'একাউণ্ট',
  L10nKeys.caregiverTitle: 'যত্নকৰ্তা',
  L10nKeys.caregiverNotLinked: 'এতিয়ালৈকে কোনো যত্নকৰ্তা সংযোগ হোৱা নাই',
  L10nKeys.authBadCredentials: 'ইউজারনেম বা পাছৱৰ্ড ভুল।',
  L10nKeys.authUsernameTaken: 'এই ইউজারনেমটো ইতিমধ্যে এই ডিভাইচত আছে।',
  L10nKeys.authPasswordMismatch: 'পাছৱৰ্ডবোৰ মিলা নাই।',
  L10nKeys.authUsernameShort: 'ইউজারনেম অন্ততঃ ৩ টা আখৰ লাগিব।',
  L10nKeys.authUsernameInvalid:
      'কেৱল আখৰ, সংখ্যা, বিন্দু, ডেশ বা আণ্ডাৰস্ক’ ব্যৱহাৰ কৰক।',
  L10nKeys.authPasswordShort: 'পাছৱৰ্ড অন্ততঃ ৬ টা আখৰ লাগিব।',
  L10nKeys.authNameRequired: 'অনুগ্ৰহ কৰি নাম দিয়ক।',
  L10nKeys.authSignOutConfirm: 'এই প্ৰফাইলৰ পৰা ছাইন আউট কৰিব নেকি?',
  L10nKeys.screenTitle: 'ত্বৰিত স্মৃতি পৰীক্ষা',
  L10nKeys.screenIntro: 'আমি ৰোগীৰ বিষয়ে কেইটামান চুটি প্ৰশ্ন সুধিম। বিগত কেইমাহত তেওঁলোক কেনেকুৱা আছিল, ভাবি চাওক।',
  L10nKeys.screenNotSure: 'নিশ্চিত নহয়',
  L10nKeys.screenFinish: 'মোৰ ফলাফল চাওক',
  L10nKeys.screenSkip: 'এতিয়াই নকৰো',
  L10nKeys.screenResultBack: 'হৈ গল',
  L10nKeys.screenCheckAgain: 'আৰু এবাৰ চাওক',
  L10nKeys.screenStartCheckup: 'পৰীক্ষা আৰম্ভ কৰক',
  L10nKeys.screenSkipped: 'পৰীক্ষা এৰি দিয়া হল',
  L10nKeys.screenStatusGood: 'সব ভালেই আছে',
  L10nKeys.screenStatusGoodBody: 'কোনো ডাঙৰ চিন্তা দেখা পোৱা নগল। দৈনন্দিন কামবোৰ কৰি থাকক, আৰু কিবা সলনি হলে যিকোনো সময়ত আকৌ পৰীক্ষা কৰিব পাৰে।',
  L10nKeys.screenStatusWatch: 'কিছু পৰিৱৰ্তন দেখা গল',
  L10nKeys.screenStatusWatchBody: 'কিছু পাহৰি যোৱাৰ মুহূৰ্ত দেখা গল। বয়সৰ লগত এইটো সাধাৰণ, কিন্তু চকু ৰাখক আৰু পৰৱৰ্তী ডাক্তৰ লগত কোৱা।',
  L10nKeys.screenStatusDoctor: 'অনুগ্ৰহ কৰি পৰীক্ষা কৰাওক',
  L10nKeys.screenStatusDoctorBody: 'কিছু লক্ষণ দেখা গৈছে যিবোৰত মন দিয়াৰ প্ৰয়োজন। অনুগ্ৰহ কৰি এইবোৰ ডাক্তৰ বা ক্লিনিকক জনাওক যাতে তেওঁলোকে সহায় কৰিব পাৰে।',
  L10nKeys.screenRarely: 'অতঃসৰল',
  L10nKeys.screenSometimes: 'কেতিয়াবা কেতিয়াবা',
  L10nKeys.screenFrequently: 'অনেকবাৰ',
  L10nKeys.screenVeryFrequently: 'বহু বাৰ',
  L10nKeys.screenQ01: 'তেওঁলোকে সাম্প্ৰতিক ঘটনা মনত ৰখাত সমস্যা হয় নেকি?',
  L10nKeys.screenQ02: 'তেওঁলোকে একে প্ৰশ্ন বা সাধু বাৰে বাৰে কয় নেকি?',
  L10nKeys.screenQ03: 'তেওঁলোকে পৰিচিত মানুহৰ নাম পাহৰি যায় নেকি?',
  L10nKeys.screenQ04: 'তেওঁলোকৰ পৰিচিত মুখ চিনিবলৈ সমস্যা হয় নেকি?',
  L10nKeys.screenQ05:
      'তেওঁলোকে নিযুক্ত সময় বা গুৰুত্বপূৰ্ণ ঘটনা পাহৰি যায় নেকি?',
  L10nKeys.screenQ06: 'তেওঁলোকৰ সঠিক শব্দ বিচাৰিবলৈ সমস্যা হয় নেকি?',
  L10nKeys.screenQ07: 'তেওঁলোকে কত আছে বুলি বিভ্ৰান্ত হয় নেকি?',
  L10nKeys.screenQ08:
      'তেওঁলোকক দৈনন্দিন কামবোৰৰ বাবে মনত পেলাই দিয়াৰ প্ৰয়োজন হয় নেকি?',
  L10nKeys.screenQ09: 'তেওঁলোকৰ ঔষধ চলাবলৈ সমস্যা হয় নেকি?',
  L10nKeys.screenQ10: 'তেওঁলোকে বিভ্ৰান্ত হলে চিন্তিত বা বিৰক্ত হয় নেকি?',
  L10nKeys.screenQ11: 'তেওঁলোকৰ কথা-বতৰা বুজিবলৈ সমস্যা হয় নেকি?',
  L10nKeys.screenQ12: 'তেওঁলোকৰ পৰিচিত কাম শেষ কৰিবলৈ সমস্যা হয় নেকি?',
  L10nKeys.screenQ13: 'তেওঁলোকে ভুলি যায় নেকি দৈনন্দিন বস্তু কত ৰখা হয়?',
  L10nKeys.screenQ14: 'তেওঁলোকৰ নিৰ্দেশনা মনত ৰখাত সমস্যা হয় নেকি?',
  L10nKeys.screenQ15: 'তেওঁলোকৰ বহু-পদক্ষেপৰ কাম কৰাত সমস্যা হয় নেকি?',

  L10nKeys.careDashboardSubtitle: 'পৰিয়ালৰ যত্ন',
  L10nKeys.careSosLive: 'লাইভ সতৰ্কবাৰ্তা',
  L10nKeys.careSosRespondedBy: '{name} এ উত্তৰ দিছে',
  L10nKeys.careLinkTitle: 'পৰিয়ালৰ সদস্যৰ সৈতে সংযোগ কৰক',
  L10nKeys.careLinkBody: 'আপোনাৰ প্ৰিয়জনক তেওঁলোকৰ ফোনত থকা 6-আখৰৰ পৰিয়ালৰ কোডটো সোধক, তাৰ পিছত সংযোগ কৰক।',
  L10nKeys.careLinkCode: 'পৰিয়ালৰ কোড',
  L10nKeys.careLinkCodeHint: 'যেনে A1B2C3',
  L10nKeys.careLinkConnect: 'সংযোগ',
  L10nKeys.careLinkDone: 'সংযোগ হৈছে',
  L10nKeys.careLinkSuccess:
      '{name} লগত সংযোগ হৈছে! স্মৃতিবোৰ আৰু সতৰ্কবাৰ্তাবোৰ এতিয়া সিংক হ’ব।',
  L10nKeys.careLinkFailed:
      'সংযোগ কৰিব পৰা নাযায়। অনুগ্ৰহ কৰি কোডটো পৰীক্ষা কৰি পুনৰ চেষ্টা কৰক।',
  L10nKeys.careTrendsTitle: 'AI প্ৰৱণতা',
  L10nKeys.careTrendsBody: 'কাৰ্য্যৰ ধৰণ অনুসৰি দৈনিক শুদ্ধতা',
  L10nKeys.careTrendsNoData:
      'এতিয়াও কোনো কাৰ্য্য নাই — প্ৰৱণতা চাবলৈ এটা অনুশীলন সম্পূৰ্ণ কৰক।',
  L10nKeys.careAiDifficulty: 'স্বয়ংক্ৰিয়ভাৱে লগোৱা কঠিনতা',
  L10nKeys.careAiAccuracy: 'মডেলৰ শুদ্ধতা',
  L10nKeys.careAiRealSessions: 'প্ৰকৃত অধিবেশন',
  L10nKeys.careAiDemoSessions: 'ডেমো অধিবেশন',
  L10nKeys.careNavGames: 'খেল',
  L10nKeys.careNavRoutine: 'নিত্যকৰ্ম',
  L10nKeys.careGreetSubtitle: 'চাওক আজি {name} কেনে আছে।',
  L10nKeys.careNotifEmpty: 'কোনো নতুন জাননী নাই',
  L10nKeys.careWellnessScore: 'জ্ঞানগত সুস্থতা স্কোৰ',
  L10nKeys.careStatusStable: 'স্থিৰ',
  L10nKeys.careStatusAttention: 'মনোযোগ প্ৰয়োজন',
  L10nKeys.careLastSynced: 'সবশেষ ছিংক {time}',
  L10nKeys.careMinAgo: '{n} মিনিট আগত',
  L10nKeys.careGamesWeek: 'এই সপ্তাহৰ খেল',
  L10nKeys.careRoutineCompletion: 'নিত্যকৰ্ম সম্পন্ন',
  L10nKeys.careCurrentStreak: 'বৰ্তমান স্ট্ৰিক',
  L10nKeys.careMoodCheckins: 'মুড চেক-ইন',
  L10nKeys.careDayUnit: 'দিন',
  L10nKeys.careDaysUnit: 'দিন',
  L10nKeys.careActivityTitle: 'সাপ্তাহিক কাৰ্যকলাপ',
  L10nKeys.careWeekly: 'সাপ্তাহিক',
  L10nKeys.careMonthly: 'মাহেকীয়া',
  L10nKeys.careNoActivityWeek:
      'এই সপ্তাহত এতিয়ালৈ কোনো কাৰ্যকলাপ লিপিবদ্ধ হোৱা নাই।',
  L10nKeys.careMoodTitle: 'মুড',
  L10nKeys.careMoodHappy: 'সন্তুষ্ট',
  L10nKeys.careMoodCalm: 'শান্ত',
  L10nKeys.careMoodNeutral: 'নিউট্ৰেল',
  L10nKeys.careMoodLow: 'নিম্ন',
  L10nKeys.careMood7Days: 'শেষ ৭ দিন',
  L10nKeys.careMoodInsight: '{name} এই সপ্তাহত বেছিভাগ সময় শান্ত আছিল, শেষ দুদিনত সামান্য হ্ৰাস পোৱা গৈছে।',
  L10nKeys.careMoodNoData: 'এই সপ্তাহত এতিয়ালৈ কোনো মুড চেক-ইন নাই।',
  L10nKeys.careSkillsTitle: 'জ্ঞানগত দক্ষতা',
  L10nKeys.careSkillMemory: 'স্মৃতিশক্তি',
  L10nKeys.careSkillAttention: 'মনোযোগ',
  L10nKeys.careSkillLanguage: 'ভাষা',
  L10nKeys.careSkillReasoning: 'তাৰ্কিক ক্ষমতা',
  L10nKeys.careSkillProcessing: 'প্ৰক্ৰিয়াকৰণ গতি',
  L10nKeys.careInsightToday: 'আজিৰ অন্তৰ্দৃষ্টি',
  L10nKeys.careInsightBody: 'ৰবাৰ্টে ৰাতিপুৱাৰ নিত্যকৰ্মৰ পিছত স্মৃতিশক্তিৰ কাৰ্যকলাপত ধাৰাবাহিকভাৱে জড়িত আছিল। শেষ দুদিনত তেওঁৰ মুড কিছুটা নিম্নমুখী আছিল।',
  L10nKeys.careInsightBodyReal: 'এই সপ্তাহত {name}য়ে {count}টা জ্ঞানগত অধিবেশন সম্পন্ন কৰিছে (লক্ষ্য {goal}) আৰু {streak} দিনীয়া স্ট্ৰিক বজাই ৰাখিছে।',
  L10nKeys.careViewDetails: 'বিশদ চাওক',
  L10nKeys.careInsightDisclaimer:
      'এইটো তথ্যৰ পৰা লোৱা এটা সৌম্য পৰ্যবেক্ষণ — চিকিৎসা নিৰ্ণয় নহয়।',
  L10nKeys.careAttentionTitle: 'আপোনাৰ মনোযোগ প্ৰয়োজন',
  L10nKeys.careAttentionEmpty: 'এতিয়া আপোনাৰ মনোযোগৰ প্ৰয়োজন হোৱা একো নাই।',
  L10nKeys.careAlertSos: '{name}য়ে SOS বুটাম টিপিছে',
  L10nKeys.careAlertRoutineMissed: 'কালি নিত্যকৰ্ম মিস হৈছে',
  L10nKeys.careAlertMoodDown: 'শেষ দুদিনত মুড হ্ৰাস পাইছে',
  L10nKeys.careAlertSessionPending: 'আজি জ্ঞানগত অধিবেশন সম্পন্ন হোৱা নাই',
  L10nKeys.careAlertSeverityHigh: 'উচ্চ',
  L10nKeys.careAlertSeverityMedium: 'মধ্যম',
  L10nKeys.careAlertSeverityLow: 'নিম্ন',
  L10nKeys.careWeeklySummary: 'সাপ্তাহিক সাৰাংশ',
  L10nKeys.careSessionsCompleted: 'সম্পন্ন অধিবেশন',
  L10nKeys.careAvgSessionDuration: 'গড় অধিবেশন সময়',
  L10nKeys.careRoutineAdherence: 'নিত্যকৰ্ম অনুসৰণ',
  L10nKeys.careMoodTrend: 'মুড প্ৰৱণতা',
  L10nKeys.careMoodTrendSlightlyDown: 'সামান্য নিম্ন',
  L10nKeys.careMoodTrendStable: 'স্থিৰ',
  L10nKeys.careMoodTrendUp: 'উন্নতি হৈছে',
  L10nKeys.careVsLastWeek: 'গত সপ্তাহৰ তুলনাত',
  L10nKeys.careSyncedJustNow: 'এইমাত্ৰ ছিংক হৈছে',
  L10nKeys.careOfflineWaiting: 'অফলাইন · {count}টা কাৰ্যকলাপ ছিংকৰ অপেক্ষাত',
  L10nKeys.careComingSoon: 'অচিৰেই আহি আছে',
  L10nKeys.careHomeSoon: '{name}ৰ দিনটোৰ এটা চমু আভাস ইয়াত দেখা যাব।',
  L10nKeys.careGamesSoon: 'খেল আৰু অধিবেশন ইতিহাস ইয়াত দেখা যাব।',
  L10nKeys.careRoutineSoon: 'ৰোগীৰ দৈনিক নিত্যকৰ্ম ইয়াত দেখা যাব।',
  L10nKeys.careProfileSoon: 'যত্নকৰ্তাৰ প্ৰফাইল আৰু ছেটিংছ ইয়াত দেখা যাব।',
  L10nKeys.serverPairingTitle: 'পৰিয়ালৰ কোড',
  L10nKeys.serverPairingBody: 'এই কোডটো কোনোবা যত্নকৰ্তাৰ সৈতে ভাগ কৰক যাতে তেওঁলোকে আপোনাৰ লগত সংযোগ কৰিব পাৰে।',
  L10nKeys.serverUnlinked: 'ছাৰ্ভাৰৰ সৈতে সংযোগ নাই',
  L10nKeys.serverLinked: 'ছাৰ্ভাৰৰ সৈতে সংযোগ হৈছে',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
