import '../l10n_keys.dart';

/// Santali dictionary in Devanagari script (best-effort machine-assisted translation; native review required).
/// Core food-market terms corroborated against Glosbe.
/// Official Ol Chiki script can be added later. Untranslated keys fall back to English.
const Map<String, String> stringsSat = {
  L10nKeys.appName: 'Companio',
  // How to play (tutorials)
  L10nKeys.tutListen: 'Listen',
  L10nKeys.tutPairs1: 'Watch the pictures carefully. Soon they will be hidden.',
  L10nKeys.tutPairs2: 'Tap a card to turn it around.',
  L10nKeys.tutPairs3: 'Find two of the very same picture.',
  L10nKeys.tutSeq1: 'Watch the cards light up one by one.',
  L10nKeys.tutSeq2: 'Remember the order.',
  L10nKeys.tutSeq3: 'Tap the cards in the same order.',
  L10nKeys.tutRecall1: 'Read or listen to the question.',
  L10nKeys.tutRecall2: 'Tap the answer you remember.',
  L10nKeys.tutRecall3: 'Choose one answer to finish.',
  L10nKeys.tutMatch1: 'Look at the pictures on the left.',
  L10nKeys.tutMatch2: 'Tap the matching picture on the right.',
  L10nKeys.tutMatch3: 'Match every pair to finish.',
  L10nKeys.tutNoFail: 'Take your time. There is no failing.',
  L10nKeys.tagline: 'आपंक यादन रे साथी',
  L10nKeys.back: 'आट',
  L10nKeys.next: 'आहल',
  L10nKeys.continueText: 'आहलन जाओ',
  L10nKeys.skip: 'ओहोड़',
  L10nKeys.done: 'सिदाम',
  L10nKeys.cancel: 'माड़',
  L10nKeys.yes: 'होए',
  L10nKeys.no: 'नाया',
  L10nKeys.save: 'गोचन',
  L10nKeys.close: 'कज',
  L10nKeys.retry: 'हड़े हड़े जाहा',
  L10nKeys.add: 'अलाय',
  L10nKeys.edit: 'सलाय',
  L10nKeys.remove: 'जोहोड़',
  L10nKeys.search: 'एनंज',
  L10nKeys.today: 'दिना',
  L10nKeys.offline: 'इंटरनेट बाहा',
  L10nKeys.online: 'इंटरनेट रे',

  L10nKeys.goodMorning: 'सुबह भले',
  L10nKeys.goodAfternoon: 'दिन भले',
  L10nKeys.goodEvening: 'संझा भले',
  L10nKeys.goodNight: 'रात भले',

  L10nKeys.navHome: 'ओराक',
  L10nKeys.navGarden: 'बगीचा',
  L10nKeys.navActivities: 'काज कमम',
  L10nKeys.navMemories: 'यादनो',
  L10nKeys.navProfile: 'प्रोफाइल',
  L10nKeys.navMystery: 'दिना के याद',

  L10nKeys.onboardingWelcomeTitle: 'आपंक यादन रे आसिया तायेब',
  L10nKeys.onboardingWelcomeBody: 'माइंडकेयर एनईआर इंटरनेट बाहा ने याद गोड़ क, खेल क, अर ओराक रेव दोबो जोमाओ क।',
  L10nKeys.onboardingNameTitle: 'सिमे आपो घन कने चेता?',
  L10nKeys.onboardingNameHint: 'आपंक नांव',
  L10nKeys.onboardingRegionTitle: 'आपंक ओराक कनह रे ओड़ा?',
  L10nKeys.onboardingRegionHint: 'गांव नो महानगर',
  L10nKeys.onboardingRegionList: 'दुमका, जामताड़ा, देवघर, साहिबगंज, गोडा, पाकुड़, रांची, गुवाहाटी, शिलांग, अगरतला',
  L10nKeys.onboardingLanguageTitle: 'आपरे मोन कन भाषाये दो भले आर?',
  L10nKeys.onboardingLanguageBody: 'आपोन ह़ाजे हो माड़ा ट केतेह ने तयोहाड़।',
  L10nKeys.onboardingFamilyTitle: 'ओराक रेव सकाड़र?',
  L10nKeys.onboardingFamilyBody:
      'आपंक भला लगाओ मिनसकनो दो अनाय, ते सोनोहोख़ठा अर आड़यान याद गोड़ क।',
  L10nKeys.onboardingAddFamily: 'ओराक रेव सकाड़ अनाय',
  L10nKeys.onboardingEmergencyTitle: 'हकातहन रे सकाड़कनो कानी पुरान?',
  L10nKeys.onboardingEmergencyBody:
      'SOS थपट रे माइंडकेयर आपंक ओराक रेवलो दो पुराओ, — दो क खान दो बाहं ते।',
  L10nKeys.onboardingEmergencyName: 'नांव',
  L10nKeys.onboardingEmergencyPhone: 'फोन नंबर',
  L10nKeys.onboardingEmergencyRelation: 'मन (धी, कोड़ा…)',
  L10nKeys.onboardingDoneTitle: 'आपंक बगीचा तायेब!',
  L10nKeys.onboardingDoneBody: 'एकड़कि काज कम्म में सिदाम कर मे, अर बगीचा बाड़ ब दुईटा देख मे। आले आपं बगे साथी रे।',
  L10nKeys.onboardingStart: 'एमन बगीचा घालकाद',

  L10nKeys.homeWhatsGrowing: 'दिना कनह बाड़ ए दुई?',
  L10nKeys.homeTodayActivity: 'दिना मे काज कमम',
  L10nKeys.homeActivityDuration: '३ मिनिट टाक ओ़होका',
  L10nKeys.homeMinutes: 'मिनिट',
  L10nKeys.homeMemoryOfDay: 'दिना के याद',
  L10nKeys.homeMemoryLocked: 'ए काया याद आंमण नगड़ ए दारहाय…',
  L10nKeys.homeMemoryUnlocked: 'ए याद चटाआओन!',
  L10nKeys.homeContinueActivity: 'काज कमम जोहारा आहलन जाओ',
  L10nKeys.homeFamilyMemory: 'आपंक ओराक रेहें',
  L10nKeys.homeFamilyMemoryEmpty: 'ओराक रेव याद ian ठेन दुईटा मनम।',
  L10nKeys.homeSos: 'सहायता दराय',
  L10nKeys.homeSosSubtitle: 'हकातहन रे ओराक रेवलो पुरा',
  L10nKeys.homeGardenPreview: 'आपंक बगीचा',
  L10nKeys.homeEngine: 'माइंडकेयर साथी',
  L10nKeys.homeEngineReady: 'आपंक सहायता तायेब।',
  L10nKeys.homeWelcomeBack: 'सावा गोलो! बगीचा जोहारा आहलन जाओ। 🌸',
  L10nKeys.homeNoActivity: 'दिना काज कमम बाहं',
  L10nKeys.homeNoActivityBody:
      'चोतोई क निरम कम मे — न यात दो आपं भला कमम में घूर। 🌻',

  L10nKeys.gardenTitle: 'एमन याद बगीचा',
  L10nKeys.gardenSectionAll: 'चेना',
  L10nKeys.gardenSectionFamily: 'ओराक',
  L10nKeys.gardenSectionChildhood: 'होनन समय',
  L10nKeys.gardenSectionPlaces: 'जगा',
  L10nKeys.gardenSectionFestivals: 'परब',
  L10nKeys.gardenEmpty: 'आपंक बगीचा साथ बिजाराय',
  L10nKeys.gardenEmptyBody:
      'ए पहिल काज कमम में सिदाम, रे आंजे ठें ए बीज बिआदाओं।',
  L10nKeys.gardenPoints: 'पोयंट',
  L10nKeys.gardenLevel: 'सोर',
  L10nKeys.gardenSeed: 'बीज',
  L10nKeys.gardenPlant: 'गुड़',
  L10nKeys.gardenFlower: 'फुल',
  L10nKeys.gardenTree: 'दार',
  L10nKeys.gardenMilestone: 'संता',
  L10nKeys.gardenGrowth: 'बाड़',
  L10nKeys.gardenDidYouKnow: 'चेना काज कमम सिदाम रे आपंक बगीचा बाड़।',
  L10nKeys.gardenPlantSeed: 'बीज बिआदाओं',

  L10nKeys.activitiesTitle: 'काज कमम',
  L10nKeys.activitiesToday: 'दिना',
  L10nKeys.activitiesLibrary: 'आहल काज कमम',
  L10nKeys.mainGamesTitle: 'मूख्य खेल',
  L10nKeys.activitiesStart: 'घालकाद',
  L10nKeys.activitiesCompleted: 'सिदाम कद',
  L10nKeys.activitiesInProgress: 'जोहारा',
  L10nKeys.activitiesNotStarted: 'तायेब',
  L10nKeys.activityYoureDone: 'भले अतब!',
  L10nKeys.activityPraise: 'आपोन बगीचा ठे ए जाकाट तायेब हो। 🌱',
  L10nKeys.activityHint: 'सहायता दराय?',
  L10nKeys.activityTryAgain: 'याद दो हड़े देख्',
  L10nKeys.activityOptionsHint: 'आपंक आकार घूर',
  L10nKeys.activityTapToMatch: 'साथ जोमाओ रेव घूर',
  L10nKeys.activityNext: 'आहल',
  L10nKeys.activityFinish: 'सिदाम',
  L10nKeys.activityGroupLetsAgain: 'हड़े देख् क',
  L10nKeys.activityGroupTogether: 'हज़ारे बगे ताले',
  L10nKeys.activityGreatJob: 'भले काज!',
  L10nKeys.activityKitchen: 'एमन सनदर',
  L10nKeys.activityShopping: 'एमन हाट',
  L10nKeys.activityMatching: 'जोमाओ',
  L10nKeys.activitySequence: 'सिदुक भाना',
  L10nKeys.activityRecognition: 'इए कनह?',
  L10nKeys.activityAssociation: 'कनह साथ जोमाओ?',
  L10nKeys.activityRecall: 'आपोन चेता आ?',
  L10nKeys.activityAttention: 'एनंज',
  L10nKeys.activityDurationSuffix: 'मिनिट',
  L10nKeys.activityTodayDone: 'दिना के काज कमम सिदाम कद',
  L10nKeys.activityTodayDoneBody: 'आपंक बगीचा बाड़ ए। सीयोम ए याद दारहाय ब।',
  L10nKeys.activityGardenGrew: 'आपंक बगीचा बाड़ ए!',
  L10nKeys.activityMemoryUnlocked: 'ए याद चटाआओन',
  L10nKeys.activityReadAloud: 'उच्चे लोड़ देग',

  L10nKeys.kitchenTitle: 'चाह लेओट क',
  L10nKeys.kitchenMakeChai: 'चाह लेओट',
  L10nKeys.kitchenMakeChaiPrompt: 'काज कमम चेना सिदुक रे घूर।',
  L10nKeys.kitchenSteps: 'काज कमम',
  L10nKeys.kitchenTapInOrder: 'काज कमम सिदुक रे घूर',
  L10nKeys.kitchenCorrectOrder: 'भले! चाह तायेब!',
  L10nKeys.kitchenBreakfast: 'सुबह रे चना',
  L10nKeys.kitchenBreakfastHint: 'दिना के पहिल आराम',
  L10nKeys.kitchenBreakfastPrompt: 'सुबह रेव चना काज कमम सिदुक रे घूर।',

  L10nKeys.shopTitle: 'एमन हाट',
  L10nKeys.shopGetMilkBread: 'तोआ अर रोटी',
  L10nKeys.shopGetMilkBreadPrompt: '₹१०० रे तोआ अर रोटी ओवोहोक।',
  L10nKeys.shopBudget: 'जोड़ा',
  L10nKeys.shopBasket: 'आपंक बीठा',
  L10nKeys.shopTotal: 'चेना',
  L10nKeys.shopWithinBudget: 'जोड़ा रे!',
  L10nKeys.shopOverBudget: 'जोड़ा दो बाड़िएं — हड़े देख्',
  L10nKeys.shopCheckout: 'सिदाम कर अर दा',
  L10nKeys.shopBuy: 'बीठा रे थाक',
  L10nKeys.shopSell: 'ओहोड़',
  L10nKeys.shopVeggies: 'साँझ खाना लागी हड़',
  L10nKeys.shopVeggiesPrompt: '₹६० रे आलू अर पियाज ओवोहोक।',
  L10nKeys.recKitchenItem: 'इए कनह?',
  L10nKeys.recKitchenItemPrompt: 'हाट हें दो ओबोक ते कनह बाहा हो?',
  L10nKeys.recCurrency: 'पूरु ओट',
  L10nKeys.recCurrencyPrompt: 'कनह नोट ₹२० हो?',
  L10nKeys.matchFestival: 'परब जोमाओ',
  L10nKeys.matchFestivalPrompt: 'चेना परब में ते रेव खाना बगे जोमाओ।',
  L10nKeys.matchObjectUse: 'जोमाओ',
  L10nKeys.matchObjectUsePrompt: 'चेना रेव जिनिस कनह काज रे होहोक, साथ जोमाओ।',
  L10nKeys.seqMorning: 'सुबह के काज',
  L10nKeys.seqMorningPrompt: 'आपंक सुबह के काज सिदुक रे घूर।',
  L10nKeys.seqRoute: 'सुबह के राहा',
  L10nKeys.seqRoutePrompt: 'हाटन राहा सिदुक रे घूर।',
  L10nKeys.assoRegion: 'आनह ठेन कनह?',
  L10nKeys.assoRegionPrompt: 'असम कनह लागी मोनसी परसीसो हो?',
  L10nKeys.assoHarvest: 'मिठा फल',
  L10nKeys.assoHarvestPrompt: 'गरम दिना रे कनह फल राजा होहोक?',
  L10nKeys.attnVeg: 'गाजर एनंज',
  L10nKeys.attnVegPrompt: 'आपोन गाजर चेता दुईटा?',
  L10nKeys.recallSong: 'आदत सेरेङ',
  L10nKeys.recallSongPrompt: 'बिहू रोड़म रे कनह सेरेङ आ?',
  L10nKeys.activityPairs: 'जोड़ा लान्हा',
  L10nKeys.activitySequenceRecall: 'क्रम ओहोड़',
  L10nKeys.activityFindChanged: 'चेत बदल गोचे़?',
  L10nKeys.pairsFruits: 'बज़ार रे सकमरे',
  L10nKeys.pairsKitchen: 'ओड़े रे बस्तु',
  L10nKeys.pairsRemember: 'आलमा कार्ड रे तिरियो देखाड़, तबे जोड़ा लान्हा।',
  L10nKeys.pairsStart: 'कार्ड लुपाड़ आर बढ़ाया',
  L10nKeys.pairsFound: 'जोड़ा मेर गेड़ा!',
  L10nKeys.seqRecallItems: 'दिन दिने रे बस्तु',
  L10nKeys.seqRecallNumbers: 'क्रम रे संख्या',
  L10nKeys.seqRecallWatch: 'कार्ड रे तिरियो देखाड़ – क्रम क्रमे देवा आक्रा।',
  L10nKeys.seqRecallRepeat: 'अड़े दई देखके आकलिया, क्रमे कार्ड दापड़।',
  L10nKeys.changeMarket: 'सकमरे थिपा',
  L10nKeys.changeFestival: 'पर्व रे बाती',
  L10nKeys.changeRemember: 'एयीन चित्र रे तिरियो देखाड़।',
  L10nKeys.changeFind: 'एक चित्र बदल गेड़ा – अलग चित्र आवाया।',
  L10nKeys.changeCorrect: 'सेहा! ओहो बदल गेड़ा।',

  L10nKeys.mysteryTitle: 'दिना के ए काया याद',
  L10nKeys.mysteryLocked: 'ए काया याद आंमण नगड़ ए दारहाय…',
  L10nKeys.mysteryLockedBody:
      'दिना ए २–३ काज कमम सिदाम कर; यात कनह, ते कनह चटाआओन। कनह होय?',
  L10nKeys.mysteryUnlocked: 'आपंक काया याद आनह ठेन!',
  L10nKeys.mysteryUnlockedBody: 'इए याद दो आपं एनए गे। समय लेओको। 🌸',
  L10nKeys.mysteryCuriosity: 'दिना कनह चटाआओन?',
  L10nKeys.mysteryOpen: 'याद चटाआए',

  L10nKeys.memoriesTitle: 'एमन यादनो',
  L10nKeys.memoriesEmpty: 'मेना याद बाहं आ',
  L10nKeys.memoriesEmptyBody: 'आपंक ओराक रेव मन के सोनोहोख़ठा अर आड़यान थाक क। अयाय रोसोर आनह ठेन दुईटा मनम।',
  L10nKeys.memoriesFamily: 'ओराक',
  L10nKeys.memoriesPlaces: 'जगा',
  L10nKeys.memoriesFestivals: 'परब',
  L10nKeys.memoriesChildhood: 'होनन समय',
  L10nKeys.memoriesKindPhoto: 'सोनोहोख़्ठा',
  L10nKeys.memoriesKindVoice: 'आड़या आदम',
  L10nKeys.memoriesKindText: 'कहानी',
  L10nKeys.memoriesKindSound: 'आदम',
  L10nKeys.memoriesKindPlace: 'जगा',
  L10nKeys.memoriesAddedBy: 'थाककद',
  L10nKeys.memoriesWhoIsThis: 'इमकसिकंम?',
  L10nKeys.memoriesPlayVoice: 'शुरु',
  L10nKeys.memoriesThisIsMe: 'अहिएं',
  L10nKeys.memoriesNotMe: 'अहि नोहोय',

  L10nKeys.profileTitle: 'प्रोफाइल',
  L10nKeys.profileLanguage: 'एप भाषा',
  L10nKeys.profileRegion: 'एमन जगा',
  L10nKeys.profileVoiceLanguage: 'आड़या भाषा',
  L10nKeys.profileVoicePrompts: 'आड़या काज',
  L10nKeys.profileTextSize: 'तकरा नें',
  L10nKeys.profileReducedMotion: 'घुरं आराम',
  L10nKeys.profileSoundEffects: 'आदम',
  L10nKeys.profileFamily: 'ओराक',
  L10nKeys.profileContacts: 'हकातहन संपर्क',
  L10nKeys.profileDemoMode: 'डेमो मोड',
  L10nKeys.profileReminders: 'याद होहोक',
  L10nKeys.profileNeedHelp: 'सहायता दराय?',

  L10nKeys.remindersTitle: 'याद होहोक',
  L10nKeys.remindersEmpty: 'याद होहोक बाहं आ',
  L10nKeys.remindersNew: 'नाया याद होहोक',
  L10nKeys.remindersTitleLabel: 'नांव',
  L10nKeys.remindersDetailLabel: 'विवरण (दिलाएत)',
  L10nKeys.remindersTime: 'समय',
  L10nKeys.remindersDays: 'दिना',
  L10nKeys.remindersEveryday: 'चेना दिना',
  L10nKeys.remindersEnabled: 'तायेब',
  L10nKeys.remindersMedicine: 'दबाई',
  L10nKeys.remindersAppointment: 'डाक्तर मेल',
  L10nKeys.remindersRoutine: 'दिना के काज',

  L10nKeys.dayMon: 'सोमार',
  L10nKeys.dayTue: 'मंगलार',
  L10nKeys.dayWed: 'बुधार',
  L10nKeys.dayThu: 'गुरूवार',
  L10nKeys.dayFri: 'सुक्रबार',
  L10nKeys.daySat: 'संनीबार',
  L10nKeys.daySun: 'रबीबार',

  L10nKeys.sosTitle: 'हकातहन सहायता',
  L10nKeys.sosExplain: 'थपट रे कठोको। माइंडकेयर आपंक हकातहन संपर्कनो दो पुराओ, काड़े काड़े। इए हकातहन सेवा (११२) नोहोय।',
  L10nKeys.sosHold: 'सहायता लागी थपट रे कठो',
  L10nKeys.sosHoldBody: 'थपट रे कठो…',
  L10nKeys.sosActiveTitle: 'सहायता पुराए घड़',
  L10nKeys.sosActiveBody: 'आपंक ओराक रेवलो दो पुरोकद। अयाने किन आकार लाधाकद, चान बि काड़े कन आहललो पुरा।',
  L10nKeys.sosContacting: 'पुराए घड़',
  L10nKeys.sosContactFamily: 'ओराक रेवलो पुरा',
  L10nKeys.sosContacted: 'पुरोकद',
  L10nKeys.sosWaitingResponse: 'आकार दारहाय…',
  L10nKeys.sosEscalating: 'आहल साथी पुराए घड़…',
  L10nKeys.sosCancelled: 'सहायता दो माड़ा कद',
  L10nKeys.sosCancelAction: 'सहायता माड़ा कर',
  L10nKeys.sosDone: 'सिदाम',
  L10nKeys.sosHelpOnWay: 'ए मिनस आपं लेको ते करहँका हती। 🧡',
  L10nKeys.sosNoContacts: 'हकातहन संपर्क बाहं आ',
  L10nKeys.sosNoContactsBody: 'हिलां कर, ओराक रेवलो बि हकातहन संपर्क थाक क।',
  L10nKeys.sosAddContact: 'संपर्क अनाय',
  L10nKeys.sosDisclaimer:
      'माइंडकेयर आपं घूड़्ना रेवलो दो पुराओ गे। इए आधिकारिक हकातहन सेवा नोहोय।',
  L10nKeys.sosContactedPerson: 'ओराक रेव लो पुरोकद',
  L10nKeys.sosEscalatedTo: 'आहल ओराक रेवलो पुरोकद',
  L10nKeys.sosAcknowledged: 'ओराक रेव आकार लाधाअद। सहायता ले ओड़ा हते।',
  L10nKeys.sosNotSilent: 'सहायता पुराओड़ बाहं होय खान, आले दो नजेम बाहं।',
  L10nKeys.sosAlertNotDelivered:
      'आपंक लोड़ दो अयायेत हीडुऐं ब परे; आले दो बिजारा दो।',

  L10nKeys.careTitle: 'ओराक रेव',
  L10nKeys.careDashboard: 'देख्',
  L10nKeys.carePatients: 'एमन ओराक रेव',
  L10nKeys.careMemories: 'यादनो',
  L10nKeys.careContacts: 'हकातहन संपर्क',
  L10nKeys.careSettings: 'सलाय',
  L10nKeys.careAddMemory: 'याद अनाय',
  L10nKeys.careAddContact: 'संपर्क अनाय',
  L10nKeys.careEngagement: 'जोहारा',
  L10nKeys.careActivitiesWeek: 'इए हप्ता रेव काज कमम',
  L10nKeys.careGardenProgress: 'बगीचा बाड़',
  L10nKeys.careRecentActivity: 'आखिर काज कमम',
  L10nKeys.careNoPatients: 'ओराक रेव बाहं आ',
  L10nKeys.careNoPatientsBody: 'ओराक रेवलो जोड़ाओ बि या, नो ए प्रोफाइल थाक।',
  L10nKeys.careAddPatient: 'रेवलो अनाय',
  L10nKeys.carePerformanceNote:
      'रेवलो के काज कमम अलेकाड़े आम आंचे रे लेकाचड़ी ।',
  L10nKeys.careRecordVoice: 'आड़या रिकॉर्ड',
  L10nKeys.careWriteMemory: 'याद चिमी',
  L10nKeys.careMemoryTitle: 'नांव',
  L10nKeys.careMemoryCaption: 'चिमी',
  L10nKeys.careMemoryRelation: 'आनह रे सकाड़? (मन)',
  L10nKeys.careMemoryCategory: 'जगा',
  L10nKeys.careContactName: 'नांव',
  L10nKeys.careContactPhone: 'फोन नंबर',
  L10nKeys.careContactPriority: 'पुराआहड़ सिदुक',
  L10nKeys.careContactRelation: 'मन',
  L10nKeys.careEscalationTimeout: 'आहल संपर्क केसेक मिनिट',
  L10nKeys.careIncidentStatus: 'हाल',
  L10nKeys.careAckSos: 'अलेरे आकार लाधाए घड़',
  L10nKeys.careResponding: 'आकार दोए घड़',
  L10nKeys.careActiveAlerts: 'हकातहन चेतावनी',

  L10nKeys.syncSavingOffline: 'इंटरनेट बाहा',
  L10nKeys.syncSavingOfflineBody: 'आपंक काज कमम इए उपकरण ठेन थाँवा कद।',
  L10nKeys.syncSynced: 'जोहारा कद',
  L10nKeys.syncInfo: 'आपंक यादनो जोहारा कद।',
  L10nKeys.syncPending: 'जोहारा दारहाय',

  L10nKeys.errorGeneric: 'कनह आले बुरा होद',
  L10nKeys.errorGenericBody: 'आपंक जोहारा दो तायेब। हिलां सिदाम हड़े घाला।',
  L10nKeys.errorAudio: 'इए उपकरण रे आड़या चालाओड़ दो बाहं।',
  L10nKeys.errorPermission: 'इए लागी उपकरण के साद थाक ब।',
  L10nKeys.errorNoInternetAction:
      'इंटरनेट दो बाहं — इए दो आनह ठेन बि थाँवा गोद।',

  L10nKeys.demoWelcome: 'डेमो देख्',
  L10nKeys.demoExplain: 'आपोन देख् लागी ए ओराक अर यादनो थाक ब।',
  L10nKeys.demoLoad: 'डेमो बगीचा घालकाद',

  L10nKeys.unitsPoints: 'पोयंट',
  L10nKeys.teaserChai: 'चाह लेओट क।',
  L10nKeys.familiarityName: 'माये सोरना',
  L10nKeys.regionMap: 'एमन जगा',
  L10nKeys.regionChoose: 'आपंक जगा घूर',
  L10nKeys.regionIndia: 'भारत',
  L10nKeys.importantMemory: 'काया याद',
  L10nKeys.growing: 'बाड़',
  L10nKeys.blooming: 'फुल',
  L10nKeys.mature: 'सदड',
  L10nKeys.noVoice: 'इए उपकरण रे आड़या बाहं।',
  L10nKeys.optional: 'दिलाएत',

  L10nKeys.langChoose: 'भाषा घूर',
  L10nKeys.langPrimary: 'मुख्य',
  L10nKeys.langNorthEast: 'पूर्वोत्तर भारत',
  L10nKeys.langMajor: 'भारत के मुख्य भाषा',

  L10nKeys.authSignUpTitle: 'आपंक खाता तायेब कर',
  L10nKeys.authSignUpBody: 'इए माइंडकेयर प्रोफाइल आपंक उपकरण ठेन बि थाँवा होय। आपोन गे चेता लागी नांव अर पासवर्ड थाक।',
  L10nKeys.authLoginTitle: 'सावा गोलो',
  L10nKeys.authLoginBody: 'आपं बगीचा घाला लागी नांव अर पासवर्ड में साइन इन कर।',
  L10nKeys.authUsername: 'नांव',
  L10nKeys.authUsernameHint: 'मसक सिहः ranu123',
  L10nKeys.authDisplayName: 'आपंक नांव',
  L10nKeys.authPassword: 'पासवर्ड',
  L10nKeys.authPasswordHint: 'नाहोम ६ लेक',
  L10nKeys.authConfirmPassword: 'पासवर्ड हड़े सिधामा',
  L10nKeys.authRoleQuestion: 'इए प्रोफाइल सकाड़कन लागी…',
  L10nKeys.authRolePatient: 'एमन लागी',
  L10nKeys.authRoleCaregiver: 'ओराक रेवकनिकन लागी',
  L10nKeys.authCreate: 'खाता तायेब कर',
  L10nKeys.authSignIn: 'साइन इन',
  L10nKeys.authSignOut: 'साइन आउट',
  L10nKeys.authAccount: 'खाता',
  L10nKeys.caregiverTitle: 'देखभालकर्ता',
  L10nKeys.caregiverNotLinked: 'अभी कोई देखभालकर्ता जुड़ा नहीं है',
  L10nKeys.authBadCredentials: 'नांव नो पासवर्ड दो बायंग।',
  L10nKeys.authUsernameTaken: 'इए नांव आनह उपकरण रे सिधाँवा कद।',
  L10nKeys.authPasswordMismatch: 'पासवर्ड बगे नोहोय।',
  L10nKeys.authUsernameShort: 'नांव नाहोम ३ लेक होय ब।',
  L10nKeys.authUsernameInvalid: 'खाना लेक, नंबर, डॉट, डैश नो आंडरस्कोर गे होय।',
  L10nKeys.authPasswordShort: 'पासवर्ड नाहोम ६ लेक होय ब।',
  L10nKeys.authNameRequired: 'नांव चिमी।',
  L10nKeys.authSignOutConfirm:
      'आपोन इए प्रोफाइल हें साइन आउट होय बाद हलाम चेता?',
  L10nKeys.screenTitle: 'चेता (याददाश्त) जाँच',
  L10nKeys.screenIntro: 'आले ओराक रेव रे काइना छोटा प्रश्न सोड़त। पिछ्ले मनिया हप्ता रे तार होन रे चेताओ।',
  L10nKeys.screenNotSure: 'जोहारा नों',
  L10nKeys.screenFinish: 'एन रे परीन दिखाओ',
  L10nKeys.screenSkip: 'आखिरे बचाओ',
  L10nKeys.screenResultBack: 'तायेब कद',
  L10nKeys.screenCheckAgain: 'तरे जाँच कर',
  L10nKeys.screenStartCheckup: 'जाँच आरम्भ कर',
  L10nKeys.screenSkipped: 'जाँच बचाओ कद',
  L10nKeys.screenStatusGood: 'दय ठीक मन देखेद',
  L10nKeys.screenStatusGoodBody: 'डंगो चिंता नों दिखाओ कद। दिन्री काज कमम करते रोड़ों — काइना बदल गोरोन मानबोन खान, कुनबे तरे जाँच देखेड़।',
  L10nKeys.screenStatusWatch: 'काइना बदल दिखाओ कद',
  L10nKeys.screenStatusWatchBody: 'चेताओड़ चेताओड़ काइना रुप दिखाओ कद। इए उमड़ रे साधारण, होय नोंना घड़िया रे ध्यान राखाओ डाँक्टर दा ले भेटे रे कोय।',
  L10nKeys.screenStatusDoctor: 'डाँक्टर ले जाँच कराओ',
  L10nKeys.screenStatusDoctorBody: 'काइना ऐसन दिखाओ होद, जेकरे ध्यान डोन्ड। रेवलो हकात रे इए डाँक्टर नों क्लिनिक दा ले था हाताव कर।',
  L10nKeys.screenRarely: 'फाकिरे',
  L10nKeys.screenSometimes: 'कहिया कहिया',
  L10nKeys.screenFrequently: 'अक्सरे',
  L10nKeys.screenVeryFrequently: 'बड़ो अक्सरे',
  L10nKeys.screenQ01: 'तार रे आने नोको रे घटना चेता र खड़न रे काइना दिकद ई?',
  L10nKeys.screenQ02: 'तार रे आने सोड़ा सोड़ा प्रश्न नों कथा दोहरायोगोड़ ई?',
  L10nKeys.screenQ03: 'तार रे आने जानावा मन रे नांव चेताओ बाहं ई?',
  L10nKeys.screenQ04: 'तार रे आने जानावा मन रे चेहरा हुयड़ा रे काइना दिकद ई?',
  L10nKeys.screenQ05: 'तार रे आने डेट नों आना दिन रे घटना चेताओ बाहं ई?',
  L10nKeys.screenQ06: 'तार रे आने सोन्द पाड़ होना रे काइना दिकद ई?',
  L10nKeys.screenQ07: 'तार रे आने तार सेरे हेत दिकद ई?',
  L10nKeys.screenQ08: 'तार रे आने दिन्री काज कमम ले चेता करावा हेत भला ठेक ई?',
  L10nKeys.screenQ09: 'तार रे आने दवा हुयड़ा रे काइना दिकद ई?',
  L10nKeys.screenQ10: 'तार रे आने सेरे होद खान चिंतित नों चिड़ी चिड़ी होयो ई?',
  L10nKeys.screenQ11:
      'तार रे आने गोड़े रे कथा, होड़ रे कथ गोलिया रे काइना दिकद ई?',
  L10nKeys.screenQ12: 'तार रे आने जानावा काज कमम तायेब हेत काइना दिकद ई?',
  L10nKeys.screenQ13:
      'तार रे आने दिन्री सामान काला रे थाँवा होकद हेत चेताओ बाहं ई?',
  L10nKeys.screenQ14: 'तार रे आने हुकुम चेता र खड़न रे काइना दिकद ई?',
  L10nKeys.screenQ15: 'तार रे आने डंगो चरण रे काज कमम कर रे काइना दिकद ई?',

  L10nKeys.careDashboardSubtitle: 'Family care',
  L10nKeys.careSosLive: 'Live alert',
  L10nKeys.careSosRespondedBy: 'Responded by {name}',
  L10nKeys.careLinkTitle: 'Connect to a family member',
  L10nKeys.careLinkBody: 'Ask your loved one for the 6-letter family code shown on their phone, then connect.',
  L10nKeys.careLinkCode: 'Family code',
  L10nKeys.careLinkCodeHint: 'e.g. A1B2C3',
  L10nKeys.careLinkConnect: 'Connect',
  L10nKeys.careLinkDone: 'Connected',
  L10nKeys.careLinkSuccess:
      'Linked to {name}! Memories and alerts will now sync.',
  L10nKeys.careLinkFailed:
      'Could not connect. Please check the code and try again.',
  L10nKeys.careTrendsTitle: 'AI trends',
  L10nKeys.careTrendsBody: 'Daily accuracy by activity type',
  L10nKeys.careTrendsNoData:
      'No activity yet — complete an exercise to see trends.',
  L10nKeys.careAiDifficulty: 'Auto-tuned difficulty',
  L10nKeys.careAiAccuracy: 'Model accuracy',
  L10nKeys.careAiRealSessions: 'Real sessions',
  L10nKeys.careAiDemoSessions: 'Demo sessions',
  L10nKeys.careNavGames: 'ᱠᱷᱮᱞ',
  L10nKeys.careNavRoutine: 'ᱫᱤᱱᱟ ᱠᱚᱡ',
  L10nKeys.careGreetSubtitle: '{name} ᱫᱤᱱᱟ ᱞᱮᱠᱚ ᱢᱮᱱᱚᱮ',
  L10nKeys.careNotifEmpty: 'ᱱᱚᱣᱚ ᱱᱳᱛᱤᱥ ᱵᱚᱦᱚ',
  L10nKeys.careWellnessScore: 'ᱢᱳᱱ ᱵᱷᱦᱚᱞᱚ ᱥᱠᱳᱨ',
  L10nKeys.careStatusStable: 'ᱵᱚᱫᱚᱞ ᱵᱚᱦᱚ',
  L10nKeys.careStatusAttention: 'ᱮᱱᱡ ᱞᱚᱜᱤᱚ',
  L10nKeys.careLastSynced: '{time} ᱨᱮ ᱡᱳᱦᱚᱨᱮ',
  L10nKeys.careMinAgo: '{n} ᱢᱤᱱᱤᱴ ᱯᱮᱞᱮ',
  L10nKeys.careGamesWeek: 'ᱱᱤ ᱦᱚᱯᱛᱚ ᱠᱷᱮᱞ',
  L10nKeys.careRoutineCompletion: 'ᱨᱩᱛᱤᱱ ᱥᱤᱫᱚᱢ',
  L10nKeys.careCurrentStreak: 'ᱱᱩᱦᱳ ᱞᱚᱜᱚᱛᱚᱨ',
  L10nKeys.careMoodCheckins: 'ᱢᱳᱱ ᱪᱦᱮᱠᱤᱱ',
  L10nKeys.careDayUnit: 'ᱫᱤᱱ',
  L10nKeys.careDaysUnit: 'ᱫᱤᱱ ᱠᱳ',
  L10nKeys.careActivityTitle: 'ᱦᱚᱯᱛᱚ ᱠᱚᱡ',
  L10nKeys.careWeekly: 'ᱦᱚᱯᱛᱚ',
  L10nKeys.careMonthly: 'ᱢᱚᱦᱤᱱᱚ',
  L10nKeys.careNoActivityWeek: 'ᱱᱤ ᱦᱚᱯᱛᱚᱨᱮ ᱠᱚᱡ ᱠᱮᱫᱚ ᱵᱚᱦᱚ',
  L10nKeys.careMoodTitle: 'ᱢᱳᱱ',
  L10nKeys.careMoodHappy: 'ᱵᱷᱚᱞᱮ',
  L10nKeys.careMoodCalm: 'ᱚᱨᱚᱢ',
  L10nKeys.careMoodNeutral: 'ᱥᱚᱢᱚᱱᱭᱚ',
  L10nKeys.careMoodLow: 'ᱱᱤᱪᱚ',
  L10nKeys.careMood7Days: 'ᱚᱠᱦᱤᱨ ᱫᱤᱱ ᱗',
  L10nKeys.careMoodInsight:
      '{name} ᱱᱤ ᱦᱚᱯᱛᱚ ᱚᱨᱚᱢ ᱢᱮᱱ, ᱯᱩᱨᱚ ᱫᱩᱤ ᱫᱤᱱᱨᱮ ᱱᱤᱪᱚ ᱡᱳᱞᱳ',
  L10nKeys.careMoodNoData: 'ᱱᱤ ᱦᱚᱯᱛᱚᱨᱮ ᱢᱳᱱ ᱪᱦᱮᱠᱤᱱ ᱵᱚᱦᱚ',
  L10nKeys.careSkillsTitle: 'ᱢᱳᱱ ᱚᱨᱳ ᱵᱩᱫᱫᱦᱤ',
  L10nKeys.careSkillMemory: 'ᱭᱚᱫ',
  L10nKeys.careSkillAttention: 'ᱮᱱᱡ',
  L10nKeys.careSkillLanguage: 'ᱵᱷᱚᱥᱚ',
  L10nKeys.careSkillReasoning: 'ᱵᱩᱡᱷᱚ',
  L10nKeys.careSkillProcessing: 'ᱥᱚᱥᱮᱨ ᱠᱚᱡ',
  L10nKeys.careInsightToday: 'ᱫᱤᱱᱚ ᱵᱩᱡᱷᱱᱚ',
  L10nKeys.careInsightBody:
      'Robert ᱥᱩᱵᱚᱨ ᱨᱩᱛᱤᱱᱨᱮ ᱭᱚᱫ ᱠᱚᱡ ᱫᱮᱨᱦᱮ, ᱯᱩᱨᱚ ᱫᱩᱤ ᱫᱤᱱᱨᱮ ᱩᱱ ᱢᱳᱱ ᱱᱤᱪᱚ᱾',
  L10nKeys.careInsightBodyReal: 'ᱱᱤ ᱦᱚᱯᱛᱚᱨᱮ {name} {count} ᱢᱳᱱ ᱥᱮᱥᱚᱱ ᱥᱤᱫᱚᱢᱮ (ᱞᱚᱠᱥᱭᱚ {goal}) ᱚᱨᱳ {streak} ᱫᱤᱱ ᱞᱚᱜᱚᱛᱚᱨ ᱫᱷᱚᱨ᱾',
  L10nKeys.careViewDetails: 'ᱫᱮᱠᱦ ᱵᱦᱤᱛᱨᱚ',
  L10nKeys.careInsightDisclaimer:
      'ᱱᱤᱦᱳ ᱫᱚᱛᱚ-ᱨᱮ ᱚᱨᱚᱢ ᱥᱳᱱᱚ, medical ᱱᱤᱨᱱᱳᱭ ᱱᱳᱦᱳ᱾',
  L10nKeys.careAttentionTitle: 'ᱚᱢ ᱮᱱᱡ ᱞᱚᱜᱤᱚ',
  L10nKeys.careAttentionEmpty: 'ᱱᱩᱦᱳ ᱚᱢ ᱮᱱᱡ ᱞᱚᱜᱤᱚ ᱵᱚᱦᱚ',
  L10nKeys.careAlertSos: '{name} SOS ᱛᱷᱚᱯᱚᱴ ᱠᱚᱫᱮ',
  L10nKeys.careAlertRoutineMissed: 'ᱠᱚᱞ ᱨᱩᱛᱤᱱ ᱵᱷᱩᱞᱳ ᱦᱳᱭᱳᱠ',
  L10nKeys.careAlertMoodDown: 'ᱯᱩᱨᱚ ᱫᱩᱤ ᱫᱤᱱᱨᱮ ᱢᱳᱱ ᱱᱤᱪᱚ ᱡᱳᱞᱳ',
  L10nKeys.careAlertSessionPending: 'ᱫᱤᱱᱚ ᱢᱳᱱ ᱥᱮᱥᱚᱱ ᱥᱤᱫᱚᱢ ᱱᱳᱦᱳ',
  L10nKeys.careAlertSeverityHigh: 'ᱢᱚᱨᱚᱝ',
  L10nKeys.careAlertSeverityMedium: 'ᱢᱚᱡᱦ',
  L10nKeys.careAlertSeverityLow: 'ᱱᱤᱪᱚ',
  L10nKeys.careWeeklySummary: 'ᱦᱚᱯᱛᱚ ᱞᱮᱠᱷᱚ',
  L10nKeys.careSessionsCompleted: 'ᱥᱮᱥᱚᱱ ᱠᱳ ᱥᱤᱫᱚᱢ',
  L10nKeys.careAvgSessionDuration: 'ᱢᱚᱡᱦ ᱥᱮᱥᱚᱱ ᱥᱳᱢᱳᱭ',
  L10nKeys.careRoutineAdherence: 'ᱨᱩᱛᱤᱱ ᱡᱳᱦᱚᱨᱮ',
  L10nKeys.careMoodTrend: 'ᱢᱳᱱ ᱵᱚᱫᱞᱚᱳ',
  L10nKeys.careMoodTrendSlightlyDown: 'ᱠᱳᱞᱳ ᱱᱤᱪᱚ',
  L10nKeys.careMoodTrendStable: 'ᱵᱚᱫᱚᱞ ᱵᱚᱦᱚ',
  L10nKeys.careMoodTrendUp: 'ᱦᱳᱭᱮ ᱪᱚᱞᱳ',
  L10nKeys.careVsLastWeek: 'ᱯᱩᱨᱚ ᱦᱚᱯᱛᱚ ᱵᱦᱤᱛᱨᱚ',
  L10nKeys.careSyncedJustNow: 'ᱱᱩᱦᱳ ᱡᱳᱦᱚᱨᱮ',
  L10nKeys.careOfflineWaiting: 'internet ᱵᱚᱦᱚ · {count} ᱠᱚᱡ ᱡᱳᱦᱚᱨᱮ ᱤᱱᱛᱚᱡᱚᱨ',
  L10nKeys.careComingSoon: 'ᱚᱦᱮᱱᱚ',
  L10nKeys.careHomeSoon: '{name} ᱫᱤᱱᱚ ᱠᱚᱛᱷᱚ ᱱᱤ ᱡᱚᱜᱜᱚᱨᱮ ᱚᱦᱮᱱᱚ',
  L10nKeys.careGamesSoon: 'ᱠᱷᱮᱞ ᱚᱨᱳ ᱥᱮᱥᱚᱱ ᱤᱛᱤᱦᱚᱥ ᱱᱤ ᱡᱚᱜᱜᱚᱨᱮ ᱚᱦᱮᱱᱚ',
  L10nKeys.careRoutineSoon: 'ᱨᱳᱜᱤ ᱫᱤᱱᱨᱤ ᱨᱩᱛᱤᱱ ᱱᱤ ᱡᱚᱜᱜᱚᱨᱮ ᱚᱦᱮᱱᱚ',
  L10nKeys.careProfileSoon: 'ᱥᱚᱦᱚᱭᱚᱠ profile ᱚᱨᱳ settings ᱱᱤ ᱡᱚᱜᱜᱚᱨᱮ ᱚᱦᱮᱱᱚ',
  L10nKeys.serverPairingTitle: 'Family code',
  L10nKeys.serverPairingBody:
      'Share this code with a caregiver so they can connect to you.',
  L10nKeys.serverUnlinked: 'Not connected to server',
  L10nKeys.serverLinked: 'Connected to server',
  L10nKeys.careUploadPhoto: 'Upload photo',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
  // Patient-home, memories, voice and calendar fallbacks (English source).
  L10nKeys.addFirstRoutine: 'आपंक पहिल दिना के काज अनाय',
  L10nKeys.addMemoryTooltip: 'याद अनाय',
  L10nKeys.addRoutine: 'दिना के काज अनाय',
  L10nKeys.addToMemory: 'ए याद रे अनाय',
  L10nKeys.attachmentsAddedMany: '{count} attachments added',
  L10nKeys.attachmentsAddedOne: '1 attachment added',
  L10nKeys.careAchieveEngagement: '10 Hours of Play',
  L10nKeys.careAchieveEngagementBody: '10 total hours spent playing together',
  L10nKeys.careAchieveFirstSteps: 'First Steps',
  L10nKeys.careAchieveFirstStepsBody: 'Patient completed their first session',
  L10nKeys.careAchieveGarden: 'Garden in Bloom',
  L10nKeys.careAchieveGardenBody: 'Grow 5 plants in the Memory Garden',
  L10nKeys.careAchievePerfect: 'Perfect Round',
  L10nKeys.careAchievePerfectBody: 'A game finished with a perfect score',
  L10nKeys.careAchieveSevenDay: 'One Week Together',
  L10nKeys.careAchieveSevenDayBody: 'A session on 7 different days',
  L10nKeys.categoryLabel: 'श्रेणी',
  L10nKeys.createMemory: 'एक याद तायेब कर',
  L10nKeys.deleteAction: 'जोहोड़',
  L10nKeys.deleteRoutineBody: 'आपंक दिना के काज रे "{title}" दो जोहोड़ होय?',
  L10nKeys.deleteRoutineTitle: 'दिना के काज जोहोड़?',
  L10nKeys.deleteRoutineTooltip: 'दिना के काज जोहोड़',
  L10nKeys.homeRoutineSubtitle: 'आपंक दिना लागी एक आरामं चोटो आकार।',
  L10nKeys.medicineKind: 'दबाई',
  L10nKeys.memoriesKindVideo: 'विडियो',
  L10nKeys.memoriesSubtitle: 'आपंक भले घड़ियानो दो बगे ताले थाक।',
  L10nKeys.memoryCaptionHint: 'कनह होद? ओसे रे थाको हो? कनह चेता होद?',
  L10nKeys.memoryCaptionLabel: 'ए याद आर ब काइना चिमी',
  L10nKeys.memoryComposeHint: 'एक नांव, काइना चिमी, अर आपंक ह़ाजे जानावा फोटो, विडियो नो आड़या नोट्स अनाय।',
  L10nKeys.memorySaved: 'याद गोचन कद 💙',
  L10nKeys.memoryTitleHint: 'उदाहरण: एमन धी के सादी',
  L10nKeys.memoryTitleLabel: 'याद नांव',
  L10nKeys.memoryTitleRequired: 'हिलां ए याद लागी नांव थाक।',
  L10nKeys.micVoicePermission: 'Microphone permission is needed for a voice memory.',
  L10nKeys.monthApr: 'Apr',
  L10nKeys.monthAug: 'Aug',
  L10nKeys.monthDec: 'Dec',
  L10nKeys.monthFeb: 'Feb',
  L10nKeys.monthJan: 'Jan',
  L10nKeys.monthJul: 'Jul',
  L10nKeys.monthJun: 'Jun',
  L10nKeys.monthMar: 'Mar',
  L10nKeys.monthMay: 'May',
  L10nKeys.monthNov: 'Nov',
  L10nKeys.monthOct: 'Oct',
  L10nKeys.monthSep: 'Sep',
  L10nKeys.photoAddFailed: 'ए फोटो दो अनाय नो होद। हिलां हड़े देख्।',
  L10nKeys.profileMissing: 'रोगी प्रोफाइल दो बाहं आ। हिलां हड़े साइन इन कर।',
  L10nKeys.recordingStartFailed: 'Could not start recording. Please try again.',
  L10nKeys.routineAddBody: 'आपंक दिना लागी एक सादड़ याद होहोक तायेब कर।',
  L10nKeys.routineAddTitle: 'नाया दिना के काज अनाय',
  L10nKeys.routineCheckBody: 'चंगे दिना लागी चोटो काज कमम',
  L10nKeys.routineCheckTitle: 'दिना के काज जाँच',
  L10nKeys.routineKind: 'दिना के काज',
  L10nKeys.routineNameHint: 'उदाहरण: तोआ नुस क',
  L10nKeys.routineNameLabel: 'दिना के काज नांव',
  L10nKeys.savedMemoriesTitle: 'Saved Memories',
  L10nKeys.saveMemory: 'याद गोचन',
  L10nKeys.settings: 'सेटिंग्स',
  L10nKeys.sosShort: 'SOS',
  L10nKeys.stop: 'रुकाओ',
  L10nKeys.stopVoiceFirst: 'सेता आड़या रिकॉर्डिंग रुकाओ।',
  L10nKeys.textShort: 'चिमी',
  L10nKeys.timeLabel: 'समय',
  L10nKeys.videoAddFailed: 'ए विडियो दो अनाय नो होद। हिलां हड़े देख्।',
  L10nKeys.voiceSaveFailed: 'Could not save the voice recording.',
  L10nKeys.voiceShort: 'आड़या',
  L10nKeys.waterKind: 'तोआ',
};
