import '../l10n_keys.dart';

/// Telugu dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsTe = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'మీ జ్ఞాపకాల తోడు',
  L10nKeys.back: 'వెనుకకు',
  L10nKeys.next: 'తరువాత',
  L10nKeys.continueText: 'కొనసాగించండి',
  L10nKeys.skip: 'దాటవేయి',
  L10nKeys.done: 'పూర్తయింది',
  L10nKeys.cancel: 'రద్దు',
  L10nKeys.yes: 'అవును',
  L10nKeys.no: 'లేదు',
  L10nKeys.save: 'భద్రపరచు',
  L10nKeys.close: 'మూసివేయి',
  L10nKeys.retry: 'మళ్ళీ ప్రయత్నించండి',
  L10nKeys.add: 'జోడించు',
  L10nKeys.edit: 'మార్చు',
  L10nKeys.remove: 'తీసివేయి',
  L10nKeys.search: 'వెతుకు',
  L10nKeys.today: 'నేడు',
  L10nKeys.offline: 'ఆఫ్‌లైన్',
  L10nKeys.online: 'ఆన్‌లైన్',

  L10nKeys.goodMorning: 'శుభోదయం',
  L10nKeys.goodAfternoon: 'నమస్తే',
  L10nKeys.goodEvening: 'శుభ సాయంత్రం',
  L10nKeys.goodNight: 'శుభ రాత్రి',

  L10nKeys.navHome: 'హోమ్',
  L10nKeys.navGarden: 'తోట',
  L10nKeys.navActivities: 'కార్యకలాపాలు',
  L10nKeys.navMemories: 'జ్ఞాపకాలు',
  L10nKeys.navProfile: 'ప్రొఫైల్',
  L10nKeys.navMystery: 'నేటి జ్ఞాపకం',

  L10nKeys.onboardingWelcomeTitle: 'మీ జ్ఞాపకాలకు సున్నితమైన తోడు',
  L10nKeys.onboardingWelcomeBody: 'మైండ్కేర్ ఎన్ఈఆర్ ఇంటర్నెట్ లేకుండానే గుర్తుంచుకోవడానికి, ఆడడానికి, కుటుంబంతో కలిసి ఉండటానికి సహాయపడుతుంది.',
  L10nKeys.onboardingNameTitle: 'మిమ్మల్ని ఏమని పిలవాలి?',
  L10nKeys.onboardingNameHint: 'మీ పేరు',
  L10nKeys.onboardingRegionTitle: 'మీ ఇల్లు ఎక్కడ?',
  L10nKeys.onboardingRegionHint: 'నగరం లేదా గ్రామం',
  L10nKeys.onboardingRegionList: 'గువహాటి, సిల్చార్, షిల్లాంగ్, అగర్తలా, ఇంఫాల్, ఐజోల్, ఇటానగర్, కోహిమా, గాంగ్టక్, డిబ్రుగఢ్, జోర్హాట్, మీ నగరం',
  L10nKeys.onboardingLanguageTitle: 'మీకు ఏ భాష నచ్చుతుంది?',
  L10nKeys.onboardingLanguageBody: 'దీన్ని ఎప్పుడైనా మార్చుకోవచ్చు.',
  L10nKeys.onboardingFamilyTitle: 'కుటుంబం ఎవరు?',
  L10nKeys.onboardingFamilyBody: 'మీ ప్రియమైనవారిని జోడించండి. వారి ఫోటోలను, గొంతును మృదువైన జ్ఞాపకాలుగా చూపిస్తాం.',
  L10nKeys.onboardingAddFamily: 'కుటుంబ సభ్యుడిని జోడించండి',
  L10nKeys.onboardingEmergencyTitle: 'అత్యవసరంలో మేమెవరిని పిలవాలి?',
  L10nKeys.onboardingEmergencyBody: 'SOS బటన్ నొక్కితే మైండ్కేర్ మీ కుటుంబానికి తెలియజేస్తుంది, అత్యవసర సేవలకు కాదు.',
  L10nKeys.onboardingEmergencyName: 'పేరు',
  L10nKeys.onboardingEmergencyPhone: 'ఫోన్ నంబర్',
  L10nKeys.onboardingEmergencyRelation: 'సంబంధం (కూతురు, కొడుకు…)',
  L10nKeys.onboardingDoneTitle: 'మీ తోట సిద్ధం!',
  L10nKeys.onboardingDoneBody: 'చిన్న కార్యకలాపాలు పూర్తి చేయండి, మీ తోట పెరుగుతున్నట్టు చూడండి. మేము మీకు తోడుగా ఉన్నాం.',
  L10nKeys.onboardingStart: 'నా తోటను ప్రారంభించు',

  L10nKeys.homeWhatsGrowing: 'నేడు ఏమి పెరుగుతోంది?',
  L10nKeys.homeTodayActivity: 'నేటి చిన్న కార్యకలాపం',
  L10nKeys.homeActivityDuration: 'సుమారు 3 నిమిషాలు',
  L10nKeys.homeMinutes: 'నిమిషం',
  L10nKeys.homeMemoryOfDay: 'నేటి జ్ఞాపకం',
  L10nKeys.homeMemoryLocked: 'ఒక ప్రత్యేక జ్ఞాపకం వేచి ఉంది…',
  L10nKeys.homeMemoryUnlocked: 'ఒక జ్ఞాపకం తెరుచుకుంది!',
  L10nKeys.homeContinueActivity: 'కార్యకలాపం కొనసాగించండి',
  L10nKeys.homeFamilyMemory: 'మీ కుటుంబం నుండి',
  L10nKeys.homeFamilyMemoryEmpty: 'కుటుంబ జ్ఞాపకాలు ఇక్కడ కనిపించవచ్చు.',
  L10nKeys.homeSos: 'సహాయం కావాలి',
  L10nKeys.homeSosSubtitle: 'అత్యవసరంలో కుటుంబాన్ని సంప్రదించండి',
  L10nKeys.homeGardenPreview: 'మీ తోట',
  L10nKeys.homeEngine: 'మైండ్కేర్ తోడు',
  L10nKeys.homeEngineReady: 'మీ సహాయకుడు సిద్ధంగా ఉన్నాడు.',
  L10nKeys.homeWelcomeBack: 'తిరిగి స్వాగతం! తోటను కొనసాగిద్దాం. 🌸',
  L10nKeys.homeNoActivity: 'నేడు కార్యకలాపం లేదు',
  L10nKeys.homeNoActivityBody:
      'కొంచెం విశ్రాంతి తీసుకోండి — లేదా ఇష్టమైన కార్యకలాపాన్ని ఎంచుకోండి. 🌻',

  L10nKeys.gardenTitle: 'నా జ్ఞాపకాల తోట',
  L10nKeys.gardenSectionAll: 'అన్నీ',
  L10nKeys.gardenSectionFamily: 'కుటుంబం',
  L10nKeys.gardenSectionChildhood: 'బాల్యం',
  L10nKeys.gardenSectionPlaces: 'ప్రదేశాలు',
  L10nKeys.gardenSectionFestivals: 'పండుగలు',
  L10nKeys.gardenEmpty: 'మీ తోట ఇప్పుడే మొదలైంది',
  L10nKeys.gardenEmptyBody:
      'మొదటి కార్యకలాపం పూర్తి చేయండి, ఇక్కడ విత్తనం నాటబడుతుంది.',
  L10nKeys.gardenPoints: 'పాయింట్లు',
  L10nKeys.gardenLevel: 'స్థాయి',
  L10nKeys.gardenSeed: 'విత్తనం',
  L10nKeys.gardenPlant: 'మొక్క',
  L10nKeys.gardenFlower: 'పువ్వు',
  L10nKeys.gardenTree: 'చెట్టు',
  L10nKeys.gardenMilestone: 'దశ',
  L10nKeys.gardenGrowth: 'పెరుగుతోంది',
  L10nKeys.gardenDidYouKnow: 'ప్రతి పూర్తయ్యే కార్యకలాపం మీ తోటను పెంచుతుంది.',
  L10nKeys.gardenPlantSeed: 'విత్తనం నాటండి',

  L10nKeys.activitiesTitle: 'కార్యకలాపాలు',
  L10nKeys.activitiesToday: 'నేడు',
  L10nKeys.activitiesLibrary: 'మరిన్ని కార్యకలాపాలు',
  L10nKeys.mainGamesTitle: 'ప్రధాన ఆటలు',
  L10nKeys.activitiesStart: 'ప్రారంభించు',
  L10nKeys.activitiesCompleted: 'పూర్తయినవి',
  L10nKeys.activitiesInProgress: 'నడుస్తున్నాయి',
  L10nKeys.activitiesNotStarted: 'సిద్ధంగా',
  L10nKeys.activityYoureDone: 'గొప్పది!',
  L10nKeys.activityPraise: 'మీరు తోటకి కొంచెం ప్రాణం పోశారు. 🌱',
  L10nKeys.activityHint: 'సూచన కావాలా?',
  L10nKeys.activityTryAgain: 'ఈ జ్ఞాపకాన్ని మళ్ళీ చూద్దాం',
  L10nKeys.activityOptionsHint: 'మీ సమాధానాన్ని ఎంచుకోండి',
  L10nKeys.activityTapToMatch: 'సరిపోయే జతను ఎంచుకోండి',
  L10nKeys.activityNext: 'తరువాత',
  L10nKeys.activityFinish: 'ముగించు',
  L10nKeys.activityGroupLetsAgain: 'దీన్ని మళ్ళీ చూద్దాం',
  L10nKeys.activityGroupTogether: 'దీన్ని కలిసి చేద్దాం',
  L10nKeys.activityGreatJob: 'బాగా చేశారు!',
  L10nKeys.activityKitchen: 'నా వంటగది',
  L10nKeys.activityShopping: 'నా దుకాణం',
  L10nKeys.activityMatching: 'జతపరచండి',
  L10nKeys.activitySequence: 'క్రమంలో అమర్చండి',
  L10nKeys.activityRecognition: 'ఇది ఏమిటి?',
  L10nKeys.activityAssociation: 'ఏమి కలిసి వస్తుంది?',
  L10nKeys.activityRecall: 'గుర్తుందా?',
  L10nKeys.activityAttention: 'వెతకండి',
  L10nKeys.activityDurationSuffix: 'నిమిషం',
  L10nKeys.activityTodayDone: 'నేటి కార్యకలాపం పూర్తయింది',
  L10nKeys.activityTodayDoneBody:
      'మీ తోట పెరిగింది. రేపు ఒక జ్ఞాపకం వేచి ఉంటుంది.',
  L10nKeys.activityGardenGrew: 'మీ తోట పెరిగింది!',
  L10nKeys.activityMemoryUnlocked: 'ఒక జ్ఞాపకం తెరుచుకుంది',
  L10nKeys.activityReadAloud: 'బిగ్గరగా చదవండి',

  L10nKeys.kitchenTitle: 'చాయ్ చేద్దాం',
  L10nKeys.kitchenMakeChai: 'చాయ్ తయారీ',
  L10nKeys.kitchenMakeChaiPrompt: 'దశలను సరైన క్రమంలో ఎంచుకోండి.',
  L10nKeys.kitchenSteps: 'దశలు',
  L10nKeys.kitchenTapInOrder: 'దశలను సరైన క్రమంలో ఎంచుకోండి',
  L10nKeys.kitchenCorrectOrder: 'బాగుంది! చాయ్ సిద్ధం!',
  L10nKeys.kitchenBreakfast: 'అల్పాహారం చేయడం',
  L10nKeys.kitchenBreakfastHint: 'రోజుకు తాజా ప్రారంభం',
  L10nKeys.kitchenBreakfastPrompt: 'అల్పాహారం దశలను క్రమంలో అమర్చండి.',

  L10nKeys.shopTitle: 'నా దుకాణం',
  L10nKeys.shopGetMilkBread: 'పాలు మరియు రొట్టె',
  L10nKeys.shopGetMilkBreadPrompt: '₹100 లో పాలు మరియు రొట్టె కొనండి.',
  L10nKeys.shopBudget: 'బడ్జెట్',
  L10nKeys.shopBasket: 'మీ బుట్ట',
  L10nKeys.shopTotal: 'మొత్తం',
  L10nKeys.shopWithinBudget: 'బడ్జెట్ లోపే!',
  L10nKeys.shopOverBudget: 'బడ్జెట్ మించిపోయింది — మళ్ళీ చూడండి',
  L10nKeys.shopCheckout: 'ముగించి చెల్లించండి',
  L10nKeys.shopBuy: 'బుట్టలో వేయండి',
  L10nKeys.shopSell: 'తీసివేయి',
  L10nKeys.shopVeggies: 'రాత్రి భోజనానికి కూరగాయలు',
  L10nKeys.shopVeggiesPrompt: '₹60 లో ఆలుగడ్డ, ఉల్లిపాయలు కొనండి.',
  L10nKeys.recKitchenItem: 'ఇది ఏది?',
  L10nKeys.recKitchenItemPrompt:
      'మార్కెట్ నుండి సరుకులు తీసుకురావడానికి దేన్ని వాడతాం?',
  L10nKeys.recCurrency: 'కొంచెం డబ్బు',
  L10nKeys.recCurrencyPrompt: 'ఏ నోటు ₹20?',
  L10nKeys.matchFestival: 'పండుగను జతపరచండి',
  L10nKeys.matchFestivalPrompt: 'ప్రతి పండుగను దాని ప్రత్యేక వంటకంతో జతపరచండి.',
  L10nKeys.matchObjectUse: 'జతపరచండి',
  L10nKeys.matchObjectUsePrompt: 'ప్రతి వస్తువును దాని వాడే సమయంతో జతపరచండి.',
  L10nKeys.seqMorning: 'ఉదయం దినచర్య',
  L10nKeys.seqMorningPrompt: 'మీ ఉదయపు దినచర్యను క్రమంలో అమర్చండి.',
  L10nKeys.seqRoute: 'ఉదయం ప్రయాణం',
  L10nKeys.seqRoutePrompt: 'మార్కెట్ వరకు ప్రయాణాన్ని క్రమంలో అమర్చండి.',
  L10nKeys.assoRegion: 'ఇక్కడ ఏముంది?',
  L10nKeys.assoRegionPrompt: 'అస్సాం దేనికి ప్రసిద్ధి?',
  L10nKeys.assoHarvest: 'తీపి పండు',
  L10nKeys.assoHarvestPrompt: 'ఏ పండును వేసవి రాజు అంటారు?',
  L10nKeys.attnVeg: 'క్యారెట్ వెతకండి',
  L10nKeys.attnVegPrompt: 'క్యారెట్ దొరుకుతుందా?',
  L10nKeys.recallSong: 'ఒక తెలిసిన పాట',
  L10nKeys.recallSongPrompt: 'బిహులో నృత్యం చేసేటప్పుడు ఏ పాట మోగుతుంది?',
  L10nKeys.activityPairs: 'జత కనుగొనండి',
  L10nKeys.activitySequenceRecall: 'క్రమాన్ని గుర్తుంచుకోండి',
  L10nKeys.activityFindChanged: 'ఏమి మారింది?',
  L10nKeys.pairsFruits: 'మార్కెట్ పండ్లు',
  L10nKeys.pairsKitchen: 'వంటింటి సామగ్రి',
  L10nKeys.pairsRemember:
      'అన్ని కార్డులను జాగ్రత్తగా చూడండి, తర్వాత ఒకే జతను కనుగొనండి.',
  L10nKeys.pairsStart: 'కార్డులు దాచి ప్రారంభించండి',
  L10nKeys.pairsFound: 'జత దొరికింది!',
  L10nKeys.seqRecallItems: 'రోజువారీ వస్తువులు',
  L10nKeys.seqRecallNumbers: 'క్రమంలో సంఖ్యలు',
  L10nKeys.seqRecallWatch:
      'కార్డులను జాగ్రత్తగా చూడండి – ప్రతిదీ క్రమంలో వెలుగుతుంది.',
  L10nKeys.seqRecallRepeat:
      'ఇప్పుడు మీరు చూసిన అదే క్రమంలో కార్డులను నొక్కండి.',
  L10nKeys.changeMarket: 'పండ్ల బుట్ట',
  L10nKeys.changeFestival: 'పండుగ దీపాలు',
  L10nKeys.changeRemember: 'ఈ చిత్రాలను జాగ్రత్తగా గుర్తుంచుకోండి.',
  L10nKeys.changeFind: 'ఒక చిత్రం మారింది. వేరైన దానిని కనుగొనండి.',
  L10nKeys.changeCorrect: 'బాగుంది! అదే మారింది.',

  L10nKeys.mysteryTitle: 'నేటి ప్రత్యేక జ్ఞాపకం',
  L10nKeys.mysteryLocked: 'ఒక ప్రత్యేక జ్ఞాపకం మీ కోసం వేచి ఉంది…',
  L10nKeys.mysteryLockedBody:
      'నేడు 2–3 చిన్న కార్యకలాపాలు చేయండి; అది తెరుచుకోవచ్చు. ఏమిటి?',
  L10nKeys.mysteryUnlocked: 'మీ ప్రత్యేక జ్ఞాపకం ఇక్కడ ఉంది!',
  L10nKeys.mysteryUnlockedBody: 'ఈ జ్ఞాపకం మీ కోసం మాత్రమే. సమయం తీసుకోండి. 🌸',
  L10nKeys.mysteryCuriosity: 'నేడు ఏమి తెరుచుకుంటుంది?',
  L10nKeys.mysteryOpen: 'జ్ఞాపకం తెరవండి',

  L10nKeys.memoriesTitle: 'నా జ్ఞాపకాలు',
  L10nKeys.memoriesEmpty: 'ఇంకా జ్ఞాపకాలు లేవు',
  L10nKeys.memoriesEmptyBody: 'మీ కుటుంబం ఫోటోలు, గొంతు సందేశాలు జోడించవచ్చు. వచ్చిన వెంటనే ఇక్కడ కనిపిస్తాయి.',
  L10nKeys.memoriesFamily: 'కుటుంబం',
  L10nKeys.memoriesPlaces: 'ప్రదేశాలు',
  L10nKeys.memoriesFestivals: 'పండుగలు',
  L10nKeys.memoriesChildhood: 'బాల్యం',
  L10nKeys.memoriesKindPhoto: 'ఫోటో',
  L10nKeys.memoriesKindVoice: 'గొంతు సందేశం',
  L10nKeys.memoriesKindText: 'కథ',
  L10nKeys.memoriesKindSound: 'ధ్వని',
  L10nKeys.memoriesKindPlace: 'ప్రదేశం',
  L10nKeys.memoriesAddedBy: 'జోడించినది',
  L10nKeys.memoriesWhoIsThis: 'వీరెవరు?',
  L10nKeys.memoriesPlayVoice: 'వినండి',
  L10nKeys.memoriesThisIsMe: 'ఇదే నేను',
  L10nKeys.memoriesNotMe: 'నేను కాదు',

  L10nKeys.profileTitle: 'ప్రొఫైల్',
  L10nKeys.profileLanguage: 'యాప్ భాష',
  L10nKeys.profileRegion: 'నా ప్రాంతం',
  L10nKeys.profileVoiceLanguage: 'గొంతు భాష',
  L10nKeys.profileVoicePrompts: 'మాట్లాడే సూచనలు',
  L10nKeys.profileTextSize: 'అక్షర పరిమాణం',
  L10nKeys.profileReducedMotion: 'ప్రశాంత చలనం',
  L10nKeys.profileSoundEffects: 'ధ్వని ప్రభావాలు',
  L10nKeys.profileFamily: 'కుటుంబం',
  L10nKeys.profileContacts: 'అత్యవసర సంప్రదింపులు',
  L10nKeys.profileDemoMode: 'డెమో మోడ్',
  L10nKeys.profileReminders: 'రిమైండర్లు',
  L10nKeys.profileNeedHelp: 'సహాయం కావాలా?',

  L10nKeys.remindersTitle: 'రిమైండర్లు',
  L10nKeys.remindersEmpty: 'ఇంకా రిమైండర్లు లేవు',
  L10nKeys.remindersNew: 'కొత్త రిమైండర్',
  L10nKeys.remindersTitleLabel: 'శీర్షిక',
  L10nKeys.remindersDetailLabel: 'వివరాలు (ఐచ్ఛికం)',
  L10nKeys.remindersTime: 'సమయం',
  L10nKeys.remindersDays: 'రోజులు',
  L10nKeys.remindersEveryday: 'ప్రతిరోజు',
  L10nKeys.remindersEnabled: 'యాక్టివ్',
  L10nKeys.remindersMedicine: 'మందు',
  L10nKeys.remindersAppointment: 'అపాయింట్మెంట్',
  L10nKeys.remindersRoutine: 'రోజువారీ దినచర్య',

  L10nKeys.dayMon: 'సోమ',
  L10nKeys.dayTue: 'మంగళ',
  L10nKeys.dayWed: 'బుధ',
  L10nKeys.dayThu: 'గురు',
  L10nKeys.dayFri: 'శుక్ర',
  L10nKeys.daySat: 'శని',
  L10nKeys.daySun: 'ఆది',

  L10nKeys.sosTitle: 'అత్యవసర సహాయం',
  L10nKeys.sosExplain: 'నొక్కి పట్టుకోండి. మైండ్కేర్ మీ అత్యవసర సంప్రదింపులకు ఒక్కొక్కరుగా తెలియజేస్తుంది. ఇది అత్యవసర సేవ (112 లాంటిది) కాదు.',
  L10nKeys.sosHold: 'సహాయం కోసం నొక్కి పట్టుకోండి',
  L10nKeys.sosHoldBody: 'నొక్కి పట్టుకోండి…',
  L10nKeys.sosActiveTitle: 'సహాయాన్ని సంప్రదిస్తున్నాం',
  L10nKeys.sosActiveBody: 'మీ కుటుంబానికి తెలియజేశాం. వారు స్పందించకపోతే తర్వాతి సంప్రదింపును పిలుస్తాం.',
  L10nKeys.sosContacting: 'సంప్రదిస్తున్నాం',
  L10nKeys.sosContactFamily: 'కుటుంబాన్ని సంప్రదించండి',
  L10nKeys.sosContacted: 'సంప్రదించాం',
  L10nKeys.sosWaitingResponse: 'స్పందన కోసం వేచి…',
  L10nKeys.sosEscalating: 'తర్వాతి వ్యక్తిని సంప్రదిస్తున్నాం…',
  L10nKeys.sosCancelled: 'సహాయ విన్నపం రద్దు',
  L10nKeys.sosCancelAction: 'సహాయ విన్నపాన్ని రద్దు చేయండి',
  L10nKeys.sosDone: 'పూర్తయింది',
  L10nKeys.sosHelpOnWay: 'త్వరలో ఎవరో మీతో ఉంటారు. 🧡',
  L10nKeys.sosNoContacts: 'ఇంకా అత్యవసర సంప్రదింపులు లేవు',
  L10nKeys.sosNoContactsBody:
      'అత్యవసర సంప్రదింపులు జోడించమని కుటుంబాన్ని అడగండి.',
  L10nKeys.sosAddContact: 'సంప్రదింపును జోడించండి',
  L10nKeys.sosDisclaimer: 'మైండ్కేర్ మీరు ఎంచుకున్న సంప్రదింపులకు తెలియజేస్తుంది. ఇది అధికారిక అత్యవసర సేవలకు ప్రత్యామ్నాయం కాదు.',
  L10nKeys.sosContactedPerson: 'కుటుంబ సభ్యుడిని సంప్రదించాం',
  L10nKeys.sosEscalatedTo: 'తర్వాతి కుటుంబ సభ్యుడిని సంప్రదించాం',
  L10nKeys.sosAcknowledged: 'కుటుంబ సభ్యుడు స్పందించారు. సహాయం వస్తోంది.',
  L10nKeys.sosNotSilent: 'సహాయం పంపలేకపోతే మేము ఎప్పుడూ నటించము.',
  L10nKeys.sosAlertNotDelivered:
      'మీ సందేశం ఇంకా పంపబడలేదు. ప్రయత్నిస్తూనే ఉంటాం.',

  L10nKeys.careTitle: 'సంరక్షకుడు',
  L10nKeys.careDashboard: 'అవలోకనం',
  L10nKeys.carePatients: 'నా రోగులు',
  L10nKeys.careMemories: 'జ్ఞాపకాలు',
  L10nKeys.careContacts: 'అత్యవసర సంప్రదింపులు',
  L10nKeys.careSettings: 'సెట్టింగులు',
  L10nKeys.careAddMemory: 'జ్ఞాపకం జోడించండి',
  L10nKeys.careAddContact: 'సంప్రదింపును జోడించండి',
  L10nKeys.careEngagement: 'నిమగ్నత',
  L10nKeys.careActivitiesWeek: 'ఈ వారం కార్యకలాపాలు',
  L10nKeys.careGardenProgress: 'తోట పురోగతి',
  L10nKeys.careRecentActivity: 'ఇటీవలి కార్యకలాపం',
  L10nKeys.careNoPatients: 'రోగులు ఎవరూ కలపబడలేదు',
  L10nKeys.careNoPatientsBody:
      'కుటుంబ సభ్యుడిని కలపమని అడగండి, లేదా రోగి ప్రొఫైల్ను జోడించండి.',
  L10nKeys.careAddPatient: 'రోగిని జోడించండి',
  L10nKeys.carePerformanceNote: 'ఇటీవల ఈ వ్యక్తి కార్యకలాప సామర్థ్యం వారి సాధారణ స్థాయి కంటే కొంచెం తక్కువగా ఉంది.',
  L10nKeys.careUploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి',
  L10nKeys.careRecordVoice: 'గొంతు రికార్డ్ చేయండి',
  L10nKeys.careWriteMemory: 'జ్ఞాపకం రాయండి',
  L10nKeys.careMemoryTitle: 'శీర్షిక',
  L10nKeys.careMemoryCaption: 'క్యాప్షన్',
  L10nKeys.careMemoryRelation: 'ఇందులో ఎవరున్నారు? (సంబంధం)',
  L10nKeys.careMemoryCategory: 'వర్గం',
  L10nKeys.careContactName: 'పేరు',
  L10nKeys.careContactPhone: 'ఫోన్ నంబర్',
  L10nKeys.careContactPriority: 'కాల్ క్రమం',
  L10nKeys.careContactRelation: 'సంబంధం',
  L10nKeys.careEscalationTimeout: 'తర్వాతి సంప్రదింపుకు ముందు నిమిషాలు',
  L10nKeys.careIncidentStatus: 'స్థితి',
  L10nKeys.careAckSos: 'నేను స్పందిస్తున్నాను',
  L10nKeys.careResponding: 'స్పందిస్తున్నారు',
  L10nKeys.careActiveAlerts: 'యాక్టివ్ హెచ్చరికలు',

  L10nKeys.syncSavingOffline: 'ఆఫ్‌లైన్',
  L10nKeys.syncSavingOfflineBody:
      'మీ కార్యకలాపాలు ఈ పరికరంలో సురక్షితంగా ఉన్నాయి.',
  L10nKeys.syncSynced: 'సమకాలీకరించబడింది',
  L10nKeys.syncInfo: 'మీ సమాచారం సమకాలీకరించబడింది.',
  L10nKeys.syncPending: 'సమకాలీకరణ కోసం వేచి',

  L10nKeys.errorGeneric: 'ఏదో తప్పు జరిగింది',
  L10nKeys.errorGenericBody: 'మీ పురోగతి సురక్షితం. మళ్ళీ ప్రయత్నించండి.',
  L10nKeys.errorAudio: 'ఈ పరికరంలో ధ్వని ప్లే కాలేదు.',
  L10nKeys.errorPermission: 'దీనికి పరికర అనుమతి అవసరం.',
  L10nKeys.errorNoInternetAction:
      'ఇంటర్నెట్ అవసరం లేదు — ఇది ముందుగా ఇక్కడే సేవ్ అవుతుంది.',

  L10nKeys.demoWelcome: 'డెమో చూడండి',
  L10nKeys.demoExplain: 'మీరు చూసేలా నమూనా కుటుంబం, జ్ఞాపకాలు జోడించబడతాయి.',
  L10nKeys.demoLoad: 'డెమో తోటను లోడ్ చేయండి',

  L10nKeys.unitsPoints: 'పాయింట్లు',
  L10nKeys.teaserChai: 'చాయ్ చేద్దాం.',
  L10nKeys.familiarityName: 'ఆశా',
  L10nKeys.regionMap: 'నా ప్రాంతం',
  L10nKeys.regionChoose: 'మీ ప్రాంతాన్ని ఎంచుకోండి',
  L10nKeys.regionIndia: 'భారతదేశం',
  L10nKeys.importantMemory: 'ముఖ్యమైన జ్ఞాపకం',
  L10nKeys.growing: 'పెరుగుతోంది',
  L10nKeys.blooming: 'వికసిస్తోంది',
  L10nKeys.mature: 'పరిణతి',
  L10nKeys.noVoice: 'ఈ పరికరంలో గొంతు అందుబాటులో లేదు.',
  L10nKeys.optional: 'ఐచ్ఛికం',

  L10nKeys.langChoose: 'భాషను ఎంచుకోండి',
  L10nKeys.langPrimary: 'ప్రధాన',
  L10nKeys.langNorthEast: 'ఈశాన్య భారతదేశం',
  L10nKeys.langMajor: 'భారతదేశ ప్రధాన భాషలు',

  L10nKeys.authSignUpTitle: 'మీ ఖాతాను సృష్టించండి',
  L10nKeys.authSignUpBody: 'ఈ మైండ్కేర్ ప్రొఫైల్ మీ పరికరంలో సురక్షితంగా ఉంటుంది. మీరే తెరవగలరనేందుకు వినియోగదారు పేరు, పాస్‌వర్డ్ పెట్టండి.',
  L10nKeys.authLoginTitle: 'తిరిగి స్వాగతం',
  L10nKeys.authLoginBody:
      'మీ తోటను తెరవడానికి వినియోగదారు పేరు, పాస్‌వర్డ్తో సైన్ ఇన్ చేయండి.',
  L10nKeys.authUsername: 'వినియోగదారు పేరు',
  L10nKeys.authUsernameHint: 'ఉదా: ranu123',
  L10nKeys.authDisplayName: 'మీ పేరు',
  L10nKeys.authPassword: 'పాస్‌వర్డ్',
  L10nKeys.authPasswordHint: 'కనీసం 6 అక్షరాలు',
  L10nKeys.authConfirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి',
  L10nKeys.authRoleQuestion: 'ఈ ప్రొఫైల్ ఎవరి కోసం…',
  L10nKeys.authRolePatient: 'నా కోసం',
  L10nKeys.authRoleCaregiver: 'కుటుంబ సభ్యుడి కోసం',
  L10nKeys.authCreate: 'ఖాతా సృష్టించండి',
  L10nKeys.authSignIn: 'సైన్ ఇన్',
  L10nKeys.authSignOut: 'సైన్ అవుట్',
  L10nKeys.authAccount: 'ఖాతా',
  L10nKeys.caregiverTitle: 'సంరక్షకుడు',
  L10nKeys.caregiverNotLinked: 'ఇంకా ఎటువంటి సంరక్షకుడు లింక్ కాలేదు',
  L10nKeys.authBadCredentials: 'వినియోగదారు పేరు లేదా పాస్‌వర్డ్ తప్పు.',
  L10nKeys.authUsernameTaken: 'ఈ పరికరంలో ఈ పేరు ఇప్పటికే వాడుకలో ఉంది.',
  L10nKeys.authPasswordMismatch: 'పాస్‌వర్డ్లు సరిపోలడం లేదు.',
  L10nKeys.authUsernameShort: 'పేరు కనీసం 3 అక్షరాలు ఉండాలి.',
  L10nKeys.authUsernameInvalid:
      'అక్షరాలు, అంకెలు, డాట్, డాష్ లేదా అండర్‌స్కోర్ మాత్రమే వాడండి.',
  L10nKeys.authPasswordShort: 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.',
  L10nKeys.authNameRequired: 'దయచేసి పేరు నమోదు చేయండి.',
  L10nKeys.authSignOutConfirm: 'ఈ ప్రొఫైల్ నుండి సైన్ అవుట్ చేయాలా?',
  L10nKeys.screenTitle: 'శీఘ్ర జ్ఞాపకశక్తి పరీక్ష',
  L10nKeys.screenIntro: 'మేము రోగి గురించి కొన్ని చిన్న ప్రశ్నలు అడుగుతాము. గత కొన్ని నెలలుగా వారు ఎలా ఉన్నారో ఆలోచించండి.',
  L10nKeys.screenNotSure: 'ఖచ్చితంగా తెలియదు',
  L10nKeys.screenFinish: 'నా ఫలితం చూడండి',
  L10nKeys.screenSkip: 'ప్రస్తుతానికి వద్దు',
  L10nKeys.screenResultBack: 'పూర్తయింది',
  L10nKeys.screenCheckAgain: 'మళ్ళీ తనిఖీ చేయండి',
  L10nKeys.screenStartCheckup: 'పరీక్ష ప్రారంభించండి',
  L10nKeys.screenSkipped: 'పరీక్షను దాటవేశారు',
  L10nKeys.screenStatusGood: 'ప్రతిదీ బాగానే ఉంది',
  L10nKeys.screenStatusGoodBody: 'పెద్ద ఆందోళన ఏమీ కనిపించలేదు. రోజువారీ కార్యకలాపాలు చేస్తూ ఉండండి, మరియు ఏదైనా మారితే ఎప్పుడైనా మళ్ళీ తనిఖీ చేయవచ్చు.',
  L10nKeys.screenStatusWatch: 'కొన్ని మార్పులు గమనించాం',
  L10nKeys.screenStatusWatchBody: 'మరచిపోయే కొన్ని క్షణాలు గమనించాం. ఇది వయస్సుతో సాధారణం, కానీ గమనించండి మరియు తదుపరి డాక్టర్ సందర్శనలో చెప్పండి.',
  L10nKeys.screenStatusDoctor: 'దయచేసి పరీక్ష చేయించుకోండి',
  L10nKeys.screenStatusDoctorBody: 'శ్రద్ధ అవసరమయ్యే కొన్ని సంకేతాలు గమనించాం. వారు సహాయం చేయగలిగేలా వీటిని డాక్టర్ లేదా క్లినిక్కు తెలియజేయండి.',
  L10nKeys.screenRarely: 'అరుదుగా',
  L10nKeys.screenSometimes: 'కొన్నిసార్లు',
  L10nKeys.screenFrequently: 'తరచుగా',
  L10nKeys.screenVeryFrequently: 'చాలా తరచుగా',
  L10nKeys.screenQ01: 'ఇటీవలి సంఘటనలను గుర్తుంచుకోవడంలో వారికి ఇబ్బంది ఉందా?',
  L10nKeys.screenQ02: 'వారు అదే ప్రశ్నలు లేదా కథలను పునరావృతం చేస్తారా?',
  L10nKeys.screenQ03: 'వారు తెలిసిన వ్యక్తుల పేర్లను మరచిపోతారా?',
  L10nKeys.screenQ04: 'తెలిసిన ముఖాలను గుర్తించడంలో వారికి ఇబ్బంది ఉందా?',
  L10nKeys.screenQ05: 'వారు నియామకాలు లేదా ముఖ్యమైన సంఘటనలను మరచిపోతారా?',
  L10nKeys.screenQ06: 'సరైన పదాలు కనుగొనడంలో వారికి ఇబ్బంది ఉందా?',
  L10nKeys.screenQ07: 'వారు ఎక్కడ ఉన్నారో గందరగోళం చెందుతారా?',
  L10nKeys.screenQ08: 'రోజువారీ కార్యకలాపాలకు వారికి గుర్తు చేయడం అవసరమా?',
  L10nKeys.screenQ09: 'మందులు నిర్వహించడంలో వారికి ఇబ్బంది ఉందా?',
  L10nKeys.screenQ10: 'గందరగోళం చెందినప్పుడు వారు ఆందోళన లేదా చిరాకుగా ఉంటారా?',
  L10nKeys.screenQ11: 'సంభాషణలను అనుసరించడంలో వారికి ఇబ్బంది ఉందా?',
  L10nKeys.screenQ12: 'తెలిసిన పనులను పూర్తి చేయడంలో వారికి ఇబ్బంది ఉందా?',
  L10nKeys.screenQ13: 'రోజువారీ వస్తువులు ఎక్కడ ఉన్నాయో వారు మరచిపోతారా?',
  L10nKeys.screenQ14: 'సూచనలను గుర్తుంచుకోవడంలో వారికి ఇబ్బంది ఉందా?',
  L10nKeys.screenQ15: 'బహుళ-దశల కార్యకలాపాలు చేయడంలో వారికి ఇబ్బంది ఉందా?',

  L10nKeys.careDashboardSubtitle: 'కుటుంబ సంరక్షణ',
  L10nKeys.careSosLive: 'ప్రత్యక్ష హెచ్చరిక',
  L10nKeys.careSosRespondedBy: '{name} స్పందించారు',
  L10nKeys.careLinkTitle: 'కుటుంబ సభ్యునితో కనెక్ట్ చేయండి',
  L10nKeys.careLinkBody: 'మీ ప్రియమైన వ్యక్తి ఫోన్లో కనిపించే 6-అక్షరాల కుటుంబ కోడ్ను అడగండి, ఆపై కనెక్ట్ చేయండి.',
  L10nKeys.careLinkCode: 'కుటుంబ కోడ్',
  L10nKeys.careLinkCodeHint: 'ఉదా. A1B2C3',
  L10nKeys.careLinkConnect: 'కనెక్ట్',
  L10nKeys.careLinkDone: 'కనెక్ట్ అయ్యింది',
  L10nKeys.careLinkSuccess: '{name}తో కనెక్ట్ అయ్యింది! జ్ఞాపకాలు మరియు హెచ్చరికలు ఇప్పుడు సమకాలీకరించబడతాయి.',
  L10nKeys.careLinkFailed:
      'కనెక్ట్ చేయలేకపోయాము. దయచేసి కోడ్ను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
  L10nKeys.careTrendsTitle: 'AI ధోరణులు',
  L10nKeys.careTrendsBody: 'కార్యాచరణ రకం ప్రకారం రోజువారీ ఖచ్చితత్వం',
  L10nKeys.careTrendsNoData:
      'ఇంకా కార్యాచరణ లేదు — ధోరణులను చూడటానికి ఒక వ్యాయామాన్ని పూర్తి చేయండి.',
  L10nKeys.careAiDifficulty: 'స్వయంచాలకంగా సర్దుబాటు చేసిన కష్టం',
  L10nKeys.careAiAccuracy: 'మోడల్ ఖచ్చితత్వం',
  L10nKeys.careAiRealSessions: 'వాస్తవ సెషన్లు',
  L10nKeys.careAiDemoSessions: 'డెమో సెషన్లు',
  L10nKeys.careNavGames: 'గేమ్లు',
  L10nKeys.careNavRoutine: 'దినచర్య',
  L10nKeys.careGreetSubtitle: 'ఈరోజు {name} ఎలా ఉన్నారో ఇక్కడ ఉంది.',
  L10nKeys.careNotifEmpty: 'కొత్త నోటిఫికేషన్లు లేవు',
  L10nKeys.careWellnessScore: 'అభిజ్ఞా సంక్షేమ స్కోర్',
  L10nKeys.careStatusStable: 'స్థిరం',
  L10nKeys.careStatusAttention: 'శ్రద్ధ అవసరం',
  L10nKeys.careLastSynced: 'చివరిగా సమకాలీకరించినది {time}',
  L10nKeys.careMinAgo: '{n} నిమిషాల క్రితం',
  L10nKeys.careGamesWeek: 'ఈ వారం గేమ్లు',
  L10nKeys.careRoutineCompletion: 'దినచర్య పూర్తి',
  L10nKeys.careCurrentStreak: 'ప్రస్తుత స్ట్రీక్',
  L10nKeys.careMoodCheckins: 'మూడ్ చెక్-ఇన్లు',
  L10nKeys.careDayUnit: 'రోజు',
  L10nKeys.careDaysUnit: 'రోజులు',
  L10nKeys.careActivityTitle: 'వారంవారీ కార్యాచరణ',
  L10nKeys.careWeekly: 'వారంవారీ',
  L10nKeys.careMonthly: 'నెలవారీ',
  L10nKeys.careNoActivityWeek: 'ఈ వారం ఇంకా కార్యాచరణ నమోదు కాలేదు.',
  L10nKeys.careMoodTitle: 'మూడ్',
  L10nKeys.careMoodHappy: 'సంతోషం',
  L10nKeys.careMoodCalm: 'ప్రశాంతం',
  L10nKeys.careMoodNeutral: 'తటస్థం',
  L10nKeys.careMoodLow: 'తక్కువ',
  L10nKeys.careMood7Days: 'గత 7 రోజులు',
  L10nKeys.careMoodInsight: '{name} ఈ వారం ఎక్కువగా ప్రశాంతంగా ఉన్నారు, గత రెండు రోజుల్లో కొంచెం తగ్గుదల కనిపించింది.',
  L10nKeys.careMoodNoData: 'ఈ వారం ఇంకా మూడ్ చెక్-ఇన్లు లేవు.',
  L10nKeys.careSkillsTitle: 'అభిజ్ఞా నైపుణ్యాలు',
  L10nKeys.careSkillMemory: 'జ్ఞాపకశక్తి',
  L10nKeys.careSkillAttention: 'శ్రద్ధ',
  L10nKeys.careSkillLanguage: 'భాష',
  L10nKeys.careSkillReasoning: 'తార్కికం',
  L10nKeys.careSkillProcessing: 'ప్రాసెసింగ్ వేగం',
  L10nKeys.careInsightToday: 'ఈరోజు అంతర్దృష్టి',
  L10nKeys.careInsightBody: 'రాబర్ట్ తన ఉదయం దినచర్య తర్వాత జ్ఞాపకశక్తి కార్యకలాపాలలో స్థిరంగా ఉన్నారు. గత రెండు రోజులుగా ఆయన మూడ్ కొద్దిగా తక్కువగా ఉంది.',
  L10nKeys.careInsightBodyReal: 'ఈ వారం {name} {count} అభిజ్ఞా సెషన్లను (లక్ష్యం {goal}) పూర్తి చేశారు మరియు {streak}-రోజుల స్ట్రీక్ను కొనసాగిస్తున్నారు.',
  L10nKeys.careViewDetails: 'వివరాలను చూడండి',
  L10nKeys.careInsightDisclaimer:
      'ఇది డేటా నుండి తీసుకున్న సున్నితమైన పరిశీలన — ఇది వైద్య నిర్ధారణ కాదు.',
  L10nKeys.careAttentionTitle: 'మీ శ్రద్ధ అవసరం',
  L10nKeys.careAttentionEmpty: 'ప్రస్తుతం మీ శ్రద్ధ అవసరమైనది ఏమీ లేదు.',
  L10nKeys.careAlertSos: '{name} SOS బటన్ నొక్కారు',
  L10nKeys.careAlertRoutineMissed: 'నిన్న దినచర్య తప్పిపోయింది',
  L10nKeys.careAlertMoodDown: 'గత రెండు రోజుల్లో మూడ్ తగ్గింది',
  L10nKeys.careAlertSessionPending: 'ఈరోజు అభిజ్ఞా సెషన్ పూర్తి కాలేదు',
  L10nKeys.careAlertSeverityHigh: 'అధికం',
  L10nKeys.careAlertSeverityMedium: 'మధ్యస్థం',
  L10nKeys.careAlertSeverityLow: 'తక్కువ',
  L10nKeys.careWeeklySummary: 'వారంవారీ సారాంశం',
  L10nKeys.careSessionsCompleted: 'పూర్తి చేసిన సెషన్లు',
  L10nKeys.careAvgSessionDuration: 'సగటు సెషన్ వ్యవధి',
  L10nKeys.careRoutineAdherence: 'దినచర్య పాటించడం',
  L10nKeys.careMoodTrend: 'మూడ్ ధోరణి',
  L10nKeys.careMoodTrendSlightlyDown: 'కొద్దిగా తక్కువ',
  L10nKeys.careMoodTrendStable: 'స్థిరం',
  L10nKeys.careMoodTrendUp: 'మెరుగవుతోంది',
  L10nKeys.careVsLastWeek: 'గత వారంతో పోలిస్తే',
  L10nKeys.careSyncedJustNow: 'ఇప్పుడే సమకాలీకరించబడింది',
  L10nKeys.careOfflineWaiting:
      'ఆఫ్లైన్ · సమకాలీకరించడానికి వేచి ఉన్న {count} కార్యకలాపాలు',
  L10nKeys.careComingSoon: 'త్వరలో వస్తుంది',
  L10nKeys.careHomeSoon: '{name} రోజు యొక్క శీఘ్ర అవలోకనం ఇక్కడ కనిపిస్తుంది.',
  L10nKeys.careGamesSoon: 'గేమ్లు మరియు సెషన్ చరిత్ర ఇక్కడ కనిపిస్తుంది.',
  L10nKeys.careRoutineSoon: 'రోగి యొక్క రోజువారీ దినచర్య ఇక్కడ కనిపిస్తుంది.',
  L10nKeys.careProfileSoon:
      'సంరక్షకుడి ప్రొఫైల్ మరియు సెట్టింగ్లు ఇక్కడ కనిపిస్తాయి.',
  L10nKeys.serverPairingTitle: 'కుటుంబ కోడ్',
  L10nKeys.serverPairingBody:
      'ఈ కోడ్ను ఒక సంరక్షకునితో పంచుకోండి, తద్వారా వారు మీతో కనెక్ట్ అవుతారు.',
  L10nKeys.serverUnlinked: 'సర్వర్కు కనెక్ట్ కాలేదు',
  L10nKeys.serverLinked: 'సర్వర్కు కనెక్ట్ అయ్యింది',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
