import '../l10n_keys.dart';

/// Urdu dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsUr = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'آپ کی یادوں کا ساتھی',
  L10nKeys.back: 'پیچھے',
  L10nKeys.next: 'آگے',
  L10nKeys.continueText: 'جاری رکھیں',
  L10nKeys.skip: 'چھوڑیں',
  L10nKeys.done: 'ہو گیا',
  L10nKeys.cancel: 'منسوخ',
  L10nKeys.yes: 'ہاں',
  L10nKeys.no: 'نہیں',
  L10nKeys.save: 'محفوظ کریں',
  L10nKeys.close: 'بند کریں',
  L10nKeys.retry: 'دوبارہ کوشش کریں',
  L10nKeys.add: 'شامل کریں',
  L10nKeys.edit: 'ترمیم کریں',
  L10nKeys.remove: 'ہٹائیں',
  L10nKeys.search: 'تلاش',
  L10nKeys.today: 'آج',
  L10nKeys.offline: 'آف لائن',
  L10nKeys.online: 'آن لائن',

  L10nKeys.goodMorning: 'صبح بخیر',
  L10nKeys.goodAfternoon: 'نمستے',
  L10nKeys.goodEvening: 'شام بخیر',
  L10nKeys.goodNight: 'شب بخیر',

  L10nKeys.navHome: 'گھر',
  L10nKeys.navGarden: 'باغ',
  L10nKeys.navActivities: 'سرگرمیاں',
  L10nKeys.navMemories: 'یادیں',
  L10nKeys.navProfile: 'پروفائل',
  L10nKeys.navMystery: 'آج کی یاد',

  L10nKeys.onboardingWelcomeTitle: 'آپ کی یادوں کا ایک نرم ساتھی',
  L10nKeys.onboardingWelcomeBody: 'مائند کیئر این ای آر بغیر انٹرنیٹ کے بھی یاد رکھنے، کھیلنے اور خاندان سے جڑے رہنے میں مدد کرتا ہے۔',
  L10nKeys.onboardingNameTitle: 'ہم آپ کو کیا کہہ کر پکاریں؟',
  L10nKeys.onboardingNameHint: 'آپ کا نام',
  L10nKeys.onboardingRegionTitle: 'آپ کا گھر کہاں ہے؟',
  L10nKeys.onboardingRegionHint: 'شہر یا گاؤں',
  L10nKeys.onboardingRegionList: 'گواہاٹی، سلچر، شیلونگ، اگرتلا، امفال، آئیزول، اٹاناگر، کوہیما، گینگٹاک، ڈیبروگڑھ، جورہاٹ، آپ کا شہر',
  L10nKeys.onboardingLanguageTitle: 'آپ کو کون سی زبان پسند آئے گی؟',
  L10nKeys.onboardingLanguageBody: 'آپ اسے کسی بھی وقت تبدیل کر سکتے ہیں۔',
  L10nKeys.onboardingFamilyTitle: 'خاندان کون؟',
  L10nKeys.onboardingFamilyBody: 'اپنے پیاروں کو شامل کریں۔ ہم ان کی تصاویر اور آواز کو نرم یادوں کے طور پر دکھائیں گے۔',
  L10nKeys.onboardingAddFamily: 'خاندان کا فرد شامل کریں',
  L10nKeys.onboardingEmergencyTitle: 'ہنگامی صورت میں ہم کسے بلائیں؟',
  L10nKeys.onboardingEmergencyBody: 'SOS بٹن دبانے سے مائند کیئر آپ کے خاندان کو اطلاع دیتا ہے، ہنگامی خدمات کو نہیں۔',
  L10nKeys.onboardingEmergencyName: 'نام',
  L10nKeys.onboardingEmergencyPhone: 'فون نمبر',
  L10nKeys.onboardingEmergencyRelation: 'رشتہ (بیٹی، بیٹا…)',
  L10nKeys.onboardingDoneTitle: 'آپ کا باغ تیار ہے!',
  L10nKeys.onboardingDoneBody:
      'چھوٹی سرگرمیاں مکمل کریں اور اپنا باغ بڑھتا دیکھیں۔ ہم آپ کے ساتھ ہیں۔',
  L10nKeys.onboardingStart: 'میرا باغ شروع کریں',

  L10nKeys.homeWhatsGrowing: 'آج کیا بڑھ رہا ہے؟',
  L10nKeys.homeTodayActivity: 'آج کی چھوٹی سرگرمی',
  L10nKeys.homeActivityDuration: 'تقریباً ۳ منٹ',
  L10nKeys.homeMinutes: 'منٹ',
  L10nKeys.homeMemoryOfDay: 'آج کی یاد',
  L10nKeys.homeMemoryLocked: 'ایک خاص یاد آپ کا انتظار کر رہی ہے…',
  L10nKeys.homeMemoryUnlocked: 'ایک یاد کھل گئی!',
  L10nKeys.homeContinueActivity: 'سرگرمی جاری رکھیں',
  L10nKeys.homeFamilyMemory: 'آپ کے خاندان کی طرف سے',
  L10nKeys.homeFamilyMemoryEmpty: 'خاندان کی یادیں یہاں دکھ سکتی ہیں۔',
  L10nKeys.homeSos: 'مدد درکار ہے',
  L10nKeys.homeSosSubtitle: 'ہنگامی صورت میں خاندان سے رابطہ',
  L10nKeys.homeGardenPreview: 'آپ کا باغ',
  L10nKeys.homeEngine: 'مائند کیئر ساتھی',
  L10nKeys.homeEngineReady: 'آپ کا معاون تیار ہے۔',
  L10nKeys.homeWelcomeBack: 'واپسی خوش آئند! باغ آگے بڑھائیں۔ 🌸',
  L10nKeys.homeNoActivity: 'آج کوئی سرگرمی نہیں',
  L10nKeys.homeNoActivityBody: 'تھوڑا آرام کریں — یا پسندیدہ سرگرمی چنیں۔ 🌻',

  L10nKeys.gardenTitle: 'میرا یادوں کا باغ',
  L10nKeys.gardenSectionAll: 'سب',
  L10nKeys.gardenSectionFamily: 'خاندان',
  L10nKeys.gardenSectionChildhood: 'بچپن',
  L10nKeys.gardenSectionPlaces: 'مقامات',
  L10nKeys.gardenSectionFestivals: 'تہوار',
  L10nKeys.gardenEmpty: 'آپ کا باغ ابھی شروع ہوا ہے',
  L10nKeys.gardenEmptyBody: 'پہلی سرگرمی مکمل کریں، یہاں ایک بیج بویا جائے گا۔',
  L10nKeys.gardenPoints: 'نکات',
  L10nKeys.gardenLevel: 'سطح',
  L10nKeys.gardenSeed: 'بیج',
  L10nKeys.gardenPlant: 'پودا',
  L10nKeys.gardenFlower: 'پھول',
  L10nKeys.gardenTree: 'درخت',
  L10nKeys.gardenMilestone: 'مرحلہ',
  L10nKeys.gardenGrowth: 'بڑھ رہا ہے',
  L10nKeys.gardenDidYouKnow: 'ہر مکمل ہونے والی سرگرمی آپ کے باغ کو بڑھاتی ہے۔',
  L10nKeys.gardenPlantSeed: 'بیج بوئیں',

  L10nKeys.activitiesTitle: 'سرگرمیاں',
  L10nKeys.activitiesToday: 'آج',
  L10nKeys.activitiesLibrary: 'مزید سرگرمیاں',
  L10nKeys.mainGamesTitle: 'مرکزی کھیل',
  L10nKeys.activityPairs: 'جوڑی تلاش کریں',
  L10nKeys.activitySequenceRecall: 'ترتیب یاد رکھیں',
  L10nKeys.activityFindChanged: 'کیا بدل گیا؟',
  L10nKeys.pairsFruits: 'بازار کے پھل',
  L10nKeys.pairsKitchen: 'گھر کے سامان',
  L10nKeys.pairsRemember: 'تمام کارڈز کو غور سے دیکھیں، پھر جوڑی تلاش کریں۔',
  L10nKeys.pairsStart: 'یاد کر لیا',
  L10nKeys.pairsFound: 'بہت خوب! جوڑی مل گئی!',
  L10nKeys.seqRecallItems: 'گھر کی چیزیں',
  L10nKeys.seqRecallNumbers: 'نمبر یاد رکھیں',
  L10nKeys.seqRecallWatch: 'لائٹس کی ترتیب دھیان سے دیکھیں۔',
  L10nKeys.seqRecallRepeat: 'اب اسی ترتیب میں چنیں۔',
  L10nKeys.changeMarket: 'بازار کی ٹوکری',
  L10nKeys.changeFestival: 'تہوار کا سامان',
  L10nKeys.changeRemember: 'فوٹو کو غور سے دیکھیں؛ ایک چیز بدل جائے گی۔',
  L10nKeys.changeFind: 'کون سی چیز بدل گئی؟',
  L10nKeys.changeCorrect: 'صحیح! آپ نے تبدیلی ڈھونڈ لی!',
  L10nKeys.activitiesStart: 'شروع کریں',
  L10nKeys.activitiesCompleted: 'مکمل',
  L10nKeys.activitiesInProgress: 'جاری',
  L10nKeys.activitiesNotStarted: 'تیار',
  L10nKeys.activityYoureDone: 'بہت اچھے!',
  L10nKeys.activityPraise: 'آپ نے باغ کو تھوڑی زندگانی دی۔ 🌱',
  L10nKeys.activityHint: 'اشارہ چاہیے؟',
  L10nKeys.activityTryAgain: 'چلیے اس یاد کو پھر دیکھیں',
  L10nKeys.activityOptionsHint: 'اپنا جواب منتخب کریں',
  L10nKeys.activityTapToMatch: 'مطابق جوڑی منتخب کریں',
  L10nKeys.activityNext: 'آگے',
  L10nKeys.activityFinish: 'مکمل',
  L10nKeys.activityGroupLetsAgain: 'چلیے اسے پھر دیکھیں',
  L10nKeys.activityGroupTogether: 'چلیے یہ مل کر کریں',
  L10nKeys.activityGreatJob: 'شاباش!',
  L10nKeys.activityKitchen: 'میرا باورچی خانہ',
  L10nKeys.activityShopping: 'میری دکان',
  L10nKeys.activityMatching: 'جوڑی بنائیں',
  L10nKeys.activitySequence: 'ترتیب سے لگائیں',
  L10nKeys.activityRecognition: 'یہ کیا ہے؟',
  L10nKeys.activityAssociation: 'کون سا اکٹھا چلتا ہے؟',
  L10nKeys.activityRecall: 'یاد ہے؟',
  L10nKeys.activityAttention: 'ڈھونڈیں',
  L10nKeys.activityDurationSuffix: 'منٹ',
  L10nKeys.activityTodayDone: 'آج کی سرگرمی مکمل',
  L10nKeys.activityTodayDoneBody: 'آپ کا باغ بڑھا۔ کل ایک یاد انتظار کرے گی۔',
  L10nKeys.activityGardenGrew: 'آپ کا باغ بڑھا!',
  L10nKeys.activityMemoryUnlocked: 'ایک یاد کھل گئی',
  L10nKeys.activityReadAloud: 'بلند آواز سے پڑھیں',

  L10nKeys.kitchenTitle: 'چائے بنائیں',
  L10nKeys.kitchenMakeChai: 'چائے بنانا',
  L10nKeys.kitchenMakeChaiPrompt: 'مراحل صحیح ترتیب سے منتخب کریں۔',
  L10nKeys.kitchenSteps: 'مراحل',
  L10nKeys.kitchenTapInOrder: 'مراحل صحیح ترتیب سے منتخب کریں',
  L10nKeys.kitchenCorrectOrder: 'بہترین! چائے تیار!',
  L10nKeys.kitchenBreakfast: 'ناشتہ بنانا',
  L10nKeys.kitchenBreakfastHint: 'دن کی تازہ شروعات',
  L10nKeys.kitchenBreakfastPrompt: 'ناشتے کے مراحل ترتیب میں لگائیں۔',

  L10nKeys.shopTitle: 'میری دکان',
  L10nKeys.shopGetMilkBread: 'بریڈ اور دودھ',
  L10nKeys.shopGetMilkBreadPrompt: '₹۱۰۰ میں دودھ اور بریڈ خریدیں۔',
  L10nKeys.shopBudget: 'بجٹ',
  L10nKeys.shopBasket: 'آپ کی ٹوکری',
  L10nKeys.shopTotal: 'کل',
  L10nKeys.shopWithinBudget: 'بجٹ کے اندر!',
  L10nKeys.shopOverBudget: 'بجٹ سے باہر — دوبارہ دیکھیں',
  L10nKeys.shopCheckout: 'مکمل کریں اور ادائیگی کریں',
  L10nKeys.shopBuy: 'ٹوکری میں ڈالیں',
  L10nKeys.shopSell: 'نکالیں',
  L10nKeys.shopVeggies: 'رات کے کھانے کے لیے سبزیاں',
  L10nKeys.shopVeggiesPrompt: '₹۶۰ میں آلو اور پیاز خریدیں۔',
  L10nKeys.recKitchenItem: 'یہ کون سا ہے؟',
  L10nKeys.recKitchenItemPrompt:
      'بازار سے سامان لانے کے لیے ان میں سے کون سا استعمال ہوتا ہے؟',
  L10nKeys.recCurrency: 'تھوڑی رقم',
  L10nKeys.recCurrencyPrompt: 'کون سا نوٹ ₹۲۰ ہے؟',
  L10nKeys.matchFestival: 'تہوار ملائیں',
  L10nKeys.matchFestivalPrompt: 'ہر تہوار کو اس کی خاص ڈش سے ملائیں۔',
  L10nKeys.matchObjectUse: 'جوڑی بنائیں',
  L10nKeys.matchObjectUsePrompt: 'ہر چیز کو استعمال کے وقت سے ملائیں۔',
  L10nKeys.seqMorning: 'صبح کا معمول',
  L10nKeys.seqMorningPrompt: 'اپنے صبح کا معمول ترتیب میں لگائیں۔',
  L10nKeys.seqRoute: 'صبح کا سفر',
  L10nKeys.seqRoutePrompt: 'بازار تک کا سفر ترتیب میں لگائیں۔',
  L10nKeys.assoRegion: 'یہاں کیا ہے؟',
  L10nKeys.assoRegionPrompt: 'آسام کس لیے مشہور ہے؟',
  L10nKeys.assoHarvest: 'میٹھا پھل',
  L10nKeys.assoHarvestPrompt: 'کس پھل کو گرمیوں کا بادشاہ کہتے ہیں؟',
  L10nKeys.attnVeg: 'گاجر ڈھونڈیں',
  L10nKeys.attnVegPrompt: 'کیا آپ گاجر ڈھونڈ سکتے ہیں؟',
  L10nKeys.recallSong: 'ایک مانوس گانا',
  L10nKeys.recallSongPrompt: 'بیہو میں ناچتے وقت کون سا گانا بجتا ہے؟',

  L10nKeys.mysteryTitle: 'آج کی خاص یاد',
  L10nKeys.mysteryLocked: 'ایک خاص یاد آپ کا انتظار کر رہی ہے…',
  L10nKeys.mysteryLockedBody:
      'آج ۲–۳ چھوٹی سرگرمیاں کریں؛ شاید وہ کھل جائے۔ کیا ہوگی؟',
  L10nKeys.mysteryUnlocked: 'آپ کی خاص یاد یہاں ہے!',
  L10nKeys.mysteryUnlockedBody: 'یہ یاد صرف آپ کے لیے ہے۔ اپنا وقت لیں۔ 🌸',
  L10nKeys.mysteryCuriosity: 'آج کیا کھلے گا؟',
  L10nKeys.mysteryOpen: 'یاد کھولیں',

  L10nKeys.memoriesTitle: 'میری یادیں',
  L10nKeys.memoriesEmpty: 'ابھی کوئی یاد نہیں',
  L10nKeys.memoriesEmptyBody: 'آپ کا خاندان تصاویر اور آواز کے پیغامات شامل کر سکتا ہے۔ ملتے ہی یہاں نظر آئیں گے۔',
  L10nKeys.memoriesFamily: 'خاندان',
  L10nKeys.memoriesPlaces: 'مقامات',
  L10nKeys.memoriesFestivals: 'تہوار',
  L10nKeys.memoriesChildhood: 'بچپن',
  L10nKeys.memoriesKindPhoto: 'تصویر',
  L10nKeys.memoriesKindVoice: 'آواز کا پیغام',
  L10nKeys.memoriesKindText: 'کہانی',
  L10nKeys.memoriesKindSound: 'آواز',
  L10nKeys.memoriesKindPlace: 'مقام',
  L10nKeys.memoriesAddedBy: 'شامل کیا',
  L10nKeys.memoriesWhoIsThis: 'یہ کون ہیں؟',
  L10nKeys.memoriesPlayVoice: 'سنیں',
  L10nKeys.memoriesThisIsMe: 'یہ میں ہوں',
  L10nKeys.memoriesNotMe: 'میں نہیں',

  L10nKeys.profileTitle: 'پروفائل',
  L10nKeys.profileLanguage: 'ایپ کی زبان',
  L10nKeys.profileRegion: 'میرا علاقہ',
  L10nKeys.profileVoiceLanguage: 'آواز کی زبان',
  L10nKeys.profileVoicePrompts: 'بولے جانے والے اشارے',
  L10nKeys.profileTextSize: 'متن کا سائز',
  L10nKeys.profileReducedMotion: 'پرسکون حرکت',
  L10nKeys.profileSoundEffects: 'آواز کے اثرات',
  L10nKeys.profileFamily: 'خاندان',
  L10nKeys.profileContacts: 'ہنگامی رابطے',
  L10nKeys.profileDemoMode: 'ڈیمو موڈ',
  L10nKeys.profileReminders: 'یاد دہانیاں',
  L10nKeys.profileNeedHelp: 'مدد چاہیے؟',

  L10nKeys.remindersTitle: 'یاد دہانیاں',
  L10nKeys.remindersEmpty: 'ابھی کوئی یاد دہانی نہیں',
  L10nKeys.remindersNew: 'نئی یاد دہانی',
  L10nKeys.remindersTitleLabel: 'عنوان',
  L10nKeys.remindersDetailLabel: 'تفصیل (اختیاری)',
  L10nKeys.remindersTime: 'وقت',
  L10nKeys.remindersDays: 'دن',
  L10nKeys.remindersEveryday: 'روزانہ',
  L10nKeys.remindersEnabled: 'فعال',
  L10nKeys.remindersMedicine: 'دوا',
  L10nKeys.remindersAppointment: 'ملاقات',
  L10nKeys.remindersRoutine: 'روزمرہ معمول',

  L10nKeys.dayMon: 'سوم',
  L10nKeys.dayTue: 'منگل',
  L10nKeys.dayWed: 'بدھ',
  L10nKeys.dayThu: 'جمعرات',
  L10nKeys.dayFri: 'جمعہ',
  L10nKeys.daySat: 'ہفتہ',
  L10nKeys.daySun: 'اتوار',

  L10nKeys.sosTitle: 'ہنگامی مدد',
  L10nKeys.sosExplain: 'دبا کر رکھیں۔ مائند کیئر آپ کے ہنگامی رابطوں کو یکے بعد دیگرے اطلاع دے گا۔ یہ ہنگامی خدمت (جیسے ۱۱۲) نہیں ہے۔',
  L10nKeys.sosHold: 'مدد کے لیے دبا کر رکھیں',
  L10nKeys.sosHoldBody: 'دبا کر رکھیں…',
  L10nKeys.sosActiveTitle: 'مدد سے رابطہ کیا جا رہا ہے',
  L10nKeys.sosActiveBody: 'آپ کے خاندان کو اطلاع دی گئی۔ اگر وہ جواب نہ دیں تو اگلے رابطے کو بلایا جائے گا۔',
  L10nKeys.sosContacting: 'رابطہ کیا جا رہا ہے',
  L10nKeys.sosContactFamily: 'خاندان سے رابطہ',
  L10nKeys.sosContacted: 'رابطہ ہوا',
  L10nKeys.sosWaitingResponse: 'جواب کا انتظار…',
  L10nKeys.sosEscalating: 'اگلے شخص سے رابطہ…',
  L10nKeys.sosCancelled: 'مدد کی درخواست منسوخ',
  L10nKeys.sosCancelAction: 'مدد کی درخواست منسوخ کریں',
  L10nKeys.sosDone: 'ہو گیا',
  L10nKeys.sosHelpOnWay: 'جلد کوئی آپ کے ساتھ ہوگا۔ 🧡',
  L10nKeys.sosNoContacts: 'ابھی کوئی ہنگامی رابطہ نہیں',
  L10nKeys.sosNoContactsBody:
      'براہ کرم خاندان سے ہنگامی رابطے شامل کرنے کو کہیں۔',
  L10nKeys.sosAddContact: 'رابطہ شامل کریں',
  L10nKeys.sosDisclaimer: 'مائند کیئر آپ کے منتخب کردہ رابطوں کو اطلاع دیتا ہے۔ یہ سرکاری ہنگامی خدمات کا متبادل نہیں۔',
  L10nKeys.sosContactedPerson: 'خاندان کے فرد سے رابطہ ہوا',
  L10nKeys.sosEscalatedTo: 'اگلے خاندان کے فرد سے رابطہ ہوا',
  L10nKeys.sosAcknowledged: 'خاندان کے فرد نے جواب دیا ہے۔ مدد آ رہی ہے۔',
  L10nKeys.sosNotSilent:
      'اگر ہم مدد نہ بھیج سکیں تو ہم کبھی دکھاوا نہیں کریں گے۔',
  L10nKeys.sosAlertNotDelivered:
      'آپ کا پیغام ابھی نہیں بھیجا جا سکا۔ ہم کوشش کرتے رہیں گے۔',

  L10nKeys.careTitle: 'دیکھ بھال کرنے والا',
  L10nKeys.careDashboard: 'جائزہ',
  L10nKeys.carePatients: 'میرے مریض',
  L10nKeys.careMemories: 'یادیں',
  L10nKeys.careContacts: 'ہنگامی رابطے',
  L10nKeys.careSettings: 'ترتیبات',
  L10nKeys.careAddMemory: 'یاد شامل کریں',
  L10nKeys.careAddContact: 'رابطہ شامل کریں',
  L10nKeys.careEngagement: 'شمولیت',
  L10nKeys.careActivitiesWeek: 'اس ہفتے کی سرگرمیاں',
  L10nKeys.careGardenProgress: 'باغ کی ترقی',
  L10nKeys.careRecentActivity: 'حالیہ سرگرمی',
  L10nKeys.careNoPatients: 'کوئی مریض منسلک نہیں',
  L10nKeys.careNoPatientsBody:
      'خاندان کے فرد کو منسلک کرنے کو کہیں، یا مریض کا پروفائل شامل کریں۔',
  L10nKeys.careAddPatient: 'مریض شامل کریں',
  L10nKeys.carePerformanceNote: 'حالیہ طور پر اس شخص کی سرگرمی کارکردگی ان کی معمول کی سطح سے تھوڑی کم ہے۔',
  L10nKeys.careUploadPhoto: 'تصویر اپ لوڈ کریں',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'آواز ریکارڈ کریں',
  L10nKeys.careWriteMemory: 'یاد لکھیں',
  L10nKeys.careMemoryTitle: 'عنوان',
  L10nKeys.careMemoryCaption: 'کیپشن',
  L10nKeys.careMemoryRelation: 'اس میں کون ہے؟ (رشتہ)',
  L10nKeys.careMemoryCategory: 'زمرہ',
  L10nKeys.careContactName: 'نام',
  L10nKeys.careContactPhone: 'فون نمبر',
  L10nKeys.careContactPriority: 'کال ترتیب',
  L10nKeys.careContactRelation: 'رشتہ',
  L10nKeys.careEscalationTimeout: 'اگلے رابطے سے پہلے کے منٹ',
  L10nKeys.careIncidentStatus: 'صورتحال',
  L10nKeys.careAckSos: 'میں جواب دے رہا ہوں',
  L10nKeys.careResponding: 'جواب دے رہے ہیں',
  L10nKeys.careActiveAlerts: 'فعال الرٹس',

  L10nKeys.syncSavingOffline: 'آف لائن',
  L10nKeys.syncSavingOfflineBody: 'آپ کی سرگرمیاں اس آلے پر محفوظ ہیں۔',
  L10nKeys.syncSynced: 'مطابقت ہو گئی',
  L10nKeys.syncInfo: 'آپ کی معلومات مطابقت پزیر ہو گئیں۔',
  L10nKeys.syncPending: 'مطابقت کا انتظار',

  L10nKeys.errorGeneric: 'کچھ غلط ہو گیا',
  L10nKeys.errorGenericBody:
      'آپ کی پیشرفت محفوظ ہے۔ براہ کرم دوبارہ کوشش کریں۔',
  L10nKeys.errorAudio: 'اس آلے پر آواز نہیں چل سکی۔',
  L10nKeys.errorPermission: 'اس کے لیے آلے کی اجازت درکار ہے۔',
  L10nKeys.errorNoInternetAction:
      'انٹرنیٹ کی ضرورت نہیں — یہ پہلے یہیں محفوظ ہوتا ہے۔',

  L10nKeys.demoWelcome: 'ڈیمو دیکھیں',
  L10nKeys.demoExplain:
      'آپ دیکھ سکیں اس لیے نمونہ خاندان اور یادیں شامل کی جائیں گی۔',
  L10nKeys.demoLoad: 'ڈیمو باغ لوڈ کریں',

  L10nKeys.unitsPoints: 'نکات',
  L10nKeys.teaserChai: 'چائے بنائیں۔',
  L10nKeys.familiarityName: 'آشا',
  L10nKeys.regionMap: 'میرا علاقہ',
  L10nKeys.regionChoose: 'اپنا علاقہ منتخب کریں',
  L10nKeys.regionIndia: 'بھارت',
  L10nKeys.importantMemory: 'اہم یاد',
  L10nKeys.growing: 'بڑھ رہا ہے',
  L10nKeys.blooming: 'کھل رہا ہے',
  L10nKeys.mature: 'پختہ',
  L10nKeys.noVoice: 'اس آلے پر آواز دستیاب نہیں۔',
  L10nKeys.optional: 'اختیاری',

  L10nKeys.langChoose: 'زبان منتخب کریں',
  L10nKeys.langPrimary: 'بنیادی',
  L10nKeys.langNorthEast: 'شمال مشرقی بھارت',
  L10nKeys.langMajor: 'بھارت کی اہم زبانیں',

  L10nKeys.authSignUpTitle: 'اپنا اکاؤنٹ بنائیں',
  L10nKeys.authSignUpBody: 'یہ مائند کیئر پروفائل آپ کے آلے پر محفوظ رہتا ہے۔ صرف آپ کھول سکیں اس لیے صارف نام اور پاس ورڈ رکھیں۔',
  L10nKeys.authLoginTitle: 'واپسی خوش آئند',
  L10nKeys.authLoginBody:
      'اپنا باغ کھولنے کے لیے صارف نام اور پاس ورڈ سے سائن ان کریں۔',
  L10nKeys.authUsername: 'صارف نام',
  L10nKeys.authUsernameHint: 'مثلاً: ranu123',
  L10nKeys.authDisplayName: 'آپ کا نام',
  L10nKeys.authPassword: 'پاس ورڈ',
  L10nKeys.authPasswordHint: 'کم از کم ۶ حروف',
  L10nKeys.authConfirmPassword: 'پاس ورڈ کی تصدیق کریں',
  L10nKeys.authRoleQuestion: 'یہ پروفائل کس کے لیے…',
  L10nKeys.authRolePatient: 'میرے لیے',
  L10nKeys.authRoleCaregiver: 'خاندان کے فرد کے لیے',
  L10nKeys.authCreate: 'اکاؤنٹ بنائیں',
  L10nKeys.authSignIn: 'سائن ان',
  L10nKeys.authSignOut: 'سائن آؤٹ',
  L10nKeys.authAccount: 'اکاؤنٹ',
  L10nKeys.caregiverTitle: 'دیکھ بھال کرنے والا',
  L10nKeys.caregiverNotLinked: 'ابھی تک کوئی دیکھ بھال کرنے والا منسلک نہیں',
  L10nKeys.authBadCredentials: 'صارف نام یا پاس ورڈ غلط ہے۔',
  L10nKeys.authUsernameTaken: 'یہ صارف نام اس آلے پر پہلے سے استعمال میں ہے۔',
  L10nKeys.authPasswordMismatch: 'پاس ورڈ مطابقت نہیں رکھتے۔',
  L10nKeys.authUsernameShort: 'صارف نام کم از کم ۳ حروف کا ہونا چاہیے۔',
  L10nKeys.authUsernameInvalid:
      'صرف حروف، اعداد، ڈاٹ، ڈیش یا انڈر اسکور استعمال کریں۔',
  L10nKeys.authPasswordShort: 'پاس ورڈ کم از کم ۶ حروف کا ہونا چاہیے۔',
  L10nKeys.authNameRequired: 'براہ کرم نام درج کریں۔',
  L10nKeys.authSignOutConfirm: 'کیا آپ اس پروفائل سے سائن آؤٹ کرنا چاہتے ہیں؟',
  L10nKeys.screenTitle: 'فوری یادداشت جانچ',
  L10nKeys.screenIntro: 'ہم مریض کے بارے میں کچھ چھوٹے سوال پوچھیں گے۔ پچھلے چند مہینوں میں وہ کیسے رہے ہیں اس کے بارے میں سوچیں۔',
  L10nKeys.screenNotSure: 'یقین نہیں',
  L10nKeys.screenFinish: 'میرا نتیجہ دیکھیں',
  L10nKeys.screenSkip: 'ابھی چھوڑیں',
  L10nKeys.screenResultBack: 'ہو گیا',
  L10nKeys.screenCheckAgain: 'دوبارہ جانچیں',
  L10nKeys.screenStartCheckup: 'جانچ شروع کریں',
  L10nKeys.screenSkipped: 'جانچ ملتوی کر دی گئی',
  L10nKeys.screenStatusGood: 'سب کچھ ٹھیک لگتا ہے',
  L10nKeys.screenStatusGoodBody: 'کوئی بڑی تشویش نظر نہیں آئی۔ روزانہ کی سرگرمیاں جاری رکھیں، اور اگر کچھ بدلے تو کسی بھی وقت دوبارہ جانچ کر سکتے ہیں۔',
  L10nKeys.screenStatusWatch: 'کچھ تبدیلیاں نظر آئیں',
  L10nKeys.screenStatusWatchBody: 'بھولنے کے کچھ لمحے نظر آئے۔ یہ عمر کے ساتھ عام ہے، لیکن نظر رکھیں اور اگلی ڈاکٹر ملاقات پر بتائیں۔',
  L10nKeys.screenStatusDoctor: 'براہ کرم جانچ کروائیں',
  L10nKeys.screenStatusDoctorBody: 'کچھ ایسی علامات نظر آئیں جن پر توجہ دینے کی ضرورت ہو سکتی ہے۔ براہ کرم انہیں ڈاکٹر یا کلینک سے شیئر کریں تاکہ وہ مدد کر سکیں۔',
  L10nKeys.screenRarely: 'شاذ و نادر',
  L10nKeys.screenSometimes: 'کبھی کبھی',
  L10nKeys.screenFrequently: 'اکثر',
  L10nKeys.screenVeryFrequently: 'بہت اکثر',
  L10nKeys.screenQ01: 'کیا انہیں حالیہ واقعات یاد رکھنے میں دشواری ہوتی ہے؟',
  L10nKeys.screenQ02: 'کیا وہ ایک ہی سوال یا کہانیاں دہراتے ہیں؟',
  L10nKeys.screenQ03: 'کیا وہ جانے پہچانے لوگوں کے نام بھول جاتے ہیں؟',
  L10nKeys.screenQ04: 'کیا انہیں پہچانے ہوئے چہرے پہچاننے میں دشواری ہوتی ہے؟',
  L10nKeys.screenQ05: 'کیا وہ ملاقاتیں یا اہم واقعات بھول جاتے ہیں؟',
  L10nKeys.screenQ06: 'کیا انہیں صحیح الفاظ تلاش کرنے میں دشواری ہوتی ہے؟',
  L10nKeys.screenQ07: 'کیا وہ اس بارے میں الجھ جاتے ہیں کہ وہ کہاں ہیں؟',
  L10nKeys.screenQ08:
      'کیا انہیں روزانہ کی سرگرمیوں کے لیے یاد دہانی کی ضرورت ہوتی ہے؟',
  L10nKeys.screenQ09: 'کیا انہیں ادویات سنبھالنے میں دشواری ہوتی ہے؟',
  L10nKeys.screenQ10: 'کیا وہ الجھن پر پریشان یا چڑچڑے ہو جاتے ہیں؟',
  L10nKeys.screenQ11: 'کیا انہیں گفتگو سمجھنے میں دشواری ہوتی ہے؟',
  L10nKeys.screenQ12: 'کیا انہیں جانے پہچانے کام مکمل کرنے میں دشواری ہوتی ہے؟',
  L10nKeys.screenQ13: 'کیا وہ بھول جاتے ہیں کہ روزمرہ کی چیزیں کہاں رکھی ہیں؟',
  L10nKeys.screenQ14: 'کیا انہیں ہدایات یاد رکھنے میں دشواری ہوتی ہے؟',
  L10nKeys.screenQ15:
      'کیا انہیں کئی مرحلوں والی سرگرمیاں کرنے میں دشواری ہوتی ہے؟',

  L10nKeys.careDashboardSubtitle: 'خاندانی دیکھ بھال',
  L10nKeys.careSosLive: 'لائیو الرٹ',
  L10nKeys.careSosRespondedBy: '{name} نے جواب دیا',
  L10nKeys.careLinkTitle: 'خاندان کے کسی رکن سے جڑیں',
  L10nKeys.careLinkBody: 'اپنے پیارے سے ان کے فون پر نظر آنے والا 6 حرفی خاندانی کوڈ پوچھیں، پھر جڑیں۔',
  L10nKeys.careLinkCode: 'خاندانی کوڈ',
  L10nKeys.careLinkCodeHint: 'جیسے A1B2C3',
  L10nKeys.careLinkConnect: 'جڑیں',
  L10nKeys.careLinkDone: 'منسلک',
  L10nKeys.careLinkSuccess:
      '{name} سے منسلک! یادیں اور الرٹس اب ہم وقت ساز ہوں گے۔',
  L10nKeys.careLinkFailed:
      'منسلک نہیں ہو سکا۔ براہ کرم کوڈ چیک کر کے دوبارہ کوشش کریں۔',
  L10nKeys.careTrendsTitle: 'AI رجحانات',
  L10nKeys.careTrendsBody: 'سرگرمی کی قسم کے مطابق روزانہ کی درستی',
  L10nKeys.careTrendsNoData:
      'ابھی کوئی سرگرمی نہیں — رجحانات دیکھنے کے لیے ایک مشق مکمل کریں۔',
  L10nKeys.careAiDifficulty: 'خودکار ایڈجسٹ شدہ مشکل',
  L10nKeys.careAiAccuracy: 'ماڈل کی درستی',
  L10nKeys.careAiRealSessions: 'حقیقی سیشن',
  L10nKeys.careAiDemoSessions: 'ڈیمو سیشن',
  L10nKeys.careNavGames: 'گیمز',
  L10nKeys.careNavRoutine: 'روٹین',
  L10nKeys.careGreetSubtitle: 'آج {name} کیسی کارکردگی ہے اس کا خلاصہ یہ ہے۔',
  L10nKeys.careNotifEmpty: 'کوئی نئی اطلاع نہیں',
  L10nKeys.careWellnessScore: 'ادراکی صحت کا اسکور',
  L10nKeys.careStatusStable: 'مستحکم',
  L10nKeys.careStatusAttention: 'توجہ درکار ہے',
  L10nKeys.careLastSynced: 'آخری ہم آہنگی {time}',
  L10nKeys.careMinAgo: '{n} منٹ قبل',
  L10nKeys.careGamesWeek: 'اس ہفتے کے گیمز',
  L10nKeys.careRoutineCompletion: 'روٹین کی تکمیل',
  L10nKeys.careCurrentStreak: 'موجودہ سلسلہ',
  L10nKeys.careMoodCheckins: 'موڈ چیک-اِنز',
  L10nKeys.careDayUnit: 'دن',
  L10nKeys.careDaysUnit: 'دن',
  L10nKeys.careActivityTitle: 'ہفتہ وار سرگرمی',
  L10nKeys.careWeekly: 'ہفتہ وار',
  L10nKeys.careMonthly: 'ماہانہ',
  L10nKeys.careNoActivityWeek: 'اس ہفتے ابھی کوئی سرگرمی درج نہیں ہوئی ہے۔',
  L10nKeys.careMoodTitle: 'موڈ',
  L10nKeys.careMoodHappy: 'خوش',
  L10nKeys.careMoodCalm: 'پرسکون',
  L10nKeys.careMoodNeutral: 'غیر جانبدار',
  L10nKeys.careMoodLow: 'کم',
  L10nKeys.careMood7Days: 'پچھلے 7 دن',
  L10nKeys.careMoodInsight: '{name} اس ہفتے زیادہ تر پرسکون رہے، آخری دو دنوں میں ہلکی سی کمی دیکھی گئی۔',
  L10nKeys.careMoodNoData: 'اس ہفتے ابھی کوئی موڈ چیک-اِن نہیں ہے۔',
  L10nKeys.careSkillsTitle: 'ادراکی مہارتیں',
  L10nKeys.careSkillMemory: 'یادداشت',
  L10nKeys.careSkillAttention: 'توجہ',
  L10nKeys.careSkillLanguage: 'زبان',
  L10nKeys.careSkillReasoning: 'استدلال',
  L10nKeys.careSkillProcessing: 'پروسیسنگ کی رفتار',
  L10nKeys.careInsightToday: 'آج کی بصیرت',
  L10nKeys.careInsightBody: 'رابرٹ اپنے صبح کے روٹین کے بعد یادداشت کی سرگرمیوں میں مستقل رہے ہیں۔ پچھلے دو دنوں میں ان کا موڈ قدرے کم رہا ہے۔',
  L10nKeys.careInsightBodyReal: 'اس ہفتے {name} نے {count} ادراکی سیشن مکمل کیے (ہدف {goal}) اور {streak}-دن کا سلسلہ جاری رکھے ہوئے ہیں۔',
  L10nKeys.careViewDetails: 'تفصیلات دیکھیں',
  L10nKeys.careInsightDisclaimer:
      'یہ ڈیٹا سے لی گئی ایک نرم مشاہدہ ہے — طبی تشخیص نہیں۔',
  L10nKeys.careAttentionTitle: 'آپ کی توجہ درکار ہے',
  L10nKeys.careAttentionEmpty:
      'ابھی آپ کی توجہ کی ضرورت والی کوئی چیز نہیں ہے۔',
  L10nKeys.careAlertSos: '{name} نے SOS بٹن دبایا',
  L10nKeys.careAlertRoutineMissed: 'کل روٹین چھوٹ گئی',
  L10nKeys.careAlertMoodDown: 'پچھلے دو دنوں میں موڈ کم ہوا',
  L10nKeys.careAlertSessionPending: 'آج ادراکی سیشن مکمل نہیں ہوا',
  L10nKeys.careAlertSeverityHigh: 'زیادہ',
  L10nKeys.careAlertSeverityMedium: 'درمیانہ',
  L10nKeys.careAlertSeverityLow: 'کم',
  L10nKeys.careWeeklySummary: 'ہفتہ وار خلاصہ',
  L10nKeys.careSessionsCompleted: 'مکمل شدہ سیشن',
  L10nKeys.careAvgSessionDuration: 'اوسط سیشن کا دورانیہ',
  L10nKeys.careRoutineAdherence: 'روٹین کی پابندی',
  L10nKeys.careMoodTrend: 'موڈ کا رجحان',
  L10nKeys.careMoodTrendSlightlyDown: 'قدرے کم',
  L10nKeys.careMoodTrendStable: 'مستحکم',
  L10nKeys.careMoodTrendUp: 'بہتری آ رہی ہے',
  L10nKeys.careVsLastWeek: 'پچھلے ہفتے کے مقابلے میں',
  L10nKeys.careSyncedJustNow: 'ابھی ہم آہنگ ہوا',
  L10nKeys.careOfflineWaiting:
      'آف لائن · {count} سرگرمیاں ہم آہنگی کے منتظر ہیں',
  L10nKeys.careComingSoon: 'عنقریب آ رہا ہے',
  L10nKeys.careHomeSoon: '{name} کے دن کا فوری جائزہ یہاں ظاہر ہوگا۔',
  L10nKeys.careGamesSoon: 'گیمز اور سیشن کی تاریخ یہاں ظاہر ہوگی۔',
  L10nKeys.careRoutineSoon: 'مریض کا روزانہ روٹین یہاں ظاہر ہوگا۔',
  L10nKeys.careProfileSoon:
      'نگہداشت کرنے والے کا پروفائل اور ترتیبات یہاں ظاہر ہوں گی۔',
  L10nKeys.serverPairingTitle: 'خاندانی کوڈ',
  L10nKeys.serverPairingBody:
      'یہ کوڈ کسی دیکھ بھال کرنے والے کے ساتھ شیئر کریں تاکہ وہ آپ سے جڑ سکیں۔',
  L10nKeys.serverUnlinked: 'سرور سے منسلک نہیں',
  L10nKeys.serverLinked: 'سرور سے منسلک',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
