import '../l10n_keys.dart';

/// Odia dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsOr = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'ଆପଣଙ୍କ ସ୍ମୃତିର ସାଥୀ',
  L10nKeys.back: 'ପଛକୁ',
  L10nKeys.next: 'ଆଗକୁ',
  L10nKeys.continueText: 'ଆଗକୁ ଯାଆନ୍ତୁ',
  L10nKeys.skip: 'ଏଡ଼ିଯାଆନ୍ତୁ',
  L10nKeys.done: 'ହେଲାଣି',
  L10nKeys.cancel: 'ବାତିଲ',
  L10nKeys.yes: 'ହଁ',
  L10nKeys.no: 'ନାଁ',
  L10nKeys.save: 'ସାଇତନ୍ତୁ',
  L10nKeys.close: 'ବନ୍ଦ କରନ୍ତୁ',
  L10nKeys.retry: 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ',
  L10nKeys.add: 'ଯୋଡ଼ନ୍ତୁ',
  L10nKeys.edit: 'ବଦଳାନ୍ତୁ',
  L10nKeys.remove: 'ହଟାନ୍ତୁ',
  L10nKeys.search: 'ଖୋଜନ୍ତୁ',
  L10nKeys.today: 'ଆଜି',
  L10nKeys.offline: 'ଅଫଲାଇନ',
  L10nKeys.online: 'ଅନଲାଇନ',

  L10nKeys.goodMorning: 'ଶୁଭ ସକାଳ',
  L10nKeys.goodAfternoon: 'ନମସ୍କାର',
  L10nKeys.goodEvening: 'ଶୁଭ ସଞ୍ଜ',
  L10nKeys.goodNight: 'ଶୁଭ ରାତ୍ରି',

  L10nKeys.navHome: 'ଘର',
  L10nKeys.navGarden: 'ବଗିଚା',
  L10nKeys.navActivities: 'କାର୍ଯ୍ୟକଳାପ',
  L10nKeys.navMemories: 'ସ୍ମୃତି',
  L10nKeys.navProfile: 'ପ୍ରୋଫାଇଲ',
  L10nKeys.navMystery: 'ଆଜିର ସ୍ମୃତି',

  L10nKeys.onboardingWelcomeTitle: 'ଆପଣଙ୍କ ସ୍ମୃତିର ଏକ କୋମଳ ସାଥୀ',
  L10nKeys.onboardingWelcomeBody: 'ମାଇଣ୍ଡକେୟାର ଏନଇଆର ଇଣ୍ଟରନେଟ ବିନା ମଧ୍ୟ ମନେ ରଖିବା, ଖେଳିବା ଏବଂ ପରିବାର ସହ ଯୋଡ଼ି ହୋଇ ରହିବାରେ ସାହାଯ୍ୟ କରେ।',
  L10nKeys.onboardingNameTitle: 'ଆମେ ଆପଣଙ୍କୁ କଣ ବୋଲି ଡାକିବା?',
  L10nKeys.onboardingNameHint: 'ଆପଣଙ୍କ ନାମ',
  L10nKeys.onboardingRegionTitle: 'ଆପଣଙ୍କ ଘର କେଉଁଠି?',
  L10nKeys.onboardingRegionHint: 'ସହର କିମ୍ବା ଗାଁ',
  L10nKeys.onboardingRegionList: 'ଗୁୱାହାଟୀ, ସିଲଚର, ଶିଲୋଙ୍ଗ, ଅଗରତଲା, ଇମ୍ଫାଲ, ଆଇଜୋଲ, ଇଟାନଗର, କୋହିମା, ଗାଙ୍ଗଟକ, ଡିବ୍ରୁଗଡ଼, ଯୋରହାଟ, ଆପଣଙ୍କ ସହର',
  L10nKeys.onboardingLanguageTitle: 'ଆପଣଙ୍କୁ କେଉଁ ଭାଷା ଭଲ ଲାଗିବ?',
  L10nKeys.onboardingLanguageBody: 'ଆପଣ ଏହାକୁ ଯେକୌଣସି ସମୟରେ ବଦଳାଇ ପାରିବେ।',
  L10nKeys.onboardingFamilyTitle: 'ପରିବାର କିଏ?',
  L10nKeys.onboardingFamilyBody: 'ଆପଣଙ୍କ ପ୍ରିୟ ଲୋକଙ୍କୁ ଯୋଡ଼ନ୍ତୁ। ସେମାନଙ୍କ ଫଟୋ ଏବଂ ସ୍ୱରକୁ ଆମେ କୋମଳ ସ୍ମୃତି ଭାବେ ଦେଖାଇବୁ।',
  L10nKeys.onboardingAddFamily: 'ପରିବାର ସଦସ୍ୟ ଯୋଡ଼ନ୍ତୁ',
  L10nKeys.onboardingEmergencyTitle: 'ଜରୁରୀ ପରିସ୍ଥିତିରେ ଆମେ କାହାକୁ ଡାକିବା?',
  L10nKeys.onboardingEmergencyBody:
      'SOS ବଟନ ଦାବିଲେ ମାଇଣ୍ଡକେୟାର ଆପଣଙ୍କ ପରିବାରକୁ ଜଣାଏ, ଜରୁରୀ ସେବାକୁ ନୁହେଁ।',
  L10nKeys.onboardingEmergencyName: 'ନାମ',
  L10nKeys.onboardingEmergencyPhone: 'ଫୋନ ନମ୍ବର',
  L10nKeys.onboardingEmergencyRelation: 'ସମ୍ପର୍କ (ଝିଅ, ପୁଅ…)',
  L10nKeys.onboardingDoneTitle: 'ଆପଣଙ୍କ ବଗିଚା ପ୍ରସ୍ତୁତ!',
  L10nKeys.onboardingDoneBody: 'ଛୋଟ କାର୍ଯ୍ୟକଳାପ ଶେଷ କରନ୍ତୁ ଏବଂ ବଗିଚା ବଢ଼ିବା ଦେଖନ୍ତୁ। ଆମେ ଆପଣଙ୍କ ସହିତ ଅଛୁ।',
  L10nKeys.onboardingStart: 'ମୋ ବଗିଚା ଆରମ୍ଭ କରନ୍ତୁ',

  L10nKeys.homeWhatsGrowing: 'ଆଜି କଣ ବଢ଼ୁଛି?',
  L10nKeys.homeTodayActivity: 'ଆଜିର ଛୋଟ କାର୍ଯ୍ୟକଳାପ',
  L10nKeys.homeActivityDuration: 'ପ୍ରାୟ ୩ ମିନିଟ',
  L10nKeys.homeMinutes: 'ମିନିଟ',
  L10nKeys.homeMemoryOfDay: 'ଆଜିର ସ୍ମୃତି',
  L10nKeys.homeMemoryLocked: 'ଏକ ବିଶେଷ ସ୍ମୃତି ଅପେକ୍ଷା କରୁଛି…',
  L10nKeys.homeMemoryUnlocked: 'ଏକ ସ୍ମୃତି ଖୋଲିଗଲା!',
  L10nKeys.homeContinueActivity: 'କାର୍ଯ୍ୟକଳାପ ଜାରି ରଖନ୍ତୁ',
  L10nKeys.homeFamilyMemory: 'ଆପଣଙ୍କ ପରିବାର ତରଫରୁ',
  L10nKeys.homeFamilyMemoryEmpty: 'ପରିବାରର ସ୍ମୃତି ଏଠାରେ ଦେଖାଯାଇପାରେ।',
  L10nKeys.homeSos: 'ସାହାଯ୍ୟ ଦରକାର',
  L10nKeys.homeSosSubtitle: 'ଜରୁରୀ ପରିସ୍ଥିତିରେ ପରିବାର ସହ ଯୋଗାଯୋଗ',
  L10nKeys.homeGardenPreview: 'ଆପଣଙ୍କ ବଗିଚା',
  L10nKeys.homeEngine: 'ମାଇଣ୍ଡକେୟାର ସାଥୀ',
  L10nKeys.homeEngineReady: 'ଆପଣଙ୍କ ସହାୟକ ପ୍ରସ୍ତୁତ।',
  L10nKeys.homeWelcomeBack: 'ପୁଣି ସ୍ୱାଗତ! ଚାଲନ୍ତୁ ବଗିଚା ଆଗକୁ ନେବା। 🌸',
  L10nKeys.homeNoActivity: 'ଆଜି କୌଣସି କାର୍ଯ୍ୟକଳାପ ନାହିଁ',
  L10nKeys.homeNoActivityBody:
      'ଟିକିଏ ଆରାମ କରନ୍ତୁ — କିମ୍ବା ମନପସନ୍ଦ କାର୍ଯ୍ୟକଳାପ ବାଛନ୍ତୁ। 🌻',

  L10nKeys.gardenTitle: 'ମୋ ସ୍ମୃତି ବଗିଚା',
  L10nKeys.gardenSectionAll: 'ସବୁ',
  L10nKeys.gardenSectionFamily: 'ପରିବାର',
  L10nKeys.gardenSectionChildhood: 'ଶୈଶବ',
  L10nKeys.gardenSectionPlaces: 'ସ୍ଥାନ',
  L10nKeys.gardenSectionFestivals: 'ପର୍ବପର୍ବାଣୀ',
  L10nKeys.gardenEmpty: 'ଆପଣଙ୍କ ବଗିଚା ଅଳ୍ପ ମାତ୍ରରେ ଆରମ୍ଭ ହୋଇଛି',
  L10nKeys.gardenEmptyBody:
      'ପ୍ରଥମ କାର୍ଯ୍ୟକଳାପ ଶେଷ କରନ୍ତୁ, ଏଠାରେ ଗୋଟିଏ ମଞ୍ଜି ବୁଣାଯିବ।',
  L10nKeys.gardenPoints: 'ପଏଣ୍ଟ',
  L10nKeys.gardenLevel: 'ସ୍ତର',
  L10nKeys.gardenSeed: 'ମଞ୍ଜି',
  L10nKeys.gardenPlant: 'ଗଛ',
  L10nKeys.gardenFlower: 'ଫୁଲ',
  L10nKeys.gardenTree: 'ବୃକ୍ଷ',
  L10nKeys.gardenMilestone: 'ପର୍ଯ୍ୟାୟ',
  L10nKeys.gardenGrowth: 'ବଢ଼ୁଛି',
  L10nKeys.gardenDidYouKnow: 'ପ୍ରତ୍ୟେକ ଶେଷ ହେଉଥିବା କାର୍ଯ୍ୟକଳାପରେ ବଗିଚା ବଢ଼େ।',
  L10nKeys.gardenPlantSeed: 'ମଞ୍ଜି ବୁଣନ୍ତୁ',

  L10nKeys.activitiesTitle: 'କାର୍ଯ୍ୟକଳାପ',
  L10nKeys.activitiesToday: 'ଆଜି',
  L10nKeys.activitiesLibrary: 'ଅଧିକ କାର୍ଯ୍ୟକଳାପ',
  L10nKeys.mainGamesTitle: 'ମୁଖ୍ୟ ଖେଳ',
  L10nKeys.activitiesStart: 'ଆରମ୍ଭ କରନ୍ତୁ',
  L10nKeys.activitiesCompleted: 'ଶେଷ',
  L10nKeys.activitiesInProgress: 'ଚାଲୁଛି',
  L10nKeys.activitiesNotStarted: 'ପ୍ରସ୍ତୁତ',
  L10nKeys.activityYoureDone: 'ବହୁତ ଭଲ!',
  L10nKeys.activityPraise: 'ଆପଣ ବଗିଚାକୁ ଟିକେ ଜୀବନ ଦେଲେ। 🌱',
  L10nKeys.activityHint: 'ସଙ୍କେତ ଦରକାର?',
  L10nKeys.activityTryAgain: 'ଚାଲନ୍ତୁ ଏହି ସ୍ମୃତି ପୁଣି ଦେଖିବା',
  L10nKeys.activityOptionsHint: 'ଆପଣଙ୍କ ଉତ୍ତର ବାଛନ୍ତୁ',
  L10nKeys.activityTapToMatch: 'ମିଳୁଥିବା ଯୋଡ଼ି ବାଛନ୍ତୁ',
  L10nKeys.activityNext: 'ଆଗକୁ',
  L10nKeys.activityFinish: 'ଶେଷ',
  L10nKeys.activityGroupLetsAgain: 'ଚାଲନ୍ତୁ ପୁଣି ଦେଖିବା',
  L10nKeys.activityGroupTogether: 'ଚାଲନ୍ତୁ ଏହା ମିଶି କରିବା',
  L10nKeys.activityGreatJob: 'ବହୁତ ଭଲ କରିଛନ୍ତି!',
  L10nKeys.activityKitchen: 'ମୋ ରୋଷେଇ ଘର',
  L10nKeys.activityShopping: 'ମୋ ଦୋକାନ',
  L10nKeys.activityMatching: 'ଯୋଡ଼ି ମିଳାନ୍ତୁ',
  L10nKeys.activitySequence: 'କ୍ରମରେ ଲଗାନ୍ତୁ',
  L10nKeys.activityRecognition: 'ଏହା କଣ?',
  L10nKeys.activityAssociation: 'କଣ ସାଙ୍ଗରେ ଚାଲେ?',
  L10nKeys.activityRecall: 'ମନେ ପଡ଼ୁଛି?',
  L10nKeys.activityAttention: 'ଖୋଜନ୍ତୁ',
  L10nKeys.activityDurationSuffix: 'ମିନିଟ',
  L10nKeys.activityTodayDone: 'ଆଜିର କାର୍ଯ୍ୟକଳାପ ଶେଷ',
  L10nKeys.activityTodayDoneBody:
      'ଆପଣଙ୍କ ବଗିଚା ବଢ଼ିଲା। ଆସନ୍ତାକାଲି ଏକ ସ୍ମୃତି ଅପେକ୍ଷା କରିବ।',
  L10nKeys.activityGardenGrew: 'ଆପଣଙ୍କ ବଗିଚା ବଢ଼ିଲା!',
  L10nKeys.activityMemoryUnlocked: 'ଏକ ସ୍ମୃତି ଖୋଲିଗଲା',
  L10nKeys.activityReadAloud: 'ଉଚ୍ଚ ସ୍ୱରରେ ପଢ଼ନ୍ତୁ',

  L10nKeys.kitchenTitle: 'ଚା ତିଆରି କରିବା',
  L10nKeys.kitchenMakeChai: 'ଚା ତିଆରି',
  L10nKeys.kitchenMakeChaiPrompt: 'ପଦକ୍ଷେପ ଠିକ୍ କ୍ରମରେ ବାଛନ୍ତୁ।',
  L10nKeys.kitchenSteps: 'ପଦକ୍ଷେପ',
  L10nKeys.kitchenTapInOrder: 'ପଦକ୍ଷେପ ଠିକ୍ କ୍ରମରେ ବାଛନ୍ତୁ',
  L10nKeys.kitchenCorrectOrder: 'ଭଲ! ଚା ପ୍ରସ୍ତୁତ!',
  L10nKeys.kitchenBreakfast: 'ଜଳଖିଆ ତିଆରି',
  L10nKeys.kitchenBreakfastHint: 'ଦିନର ତାଜା ଆରମ୍ଭ',
  L10nKeys.kitchenBreakfastPrompt: 'ଜଳଖିଆର ପଦକ୍ଷେପ କ୍ରମରେ ଲଗାନ୍ତୁ।',

  L10nKeys.shopTitle: 'ମୋ ଦୋକାନ',
  L10nKeys.shopGetMilkBread: 'ରୁଟି ଏବଂ କ୍ଷୀର',
  L10nKeys.shopGetMilkBreadPrompt: '₹୧୦୦ ରେ କ୍ଷୀର ଏବଂ ରୁଟି କିଣନ୍ତୁ।',
  L10nKeys.shopBudget: 'ବଜେଟ',
  L10nKeys.shopBasket: 'ଆପଣଙ୍କ ଟୋକେଇ',
  L10nKeys.shopTotal: 'ମୋଟ',
  L10nKeys.shopWithinBudget: 'ବଜେଟ ଭିତରେ!',
  L10nKeys.shopOverBudget: 'ବଜେଟ ବାହାରେ — ପୁଣି ଦେଖନ୍ତୁ',
  L10nKeys.shopCheckout: 'ଶେଷ କରି ଦେମାନ ଦିଅନ୍ତୁ',
  L10nKeys.shopBuy: 'ଟୋକେଇରେ ପକାନ୍ତୁ',
  L10nKeys.shopSell: 'ହଟାନ୍ତୁ',
  L10nKeys.shopVeggies: 'ରାତ୍ରି ଭୋଜନ ପାଇଁ ପନିପରିବା',
  L10nKeys.shopVeggiesPrompt: '₹୬୦ ରେ ଆଳୁ ଏବଂ ପିଆଜ କିଣନ୍ତୁ।',
  L10nKeys.recKitchenItem: 'ଏହା କେଉଁଟି?',
  L10nKeys.recKitchenItemPrompt:
      'ବଜାରରୁ ସାମଗ୍ରୀ ଆଣିବା ପାଇଁ ଏଥିରୁ କେଉଁଟି ବ୍ୟବହାର ହୁଏ?',
  L10nKeys.recCurrency: 'ଟିକିଏ ଟଙ୍କା',
  L10nKeys.recCurrencyPrompt: 'କେଉଁ ନୋଟ ₹୨୦ ଅଟେ?',
  L10nKeys.matchFestival: 'ପର୍ବ ମିଳାନ୍ତୁ',
  L10nKeys.matchFestivalPrompt:
      'ପ୍ରତ୍ୟେକ ପର୍ବକୁ ତା’ର ବିଶେଷ ବ୍ୟଞ୍ଜନ ସହ ମିଳାନ୍ତୁ।',
  L10nKeys.matchObjectUse: 'ଯୋଡ଼ି ବାନ୍ଧନ୍ତୁ',
  L10nKeys.matchObjectUsePrompt:
      'ପ୍ରତ୍ୟେକ ଜିନିଷକୁ ବ୍ୟବହାର ହେବାର ସମୟ ସହ ମିଳାନ୍ତୁ।',
  L10nKeys.seqMorning: 'ସକାଳର ଦୈନନ୍ଦିନୀ',
  L10nKeys.seqMorningPrompt: 'ଆପଣଙ୍କ ସକାଳର କାର୍ଯ୍ୟକ୍ରମ କ୍ରମରେ ଲଗାନ୍ତୁ।',
  L10nKeys.seqRoute: 'ସକାଳର ଯାତ୍ରା',
  L10nKeys.seqRoutePrompt: 'ବଜାର ଯାଏଁ ଯାତ୍ରା କ୍ରମରେ ଲଗାନ୍ତୁ।',
  L10nKeys.assoRegion: 'ଏଠାରେ କଣ ଅଛି?',
  L10nKeys.assoRegionPrompt: 'ଆସାମ କେଉଁ ପାଇଁ ପ୍ରସିଦ୍ଧ?',
  L10nKeys.assoHarvest: 'ମିଠା ଫଳ',
  L10nKeys.assoHarvestPrompt: 'କେଉଁ ଫଳକୁ ଗ୍ରୀଷ୍ମର ରାଜା କୁହାଯାଏ?',
  L10nKeys.attnVeg: 'ଗାଜର ଖୋଜନ୍ତୁ',
  L10nKeys.attnVegPrompt: 'ଆପଣ ଗାଜର ଖୋଜି ପାରିବେ କି?',
  L10nKeys.recallSong: 'ଏକ ଜଣାଶୁଣା ଗୀତ',
  L10nKeys.recallSongPrompt: 'ବିହୁରେ ନୃତ୍ୟଶିଳ୍ପୀମାନେ କେଉଁ ଗୀତରେ ନାଚନ୍ତି?',
  L10nKeys.activityPairs: 'ଜୋଡ଼ା ଖୋଜ',
  L10nKeys.activitySequenceRecall: 'କ୍ରମ ମନେରଖ',
  L10nKeys.activityFindChanged: 'କ’ଣ ବଦଳିଲା?',
  L10nKeys.pairsFruits: 'ବଜାରର ଫଳ',
  L10nKeys.pairsKitchen: 'ରନ୍ଧନଘରର ଜିନିଷ',
  L10nKeys.pairsRemember: 'ସବୁ କାର୍ଡ ଧ୍ୟାନରେ ଦେଖ, ପରେ ସମାନ ଜୋଡ଼ା ଖୋଜ।',
  L10nKeys.pairsStart: 'କାର୍ଡ ଲୁଚାଇ ଆରମ୍ଭ କର',
  L10nKeys.pairsFound: 'ଜୋଡ଼ା ମିଳିଗଲା!',
  L10nKeys.seqRecallItems: 'ରୋଜର ଜିନିଷ',
  L10nKeys.seqRecallNumbers: 'କ୍ରମରେ ସଂଖ୍ୟା',
  L10nKeys.seqRecallWatch: 'କାର୍ଡ ଧ୍ୟାନରେ ଦେଖ – ପ୍ରତ୍ୟେକ କ୍ରମରେ ଆଲୋକିତ ହେବ।',
  L10nKeys.seqRecallRepeat: 'ଏବେ ଦେଖିଥିବା କ୍ରମରେ କାର୍ଡ ଦବାଅ।',
  L10nKeys.changeMarket: 'ଫଳର ଟୋକରୀ',
  L10nKeys.changeFestival: 'ପର୍ବର ବତୀ',
  L10nKeys.changeRemember: 'ଏହି ଚିତ୍ରଗୁଡ଼ିକ ଧ୍ୟାନରେ ମନେରଖ।',
  L10nKeys.changeFind: 'ଗୋଟିଏ ଚିତ୍ର ବଦଳିଛି। ଭିନ୍ନ ଚିତ୍ର ଖୋଜ।',
  L10nKeys.changeCorrect: 'ବାହାପ! ସେଇଟି ବଦଳିଥିଲା।',

  L10nKeys.mysteryTitle: 'ଆଜିର ବିଶେଷ ସ୍ମୃତି',
  L10nKeys.mysteryLocked: 'ଏକ ବିଶେଷ ସ୍ମୃତି ଆପଣଙ୍କୁ ଅପେକ୍ଷା କରୁଛି…',
  L10nKeys.mysteryLockedBody:
      'ଆଜି ୨–୩ ଛୋଟ କାର୍ଯ୍ୟକଳାପ କରନ୍ତୁ; ବୋଧହୁଏ ତାହା ଖୋଲିବ। କଣ ହେବ?',
  L10nKeys.mysteryUnlocked: 'ଆପଣଙ୍କ ବିଶେଷ ସ୍ମୃତି ଏଠାରେ ଅଛି!',
  L10nKeys.mysteryUnlockedBody: 'ଏହି ସ୍ମୃତି କେବଳ ଆପଣଙ୍କ ପାଇଁ। ସମୟ ନିଅନ୍ତୁ। 🌸',
  L10nKeys.mysteryCuriosity: 'ଆଜି କଣ ଖୋଲିବ?',
  L10nKeys.mysteryOpen: 'ସ୍ମୃତି ଖୋଲନ୍ତୁ',

  L10nKeys.memoriesTitle: 'ମୋ ସ୍ମୃତି',
  L10nKeys.memoriesEmpty: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସ୍ମୃତି ନାହିଁ',
  L10nKeys.memoriesEmptyBody: 'ଆପଣଙ୍କ ପରିବାର ଫଟୋ ଏବଂ ସ୍ୱର ବାର୍ତ୍ତା ଯୋଡ଼ିପାରେ। ମିଳିବା ମାତ୍ରେ ଏଠାରେ ଦେଖାଯିବ।',
  L10nKeys.memoriesFamily: 'ପରିବାର',
  L10nKeys.memoriesPlaces: 'ସ୍ଥାନ',
  L10nKeys.memoriesFestivals: 'ପର୍ବପର୍ବାଣୀ',
  L10nKeys.memoriesChildhood: 'ଶୈଶବ',
  L10nKeys.memoriesKindPhoto: 'ଫଟୋ',
  L10nKeys.memoriesKindVoice: 'ସ୍ୱର ବାର୍ତ୍ତା',
  L10nKeys.memoriesKindText: 'କାହାଣୀ',
  L10nKeys.memoriesKindSound: 'ଧ୍ୱନି',
  L10nKeys.memoriesKindPlace: 'ସ୍ଥାନ',
  L10nKeys.memoriesAddedBy: 'ଯୋଡ଼ିଲେ',
  L10nKeys.memoriesWhoIsThis: 'ଏମାନେ କିଏ?',
  L10nKeys.memoriesPlayVoice: 'ଶୁଣନ୍ତୁ',
  L10nKeys.memoriesThisIsMe: 'ଏହି ମୁଁ',
  L10nKeys.memoriesNotMe: 'ମୁଁ ନୁହେଁ',

  L10nKeys.profileTitle: 'ପ୍ରୋଫାଇଲ',
  L10nKeys.profileLanguage: 'ଆପ୍ ଭାଷା',
  L10nKeys.profileRegion: 'ମୋ ଅଞ୍ଚଳ',
  L10nKeys.profileVoiceLanguage: 'ସ୍ୱର ଭାଷା',
  L10nKeys.profileVoicePrompts: 'ବୋଲା ଯାଉଥିବା ସଙ୍କେତ',
  L10nKeys.profileTextSize: 'ଲେଖା ଆକାର',
  L10nKeys.profileReducedMotion: 'ଶାନ୍ତ ଗତି',
  L10nKeys.profileSoundEffects: 'ଧ୍ୱନି ପ୍ରଭାବ',
  L10nKeys.profileFamily: 'ପରିବାର',
  L10nKeys.profileContacts: 'ଜରୁରୀ ସଂପର୍କ',
  L10nKeys.profileDemoMode: 'ଡେମୋ ମୋଡ',
  L10nKeys.profileReminders: 'ମନେ ପକାଇବା',
  L10nKeys.profileNeedHelp: 'ସାହାଯ୍ୟ ଦରକାର?',

  L10nKeys.remindersTitle: 'ମନେ ପକାଇବା',
  L10nKeys.remindersEmpty: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ମନେ ପକାଇବା ନାହିଁ',
  L10nKeys.remindersNew: 'ନୂଆ ମନେ ପକାଇବା',
  L10nKeys.remindersTitleLabel: 'ଶୀର୍ଷକ',
  L10nKeys.remindersDetailLabel: 'ବିବରଣୀ (ଇଚ୍ଛାଧୀନ)',
  L10nKeys.remindersTime: 'ସମୟ',
  L10nKeys.remindersDays: 'ଦିନ',
  L10nKeys.remindersEveryday: 'ପ୍ରତିଦିନ',
  L10nKeys.remindersEnabled: 'ଚାଲୁ',
  L10nKeys.remindersMedicine: 'ଔଷଧ',
  L10nKeys.remindersAppointment: 'ଆପଏଣ୍ଟମେଣ୍ଟ',
  L10nKeys.remindersRoutine: 'ଦୈନନ୍ଦିନ କାର୍ଯ୍ୟ',

  L10nKeys.dayMon: 'ସୋମ',
  L10nKeys.dayTue: 'ମଙ୍ଗଳ',
  L10nKeys.dayWed: 'ବୁଧ',
  L10nKeys.dayThu: 'ଗୁରୁ',
  L10nKeys.dayFri: 'ଶୁକ୍ର',
  L10nKeys.daySat: 'ଶନି',
  L10nKeys.daySun: 'ରବି',

  L10nKeys.sosTitle: 'ଜରୁରୀ ସାହାଯ୍ୟ',
  L10nKeys.sosExplain: 'ଚାପି ରଖନ୍ତୁ। ମାଇଣ୍ଡକେୟାର ଆପଣଙ୍କ ଜରୁରୀ ସଂପର୍କମାନଙ୍କୁ ଜଣାଇବ। ଏହା ଜରୁରୀ ସେବା (ଯେପରି ୧୧୨) ନୁହେଁ।',
  L10nKeys.sosHold: 'ସାହାଯ୍ୟ ପାଇଁ ଚାପି ରଖନ୍ତୁ',
  L10nKeys.sosHoldBody: 'ଚାପି ରଖନ୍ତୁ…',
  L10nKeys.sosActiveTitle: 'ସାହାଯ୍ୟ ସହ ଯୋଗାଯୋଗ ହେଉଛି',
  L10nKeys.sosActiveBody: 'ଆପଣଙ୍କ ପରିବାରକୁ ଜଣାଇ ଦିଆଯାଇଛି। ଯଦି ସେମାନେ ଉତ୍ତର ନଦିଅନ୍ତି, ପରବର୍ତ୍ତୀ ସଂପର୍କକୁ ଡକାଯିବ।',
  L10nKeys.sosContacting: 'ଯୋଗାଯୋଗ ହେଉଛି',
  L10nKeys.sosContactFamily: 'ପରିବାର ସହ ଯୋଗାଯୋଗ',
  L10nKeys.sosContacted: 'ଯୋଗାଯୋଗ ହେଲା',
  L10nKeys.sosWaitingResponse: 'ଉତ୍ତର ଅପେକ୍ଷା…',
  L10nKeys.sosEscalating: 'ପରବର୍ତ୍ତୀ ବ୍ୟକ୍ତିଙ୍କ ସହ ଯୋଗାଯୋଗ…',
  L10nKeys.sosCancelled: 'ସାହାଯ୍ୟ ଅନୁରୋଧ ରଦ୍ଦ',
  L10nKeys.sosCancelAction: 'ସାହାଯ୍ୟ ଅନୁରୋଧ ରଦ୍ଦ କରନ୍ତୁ',
  L10nKeys.sosDone: 'ହେଲାଣି',
  L10nKeys.sosHelpOnWay: 'କେହି ଶୀଘ୍ର ଆପଣଙ୍କ ସାଙ୍ଗରେ ହେବେ। 🧡',
  L10nKeys.sosNoContacts: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଜରୁରୀ ସଂପର୍କ ନାହିଁ',
  L10nKeys.sosNoContactsBody: 'ଦୟାକରି ପରିବାରକୁ ଜରୁରୀ ସଂପର୍କ ଯୋଡ଼ିବାକୁ କୁହନ୍ତୁ।',
  L10nKeys.sosAddContact: 'ସଂପର୍କ ଯୋଡ଼ନ୍ତୁ',
  L10nKeys.sosDisclaimer: 'ମାଇଣ୍ଡକେୟାର ଆପଣଙ୍କ ବଛା ସଂପର୍କମାନଙ୍କୁ ଜଣାଏ। ଏହା ଆଧିକାରିକ ଜରୁରୀ ସେବାର ବଦଳ ନୁହେଁ।',
  L10nKeys.sosContactedPerson: 'ପରିବାର ସଦସ୍ୟଙ୍କ ସହ ଯୋଗାଯୋଗ ହେଲା',
  L10nKeys.sosEscalatedTo: 'ପରବର୍ତ୍ତୀ ପରିବାର ସଦସ୍ୟଙ୍କ ସହ ଯୋଗାଯୋଗ ହେଲା',
  L10nKeys.sosAcknowledged: 'ପରିବାର ସଦସ୍ୟ ଉତ୍ତର ଦେଇଛନ୍ତି। ସାହାଯ୍ୟ ଆସୁଛି।',
  L10nKeys.sosNotSilent:
      'ଯଦି ଆମେ ସାହାଯ୍ୟ ପଠାଇ ପାରିବୁ ନାହିଁ, ଆମେ କେବେ ଦେଖାଣ୍ଟି ନକରିବୁ।',
  L10nKeys.sosAlertNotDelivered:
      'ଆପଣଙ୍କ ବାର୍ତ୍ତା ଏପର୍ଯ୍ୟନ୍ତ ପଠାଇ ପାରିନାହୁଁ। ଆମେ ଚେଷ୍ଟା କରି ଚାଲିବା।',

  L10nKeys.careTitle: 'ଯତ୍ନ ନେଉଥିବା ବ୍ୟକ୍ତି',
  L10nKeys.careDashboard: 'ସମୀକ୍ଷା',
  L10nKeys.carePatients: 'ମୋ ରୋଗୀ',
  L10nKeys.careMemories: 'ସ୍ମୃତି',
  L10nKeys.careContacts: 'ଜରୁରୀ ସଂପର୍କ',
  L10nKeys.careSettings: 'ସେଟିଂ',
  L10nKeys.careAddMemory: 'ସ୍ମୃତି ଯୋଡ଼ନ୍ତୁ',
  L10nKeys.careAddContact: 'ସଂପର୍କ ଯୋଡ଼ନ୍ତୁ',
  L10nKeys.careEngagement: 'ସଂପୃକ୍ତି',
  L10nKeys.careActivitiesWeek: 'ଏହି ସପ୍ତାହର କାର୍ଯ୍ୟକଳାପ',
  L10nKeys.careGardenProgress: 'ବଗିଚାର ଅଗ୍ରଗତି',
  L10nKeys.careRecentActivity: 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ',
  L10nKeys.careNoPatients: 'କୌଣସି ରୋଗୀ ସଂଯୁକ୍ତ ନାହିଁ',
  L10nKeys.careNoPatientsBody:
      'ପରିବାର ସଦସ୍ୟଙ୍କୁ ଯୋଡ଼ିବାକୁ କୁହନ୍ତୁ, କିମ୍ବା ରୋଗୀ ପ୍ରୋଫାଇଲ ଯୋଡ଼ନ୍ତୁ।',
  L10nKeys.careAddPatient: 'ରୋଗୀ ଯୋଡ଼ନ୍ତୁ',
  L10nKeys.carePerformanceNote:
      'ଏବେ ଏହି ବ୍ୟକ୍ତିଙ୍କ କାର୍ଯ୍ୟକଳାପ ପ୍ରଦର୍ଶନ ସାଧାରଣ ସ୍ତରଠାରୁ ଟିକିଏ କମ୍ ଅଛି।',
  L10nKeys.careUploadPhoto: 'ଫଟୋ ଅପଲୋଡ କରନ୍ତୁ',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'ସ୍ୱର ରେକର୍ଡ କରନ୍ତୁ',
  L10nKeys.careWriteMemory: 'ସ୍ମୃତି ଲେଖନ୍ତୁ',
  L10nKeys.careMemoryTitle: 'ଶୀର୍ଷକ',
  L10nKeys.careMemoryCaption: 'କ୍ୟାପ୍ସନ',
  L10nKeys.careMemoryRelation: 'ଏଥିରେ କିଏ ଅଛନ୍ତି? (ସମ୍ପର୍କ)',
  L10nKeys.careMemoryCategory: 'ବର୍ଗ',
  L10nKeys.careContactName: 'ନାମ',
  L10nKeys.careContactPhone: 'ଫୋନ ନମ୍ବର',
  L10nKeys.careContactPriority: 'କଲ କ୍ରମ',
  L10nKeys.careContactRelation: 'ସମ୍ପର୍କ',
  L10nKeys.careEscalationTimeout: 'ପରବର୍ତ୍ତୀ ସଂପର୍କ ପୂର୍ବରୁ ମିନିଟ',
  L10nKeys.careIncidentStatus: 'ଅବସ୍ଥା',
  L10nKeys.careAckSos: 'ମୁଁ ଉତ୍ତର ଦେଉଛି',
  L10nKeys.careResponding: 'ଉତ୍ତର ଦେଉଛନ୍ତି',
  L10nKeys.careActiveAlerts: 'ସକ୍ରିୟ ଆଲର୍ଟ',

  L10nKeys.syncSavingOffline: 'ଅଫଲାଇନ',
  L10nKeys.syncSavingOfflineBody: 'ଆପଣଙ୍କ କାର୍ଯ୍ୟକଳାପ ଏହି ଉପକରଣରେ ସୁରକ୍ଷିତ।',
  L10nKeys.syncSynced: 'ସିଙ୍କ ହେଲା',
  L10nKeys.syncInfo: 'ଆପଣଙ୍କ ସୂଚନା ସିଙ୍କ ହୋଇଗଲା।',
  L10nKeys.syncPending: 'ସିଙ୍କ ଅପେକ୍ଷାରେ',

  L10nKeys.errorGeneric: 'କିଛି ଭୁଲ୍ ହେଲା',
  L10nKeys.errorGenericBody:
      'ଆପଣଙ୍କ ଅଗ୍ରଗତି ସୁରକ୍ଷିତ। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
  L10nKeys.errorAudio: 'ଏହି ଉପକରଣରେ ସ୍ୱର ଚାଲିପାରିଲା ନାହିଁ।',
  L10nKeys.errorPermission: 'ଏଥିପାଇଁ ଉପକରଣର ଅନୁମତି ଆବଶ୍ୟକ।',
  L10nKeys.errorNoInternetAction:
      'ଇଣ୍ଟରନେଟ ଦରକାର ନାହିଁ — ଏହା ପ୍ରଥମେ ଏଠାରେ ହିଁ ସାଇତା ଯାଏ।',

  L10nKeys.demoWelcome: 'ଡେମୋ ଦେଖନ୍ତୁ',
  L10nKeys.demoExplain: 'ଆପଣ ଦେଖିପାରିବା ପାଇଁ ନମୂନା ପରିବାର ଏବଂ ସ୍ମୃତି ଯୋଡ଼ାଯିବ।',
  L10nKeys.demoLoad: 'ଡେମୋ ବଗିଚା ଲୋଡ କରନ୍ତୁ',

  L10nKeys.unitsPoints: 'ପଏଣ୍ଟ',
  L10nKeys.teaserChai: 'ଚା ତିଆରି କରିବା।',
  L10nKeys.familiarityName: 'ଆଶା',
  L10nKeys.regionMap: 'ମୋ ଅଞ୍ଚଳ',
  L10nKeys.regionChoose: 'ଆପଣଙ୍କ ଅଞ୍ଚଳ ବାଛନ୍ତୁ',
  L10nKeys.regionIndia: 'ଭାରତ',
  L10nKeys.importantMemory: 'ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ସ୍ମୃତି',
  L10nKeys.growing: 'ବଢ଼ୁଛି',
  L10nKeys.blooming: 'ଫୁଟୁଛି',
  L10nKeys.mature: 'ପରିପକ୍ୱ',
  L10nKeys.noVoice: 'ଏହି ଉପକରଣରେ ସ୍ୱର ଉପଲବ୍ଧ ନାହିଁ।',
  L10nKeys.optional: 'ଇଚ୍ଛାଧୀନ',

  L10nKeys.langChoose: 'ଭାଷା ବାଛନ୍ତୁ',
  L10nKeys.langPrimary: 'ମୁଖ୍ୟ',
  L10nKeys.langNorthEast: 'ଉତ୍ତର-ପୂର୍ବ ଭାରତ',
  L10nKeys.langMajor: 'ଭାରତର ମୁଖ୍ୟ ଭାଷା',

  L10nKeys.authSignUpTitle: 'ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ତିଆରି କରନ୍ତୁ',
  L10nKeys.authSignUpBody: 'ଏହି ମାଇଣ୍ଡକେୟାର ପ୍ରୋଫାଇଲ ଆପଣଙ୍କ ଉପକରଣରେ ସୁରକ୍ଷିତ ରହେ। କେବଳ ଆପଣ ଖୋଲିପାରିବେ ବୋଲି ୟୁଜରନେମ ଏବଂ ପାସୱାର୍ଡ ଦିଅନ୍ତୁ।',
  L10nKeys.authLoginTitle: 'ପୁଣି ସ୍ୱାଗତ',
  L10nKeys.authLoginBody:
      'ଆପଣଙ୍କ ବଗିଚା ଖୋଲିବା ପାଇଁ ୟୁଜରନେମ ଏବଂ ପାସୱାର୍ଡରେ ସାଇନ ଇନ କରନ୍ତୁ।',
  L10nKeys.authUsername: 'ୟୁଜରନେମ',
  L10nKeys.authUsernameHint: 'ଯେପରି: ranu123',
  L10nKeys.authDisplayName: 'ଆପଣଙ୍କ ନାମ',
  L10nKeys.authPassword: 'ପାସୱାର୍ଡ',
  L10nKeys.authPasswordHint: 'ଅନ୍ୟୁନ୍ୟ ୬ ଅକ୍ଷର',
  L10nKeys.authConfirmPassword: 'ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
  L10nKeys.authRoleQuestion: 'ଏହି ପ୍ରୋଫାଇଲ କାହା ପାଇଁ…',
  L10nKeys.authRolePatient: 'ମୋ ପାଇଁ',
  L10nKeys.authRoleCaregiver: 'ପରିବାର ସଦସ୍ୟଙ୍କ ପାଇଁ',
  L10nKeys.authCreate: 'ଆକାଉଣ୍ଟ ତିଆରି କରନ୍ତୁ',
  L10nKeys.authSignIn: 'ସାଇନ ଇନ',
  L10nKeys.authSignOut: 'ସାଇନ ଆଉଟ',
  L10nKeys.authAccount: 'ଆକାଉଣ୍ଟ',
  L10nKeys.caregiverTitle: 'ଯତ୍ନକାରୀ',
  L10nKeys.caregiverNotLinked: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଯତ୍ନକାରୀ ସଂଯୁକ୍ତ ହୋଇନାହିଁ',
  L10nKeys.authBadCredentials: 'ୟୁଜରନେମ କିମ୍ବା ପାସୱାର୍ଡ ଭୁଲ ଅଟେ।',
  L10nKeys.authUsernameTaken: 'ଏହି ୟୁଜରନେମ ଏହି ଉପକରଣରେ ପୂର୍ବରୁ ବ୍ୟବହୃତ।',
  L10nKeys.authPasswordMismatch: 'ପାସୱାର୍ଡ ମିଶୁନାହିଁ।',
  L10nKeys.authUsernameShort: 'ୟୁଜରନେମ ଅନ୍ୟୁନ୍ୟ ୩ ଅକ୍ଷରର ହେବା ଉଚିତ।',
  L10nKeys.authUsernameInvalid:
      'କେବଳ ଅକ୍ଷର, ସଂଖ୍ୟା, ଡଟ, ଡ୍ୟାସ କିମ୍ବା ଅଣ୍ଡରସ୍କୋର ବ୍ୟବହାର କରନ୍ତୁ।',
  L10nKeys.authPasswordShort: 'ପାସୱାର୍ଡ ଅନ୍ୟୁନ୍ୟ ୬ ଅକ୍ଷରର ହେବା ଉଚିତ।',
  L10nKeys.authNameRequired: 'ଦୟାକରି ନାମ ଲେଖନ୍ତୁ।',
  L10nKeys.authSignOutConfirm:
      'ଆପଣ କ’ଣ ଏହି ପ୍ରୋଫାଇଲରୁ ସାଇନ ଆଉଟ କରିବାକୁ ଚାହାଁନ୍ତି?',
  L10nKeys.screenTitle: 'ଶୀଘ୍ର ସ୍ମୃତି ଯାଞ୍ଚ',
  L10nKeys.screenIntro: 'ଆମେ ରୋଗୀଙ୍କ ବିଷୟରେ କିଛି ଛୋଟ ପ୍ରଶ୍ନ ପଚାରିବୁ। ଗତ କିଛି ମାସରେ ସେମାନେ କିପରି ଥିଲେ ସେ ବିଷୟରେ ଭାବନ୍ତୁ।',
  L10nKeys.screenNotSure: 'ନିଶ୍ଚିତ ନୁହେଁ',
  L10nKeys.screenFinish: 'ମୋ ଫଳାଫଳ ଦେଖ',
  L10nKeys.screenSkip: 'ଏବେ ଛାଡ଼',
  L10nKeys.screenResultBack: 'ହେଲା',
  L10nKeys.screenCheckAgain: 'ଆଉ ଥରେ ଯାଞ୍ଚ କର',
  L10nKeys.screenStartCheckup: 'ଯାଞ୍ଚ ଆରମ୍ଭ କର',
  L10nKeys.screenSkipped: 'ଯାଞ୍ଚ ଛାଡ଼ି ଦିଆଗଲା',
  L10nKeys.screenStatusGood: 'ସବୁ ଠିକ୍ ଦେଖାଯାଉଛି',
  L10nKeys.screenStatusGoodBody: 'କୌଣସି ବଡ଼ ଚିନ୍ତା ଦେଖାଗଲା ନାହିଁ। ଦୈନନ୍ଦିନ କାର୍ଯ୍ୟ କରିଚାଲ, ଏବଂ କିଛି ବଦଳିଲେ ଯେକୌଣସି ସମୟରେ ଆଉ ଥରେ ଯାଞ୍ଚ କରିପାରିବ।',
  L10nKeys.screenStatusWatch: 'କିଛି ପରିବର୍ତ୍ତନ ଦେଖାଗଲା',
  L10nKeys.screenStatusWatchBody: 'ଭୁଲିଯିବାର କିଛି ମୁହୂର୍ତ୍ତ ଦେଖାଗଲା। ବୟସ ସହିତ ଏହା ସାଧାରଣ, କିନ୍ତୁ ଧ୍ୟାନ ରଖ ଏବଂ ପରବର୍ତ୍ତୀ ଡାକ୍ତର ଭେଟରେ କୁହ।',
  L10nKeys.screenStatusDoctor: 'ଦୟାକରି ଯାଞ୍ଚ କରା',
  L10nKeys.screenStatusDoctorBody: 'କିଛି ସଙ୍କେତ ଦେଖାଗଲା ଯାହା ଉପରେ ଧ୍ୟାନ ଦେବାର ଆବଶ୍ୟକତା ଥାଇପାରେ। ଦୟାକରି ଏହାକୁ ଡାକ୍ତର କିମ୍ବା କ୍ଲିନିକକୁ ଜଣା ଯାହାଫଳରେ ସେମାନେ ସାହାଯ୍ୟ କରିପାରିବେ।',
  L10nKeys.screenRarely: 'ବିରଳ',
  L10nKeys.screenSometimes: 'ବେଳେବେଳେ',
  L10nKeys.screenFrequently: 'ଅଧିକାଂଶ ସମୟ',
  L10nKeys.screenVeryFrequently: 'ବହୁତ ଅଧିକ',
  L10nKeys.screenQ01: 'ସେମାନଙ୍କର ସାମ୍ପ୍ରତିକ ଘଟଣା ମନେ ରଖିବାରେ ଅସୁବିଧା ହୁଏ କି?',
  L10nKeys.screenQ02: 'ସେମାନେ ସମାନ ପ୍ରଶ୍ନ କିମ୍ବା କାହାଣୀ ବାରମ୍ବାର କୁହନ୍ତି କି?',
  L10nKeys.screenQ03: 'ସେମାନେ ପରିଚିତ ଲୋକଙ୍କ ନାମ ଭୁଲିଯାଆନ୍ତି କି?',
  L10nKeys.screenQ04: 'ସେମାନଙ୍କର ପରିଚିତ ମୁହଁ ଚିହ୍ନିବାରେ ଅସୁବିଧା ହୁଏ କି?',
  L10nKeys.screenQ05:
      'ସେମାନେ ନିଯୁକ୍ତି ସମୟ କିମ୍ବା ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଘଟଣା ଭୁଲିଯାଆନ୍ତି କି?',
  L10nKeys.screenQ06: 'ସେମାନଙ୍କର ସଠିକ୍ ଶବ୍ଦ ପାଇବାରେ ଅସୁବିଧା ହୁଏ କି?',
  L10nKeys.screenQ07: 'ସେମାନେ କେଉଁଠାରେ ଅଛନ୍ତି ବୋଲି ଭ୍ରମିତ ହୁଅନ୍ତି କି?',
  L10nKeys.screenQ08:
      'ସେମାନଙ୍କୁ ଦୈନନ୍ଦିନ କାର୍ଯ୍ୟ ପାଇଁ ମନେ ପକାଇବାର ଆବଶ୍ୟକତା ହୁଏ କି?',
  L10nKeys.screenQ09: 'ସେମାନଙ୍କର ଔଷଧ ସମ୍ଭାଳିବାରେ ଅସୁବିଧା ହୁଏ କି?',
  L10nKeys.screenQ10: 'ସେମାନେ ଭ୍ରମିତ ହେଲେ ଚିନ୍ତିତ କିମ୍ବା ବିରକ୍ତ ହୁଅନ୍ତି କି?',
  L10nKeys.screenQ11: 'ସେମାନଙ୍କର କଥାବାର୍ତ୍ତା ବୁଝିବାରେ ଅସୁବିଧା ହୁଏ କି?',
  L10nKeys.screenQ12: 'ସେମାନଙ୍କର ପରିଚିତ କାର୍ଯ୍ୟ ଶେଷ କରିବାରେ ଅସୁବିଧା ହୁଏ କି?',
  L10nKeys.screenQ13: 'ସେମାନେ ଭୁଲିଯାଆନ୍ତି କି ଦୈନନ୍ଦିନ ଜିନିଷ କେଉଁଠାରେ ରଖାଯାଇଛି?',
  L10nKeys.screenQ14: 'ସେମାନଙ୍କର ନିର୍ଦ୍ଦେଶ ମନେ ରଖିବାରେ ଅସୁବିଧା ହୁଏ କି?',
  L10nKeys.screenQ15: 'ସେମାନଙ୍କର ବହୁ-ପଦକ୍ଷେପ କାର୍ଯ୍ୟ କରିବାରେ ଅସୁବିଧା ହୁଏ କି?',

  L10nKeys.careDashboardSubtitle: 'ପରିବାର ଯତ୍ନ',
  L10nKeys.careSosLive: 'ଲାଇଭ ଆଲର୍ଟ',
  L10nKeys.careSosRespondedBy: '{name} ଉତ୍ତର ଦେଇଛନ୍ତି',
  L10nKeys.careLinkTitle: 'ପରିବାର ସଦସ୍ୟଙ୍କ ସହିତ ସଂଯୋଗ କରନ୍ତୁ',
  L10nKeys.careLinkBody: 'ଆପଣଙ୍କ ପ୍ରିୟଜନଙ୍କ ଫୋନରେ ଦେଖାଯାଉଥିବା 6-ଅକ୍ଷରର ପାରିବାରିକ କୋଡ ପଚାରି ପରେ ସଂଯୋଗ କରନ୍ତୁ।',
  L10nKeys.careLinkCode: 'ପାରିବାରିକ କୋଡ',
  L10nKeys.careLinkCodeHint: 'ଉଦା. A1B2C3',
  L10nKeys.careLinkConnect: 'ସଂଯୋଗ',
  L10nKeys.careLinkDone: 'ସଂଯୋଗ ହେଲା',
  L10nKeys.careLinkSuccess:
      '{name} ଙ୍କ ସହିତ ସଂଯୋଗ ହେଲା! ସ୍ମୃତି ଏବଂ ଆଲର୍ଟ ବର୍ତ୍ତମାନ ସିଙ୍କ ହେବ।',
  L10nKeys.careLinkFailed:
      'ସଂଯୋଗ ହୋଇପାରିନାହିଁ। ଦୟାକରି କୋଡ ଯାଞ୍ଚ କରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।',
  L10nKeys.careTrendsTitle: 'AI ଧାରା',
  L10nKeys.careTrendsBody: 'କାର୍ଯ୍ୟ ପ୍ରକାର ଅନୁଯାୟୀ ଦୈନିକ ସଠିକତା',
  L10nKeys.careTrendsNoData: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାର୍ଯ୍ୟ ନାହିଁ — ଧାରା ଦେଖିବାକୁ ଗୋଟିଏ ବ୍ୟାୟାମ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ।',
  L10nKeys.careAiDifficulty: 'ସ୍ୱୟଂ ସମନ୍ୱିତ କଷ୍ଟ',
  L10nKeys.careAiAccuracy: 'ମଡେଲ ସଠିକତା',
  L10nKeys.careAiRealSessions: 'ପ୍ରକୃତ ଅଧିବେଶନ',
  L10nKeys.careAiDemoSessions: 'ଡେମୋ ଅଧିବେଶନ',
  L10nKeys.careNavGames: 'ଖେଳ',
  L10nKeys.careNavRoutine: 'ରୁଟିନ',
  L10nKeys.careGreetSubtitle: 'ଆଜି {name} କେମିତି ଅଛନ୍ତି, ଏଠାରେ ଦେଖନ୍ତୁ।',
  L10nKeys.careNotifEmpty: 'କୌଣସି ନୂଆ ସୂଚନା ନାହିଁ',
  L10nKeys.careWellnessScore: 'ଜ୍ଞାନାତ୍ମକ ସୁସ୍ଥତା ସ୍କୋର',
  L10nKeys.careStatusStable: 'ସ୍ଥିର',
  L10nKeys.careStatusAttention: 'ଧ୍ୟାନ ଆବଶ୍ୟକ',
  L10nKeys.careLastSynced: 'ଶେଷ ସିଙ୍କ {time}',
  L10nKeys.careMinAgo: '{n} ମିନିଟ ପୂର୍ବେ',
  L10nKeys.careGamesWeek: 'ଏହି ସପ୍ତାହର ଖେଳ',
  L10nKeys.careRoutineCompletion: 'ରୁଟିନ ସମ୍ପୂର୍ଣ୍ଣ',
  L10nKeys.careCurrentStreak: 'ବର୍ତ୍ତମାନର ସ୍ଟ୍ରିକ',
  L10nKeys.careMoodCheckins: 'ମୁଡ ଚେକ୍-ଇନ',
  L10nKeys.careDayUnit: 'ଦିନ',
  L10nKeys.careDaysUnit: 'ଦିନ',
  L10nKeys.careActivityTitle: 'ସାପ୍ତାହିକ କାର୍ଯ୍ୟକଳାପ',
  L10nKeys.careWeekly: 'ସାପ୍ତାହିକ',
  L10nKeys.careMonthly: 'ମାସିକ',
  L10nKeys.careNoActivityWeek:
      'ଏହି ସପ୍ତାହରେ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାର୍ଯ୍ୟକଳାପ ରେକର୍ଡ ହୋଇନାହିଁ।',
  L10nKeys.careMoodTitle: 'ମୁଡ',
  L10nKeys.careMoodHappy: 'ଖୁସି',
  L10nKeys.careMoodCalm: 'ଶାନ୍ତ',
  L10nKeys.careMoodNeutral: 'ନିରପେକ୍ଷ',
  L10nKeys.careMoodLow: 'କମ',
  L10nKeys.careMood7Days: 'ଗତ ୭ ଦିନ',
  L10nKeys.careMoodInsight: 'ଏହି ସପ୍ତାହରେ {name} ଅଧିକାଂଶ ସମୟ ଶାନ୍ତ ରହିଛନ୍ତି, ଗତ ଦୁଇ ଦିନରେ ସାମାନ୍ୟ ହ୍ରାସ ଘଟିଛି।',
  L10nKeys.careMoodNoData: 'ଏହି ସପ୍ତାହରେ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ମୁଡ ଚେକ୍-ଇନ ନାହିଁ।',
  L10nKeys.careSkillsTitle: 'ଜ୍ଞାନାତ୍ମକ ଦକ୍ଷତା',
  L10nKeys.careSkillMemory: 'ସ୍ମୃତି',
  L10nKeys.careSkillAttention: 'ଧ୍ୟାନ',
  L10nKeys.careSkillLanguage: 'ଭାଷା',
  L10nKeys.careSkillReasoning: 'ତର୍କ',
  L10nKeys.careSkillProcessing: 'ପ୍ରକ୍ରିୟାକରଣ ଗତି',
  L10nKeys.careInsightToday: 'ଆଜିର ସୂଚନା',
  L10nKeys.careInsightBody: 'ରୋବର୍ଟ ସକାଳର ରୁଟିନ ପରେ ସ୍ମୃତି କାର୍ଯ୍ୟକଳାପରେ ନିରନ୍ତର ରହିଛନ୍ତି। ଗତ ଦୁଇ ଦିନରେ ତାଙ୍କର ମୁଡ ସାମାନ୍ୟ କମିଛି।',
  L10nKeys.careInsightBodyReal: 'ଏହି ସପ୍ତାହରେ {name} {count}ଟି ଜ୍ଞାନାତ୍ମକ ଅଧିବେଶନ ସମ୍ପୂର୍ଣ୍ଣ କରିଛନ୍ତି (ଲକ୍ଷ୍ୟ {goal}) ଏବଂ {streak} ଦିନର ସ୍ଟ୍ରିକ ବଜାୟ ରଖିଛନ୍ତି।',
  L10nKeys.careViewDetails: 'ବିବରଣୀ ଦେଖନ୍ତୁ',
  L10nKeys.careInsightDisclaimer:
      'ଏହା ତଥ୍ୟରୁ ଏକ ସୌମ୍ୟ ପର୍ଯ୍ୟବେକ୍ଷଣ — ଚିକିତ୍ସା ନିର୍ଣ୍ଣୟ ନୁହେଁ।',
  L10nKeys.careAttentionTitle: 'ଆପଣଙ୍କ ଧ୍ୟାନ ଆବଶ୍ୟକ',
  L10nKeys.careAttentionEmpty: 'ବର୍ତ୍ତମାନ ଆପଣଙ୍କ ଧ୍ୟାନ ଆବଶ୍ୟକ କିଛି ନାହିଁ।',
  L10nKeys.careAlertSos: '{name} SOS ବଟନ ଦବାଇଛନ୍ତି',
  L10nKeys.careAlertRoutineMissed: 'ଗତକାଲି ରୁଟିନ ମିସ୍ ହୋଇଥିଲା',
  L10nKeys.careAlertMoodDown: 'ଗତ ଦୁଇ ଦିନରେ ମୁଡ ହ୍ରାସ ପାଇଛି',
  L10nKeys.careAlertSessionPending:
      'ଆଜି ଜ୍ଞାନାତ୍ମକ ଅଧିବେଶନ ସମ୍ପୂର୍ଣ୍ଣ ହୋଇନାହିଁ',
  L10nKeys.careAlertSeverityHigh: 'ଉଚ୍ଚ',
  L10nKeys.careAlertSeverityMedium: 'ମଧ୍ୟମ',
  L10nKeys.careAlertSeverityLow: 'ନିମ୍ନ',
  L10nKeys.careWeeklySummary: 'ସାପ୍ତାହିକ ସାରାଂଶ',
  L10nKeys.careSessionsCompleted: 'ସମ୍ପୂର୍ଣ୍ଣ ଅଧିବେଶନ',
  L10nKeys.careAvgSessionDuration: 'ହାରାହାରି ଅଧିବେଶନ ଅବଧି',
  L10nKeys.careRoutineAdherence: 'ରୁଟିନ ଅନୁସରଣ',
  L10nKeys.careMoodTrend: 'ମୁଡ ପ୍ରବୃତ୍ତି',
  L10nKeys.careMoodTrendSlightlyDown: 'ସାମାନ୍ୟ କମ',
  L10nKeys.careMoodTrendStable: 'ସ୍ଥିର',
  L10nKeys.careMoodTrendUp: 'ଉନ୍ନତି ହେଉଛି',
  L10nKeys.careVsLastWeek: 'ଗତ ସପ୍ତାହ ତୁଳନାରେ',
  L10nKeys.careSyncedJustNow: 'ଏବେ ମାତ୍ର ସିଙ୍କ ହେଲା',
  L10nKeys.careOfflineWaiting:
      'ଅଫଲାଇନ · {count}ଟି କାର୍ଯ୍ୟକଳାପ ସିଙ୍କ ପାଇଁ ଅପେକ୍ଷାରେ',
  L10nKeys.careComingSoon: 'ଶୀଘ୍ର ଆସୁଛି',
  L10nKeys.careHomeSoon: '{name}ଙ୍କ ଦିନର ଏକ ସଂକ୍ଷିପ୍ତ ଆଭାସ ଏଠାରେ ଦେଖାଯିବ।',
  L10nKeys.careGamesSoon: 'ଖେଳ ଏବଂ ଅଧିବେଶନ ଇତିହାସ ଏଠାରେ ଦେଖାଯିବ।',
  L10nKeys.careRoutineSoon: 'ରୋଗୀଙ୍କ ଦୈନନ୍ଦିନ ରୁଟିନ ଏଠାରେ ଦେଖାଯିବ।',
  L10nKeys.careProfileSoon: 'ଯତ୍ନକର୍ତ୍ତାଙ୍କ ପ୍ରୋଫାଇଲ ଏବଂ ସେଟିଂସ ଏଠାରେ ଦେଖାଯିବ।',
  L10nKeys.serverPairingTitle: 'ପାରିବାରିକ କୋଡ',
  L10nKeys.serverPairingBody: 'ଏହି କୋଡ କୌଣସି ଯତ୍ନକର୍ତ୍ତାଙ୍କ ସହିତ ଅଂଶୀଦାର କରନ୍ତୁ ଯାହା ଫଳରେ ସେମାନେ ଆପଣଙ୍କ ସହିତ ସଂଯୋଗ ହୋଇପାରିବେ।',
  L10nKeys.serverUnlinked: 'ସର୍ଭର ସହିତ ସଂଯୋଗ ନାହିଁ',
  L10nKeys.serverLinked: 'ସର୍ଭର ସହିତ ସଂଯୋଗ ହୋଇଛି',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
