import '../l10n_keys.dart';

/// Kannada dictionary (machine-assisted; native review recommended).
const Map<String, String> stringsKn = {
  L10nKeys.appName: 'Companio',
  // How to play (tutorials)
  L10nKeys.tutListen: 'Listen',
  L10nKeys.tutPairs1: 'Watch the pictures carefully. Soon they will be hidden.',
  L10nKeys.tutPairs2: 'Tap a card to turn it around.',
  L10nKeys.tutPairs3: 'Find two of the very same picture.',
  L10nKeys.tutSeq1: 'Watch the cards light up one by one.',
  L10nKeys.tutSeq2: 'Remember the order.',
  L10nKeys.tutSeq3: 'Tap the cards in the same order.',
  L10nKeys.tutRecall1: 'Read or listen to the question.',
  L10nKeys.tutRecall2: 'Tap the answer you remember.',
  L10nKeys.tutRecall3: 'Choose one answer to finish.',
  L10nKeys.tutMatch1: 'Look at the pictures on the left.',
  L10nKeys.tutMatch2: 'Tap the matching picture on the right.',
  L10nKeys.tutMatch3: 'Match every pair to finish.',
  L10nKeys.tutNoFail: 'Take your time. There is no failing.',
  L10nKeys.tagline: 'ನಿಮ್ಮ ನೆನಪುಗಳ ಒಡನಾಡಿ',
  L10nKeys.back: 'ಹಿಂದೆ',
  L10nKeys.next: 'ಮುಂದೆ',
  L10nKeys.continueText: 'ಮುಂದುವರಿಸಿ',
  L10nKeys.skip: 'ಬಿಟ್ಟುಬಿಡಿ',
  L10nKeys.done: 'ಮುಗಿಯಿತು',
  L10nKeys.cancel: 'ರದ್ದು',
  L10nKeys.yes: 'ಹೌದು',
  L10nKeys.no: 'ಇಲ್ಲ',
  L10nKeys.save: 'ಉಳಿಸಿ',
  L10nKeys.close: 'ಮುಚ್ಚಿ',
  L10nKeys.retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
  L10nKeys.add: 'ಸೇರಿಸಿ',
  L10nKeys.edit: 'ಬದಲಿಸಿ',
  L10nKeys.remove: 'ತೆಗೆದುಹಾಕಿ',
  L10nKeys.search: 'ಹುಡುಕಿ',
  L10nKeys.today: 'ಇಂದು',
  L10nKeys.offline: 'ಆಫ್‌ಲೈನ್',
  L10nKeys.online: 'ಆನ್‌ಲೈನ್',

  L10nKeys.goodMorning: 'ಶುಭೋದಯ',
  L10nKeys.goodAfternoon: 'ನಮಸ್ಕಾರ',
  L10nKeys.goodEvening: 'ಶುಭ ಸಂಜೆ',
  L10nKeys.goodNight: 'ಶುಭ ರಾತ್ರಿ',

  L10nKeys.navHome: 'ಮುಖಪುಟ',
  L10nKeys.navGarden: 'ತೋಟ',
  L10nKeys.navActivities: 'ಚಟುವಟಿಕೆಗಳು',
  L10nKeys.navMemories: 'ನೆನಪುಗಳು',
  L10nKeys.navProfile: 'ಪ್ರೊಫೈಲ್',
  L10nKeys.navMystery: 'ಇಂದಿನ ನೆನಪು',

  L10nKeys.onboardingWelcomeTitle: 'ನಿಮ್ಮ ನೆನಪುಗಳ ಮೃದು ಒಡನಾಡಿ',
  L10nKeys.onboardingWelcomeBody: 'ಮೈಂಡ್ಕೇರ್ ಎನ್ಇಆರ್ ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆಯೇ ನೆನಪಿಟ್ಟುಕೊಳ್ಳಲು, ಆಡಲು, ಕುಟುಂಬದೊಂದಿಗೆ ಸಂಪರ್ಕದಲ್ಲಿರಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
  L10nKeys.onboardingNameTitle: 'ನಿಮ್ಮನ್ನು ಏನೆಂದು ಕರೆಯಲಿ?',
  L10nKeys.onboardingNameHint: 'ನಿಮ್ಮ ಹೆಸರು',
  L10nKeys.onboardingRegionTitle: 'ನಿಮ್ಮ ಮನೆ ಎಲ್ಲಿದೆ?',
  L10nKeys.onboardingRegionHint: 'ನಗರ ಅಥವಾ ಊರು',
  L10nKeys.onboardingRegionList: 'ಗುವಾಹಟಿ, ಸಿಲ್ಚಾರ್, ಶಿಲ್ಲಾಂಗ್, ಅಗರ್ತಲಾ, ಇಂಫಾಲ್, ಐಝಾಲ್, ಇಟಾನಗರ್, ಕೊಹಿಮಾ, ಗಾಂಗ್ಟಕ್, ಡಿಬ್ರುಗಢ್, ಜೋರ್ಹಾಟ್, ನಿಮ್ಮ ನಗರ',
  L10nKeys.onboardingLanguageTitle: 'ನಿಮಗೆ ಯಾವ ಭಾಷೆ ಇಷ್ಟವಾಗುತ್ತದೆ?',
  L10nKeys.onboardingLanguageBody: 'ಇದನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಿಸಬಹುದು.',
  L10nKeys.onboardingFamilyTitle: 'ಕುಟುಂಬ ಯಾರು?',
  L10nKeys.onboardingFamilyBody: 'ನಿಮ್ಮ ಆಪ್ತರನ್ನು ಸೇರಿಸಿ. ಅವರ ಫೋಟೋ ಮತ್ತು ಧ್ವನಿಯನ್ನು ಮೃದು ನೆನಪುಗಳಾಗಿ ತೋರಿಸುತ್ತೇವೆ.',
  L10nKeys.onboardingAddFamily: 'ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ',
  L10nKeys.onboardingEmergencyTitle: 'ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ಯಾರನ್ನು ಕರೆಯಲಿ?',
  L10nKeys.onboardingEmergencyBody: 'SOS ಬಟನ್ ಒತ್ತಿದರೆ ಮೈಂಡ್ಕೇರ್ ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ತಿಳಿಸುತ್ತದೆ, ತುರ್ತು ಸೇವೆಗಳಿಗಲ್ಲ.',
  L10nKeys.onboardingEmergencyName: 'ಹೆಸರು',
  L10nKeys.onboardingEmergencyPhone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
  L10nKeys.onboardingEmergencyRelation: 'ಸಂಬಂಧ (ಮಗಳು, ಮಗ…)',
  L10nKeys.onboardingDoneTitle: 'ನಿಮ್ಮ ತೋಟ ಸಿದ್ಧವಾಗಿದೆ!',
  L10nKeys.onboardingDoneBody: 'ಸಣ್ಣ ಚಟುವಟಿಕೆಗಳನ್ನು ಮುಗಿಸಿ, ತೋಟ ಬೆಳೆಯುವುದನ್ನು ನೋಡಿ. ನಾವು ನಿಮ್ಮೊಂದಿಗಿದ್ದೇವೆ.',
  L10nKeys.onboardingStart: 'ನನ್ನ ತೋಟ ಪ್ರಾರಂಭಿಸಿ',

  L10nKeys.homeWhatsGrowing: 'ಇಂದು ಏನು ಬೆಳೆಯುತ್ತಿದೆ?',
  L10nKeys.homeTodayActivity: 'ಇಂದಿನ ಸಣ್ಣ ಚಟುವಟಿಕೆ',
  L10nKeys.homeActivityDuration: 'ಸುಮಾರು ೩ ನಿಮಿಷ',
  L10nKeys.homeMinutes: 'ನಿಮಿಷ',
  L10nKeys.homeMemoryOfDay: 'ಇಂದಿನ ನೆನಪು',
  L10nKeys.homeMemoryLocked: 'ಒಂದು ವಿಶೇಷ ನೆನಪು ಕಾಯುತ್ತಿದೆ…',
  L10nKeys.homeMemoryUnlocked: 'ಒಂದು ನೆನಪು ತೆರೆಯಿತು!',
  L10nKeys.homeContinueActivity: 'ಚಟುವಟಿಕೆ ಮುಂದುವರಿಸಿ',
  L10nKeys.homeFamilyMemory: 'ನಿಮ್ಮ ಕುಟುಂಬದಿಂದ',
  L10nKeys.homeFamilyMemoryEmpty: 'ಕುಟುಂಬದ ನೆನಪುಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಬಹುದು.',
  L10nKeys.homeSos: 'ಸಹಾಯ ಬೇಕಿದೆ',
  L10nKeys.homeSosSubtitle: 'ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ಕುಟುಂಬವನ್ನು ಸಂಪರ್ಕಿಸಿ',
  L10nKeys.homeGardenPreview: 'ನಿಮ್ಮ ತೋಟ',
  L10nKeys.homeEngine: 'ಮೈಂಡ್ಕೇರ್ ಒಡನಾಡಿ',
  L10nKeys.homeEngineReady: 'ನಿಮ್ಮ ಸಹಾಯಕ ಸಿದ್ಧನಿದ್ದಾನೆ.',
  L10nKeys.homeWelcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ! ತೋಟ ಮುಂದುವರಿಸೋಣ. 🌸',
  L10nKeys.homeNoActivity: 'ಇಂದು ಯಾವ ಚಟುವಟಿಕೆಯೂ ಇಲ್ಲ',
  L10nKeys.homeNoActivityBody:
      'ಸ್ವಲ್ಪ ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ — ಅಥವಾ ಇಷ್ಟದ ಚಟುವಟಿಕೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ. 🌻',

  L10nKeys.gardenTitle: 'ನನ್ನ ನೆನಪುಗಳ ತೋಟ',
  L10nKeys.gardenSectionAll: 'ಎಲ್ಲಾ',
  L10nKeys.gardenSectionFamily: 'ಕುಟುಂಬ',
  L10nKeys.gardenSectionChildhood: 'ಬಾಲ್ಯ',
  L10nKeys.gardenSectionPlaces: 'ಸ್ಥಳಗಳು',
  L10nKeys.gardenSectionFestivals: 'ಹಬ್ಬಗಳು',
  L10nKeys.gardenEmpty: 'ನಿಮ್ಮ ತೋಟ ಇದೀಗ ಪ್ರಾರಂಭವಾಗಿದೆ',
  L10nKeys.gardenEmptyBody: 'ಮೊದಲ ಚಟುವಟಿಕೆ ಮುಗಿಸಿ, ಇಲ್ಲಿ ಬೀಜ ನೆಡಲಾಗುತ್ತದೆ.',
  L10nKeys.gardenPoints: 'ಅಂಕಗಳು',
  L10nKeys.gardenLevel: 'ಹಂತ',
  L10nKeys.gardenSeed: 'ಬೀಜ',
  L10nKeys.gardenPlant: 'ಗಿಡ',
  L10nKeys.gardenFlower: 'ಹೂವು',
  L10nKeys.gardenTree: 'ಮರ',
  L10nKeys.gardenMilestone: 'ಘಟ್ಟ',
  L10nKeys.gardenGrowth: 'ಬೆಳೆಯುತ್ತಿದೆ',
  L10nKeys.gardenDidYouKnow:
      'ಪ್ರತಿ ಮುಗಿಯುವ ಚಟುವಟಿಕೆಯೂ ನಿಮ್ಮ ತೋಟವನ್ನು ಬೆಳೆಸುತ್ತದೆ.',
  L10nKeys.gardenPlantSeed: 'ಬೀಜ ನೆಡಿ',

  L10nKeys.activitiesTitle: 'ಚಟುವಟಿಕೆಗಳು',
  L10nKeys.activitiesToday: 'ಇಂದು',
  L10nKeys.activitiesLibrary: 'ಹೆಚ್ಚಿನ ಚಟುವಟಿಕೆಗಳು',
  L10nKeys.mainGamesTitle: 'ಪ್ರಮುಖ ಆಟಗಳು',
  L10nKeys.activitiesStart: 'ಪ್ರಾರಂಭಿಸಿ',
  L10nKeys.activitiesCompleted: 'ಮುಗಿದವು',
  L10nKeys.activitiesInProgress: 'ನಡೆಯುತ್ತಿವೆ',
  L10nKeys.activitiesNotStarted: 'ಸಿದ್ಧ',
  L10nKeys.activityYoureDone: 'ಅದ್ಭುತ!',
  L10nKeys.activityPraise: 'ತೋಟಕ್ಕೆ ಸ್ವಲ್ಪ ಜೀವ ನೀಡಿದ್ದೀರಿ. 🌱',
  L10nKeys.activityHint: 'ಸುಳಿವು ಬೇಕೇ?',
  L10nKeys.activityTryAgain: 'ಈ ನೆನಪನ್ನು ಮತ್ತೆ ನೋಡೋಣ',
  L10nKeys.activityOptionsHint: 'ನಿಮ್ಮ ಉತ್ತರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
  L10nKeys.activityTapToMatch: 'ಸರಿಹೊಂದುವ ಜೋಡಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
  L10nKeys.activityNext: 'ಮುಂದೆ',
  L10nKeys.activityFinish: 'ಮುಗಿಸಿ',
  L10nKeys.activityGroupLetsAgain: 'ಇದನ್ನು ಮತ್ತೆ ನೋಡೋಣ',
  L10nKeys.activityGroupTogether: 'ಇದನ್ನು ಒಟ್ಟಿಗೆ ಮಾಡೋಣ',
  L10nKeys.activityGreatJob: 'ಚೆನ್ನಾಗಿ ಮಾಡಿದ್ದೀರಿ!',
  L10nKeys.activityKitchen: 'ನನ್ನ ಅಡುಗೆಮನೆ',
  L10nKeys.activityShopping: 'ನನ್ನ ಅಂಗಡಿ',
  L10nKeys.activityMatching: 'ಜೋಡಿ ಹೊಂದಿಸಿ',
  L10nKeys.activitySequence: 'ಕ್ರಮದಲ್ಲಿ ಜೋಡಿಸಿ',
  L10nKeys.activityRecognition: 'ಇದು ಏನು?',
  L10nKeys.activityAssociation: 'ಏನು ಒಟ್ಟಿಗೆ ಹೋಗುತ್ತದೆ?',
  L10nKeys.activityRecall: 'ನೆನಪಿದೆಯೇ?',
  L10nKeys.activityAttention: 'ಹುಡುಕಿ',
  L10nKeys.activityDurationSuffix: 'ನಿಮಿಷ',
  L10nKeys.activityTodayDone: 'ಇಂದಿನ ಚಟುವಟಿಕೆ ಮುಗಿದಿದೆ',
  L10nKeys.activityTodayDoneBody:
      'ನಿಮ್ಮ ತೋಟ ಬೆಳೆಯಿತು. ನಾಳೆ ಒಂದು ನೆನಪು ಕಾಯುತ್ತಿದೆ.',
  L10nKeys.activityGardenGrew: 'ನಿಮ್ಮ ತೋಟ ಬೆಳೆಯಿತು!',
  L10nKeys.activityMemoryUnlocked: 'ಒಂದು ನೆನಪು ತೆರೆಯಿತು',
  L10nKeys.activityReadAloud: 'ಜೋರಾಗಿ ಓದಿ',

  L10nKeys.kitchenTitle: 'ಚಹಾ ಮಾಡೋಣ',
  L10nKeys.kitchenMakeChai: 'ಚಹಾ ತಯಾರಿಸುವುದು',
  L10nKeys.kitchenMakeChaiPrompt: 'ಹಂತಗಳನ್ನು ಸರಿಯಾದ ಕ್ರಮದಲ್ಲಿ ಆಯ್ಕೆ ಮಾಡಿ.',
  L10nKeys.kitchenSteps: 'ಹಂತಗಳು',
  L10nKeys.kitchenTapInOrder: 'ಹಂತಗಳನ್ನು ಸರಿಯಾದ ಕ್ರಮದಲ್ಲಿ ಆಯ್ಕೆ ಮಾಡಿ',
  L10nKeys.kitchenCorrectOrder: 'ಚೆನ್ನಾಗಿದೆ! ಚಹಾ ಸಿದ್ಧ!',
  L10nKeys.kitchenBreakfast: 'ಉಪಾಹಾರ ತಯಾರಿಸುವುದು',
  L10nKeys.kitchenBreakfastHint: 'ದಿನದ ತಾಜಾ ಪ್ರಾರಂಭ',
  L10nKeys.kitchenBreakfastPrompt: 'ಉಪಾಹಾರದ ಹಂತಗಳನ್ನು ಕ್ರಮದಲ್ಲಿ ಜೋಡಿಸಿ.',

  L10nKeys.shopTitle: 'ನನ್ನ ಅಂಗಡಿ',
  L10nKeys.shopGetMilkBread: 'ಬ್ರೆಡ್ ಮತ್ತು ಹಾಲು',
  L10nKeys.shopGetMilkBreadPrompt: '₹೧೦೦ ನಲ್ಲಿ ಹಾಲು ಮತ್ತು ಬ್ರೆಡ್ ಖರೀದಿಸಿ.',
  L10nKeys.shopBudget: 'ಬಜೆಟ್',
  L10nKeys.shopBasket: 'ನಿಮ್ಮ ಬುಟ್ಟಿ',
  L10nKeys.shopTotal: 'ಒಟ್ಟು',
  L10nKeys.shopWithinBudget: 'ಬಜೆಟ್ ಒಳಗೆ!',
  L10nKeys.shopOverBudget: 'ಬಜೆಟ್ ಮೀರಿದೆ — ಮತ್ತೆ ನೋಡಿ',
  L10nKeys.shopCheckout: 'ಮುಗಿಸಿ ಹಣ ಪಾವತಿಸಿ',
  L10nKeys.shopBuy: 'ಬುಟ್ಟಿಗೆ ಹಾಕಿ',
  L10nKeys.shopSell: 'ಹೊರತೆಗೆಯಿರಿ',
  L10nKeys.shopVeggies: 'ರಾತ್ರಿ ಊಟಕ್ಕೆ ತರಕಾರಿಗಳು',
  L10nKeys.shopVeggiesPrompt: '₹೬೦ ನಲ್ಲಿ ಆಲೂಗಡ್ಡೆ ಮತ್ತು ಈರುಳ್ಳಿ ಖರೀದಿಸಿ.',
  L10nKeys.recKitchenItem: 'ಇದು ಯಾವುದು?',
  L10nKeys.recKitchenItemPrompt:
      'ಮಾರುಕಟ್ಟೆಯಿಂದ ಸಾಮಾನು ತರಲು ಯಾವುದನ್ನು ಬಳಸುತ್ತೇವೆ?',
  L10nKeys.recCurrency: 'ಸ್ವಲ್ಪ ಹಣ',
  L10nKeys.recCurrencyPrompt: 'ಯಾವ ನೋಟ್ ₹೨೦?',
  L10nKeys.matchFestival: 'ಹಬ್ಬ ಹೊಂದಿಸಿ',
  L10nKeys.matchFestivalPrompt:
      'ಪ್ರತಿ ಹಬ್ಬವನ್ನು ಅದರ ವಿಶೇಷ ಖಾದ್ಯದೊಂದಿಗೆ ಹೊಂದಿಸಿ.',
  L10nKeys.matchObjectUse: 'ಜೋಡಿ ಹೊಂದಿಸಿ',
  L10nKeys.matchObjectUsePrompt: 'ಪ್ರತಿ ವಸ್ತುವನ್ನು ಬಳಕೆಯ ಸಮಯದೊಂದಿಗೆ ಹೊಂದಿಸಿ.',
  L10nKeys.seqMorning: 'ಬೆಳಿಗ್ಗಿನ ದಿನಚರಿ',
  L10nKeys.seqMorningPrompt: 'ನಿಮ್ಮ ಬೆಳಿಗ್ಗಿನ ದಿನಚರಿಯನ್ನು ಕ್ರಮದಲ್ಲಿ ಜೋಡಿಸಿ.',
  L10nKeys.seqRoute: 'ಬೆಳಿಗ್ಗಿನ ಪ್ರಯಾಣ',
  L10nKeys.seqRoutePrompt: 'ಮಾರುಕಟ್ಟೆಯವರೆಗಿನ ಪ್ರಯಾಣವನ್ನು ಕ್ರಮದಲ್ಲಿ ಜೋಡಿಸಿ.',
  L10nKeys.assoRegion: 'ಇಲ್ಲಿ ಏನಿದೆ?',
  L10nKeys.assoRegionPrompt: 'ಅಸ್ಸಾಂ ಯಾವುದಕ್ಕೆ ಪ್ರಸಿದ್ಧ?',
  L10nKeys.assoHarvest: 'ರುಚಿಯಾದ ಹಣ್ಣು',
  L10nKeys.assoHarvestPrompt: 'ಯಾವ ಹಣ್ಣನ್ನು ಬೇಸಿಗೆಯ ರಾಜ ಎನ್ನುತ್ತಾರೆ?',
  L10nKeys.attnVeg: 'ಕ್ಯಾರೆಟ್ ಹುಡುಕಿ',
  L10nKeys.attnVegPrompt: 'ಕ್ಯಾರೆಟ್ ಸಿಗುತ್ತದೆಯೇ?',
  L10nKeys.recallSong: 'ಒಂದು ಚಿರಪರಿಚಿತ ಹಾಡು',
  L10nKeys.recallSongPrompt: 'ಬಿಹುವಿನಲ್ಲಿ ನೃತ್ಯಮಾಡುವಾಗ ಯಾವ ಹಾಡು ನುಡಿಯುತ್ತದೆ?',
  L10nKeys.activityPairs: 'ಜೋಡಿ ಹುಡುಕಿ',
  L10nKeys.activitySequenceRecall: 'ಕ್ರಮವನ್ನು ನೆನಪಿಡಿ',
  L10nKeys.activityFindChanged: 'ಏನು ಬದಲಾಯಿತು?',
  L10nKeys.pairsFruits: 'ಮಾರುಕಟ್ಟೆಯ ಹಣ್ಣುಗಳು',
  L10nKeys.pairsKitchen: 'ಅಡುಗೆಮನೆಯ ವಸ್ತುಗಳು',
  L10nKeys.pairsRemember:
      'ಎಲ್ಲಾ ಕಾರ್ಡ್‌ಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ನೋಡಿ, ನಂತರ ಒಂದೇ ಜೋಡಿಯನ್ನು ಹುಡುಕಿ.',
  L10nKeys.pairsStart: 'ಕಾರ್ಡ್‌ಗಳನ್ನು ಮರೆಮಾಡಿ ಪ್ರಾರಂಭಿಸಿ',
  L10nKeys.pairsFound: 'ಜೋಡಿ ಸಿಕ್ಕಿತು!',
  L10nKeys.seqRecallItems: 'ದೈನಂದಿನ ವಸ್ತುಗಳು',
  L10nKeys.seqRecallNumbers: 'ಕ್ರಮದಲ್ಲಿ ಸಂಖ್ಯೆಗಳು',
  L10nKeys.seqRecallWatch:
      'ಕಾರ್ಡ್‌ಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ನೋಡಿ – ಪ್ರತಿಯೊಂದೂ ಕ್ರಮವಾಗಿ ಪ್ರಕಾಶಿಸುತ್ತದೆ.',
  L10nKeys.seqRecallRepeat: 'ಈಗ ನೀವು ನೋಡಿದ ಅದೇ ಕ್ರಮದಲ್ಲಿ ಕಾರ್ಡ್‌ಗಳನ್ನು ಒತ್ತಿ.',
  L10nKeys.changeMarket: 'ಹಣ್ಣುಗಳ ಬುಟ್ಟಿ',
  L10nKeys.changeFestival: 'ಹಬ್ಬದ ದೀಪಗಳು',
  L10nKeys.changeRemember: 'ಈ ಚಿತ್ರಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ನೆನಪಿಡಿ.',
  L10nKeys.changeFind: 'ಒಂದು ಚಿತ್ರ ಬದಲಾಗಿದೆ. ವಿಭಿನ್ನವಾದದನ್ನು ಹುಡುಕಿ.',
  L10nKeys.changeCorrect: 'ಭಲೇ! ಅದೇ ಬದಲಾಗಿತ್ತು.',

  L10nKeys.mysteryTitle: 'ಇಂದಿನ ವಿಶೇಷ ನೆನಪು',
  L10nKeys.mysteryLocked: 'ಒಂದು ವಿಶೇಷ ನೆನಪು ನಿಮಗಾಗಿ ಕಾಯುತ್ತಿದೆ…',
  L10nKeys.mysteryLockedBody:
      'ಇಂದು ೨–೩ ಸಣ್ಣ ಚಟುವಟಿಕೆ ಮಾಡಿ; ಅದು ತೆರೆಯಬಹುದು. ಏನಿರುತ್ತದೆ?',
  L10nKeys.mysteryUnlocked: 'ನಿಮ್ಮ ವಿಶೇಷ ನೆನಪು ಇಲ್ಲಿದೆ!',
  L10nKeys.mysteryUnlockedBody:
      'ಈ ನೆನಪು ನಿಮಗೆ ಮಾತ್ರ. ನಿಮ್ಮ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳಿ. 🌸',
  L10nKeys.mysteryCuriosity: 'ಇಂದು ಏನು ತೆರೆಯುತ್ತದೆ?',
  L10nKeys.mysteryOpen: 'ನೆನಪು ತೆರೆಯಿರಿ',

  L10nKeys.memoriesTitle: 'ನನ್ನ ನೆನಪುಗಳು',
  L10nKeys.memoriesEmpty: 'ಇನ್ನೂ ಯಾವ ನೆನಪೂ ಇಲ್ಲ',
  L10nKeys.memoriesEmptyBody: 'ಒಂದು ನೆನಪು ರಚಿಸಿ ಮತ್ತು ಅದಕ್ಕೆ ಫೋಟೋ, ವೀಡಿಯೊ, ಧ್ವನಿ ಅಥವಾ ಪಠ್ಯ ಸೇರಿಸಿ.',
  L10nKeys.memoriesFamily: 'ಕುಟುಂಬ',
  L10nKeys.memoriesPlaces: 'ಸ್ಥಳಗಳು',
  L10nKeys.memoriesFestivals: 'ಹಬ್ಬಗಳು',
  L10nKeys.memoriesChildhood: 'ಬಾಲ್ಯ',
  L10nKeys.memoriesKindPhoto: 'ಫೋಟೋ',
  L10nKeys.memoriesKindVoice: 'ಧ್ವನಿ ಸಂದೇಶ',
  L10nKeys.memoriesKindText: 'ಕಥೆ',
  L10nKeys.memoriesKindSound: 'ಧ್ವನಿ',
  L10nKeys.memoriesKindPlace: 'ಸ್ಥಳ',
  L10nKeys.memoriesAddedBy: 'ಸೇರಿಸಿದವರು',
  L10nKeys.memoriesWhoIsThis: 'ಇವರು ಯಾರು?',
  L10nKeys.memoriesPlayVoice: 'ಕೇಳಿ',
  L10nKeys.memoriesThisIsMe: 'ಇವನೇ ನಾನು',
  L10nKeys.memoriesNotMe: 'ನಾನಲ್ಲ',

  L10nKeys.profileTitle: 'ಪ್ರೊಫೈಲ್',
  L10nKeys.profileLanguage: 'ಆ್ಯಪ್ ಭಾಷೆ',
  L10nKeys.profileRegion: 'ನನ್ನ ಪ್ರದೇಶ',
  L10nKeys.profileVoiceLanguage: 'ಧ್ವನಿ ಭಾಷೆ',
  L10nKeys.profileVoicePrompts: 'ಮಾತನಾಡುವ ಸುಳಿವುಗಳು',
  L10nKeys.profileTextSize: 'ಅಕ್ಷರದ ಗಾತ್ರ',
  L10nKeys.profileReducedMotion: 'ಶಾಂತ ಹಲನ',
  L10nKeys.profileSoundEffects: 'ಧ್ವನಿ ಪರಿಣಾಮಗಳು',
  L10nKeys.profileFamily: 'ಕುಟುಂಬ',
  L10nKeys.profileContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
  L10nKeys.profileDemoMode: 'ಡೆಮೊ ಮೋಡ್',
  L10nKeys.profileReminders: 'ಜ್ಞಾಪನೆಗಳು',
  L10nKeys.profileNeedHelp: 'ಸಹಾಯ ಬೇಕೇ?',

  L10nKeys.remindersTitle: 'ಜ್ಞಾಪನೆಗಳು',
  L10nKeys.remindersEmpty: 'ಇನ್ನೂ ಜ್ಞಾಪನೆಗಳಿಲ್ಲ',
  L10nKeys.remindersNew: 'ಹೊಸ ಜ್ಞಾಪನೆ',
  L10nKeys.remindersTitleLabel: 'ಶೀರ್ಷಿಕೆ',
  L10nKeys.remindersDetailLabel: 'ವಿವರ (ಐಚ್ಛಿಕ)',
  L10nKeys.remindersTime: 'ಸಮಯ',
  L10nKeys.remindersDays: 'ದಿನಗಳು',
  L10nKeys.remindersEveryday: 'ಪ್ರತಿದಿನ',
  L10nKeys.remindersEnabled: 'ಸಕ್ರಿಯ',
  L10nKeys.remindersMedicine: 'ಔಷಧ',
  L10nKeys.remindersAppointment: 'ಭೇಟಿ',
  L10nKeys.remindersRoutine: 'ದಿನನಿತ್ಯದ ದಿನಚರಿ',

  L10nKeys.dayMon: 'ಸೋಮ',
  L10nKeys.dayTue: 'ಮಂಗಳ',
  L10nKeys.dayWed: 'ಬುಧ',
  L10nKeys.dayThu: 'ಗುರು',
  L10nKeys.dayFri: 'ಶುಕ್ರ',
  L10nKeys.daySat: 'ಶನಿ',
  L10nKeys.daySun: 'ರವಿ',

  L10nKeys.sosTitle: 'ತುರ್ತು ಸಹಾಯ',
  L10nKeys.sosExplain: 'ಒತ್ತಿ ಹಿಡಿಯಿರಿ. ಮೈಂಡ್ಕೇರ್ ನಿಮ್ಮ ತುರ್ತು ಸಂಪರ್ಕಗಳಿಗೆ ಒಬ್ಬೊಬ್ಬರಾಗಿ ತಿಳಿಸುತ್ತದೆ. ಇದು ತುರ್ತು ಸೇವೆ (೧೧೨ ಇತ್ಯಾದಿ) ಅಲ್ಲ.',
  L10nKeys.sosHold: 'ಸಹಾಯಕ್ಕಾಗಿ ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
  L10nKeys.sosHoldBody: 'ಒತ್ತಿ ಹಿಡಿಯಿರಿ…',
  L10nKeys.sosActiveTitle: 'ಸಹಾಯವನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ',
  L10nKeys.sosActiveBody: 'ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ತಿಳಿಸಲಾಗಿದೆ. ಸ್ಪಂದಿಸದಿದ್ದರೆ ಮುಂದಿನ ಸಂಪರ್ಕಕ್ಕೆ ಕರೆ ಮಾಡಲಾಗುತ್ತದೆ.',
  L10nKeys.sosContacting: 'ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ',
  L10nKeys.sosContactFamily: 'ಕುಟುಂಬವನ್ನು ಸಂಪರ್ಕಿಸಿ',
  L10nKeys.sosContacted: 'ಸಂಪರ್ಕವಾಯಿತು',
  L10nKeys.sosWaitingResponse: 'ಸ್ಪಂದನೆಗಾಗಿ ಕಾಯುವಿಕೆ…',
  L10nKeys.sosEscalating: 'ಮುಂದಿನ ವ್ಯಕ್ತಿಯನ್ನು ಸಂಪರ್ಕಿಸುವುದು…',
  L10nKeys.sosCancelled: 'ಸಹಾಯ ವಿನಂತಿ ರದ್ದಾಗಿದೆ',
  L10nKeys.sosCancelAction: 'ಸಹಾಯ ವಿನಂತಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ',
  L10nKeys.sosDone: 'ಮುಗಿಯಿತು',
  L10nKeys.sosHelpOnWay: 'ಬೇಗನೆ ಯಾರಾದರೂ ನಿಮ್ಮೊಂದಿಗಿರುತ್ತಾರೆ. 🧡',
  L10nKeys.sosNoContacts: 'ಇನ್ನೂ ತುರ್ತು ಸಂಪರ್ಕಗಳಿಲ್ಲ',
  L10nKeys.sosNoContactsBody: 'ದಯವಿಟ್ಟು ಕುಟುಂಬಕ್ಕೆ ತುರ್ತು ಸಂಪರ್ಕ ಸೇರಿಸಲು ಹೇಳಿ.',
  L10nKeys.sosAddContact: 'ಸಂಪರ್ಕ ಸೇರಿಸಿ',
  L10nKeys.sosDisclaimer: 'ಮೈಂಡ್ಕೇರ್ ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಸಂಪರ್ಕಗಳಿಗೆ ತಿಳಿಸುತ್ತದೆ. ಇದು ಅಧಿಕೃತ ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಬದಲಿಯಲ್ಲ.',
  L10nKeys.sosContactedPerson: 'ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಲಾಗಿದೆ',
  L10nKeys.sosEscalatedTo: 'ಮುಂದಿನ ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಲಾಗಿದೆ',
  L10nKeys.sosAcknowledged: 'ಕುಟುಂಬದ ಸದಸ್ಯ ಸ್ಪಂದಿಸಿದ್ದಾರೆ. ಸಹಾಯ ಬರಲಿದೆ.',
  L10nKeys.sosNotSilent: 'ಸಹಾಯ ಕಳುಹಿಸಲು ಆಗದಿದ್ದರೆ ನಾವೆಂದೂ ನಟಿಸುವುದಿಲ್ಲ.',
  L10nKeys.sosAlertNotDelivered:
      'ನಿಮ್ಮ ಸಂದೇಶ ಇನ್ನೂ ಕಳುಹಿಸಲಾಗಿಲ್ಲ. ಪ್ರಯತ್ನಿಸುತ್ತಲೇ ಇರುತ್ತೇವೆ.',

  L10nKeys.careTitle: 'ಆರೈಕೆದಾರ',
  L10nKeys.careDashboard: 'ಅವಲೋಕನ',
  L10nKeys.carePatients: 'ನನ್ನ ರೋಗಿಗಳು',
  L10nKeys.careMemories: 'ನೆನಪುಗಳು',
  L10nKeys.careContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
  L10nKeys.careSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  L10nKeys.careAddMemory: 'ನೆನಪು ಸೇರಿಸಿ',
  L10nKeys.careAddContact: 'ಸಂಪರ್ಕ ಸೇರಿಸಿ',
  L10nKeys.careEngagement: 'ಒಳಗೊಳ್ಳುವಿಕೆ',
  L10nKeys.careActivitiesWeek: 'ಈ ವಾರದ ಚಟುವಟಿಕೆಗಳು',
  L10nKeys.careGardenProgress: 'ತೋಟದ ಪ್ರಗತಿ',
  L10nKeys.careRecentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
  L10nKeys.careNoPatients: 'ಯಾವ ರೋಗಿಗಳೂ ಸಂಪರ್ಕವಾಗಿಲ್ಲ',
  L10nKeys.careNoPatientsBody:
      'ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಲು ಹೇಳಿ, ಅಥವಾ ರೋಗಿಯ ಪ್ರೊಫೈಲ್ ಸೇರಿಸಿ.',
  L10nKeys.careAddPatient: 'ರೋಗಿಯನ್ನು ಸೇರಿಸಿ',
  L10nKeys.carePerformanceNote: 'ಇತ್ತೀಚೆಗೆ ಈ ವ್ಯಕ್ತಿಯ ಚಟುವಟಿಕೆ ಸಾಧನೆ ಸಾಮಾನ್ಯ ಮಟ್ಟಕ್ಕಿಂತ ಸ್ವಲ್ಪ ಕಡಿಮೆ ಇದೆ.',
  L10nKeys.careUploadPhoto: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
  L10nKeys.careChoosePhoto: 'Choose a photo',
  L10nKeys.careReplacePhoto: 'Change photo',
  L10nKeys.careUploadVideo: 'Upload video',
  L10nKeys.careChooseVideo: 'Choose a video',
  L10nKeys.careReplaceVideo: 'Change video',
  L10nKeys.careRecording: 'Recording...',
  L10nKeys.careMicPermission: 'Microphone permission is needed to record a voice note.',
  L10nKeys.careVoiceRecordingFailed: 'Could not start the voice recording. Please try again.',
  L10nKeys.careMemoryKindVideo: 'Video',
  L10nKeys.camera: 'Camera',
  L10nKeys.gallery: 'Gallery',
  L10nKeys.careRecordVoice: 'ಧ್ವನಿ ರೆಕಾರ್ಡ್ ಮಾಡಿ',
  L10nKeys.careWriteMemory: 'ನೆನಪು ಬರೆಯಿರಿ',
  L10nKeys.careMemoryTitle: 'ಶೀರ್ಷಿಕೆ',
  L10nKeys.careMemoryCaption: 'ಶೀರ್ಷಿಕೆ ವಿವರಣೆ',
  L10nKeys.careMemoryRelation: 'ಇದರಲ್ಲಿ ಯಾರಿದ್ದಾರೆ? (ಸಂಬಂಧ)',
  L10nKeys.careMemoryCategory: 'ವರ್ಗ',
  L10nKeys.careContactName: 'ಹೆಸರು',
  L10nKeys.careContactPhone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
  L10nKeys.careContactPriority: 'ಕರೆ ಕ್ರಮ',
  L10nKeys.careContactRelation: 'ಸಂಬಂಧ',
  L10nKeys.careEscalationTimeout: 'ಮುಂದಿನ ಸಂಪರ್ಕಕ್ಕೆ ಮೊದಲು ನಿಮಿಷಗಳು',
  L10nKeys.careIncidentStatus: 'ಸ್ಥಿತಿ',
  L10nKeys.careAckSos: 'ನಾನು ಸ್ಪಂದಿಸುತ್ತಿದ್ದೇನೆ',
  L10nKeys.careResponding: 'ಸ್ಪಂದಿಸುತ್ತಿದ್ದಾರೆ',
  L10nKeys.careActiveAlerts: 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು',

  L10nKeys.syncSavingOffline: 'ಆಫ್‌ಲೈನ್',
  L10nKeys.syncSavingOfflineBody:
      'ನಿಮ್ಮ ಚಟುವಟಿಕೆಗಳು ಈ ಸಾಧನದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿವೆ.',
  L10nKeys.syncSynced: 'ಸಿಂಕ್ ಆಗಿದೆ',
  L10nKeys.syncInfo: 'ನಿಮ್ಮ ಮಾಹಿತಿ ಸಿಂಕ್ ಆಗಿದೆ.',
  L10nKeys.syncPending: 'ಸಿಂಕ್‌ಗಾಗಿ ಕಾಯುತ್ತಿದೆ',

  L10nKeys.errorGeneric: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
  L10nKeys.errorGenericBody:
      'ನಿಮ್ಮ ಪ್ರಗತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  L10nKeys.errorAudio: 'ಈ ಸಾಧನದಲ್ಲಿ ಧ್ವನಿ ಪ್ಲೇ ಆಗಲಿಲ್ಲ.',
  L10nKeys.errorPermission: 'ಇದಕ್ಕೆ ಸಾಧನದ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
  L10nKeys.errorNoInternetAction:
      'ಇಂಟರ್ನೆಟ್ ಅಗತ್ಯವಿಲ್ಲ — ಇದು ಮೊದಲೇ ಇಲ್ಲಿ ಉಳಿಯುತ್ತದೆ.',

  L10nKeys.demoWelcome: 'ಡೆಮೊ ನೋಡಿ',
  L10nKeys.demoExplain:
      'ನೀವು ನೋಡಲೆಂದು ಮಾದರಿ ಕುಟುಂಬ ಹಾಗೂ ನೆನಪುಗಳನ್ನು ಸೇರಿಸಲಾಗುತ್ತದೆ.',
  L10nKeys.demoLoad: 'ಡೆಮೊ ತೋಟವನ್ನು ಲೋಡ್ ಮಾಡಿ',

  L10nKeys.unitsPoints: 'ಅಂಕಗಳು',
  L10nKeys.teaserChai: 'ಚಹಾ ಮಾಡೋಣ.',
  L10nKeys.familiarityName: 'ಆಶಾ',
  L10nKeys.regionMap: 'ನನ್ನ ಪ್ರದೇಶ',
  L10nKeys.regionChoose: 'ನಿಮ್ಮ ಪ್ರದೇಶವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
  L10nKeys.regionIndia: 'ಭಾರತ',
  L10nKeys.importantMemory: 'ಮುಖ್ಯವಾದ ನೆನಪು',
  L10nKeys.growing: 'ಬೆಳೆಯುತ್ತಿದೆ',
  L10nKeys.blooming: 'ಅರಳುತ್ತಿದೆ',
  L10nKeys.mature: 'ಪರಿಪಕ್ವ',
  L10nKeys.noVoice: 'ಈ ಸಾಧನದಲ್ಲಿ ಧ್ವನಿ ಲಭ್ಯವಿಲ್ಲ.',
  L10nKeys.optional: 'ಐಚ್ಛಿಕ',

  L10nKeys.langChoose: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
  L10nKeys.langPrimary: 'ಮುಖ್ಯ',
  L10nKeys.langNorthEast: 'ಈಶಾನ್ಯ ಭಾರತ',
  L10nKeys.langMajor: 'ಭಾರತದ ಪ್ರಮುಖ ಭಾಷೆಗಳು',

  L10nKeys.authSignUpTitle: 'ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ',
  L10nKeys.authSignUpBody: 'ಈ ಮೈಂಡ್ಕೇರ್ ಪ್ರೊಫೈಲ್ ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ. ನೀವೇ ತೆರೆಯಬಲ್ಲಿರಿ ಎಂಬುದಕ್ಕೆ ಬಳಕೆದಾರ ಹೆಸರು ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ಇಡಿ.',
  L10nKeys.authLoginTitle: 'ಮರಳಿ ಸ್ವಾಗತ',
  L10nKeys.authLoginBody:
      'ನಿಮ್ಮ ತೋಟ ತೆರೆಯಲು ಬಳಕೆದಾರ ಹೆಸರು ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್‌ನಿಂದ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
  L10nKeys.authUsername: 'ಬಳಕೆದಾರ ಹೆಸರು',
  L10nKeys.authUsernameHint: 'ಉದಾ: ranu123',
  L10nKeys.authDisplayName: 'ನಿಮ್ಮ ಹೆಸರು',
  L10nKeys.authPassword: 'ಪಾಸ್‌ವರ್ಡ್',
  L10nKeys.authPasswordHint: 'ಕನಿಷ್ಠ ೬ ಅಕ್ಷರಗಳು',
  L10nKeys.authConfirmPassword: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
  L10nKeys.authRoleQuestion: 'ಈ ಪ್ರೊಫೈಲ್ ಯಾರಿಗಾಗಿ…',
  L10nKeys.authRolePatient: 'ನನಗಾಗಿ',
  L10nKeys.authRoleCaregiver: 'ಕುಟುಂಬದ ಸದಸ್ಯರಿಗಾಗಿ',
  L10nKeys.authCreate: 'ಖಾತೆ ರಚಿಸಿ',
  L10nKeys.authSignIn: 'ಸೈನ್ ಇನ್',
  L10nKeys.authSignOut: 'ಸೈನ್ ಔಟ್',
  L10nKeys.authAccount: 'ಖಾತೆ',
  L10nKeys.caregiverTitle: 'ಆರೈಕೆದಾರ',
  L10nKeys.caregiverNotLinked: 'ಇನ್ನೂ ಯಾವುದೇ ಆರೈಕೆದಾರ ಸಂಪರ್ಕಗೊಂಡಿಲ್ಲ',
  L10nKeys.authBadCredentials: 'ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್ ತಪ್ಪಾಗಿದೆ.',
  L10nKeys.authUsernameTaken: 'ಈ ಹೆಸರು ಈ ಸಾಧನದಲ್ಲಿ ಈಗಾಗಲೇ ಬಳಕೆಯಲ್ಲಿದೆ.',
  L10nKeys.authPasswordMismatch: 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಾಣಿಕೆಯಾಗುತ್ತಿಲ್ಲ.',
  L10nKeys.authUsernameShort: 'ಹೆಸರು ಕನಿಷ್ಠ ೩ ಅಕ್ಷರಗಳಾಗಿರಬೇಕು.',
  L10nKeys.authUsernameInvalid:
      'ಅಕ್ಷರ, ಅಂಕಿ, ಡಾಟ್, ಡ್ಯಾಶ್ ಅಥವಾ ಅಂಡರ್ಸ್ಕೋರ್ ಮಾತ್ರ ಬಳಸಿ.',
  L10nKeys.authPasswordShort: 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ ೬ ಅಕ್ಷರಗಳಾಗಿರಬೇಕು.',
  L10nKeys.authNameRequired: 'ದಯವಿಟ್ಟು ಹೆಸರು ನಮೂದಿಸಿ.',
  L10nKeys.authSignOutConfirm: 'ಈ ಪ್ರೊಫೈಲ್‌ನಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡಬೇಕೆ?',
  L10nKeys.screenTitle: 'ತ್ವರಿತ ಸ್ಮರಣಶಕ್ತಿ ಪರೀಕ್ಷೆ',
  L10nKeys.screenIntro: 'ರೋಗಿಯ ಬಗ್ಗೆ ಕೆಲವು ಚಿಕ್ಕ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳುತ್ತೇವೆ. ಕಳೆದ ಕೆಲವು ತಿಂಗಳುಗಳಲ್ಲಿ ಅವರು ಹೇಗಿದ್ದರು ಎಂದು ಯೋಚಿಸಿ.',
  L10nKeys.screenNotSure: 'ಖಚಿತವಿಲ್ಲ',
  L10nKeys.screenFinish: 'ನನ್ನ ಫಲಿತಾಂಶ ನೋಡಿ',
  L10nKeys.screenSkip: 'ಈಗ ಬೇಡ',
  L10nKeys.screenResultBack: 'ಮುಗಿಯಿತು',
  L10nKeys.screenCheckAgain: 'ಮತ್ತೆ ಪರೀಕ್ಷಿಸಿ',
  L10nKeys.screenStartCheckup: 'ಪರೀಕ್ಷೆ ಪ್ರಾರಂಭಿಸಿ',
  L10nKeys.screenSkipped: 'ಪರೀಕ್ಷೆ ಬಿಟ್ಟುಬಿಡಲಾಗಿದೆ',
  L10nKeys.screenStatusGood: 'ಎಲ್ಲವೂ ಚೆನ್ನಾಗಿದೆ',
  L10nKeys.screenStatusGoodBody: 'ಯಾವುದೇ ದೊಡ್ಡ ಕಾಳಜಿ ಕಂಡುಬಂದಿಲ್ಲ. ದೈನಂದಿನ ಚಟುವಟಿಕೆಗಳನ್ನು ಮುಂದುವರಿಸಿ, ಮತ್ತು ಏನಾದರೂ ಬದಲಾದರೆ ಯಾವಾಗಲೂ ಮತ್ತೆ ಪರೀಕ್ಷಿಸಬಹುದು.',
  L10nKeys.screenStatusWatch: 'ಕೆಲವು ಬದಲಾವಣೆಗಳು ಕಂಡುಬಂದಿವೆ',
  L10nKeys.screenStatusWatchBody: 'ಮರೆಯುವ ಕೆಲವು ಕ್ಷಣಗಳು ಕಂಡುಬಂದಿವೆ. ಇದು ವಯಸ್ಸಿಗೆ ಸಾಮಾನ್ಯ, ಆದರೆ ಗಮನವಿಡಿ ಮತ್ತು ಮುಂದಿನ ವೈದ್ಯರ ಭೇಟಿಯಲ್ಲಿ ಹೇಳಿ.',
  L10nKeys.screenStatusDoctor: 'ದಯವಿಟ್ಟು ಪರೀಕ್ಷೆ ಮಾಡಿಸಿಕೊಳ್ಳಿ',
  L10nKeys.screenStatusDoctorBody: 'ಗಮನ ಬೇಕಾಗಬಹುದಾದ ಕೆಲವು ಚಿಹ್ನೆಗಳು ಕಂಡುಬಂದಿವೆ. ಅವರು ಸಹಾಯ ಮಾಡಲು ಇವುಗಳನ್ನು ವೈದ್ಯರು ಅಥವಾ ಕ್ಲಿನಿಕ್ಗೆ ತಿಳಿಸಿ.',
  L10nKeys.screenRarely: 'ವಿರಳವಾಗಿ',
  L10nKeys.screenSometimes: 'ಕೆಲವೊಮ್ಮೆ',
  L10nKeys.screenFrequently: 'ಆಗಾಗ್ಗೆ',
  L10nKeys.screenVeryFrequently: 'ಬಹಳ ಆಗಾಗ್ಗೆ',
  L10nKeys.screenQ01:
      'ಇತ್ತೀಚಿನ ಘಟನೆಗಳನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',
  L10nKeys.screenQ02:
      'ಅವರು ಅದೇ ಪ್ರಶ್ನೆಗಳು ಅಥವಾ ಕಥೆಗಳನ್ನು ಪುನರಾವರ್ತಿಸುತ್ತಾರೆಯೇ?',
  L10nKeys.screenQ03: 'ಅವರು ಪರಿಚಿತ ಜನರ ಹೆಸರುಗಳನ್ನು ಮರೆಯುತ್ತಾರೆಯೇ?',
  L10nKeys.screenQ04: 'ಪರಿಚಿತ ಮುಖಗಳನ್ನು ಗುರುತಿಸಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',
  L10nKeys.screenQ05: 'ಅವರು ಭೇಟಿಗಳು ಅಥವಾ ಪ್ರಮುಖ ಘಟನೆಗಳನ್ನು ಮರೆಯುತ್ತಾರೆಯೇ?',
  L10nKeys.screenQ06: 'ಸರಿಯಾದ ಪದಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',
  L10nKeys.screenQ07: 'ಅವರು ಎಲ್ಲಿದ್ದಾರೆಂದು ಗೊಂದಲಕ್ಕೊಳಗಾಗುತ್ತಾರೆಯೇ?',
  L10nKeys.screenQ08: 'ದೈನಂದಿನ ಚಟುವಟಿಕೆಗಳಿಗೆ ಅವರಿಗೆ ನೆನಪಿಸಲು ಅಗತ್ಯವಿದೆಯೇ?',
  L10nKeys.screenQ09: 'ಔಷಧಿಗಳನ್ನು ನಿರ್ವಹಿಸಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',
  L10nKeys.screenQ10:
      'ಗೊಂದಲಕ್ಕೊಳಗಾದಾಗ ಅವರು ಆತಂಕಗೊಳ್ಳುತ್ತಾರೆಯೇ ಅಥವಾ ಸಿಟ್ಟಾಗುತ್ತಾರೆಯೇ?',
  L10nKeys.screenQ11: 'ಸಂಭಾಷಣೆಗಳನ್ನು ಅನುಸರಿಸಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',
  L10nKeys.screenQ12: 'ಪರಿಚಿತ ಕಾರ್ಯಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',
  L10nKeys.screenQ13: 'ದೈನಂದಿನ ವಸ್ತುಗಳು ಎಲ್ಲಿವೆ ಎಂಬುದನ್ನು ಅವರು ಮರೆಯುತ್ತಾರೆಯೇ?',
  L10nKeys.screenQ14: 'ಸೂಚನೆಗಳನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',
  L10nKeys.screenQ15: 'ಬಹು-ಹಂತದ ಚಟುವಟಿಕೆಗಳನ್ನು ಮಾಡಲು ಅವರಿಗೆ ತೊಂದರೆ ಇದೆಯೇ?',

  L10nKeys.careDashboardSubtitle: 'ಕುಟುಂಬದ ಆರೈಕೆ',
  L10nKeys.careSosLive: 'ಲೈವ್ ಎಚ್ಚರಿಕೆ',
  L10nKeys.careSosRespondedBy: '{name} ಪ್ರತಿಕ್ರಿಯಿಸಿದ್ದಾರೆ',
  L10nKeys.careLinkTitle: 'ಕುಟುಂಬ ಸದಸ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
  L10nKeys.careLinkBody: 'ನಿಮ್ಮ ಪ್ರೀತಿಪಾತ್ರರ ಫೋನ್ನಲ್ಲಿ ತೋರಿಸುವ 6-ಅಕ್ಷರದ ಕುಟುಂಬ ಕೋಡ್ ಅನ್ನು ಕೇಳಿ, ನಂತರ ಸಂಪರ್ಕಿಸಿ.',
  L10nKeys.careLinkCode: 'ಕುಟುಂಬ ಕೋಡ್',
  L10nKeys.careLinkCodeHint: 'ಉದಾ. A1B2C3',
  L10nKeys.careLinkConnect: 'ಸಂಪರ್ಕಿಸಿ',
  L10nKeys.careLinkDone: 'ಸಂಪರ್ಕಿಸಿದೆ',
  L10nKeys.careLinkSuccess:
      '{name} ಜೊತೆ ಸಂಪರ್ಕಿಸಿದೆ! ನೆನಪುಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು ಈಗ ಸಿಂಕ್ ಆಗುತ್ತವೆ.',
  L10nKeys.careLinkFailed:
      'ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಕೋಡ್ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  L10nKeys.careTrendsTitle: 'AI ಪ್ರವಣತೆ',
  L10nKeys.careTrendsBody: 'ಚಟುವಟಿಕೆ ಪ್ರಕಾರದ ದೈನಂದಿನ ನಿಖರತೆ',
  L10nKeys.careTrendsNoData:
      'ಇನ್ನೂ ಯಾವುದೇ ಚಟುವಟಿಕೆ ಇಲ್ಲ — ಪ್ರವಣತೆ ನೋಡಲು ಒಂದು ವ್ಯಾಯಾಮ ಪೂರ್ಣಗೊಳಿಸಿ.',
  L10nKeys.careAiDifficulty: 'ಸ್ವಯಂ-ಸರಿಹೊಂದಿಸಿದ ಕಷ್ಟ',
  L10nKeys.careAiAccuracy: 'ಮಾದರಿ ನಿಖರತೆ',
  L10nKeys.careAiRealSessions: 'ನೈಜ ಸೆಶನ್ಗಳು',
  L10nKeys.careAiDemoSessions: 'ಡೆಮೊ ಸೆಶನ್ಗಳು',
  L10nKeys.careNavGames: 'ಆಟಗಳು',
  L10nKeys.careNavRoutine: 'ದಿನಚರಿ',
  L10nKeys.careGreetSubtitle: 'ಇಂದು {name} ಹೇಗಿದ್ದಾರೆ ಎಂಬುದು ಇಲ್ಲಿದೆ.',
  L10nKeys.careNotifEmpty: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
  L10nKeys.careWellnessScore: 'ಅರಿವಿನ ಕ್ಷೇಮ ಸ್ಕೋರ್',
  L10nKeys.careStatusStable: 'ಸ್ಥಿರ',
  L10nKeys.careStatusAttention: 'ಗಮನ ಅಗತ್ಯವಿದೆ',
  L10nKeys.careLastSynced: 'ಕೊನೆಯದಾಗಿ ಸಿಂಕ್ ಮಾಡಿದ್ದು {time}',
  L10nKeys.careMinAgo: '{n} ನಿಮಿಷದ ಹಿಂದೆ',
  L10nKeys.careGamesWeek: 'ಈ ವಾರದ ಆಟಗಳು',
  L10nKeys.careRoutineCompletion: 'ದಿನಚರಿ ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ',
  L10nKeys.careCurrentStreak: 'ಪ್ರಸ್ತುತ ಸತತ ದಿನಗಳ ಸರಣಿ',
  L10nKeys.careMoodCheckins: 'ಮನಸ್ಥಿತಿ ಚೆಕ್-ಇನ್ಗಳು',
  L10nKeys.careDayUnit: 'ದಿನ',
  L10nKeys.careDaysUnit: 'ದಿನಗಳು',
  L10nKeys.careActivityTitle: 'ಸಾಪ್ತಾಹಿಕ ಚಟುವಟಿಕೆ',
  L10nKeys.careWeekly: 'ಸಾಪ್ತಾಹಿಕ',
  L10nKeys.careMonthly: 'ಮಾಸಿಕ',
  L10nKeys.careNoActivityWeek: 'ಈ ವಾರ ಇನ್ನೂ ಯಾವುದೇ ಚಟುವಟಿಕೆ ದಾಖಲಾಗಿಲ್ಲ.',
  L10nKeys.careMoodTitle: 'ಮನಸ್ಥಿತಿ',
  L10nKeys.careMoodHappy: 'ಸಂತೋಷ',
  L10nKeys.careMoodCalm: 'ಶಾಂತ',
  L10nKeys.careMoodNeutral: 'ತಟಸ್ಥ',
  L10nKeys.careMoodLow: 'ಕಡಿಮೆ',
  L10nKeys.careMood7Days: 'ಕಳೆದ 7 ದಿನಗಳು',
  L10nKeys.careMoodInsight: '{name} ಈ ವಾರ ಹೆಚ್ಚಾಗಿ ಶಾಂತವಾಗಿದ್ದಾರೆ, ಕಳೆದ ಎರಡು ದಿನಗಳಲ್ಲಿ ಸ್ವಲ್ಪ ಇಳಿಕೆ ಕಂಡುಬಂದಿದೆ.',
  L10nKeys.careMoodNoData: 'ಈ ವಾರ ಇನ್ನೂ ಯಾವುದೇ ಮನಸ್ಥಿತಿ ಚೆಕ್-ಇನ್ಗಳಿಲ್ಲ.',
  L10nKeys.careSkillsTitle: 'ಅರಿವಿನ ಕೌಶಲ್ಯಗಳು',
  L10nKeys.careSkillMemory: 'ಸ್ಮರಣೆ',
  L10nKeys.careSkillAttention: 'ಗಮನ',
  L10nKeys.careSkillLanguage: 'ಭಾಷೆ',
  L10nKeys.careSkillReasoning: 'ತರ್ಕ',
  L10nKeys.careSkillProcessing: 'ಸಂಸ್ಕರಣಾ ವೇಗ',
  L10nKeys.careInsightToday: 'ಇಂದಿನ ಒಳನೋಟ',
  L10nKeys.careInsightBody: 'ರಾಬರ್ಟ್ ತಮ್ಮ ಬೆಳಿಗ್ಗಿನ ದಿನಚರಿಯ ನಂತರ ಸ್ಮರಣೆ ಚಟುವಟಿಕೆಗಳಲ್ಲಿ ಸ್ಥಿರವಾಗಿದ್ದಾರೆ. ಕಳೆದ ಎರಡು ದಿನಗಳಲ್ಲಿ ಅವರ ಮನಸ್ಥಿತಿ ಸ್ವಲ್ಪ ಕಡಿಮೆಯಾಗಿದೆ.',
  L10nKeys.careInsightBodyReal: 'ಈ ವಾರ {name} ಅವರು {count} ಅರಿವಿನ ಸೆಶನ್ಗಳನ್ನು (ಗುರಿ {goal}) ಪೂರ್ಣಗೊಳಿಸಿದ್ದಾರೆ ಮತ್ತು {streak}-ದಿನಗಳ ಸರಣಿಯನ್ನು ಮುಂದುವರಿಸಿದ್ದಾರೆ.',
  L10nKeys.careViewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
  L10nKeys.careInsightDisclaimer:
      'ಇದು ಡೇಟಾದಿಂದ ಪಡೆದ ಒಂದು ನಮ್ರ ಅವಲೋಕನ — ಇದು ವೈದ್ಯಕೀಯ ರೋಗನಿದಾನವಲ್ಲ.',
  L10nKeys.careAttentionTitle: 'ನಿಮ್ಮ ಗಮನ ಅಗತ್ಯವಿದೆ',
  L10nKeys.careAttentionEmpty: 'ಇದೀಗ ನಿಮ್ಮ ಗಮನ ಬೇಕಾದ ಯಾವುದೂ ಇಲ್ಲ.',
  L10nKeys.careAlertSos: '{name} SOS ಗುಂಡಿಯನ್ನು ಒತ್ತಿದ್ದಾರೆ',
  L10nKeys.careAlertRoutineMissed: 'ನಿನ್ನೆ ದಿನಚರಿ ತಪ್ಪಿಹೋಗಿದೆ',
  L10nKeys.careAlertMoodDown: 'ಕಳೆದ ಎರಡು ದಿನಗಳಲ್ಲಿ ಮನಸ್ಥಿತಿ ಕಡಿಮೆಯಾಗಿದೆ',
  L10nKeys.careAlertSessionPending: 'ಇಂದು ಅರಿವಿನ ಸೆಶನ್ ಪೂರ್ಣಗೊಂಡಿಲ್ಲ',
  L10nKeys.careAlertSeverityHigh: 'ಹೆಚ್ಚು',
  L10nKeys.careAlertSeverityMedium: 'ಮಧ್ಯಮ',
  L10nKeys.careAlertSeverityLow: 'ಕಡಿಮೆ',
  L10nKeys.careWeeklySummary: 'ಸಾಪ್ತಾಹಿಕ ಸಾರಾಂಶ',
  L10nKeys.careSessionsCompleted: 'ಪೂರ್ಣಗೊಂಡ ಸೆಶನ್ಗಳು',
  L10nKeys.careAvgSessionDuration: 'ಸರಾಸರಿ ಸೆಶನ್ ಅವಧಿ',
  L10nKeys.careRoutineAdherence: 'ದಿನಚರಿ ಪಾಲನೆ',
  L10nKeys.careMoodTrend: 'ಮನಸ್ಥಿತಿ ಪ್ರವೃತ್ತಿ',
  L10nKeys.careMoodTrendSlightlyDown: 'ಸ್ವಲ್ಪ ಕಡಿಮೆ',
  L10nKeys.careMoodTrendStable: 'ಸ್ಥಿರ',
  L10nKeys.careMoodTrendUp: 'ಸುಧಾರಿಸುತ್ತಿದೆ',
  L10nKeys.careVsLastWeek: 'ಕಳೆದ ವಾರದ ವಿರುದ್ಧ',
  L10nKeys.careSyncedJustNow: 'ಈಗಷ್ಟೇ ಸಿಂಕ್ ಆಗಿದೆ',
  L10nKeys.careOfflineWaiting:
      'ಆಫ್ಲೈನ್ · ಸಿಂಕ್ ಆಗಲು ಕಾಯುತ್ತಿರುವ {count} ಚಟುವಟಿಕೆಗಳು',
  L10nKeys.careComingSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ',
  L10nKeys.careHomeSoon: '{name} ಅವರ ದಿನದ ತ್ವರಿತ ಅವಲೋಕನ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
  L10nKeys.careGamesSoon: 'ಆಟಗಳು ಮತ್ತು ಸೆಶನ್ ಇತಿಹಾಸ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
  L10nKeys.careRoutineSoon: 'ರೋಗಿಯ ದೈನಂದಿನ ದಿನಚರಿ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
  L10nKeys.careProfileSoon:
      'ಆರೈಕೆದಾರರ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್ಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
  L10nKeys.serverPairingTitle: 'ಕುಟುಂಬ ಕೋಡ್',
  L10nKeys.serverPairingBody: 'ಈ ಕೋಡ್ ಅನ್ನು ಆರೈಕೆದಾರರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ, ಆಗ ಅವರು ನಿಮ್ಮೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಬಹುದು.',
  L10nKeys.serverUnlinked: 'ಸರ್ವರ್ಗೆ ಸಂಪರ್ಕಿಸಿಲ್ಲ',
  L10nKeys.serverLinked: 'ಸರ್ವರ್ಗೆ ಸಂಪರ್ಕಿಸಲಾಗಿದೆ',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
  // Patient-home, memories, voice and calendar fallbacks (English source).
  L10nKeys.addFirstRoutine: 'ನಿಮ್ಮ ಮೊದಲ ದಿನಚರಿ ಸೇರಿಸಿ',
  L10nKeys.addMemoryTooltip: 'ನೆನಪು ಸೇರಿಸಿ',
  L10nKeys.addRoutine: 'ದಿನಚರಿ ಸೇರಿಸಿ',
  L10nKeys.addToMemory: 'ಈ ನೆನಪಿಗೆ ಸೇರಿಸಿ',
  L10nKeys.attachmentsAddedMany: '{count} ಲಗತ್ತುಗಳನ್ನು ಸೇರಿಸಲಾಗಿದೆ',
  L10nKeys.attachmentsAddedOne: '1 ಲಗತ್ತು ಸೇರಿಸಲಾಗಿದೆ',
  L10nKeys.careAchieveEngagement: '೧೦ ಗಂಟೆ ಆಟ',
  L10nKeys.careAchieveEngagementBody: 'ಒಟ್ಟಿಗೆ ಆಡಿದ ಒಟ್ಟು ೧೦ ಗಂಟೆ',
  L10nKeys.careAchieveFirstSteps: 'ಮೊದಲ ಹೆಜ್ಜೆಗಳು',
  L10nKeys.careAchieveFirstStepsBody: 'ರೋಗಿ ತಮ್ಮ ಮೊದಲ ಸೆಶನ್ ಪೂರ್ಣಗೊಳಿಸಿದ್ದಾರೆ',
  L10nKeys.careAchieveGarden: 'ಅರಳಿದ ತೋಟ',
  L10nKeys.careAchieveGardenBody: 'ನೆನಪುಗಳ ತೋಟದಲ್ಲಿ ೫ ಗಿಡಗಳನ್ನು ಬೆಳೆಸಿ',
  L10nKeys.careAchievePerfect: 'ಪರಿಪೂರ್ಣ ಸುತ್ತು',
  L10nKeys.careAchievePerfectBody: 'ಪರಿಪೂರ್ಣ ಅಂಕಗಳೊಂದಿಗೆ ಮುಗಿದ ಆಟ',
  L10nKeys.careAchieveSevenDay: 'ಒಟ್ಟಿಗೆ ಒಂದು ವಾರ',
  L10nKeys.careAchieveSevenDayBody: '೭ ವಿಭಿನ್ನ ದಿನಗಳಲ್ಲಿ ಸೆಶನ್',
  L10nKeys.categoryLabel: 'ವರ್ಗ',
  L10nKeys.createMemory: 'ನೆನಪು ರಚಿಸಿ',
  L10nKeys.deleteAction: 'ಅಳಿಸಿ',
  L10nKeys.deleteRoutineBody: 'ನಿಮ್ಮ ದಿನಚರಿಯಿಂದ "{title}" ತೆಗೆದುಹಾಕುವುದೇ?',
  L10nKeys.deleteRoutineTitle: 'ದಿನಚರಿ ಅಳಿಸುವುದೇ?',
  L10nKeys.deleteRoutineTooltip: 'ದಿನಚರಿ ಅಳಿಸಿ',
  L10nKeys.homeRoutineSubtitle: 'ನಿಮ್ಮ ದಿನಕ್ಕೊಂದು ಶಾಂತವಾದ ಸಣ್ಣ ಯೋಜನೆ.',
  L10nKeys.medicineKind: 'ಔಷಧ',
  L10nKeys.memoriesKindVideo: 'ವೀಡಿಯೊ',
  L10nKeys.memoriesSubtitle: 'ನಿಮ್ಮ ಮೆಚ್ಚಿನ ಕ್ಷಣಗಳನ್ನು ಹತ್ತಿರ ಇಟ್ಟುಕೊಳ್ಳಿ.',
  L10nKeys.memoryCaptionHint: 'ಏನಾಯಿತು? ಯಾರಿದ್ದರು? ಹೇಗಿತ್ತು ಅನಿಸಿದ್ದು?',
  L10nKeys.memoryCaptionLabel: 'ಈ ನೆನಪಿನ ಬಗ್ಗೆ ಏನಾದರೂ ಬರೆಯಿರಿ',
  L10nKeys.memoryComposeHint: 'ಶೀರ್ಷಿಕೆ, ಸ್ವಲ್ಪ ಪಠ್ಯ, ಮತ್ತು ನಿಮಗಿಷ್ಟವಾದಷ್ಟು ಫೋಟೋ, ವೀಡಿಯೊ ಅಥವಾ ಧ್ವನಿ ಟಿಪ್ಪಣಿಗಳನ್ನು ಸೇರಿಸಿ.',
  L10nKeys.memorySaved: 'ನೆನಪು ಉಳಿಸಲಾಗಿದೆ 💙',
  L10nKeys.memoryTitleHint: 'ಉದಾ. ನನ್ನ ಮಗಳ ಮದುವೆ',
  L10nKeys.memoryTitleLabel: 'ನೆನಪಿನ ಶೀರ್ಷಿಕೆ',
  L10nKeys.memoryTitleRequired: 'ದಯವಿಟ್ಟು ಈ ನೆನಪಿಗೆ ಒಂದು ಶೀರ್ಷಿಕೆ ನೀಡಿ.',
  L10nKeys.micVoicePermission: 'ಧ್ವನಿ ನೆನಪಿಗೆ ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
  L10nKeys.monthApr: 'ಏಪ್ರಿಲ್',
  L10nKeys.monthAug: 'ಆಗಸ್ಟ್',
  L10nKeys.monthDec: 'ಡಿಸೆಂಬರ್',
  L10nKeys.monthFeb: 'ಫೆಬ್ರವರಿ',
  L10nKeys.monthJan: 'ಜನವರಿ',
  L10nKeys.monthJul: 'ಜುಲೈ',
  L10nKeys.monthJun: 'ಜೂನ್',
  L10nKeys.monthMar: 'ಮಾರ್ಚ್',
  L10nKeys.monthMay: 'ಮೇ',
  L10nKeys.monthNov: 'ನವೆಂಬರ್',
  L10nKeys.monthOct: 'ಅಕ್ಟೋಬರ್',
  L10nKeys.monthSep: 'ಸೆಪ್ಟೆಂಬರ್',
  L10nKeys.photoAddFailed: 'ಈ ಫೋಟೋ ಸೇರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  L10nKeys.profileMissing: 'ರೋಗಿಯ ಪ್ರೊಫೈಲ್ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.',
  L10nKeys.recordingStartFailed: 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  L10nKeys.routineAddBody: 'ನಿಮ್ಮ ದಿನಕ್ಕೆ ಸರಳ ಜ್ಞಾಪನೆ ರಚಿಸಿ.',
  L10nKeys.routineAddTitle: 'ದಿನಚರಿ ಸೇರಿಸಿ',
  L10nKeys.routineCheckBody: 'ಒಳ್ಳೆಯ ದಿನಕ್ಕೆ ಸಣ್ಣ ಹೆಜ್ಜೆಗಳು',
  L10nKeys.routineCheckTitle: 'ದಿನಚರಿ ಪರಿಶೀಲನೆ',
  L10nKeys.routineKind: 'ದಿನಚರಿ',
  L10nKeys.routineNameHint: 'ಉದಾ. ನೀರು ಕುಡಿಯಿರಿ',
  L10nKeys.routineNameLabel: 'ದಿನಚರಿಯ ಹೆಸರು',
  L10nKeys.savedMemoriesTitle: 'ಉಳಿಸಿದ ನೆನಪುಗಳು',
  L10nKeys.saveMemory: 'ನೆನಪು ಉಳಿಸಿ',
  L10nKeys.settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
  L10nKeys.sosShort: 'SOS',
  L10nKeys.stop: 'ನಿಲ್ಲಿಸಿ',
  L10nKeys.stopVoiceFirst: 'ಮೊದಲು ಧ್ವನಿ ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ.',
  L10nKeys.textShort: 'ಪಠ್ಯ',
  L10nKeys.timeLabel: 'ಸಮಯ',
  L10nKeys.videoAddFailed: 'ಈ ವೀಡಿಯೊ ಸೇರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  L10nKeys.voiceSaveFailed: 'ಧ್ವನಿ ರೆಕಾರ್ಡಿಂಗ್ ಉಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
  L10nKeys.voiceShort: 'ಧ್ವನಿ',
  L10nKeys.waterKind: 'ನೀರು',
};
