import '../l10n_keys.dart';

/// Bodo dictionary — best-effort machine-assisted translation.
/// Untranslated keys automatically fall back to English at runtime.
/// Core food-market terms corroborated against xobdo.org / Glosbe.
/// Native-speaker review strongly recommended.
const Map<String, String> stringsBrx = {
  L10nKeys.appName: 'Companio',
  L10nKeys.tagline: 'बिनाय सानग्राफोरनि गाहाय',
  L10nKeys.back: 'ओनसाय',
  L10nKeys.next: 'बिसाय',
  L10nKeys.continueText: 'बिसायनो थाइ',
  L10nKeys.skip: 'बाद होर',
  L10nKeys.done: 'हामोबाय',
  L10nKeys.cancel: 'यायख',
  L10nKeys.yes: 'हांनाय',
  L10nKeys.no: 'ननाय',
  L10nKeys.save: 'सांखोनाय',
  L10nKeys.close: 'बिजाम',
  L10nKeys.retry: 'गोबोन जोनाब्लाय',
  L10nKeys.add: 'दावहायनाय',
  L10nKeys.edit: 'सोल',
  L10nKeys.remove: 'खाम',
  L10nKeys.search: 'थानाय',
  L10nKeys.today: 'दानि',
  L10nKeys.offline: 'आगु-आलि आखाइनान',
  L10nKeys.online: 'आगु-आलि',

  L10nKeys.goodMorning: 'सुप्रभात',
  L10nKeys.goodAfternoon: 'गोजान साहोसिम',
  L10nKeys.goodEvening: 'गोजान सिन्जा',
  L10nKeys.goodNight: 'गोजान होर',

  L10nKeys.navHome: 'गोजों',
  L10nKeys.navGarden: 'बारिखा',
  L10nKeys.navActivities: 'बेरायथि',
  L10nKeys.navMemories: 'सानग्रा',
  L10nKeys.navProfile: 'प्रोफाइल',
  L10nKeys.navMystery: 'दानिसिनि सानग्रा',

  L10nKeys.onboardingWelcomeTitle: 'नुनायनि सानग्राफोरनि एको गिसिम गाहाय',
  L10nKeys.onboardingWelcomeBody: 'माइंडकेयर एनईआर आगु-आलि नांगरैयै नो लिरगांनना, सायलगिनाय आरो हागोरिसोनि गोख्राहोनि थानोनि मदद खालामो।',
  L10nKeys.onboardingNameTitle: 'आंखो नोंनि खान’खौ मा बोई होर?',
  L10nKeys.onboardingNameHint: 'नुनायनि मुं',
  L10nKeys.onboardingRegionTitle: 'नुनायनि गोजों बबेआव थाया?',
  L10nKeys.onboardingRegionHint: 'नोदोम एबा गाम',
  L10nKeys.onboardingRegionList: 'गुवाहाटी, सिलचर, शिलांग, अगरतला, इंफाळ, आइझोल, इटानगर, कोहिमा, गंगटोक, डिब्रुगढ़, जोरहाट, नुनायनि नोदोम',
  L10nKeys.onboardingLanguageTitle: 'नोंनि गावखाय मा रावखौ जावथि?',
  L10nKeys.onboardingLanguageBody: 'नों बेखौ जेब्ला जायाब्ला सोलनाय जाबो।',
  L10nKeys.onboardingFamilyTitle: 'हागोरि सोर?',
  L10nKeys.onboardingFamilyBody: 'नुनायनि गिवदाफोरखौ दाव-हाय। आंखोबाथाव बिनी जोरोसा आरो बारखुनानि सानग्राखौ नोनो मुंनि बिलायांग।',
  L10nKeys.onboardingAddFamily: 'हागोरि-मिनि दावहायनाय',
  L10nKeys.onboardingEmergencyTitle: 'हायग्ति-नोनो आंखोब सोरखौ रांनो?',
  L10nKeys.onboardingEmergencyBody: 'SOS बेदोंनि नाफों-खालामब्लानो माइंडकेयर नुनायनि हागोरिनि लोरि होर, हायग्ति सेवाफोरनि लोरि नबा।',
  L10nKeys.onboardingEmergencyName: 'मुं',
  L10nKeys.onboardingEmergencyPhone: 'फोन नंबर',
  L10nKeys.onboardingEmergencyRelation: 'जाथाव (जिसान, रंदा…)',
  L10nKeys.onboardingDoneTitle: 'नुनायनि बारिखा साजाबो!',
  L10nKeys.onboardingDoneBody: 'जेथु बेरायथिखौ हामोनान नुनायनि बारिखा दालांगनि नो बेखेव। आंखोब नुनायसोनि जा।',
  L10nKeys.onboardingStart: 'आन’नि बारिखाखौ आरंभ खालाम',

  L10nKeys.homeWhatsGrowing: 'दानि मा दालां दा?',
  L10nKeys.homeTodayActivity: 'दानिसिनि जेथु बेरायथि',
  L10nKeys.homeActivityDuration: 'जानथिब्ला ३ मिनिट',
  L10nKeys.homeMinutes: 'मिनिट',
  L10nKeys.homeMemoryOfDay: 'दानिसिनि सानग्रा',
  L10nKeys.homeMemoryLocked: 'एको गिदिनसे सानग्रा नोंनि इयांआव था…',
  L10nKeys.homeMemoryUnlocked: 'एको सानग्रा खेवबाय!',
  L10nKeys.homeContinueActivity: 'बेरायथि बिसायनो थाइ',
  L10nKeys.homeFamilyMemory: 'नुनायनि हागोरिनिफ्राय',
  L10nKeys.homeFamilyMemoryEmpty: 'हागोरिनि सानग्राफोर बेजागायाव नोनो जाबो।',
  L10nKeys.homeSos: 'सहायखौ मोना',
  L10nKeys.homeSosSubtitle: 'हायग्ति-नोनो हागोरिनि जागा-जागा',
  L10nKeys.homeGardenPreview: 'नुनायनि बारिखा',
  L10nKeys.homeEngine: 'माइंडकेयर गाहाय',
  L10nKeys.homeEngineReady: 'नुनायनि मददगिरि साजाबो।',
  L10nKeys.homeWelcomeBack: 'फिननायनि गोजान! बारिखाखौ बिसायनो थां। 🌸',
  L10nKeys.homeNoActivity: 'दानि बेरायथि जागाय दा',
  L10nKeys.homeNoActivityBody:
      'गिसिम आराम ला — एबा गावखायनि बेरायथिखौ जेरेन। 🌻',

  L10nKeys.gardenTitle: 'आन’नि सानग्रानि बारिखा',
  L10nKeys.gardenSectionAll: 'आबसे',
  L10nKeys.gardenSectionFamily: 'हागोरि',
  L10nKeys.gardenSectionChildhood: 'अनसुग्रा सान',
  L10nKeys.gardenSectionPlaces: 'जागायथिफोर',
  L10nKeys.gardenSectionFestivals: 'हानजानि',
  L10nKeys.gardenEmpty: 'नुनायनि बारिखा आनो जानाय जानाय',
  L10nKeys.gardenEmptyBody:
      'आनो बेरायथिखौ हामो, बेजागायाव एको हाम बे-नाय जागोन।',
  L10nKeys.gardenPoints: 'फोर्थि',
  L10nKeys.gardenLevel: 'गेदेर',
  L10nKeys.gardenSeed: 'हाम',
  L10nKeys.gardenPlant: 'गिदि',
  L10nKeys.gardenFlower: 'आवदो',
  L10nKeys.gardenTree: 'बिडां',
  L10nKeys.gardenMilestone: 'गिदिनसे थाथा',
  L10nKeys.gardenGrowth: 'दालां दा',
  L10nKeys.gardenDidYouKnow:
      'हामाजाब्लाबो बेरायथिनि गोबाव नुनायनि बारिखा दालां दा।',
  L10nKeys.gardenPlantSeed: 'हाम बे',

  L10nKeys.activitiesTitle: 'बेरायथिफोर',
  L10nKeys.activitiesToday: 'दानि',
  L10nKeys.activitiesLibrary: 'गोबोन बेरायथिफोर',
  L10nKeys.mainGamesTitle: 'गाहाय खेल',
  L10nKeys.activitiesStart: 'आरंभ खालाम',
  L10nKeys.activitiesCompleted: 'हामो',
  L10nKeys.activitiesInProgress: 'थाखा-थाया',
  L10nKeys.activitiesNotStarted: 'आरंभ मोन',
  L10nKeys.activityYoureDone: 'गोजान!',
  L10nKeys.activityPraise: 'नों बारिखानो गिसिम जिन’नाय होदोंनाय। 🌱',
  L10nKeys.activityHint: 'आस दिनाय खालामा?',
  L10nKeys.activityTryAgain: 'थेखाइ बे सानग्राखौ नोहोरोन नो',
  L10nKeys.activityOptionsHint: 'नुनायनि जाबायखौ जेरेन',
  L10nKeys.activityTapToMatch: 'गाखो-गाखो जाथाखौ जेरेन',
  L10nKeys.activityNext: 'बिसाय',
  L10nKeys.activityFinish: 'हामो',
  L10nKeys.activityGroupLetsAgain: 'थेखाइ बेखौ नोहोरोन नो',
  L10nKeys.activityGroupTogether: 'थेखाइ बेखौ गोजिनायनो खालाम',
  L10nKeys.activityGreatJob: 'गोजान खालामो!',
  L10nKeys.activityKitchen: 'आन’नि सालाइ',
  L10nKeys.activityShopping: 'आन’नि बे’खाथ्रि',
  L10nKeys.activityMatching: 'जाथा-खाम',
  L10nKeys.activitySequence: 'सिनि सिनि लुख',
  L10nKeys.activityRecognition: 'बे मा?',
  L10nKeys.activityAssociation: 'मा जाथा जा?',
  L10nKeys.activityRecall: 'आव होदों दा?',
  L10nKeys.activityAttention: 'थान',
  L10nKeys.activityDurationSuffix: 'मिनिट',
  L10nKeys.activityTodayDone: 'दानिसिनि बेरायथि हामोबाय',
  L10nKeys.activityTodayDoneBody:
      'नुनायनि बारिखा दालांगबाय। साफलो एको सानग्रा इयां करिखाबो।',
  L10nKeys.activityGardenGrew: 'नुनायनि बारिखा दालांगबाय!',
  L10nKeys.activityMemoryUnlocked: 'एको सानग्रा खेवबाय',
  L10nKeys.activityReadAloud: 'दाफिन-दाफिन सोलनान नो',

  L10nKeys.kitchenTitle: 'सामारि खालाम',
  L10nKeys.kitchenMakeChai: 'चा खालामनाय',
  L10nKeys.kitchenMakeChaiPrompt: 'दिननाय-फोरखौ गोजान सिनियै जेरेन।',
  L10nKeys.kitchenSteps: 'दिननाय',
  L10nKeys.kitchenTapInOrder: 'दिननाय-फोरखौ गोजान सिनियै जेरेन',
  L10nKeys.kitchenCorrectOrder: 'गोजान! चा साजाबो!',
  L10nKeys.kitchenBreakfast: 'आखा-गाजिर खालामनाय',
  L10nKeys.kitchenBreakfastHint: 'दिननि सैफान-साफान नानसे',
  L10nKeys.kitchenBreakfastPrompt: 'आखा-गाजिरनि दिननाय-फोरखौ सिनियै लुख।',

  L10nKeys.shopTitle: 'आन’नि बेखाथ्रि',
  L10nKeys.shopGetMilkBread: 'ब्रेड आरो गाइखेर',
  L10nKeys.shopGetMilkBreadPrompt: '₹१०० आव गाइखेर आरो ब्रेड बेलाय।',
  L10nKeys.shopBudget: 'बजेट',
  L10nKeys.shopBasket: 'नुनायनि सुखा',
  L10nKeys.shopTotal: 'खालां',
  L10nKeys.shopWithinBudget: 'बजेटनि खोंथायाव!',
  L10nKeys.shopOverBudget: 'बजेटनि जाखाय जायगोन — नोहोरोन नो',
  L10nKeys.shopCheckout: 'हामोनान फि सौलाय',
  L10nKeys.shopBuy: 'सुखायाव होर',
  L10nKeys.shopSell: 'बाद होर',
  L10nKeys.shopVeggies: 'होरखा-आबारिनि बाबारि',
  L10nKeys.shopVeggiesPrompt: '₹६० आव आलु आरो सामब्राम बेलाय।',
  L10nKeys.recKitchenItem: 'बे मा?',
  L10nKeys.recKitchenItemPrompt:
      'बेखाथ्रिनिफ्राय बाबारि होनथोनो सोराब जा जायो?',
  L10nKeys.recCurrency: 'गिसिम फां',
  L10nKeys.recCurrencyPrompt: 'बबे नोटा ₹२०?',
  L10nKeys.matchFestival: 'हानजानि जाथा-खाम',
  L10nKeys.matchFestivalPrompt:
      'हामा हानजानिखौ बिनि गिदिनसे आखानाय-आबारि जाथा होर।',
  L10nKeys.matchObjectUse: 'जाथा-खाम',
  L10nKeys.matchObjectUsePrompt: 'हामा गिन्जिनखौ बेबलायखियै समि जाथा होर।',
  L10nKeys.seqMorning: 'सुबुरनि बेरायथि',
  L10nKeys.seqMorningPrompt: 'नुनायनि सुबुरनि बेरायथिखौ सिनियै लुख।',
  L10nKeys.seqRoute: 'सुबुरनि जात्रा',
  L10nKeys.seqRoutePrompt: 'बेखाथ्रि थाबायनो जात्राखौ सिनियै लुख।',
  L10nKeys.assoRegion: 'बेजागायाव मा दो?',
  L10nKeys.assoRegionPrompt: 'आसाम मा नाफ्रानि गिदिनसि मिथिया?',
  L10nKeys.assoHarvest: 'मेहाम थैथों',
  L10nKeys.assoHarvestPrompt: 'बबे थैथोंनिखौ दलानि राजा बा ही?',
  L10nKeys.attnVeg: 'गाजर थान',
  L10nKeys.attnVegPrompt: 'नों गाजर लायसायनाब्लाय दा?',
  L10nKeys.recallSong: 'एको मिथिगिरि सेरा',
  L10nKeys.recallSongPrompt:
      'बिहुआव मिनिनि नैंनानि बेरायखियै बबे सेरा बा जायो?',
  L10nKeys.activityPairs: 'जोराइ खानाय',
  L10nKeys.activitySequenceRecall: 'सालिआव गुसुननाय',
  L10nKeys.activityFindChanged: 'माखो बोदलायबा?',
  L10nKeys.pairsFruits: 'बाजारनि फोरै',
  L10nKeys.pairsKitchen: 'जुजुनानि सामान',
  L10nKeys.pairsRemember: 'जाबो कार्डखौ गोरबोनो नाय, बादी जोराइ खा।',
  L10nKeys.pairsStart: 'कार्डखौ आयोबायहो आरो जागा',
  L10nKeys.pairsFound: 'जोराइ गोखोनबा!',
  L10nKeys.seqRecallItems: 'माफुंनि सामान',
  L10nKeys.seqRecallNumbers: 'सालिआव अंखा',
  L10nKeys.seqRecallWatch: 'कार्डखौ गोरबोनो नाय – बादि बादि सावनाय खालाम।',
  L10nKeys.seqRecallRepeat: 'दाना उथुङाव नायग्रासे बादे सालिआव कार्डखौ दोन।',
  L10nKeys.changeMarket: 'फोरैनि जुदा',
  L10nKeys.changeFestival: 'जाथारनि श बा लायार',
  L10nKeys.changeRemember: 'बे फिनशिंखौ गुसुंनो होखर।',
  L10nKeys.changeFind: 'बेसे फिनशिं बोदलाय, बिबादिं फिनशिंखौ खा।',
  L10nKeys.changeCorrect: 'निरबाय! बियासें बोदलायबा।',

  L10nKeys.mysteryTitle: 'दानिसिनि गिदिनसे सानग्रा',
  L10nKeys.mysteryLocked: 'एको गिदिनसे सानग्रा नोंनि इयांआव था…',
  L10nKeys.mysteryLockedBody:
      'दानि २–३ जेथु बेरायथि खालाम; अनगौ खेवनाय जाबो। मा जागोन?',
  L10nKeys.mysteryUnlocked: 'नुनायनि गिदिनसे सानग्रा बेजागायाव दो!',
  L10nKeys.mysteryUnlockedBody: 'बे सानग्रा नोंनि थाखोननो। नुनायनि सम ला। 🌸',
  L10nKeys.mysteryCuriosity: 'दानि मा खेवगोन?',
  L10nKeys.mysteryOpen: 'सानग्रा खे',

  L10nKeys.memoriesTitle: 'आन’नि सानग्रा',
  L10nKeys.memoriesEmpty: 'आनो सानग्रा जागाय दा',
  L10nKeys.memoriesEmptyBody: 'नुनायनि हागोरि जोरोसा आरो बारखुनानि दखाफोर दाव-हायनाय जाबो। मोननान नो जागा नोबो।',
  L10nKeys.memoriesFamily: 'हागोरि',
  L10nKeys.memoriesPlaces: 'जागायथिफोर',
  L10nKeys.memoriesFestivals: 'हानजानि',
  L10nKeys.memoriesChildhood: 'अनसुग्रा सान',
  L10nKeys.memoriesKindPhoto: 'रेवाफो',
  L10nKeys.memoriesKindVoice: 'बारखुनानि दखा',
  L10nKeys.memoriesKindText: 'आखाना',
  L10nKeys.memoriesKindSound: 'खुद',
  L10nKeys.memoriesKindPlace: 'जागाय',
  L10nKeys.memoriesAddedBy: 'दाव-हायो',
  L10nKeys.memoriesWhoIsThis: 'बेर सोर?',
  L10nKeys.memoriesPlayVoice: 'मेनो',
  L10nKeys.memoriesThisIsMe: 'बेबा आं',
  L10nKeys.memoriesNotMe: 'आं ना',

  L10nKeys.profileTitle: 'प्रोफाइल',
  L10nKeys.profileLanguage: 'एपनि राव',
  L10nKeys.profileRegion: 'आन’नि जागाय',
  L10nKeys.profileVoiceLanguage: 'बारखुनानि राव',
  L10nKeys.profileVoicePrompts: 'बारखुनानि आस-फोर',
  L10nKeys.profileTextSize: 'आखानानि साइज',
  L10nKeys.profileReducedMotion: 'गिसिम थानाय',
  L10nKeys.profileSoundEffects: 'खुदनि प्रभाव',
  L10nKeys.profileFamily: 'हागोरि',
  L10nKeys.profileContacts: 'हायग्तिनि जायखा-फोर',
  L10nKeys.profileDemoMode: 'डेमो मोड',
  L10nKeys.profileReminders: 'सोलनाय-आव-फान्नाय',
  L10nKeys.profileNeedHelp: 'मदद मोनाखौ मा?',

  L10nKeys.remindersTitle: 'सोलनाय-आव-फान्नाय',
  L10nKeys.remindersEmpty: 'आनो सोलनाय-आव-फान्नाय जागाय दा',
  L10nKeys.remindersNew: 'गोदान सोलनाय-आव-फान्नाय',
  L10nKeys.remindersTitleLabel: 'मुंनि',
  L10nKeys.remindersDetailLabel: 'बिनोद (आवसे)',
  L10nKeys.remindersTime: 'सम',
  L10nKeys.remindersDays: 'सान',
  L10nKeys.remindersEveryday: 'सान-सान',
  L10nKeys.remindersEnabled: 'जागा',
  L10nKeys.remindersMedicine: 'आखाइ',
  L10nKeys.remindersAppointment: 'मिगां-मोननाय',
  L10nKeys.remindersRoutine: 'देटानि बेरायथि',

  L10nKeys.dayMon: 'सोम',
  L10nKeys.dayTue: 'मंगल',
  L10nKeys.dayWed: 'बुध',
  L10nKeys.dayThu: 'बिहा',
  L10nKeys.dayFri: 'शुक्र',
  L10nKeys.daySat: 'शनि',
  L10nKeys.daySun: 'रबि',

  L10nKeys.sosTitle: 'हायग्ति-नोनि सहाय',
  L10nKeys.sosExplain: 'नाफों-नाफों दोनान जागा हो। माइंडकेयर नुनायनि हायग्ति जायखा-फोरनिफ्राय बुलु-बुलु लोरि होरगोन। बे हायग्ति सेवा (११२ नोनां) ना।',
  L10nKeys.sosHold: 'सहाय नांगिया बा नाफों-नाफों दोन',
  L10nKeys.sosHoldBody: 'नाफों-नाफों दोनान…',
  L10nKeys.sosActiveTitle: 'सहायनि जागा-जागा होनाय हो दा',
  L10nKeys.sosActiveBody: 'नुनायनि हागोरि लोरि होयबाय। बिनियै जाबाय नोनांब्ला बिसायनि जायख। सोदोंगोन।',
  L10nKeys.sosContacting: 'जागा-जागा होय दा',
  L10nKeys.sosContactFamily: 'हागोरिनि जागा-जागा',
  L10nKeys.sosContacted: 'जागायबाय',
  L10nKeys.sosWaitingResponse: 'जाबायनि इयां…',
  L10nKeys.sosEscalating: 'बिसायनि मानसि जागा…',
  L10nKeys.sosCancelled: 'सहायनि अनखियाय बाद होयबाय',
  L10nKeys.sosCancelAction: 'सहायनि अनखियाय बाद होर',
  L10nKeys.sosDone: 'हामोबाय',
  L10nKeys.sosHelpOnWay: 'सोरबो दालां बा जागाय थाबो। 🧡',
  L10nKeys.sosNoContacts: 'आनो हायग्ति जायखा जागाय दा',
  L10nKeys.sosNoContactsBody: 'अनथाइ हागोरिनि जायखा-फोरखौ दाव-हायनान होर।',
  L10nKeys.sosAddContact: 'जायखा दाव-हाय',
  L10nKeys.sosDisclaimer: 'माइंडकेयर नोंनि जेरेनसिनि जायखा-फोरखौ लोरि होर। बे आखौथाइसिनि हायग्ति सेवानि बादला ना।',
  L10nKeys.sosContactedPerson: 'हागोरि-मिनिनि जागा होयबाय',
  L10nKeys.sosEscalatedTo: 'बिसायनि हागोरि-मिनिनि जागा होयबाय',
  L10nKeys.sosAcknowledged: 'हागोरि-मिनि जाबाय होदोंबाय। सहाय आव था।',
  L10nKeys.sosNotSilent: 'जोरि सहाय होय नांगेंना बा? जेब्ला गोजान सहाय होय जाबो, फोरों-फोरों होय-खांलां।',
  L10nKeys.sosAlertNotDelivered: 'नुनायनि दखा आनो होय-थाया दा। आंखो बेरायिया।',

  L10nKeys.careTitle: 'सेवा-गिरि',
  L10nKeys.careDashboard: 'नोयनि-आवसिनि',
  L10nKeys.carePatients: 'आन’नि बेमारि',
  L10nKeys.careMemories: 'सानग्रा',
  L10nKeys.careContacts: 'हायग्ति जायखा',
  L10nKeys.careSettings: 'सेटिंग',
  L10nKeys.careAddMemory: 'सानग्रा दाव-हाय',
  L10nKeys.careAddContact: 'जायखा दाव-हाय',
  L10nKeys.careEngagement: 'मुंदां-जागाय',
  L10nKeys.careActivitiesWeek: 'बे-सिप्तानि बेरायथि',
  L10nKeys.careGardenProgress: 'बारिखानि आगोन-फिन',
  L10nKeys.careRecentActivity: 'जायारि बेरायथि',
  L10nKeys.careNoPatients: 'बेमारि जागाय दा',
  L10nKeys.careNoPatientsBody:
      'हागोरि-मिनिनि जागा खालामनान होर, एबा बेमारिनि प्रोफाइल दाव-हाय।',
  L10nKeys.careAddPatient: 'बेमारि दाव-हाय',
  L10nKeys.carePerformanceNote:
      'जायारि बेनि बेरायथि बिनि देटानि गेदेरनिफ्राय गिसिम जाबाय जाया।',
  L10nKeys.careUploadPhoto: 'रेवाफो दाव-हाय',
  L10nKeys.careRecordVoice: 'बारखुनानि रेकर्ड खालाम',
  L10nKeys.careWriteMemory: 'सानग्रा सो',
  L10nKeys.careMemoryTitle: 'मुंनि',
  L10nKeys.careMemoryCaption: 'क्याप्सन',
  L10nKeys.careMemoryRelation: 'बेसोनो सोर-फोर दो? (जाथाव)',
  L10nKeys.careMemoryCategory: 'बाहागोरि',
  L10nKeys.careContactName: 'मुं',
  L10nKeys.careContactPhone: 'फोन नंबर',
  L10nKeys.careContactPriority: 'फोननि सिनि',
  L10nKeys.careContactRelation: 'जाथाव',
  L10nKeys.careEscalationTimeout: 'बिसायनि जायखा नांनायनि आगोसम मिनिट',
  L10nKeys.careIncidentStatus: 'स्थिति',
  L10nKeys.careAckSos: 'आं जाबाय होय दा',
  L10nKeys.careResponding: 'जाबाय होय जाया',
  L10nKeys.careActiveAlerts: 'जागा-नोनि अलर्ट',

  L10nKeys.syncSavingOffline: 'आगु-आलि आखाइनान',
  L10nKeys.syncSavingOfflineBody: 'नुनायनि बेरायथि बे डिवाइसाव सेफ दो।',
  L10nKeys.syncSynced: 'सिंक होयबाय',
  L10nKeys.syncInfo: 'नुनायनि खोबोर सिंक होयबाय।',
  L10nKeys.syncPending: 'सिंकनि इयां',

  L10nKeys.errorGeneric: 'माबो आलु जायगोन',
  L10nKeys.errorGenericBody: 'नुनायनि आगोन-फिन सेफ दो। अनथाइ जोनाब्लाय।',
  L10nKeys.errorAudio: 'बे डिवाइसाव खुद बाद-बायो ना।',
  L10nKeys.errorPermission: 'बेयोनि थाखो डिवाइसनि फुरानाय खामला।',
  L10nKeys.errorNoInternetAction:
      'आगु-आलि नांगैया ना — बे खोंथायनि जागायाव सेफ होयगोन।',

  L10nKeys.demoWelcome: 'डेमो नो',
  L10nKeys.demoExplain: 'नो लायनि थाखो नेमनि हागोरि आरो सानग्रा दाव-हायगोन।',
  L10nKeys.demoLoad: 'डेमो बारिखा सो-लाय',

  L10nKeys.unitsPoints: 'फोर्थि',
  L10nKeys.teaserChai: 'सामारि खालाम।',
  L10nKeys.familiarityName: 'आशा',
  L10nKeys.regionMap: 'आन’नि जागाय',
  L10nKeys.regionChoose: 'नुनायनि जागाय जेरेन',
  L10nKeys.regionIndia: 'भारत',
  L10nKeys.importantMemory: 'गाहाय सानग्रा',
  L10nKeys.growing: 'दालां दा',
  L10nKeys.blooming: 'जाव-खां दा',
  L10nKeys.mature: 'सुफुंग',
  L10nKeys.noVoice: 'बे डिवाइसाव बारखुनाय जागाय दा।',
  L10nKeys.optional: 'आवसे',

  L10nKeys.langChoose: 'राव जेरेन',
  L10nKeys.langPrimary: 'बाहायनि',
  L10nKeys.langNorthEast: 'उत्तर-पूर्व भारत',
  L10nKeys.langMajor: 'भारतनि गाहाय राव-फोर',
  L10nKeys.screenTitle: 'गाहाइयै सानखां जाँच',
  L10nKeys.screenIntro: 'आन बिमारनि सायाव गाहा सोंनायग्रो सोंनाय खालामगोन। बिसोरा फैसिन महरनि सायाव जोंथाइ खालाम।',
  L10nKeys.screenNotSure: 'नाथिनाय',
  L10nKeys.screenFinish: 'आनायनि फोरमानखौ नाय',
  L10nKeys.screenSkip: 'बेखौ थाजाय फुदा',
  L10nKeys.screenResultBack: 'खालाम जाबोदों',
  L10nKeys.screenCheckAgain: 'आरियो जाँच खालाम',
  L10nKeys.screenStartCheckup: 'जाँच आरम्भ खालाम',
  L10nKeys.screenSkipped: 'जाँचखौ बाद होन',
  L10nKeys.screenStatusGood: 'गासैबो मोननय जाथाव',
  L10nKeys.screenStatusGoodBody: 'मोनसे बाङा मोनदोंखौ नाङाया। गासे गासे सान काम खालामा जाथाव — महर बाहायनो होब्ला, जाँच आरो खालामनानै।',
  L10nKeys.screenStatusWatch: 'गुबुन महर बाहायनाय दं',
  L10nKeys.screenStatusWatchBody: 'सानखां बाहायनाय मोनसे मोनसे मोनथों दं। बेयो बेरनि सायाव सामान्य, जोंथाइ खालाम आरो बेसिरफिनि डाक्टरनि कन्थायाव होनो।',
  L10nKeys.screenStatusDoctor: 'जाँच खालामा बिनो',
  L10nKeys.screenStatusDoctorBody: 'सानखां बाहायनाय मोनसे मोनसे मोनथों दं, बेखौ मा जोंथाइ खालामा बिनो। बेखौ डाक्टर आरो क्लिनिक नि सायाव होननानै।',
  L10nKeys.screenRarely: 'रायगा',
  L10nKeys.screenSometimes: 'सान सान',
  L10nKeys.screenFrequently: 'गाहायो',
  L10nKeys.screenVeryFrequently: 'जाखोब्लाबां सान',
  L10nKeys.screenQ01:
      'बिमारि थांनाय गोरबै खोम्बायथियाब फैसिननि जोंथाइखौ नांगेनमा?',
  L10nKeys.screenQ02:
      'बिसोरा बे सोंनायग्रो आरो गोरकुनि जोंगायथि फिन खालामा ना?',
  L10nKeys.screenQ03: 'बिसोरा मिजि मानसिनि मुंखौ बुथियामोना?',
  L10nKeys.screenQ04: 'बिसोरा मिजि मुखायखौ नायथिजोंथि खालामा गोरबै दं ना?',
  L10nKeys.screenQ05: 'बिसोरा खालामा गोरबै आरो गोबां गोरकुनि महरखौ बुथियामोना?',
  L10nKeys.screenQ06: 'बिसोरा थुनो जाथाव बुंनि खोम्बायथियाब दं ना?',
  L10nKeys.screenQ07: 'बिसोरा बेथानि जायगायाव दं नि गेजेरे महरगबो बाहायोना?',
  L10nKeys.screenQ08: 'बिसोरा सानगदि खालामा खौ आबुथि रायखौ लागोना?',
  L10nKeys.screenQ09: 'बिसोरा दाखाइखौ खलियाई खालामा गोरबै दं ना?',
  L10nKeys.screenQ10: 'बिसोरा महरगबो होब्ला बानखानथि आरो रागासियोना?',
  L10nKeys.screenQ11:
      'बिसोरा मानसिनि बुंनिख्रुइ थाखियायफुनि बुथियाब गोरबै दं ना?',
  L10nKeys.screenQ12: 'बिसोरा मिजि खालामा गोरबैखौ बोदाय जाथाव खामोदों दं ना?',
  L10nKeys.screenQ13: 'बिसोरा सानगदि सामानखौ बेथानि बुथिया गोया दं ना?',
  L10nKeys.screenQ14: 'बिसोरा रायखौ बुथिया रखा गोरबै दं ना?',
  L10nKeys.screenQ15: 'बिसोरा गोजौनि गोरबै खालामा खौ बोदाय गोरबै दं ना?',

  L10nKeys.careDashboardSubtitle: 'Family care',
  L10nKeys.careSosLive: 'Live alert',
  L10nKeys.careSosRespondedBy: 'Responded by {name}',
  L10nKeys.careLinkTitle: 'Connect to a family member',
  L10nKeys.careLinkBody: 'Ask your loved one for the 6-letter family code shown on their phone, then connect.',
  L10nKeys.careLinkCode: 'Family code',
  L10nKeys.careLinkCodeHint: 'e.g. A1B2C3',
  L10nKeys.careLinkConnect: 'Connect',
  L10nKeys.careLinkDone: 'Connected',
  L10nKeys.careLinkSuccess:
      'Linked to {name}! Memories and alerts will now sync.',
  L10nKeys.careLinkFailed:
      'Could not connect. Please check the code and try again.',
  L10nKeys.careTrendsTitle: 'AI trends',
  L10nKeys.careTrendsBody: 'Daily accuracy by activity type',
  L10nKeys.careTrendsNoData:
      'No activity yet — complete an exercise to see trends.',
  L10nKeys.careAiDifficulty: 'Auto-tuned difficulty',
  L10nKeys.careAiAccuracy: 'Model accuracy',
  L10nKeys.careAiRealSessions: 'Real sessions',
  L10nKeys.careAiDemoSessions: 'Demo sessions',
  L10nKeys.careNavGames: 'खेल',
  L10nKeys.careNavRoutine: 'देटानि बेरायथि',
  L10nKeys.careGreetSubtitle: 'बेयो दानि {name} माबादि दं।',
  L10nKeys.careNotifEmpty: 'गोदान खोबोर जागाय दा',
  L10nKeys.careWellnessScore: 'सानखांगिरि खानालि स्कोर',
  L10nKeys.careStatusStable: 'स्थिर',
  L10nKeys.careStatusAttention: 'थान नांगो',
  L10nKeys.careLastSynced: '{time}आव सिंक होयबाय',
  L10nKeys.careMinAgo: '{n} मिनिट साबद',
  L10nKeys.careGamesWeek: 'बे-सिप्तानि खेल',
  L10nKeys.careRoutineCompletion: 'देटानि बेरायथि हामो',
  L10nKeys.careCurrentStreak: 'गोबाव सालि',
  L10nKeys.careMoodCheckins: 'मोनथि खिकाथाइ',
  L10nKeys.careDayUnit: 'सान',
  L10nKeys.careDaysUnit: 'सानफोर',
  L10nKeys.careActivityTitle: 'सिप्तानि बेरायथि',
  L10nKeys.careWeekly: 'सिप्तागिरि',
  L10nKeys.careMonthly: 'माखागिरि',
  L10nKeys.careNoActivityWeek: 'बे-सिप्तानि थाखो अबो बेरायथि जागाय दा।',
  L10nKeys.careMoodTitle: 'मोनथि',
  L10nKeys.careMoodHappy: 'गोजान',
  L10nKeys.careMoodCalm: 'गिसिम',
  L10nKeys.careMoodNeutral: 'सामान्य',
  L10nKeys.careMoodLow: 'खेव',
  L10nKeys.careMood7Days: 'फिसा ७ सान',
  L10nKeys.careMoodInsight: '{name} बे-सिप्ता बांसिन गिसिम दंखिन, थांखाबा नैखे साननि गेवमिनखौ खेव जानाय दं।',
  L10nKeys.careMoodNoData: 'बे-सिप्तानि थाखो अबो मोनथि खिकाथाइ जागाय दा।',
  L10nKeys.careSkillsTitle: 'सानखांगिरि खानाफोर',
  L10nKeys.careSkillMemory: 'सानग्रा',
  L10nKeys.careSkillAttention: 'थान',
  L10nKeys.careSkillLanguage: 'राव',
  L10nKeys.careSkillReasoning: 'बुथिनाय',
  L10nKeys.careSkillProcessing: 'खालामनायनि गोखेर',
  L10nKeys.careInsightToday: 'दानिसिनि मोननाय',
  L10nKeys.careInsightBody: 'रॉबर्ट बिनि सा-सुबुरनि देटानि बेरायथिनि उननि सानग्रा बेरायथिआव नांथेन खालामनि दंखिन। जायखाबा नैखे साननि बिनि मोनखाल खेव जानाय दं।',
  L10nKeys.careInsightBodyReal: 'बे-सिप्ता {name} गोबाव {count} सानखां बेरायथि (फराय {goal}) हामो, आरो {streak}-साननि सालि थाखाय दं।',
  L10nKeys.careViewDetails: 'नायखालाम',
  L10nKeys.careInsightDisclaimer:
      'बेयो खोबोरजोरा-अनिफ्राय गिसिमरै दिहुननाय — थेरा जाँचनि गोख्रा ना।',
  L10nKeys.careAttentionTitle: 'नोंनि थान नांगो',
  L10nKeys.careAttentionEmpty: 'गोबाव नोंनि थान नांगोना माबो दा।',
  L10nKeys.careAlertSos: '{name} SOS बेदोंखौ दोनबाय',
  L10nKeys.careAlertRoutineMissed: 'मैखू देटानि बेरायथि खालामा गैयाया दं',
  L10nKeys.careAlertMoodDown: 'थांखाबा नैखे साननि मोनखाल खेव जायगोन',
  L10nKeys.careAlertSessionPending: 'दानि सानखां बेरायथि हामो गैया',
  L10nKeys.careAlertSeverityHigh: 'गाहाय',
  L10nKeys.careAlertSeverityMedium: 'गैयासिन',
  L10nKeys.careAlertSeverityLow: 'खेव',
  L10nKeys.careWeeklySummary: 'सिप्तानि खोबोर',
  L10nKeys.careSessionsCompleted: 'सत्रफोर हामो',
  L10nKeys.careAvgSessionDuration: 'सत्रनि गारखान्थि सम',
  L10nKeys.careRoutineAdherence: 'देटानि बेरायथि जाथान्थि',
  L10nKeys.careMoodTrend: 'मोनखालनि बाहायनाय',
  L10nKeys.careMoodTrendSlightlyDown: 'देग्रा खेव',
  L10nKeys.careMoodTrendStable: 'स्थिर',
  L10nKeys.careMoodTrendUp: 'सुनाय',
  L10nKeys.careVsLastWeek: 'थांखाबा सिप्ताबादि',
  L10nKeys.careSyncedJustNow: 'बेंखनबा सिंक होयबाय',
  L10nKeys.careOfflineWaiting:
      'आगु-आलि आखाइनान · {count} बेरायथि सिंक होयनि इयां दं',
  L10nKeys.careComingSoon: 'आसोबै आखाङो',
  L10nKeys.careHomeSoon:
      '{name}नि दानिसिनि सानग्राफोरनि गिदिनसे नोयनि बेजागायाव नोयो।',
  L10nKeys.careGamesSoon: 'खेल आरो सत्रनि इतिहास बेजागायाव दिनो।',
  L10nKeys.careRoutineSoon: 'बेमारिनि देटानि बेरायथि बेजागायाव दिनो।',
  L10nKeys.careProfileSoon: 'सेवा-गिरिनि प्रोफाइल आरो सेटिंग बेजागायाव दिनो।',
  L10nKeys.serverPairingTitle: 'Family code',
  L10nKeys.serverPairingBody:
      'Share this code with a caregiver so they can connect to you.',
  L10nKeys.serverUnlinked: 'Not connected to server',
  L10nKeys.serverLinked: 'Connected to server',
  L10nKeys.authSignUpTitle: 'Create your account',
  L10nKeys.authSignUpBody: 'This Companio profile will stay safely on this device. Use a username and password so only you can open it.',
  L10nKeys.authLoginTitle: 'Welcome back',
  L10nKeys.authLoginBody:
      'Sign in with your username and password to open your garden.',
  L10nKeys.authUsername: 'Username',
  L10nKeys.authUsernameHint: 'e.g. ranu123',
  L10nKeys.authDisplayName: 'Your name',
  L10nKeys.authPassword: 'Password',
  L10nKeys.authPasswordHint: 'At least 6 characters',
  L10nKeys.authConfirmPassword: 'Confirm password',
  L10nKeys.authRoleQuestion: 'This profile is for…',
  L10nKeys.authRolePatient: 'Myself',
  L10nKeys.authRoleCaregiver: 'A family member',
  L10nKeys.authCreate: 'Create account',
  L10nKeys.authSignIn: 'Sign in',
  L10nKeys.authSignOut: 'Sign out',
  L10nKeys.authAccount: 'Account',
  L10nKeys.caregiverTitle: 'Caregiver',
  L10nKeys.caregiverNotLinked: 'No caregiver linked yet',
  L10nKeys.authBadCredentials: 'Incorrect username or password.',
  L10nKeys.authUsernameTaken: 'That username is already in use on this device.',
  L10nKeys.authPasswordMismatch: 'Passwords do not match.',
  L10nKeys.authUsernameShort: 'Username needs at least 3 characters.',
  L10nKeys.authUsernameInvalid:
      'Use only letters, numbers, dots, dashes or underscores.',
  L10nKeys.authPasswordShort: 'Password needs at least 6 characters.',
  L10nKeys.authNameRequired: 'Please enter a name.',
  L10nKeys.authSignOutConfirm: 'Sign out of this profile?',
  L10nKeys.navGames: 'Games',
  L10nKeys.homeWhatNeed: 'What would you like to do today?',
  L10nKeys.homeLetsPlayTitle: 'Let’s play a game',
  L10nKeys.homeLetsPlaySubtitle: 'A few gentle games — no hurry, no pressure. The garden loves every try. 🌱',
  L10nKeys.homePlayCta: 'Let’s play',
  L10nKeys.chooseGameTitle: 'Choose a game',
  L10nKeys.chooseGameSubtitle: 'Pick anything you like — there is no rush.',
  L10nKeys.gamesMoreTitle: 'More gentle activities',
  L10nKeys.gamePictureMatch: 'Picture Match',
  L10nKeys.gamePictureMatchDesc: 'Find the matching pair of cards',
  L10nKeys.gameRememberOrder: 'Remember the Order',
  L10nKeys.gameRememberOrderDesc: 'Watch the cards light up, then repeat them',
  L10nKeys.gameWordRecall: 'Word Recall',
  L10nKeys.gameWordRecallDesc: 'A gentle question about something familiar',
  L10nKeys.gameShapeMatch: 'Shape Match',
  L10nKeys.gameShapeMatchDesc: 'Match the things that belong together',
  L10nKeys.levelSelectTitle: 'Pick a level',
  L10nKeys.levelSelectSubtitle: 'Take your time — you decide the pace.',
  L10nKeys.levelTakeYourTime:
      'There is no time limit and no failing. Enjoy the round.',
  L10nKeys.levelEasy: 'Easy',
  L10nKeys.levelEasyDesc: 'A soft, unhurried round',
  L10nKeys.levelMedium: 'Medium',
  L10nKeys.levelMediumDesc: 'A comfortable pace',
  L10nKeys.levelHard: 'Hard',
  L10nKeys.levelHardDesc: 'A longer, careful round',
  L10nKeys.progressRecentActivity: 'Your recent days',
  L10nKeys.progressGamesPlayed: 'Games played',
  L10nKeys.progressBestStreak: 'Best streak',
  L10nKeys.progressStreakDays: '{n} days',
  L10nKeys.progressGamesThisWeek: '{n} games this week',
  L10nKeys.progressKeepGoing:
      'Keep going — your garden grows with every game. 🌱',
  L10nKeys.settingsComfortTitle: 'Comfort & reading',
  L10nKeys.settingsTextSize: 'Text size',
  L10nKeys.settingsTextSizeSmall: 'Small',
  L10nKeys.settingsTextSizeMedium: 'Medium',
  L10nKeys.settingsTextSizeLarge: 'Large',
  L10nKeys.settingsHighContrast: 'High contrast',
  L10nKeys.settingsHighContrastBody:
      'Stronger colours make everything easier to read.',
  L10nKeys.settingsHowToPlayBody: 'Every game has no fail — tap around, take your time, and the garden rewards every try.',

  L10nKeys.careBrandName: 'Mindful Days',
  L10nKeys.careBrandTagline: 'Play. Remember. Brighter Days.',
  L10nKeys.carePreviewBadge: 'Preview',
  L10nKeys.careGreetingMorning: 'Good morning, {name}',
  L10nKeys.careGreetingAfternoon: 'Good afternoon, {name}',
  L10nKeys.careGreetingEvening: 'Good evening, {name}',
  L10nKeys.careGreetingOk: 'How is {name} today?',
  L10nKeys.careHomeToday: 'Today at a glance',
  L10nKeys.careStatsGames: 'Games',
  L10nKeys.careStatsMinutes: 'Minutes',
  L10nKeys.careStatsAvgScore: 'Avg score',
  L10nKeys.careStatsStreak: 'Day streak',
  L10nKeys.careHomeToReview: 'To review',
  L10nKeys.careReviewWeeklyTitle: 'Weekly summary is ready',
  L10nKeys.careReviewWeeklyBody: 'A gentle review of this week\'s play.',
  L10nKeys.careReviewGardenTitle: 'Memory Garden is blooming',
  L10nKeys.careReviewGardenBody: 'Three new memories to water together.',
  L10nKeys.careReviewMilestoneTitle: 'New milestone reached',
  L10nKeys.careReviewMilestoneBody: 'Celebrate together today.',
  L10nKeys.careReviewMedicationTitle: 'Meditation session due',
  L10nKeys.careReviewMedicationBody:
      'A few minutes of calm keeps the day soft.',
  L10nKeys.careCtaReview: 'Review',
  L10nKeys.careCtaView: 'View',
  L10nKeys.careQuickActions: 'Quick actions',
  L10nKeys.careQuickMemories: 'Memories',
  L10nKeys.careQuickNotes: 'Notes',
  L10nKeys.careQuickAchievements: 'Achievements',
  L10nKeys.careQuickEmergency: 'Emergency',
  L10nKeys.careWeekHighlight: 'This week',
  L10nKeys.careWeekUp: '+{percent}% this week',
  L10nKeys.careWeekSessionsDone: '{count} sessions completed',
  L10nKeys.careSosLiveTitle: 'SOS alert — {name} needs you',
  L10nKeys.careSosLiveSubtitle: 'Raised a moment ago',
  L10nKeys.careSosOpen: 'Open',
  L10nKeys.careNoLinkedTitle: 'No patient linked yet',
  L10nKeys.careNoLinkedBody: 'Ask your family member for their pairing code to see their progress here.',
  L10nKeys.careLinkNow: 'Link now',
  L10nKeys.patient: 'patient',
  L10nKeys.careProgressTitle: 'Progress',
  L10nKeys.careMonth: 'Month',
  L10nKeys.careAllTime: 'All time',
  L10nKeys.careSeeAll: 'See all',
  L10nKeys.careTodayTitle: 'Today',
  L10nKeys.careThisWeek: 'This week',
  L10nKeys.careWeekMinutes: '{count} min',
  L10nKeys.careWeekCompletedCount: '{count} completed',
  L10nKeys.careStreakCount: '{count} day streak',
  L10nKeys.careWeekGoal: 'Goal {done} of {total}',
  L10nKeys.careImprovementLabel: '{percent}% better than last week',
  L10nKeys.careSkillStrengths: 'Skill strengths',
  L10nKeys.carePct: '{pct}%',
  L10nKeys.careRecentSessions: 'Recent sessions',
  L10nKeys.careSessionMeta: '{date} · {minutes} min',
  L10nKeys.careScoreLabel: 'Score',
  L10nKeys.careGamePerformance: 'Game performance',
  L10nKeys.carePlayedCount: '{count} plays',
  L10nKeys.careBestScore: 'Best',
  L10nKeys.careAvgScoreShort: 'Avg',
  L10nKeys.careLastPlayed: 'Last played {date}',
  L10nKeys.careNoDataTitle: 'No data yet',
  L10nKeys.careNoDataBody:
      'Once {name} finishes a few sessions, trends will appear here.',
  L10nKeys.careGamesEmptyTitle: 'No games yet',
  L10nKeys.careGamesEmptyBody: 'Suggest a session from the Games tab.',
  L10nKeys.careSessionsEmptyTitle: 'No sessions yet',
  L10nKeys.careGoToGames: 'Open games',
  L10nKeys.careGamesTitle: 'Games',
  L10nKeys.careGamesSubtitle: 'Play together, grow together',
  L10nKeys.careAllCategory: 'All',
  L10nKeys.careNotPlayedYet: 'Not played yet',
  L10nKeys.careGameTitle: 'Game',
  L10nKeys.careGameHowToPlay: 'How to play',
  L10nKeys.careGamePlayCountTitle: 'Games played',
  L10nKeys.careGameBestTitle: 'Best',
  L10nKeys.careGameAvgTitle: 'Avg score',
  L10nKeys.careGameMinsTitle: 'Avg time',
  L10nKeys.careGameMostActiveDay: 'Most active day',
  L10nKeys.careGameRecentRounds: 'Recent rounds',
  L10nKeys.careGameNoSessions: 'No sessions for this game yet.',
  L10nKeys.careCatMemory: 'Memory',
  L10nKeys.careCatAttention: 'Attention',
  L10nKeys.careCatLanguage: 'Language',
  L10nKeys.careCatProblemSolving: 'Problem solving',
  L10nKeys.careCatRecognition: 'Recognition',
  L10nKeys.careCatNarrative: 'Narrative',
  L10nKeys.careCatMath: 'Math',
  L10nKeys.careCatVisual: 'Visual',
  L10nKeys.careNotesTitle: 'Observation notes',
  L10nKeys.careNotesSubtitle: 'Little everyday moments, captured',
  L10nKeys.careAddNote: 'Add a note',
  L10nKeys.careNoteFilterAll: 'All',
  L10nKeys.careNoteKindGeneral: 'General',
  L10nKeys.careNoteKindMood: 'Mood',
  L10nKeys.careNoteKindActivities: 'Activities',
  L10nKeys.careNoteKindHealth: 'Health',
  L10nKeys.careNotesCount: '{count} notes',
  L10nKeys.careNotesEmptyTitle: 'No notes yet',
  L10nKeys.careNotesEmptyBody:
      'Capture a small observation today — a mood, an activity, a detail.',
  L10nKeys.careNoteDelete: 'Delete',
  L10nKeys.careNoteSaved: 'Note saved',
  L10nKeys.careNoteTitle: 'Add a note',
  L10nKeys.careNoteBodyHint: 'What happened today?',
  L10nKeys.careNoteKindLabel: 'Note type',
  L10nKeys.careMemoriesTitle: 'Memories',
  L10nKeys.careMemoriesSubtitle: 'Stories worth keeping',
  L10nKeys.careMemoriesEmptyTitle: 'No memories yet',
  L10nKeys.careMemoriesEmptyBody: 'Add a favourite story or photo — the patient will discover it in their garden, games and puzzles.',
  L10nKeys.careMemoryCategoryFamily: 'Family',
  L10nKeys.careMemoryCategoryChildhood: 'Childhood',
  L10nKeys.careMemoryCategoryPlaces: 'Places',
  L10nKeys.careMemoryCategoryFestivals: 'Festivals',
  L10nKeys.careMemoryCategoryImportant: 'Important',
  L10nKeys.careMemoryPlacementLabel: 'Unlocks in',
  L10nKeys.careMemoryPlacementGarden: 'Garden',
  L10nKeys.careMemoryPlacementMystery: 'Mystery memory',
  L10nKeys.careMemoryPlacementRescue: 'Memory rescue',
  L10nKeys.careMemoryPlacementPicture: 'Picture match',
  L10nKeys.careMemoryPlacementObjects: 'Familiar objects',
  L10nKeys.careMemoryAddTitle: 'Add a memory',
  L10nKeys.careMemoryTitleField: 'Title',
  L10nKeys.careMemoryCaptionField: 'Caption',
  L10nKeys.careMemoryPlaceField: 'Place (optional)',
  L10nKeys.careMemoryKindLabel: 'Type',
  L10nKeys.careMemoryKindText: 'Text',
  L10nKeys.careMemoryKindPhoto: 'Photo',
  L10nKeys.careMemoryKindVoice: 'Voice',
  L10nKeys.careMemoryKindSound: 'Sound',
  L10nKeys.careMemoryKindPlace: 'Place',
  L10nKeys.careMemoryPlacesLabel: 'Where will it appear?',
  L10nKeys.careMemorySaved: 'Memory added',
  L10nKeys.careMemoryCount: '{count} memories',
  L10nKeys.careAchieveTitle: 'Achievements',
  L10nKeys.careAchieveSubtitle: 'Milestones to celebrate together',
  L10nKeys.careAchieveUnlocked: 'Unlocked',
  L10nKeys.careAchieveInProgress: 'In progress',
  L10nKeys.careAchieveHowTitle: 'How milestones work',
  L10nKeys.careAchieveHowBody: 'Milestones build from everyday play. When one unlocks, an alert appears on the home screen — take a moment to celebrate together.',
  L10nKeys.careAchieveCount: '{count} milestones',
  L10nKeys.careProfileTitle: 'Profile',
  L10nKeys.careProfileAge: '{age} years',
  L10nKeys.careProfileRegion: 'Region',
  L10nKeys.careProfileLinked: 'Linked',
  L10nKeys.careProfileNotLinked: 'Not linked yet',
  L10nKeys.careProfileSyncNote:
      'Live progress syncs once a pairing code is linked.',
  L10nKeys.careProfileLinkButton: 'Link with a pairing code',
  L10nKeys.careProfilePairingTitle: 'Link a patient',
  L10nKeys.careProfilePairingHint:
      'Enter the 6-character code your family member shows.',
  L10nKeys.careProfilePairingPlaceholder: 'e.g. ABCD12',
  L10nKeys.careProfilePairingSuccess: 'Patient connected',
  L10nKeys.careProfilePairingError: 'Code not recognised. Check and try again.',
  L10nKeys.careProfileSosTitle: 'Emergency contacts',
  L10nKeys.careProfileContactsCount: '{count} contacts',
  L10nKeys.careProfileSettings: 'Settings',
  L10nKeys.careProfileCaregiverTitle: 'Caregiver account',
  L10nKeys.careProfileLogout: 'Log out',
  L10nKeys.careProfileLogoutConfirm: 'Log out of this caregiver account?',
  L10nKeys.careSettingsTitle: 'Settings',
  L10nKeys.careSettingsDisplay: 'Display',
  L10nKeys.careSettingsFontSize: 'Text size',
  L10nKeys.careSettingsFontSmall: 'Small',
  L10nKeys.careSettingsFontNormal: 'Normal',
  L10nKeys.careSettingsFontLarge: 'Large',
  L10nKeys.careSettingsHighContrast: 'High contrast',
  L10nKeys.careSettingsHighContrastBody: 'Stronger colours and clearer borders',
  L10nKeys.careSettingsNotifications: 'Notifications',
  L10nKeys.careSettingsReminders: 'Care reminders',
  L10nKeys.careSettingsRemindersBody: 'Daily check-in nudges',
  L10nKeys.careSettingsWeekly: 'Weekly report',
  L10nKeys.careSettingsWeeklyBody: 'A summary of the week\'s play',
  L10nKeys.careSettingsSosAlerts: 'Emergency alerts',
  L10nKeys.careSettingsSosAlertsBody: 'Alerts when an SOS is raised',
  L10nKeys.careSettingsAbout: 'About',
  L10nKeys.careSettingsAboutBody: 'Companio caregiver companion v1.0',
  L10nKeys.careEmergencyTitle: 'Emergency',
  L10nKeys.careEmergencySubtitle: 'Help that reaches fast',
  L10nKeys.careCallFamily: 'Call family / caregiver',
  L10nKeys.careCallFamilyBody: 'Primary contact',
  L10nKeys.careCallServices: 'Call emergency services',
  L10nKeys.careCallServicesBody: '112 in India',
  L10nKeys.careSmsFamily: 'Send SMS to family',
  L10nKeys.careSmsFamilyBody: 'Message all contacts',
  L10nKeys.careEmergencyLive: 'Live alert',
  L10nKeys.careEmergencyLiveBody: '{name} pressed SOS {time} ago',
  L10nKeys.careAcknowledge: 'Acknowledge',
  L10nKeys.careEscalate: 'Escalate',
  L10nKeys.careResolve: 'Mark resolved',
  L10nKeys.careAcknowledged: 'Acknowledged',
  L10nKeys.careEscalationLadder: 'Escalation ladder',
  L10nKeys.careStepCallPrimary: 'Call primary',
  L10nKeys.careStepSmsPrimary: 'SMS primary',
  L10nKeys.careStepCallFamily: 'Call family group',
  L10nKeys.carePrimaryContacts: 'Primary',
  L10nKeys.careFamilyContacts: 'Family',
  L10nKeys.careCallShort: 'Call',
  L10nKeys.careSmsShort: 'SMS',
  L10nKeys.careNoContactsTitle: 'No contacts yet',
  L10nKeys.careNoContactsBody: 'Add emergency contacts in the patient\'s profile so alerts can reach family fast.',
  L10nKeys.careHistory: 'Past alerts',
  L10nKeys.careHistoryEmpty: 'No past alerts',
  L10nKeys.careCancel: 'Cancel',
  L10nKeys.careByCaregiver: 'Added by caregiver',
  L10nKeys.careNavMore: 'More',
};
